
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_jm = {'_': ['jm_wallace-hadrill',
       'jm_productions',
       'jm_dematteis',
       'jm_robertson',
       'jm_lofficier',
       'jm_humphrey',
       'jm_kerrigan',
       'jm_marauder',
       'jm_ledgard',
       'jm_langtry',
       'jm_coetzee',
       'jm_whorton',
       'jm_johnson',
       'jm_yosures',
       'jm_howard',
       'jm_aitken',
       'jm_gordon',
       'jm_barrie',
       'jm_cloche',
       'jm_weston',
       'jm_keynes',
       'jm_snyder',
       'jm_eagle',
       'jm_gully',
       'jm_lexus',
       'jm_appel',
       'jm_synge',
       'jm_cohen',
       'jm_flagg',
       'jm_gates',
       'jm_lang',
       'jm_dent',
       'jm_kemp',
       'jm_wave',
       'jm_3100',
       'jm_ravi',
       'jm_hogg'],
 'a': ['jmak_equation'],
 'b': ['jmb_competition', 'jmbg_protests', 'jmb_racing', 'jmb_realty'],
 'c': ['jmc_communities',
       'jmc_landwind',
       'jmc_airlines',
       'jmc_bicycles',
       'jmc_yusheng',
       'jmc_academy',
       'jmc_teshun',
       'jmc_yuhu',
       'jmc_air'],
 'd': ['jmd_coey'],
 'e': ['jme_mctaggart', 'jme_editor'],
 'g': ['jmg_academy'],
 'i': ['jmi_records'],
 'j': ['jmj_fletcher', 'jmj_records'],
 'l': ['jml_direct'],
 'o': ['jmonkey_engine'],
 'r': ['jmr_parrondo'],
 's': ['jms_careless'],
 't': ['jmt_records'],
 'u': ['jmu_dukes'],
 'w': ['jmw_turner'],
 'y': ['jmy_records']}
