# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: th2_grpc_data_provider/queue_data_provider.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from th2_grpc_data_provider import data_provider_pb2 as th2__grpc__data__provider_dot_data__provider__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='th2_grpc_data_provider/queue_data_provider.proto',
  package='th2.data_provider',
  syntax='proto3',
  serialized_options=b'\n\"com.exactpro.th2.dataprovider.grpcP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n0th2_grpc_data_provider/queue_data_provider.proto\x12\x11th2.data_provider\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a*th2_grpc_data_provider/data_provider.proto\"\x9f\x02\n\x1fMessageGroupsQueueSearchRequest\x12\x33\n\x0fstart_timestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x31\n\rend_timestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12J\n\rmessage_group\x18\x03 \x03(\x0b\x32\x33.th2.data_provider.MessageGroupsSearchRequest.Group\x12\x30\n\rsync_interval\x18\x04 \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x16\n\x0e\x65xternal_queue\x18\x05 \x01(\t\"\xad\x01\n\x0fLoadedStatistic\x12:\n\x04stat\x18\x01 \x03(\x0b\x32,.th2.data_provider.LoadedStatistic.GroupStat\x1a^\n\tGroupStat\x12\x42\n\x05group\x18\x01 \x01(\x0b\x32\x33.th2.data_provider.MessageGroupsSearchRequest.Group\x12\r\n\x05\x63ount\x18\x02 \x01(\x04\x32\x85\x01\n\x14QueueProviderService\x12m\n\x13SearchMessageGroups\x12\x32.th2.data_provider.MessageGroupsQueueSearchRequest\x1a\".th2.data_provider.LoadedStatisticB&\n\"com.exactpro.th2.dataprovider.grpcP\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_duration__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,th2__grpc__data__provider_dot_data__provider__pb2.DESCRIPTOR,])




_MESSAGEGROUPSQUEUESEARCHREQUEST = _descriptor.Descriptor(
  name='MessageGroupsQueueSearchRequest',
  full_name='th2.data_provider.MessageGroupsQueueSearchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_timestamp', full_name='th2.data_provider.MessageGroupsQueueSearchRequest.start_timestamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_timestamp', full_name='th2.data_provider.MessageGroupsQueueSearchRequest.end_timestamp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message_group', full_name='th2.data_provider.MessageGroupsQueueSearchRequest.message_group', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sync_interval', full_name='th2.data_provider.MessageGroupsQueueSearchRequest.sync_interval', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='external_queue', full_name='th2.data_provider.MessageGroupsQueueSearchRequest.external_queue', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=181,
  serialized_end=468,
)


_LOADEDSTATISTIC_GROUPSTAT = _descriptor.Descriptor(
  name='GroupStat',
  full_name='th2.data_provider.LoadedStatistic.GroupStat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='group', full_name='th2.data_provider.LoadedStatistic.GroupStat.group', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='count', full_name='th2.data_provider.LoadedStatistic.GroupStat.count', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=550,
  serialized_end=644,
)

_LOADEDSTATISTIC = _descriptor.Descriptor(
  name='LoadedStatistic',
  full_name='th2.data_provider.LoadedStatistic',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stat', full_name='th2.data_provider.LoadedStatistic.stat', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_LOADEDSTATISTIC_GROUPSTAT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=471,
  serialized_end=644,
)

_MESSAGEGROUPSQUEUESEARCHREQUEST.fields_by_name['start_timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_MESSAGEGROUPSQUEUESEARCHREQUEST.fields_by_name['end_timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_MESSAGEGROUPSQUEUESEARCHREQUEST.fields_by_name['message_group'].message_type = th2__grpc__data__provider_dot_data__provider__pb2._MESSAGEGROUPSSEARCHREQUEST_GROUP
_MESSAGEGROUPSQUEUESEARCHREQUEST.fields_by_name['sync_interval'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_LOADEDSTATISTIC_GROUPSTAT.fields_by_name['group'].message_type = th2__grpc__data__provider_dot_data__provider__pb2._MESSAGEGROUPSSEARCHREQUEST_GROUP
_LOADEDSTATISTIC_GROUPSTAT.containing_type = _LOADEDSTATISTIC
_LOADEDSTATISTIC.fields_by_name['stat'].message_type = _LOADEDSTATISTIC_GROUPSTAT
DESCRIPTOR.message_types_by_name['MessageGroupsQueueSearchRequest'] = _MESSAGEGROUPSQUEUESEARCHREQUEST
DESCRIPTOR.message_types_by_name['LoadedStatistic'] = _LOADEDSTATISTIC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MessageGroupsQueueSearchRequest = _reflection.GeneratedProtocolMessageType('MessageGroupsQueueSearchRequest', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEGROUPSQUEUESEARCHREQUEST,
  '__module__' : 'th2_grpc_data_provider.queue_data_provider_pb2'
  # @@protoc_insertion_point(class_scope:th2.data_provider.MessageGroupsQueueSearchRequest)
  })
_sym_db.RegisterMessage(MessageGroupsQueueSearchRequest)

LoadedStatistic = _reflection.GeneratedProtocolMessageType('LoadedStatistic', (_message.Message,), {

  'GroupStat' : _reflection.GeneratedProtocolMessageType('GroupStat', (_message.Message,), {
    'DESCRIPTOR' : _LOADEDSTATISTIC_GROUPSTAT,
    '__module__' : 'th2_grpc_data_provider.queue_data_provider_pb2'
    # @@protoc_insertion_point(class_scope:th2.data_provider.LoadedStatistic.GroupStat)
    })
  ,
  'DESCRIPTOR' : _LOADEDSTATISTIC,
  '__module__' : 'th2_grpc_data_provider.queue_data_provider_pb2'
  # @@protoc_insertion_point(class_scope:th2.data_provider.LoadedStatistic)
  })
_sym_db.RegisterMessage(LoadedStatistic)
_sym_db.RegisterMessage(LoadedStatistic.GroupStat)


DESCRIPTOR._options = None

_QUEUEPROVIDERSERVICE = _descriptor.ServiceDescriptor(
  name='QueueProviderService',
  full_name='th2.data_provider.QueueProviderService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=647,
  serialized_end=780,
  methods=[
  _descriptor.MethodDescriptor(
    name='SearchMessageGroups',
    full_name='th2.data_provider.QueueProviderService.SearchMessageGroups',
    index=0,
    containing_service=None,
    input_type=_MESSAGEGROUPSQUEUESEARCHREQUEST,
    output_type=_LOADEDSTATISTIC,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_QUEUEPROVIDERSERVICE)

DESCRIPTOR.services_by_name['QueueProviderService'] = _QUEUEPROVIDERSERVICE

# @@protoc_insertion_point(module_scope)
