
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ez = {'_': ['ez-rocket',
       'ez2dancer',
       'ez-zerga',
       'ez-gimpy',
       'ez3kiel',
       'ez-park',
       'ez-link',
       'ez-poly',
       'ez-pass',
       'ez-103',
       'ez135',
       'ez430',
       'ez2dj',
       'ez-7',
       'ez-d',
       'ez80',
       'ez2'],
 'a': ['ezanville',
       'ezaart',
       'ezabad',
       'ezafeh',
       'ezana',
       'ezaki',
       'ezame',
       'ezafe',
       'ezair',
       'ezaro',
       'ezan',
       'eza'],
 'b': ['ezbakeya', 'ezbaran', 'ezboard', 'ezbaram', 'ezbob'],
 'c': ['ezchakuuta',
       'ezcabarte',
       'ezcater',
       'ezcaray',
       'ezcorp',
       'ezcema',
       'ezcast'],
 'd': ['ezdrummer'],
 'e': ['ezetimibe/atorvastatin',
       'ezetimibe/rosuvastatin',
       'ezetimibe/simvastatin',
       'ezebelamiri',
       'ezergailis',
       'ezengileer',
       'ezenwaanyi',
       'ezerkrasts',
       'ezetimibe',
       'ezellohar',
       'ezetaerre',
       'ezeriekai',
       'ezerinis',
       'ezequiel',
       'ezechiel',
       'ezeritai',
       'eze-igwe',
       'ezerelis',
       'ezemvelo',
       'ezenkosi',
       'ezequias',
       'ezechias',
       'ezetrol',
       'ezeqeel',
       'ezekial',
       'ezerovo',
       'ezevets',
       'ezekiel',
       'ezee-on',
       'ezernya',
       'ezerani',
       'ezekias',
       'ezerche',
       'ezeroto',
       'ezerets',
       'ezernet',
       'ezeleke',
       'ezekwe',
       'ezevel',
       'ezenwa',
       'ezeilo',
       'ezerjo',
       'ezeiza',
       'ezeagu',
       'ezeris',
       'ezell',
       'ezego',
       'ezek.',
       'ezem',
       'ezec',
       'ezel',
       'ezee',
       'eze.',
       'ezer',
       'ezeh',
       'ezek',
       'eze'],
 'f': ['ezf'],
 'g': ['ezgenerator', 'ezgeleh', 'ezgi'],
 'h': ['ezhamkadalinakkare',
       'ezhuthiyatharadi',
       'ezhumanthuruthu',
       'ezhuthapurangal',
       'ezhuvathiruthy',
       'ezhunnallathu',
       'ezharakoottam',
       'ezhuvanthala',
       'ezhumattoor',
       'ezhuthachan',
       'ezhakadavu',
       'ezhuthchan',
       'ezhamkulam',
       'ezhavathi',
       'ezhudesam',
       'ezhupunna',
       'ezhikkara',
       'ezhumalai',
       'ezhukone',
       'ezhimala',
       'ezhavars',
       'ezhantsy',
       'ezhavas',
       'ezhiyeh',
       'ezhumin',
       'ezhome',
       'ezhava',
       'ezhil',
       'ezhov',
       'ezhou',
       'ezhel',
       'ezh2',
       'ezh1',
       'ezha',
       'ezh'],
 'i': ['ezinihitte-mbaise',
       'ezion-gever',
       'ezion-geber',
       'ezichestvo',
       'eziongeber',
       'ezinihitte',
       'eziowelle',
       'ezibeleni',
       'ezinachi',
       'ezinkulu',
       'eziobodo',
       'ezidxan',
       'eziorsu',
       'ezitext',
       'eziran',
       'ezines',
       'ezinge',
       'ezinma',
       'eziama',
       'ezibuy',
       'ezidi',
       'ezili',
       'ezine',
       'ezira',
       'ezio',
       'ezi'],
 'k': ['ezkio-itsaso',
       'ezkerekotxa',
       'ezkioga',
       'ezkaton',
       'ezkurra',
       'ezkimo',
       'ezkio'],
 'l': ['ezlopitant', 'ezln'],
 'm': ['ezmareh', 'ezmol', 'ezmlm', 'ezma', 'ezmo'],
 'n': ['eznavigation', 'eznaveleh', 'eznabad', 'eznite', 'eznik', 'eznav'],
 'o': ['ezofficeinventory',
       'ezorongondo',
       'ezosciadium',
       'ezour-veda',
       'ezo-wakame',
       'ezourvedam',
       'ezogelin',
       'ezoloba',
       "ezo'la",
       'ezov',
       'ezop',
       'ezob',
       'ezo'],
 'p': ['ezpublish',
       'ezpeleta',
       'ezprogui',
       'ezproxy',
       'ezpass',
       'ezpay',
       'ezpl'],
 'q': ['ezquerro', 'ezquioga', 'ezq'],
 'r': ['ezra-nehemiah',
       'ezra-nama',
       'ezrocket',
       'ezrock',
       'ezrail',
       'ezride',
       'ezrin',
       'ezri',
       'ezr.',
       'ezra',
       'ezr'],
 's': ['ezsportsbook.com', 'ezstorage', 'ezs'],
 't': ['eztable', 'eztest', 'eztel', 'eztv'],
 'u': ['ezutromid', 'ezumeri', 'ezubao', 'ezuz'],
 'w': ['ezweb', 'ezw'],
 'y': ['ezy-sur-eure', 'ezydvd', 'ezycom', 'ezy'],
 'z': ['ezzedeen-al-qassam',
       'ezz-thetics',
       'ezzhiliga',
       'ezzatabad',
       'ezzaouite',
       'ezzahabad',
       'ezzouhour',
       'ezzolied',
       'ezzedine',
       'ezzelini',
       'ezzonids',
       'ezzelino',
       'ezzahra',
       'ezzonen',
       'ezzoud',
       'ezzell',
       'ezzat',
       'ezzo',
       'ezz']}
