
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_xu = {'xuan-zong': 'xuanzong',
 'xuande': 'xuande_emperor',
 'xuanhan': 'xuanhan_county',
 'xuanhuasaurus': 'xuanhuaceratops',
 'xuanqing': 'qiu_jin',
 'xuanshi': 'choi_kyu-hah',
 'xuantong': 'puyi',
 'xuantu': 'xuantu_commandery',
 'xuanwei': 'xuanwei_city',
 'xuanwumen': 'xuanwumen_station',
 'xuanxang': 'xuanzang',
 'xuanye': 'kangxi_emperor',
 'xuanzhi': 'xuan_paper',
 'xuanzhou': 'xuanzhou_district',
 'xuar': 'xinjiang',
 'xuberoa': 'soule',
 'xucuri': 'georgian_alphabet',
 'xudat': 'khudat',
 'xueberoa': 'soule',
 'xuepan': 'xue_pan',
 'xueta/translation': 'xueta',
 'xuetes': 'xueta',
 'xuetons': 'xueta',
 'xuexiao': 'school',
 'xufa': 'silla',
 'xuhs': 'cagayan_de_oro_city',
 'xuhui': 'xuhui_district',
 'xuite': 'suite',
 'xukuru': 'xucuru',
 'xul-solar': 'xul_solar',
 'xula': 'xavier_university_of_louisiana',
 'xulella': 'chulilla',
 'xulon': 'semantron',
 'xuluo': 'silla',
 'xuluofa': 'silla',
 'xumana': 'suma-jumano',
 'xuml': 'executable_uml',
 'xuna': 'silla',
 'xunafa': 'silla',
 'xunan': 'syngman_rhee',
 'xunantinich': 'xunantunich',
 'xundian': 'xundian_hui_and_yi_autonomous_county',
 'xungen': 'xungen_movement',
 'xunhua': 'xunhua_salar_autonomous_county',
 'xunminzhengyin': 'hunminjeongeum',
 'xunta': 'xunta_de_galicia',
 'xunwu': 'xunwu_county',
 'xunyi': 'xunyi_county',
 'xunzi': 'xun_zi',
 'xupiter.sqwire': 'xupiter',
 'xupn': 'xhdtv-tv',
 'xupn-tv': 'xhdtv-tv',
 'xusal': 'levocetirizine',
 'xushui': 'xushui_county',
 'xusui': 'east_asian_age_reckoning',
 'xutian': 'xu_tianlongzi',
 'xuye': 'silla',
 'xuyefa': 'silla',
 'xuyi': 'xuyi_county',
 'xuyong': 'xuyong_county'}
        