
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_xb = {'xb-1': 'huff-daland_xb-1',
 'xb-15': 'boeing_xb-15',
 'xb-16': 'martin_xb-16',
 'xb-17': 'b-17_flying_fortress',
 'xb-19': 'douglas_xb-19',
 'xb-21': 'north_american_xb-21',
 'xb-22': 'douglas_xb-22',
 'xb-27': 'martin_xb-27',
 'xb-28': 'north_american_xb-28',
 'xb-30': 'lockheed_xb-30',
 'xb-31': 'douglas_xb-31',
 'xb-33': 'xb-33_super_marauder',
 'xb-35': 'northrop_yb-35',
 'xb-38': 'xb-38_flying_fortress',
 'xb-39': 'xb-39_superfortress',
 'xb-40': 'yb-40_flying_fortress',
 'xb-41': 'xb-41_liberator',
 'xb-42': 'xb-42_mixmaster',
 'xb-44': 'xb-44_superfortress',
 'xb-45': 'b-45_tornado',
 'xb-46': 'convair_xb-46',
 'xb-48': 'martin_xb-48',
 'xb-49': 'northrop_yb-49',
 'xb-51': 'martin_xb-51',
 'xb-52': 'b-52_stratofortress',
 'xb-53': 'convair_xb-53',
 'xb-59': 'boeing_xb-59',
 'xb-60': 'convair_yb-60',
 'xb-68': 'martin_model_316',
 'xb-70': 'xb-70_valkyrie',
 'xb-8': 'fokker_xb-8',
 'xb17': 'b-17_flying_fortress',
 'xb360': 'xbox_360',
 'xbalanque': 'maya_hero_twins',
 'xbap': 'xaml_browser_applications',
 'xbbrowser': 'xerobank_browser',
 'xber': 'december',
 'xbhs': 'xaverian_brothers_high_school',
 'xbl2': 'xbl',
 'xbla': 'xbox_live_arcade',
 'xblive': 'xbox_live',
 'xblm': 'xbox_live_marketplace',
 'xbmp': 'xbox_media_player',
 'xbow': 'crossbow_technology',
 'xbox-360': 'xbox_360',
 'xbox-live': 'xbox_live',
 'xbox2': 'xbox_360',
 'xbox360': 'xbox_360',
 'xboxen': 'xbox',
 'xboxlive': 'xbox_live',
 'xboxmediacenter': 'xbmc',
 'xboxmediaplayer': 'xbox_media_player',
 'xbright': 'glossy_display',
 'xbrite': 'glossy_display',
 'xbss': 'xaverian_brothers',
 'xbtf': 'x:_beyond_the_frontier',
 'xbuntu': 'xubuntu',
 'xburst': 'lnx_code_8',
 'xbwd': 'british_west_indies_dollar'}
        