#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# AUTO-GENERATED CONTENT
d_stem_yn = {'yna': {'ynas': []},
             'ynagogu': {'ynagogue': ['ynagogues']},
             'ynagogue': ['ynagogues'],
             'ynamic': {'ynamical': [], 'ynamics': []},
             'ynar': {'ynars': []},
             'ynare': {'ynares': []},
             'ynasti': {'ynasties': [], 'ynasty': []},
             'ynca': {'yncas': []},
             'ynche': {'ynches': []},
             'ynchroniz': {'ynchronization': [], 'ynchronized': []},
             'ynchronou': {'ynchronous': []},
             'ynchu': {'ynchus': []},
             'ynciart': {'ynciarte': []},
             'ynconvenient': {'ynconvenientes': []},
             'yndia': {'yndias': []},
             'yndicat': {'yndicate': []},
             'yndio': {'yndios': []},
             'yndrome': {'yndromes': []},
             'yne': {'ynes': []},
             'ynea': {'yneas': []},
             'ynestrilla': {'ynestrillas': []},
             'ynew': {'ynewe': []},
             'ynfant': {'ynfante': []},
             'ynfiel': {'ynfieles': []},
             'ynfierno': {'ynfiernos': []},
             'ynform': {'ynforme': ['ynformes']},
             'ynforme': ['ynformes'],
             'yng': {'yngs': []},
             'ynga': {'yngas': []},
             'ynge': {'ynges': []},
             'yngelond': {'yngelonde': []},
             'yngenio': {'yngenios': []},
             'yngiti': {'yngitis': []},
             'yngland': {'ynglande': []},
             'yngle': {'yngles': []},
             'ynglese': {'yngleses': []},
             'yngli': {'ynglis': [], 'ynglys': []},
             'yngling': {'ynglinge': [], 'ynglings': []},
             'ynglingat': {'ynglingatal': []},
             'ynglond': {'ynglonde': []},
             'yngolog': {'yngology': []},
             'yngvar': {'yngvars': []},
             'yni': {'ynis': [], 'yny': ['ynys']},
             'ynit': {'ynits': []},
             'ynite': {'ynited': []},
             'yniti': {'ynity': []},
             'ynivers': {'yniversity': []},
             'ynkehorn': {'ynkehorne': []},
             'ynli': {'ynly': []},
             'ynn': {'ynns': []},
             'ynne': {'ynnes': []},
             'yno': {'ynos': []},
             'ynoat': {'ynoate': []},
             'ynocent': {'ynocente': []},
             'ynod': {'ynods': []},
             'ynogh': {'ynoghe': []},
             'ynojo': {'ynojos': []},
             'ynold': {'ynolds': []},
             'ynonym': {'ynonymous': [], 'ynonyms': []},
             'ynopsi': {'ynopsis': []},
             'ynou': {'ynous': []},
             'ynough': {'ynoughe': []},
             'ynow': {'ynowe': []},
             'ynr': {'ynrs': []},
             'ynrd': {'ynrds': []},
             'ynservanc': {'ynservancy': []},
             'ynsign': {'ynsigne': []},
             'ynstruccion': {'ynstrucciones': []},
             'ynstrumento': {'ynstrumentos': []},
             'ynte': {'yntes': []},
             'yntendent': {'yntendente': []},
             'ynteres': {'ynterese': ['yntereses']},
             'ynterese': ['yntereses'],
             'ynterna': {'ynternas': []},
             'ynterpret': {'ynterprete': []},
             'ynthesi': {'ynthesis': []},
             'ynthesiz': {'ynthesized': []},
             'ynwersiti': {'ynwersity': []},
             'yny': ['ynys'],
             'ynysla': {'ynyslas': []},
             'ynystaw': {'ynystawe': []}}
