#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# AUTO-GENERATED CONTENT
d_stem_yl = {'yla': {'ylas': []},
 'ylacet': {'ylacetate': [], 'ylacetic': []},
 'ylacton': {'ylactone': ['ylactones']},
 'ylactone': ['ylactones'],
 'ylalanin': {'ylalanine': []},
 'ylamin': {'ylamine': []},
 'ylan': {'ylans': []},
 'yland': {'ylande': ['ylandes'], 'ylands': []},
 'ylande': ['ylandes'],
 'ylangen': {'ylangene': []},
 'ylann': {'ylanne': []},
 'ylate': {'ylated': [], 'ylates': [], 'ylating': []},
 'ylcarbam': {'ylcarbamate': []},
 'ylcholin': {'ylcholine': []},
 'ylcker': {'ylckers': []},
 'yld': {'ylds': []},
 'yle': {'yles': []},
 'yledon': {'yledons': []},
 'yleft': {'ylefte': []},
 'yleisyy': {'yleisyys': []},
 'yleld': {'ylelded': [], 'ylelds': []},
 'ylesburi': {'ylesbury': []},
 'ylfing': {'ylfings': []},
 'ylha': {'ylhas': []},
 'yli': {'ylis': [], 'yly': []},
 'ylia': {'ylias': []},
 'ylich': {'yliche': []},
 'ylid': {'ylids': []},
 'ylide': {'ylides': []},
 'yliden': {'ylidene': []},
 'ylikanga': {'ylikangas': []},
 'ylinck': {'ylincked': []},
 'ylinder': {'ylinders': []},
 'ylindric': {'ylindrical': []},
 'yline': {'ylines': []},
 'ylink': {'ylinked': []},
 'ylinnes': {'ylinneses': []},
 'ylinolen': {'ylinolenic': []},
 'ylioppila': {'ylioppilas': []},
 'yll': {'ylls': []},
 'ylla': {'yllas': []},
 'yllabl': {'yllable': ['yllables']},
 'yllable': ['yllables'],
 'yllabu': {'yllabus': []},
 'yllane': {'yllanes': []},
 'ylle': {'ylles': []},
 'yllesca': {'yllescas': []},
 'ylli': {'yllis': [], 'ylly': []},
 'ylliad': {'ylliade': []},
 'yllness': {'yllnesse': []},
 'ylloco': {'yllocos': []},
 'ylnhniamshi': {'ylnhniamshy': []},
 'ylo': {'ylos': []},
 'ylocentrotu': {'ylocentrotus': []},
 'yloco': {'ylocos': []},
 'ylococc': {'ylococcal': []},
 'ylococcu': {'ylococcus': []},
 'yloid': {'yloides': []},
 'ylond': {'ylonde': []},
 'ylonian': {'ylonians': []},
 'ylori': {'ylory': []},
 'ylote': {'ylotes': []},
 'ylous': {'ylouses': []},
 'ylu': {'ylus': []},
 'ylum': {'ylums': []},
 'ylvisak': {'ylvisaker': []},
 'ylvo': {'ylvos': []},
 'ylych': {'ylyche': []}}
