
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_zs = {'zsam': 'xiamen_gaoqi_international_airport',
 'zsasz': 'victor_zsasz',
 'zsaz': 'victor_zsasz',
 'zscg': 'changzhou_benniu_airport',
 'zschetzsch': 'muldentalkreis',
 'zschokke': 'heinrich_zschokke',
 'zscore': 'standard_score',
 'zseries': 'ibm_system_z9',
 'zsgz': 'ganzhou_huangjin_airport',
 'zshare': 'file_hosting_service',
 'zshare.net': 'file_hosting_service',
 'zshc': 'hangzhou_xiaoshan_international_airport',
 'zshell': 'z_shell',
 'zshops': 'amazon.com',
 'zsibo': 'jibou',
 'zsigmond': 'sigismund',
 'zsja': 'jinggangshan_airport',
 'zsjd': 'jingdezhen_airport',
 'zsknight': 'zsnes',
 'zslg': 'lianyungang_baitabu_airport',
 'zslq': 'huangyan_luqiao_airport',
 'zsmp': 'polish_socialist_youth_union',
 'zsmu': 'zaporizhia_state_medical_university',
 'zsnb': 'ningbo_lishe_international_airport',
 'zsnhs': 'zamboanga_del_sur_national_high_school',
 'zsnj': 'nanjing_lukou_international_airport',
 'zsnt': 'nantong_airport',
 'zso-523': 'zso_523',
 'zsof': 'hefei_luogang_international_airport',
 'zsofi': 'sophie_evans',
 'zsoft': 'zsoft_corporation',
 'zsogodfurdo': 'miercurea_ciuc',
 'zsombolya': 'jimbolia',
 'zspace': 'z_communications',
 'zspd': 'shanghai_pudong_international_airport',
 'zsqd': 'qingdao_liuting_international_airport',
 'zsrs': 'ziegler_school_of_rabbinic_studies',
 'zstu': 'zhejiang_sci-tech_university',
 'zstx': 'huangshan_tunxi_international_airport',
 'zstylzhemgni': 'tsathoggua',
 'zsu-23': 'zsu-23-4',
 'zsu-23-2': 'zu-23-2',
 'zsu-23/4': 'zsu-23-4',
 'zsu-23x4': 'zsu-23-4',
 'zsu-24': 'zsu-23-4',
 'zsu23': 'zsu-23-4',
 'zswh': 'weihai_airport',
 'zswx': 'wuxi_shuofang_airport',
 'zswy': 'nanping_wuyishan_airport',
 'zswz': 'wenzhou_yongqiang_airport',
 'zsxz': 'xuzhou_airport',
 'zsyn': 'yancheng_airport',
 'zsyt': 'yantai_laishan_international_airport',
 'zszs': 'zhoushan_airport'}
        