
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_sb = {'_': ['sb-277,011-a',
       'sb-612,111',
       'sb-649,915',
       'sb-258585',
       'sb-357134',
       'sb-271046',
       'sb-215505',
       'sb-408124',
       'sb-366791',
       'sb-203580',
       'sb-204070',
       'sb-228357',
       'sb-236057',
       'sb-334867',
       'sb-200646',
       'sb-258719',
       'sb-243213',
       'sb-242084',
       'sb-699551',
       'sb-204741',
       'sb-649868',
       'sb-205384',
       'sb-216641',
       'sb-206553',
       'sb-399885',
       'sb-705498',
       'sb-431542',
       'sb-269970',
       'sb203580',
       'sb-pro',
       'sb-mvp',
       'sb2se3',
       'sb-800',
       'sb1394',
       'sb.tv',
       'sb2o4',
       'sb2o3',
       'sb420',
       'sb19',
       'sb-l',
       'sb20',
       'sb2u',
       'sb-2',
       'sb41',
       'sb2a',
       'sb2c',
       'sb16',
       'sb2',
       'sb1',
       'sb6'],
 'a': ['sbarcioara',
       'sbaraglia',
       'sbardella',
       'sbarbaro',
       'sbarabed',
       'sbaralea',
       'sbanken',
       'sbarros',
       'sbaitso',
       'sballen',
       'sbardun',
       'sbalbi',
       'sbarro',
       'sbaro',
       'sbata',
       'sbant',
       'sbach',
       'sbase',
       'sbai',
       'sbac',
       'sbaa',
       'sbap',
       'sbar',
       'sba'],
 'b': ['sbb-cff-ffs-vff',
       'sbb-cff-ffs',
       'sbbcollege',
       'sbbackup',
       'sbbod',
       'sbbos',
       'sbbr3',
       'sbbo',
       'sbbs',
       'sbb'],
 'c': ['sbcglobal.net',
       'sbcape',
       'sbcusd',
       'sbclo',
       'sbcl3',
       'sbcea',
       'sbcsc',
       'sbcl5',
       'sbc7',
       'sbcs',
       'sbca',
       'sbcv',
       'sbcc',
       'sbct',
       'sbcl',
       'sbcb',
       'sbc'],
 'd': ['sbd-3', 'sbds', 'sbd'],
 'e': ['sberkassa',
       'sberbank',
       'sbeitla',
       'sbectel',
       'sberna',
       'sbenu',
       'sbeta',
       'sbee',
       'sbec',
       'sber',
       'sbe'],
 'f': ['sbf5', 'sbf1', 'sbfz', 'sbfa', 'sbfc', 'sbf2', 'sbf3', 'sbf'],
 'g': ['sbgo', 'sbgs', 'sbgi', 'sbgt', 'sbg'],
 'h': ['sbh3', 'sbhk', 'sbhs', 'sbhc', 'sbh'],
 'i': ['sbitenshchik',
       'sbirs-high',
       'sbirs-low',
       'sbirro',
       'sbirri',
       'sbiten',
       'sbikha',
       'sbinet',
       'sbiba',
       'sbirs',
       'sbida',
       'sbisd',
       'sbisa',
       'sbih',
       'sbic',
       'sbin',
       'sbia',
       'sbid',
       'sbir',
       'sbi3',
       'sbig',
       'sbi'],
 'j': ['sbjd', 'sbj'],
 'k': ['sbkrs', 'sbk3', 'sbk'],
 'l': ['sblc', 'sbl'],
 'm': ['sbmerge.exe',
       'sbmnh',
       'sbms',
       'sbmc',
       'sbmp',
       'sbml',
       'sbmt',
       'sbma',
       'sbm'],
 'n': ['sbno2', 'sbnt', 'sbn'],
 'o': ['sbordoniella',
       'sboyevskaya',
       'sbobet.com',
       'sbolenfi',
       'sborgite',
       'sborino',
       'sbobet',
       'sbouya',
       'sborz',
       'sbonr',
       'sbot',
       'sbor',
       'sbox',
       'sbo2',
       'sbop',
       'sbod',
       'sboc',
       'sbo'],
 'p': ['sbp-tag', 'sbp-2', 'sbpl', 'sbp2', 'sbpv', 'sbpa', 'sbps', 'sbp'],
 'q': ['sbq'],
 'r': ['sbracciantizzazione',
       'sbrodovo',
       'sbragia',
       'sbrugby',
       'sbrinz',
       'sbrna',
       'sbrct',
       'sbrf',
       'sbrp',
       'sbri',
       'sbrk',
       'sbrj',
       'sbrr',
       'sbr'],
 's': ['sbstransit',
       'sbs-28',
       'sbscet',
       'sbs28',
       'sbsyo',
       'sbshc',
       'sbs-6',
       'sbsi',
       'sbso',
       'sbss',
       'sbst',
       'sbsd',
       'sbsj',
       'sbsa',
       'sbs1',
       'sbsh',
       'sbs9',
       'sbs6',
       'sbsk',
       'sbsp',
       'sbse',
       'sbs2',
       'sbs'],
 't': ['sbtvd-t',
       'sbtrkt',
       'sbtvd',
       'sbtv',
       'sbtb',
       'sbtn',
       'sbtc',
       'sbtk',
       'sbts',
       'sbt'],
 'u': ['sburatorul', 'sbuv/2', 'sbuks', 'sbus', 'sbux', 'sbu'],
 'v': ['sbvft', 'sbvc', 'sbvr', 'sbvt', 'sbv'],
 'w': ['sbwr', 'sbwc', 'sbw'],
 'x': ['sbxliii', 'sbxli', 'sbx-1', 'sbx'],
 'y': ['sby'],
 'z': ['sbz']}
