#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# AUTO-GENERATED CONTENT
d_stem_yd = {'ydar': {'ydars': []},
             'yday': {'ydays': []},
             'ydbi': {'ydby': []},
             'ydcata': {'ydcatas': []},
             'yddava': {'yddavas': []},
             'yde': {'ydes': []},
             'ydea': {'ydeas': []},
             'ydei': {'ydeis': []},
             'ydel': {'ydelness': []},
             'ydeli': {'ydely': []},
             'ydelli': {'ydelly': []},
             'ydeln': {'ydelnes': []},
             'ydelness': {'ydelnesse': []},
             'ydemptita': {'ydemptitas': []},
             'ydenstrick': {'ydenstricker': []},
             'ydepend': {'ydependent': []},
             'yderliger': {'yderligere': []},
             'yderst': {'yderste': []},
             'ydewal': {'ydewalle': []},
             'ydfgora': {'ydfgoras': []},
             'ydfio': {'ydfios': []},
             'ydga': {'ydgas': []},
             'ydgrunit': {'ydgrunites': []},
             'ydi': {'ydy': []},
             'ydide': {'ydides': []},
             'ydigora': {'ydigoras': []},
             'ydiln': {'ydilnes': []},
             'ydimens': {'ydimension': []},
             'ydiomat': {'ydiomate': []},
             'ydiot': {'ydiote': []},
             'ydirect': {'ydirection': ['ydirections']},
             'ydirection': ['ydirections'],
             'ydjana': {'ydjanas': []},
             'ydlene': {'ydlenes': []},
             'ydleness': {'ydlenesse': []},
             'ydlgora': {'ydlgoras': []},
             'ydli': {'ydlis': [], 'ydly': []},
             'ydna': {'ydnas': []},
             'ydo': {'ydos': []},
             'ydoe': {'ydoes': []},
             'ydoin': {'ydoine': []},
             'ydol': {'ydols': []},
             'ydolastr': {'ydolastre': []},
             'ydolatr': {'ydolatres': []},
             'ydolatra': {'ydolatras': []},
             'ydolatri': {'ydolatrie': [], 'ydolatry': []},
             'ydolatria': {'ydolatrias': []},
             'ydolatry': {'ydolatrye': []},
             'ydole': {'ydoles': []},
             'ydoli': {'ydolis': []},
             'ydoll': {'ydolles': []},
             'ydolo': {'ydolos': []},
             'ydone': {'ydonee': []},
             'ydonea': {'ydoneas': []},
             'ydonei': {'ydoneis': []},
             'ydoneo': {'ydoneos': []},
             'ydoneu': {'ydoneus': []},
             'ydoyn': {'ydoyne': []},
             'ydpo': {'ydpos': []},
             'ydrate': {'ydrated': [], 'ydrates': []},
             'ydraw': {'ydrawe': []},
             'ydro': {'ydros': []},
             'ydrocarbon': {'ydrocarbons': []},
             'ydrochlor': {'ydrochloric': []},
             'ydrodynam': {'ydrodynamic': ['ydrodynamics']},
             'ydrodynamic': ['ydrodynamics'],
             'ydroelectr': {'ydroelectric': []},
             'ydrogen': {'ydrogenation': []},
             'ydrolog': {'ydrologic': ['ydrological']},
             'ydrologic': ['ydrological'],
             'ydrolysi': {'ydrolysis': []},
             'ydronk': {'ydronke': []},
             'ydrophob': {'ydrophobic': []},
             'ydrostat': {'ydrostatic': []},
             'ydtra': {'ydtras': []},
             'ydtrd': {'ydtrds': []},
             'ydu': {'ydus': []},
             'ydur': {'ydurs': []},
             'ydut': {'yduts': []},
             'ydvo': {'ydvos': []}}
