
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_pz = {'_': ['pz_cassiopeiae',
       'pz_telescopii',
       'pz.sfl._ii',
       'pz_cussons',
       'pz_meyers',
       'pz_myers',
       'pz_iii',
       'pz_ivg',
       'pz-i_a',
       'pz_ii',
       'pz_iv'],
 'a': ['pza_loara'],
 'f': ['pzf_44'],
 'h': ['pzh_2000nl', 'pzh_2000'],
 'i': ['pzinz_703', 'pzinz_l-s', 'pzinz_130'],
 'k': ['pzkpfw_iii',
       'pzkpfw_iil',
       'pzkpfw_ii',
       'pzkpfw_vi',
       'pzkpfw_iv',
       'pzkpfw_ia',
       'pzkpfw_v',
       'pzkpfw_i',
       'pzkw_vi'],
 'l': ['pzl-swidnik_kania',
       'pzl-230_skorpion',
       'pzl-swidnik_sw-4',
       'pzl-mielec_ts-11',
       'pzl-swidnik_mi-2',
       'pzl-mielec_lim-6',
       'pzl-mielec_m-18',
       'pzl-mielec_m-20',
       'pzl-105_flaming',
       'pzl.50_jastrzab',
       'pzl-swidnik_w-3',
       'pzl-mielec_m-15',
       'pzl-110_koliber',
       'pzl-112_junior',
       'pzl-126_mrowka',
       'pzl-101_gawron',
       'pzl.48_lampart',
       'pzl.44_wicher',
       'pzl-104_wilga',
       'pzl-130_orlik',
       'pzl.43_karas',
       'pzl.23_karas',
       'pzl.56_kania',
       'pzl.45_sokol',
       'pzl-106_kruk',
       'pzl_swidnik',
       'pzl_bielsko',
       'pzl.38_wilk',
       'pzl-38_wilk',
       'pzl-102_kos',
       'pzl-46_sum',
       'pzl.49_mis',
       'pzl_mielec',
       'pzl.37_los',
       'pzl.46_sum',
       'pzl_asz-62',
       'pzl_md-12',
       'pzl_kania',
       'pzl_p.11c',
       'pzl_an-28',
       'pzl_iskra',
       'pzl_p-11c',
       'pzl_p.11',
       'pzl_p.46',
       'pzl_p.24',
       'pzl_m-28',
       'pzl_p-24',
       'pzl_m-17',
       'pzl_pw-6',
       'pzl_p.7a',
       'pzl_i-22',
       'pzl_sm-1',
       'pzl_p.43',
       'pzl_p-11',
       'pzl_sw-4',
       'pzl_pw-5',
       'pzl_sm-2',
       'pzl_p-19',
       'pzl_mi-2',
       'pzl_s-1',
       'pzl_p-1',
       'pzl_110',
       'pzl_p-5',
       'pzl_w-4',
       'pzl_p-7',
       'pzl_102',
       'pzl_l.2',
       'pzl_m-2',
       'pzl_p.7',
       'pzl_w-3',
       'pzl_101',
       'pzl_m28',
       'pzl_104',
       'pzl_106',
       'pzl_p.1',
       'pzl_p.8',
       'pzl_p.6',
       'pzl_p7',
       'pzl_16',
       'pzl_19',
       'pzl._6',
       'pzl_12',
       'pzl_5',
       'pzl_4'],
 'm': ['pzms_poltava'],
 'r': ['pzr_317'],
 't': ['pzt-based_compounds'],
 'x': ['pzx_triangle']}
