
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_pv = {'_': ['pv_manufacturing',
       'pv_castellensis',
       'pv_gangadharan',
       'pv_amphibious',
       'pv_telescopii',
       'pv-1_harpoon',
       'pv_inverter',
       'pv_kalathur',
       'pv_simmons',
       'pv_diagram',
       'pv_saibabu',
       'pv_ventura',
       'pv_cephei',
       'pv_system',
       'pv_module',
       'pv_kurian',
       'pv_mount',
       'pv_cells',
       'pv_cell',
       'pv_pyap'],
 'a': ['pvar_rifle', 'pva_glue'],
 'c': ['pvc_superphylum',
       'pvc_recycling',
       'pvc_clothing',
       'pvc_decking',
       'pvc_bendit',
       'pvc_piping',
       'pvc_pipe',
       'pvc_tape',
       'pvc_1'],
 'k': ['pvk_jadran'],
 'l': ['pvlib_python'],
 'n': ['pvn_tower'],
 'o': ['pvo_newsday', 'pvo_strany'],
 'p': ['pvp_karting', 'pvp_online', 'pvp_cinema', 'pvp_live'],
 'r': ['pvr-resistant_advertising', 'pvr_pictures', 'pvr_cinemas'],
 's': ['pvsk_panthers'],
 't': ['pvt.dimitri_petrenko',
       'pvt_relationships',
       'pvt_bloggins',
       'pvt._martin',
       'pvt._gillis',
       'pvt._schine',
       'pvt_chat']}
