
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_pb = {'pb2m_mars': 'jrm_mars',
 'pb4y-1_liberator': 'b-24_liberator',
 'pb4y_privateer': 'pb4y-2_privateer',
 'pb_air': 'pbair',
 'pb_army': 'the_pb_army',
 'pb_chatwin': 'p._b._chatwin',
 'pb_desai': 'p._b._desai',
 'pb_navigator': 'packard_bell_navigator',
 'pb_railroad': 'western_rail_road',
 'pb_ratio': 'p/b_ratio',
 'pb_shelley': 'percy_bysshe_shelley',
 'pb_sreenivas': 'p._b._sreenivas',
 'pba_draft': 'philippine_basketball_association_draft',
 'pba_mvp': 'philippine_basketball_association_most_valuable_player_award',
 'pbat/i_19': 'norrbottens_pansarbataljon',
 'pbh_may': 'peter_may',
 'pbil_m/40': 'pansarbil_m/39',
 'pbj_mitchell': 'b-25_mitchell',
 'pbj_sandwich': 'peanut_butter_and_jelly_sandwich',
 'pbn_defender': 'britten-norman_defender',
 'pbp_rpg': 'play-by-post_role-playing_game',
 'pbpk_modelling': 'physiologically-based_pharmacokinetic_modelling',
 'pbs_buffer': 'phosphate_buffered_saline',
 'pbs_hawaii': 'khet',
 'pbs_id': 'pbs_idents',
 'pbs_ident': 'pbs_idents',
 'pbs_identification': 'pbs_idents',
 'pbs_logos': 'pbs_idents',
 'pbs_newshour': 'the_newshour_with_jim_lehrer',
 'pbs_pinchback': 'p._b._s._pinchback',
 'pbs_pro': 'portable_batch_system',
 'pbs_sprout': 'pbs_kids_sprout',
 'pbs_xtra': 'pbs_satellite_service',
 'pbv_301': 'pansarbandvagn_301',
 'pbv_302': 'pansarbandvagn_302',
 'pbv_501': 'bmp-1',
 'pbx_9404': 'polymer-bonded_explosive',
 'pbx_9502': 'polymer-bonded_explosive',
 'pby-5a_catalina': 'pby_catalina',
 'pby-6a_catalina': 'pby_catalina',
 'pby_canso': 'pby_catalina'}
        