
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_rv = {'rv-1': 'ov-1_mohawk',
 'rv-7908': 'caspian_airlines_flight_7908',
 'rv-a': 'rotavirus',
 'rv-b': 'rotavirus',
 'rv-coefficient': 'rv_coefficient',
 'rv-d': 'rotavirus',
 'rv-e': 'rotavirus',
 'rv.i': 'mandala_1',
 'rv.ii': 'mandala_2',
 'rv.iii': 'mandala_3',
 'rv.iv': 'mandala_4',
 'rv.v': 'mandala_5',
 'rv.vi': 'mandala_6',
 'rv.vii': 'mandala_7',
 'rv.viii': 'mandala_8',
 'rv350': 'radeon_r300',
 'rv7908': 'caspian_airlines_flight_7908',
 'rvaap': 'ravenna_training_and_logistics_site',
 'rvalue': 'r-value',
 'rvar': 'treynor_ratio',
 'rvb:oom': 'red_vs._blue:_out_of_mind',
 'rvbr': 'red_vs._blue:_reconstruction',
 'rvce': 'rashtreeya_vidyalaya_college_of_engineering',
 'rvd-tv': 'rob_van_dam',
 'rvdt': 'rotary_variable_differential_transformer',
 'rvdv': 'rafael_van_der_vaart',
 'rvedd': 'end-diastolic_dimension',
 'rvef': 'ejection_fraction',
 'rvesd': 'end-systolic_dimension',
 'rvipvo': 'sfr_yugoslav_air_force',
 'rvl-001': 'wii',
 'rvl-003': 'wii_remote',
 'rvnaf': 'army_of_the_republic_of_vietnam',
 'rvrd': 'rendezvous_routing_daemon',
 'rvrhs': 'rancocas_valley_regional_high_school',
 'rvrr': 'rahway_valley_railroad',
 'rvrworkers': 'river_valley_ranch',
 'rvsc': 'rio_valley_switching_company',
 'rvsm': 'reduced_vertical_separation_minima',
 'rvsn': 'strategic_rocket_forces',
 'rvtv': 'rogue_valley_community_television',
 'rvucom': 'rocky_vista_university_college_of_osteopathic_medicine',
 'rvvv': 'remote_viewing',
 'rvyc': 'royal_varuna_yacht_club'}
        