
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_kb = {'kb-29_superfortress': 'boeing_kb-29',
 'kb-50_superfortress': 'b-50_superfortress',
 'kb._mcfarlane': 'k._b._mcfarlane',
 'kb_andersen': 'k._b._andersen',
 'kb_arsenal': 'arsenal_design_bureau',
 'kb_banki': 'kaupthing_bank',
 'kb_bridge': 'koror-babeldaob_bridge',
 'kb_cup': 'amco_cup',
 'kb_group': 'kookmin_bank',
 'kb_hallen': 'k.b._hallen',
 'kb_hedgewar': 'k._b._hedgewar',
 'kb_heusden-zolder': 'k._beringen-heusden-zolder',
 'kb_homes': 'kb_home',
 'kb_karlskoga': 'kb_karlskoga_fotboll',
 'kb_khimautomatiki': 'chemical_automatics_design_bureau',
 'kb_khimavtomatika': 'chemical_automatics_design_bureau',
 'kb_lall': 'k._b._lall',
 'kb_mashinostroyeniya': 'kbm',
 'kb_mashynostroyeniya': 'kbm',
 'kb_mcfarlane': 'k._b._mcfarlane',
 'kb_molniya': 'vympel_npo',
 'kb_sahay': 'k._b._sahay',
 'kb_series': 'international_harvester_k_and_kb_series',
 'kb_shanappa': 'k._b._shanappa',
 'kb_sharp': 'k._b._sharp',
 'kb_singh': 'k._b._singh',
 'kb_sundarambal': 'k._b._sundarambal',
 'kb_wz.98a': 'kb_wz._98a',
 'kbach_rachana': 'kbach',
 'kbal_chhay': 'kbal_chhay_waterfall',
 'kbc_augusta': 'vana_h_cup_kbc_augusta',
 'kbc_groep': 'kbc_bank',
 'kbc_group': 'kbc_bank',
 'kbc_tower': 'boerentoren',
 'kbd-1_gargoyle': 'lbd-1_gargoyle',
 'kbd_window': 'kaiser_window',
 'kber_101': 'kber',
 'kbi_pa-63': 'feg_pa-63',
 'kbim_tower': 'krqe',
 'kbjr_dt2': 'kbjr-tv',
 'kbk_wz.29': 'kbk_wz._1929',
 'kbkg_m1960': 'kbkg_wz._1960',
 'kbkg_wz.1960': 'kbkg_wz._1960',
 'kbl_sports': 'fox_sports_pittsburgh',
 'kbmt_12': 'kbmt',
 'kbp_a-91': 'a-91',
 'kbp_pp-90': 'pp-90',
 'kbr_3023': 'icaridin',
 'kbr_airport': 'sultan_ismail_petra_airport',
 'kbs_1tv': 'korean_broadcasting_system',
 'kbs_beryl': 'kbs_wz._1996_beryl',
 'kbs_chicago': 'woch-ca',
 'kbs_kyoto': 'kyoto_broadcasting_system',
 'kbsp_wz.38m': 'kbsp_wz._1938m',
 'kbtx_tv': 'kbtx-tv'}
        