
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_cg = {'_': ['cg_finch-davies',
       "cg'ose_ntcox'o",
       'cg_suppression',
       'cg-4a_hadrian',
       'cg_supervisor',
       'cg_andromedae',
       'cg-4_hadrian',
       'cg_animation',
       'cg_greenidge',
       'cg_puigcerda',
       'cg_railway',
       'cg-4a_waco',
       'cg_method',
       'cg-4_haig',
       'cg_artist',
       'cg-4_waco',
       'cg_gordon',
       'cg_tools',
       'cg_films',
       'cg_cygni',
       'cg_conn',
       'cg_lang',
       'cg_jung',
       'cg_road',
       'cg_afi',
       'cg_2',
       'cg_4'],
 'a': ['cgas_clearwater',
       'cga_programming',
       'cgas_astoria',
       'cgas_kodiak',
       'cgas_salem'],
 'b': ['cgb_spender'],
 'c': ['cgcg_049-033', 'cgcoc_group', 'cgcn_group', 'cgc_grade', 'cgc_japan'],
 'e': ['cge_model'],
 'h': ['cgh_physics', 'cghs_model'],
 'i': ['cgi_animation',
       'cgi_animated',
       'cgi_script',
       'cgi_effect',
       'cgi_group',
       'cgi_inc.',
       'cgi_aero'],
 'k': ['cgk733_fraud'],
 'l': ['cgl_m5'],
 'm': ['cgm_normandie', 'cgm_gallagher', 'cgm-16_atlas', 'cgm_558'],
 'n': ['cgnet_swara', 'cgna_toxin'],
 'o': ['cgo_386'],
 'p': ['cgp_52608', 'cgp_grey'],
 'r': ['cgram_software',
       'cgrp_receptor',
       'cgr_railmotor',
       'cgr_0-6-0st',
       'cgr_0-6-0t'],
 's': ['cgs_kamaruzzaman',
       'cgs_patuakhali',
       'cgs_rangamati',
       'cgs_margaret',
       'cgs_vigilant',
       'cgs_tajuddin',
       'cgs_noakhali',
       'cgs_aberdeen',
       'cgs_kutubdia',
       'cgs_bradbury',
       'cgs_aviation',
       'cgs_lambton',
       'cgs_sonadia',
       'cgs_vigraha',
       'cgs_stanley',
       'cgs_kestrel',
       'cgs_colony',
       'cgs_alaska',
       'cgs_varaha',
       'cgs_petrel',
       'cgs_system',
       'cgs_acadia',
       'cgsc_press',
       'cgs_21680',
       'cgs_minto',
       'cgs_pabna',
       'cgs_bogra',
       'cgs_units',
       'cgs_hawk',
       'cgs_unit'],
 't': ['cgtn_documentary',
       'cgtn_america',
       'cgtn_spanish',
       'cgtn_russian',
       'cgtn_french',
       'cgtv_canada',
       'cgtn_africa',
       'cgtn_arabic'],
 'u': ['cgu_insurance', 'cgu_plc']}
