
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ds = {'_': ['ds_senanayake_college',
       'ds_download_stations',
       'ds_download_station',
       'ds_opera_browser',
       'ds_online_games',
       'ds9:_the_fallen',
       'ds_video_games',
       'ds_soap_awards',
       'ds_wi-fi_games',
       'ds_supernova_2',
       'ds_3_crossback',
       'ds_ray_carling',
       'ds_web_browser',
       'ds_7_crossback',
       'ds_luke_french',
       'ds_game_sales',
       'ds_universe_2',
       'ds_mel_silver',
       'ds_option_pak',
       'ds_al_fine'],
 'a': ['dsa-58osw_battle_carbine', 'dsa_practical_test'],
 'b': ['dsb_international_school',
       'dsbc_protein_family',
       'dsb_class_mx',
       'dsb_class_mr',
       'dsb_class_mz',
       'dsb_class_mt',
       'dsb_class_mh',
       'dsb_class_my',
       'dsb_class_me',
       'dsb_class_mq',
       'dsb_class_ea',
       'dsb_class_d',
       'dsb_class_p'],
 'c': ['dschinghis_khan_discography',
       'dschang_bus-truck_crash',
       'dschinghis_khan_family',
       'dsc_arminia_bielefeld',
       'dsc_cricket_stadium'],
 'g': ['dsg_international_ltd.',
       'dsg_international_plc',
       'dsg_international_ltd'],
 'h': ['dshk_machine_gun'],
 'i': ['dsi_samson_group'],
 'k': ['dsk_airmotive_hawk', 'dsk_shivajians_fc'],
 'l': ['dsl_access_multiplexer',
       'dsl_blue_jays2',
       'dsl_blue_jays1',
       'dsl_red_sox'],
 'm': ['dsm_cautionary_statement', 'dsm_iv_tr'],
 'o': ['dso_national_laboratories',
       'dso_tatran_teplice',
       'dso_banik_kladno',
       'dso_dynamo_praha'],
 'r': ['dsrm_national_bank'],
 's': ['dss1/sem1_protein_family', 'dsst_public_schools'],
 't': ['dst_group_building',
       'dst_systems_inc.',
       'dstl_porton_down',
       'dstv_select_1'],
 'v': ['dsv_78/08_ricklingen',
       'dsv_alpine_donawitz',
       'dsv_victoria_zemun',
       'dsv_1878_hannover',
       'dsv_shinkai_6500',
       'dsv_shinkai_2000',
       'dsv-4_sea_cliff',
       'dsv_78_hannover',
       'dsv_sea_cliff'],
 'w': ['dsw_heavyweight_championship']}
