
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_hp = {'_': ['hp_multi-programming_executive',
       'hp_quicktest_professional',
       'hp_integrated_lights-out',
       'hp_smartimage_ecosystem',
       'hp_technology_solutions',
       'hp-ux_memory_management',
       'hp_kittyhawk_microdrive',
       'hp_networking_products',
       'hp_networking_training',
       'hp_enterprise_services',
       'hp_integrity_superdome',
       'hp_technology_services',
       'hp_pretexting_scandal',
       'hp_topshot_technology',
       'hp_time-sharing_basic',
       'hp_mediasmart_connect',
       'hp_operations_manager',
       'hp-basic_for_openvms',
       'hp_service_activator',
       'hp_converged_systems',
       'hp_business_desktops',
       'hp_essential_laptops',
       'hp_hard_partitioning',
       'hp_integrity_nonstop',
       'hp_time-shared_basic',
       'hp_continuous_memory',
       'hp_mediasmart_server',
       'hp_pavilion_dv6000z',
       'hp_photosmart_r717',
       'hp_photosmart_m307',
       'hp_pavilion_dv8000',
       'hp_photosmart_m417',
       'hp_photosmart_m425',
       'hp_photosmart_m407',
       'hp_photosmart_e427',
       'hp_indigo_division',
       'hp_photosmart_m537',
       'hp_photosmart_r817',
       'hp_photosmart_m627',
       'hp_release_control',
       'hp_virtual_connect',
       'hp_hunnicutt_field',
       'hp_photosmart_r707',
       'hp_photosmart_r725',
       'hp_photosmart_r507',
       'hp_photosmart_r727',
       'hp_photosmart_r607',
       'hp_photosmart_m517',
       'hp_photosmart_735',
       'hp_9000_superdome',
       'hp_color_recovery',
       'hp_calcpad_series',
       'hp_photosmart_318',
       'hp_photosmart_715',
       'hp_laserjet_p3005',
       'hp_spying_scandal',
       'hp_quality_center',
       'hp_openview_temip',
       'hp_temip_software',
       'hp_photosmart_315',
       'hp_data_protector',
       'hp_photosmart_m22',
       'hp_laserjet_4000',
       'hp1_holin_family',
       'hp_precision_bus',
       'hp_pavilion_dv2z',
       'hp_luckett_house',
       'hp_laserjet_1020',
       'hp_compaq_tc4200',
       'hp_laserjet_4200',
       'hp_laserjet_4300',
       'hp_presario_3000',
       'hp_postcode_area',
       'hp_compaq_tc4400',
       'hp_blackbird_002',
       'hp_compaq_tc1100',
       'hp_laserjet_2400',
       'hp_pavilion_dv7',
       'hp_49/50_series',
       'hp_pavilion_dv5',
       'hp_39/40_series',
       'hp_pavilion_dv4',
       'hp_9800_series',
       'hp_compaq_2133',
       'hp_ipaq_rx1950',
       'hp_integral_pc',
       'hp_pavilion_tx',
       'hp_postal_area',
       'hp_laserjet_4m',
       'hp_media_vault',
       'hp_eio_printer',
       'hp_brown_sauce',
       'hp_laserjet_4',
       'hp_laserjet_5',
       'hp_van_schoor',
       'hp_48_series',
       'hp_slate_500',
       'hp_mini_1000',
       'hp_30_series',
       'hp_code_wars',
       'hp_series_80',
       'hp_hood_inc.',
       'hp_hood_inc',
       'hp_hood_llc',
       'hp_stream_7',
       'hp_elite_x3',
       'hp_slate_21',
       'hp_slate_7',
       'hp_de_tijd',
       'hp_xb_3000',
       'hp_pre_3'],
 'a': ['hpa_culture_collections', 'hpa_axis_suppression'],
 'c': ['hpc_challenge_benchmark'],
 'e': ['hper_biomechanics_laboratory', 'hpe_integrity_servers'],
 'i': ['hpi_baja_5b/5t', 'hpi_pro_4'],
 'l': ['hplc_fluorescence_detector', 'hplc_uv_detector'],
 'o': ['hponkanrazi_wildlife_sanctuary'],
 'v': ['hpv-positive_oropharyngeal_cancer', 'hpv_dna_test']}
