
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_nr = {'_': ['nr58-3.14.3',
       'nr2a21',
       'nr-413',
       'nr2003',
       'nr1b1',
       'nr1b3',
       'nr3c4',
       'nr5a1',
       'nr0b2',
       'nr1d1',
       'nr-40',
       'nr3c1',
       'nr1a2',
       'nr3a1',
       'nr2a1',
       'nr2c1',
       'nr1c1',
       'nr6a1',
       'nr1d2',
       'nr2f2',
       'nr1i2',
       'nr2f1',
       'nr2b1',
       'nr1h2',
       'nr500',
       'nr4a1',
       'nr4a2',
       'nr3c3',
       'nr1f2',
       'nr1c2',
       'nr3b2',
       'nr1h3',
       'nr2k3',
       'nr2b3',
       'nr-30',
       'nr3c2',
       'nr1f1',
       'nr1h4',
       'nr2e1',
       'nr3b1',
       'nr1i3',
       'nr2c2',
       'nr0b1',
       'nr2f6',
       'nr-23',
       'nr3a2',
       'nr2a2',
       'nr1i1',
       'nr5a2',
       'nr2b2',
       'nr1c3',
       'nr4a3',
       'nr1b2',
       'nr1a1',
       'nr3b3',
       'nr2e3',
       'nr2a',
       'nr2d',
       'nr2b',
       'nr2c',
       'nr3b',
       'nr3a',
       'nr4a',
       'nr3c',
       'nr-1',
       'nr1',
       'nr2',
       'nr4'],
 'a': ['nramp1',
       'nrays',
       'nratv',
       'nrank',
       'nram',
       'nrao',
       'nras',
       'nrap',
       'nray'],
 'b': ['nrbuyn', 'nrbin', 'nrbp1', 'nrbf2', 'nrbq', 'nrbg', 'nrb'],
 'c': ['nrc-handelsblad',
       'nrcfoss',
       'nrcan',
       'nrcam',
       'nrccl',
       'nrcoa',
       'nrcc',
       'nrca',
       'nrcs',
       'nrc'],
 'd': ['nrdc-gr', 'nrds', 'nrdc', 'nrd1', 'nrd'],
 'e': ['nrenum.net',
       'nremt-p',
       'nremt-b',
       'nremtp',
       'nremtb',
       'nremt',
       'nrens',
       'nregs',
       'nrega',
       'nrem',
       'nrep',
       'nrex',
       'nrev',
       'nren',
       'nrea',
       'nrel',
       'nre'],
 'f': ['nrfu', 'nrf1', 'nrfm', 'nrf2', 'nrfc', 'nrf'],
 'g': ['nrg360', 'nrg1', 'nrg'],
 'h': ['nrh2o', 'nrhp', 'nrhh', 'nrhs', 'nrh'],
 'i': ['nripatindravarman',
       'nriputungavarman',
       'nrisinghapur',
       'nritarutya',
       'nrityagram',
       'nrithasala',
       'nripendra',
       'nrisimha',
       'nritoday',
       'nri-igbo',
       'nri-pio',
       'nritya',
       'nrip2',
       'nrip1',
       'nris',
       'nria',
       'nric',
       'nri'],
 'j': ['nrj'],
 'k': ['nrk3', 'nrk2', 'nrk1', 'nrk'],
 'l': ['nrlmsise-00', 'nrlus', 'nrlc', 'nrlb', 'nrla', 'nrl'],
 'm': ['nrmsd', 'nrma', 'nrmp', 'nrmx', 'nrm'],
 'n': ['nrnadzor', 'nrn-11', 'nrn11', 'nrnt', 'nrn1', 'nrn'],
 'o': ['nrounde',
       'nrol-26',
       'nrol-21',
       'nroogd',
       'nrotc',
       'nrodt',
       'nroff',
       'nroa',
       'nroc',
       'nron',
       'nro'],
 'p': ['nrp-1', 'nrp1', 'nrpn', 'nrpb', 'nrps', 'nrpc', 'nrp'],
 'q': ['nrqz', 'nrq'],
 'r': ['nrrd', 'nrrl', 'nrrc', 'nrr'],
 's': ['nrsimhadeva',
       'nrsingadeva',
       'nrsimhadev',
       'nrsc-5-a',
       'nrsv-ce',
       'nrsimha',
       'nrsros',
       'nrsc-2',
       'nrsp-7',
       'nrsc-4',
       'nrsc-5',
       'nrsro',
       'nrsn1',
       'nrs-2',
       'nrsn2',
       'nrsa',
       'nrsp',
       'nrsv',
       'nrsc',
       'nrsf',
       'nrst',
       'nrs'],
 't': ['nrtrade', 'nrtlq', 'nrtl', 'nrta', 'nrtv', 'nrtn', 'nrti', 'nrt'],
 'u': ['nrusinhavatar', 'nrumc', 'nruf', 'nru'],
 'v': ['nrvo', 'nrv'],
 'w': ['nrw-express',
       'nrw-trophy',
       'nrw.invest',
       'nrw-forum',
       'nrwinvest',
       'nrw.bank',
       'nrw-liga',
       'nrwa',
       'nrw'],
 'x': ['nrxn3', 'nrxn2', 'nrxn1', 'nrxn', 'nrx'],
 'y': ['nry'],
 'z': ['nrz-i', 'nrz-l', 'nrzl', 'nrzm', 'nrzs', 'nrz']}
