
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_nl = {'_': ['nl.wikipedia.org',
       'nl-complete',
       'nl-alert',
       'nl-201',
       'nl-37',
       'nl-ix',
       'nl8',
       'nl1',
       'nl4',
       'nl2'],
 'a': ["nlaka'pamux",
       'nlaujats',
       'nlayers',
       'nlaman',
       'nlaiii',
       'nlams',
       'nland',
       'nlaw',
       'nlax',
       'nlab',
       'nla'],
 'b': ['nlbeter', 'nlbs', 'nlb'],
 'c': ['nlcf', 'nlcc', 'nlcs', 'nlc'],
 'd': ['nlds', 'nld'],
 'e': ['nlectc', 'nleom', 'nlets', 'nlea', 'nlex', 'nle1', 'nlec', 'nle'],
 'f': ['nlfsvn', 'nlfa', 'nlfl', 'nlfc', 'nlft', 'nlf'],
 'g': ['nlgn4x',
       'nlgla',
       'nlgn3',
       'nlgn2',
       'nlgja',
       'nlgn1',
       'nlgn',
       'nlgi',
       'nlg'],
 'h': ['nlhamankulu', 'nlhs', 'nlh'],
 'i': ['nlite', 'nlirx', 'nliu', 'nli'],
 'j': ['nljd', 'nlj'],
 'k': ['nlk'],
 'l': ['nllxp', 'nllt', 'nllr', 'nlls', 'nll'],
 'm': ['nlmk', 'nlms', 'nlm'],
 'n': ['nlnac', 'nlnet', 'nlnz', 'nln'],
 'o': ['nlos-ls', 'nlogit', 'nlos-c', 'nloth', 'nlog', 'nlos', 'nlo'],
 'p': ['nlpologist', 'nlpology', 'nlpfsr', 'nlpqlp', 'nlpg', 'nlpc', 'nlp'],
 'q': ['nlq'],
 'r': ['nlr-atsi',
       'nlrp14',
       'nlrp10',
       'nlrp11',
       'nlrp12',
       'nlrp13',
       'nlrp3',
       'nlrp5',
       'nlrp9',
       'nlrp4',
       'nlrp6',
       'nlrp8',
       'nlrp2',
       'nlrc4',
       'nlrx1',
       'nlrc3',
       'nlrc5',
       'nlrp7',
       'nlrp1',
       'nlra',
       'nlrp',
       'nlrx',
       'nlrb',
       'nlr'],
 's': ['nlsio', 'nlsiu', 'nlsp', 'nlsc', 'nlsy', 'nls'],
 't': ['nltss', 'nltk', 'nltc', 'nlt'],
 'u': ['nluug', 'nlu'],
 'v': ['nlvpd', 'nlvo', 'nlve', 'nlv'],
 'w': ['nlwf', 'nlwc', 'nlwm', 'nlw'],
 'x': ['nlx'],
 'y': ['nlyl', 'nly'],
 'z': ['nlz']}
