
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_lv = {'lv-1201': 'aliens_versus_predator_2',
 'lv-sem': 'esem',
 'lv426': 'lv-426',
 'lvac': 'latrobe_valley_aero_club',
 'lvalue': 'l-value',
 'lvam': 'las_vegas_art_museum',
 'lvcc': 'las_vegas_convention_center',
 'lvccld': 'las_vegas-clark_county_library_district',
 'lvchs': 'lehigh_valley_christian_high_school',
 'lvcva': 'las_vegas_convention_and_visitors_authority',
 'lvdc': 'direct_current',
 'lvds': 'low-voltage_differential_signaling',
 'lvdt': 'linear_variable_differential_transformer',
 'lvedd': 'end-diastolic_dimension',
 'lvee': 'linux_vacation_/_eastern_europe',
 'lvef': 'ejection_fraction',
 'lvep': 'living_values',
 'lvesd': 'end-systolic_dimension',
 'lvfcs': 'las_vegas_film_critics_society',
 'lvgz': 'yasser_arafat_international_airport',
 'lvhiff': 'hawaii_international_film_festival',
 'lvia': 'lehigh_valley_international_airport',
 'lviewpro': 'lview',
 'lvivska': 'lviv_oblast',
 'lvls': 'lithuanian_peasant_popular_union',
 'lvlt': 'level_3_communications',
 'lvmi': 'ludwig_von_mises_institute',
 'lvmpd': 'las_vegas_metropolitan_police_department',
 'lvms': 'las_vegas_motor_speedway',
 'lvov': 'lviv',
 'lvovskaya': 'lvovsky',
 'lvovskoye': 'lvovsky',
 'lvpa': 'lehigh_valley_charter_high_school_for_the_performing_arts',
 'lvpd': 'las_vegas_metropolitan_police_department',
 'lvpecl': 'low-voltage_positive_emitter-coupled_logic',
 'lvps': 'louis_vuitton_pacific_series',
 'lvrj': 'las_vegas_review-journal',
 'lvrj.com': 'las_vegas_review-journal',
 'lvrs': 'lung_volume_reduction_surgery',
 'lvrt': 'low_voltage_ride_through',
 'lvsem': 'esem',
 'lvsf': 'liga_de_voleibol_superior_femenino',
 'lvt-7': 'amphibious_assault_vehicle',
 'lvt4': 'landing_vehicle_tracked',
 'lvtn': 'kvte-lp',
 'lvtp': 'landing_vehicle_tracked',
 'lvtp-5': 'lvt-5',
 'lvtp-7': 'amphibious_assault_vehicle',
 'lvtp5': 'lvt-5',
 'lvtp7a1': 'amphibious_assault_vehicle',
 'lvts': 'large_value_transfer_system',
 'lvucentvm': 'lucentum',
 'lvucenvm': 'lucentum',
 'lvusd': 'las_virgenes_unified_school_district',
 'lvvwd': 'las_vegas_valley_water_district'}
        