
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_hk = {'_': ['hk_ozolnieki/monarhs',
       'hk_zemgale/llu',
       'hk_government',
       'hk_kremenchuk',
       'hk_dinaburga',
       'hk_governors',
       'hk_vojvodina',
       'hk_syberport',
       'hk_bardejov',
       'hk_edgerton',
       'hk_lovosice',
       'hk_magazine',
       'hk_partizan',
       'hk_jahorina',
       'hk_governor',
       'hk_passport',
       'hk_medvjedi',
       'hk_4.6x30mm',
       'hk_olimpija',
       'hk_kryvbas',
       'hk_sabinov',
       'hk_express',
       'hk_kurbads',
       'hk_vitebsk',
       'hk_denmark',
       'hk_mogilev',
       'hk_aquarii',
       'hk_beograd',
       'hk_ruzinov',
       'hk_latgale',
       'hk_beostar',
       'hk_liepaja',
       'hk_sampion',
       'hk_slavija',
       'hk_poprad',
       'hk_levice',
       'hk_storks',
       'hk_kosice',
       'hk_vukovi',
       'hk_brezno',
       'hk_trnava',
       'hk_94-100',
       'hk_gruber',
       'hk_ayliff',
       'hk_disney',
       'hk_herulf',
       'hk_martin',
       'hk_malmo',
       'hk_young',
       'hk_nitra',
       'hk_rapid',
       'hk_vitez',
       'hk_first',
       'hk_media',
       'hk_brest',
       'hk_gomel',
       'hk_bosna',
       'hk_tauri',
       'hk_celje',
       'hk_drott',
       'hk_stars',
       'hk_cafe',
       'hk_riga',
       'hk_lida',
       'hk_spin',
       'hk_flag',
       'hk_mogo',
       'hk_alfa',
       'hk_eng',
       'hk_tas',
       'hk_gem',
       'hk_id'],
 'a': ['hkamti_township',
       'hkamti,_myanmar',
       'hkamti_district',
       'hkakabo_razi',
       'hkamti_shan',
       'hkamti_long',
       'hkaru_bum',
       'hka_test'],
 'b': ['hkbp_crisis', 'hkbn_bbtv', 'hkb_600'],
 'd': ['hkd_napredak', 'hkdc_awards', 'hkdc_award'],
 'f': ['hkfc_ground', 'hkfa_cup'],
 'k': ['hkk_brotnjo', 'hkk_posusje', 'hkkabo_razi', 'hkk_siroki', 'hkk_grude'],
 'l': ['hkl_bhagat'],
 'm': ['hkm_zvolen', 'hkmk_bled', 'hkm_sala'],
 'n': ['hkn,_inc.'],
 'p': ['hkp_4'],
 'r': ['hkr_international'],
 's': ['hksar_government',
       'hksar_passport',
       'hkscan_oyj',
       'hksar_flag',
       'hks,_inc.',
       'hks_700e'],
 'u': ['hkusam_mountain',
       'hkust_library',
       'hku_station',
       'hku_space',
       'hkun_law'],
 'w': ['hkw_chemnitz-nord'],
 'y': ['hky85_model']}
