
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ck = {'_': ['ck_scott-moncrieff',
       'ck_entertainments',
       'ck-12_foundation',
       'ck_chandrappan',
       'ck_manisankar',
       'ck_vulpeculae',
       'ck_mcclatchy',
       'ck_function',
       'ck_prahalad',
       'ck_williams',
       'ck_prahlad',
       'ck_fischer',
       'ck_carinae',
       'ck_transit',
       'ck_thakker',
       'ck_nayudu',
       'ck_deluxe',
       'ck_fauver',
       'ck_space',
       'ck_vodka',
       'ck_stead',
       'ck_chow',
       'ck_tang',
       'ck_janu',
       'ck_one',
       'ck_jen',
       'ck_me'],
 'c': ['ckck_radio', 'ckcw_fm'],
 'd': ['ckd_kits', 'ckd_disk', 'ckdk_fm'],
 'e': ['cke_restaurants'],
 'm': ['ckm_wz.30', 'ckmp_fm'],
 'p': ['ckpg_news'],
 's': ['cks_airport', 'cksum_virus', 'cks_group'],
 'v': ['ckv_dvo'],
 'x': ['ckx_television', 'ckx_radio'],
 'y': ['cky_discography',
       'cky_algorithm',
       'cky/the_bronx',
       'cky_cast',
       'cky_star',
       'cky_crew']}
