
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_cm = {'_': ['cm101mmxi_fundamentals',
       'cm.170_magister',
       'cm.175_zephyr',
       'cm_kornbluth',
       'cm_chondrite',
       'cm_macdonald',
       'cm_belcourt',
       'cm_lodestar',
       'cm_airlines',
       'cm_draconis',
       'cm_guerrero',
       'cm_browser',
       'cm-12_tank',
       'cm_peralta',
       'cm_newton',
       'cm_wells',
       'cm_depew',
       'cm_burns',
       'cm_frame',
       'cm_punk',
       'cm_naim',
       'cm_yoko',
       'cm_almy',
       'cm_9380',
       'cm_dra',
       'cm_08',
       'cm_i'],
 'a': ['cma-cgm_group',
       'cmas_europe',
       'cma_awards',
       'cma_sampo',
       'cma_award',
       'cma_cgm',
       'cmac_fc'],
 'b': ['cmb_television', 'cmb_radiation', 'cmb_monaco', 'cmb_thenia'],
 'c': ['cmc_international',
       'cmc_electronics',
       'cmc_magnetics',
       'cmc_aviation',
       'cmc_publikum',
       'cmc_americas',
       'cmc_leopard',
       'cmc_cruiser',
       'cmc_markets',
       'cmc_kolkata',
       'cmc_records',
       'cmc_limited',
       'cmc_veryca',
       'cmc_zinger',
       'cmc_leadca',
       'cmc_group',
       'cmc_mode',
       'cmc_ltd',
       'cmc_msu',
       'cmc_cup'],
 'd': ['cmd_distribution',
       'cmd_fd-4000',
       'cmd_ramlink',
       'cmd_fd-2000',
       'cmd_fd2000',
       'cmd_fd4000',
       'cmd_group',
       'cmd_file',
       'cmd_key'],
 'e': ['cmentarz_lyczakowski',
       'cmentarz_rakowicki',
       'cmentarz_zydowski',
       'cmereska_gorca',
       'cme_church',
       'cme_group',
       'cme_span'],
 'f': ['cmfsc_xtreme', 'cmf_design', 'cmfs_cup'],
 'g': ['cmgi_field'],
 'h': ['cmh_rawalpindi', 'cmh_hathorn', 'cmh_records', 'cmh_jhelum'],
 'i': ['cmiszew_rybnowski',
       'cmiljka_kalusevic',
       'cmi_entanglement',
       'cmi_roadbuilding',
       'cmi_motorsports',
       'cmic_enterprise',
       'cmielow_castle',
       'cmic_software'],
 'j': ['cmj_university'],
 'k': ['cmkt_iv'],
 'm': ['cmm_tv'],
 'n': ['cmn_radio'],
 'o': ['cmos_transistor',
       'cmos_amplifier',
       'cmolas_commune',
       'cmos_settings',
       'cmos_battery',
       'cmon_limited',
       'cmot_dibbler',
       'cmos_sensor',
       'cmos_imager',
       'cmos_memory',
       'cmos_camera',
       'cmos_setup',
       'cmos_based',
       'cmos_ram',
       'cmos_aps'],
 'p': ['cmp-n-acylneuraminate_phosphodiesterase',
       'cmp-n-acetylneuraminate_monooxygenase',
       'cmp_distribution',
       'cmp_information',
       'cmp_technology',
       'cmp_truck',
       'cmp_media',
       'cmp_fat'],
 'r': ['cmr_convention',
       'cmr_university',
       'cmr_surgical',
       'cmr_dirt',
       'cmr_2.0'],
 's': ['cms_performance',
       'cmsaf_mckinley',
       'cms_pipelines',
       'cms_computers',
       'cms_software',
       'cms_systems',
       'cms_college',
       'cms_energy',
       'cms_oissel',
       'cms_legal',
       'cms_exec',
       'cms_list'],
 't': ['cmt_association',
       'cmt_crossroads',
       'cmt_outlaws',
       'cmt_insider',
       'cmt_europe',
       'cmt_music',
       'cmt_news',
       'cmt_300',
       'cmt_mwl'],
 'u': ['cmu_sphinx', 'cmu_drama', 'cmu_west', 'cmu_cam', 'cmu_cl'],
 'v': ['cmv_polyradiculomyelopathy',
       'cmv_mononucleosis',
       'cmv_enterprises',
       'cmv_retinitis',
       'cmv_disease',
       'cmv_vaccine',
       'cmvss_108',
       'cmv_group'],
 'x': ['cmx_discography', 'cmx_systems', 'cmx_600'],
 'y': ['cmyk_color']}
