
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_nz = {'nz_army': 'new_zealand_army',
 'nz_breakers': 'new_zealand_breakers',
 'nz_cabinet': 'new_zealand_cabinet',
 'nz_cavaliers': 'new_zealand_cavaliers',
 'nz_coastguard': 'royal_new_zealand_coastguard',
 'nz_coinage': 'new_zealand_dollar',
 'nz_coins': 'new_zealand_dollar',
 'nz_cuisine': 'new_zealand_cuisine',
 'nz_cup': 'new_zealand_trotting_cup',
 'nz_customs': 'new_zealand_customs_service',
 'nz_dollar': 'new_zealand_dollar',
 'nz_elections': 'elections_in_new_zealand',
 'nz_english': 'new_zealand_english',
 'nz_first': 'new_zealand_first',
 'nz_flag': 'flag_of_new_zealand',
 'nz_flax': 'phormium',
 'nz_government': 'politics_of_new_zealand',
 'nz_herald': 'the_new_zealand_herald',
 'nz_house': 'high_commission_of_new_zealand_in_london',
 'nz_idol': 'new_zealand_idol',
 'nz_labour': 'new_zealand_labour_party',
 'nz_law': 'law_of_new_zealand',
 'nz_lotteries': 'new_zealand_lotteries_commission',
 'nz_mint': 'new_zealand_mint',
 'nz_music': 'music_of_new_zealand',
 'nz_navy': 'royal_new_zealand_navy',
 'nz_parliament': 'parliament_of_new_zealand',
 'nz_passport': 'new_zealand_passport',
 'nz_police': 'new_zealand_police',
 'nz_post': 'new_zealand_post',
 'nz_sas': 'new_zealand_special_air_service',
 'nz_scholarship': 'new_zealand_scholarship',
 'nz_skeptics': 'new_zealand_skeptics',
 'nz_steel': 'new_zealand_steel',
 'nz_torpedo': 'new_zealand_torpedo',
 'nz_warriors': 'new_zealand_warriors',
 'nzb_files': 'nzb',
 'nzinga_i': 'nzinga_of_ndongo_and_matamba',
 'nzinga_mbande': 'nzinga_of_ndongo_and_matamba',
 'nzinga_mbandi': 'nzinga_of_ndongo_and_matamba',
 'nzinga_mbemba': 'afonso_i_of_kongo',
 'nzlav_lll': 'nzlav',
 'nzo_ekanghaky': 'nzo_ekangaki',
 'nzo_ekha-nghaky': 'nzo_ekangaki',
 'nzr_dsc': 'nzr_dsc_class',
 'nzr_workshops': 'new_zealand_railways_department',
 'nzski_ltd': 'nzski'}
        