
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_wl = {'wl_beresford': 'lord_william_beresford',
 'wl_driver': 'william_l._driver',
 'wl_george': 'w._l._george',
 'wl_mail': 'windows_live_mail',
 'wl_messenger': 'windows_live_messenger',
 'wl_minckley': 'w._l._minckley',
 'wl_morton': 'w._l._morton',
 'wl_murdoch': 'billy_murdoch',
 'wl_rambo': 'w._l._rambo',
 'wl_spencer-churchill': 'winston_churchill',
 'wl_stoddart': 'william_lee_stoddart',
 'wl_thomas': 'william_luson_thomas',
 'wlab_burdett-coutts': 'william_burdett-coutts',
 'wladak_zbyszko': 'wladek_zbyszko',
 'wladek_kowalski': 'killer_kowalski',
 'wladimir_baranoff-rossine': 'vladimir_baranov-rossine',
 'wladimir_bechterew': 'vladimir_bekhterev',
 'wladimir_burchel': 'krematorij',
 'wladimir_gelfand': 'vladimir_gelfand',
 'wladimir_golenischeff': 'vladimir_golenishchev',
 'wladimir_herzog': 'vladimir_herzog',
 'wladimir_ivanow': 'vladimir_alexeyevich_ivanov',
 'wladimir_jankilewskij': 'vladimir_yankilevsky',
 'wladimir_jefimkin': 'vladimir_efimkin',
 'wladimir_karpets': 'vladimir_karpets',
 'wladimir_malacki': 'jean_malaquais',
 'wladimir_putin': 'vladimir_putin',
 'wladimir_puttin': 'vladimir_putin',
 'wladimir_troubetzkoy': 'vladimir_petrovich_trubetskoy',
 'wladimir_virchis': 'vladimir_virchis',
 'wladimir_zyrinowski': 'vladimir_zhirinovsky',
 'wladimiro_guadagno': 'vladimir_luxuria',
 'wladislaus_ii': 'vladislas_ii_of_hungary',
 'wladislav_iii': 'ladislaus_iii',
 'wladislaw_ii': 'vladislas_ii_of_hungary',
 'wladislaw_jagiello': 'ladislaus_jagiello',
 'wladislaw_jogaila': 'jogaila',
 'wladmir_klitchko': 'wladimir_klitschko',
 'wladyslaw_i': 'ladislaus_i',
 'wladyslaw_ii': 'ladislaus_ii',
 'wladyslaw_iii': 'ladislaus_iii',
 'wladyslaw_jagiello': 'jogaila',
 'wladyslaw_jogaila': 'jogaila',
 'wladyslaw_lalitzky': 'vladislav_lalicki',
 'wladyslaw_starewicz': 'ladislas_starevich',
 'wladyslaw_zdora': 'kazimierz_zdziechowski',
 'wlan_autoconfig': 'wireless_zero_configuration',
 'wlan_security': 'wireless_lan_security',
 'wlat_harris': 'walt_harris',
 'wlcb-_tv': 'wtgl',
 'wlfred_owen': 'wilfred_owen',
 'wliiam_shakepear': 'william_shakespeare',
 'wliw_21': 'wliw',
 'wllb-lp_15': 'wllb-lp',
 'wlld_98.7': 'wlld',
 'wlodzimierz_wolynski': 'volodymyr-volynskyi',
 'wls_tv': 'wls-tv',
 'wltm_fm': 'wubl',
 'wlup-am_1000': 'wmvp'}
        