
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rj = {'_': ['rj1200',
       'rj.com',
       'rj-100',
       'rj-70',
       'rj-85',
       'rj500',
       'rj-21',
       'rj21x',
       'rj-48',
       'rj-61',
       'rj-xx',
       'rj100',
       'rj21',
       'rj70',
       'rj61',
       'rj12',
       'rj85',
       'rj48'],
 'a': ['rjavica',
       'rjavina',
       'rjavce',
       'rjavci',
       'rjak',
       'rjaf',
       'rjaa',
       'rjah',
       'rja'],
 'b': ['rjbt', 'rjbh', 'rjbb', 'rjb'],
 'c': ['rjcp', 'rjct', 'rjch', 'rjcm', 'rjck', 'rjco', 'rjcc', 'rjcb', 'rjc'],
 'd': ['rjdm', 'rjdj', 'rjd2', 'rjd'],
 'e': ['rjecina', 'rjeo', 'rjec', 'rjet', 'rje'],
 'f': ['rjfg', 'rjfc', 'rjfm', 'rjff', 'rjfn', 'rjfz', 'rjfy', 'rjfr', 'rjf'],
 'g': ['rjg'],
 'h': ['rjhh', 'rjhl', 'rjh'],
 'i': ['rjindael', 'rjit'],
 'k': ['rjki', 'rjkb', 'rjk'],
 'm': ['rjmetrics', 'rjm'],
 'n': ['rjno', 'rjna', 'rjnt'],
 'o': ['rjoandefossen', 'rjoo', 'rjoe', 'rjoz', 'rjoa', 'rjoc'],
 'p': ['rjp'],
 'r': ['rjr-2429', 'rjrummel', 'rjr'],
 's': ['rjst', 'rjsa', 'rjsu', 'rjs'],
 't': ['rjtk', 'rjtt', 'rjtl', 'rjtv', 'rjte', 'rjtj'],
 'u': ['rjukandefossen', 'rjukanbanen', 'rjuhsd', 'rjukan'],
 'v': ['rjv']}
