
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_xr = {'_': ['xr-budd',
       'xr-400',
       'xr650l',
       'xr808g',
       'xr4ti',
       'xr4x4',
       'xr400',
       'xr311',
       'xr-2',
       'xr-3',
       'xr2'],
 'a': ['xrafstar',
       'xramort',
       'xrated',
       'xrandr',
       'xrate',
       'xrays',
       'xrank',
       'xray',
       'xra'],
 'b': ['xrbl'],
 'c': ['xrcd24',
       'xrcc6',
       'xrcc2',
       'xrcc3',
       'xrcc5',
       'xrcd2',
       'xrcc1',
       'xrcc7',
       'xrco',
       'xrcd',
       'xrc'],
 'd': ['xrds', 'xrdb', 'xrdp', 'xrd'],
 'e': ['xrender', 'xrefer', 'xres', 'xref'],
 'f': ['xrf'],
 'i': ['xridoli', 'xrispa', 'xrinh', 'xrite', 'xrii', 'xrio', 'xri'],
 'l': ['xrl'],
 'm': ['xrml', 'xrm'],
 'n': ['xrn1', 'xrn2', 'xrnh'],
 'o': ['xrossmediabar', 'xroshtag'],
 'p': ['xrpd'],
 's': ['xrsam', 'xrs'],
 't': ['xrt'],
 'u': ['xrumer', 'xruby', 'xrun'],
 'x': ['xrx'],
 'y': ['xryspa', 'xry']}
