
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_xp = {'_': ['xp2v-1',
       'xp-pen',
       'xp-883',
       'xp-100',
       'xp-55',
       'xp-71',
       'xp-59',
       'xp-10',
       'xp-72',
       'xp-81',
       'xp-13',
       'xp-41',
       'xp-56',
       'xp-75',
       'xp-85',
       'xp-46',
       'xp-86',
       'xp-83',
       'xp-14',
       'xp-79',
       'xp-62',
       'xp-48',
       'xp-49',
       'xp-53',
       'xp-52',
       'xp-50',
       'xp-54',
       'xp64',
       'xp-7',
       'xp3',
       'xp8',
       'xp1',
       'xp7',
       'xp5',
       'xp6',
       'xp2',
       'xp4'],
 'a': ['xpander',
       'xpages',
       'xpage',
       'xpath',
       'xpaxn',
       'xpax',
       'xpac',
       'xpak',
       'xpa'],
 'b': ['xpb2m', 'xpb'],
 'c': ['xpc-binding', 'xpconnect', 'xpcom', 'xpce', 'xpcn', 'xpcc', 'xpc'],
 'd': ['xpdl', 'xpdr', 'xpdf', 'xpd'],
 'e': ['xperimental',
       'xpert-timer',
       'xpectation',
       'xperience',
       'xpenguins',
       'xpedition',
       'xperedon',
       'xpertdoc',
       'xpecial',
       'xperts',
       'xperi',
       'xpeng',
       'xpeak',
       'xpeke',
       'xpert',
       'xped',
       'xpe'],
 'f': ['xpfe', 'xpf'],
 'g': ['xpg'],
 'h': ['xphos'],
 'i': ['xpinstall',
       'xpilot-ng',
       'xpiyacoc',
       'xpiacoc',
       'xpiayoc',
       'xpilot',
       'xpidl',
       'xpic',
       'xpi'],
 'k': ['xpk'],
 'l': ['xplor-nih',
       'xploderz',
       'xplorer2',
       'xplorair',
       'xplosion',
       'xplornet',
       'xplosiv',
       'xplanet',
       'xplorer',
       'xploder',
       'xplore',
       'xplico',
       'xplora',
       'xplane',
       'xplor',
       'xplay',
       'xpl0',
       'xplm',
       'xpl'],
 'm': ['xpm2', 'xpm'],
 'n': ['xpnpep3', 'xpnpep1', 'xpnpep2', 'xpn'],
 'o': ['xpostfacto',
       'xpointer',
       'xponder',
       'xposed',
       'xports',
       'xpose',
       'xpot',
       'xpo1',
       'xpo6',
       'xpo5',
       'xpo4',
       'xpo'],
 'p': ['xpp'],
 'q': ['xpq-21', 'xpq21'],
 'r': ['xpressmedia',
       'xpressmusic',
       'xpresspost',
       'xpresscard',
       'xpressway',
       'xpressbet',
       'xpress-2',
       'xpress',
       'xprize',
       'xprint',
       'xproc',
       'xpro',
       'xpra'],
 's': ['xpsdrv', 'xps'],
 't': ['xptoolkit', 'xptpc', 'xpt'],
 'u': ['xpujil', 'xpuhil', 'xputer'],
 'v': ['xpv'],
 'w': ['xpw']}
