
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_xy = {'xy-nt': 'xy_no_trump_convention',
 'xygwin': 'cygwin',
 'xylariaceaous': 'xylariaceae',
 'xylariomycetidae': 'xylariales',
 'xyleborips': 'xyleborus',
 'xylenes': 'xylene',
 'xylidines': 'xylidine',
 'xylinum': 'acetobacter',
 'xylinx': 'xilinx',
 'xylo': 'mahindra_xylo',
 'xylo-marimba': 'xylorimba',
 'xylobalsamum': 'balsam_of_mecca',
 'xylocain': 'lidocaine',
 'xylocaine': 'lidocaine',
 'xylocard': 'lidocaine',
 'xylocopa': 'carpenter_bee',
 'xylocopidae': 'carpenter_bee',
 'xylocopini': 'carpenter_bee',
 'xylograph': 'woodcut',
 'xylographer': 'woodcut',
 'xylographic': 'woodcut',
 'xylographica': 'block_book',
 'xylography': 'woodcut',
 'xyloid': 'woody_plant',
 'xylokastron': 'xylokastro',
 'xylol': 'xylene',
 'xylologist': 'dendrology',
 'xylology': 'dendrology',
 'xylomancy': 'divination',
 'xylometazolin': 'xylometazoline',
 'xylonate': 'xylonic_acid',
 'xylonite': 'celluloid',
 'xylophage': 'xylophagy',
 'xylophaghou': 'xylofagou',
 'xylophagomorpha': 'xylophagidae',
 'xylophagos': 'xylophagy',
 'xylophagous': 'xylophagy',
 'xylophones': 'xylophone',
 'xylophonist': 'xylophone',
 'xylophylla': 'phyllanthus',
 'xyloplax': 'sea_daisy',
 'xylosyl': 'xylose',
 'xylotomist': 'xylotomy',
 'xylotymbou': 'xylotymvou',
 'xylulose-5-phosphate': 'xylulose_5-phosphate',
 'xylvania': 'battalion_wars',
 'xymox': 'clan_of_xymox',
 'xynalyq': 'khinalug',
 'xynistery': 'xynisteri',
 'xynotyro': 'xynotyro_cheese',
 'xyphoid': 'xiphoid_process',
 'xyrauchen': 'razorback_sucker',
 'xyridales': 'eriocaulales',
 'xyriscence': 'serotiny',
 'xyriscent': 'serotiny',
 'xystichromis': 'haplochromis',
 'xyy-trisomy': 'xyy_syndrome',
 'xyzal': 'levocetirizine',
 'xyzoo': 'xyzoo_animation'}
        