# coding: utf-8

"""
    Clothes Warehouse

    This API allows creation and retrieval of clothes   # noqa: E501

    Generated by: https://openapi-generator.tech
"""

import unittest

import clothes-sdk-ashuk203
from clothes-sdk-ashuk203.model.tshirt import Tshirt
from clothes-sdk-ashuk203 import configuration


class TestTshirt(unittest.TestCase):
    """Tshirt unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
