# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-ignore',
                'doc_host': 'https://feynlee.github.io',
                'git_url': 'https://github.com/feynlee/nbdev-ignore',
                'lib_path': 'nbdev_ignore'},
  'syms': {'nbdev_ignore.core': {'nbdev_ignore.core.ignore_': ('core.html#ignore_', 'nbdev_ignore/core.py')}}}
