
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_pw = {'_': ['pw_metternich',
       'pw_express',
       'pw_crummey',
       'pw_bortha',
       'pw_fenton',
       'pw_halton',
       'pw_singer',
       'pw_gopal',
       'pw_duffy',
       'pw_botha',
       'pw_ellis',
       'pw_noah',
       'pw_long',
       'pw_hof',
       'pw_usa'],
 'a': ['pwani_university',
       'pwaamei_language',
       'pwapwa_language',
       'pwa_silverdome',
       'pwani_province',
       'pwani_region',
       'pwa_saw'],
 'b': ['pwb_shell'],
 'c': ['pwc_plaza', 'pwc_uk'],
 'd': ['pwd_bamenda', 'pwdre_ser'],
 'e': ['pweto_territory',
       'pwedeng_pwede',
       'pweto_airport',
       'pwera_usog',
       'pwe_kyit'],
 'g': ['pwg_championship'],
 'i': ['pwilao_basumatary',
       'pwintbyu_township',
       'pwi_miwoty',
       'pwint_hpoo',
       'pwi_mpwoty',
       'pwi_ttoty',
       'pwi_years',
       'pwi_roty',
       'pwi_woty',
       'pwi_moty',
       'pwi_foty',
       'pwi_pwi'],
 'l': ['pwllyrhwyad,_llanarth',
       'pwllpriddog_oak',
       'pwllheli_south',
       'pwllheli_f.c.',
       'pwll,_tregare',
       'pwllheli_rfc',
       'pwll_lagoon',
       'pwl_records',
       'pwlldu_bay',
       'pwll_gwaun',
       'pwll_dwfn',
       'pwll_du'],
 'm': ['pwm_amplifier', 'pwm_rectifier', 'pwm_edition'],
 'n': ['pwn_encyclopedia',
       'pwn_encyklopedia',
       'pwn-9_kangaroo',
       'pwning_noobs',
       'pwnie_awards'],
 'o': ['pwo_language', 'pwoje_pyebwa', 'pwo_karen'],
 'r': ['pwr1_reactor', 'pwr2_reactor', 'pwr_racing', 'pwr_bttm'],
 's': ['pws-102_rekin',
       'pws-40_junak',
       'pws-33_wyzel',
       'pws-35_ogar',
       'pws_rwd-8',
       'pws_26',
       'pws_10',
       'pws_24',
       'pws_20',
       'pws_18',
       'pws_3']}
