
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_qe = {'_': ['qe1', 'qe2', 'qe4', 'qe3'],
 'b': ['qebehsenuef',
       'qebehsenuf',
       'qebhsennuf',
       'qebhsenuef',
       'qebshenuf',
       'qebehout',
       'qebchaq',
       'qeblehi',
       'qebbla',
       'qebele',
       'qebuta',
       'qebui',
       'qebh',
       'qeb'],
 'c': ['qecerzeyid', 'qechua', 'qec'],
 'd': ['qedarites',
       'qedrican',
       'qedoshim',
       'qedarite',
       'qedumim',
       'qedesh',
       'qedar',
       'qed'],
 'e': ['qeerroo', 'qeelin', 'qeema', 'qeej', 'qeep', 'qee'],
 'f': ['qeftsg', 'qefm'],
 'g': ['qegnazmach'],
 'h': ['qehwa', 'qehi', 'qehs', 'qeha', 'qeh'],
 'i': ['qeisas', 'qeii', 'qei'],
 'l': ['qelichabad',
       'qelutviaq',
       'qel-droma',
       'qelelevu',
       'qelinjlu',
       'qelichi',
       'qeleshe',
       'qelahim',
       'qeladze',
       'qelateh',
       'qelij',
       'qello',
       'qelat',
       'qelez',
       'qeli'],
 'm': ['qemu-launcher',
       'qemm-386',
       'qemscan',
       'qemm386',
       'qemists',
       'qemant',
       'qemoy',
       'qemal',
       'qemah',
       'qemu',
       'qemm',
       'qem'],
 'n': ['qenneshre',
       'qennarit',
       'qendaxan',
       'qender',
       'qenya',
       'qenet',
       'qenko',
       'qenna',
       'qenaz',
       'qeni',
       'qene',
       'qena',
       'qen'],
 'p': ['qepchaq', 'qephom', 'qeparo', 'qep'],
 'q': ['qeqertarsuatsiaat',
       'qeqertarssuaq',
       'qeqertarssdaq',
       'qeqertarsuaq',
       'qeqertalik',
       'qeqertat',
       'qeqertaq',
       'qeqqata'],
 'r': ['qernertuarssuit',
       'qernertunnguit',
       'qermezdash',
       'qermezabad',
       'qereshnik',
       'qermezin',
       'qerkhlar',
       'qerqereh',
       'qerkhlu',
       'qerret',
       'qernaq',
       'qerimi',
       'qerqiz',
       'qerveh',
       'qerim',
       'qeris',
       'qeres',
       'qeran',
       'qeri',
       'qera',
       'qere',
       'qerq'],
 's': ['qeshnehabad',
       'qeshquneh',
       'qesariyya',
       'qeshlaqlu',
       'qeshibes',
       'qestorat',
       'qeshlaq',
       'qesarat',
       'qeshet',
       'qeshm',
       'qest',
       'qesg'],
 't': ['qeturah', 'qetura', 'qetesh', 'qetdz'],
 'u': ['qeuanil'],
 'w': ['qew'],
 'x': ['qex'],
 'y': ['qeyzaniyeh',
       'qeysariyeh',
       'qeytasabad',
       'qeytaniyeh',
       'qeysarabad',
       'qeytarieh',
       'qeynarjeh',
       'qeysvand',
       'qeysabad',
       'qeysarya',
       'qeysaraq',
       'qeytaqi',
       'qeysnab',
       'qeytas',
       'qeymas',
       'qeyapa',
       'qeysar',
       'qeytak',
       'qeydar',
       'qeydu'],
 'z': ['qezelbashs',
       'qezkhachlu',
       'qezmazari',
       'qezelcheh',
       'qezelqash',
       'qezelbash',
       'qezelabad',
       'qezeljeh',
       'qezelqan',
       'qezlijeh',
       'qeziyan',
       'qezgeh',
       'qezlar',
       'qezel']}
