
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_qo = {'_': ['qo`rg`ontepa', 'qo`shko`pir', 'qo`shrabot', 'qo`ng`irot', 'qo`ytosh'],
 'a': ['qoaling'],
 'b': ['qobuqiraq',
       'qobadabad',
       'qobuustu',
       'qobustan',
       'qobadlu',
       'qobong',
       'qobad',
       'qobuz',
       'qobu'],
 'c': ['qocaqqazma',
       'qoc@hm@dli',
       'qocb@yli',
       'qocd@r@',
       'qocali',
       'qoculu',
       'qocho',
       'qoca'],
 'd': ['qodratabad',
       'qodashim',
       'qodshim',
       'qodsian',
       'qodesh',
       'qodman',
       'qod@s@',
       'qods',
       'qod'],
 'e': ['qoe'],
 'f': ['qoftsa', 'qofas', 'qof'],
 'g': ['qogir'],
 'h': ['qohandiz',
       'qoheleth',
       'qohestan',
       'qohaito',
       'qohelet',
       'qohurd',
       'qohrud',
       'qohab'],
 'i': ['qoigyijabu', 'qoiri', 'qoi'],
 'j': ['qojiabad', 'qojer', 'qojur'],
 'k': ['qokang'],
 'l': ['qolovinovka',
       'qolqolabad',
       'qolomongma',
       'qolsaerif',
       'qolsharif',
       'qollasuyu',
       'qoldarreh',
       'qolyaqol',
       'qoliabad',
       'qolsarif',
       'qolqati',
       'qollmay',
       'qolq@ti',
       'qolasta',
       'qolundy',
       'qolusta',
       'qolqol',
       'qollca',
       'qoltuq',
       'qolian',
       'qollqa',
       'qolalu',
       'qolhak',
       'qolmas',
       'qolla',
       'qolca',
       'qol'],
 'm': ['qomoqomosauropus',
       'qomolangma',
       'qomoqomong',
       'qomemiyyut',
       'qomdarreh',
       'qomshaneh',
       'qomqaleh',
       'qomeshah',
       'qomishlu',
       'qomiabad',
       'qomlijeh',
       "qombo'ul",
       'qomchian',
       'qombovan',
       'qomishan',
       'qomsheh',
       'qomshan',
       'qomrud',
       'qomish',
       'qomqan',
       'qomik',
       'qomam',
       'qomul',
       'qomuz',
       'qoma',
       'qom'],
 'n': ['qongqotwane',
       'qonaqk@nd',
       'qontisuyu',
       'qonqurtai',
       'qonggyai',
       'qongrats',
       'qonaqli',
       'qonduz',
       'qontis',
       'qonce'],
 'o': ['qoorlugud',
       'qoop.com',
       'qoornoq',
       'qooxdoo',
       'qooder',
       'qooney',
       'qoo10',
       'qoob',
       'qoop',
       'qoo'],
 'p': ['qopiwini', 'qoppoz', 'qoph'],
 'q': ['qoq-orda', 'qoqfin', 'qoqek'],
 'r': ['qoraqalpoghiston',
       'qoriwayrachina.',
       'qoriwayrachina',
       'qorlortorsuaq',
       'qorovulbozor',
       'qoreyshabad',
       'qoriwaqanki',
       'qorx-mazoba',
       'qorpo-santo',
       'qorbanabad',
       'qoridheere',
       'qorxmazoba',
       'qorao`zak',
       'qoradaryo',
       'qoruqbagi',
       'qoruqlar',
       'qorbanlu',
       'qoriltay',
       'qorako`l',
       'qoroqchi',
       'qoruglar',
       'qoryoley',
       'qoroltay',
       'qorahsin',
       'qorqoruk',
       'qoragan',
       'qordoba',
       'qorasuv',
       'qorovul',
       'qorqori',
       'qorghan',
       'qorivva',
       'qorculu',
       'qoryale',
       'qormihc',
       'qoraqir',
       'qorutak',
       'qorqan',
       'qorqor',
       'qordis',
       'qorveh',
       'qorgan',
       'qorvis',
       'qorban',
       'qoriq',
       'qormi',
       'qoruq',
       'qorcu',
       'qorab',
       'qorma',
       'qorvo',
       'qorve',
       'qoroq',
       'qorei',
       'qoros',
       'qorqi',
       'qorah',
       'qorna',
       'qoro',
       'qore',
       'qora',
       'qor'],
 's': ['qosqophryne',
       'qosmaliyon',
       'qosaqislaq',
       'qosmeliyon',
       'qosaqovaq',
       'qosmalyan',
       'qosabulaq',
       'qostanai',
       'qosak@nd',
       'qostanay',
       'qossiyeh',
       'qoshalaq',
       'qoslawic',
       'qosadiz@',
       'qosaoba',
       'qosimov',
       'qos@l@r',
       'qosseir',
       'qosabeh',
       'qoscaq',
       'qosasu',
       'qosmio',
       'qosbeh',
       'qosira',
       'qosja',
       'qosun',
       'qosfc',
       'qosur',
       'qosta',
       'qosqo',
       'qosa',
       'qosi',
       'qos'],
 't': ['qotbzadeh',
       'qotbabad',
       'qoturlar',
       'qotbiyeh',
       'qotanlu',
       'qoturlu',
       'qotsfc',
       'qottab',
       'qotsa',
       'qotlu',
       'qotan',
       'qotd',
       'qots'],
 'u': ['qounfuzed'],
 'v': ['qovlarsari', 'qovsudlu', 'qovusuq', 'qovurma', 'qovlar', 'qovaq'],
 'w': ['qowowuyag',
       'qowzlojeh',
       'qowzlujeh',
       'qownnotes',
       'qowsheh',
       'qowland',
       'qow'],
 'x': ['qoxmuq', 'qox'],
 'y': ['qoyunbin@si', 'qoydan'],
 'z': ['qozlubulaq',
       'qozbabali',
       'qozqarali',
       'qozlijeh',
       'qozagaci',
       'qozd@r@',
       'qozloq',
       'qozlu']}
