
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ua = {'_': ['ua-fairbanks',
       'ua-columbia',
       'ua-football',
       'ua:kultura',
       'ua:first',
       'ua-ildak',
       'ua-1919',
       'ua-huka',
       'ua1919',
       'ua/col',
       'ua-pou',
       'ua120',
       'ua232',
       'ua811',
       'ua175',
       'ua93',
       'ua1',
       'ua2'],
 'a': ['uaap', 'uaaf', 'uaar', 'uaaa', 'uaai', 'uaa'],
 'b': ['uabrs', 'uaboe', 'uabcs', 'uabc', 'uaba', 'uab'],
 'c': ['uachtaran',
       'uachdar',
       'uacilla',
       'uacari',
       'uacaba',
       'uaces',
       'uacam',
       'uaca',
       'uacn',
       'uacv',
       'uacc',
       'uacp',
       'uace',
       'uach',
       'uac'],
 'd': ['uadjit', 'uadjet', 'uadji', 'uade', 'uad'],
 'e': ['uaenic', 'uaecne', 'uaeaf', 'uaem', 'uae'],
 'f': ['uafato', 'uafs', 'uafa', 'uafm', 'uaf'],
 'g': ['uag'],
 'h': ['uahuntsville', 'uahuka', 'uahc', 'uahs', 'uah'],
 'i': ['uaipan-tepui',
       'uaitemuri',
       'uaithne',
       'uaiuais',
       'uaiuara',
       'uaithni',
       'uaiana',
       'uaica',
       'uaiev',
       'uaine',
       'uaioe',
       'uair',
       'uai'],
 'j': ['uaj'],
 'k': ['uakitite', 'uakaris', 'uakari', 'uakit', 'uakti', 'uak'],
 'l': ['ualuealuealeuale',
       'ualfrance.fr',
       'ualalapi',
       'ual.com',
       'uallach',
       'ual811',
       'ual232',
       'ual.de',
       'ualefi',
       'ualac',
       'uala',
       'ualr',
       'uale',
       'ualg',
       'ual'],
 'm': ['uamsho', 'uamsan', 'uamba', 'uamps', 'uamce', 'uams', 'uamc', 'uam'],
 'n': ['uanheta', 'uanda', 'uanna', 'uanc', 'uani', 'uan'],
 'o': ['uaoc-c', 'uaoc', 'uao'],
 'p': ['uapacinae',
       'uapixanas',
       'uapsat-1',
       'uapaca',
       'uaprof',
       'uapila',
       'uapou',
       'uapp',
       'uap1',
       'uapl',
       'uapb',
       'uap'],
 'q': ['uaq'],
 'r': ['uarbryichthys',
       'uarsheikh',
       'uarctic',
       'uardry',
       'uarini',
       'uaroo',
       'uart',
       'uaru',
       'uarl',
       'uars',
       'uar'],
 's': ['uastyrdzhi',
       'uastyrji',
       'uasvmcn',
       'uashat',
       'uaser',
       'uasal',
       'uasom',
       'uasd',
       'uasb',
       'uas7',
       'uasc',
       'uasp',
       'uasa',
       'uas'],
 't': ['uatchitodon',
       'uathach',
       'uatlok',
       'uatuc',
       'uatwm',
       'uatv',
       'uata',
       'uatx',
       'uath',
       'uatu',
       'uat'],
 'u': ['uaua', 'uau'],
 'v': ['uavision', 'uavcan', 'uavs'],
 'w': ['uaw:ea', 'uaw/mf', 'uawc', 'uawa', 'uawm', 'uaw'],
 'x': ['uaxactan', 'uaxactun'],
 'y': ['uaymil', 'uayma', 'uay'],
 'z': ['uaz-patriot', 'uaz-469b', 'uaz-469', 'uaz-452', 'uaz']}
