
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_q_ = {'_': ['q+/papias_hypothesis',
       'q103_cambridge',
       'q0957_561a/b',
       'q101_chicago',
       'q-2c_firebee',
       'q._palustris',
       'q-1_predator',
       'q-1_eridani',
       'q._gracilis',
       'q._lazzarus',
       'q._roscius',
       'q._patrick',
       'q0957_561a',
       'q2_stadium',
       'q0957_561b',
       'q3_academy',
       'q-5_fantan',
       'q1_eridani',
       'q._skinner',
       'q._serrata',
       'q9_method',
       'q._martel',
       'q0957_561',
       'q-1_visa',
       'q._104.3',
       'q1_mall',
       'q_104.3',
       'q13_fox',
       'q103_fm',
       'q._wang',
       'q33_ny',
       'q94_fm',
       'q._roo',
       'q._ei',
       'q_102',
       'q_40',
       'q_94',
       'q_10',
       'q_30',
       'q_95',
       'q_35',
       'q_22',
       'q_38',
       'q_92',
       'q_45',
       'q_2',
       'q_4',
       'q_6',
       'q_1',
       'q_5',
       'q_9',
       'q_7',
       'q_3'],
 'a': ["q'anjobalan_languages",
       "q'anjob'al_language",
       "q'anjob'al_people",
       "q'awiri_qullu",
       "q'ara_willk'i",
       "q'atawi_qullu",
       "q'ara_wayuna",
       'q&a_software',
       'q_arithmetic',
       "q'ara_qullu",
       "q'asa_pata",
       'q_awards',
       'q_angle',
       'q_award'],
 'b': ['q-binomial_coefficient',
       'q-bessel_polynomials',
       'q-bio_conference',
       'q@b@l@_muskurlu',
       'q-bert_spuckler',
       'q.b._cooler',
       'q_basic',
       'q_ball',
       'q_band',
       'q_boat',
       'q_bus'],
 'c': ['q-charlier_polynomials',
       'q-charlier_polynomial',
       'q-celtic_hypothesis',
       'q-chastic_ep',
       'q_clearance',
       'q_centauri',
       'q-cells_ag',
       'q_carinae',
       'q_casino',
       'q_center',
       'q_celtic',
       'q_course',
       'q_cygni',
       'q_cycle',
       'q_codes',
       'q_class',
       'q_camp',
       'q_code',
       'q_car'],
 'd': ['q-difference_polynomial',
       'q-difference_equation',
       'q-dyson_conjecture',
       'q@dirli,_masally',
       'q@dili,_qubadli',
       'q@dili,_samukh',
       'q@dirli,_tovuz',
       'q.d._leavis',
       'q_division',
       'q_document',
       'q_disease',
       'q.d._wang',
       'q_dot'],
 'e': ['q-exponential_distribution',
       'q-expansion_principle',
       "q'eqchi'_language",
       'q_entertainment',
       'q_eridani'],
 'f': ['q_function', 'q_factor', 'q_fever', 'q_feel'],
 'g': ['q-gaussian_distribution',
       'q-gaussian_process',
       'q-gamma_function',
       'q_gospel',
       'q_games'],
 'h': ['q@hr@manli,_beylagan',
       'q-hahn_polynomials',
       'q@hr@manli,_barda',
       'q_hayashida',
       'q_hook'],
 'i': ["q'illu_suchusqa",
       "q'illu_apachita",
       "q'illu_pachaka",
       "q'illu_qisqa",
       "q'illu_q'asa",
       "q'illu_salli",
       "q'illu_urqu",
       "q'inqu_mayu",
       'q_is'],
 'j': ['q-jacobi_polynomials'],
 'k': ['q-krawtchouk_polynomials', 'q-konhauser_polynomials'],
 'l': ['q-laguerre_polynomials', 'q@l@bin,_mistan', 'q_learning', 'q_lazzarus'],
 'm': ['q-meixner-pollaczek_polynomials',
       'q-meixner_polynomials',
       'q-mac_electronics',
       'q_methodology',
       'q_multiplier',
       'q_manuscript',
       'q_monthly',
       'q_martel',
       'q_method',
       'q_metal',
       'q_meter',
       'q_mack'],
 'n': ['q_number', 'q_news', 'q_n'],
 'o': ["q'orianka_kilcher"],
 'p': ['q-pochhammer_symbol',
       'q-pochammer_symbol',
       'q-par_angus',
       'q_patrick',
       'q_project',
       'q_planes',
       'q_puppis',
       'q_pid'],
 'q': ['q-q_plot'],
 'r': ['q-racah_polynomials',
       'q-racah_polynomial',
       'q_representation',
       'q@ribli,_agdash',
       'q@rv@nd,_fuzuli',
       'q@rv@nd,_agdam',
       'q@ribli,_tovuz',
       'q.r.s._boys',
       'q_rating',
       'q_radio',
       'q_road'],
 's': ['q-shifted_factorial',
       'q-switched_lasers',
       'q-switched_laser',
       'q.s._serafijn',
       'q_switching',
       'q_squared',
       'q_signals',
       'q_scorpii',
       'q_switch',
       'q_source',
       'q_series',
       'q_signal',
       'q_school',
       'q_score',
       'q_sound',
       'q_sharp',
       'q_ship',
       'q_star',
       'q_sort'],
 't': ['q-tip_discography',
       'q-theta_function',
       'q-type_asteroid',
       'q_television',
       'q_texture',
       'q-tee_spy',
       'q.t._hush',
       'q_theatre',
       'q_tips',
       'q_tour',
       'q_tip',
       'q_tv'],
 'u': ["q'umir_pata", "q'uwa_qullu", "q'uwa_laki"],
 'v': ['q-vandermonde_identity', 'q_velorum', 'q_value'],
 'w': ['q-weibull_distribution', 'q_waves', 'q_wave', 'q_who'],
 'z': ['q@zli,_sabirabad', 'q@zyan,_qubadli', 'q@zli,_ismailli']}
