
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_aq = {'aq_bars_kazan': 'ak_bars_kazan',
 'aqa_ali_shah': 'aga_khan_ii',
 'aqa_mahdi_puya': 'mahdi_puya',
 'aqiba_ben_joseph': 'akiva_ben_joseph',
 'aqm_badruddoza_chowdhury': 'a._q._m._badruddoza_chowdhury',
 'aqua_florum_omnium': 'aqua_omnium_florum',
 'aqua_lung_international': 'aqua_lung_america',
 'aqua_teen_hungerforce': 'aqua_teen_hunger_force',
 'aqua_vergine_aqueduct': 'acqua_vergine',
 'aquae_calidae_neapolitanorum': 'aquae_neapolitanae',
 'aqualand_el_arenal': 'aqualand',
 'aqualung_live_2005': 'aqualung_live',
 'aquanox_2:_revelation': 'aquanox',
 'aquarelle_of_brazil': 'aquarela_do_brasil',
 'aquarian_concepts_community': 'global_community_communication_alliance',
 'aquarian_nation_records': 'francis_dunnery',
 'aquarium_fish_magazine': 'aquarium_fish_international',
 'aquarium_of_montreal': 'montreal_aquarium',
 'aquarium_of_pacific': 'aquarium_of_the_pacific',
 'aquarium_rescue_unit': 'col._bruce_hampton_and_the_aquarium_rescue_unit',
 'aquariums_of_pyongyang': 'the_aquariums_of_pyongyang',
 'aquarius_dwarf_galaxy': 'aquarius_dwarf',
 'aquarius_forest_reserve': 'aquarius_national_forest',
 'aquarius_platinum_limited': 'aquarius_platinum',
 'aquateen_hunger_force': 'aqua_teen_hunger_force',
 'aquatic_ape_theory': 'aquatic_ape_hypothesis',
 'aquatic_mammal_dolphin': 'dolphin',
 'aquatic_timing_systems': 'aquatic_timing_system',
 'aqueduct_of_sylvius': 'cerebral_aqueduct',
 'aqueduct_race_track': 'aqueduct_racetrack',
 'aqueducts_in_rome': 'roman_aqueduct',
 'aqueducts_of_rome': 'roman_aqueduct',
 'aqueduto_da_carioca': 'carioca_aqueduct',
 'aqueous_hydrogen_chloride': 'hydrochloric_acid',
 'aqueous_hydrogen_sulfide': 'sulfuric_acid',
 'aqueous_normal_phase': 'aqueous_normal_phase_chromatography',
 'aquiba_ben_joseph': 'akiva_ben_joseph',
 'aquila_and_priscilla': 'priscilla_and_aquila',
 'aquila_audax_fleayi': 'tasmanian_wedge-tailed_eagle',
 'aquila_heliacea_adalberti': 'spanish_imperial_eagle',
 'aquila_heliacea_heliacea': 'eastern_imperial_eagle',
 'aquila_of_pontus': 'aquila_of_sinope',
 'aquila_rapax_nipalensis': 'steppe_eagle',
 'aquila_rapax_rapax': 'tawny_eagle',
 'aquilinus_of_cologne': 'aquilinus_of_milan',
 'aquilla_james_dyess': 'aquilla_j._dyess',
 'aquin_components_gmbh': 'aquin_components',
 'aquired_hypertrichosis_lanuginosa': 'hypertrichosis',
 'aquired_immune_response': 'adaptive_immune_system'}
        