
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_xh = {'_': ['xh_a1'],
 'a': ['xhaaidlagha_gwaayaai',
       'xhaaydla_gwaayaay',
       'xhavit_bajrami',
       'xhavit_demneri',
       'xhavit_haliti',
       'xhafer_tahiri',
       'xhanfise_keko',
       'xhanfize_keko',
       'xhafer_spahiu',
       'xhafer_sadik',
       'xhaferr_deva',
       'xhafer_deva',
       'xhafer_ypi'],
 'e': ['xhemahalle_complex',
       'xhezair_zaganjori',
       'xhevahir_kapllani',
       'xhensila_myrtezaj',
       'xhemal_deliallisi',
       'xhelal_koprencka',
       'xhevdet_llumnica',
       'xhemal_aranitasi',
       'xhevat_kelmendi',
       'xherdan_shaqiri',
       'xhemail_mustafa',
       'xhemile_berisha',
       'xhevdet_shabani',
       'xhemal_gjunkshi',
       'xhevahir_spahiu',
       'xhesika_berberi',
       'xhevdet_shaqiri',
       'xhejna_metalja',
       'xhelil_abdulla',
       'xhezair_teliti',
       'xhevdet_bajraj',
       'xhevdet_muriqi',
       'xhemal_bushati',
       'xhevad_prekazi',
       'xhevahir_sukaj',
       'xheyahir_sukaj',
       'xhevdet_picari',
       'xhevat_prekazi',
       'xhemail_abria',
       'xhelal_miroci',
       'xhersild_haka',
       'xhelil_asani',
       'xhemal_naipi',
       'xhevdet_gela',
       'xhevdet_doda',
       'xhelil_gjoni',
       'xhemal_kondi',
       'xhelal_juka',
       'xheni_karaj',
       'xhemil_dino',
       'xhemo_hasa',
       'xhem_hasa',
       'xhech_tv'],
 'g': ['xhgc_5'],
 'i': ['xhino_sejdo'],
 'j': ['xhjst_-tv'],
 'n': ['xhngs_96.7'],
 'o': ['xhosa_cattle-killing',
       'xhorxhia_kristollari',
       'xhosa_literature',
       'xhoaphryx_lemeei',
       'xhonatan_lajthia',
       'xhosa_wikipedia',
       'xhosan_language',
       'xhovalin_delia',
       'xhosa_alphabet',
       'xhorxhian_boci',
       'xhosa_calendar',
       'xhosa_language',
       'xhoni_athanas',
       'xhoi_hajderaj',
       'xhosa_people',
       'xhon_marinaj',
       'xhol_caravan',
       'xhosa_months',
       'xhosa_music',
       'xhoana_nano',
       'xhosa_wars',
       'xhosa_war'],
 't': ['xhtml_modularization',
       'xhtml_modules',
       'xhtml_element',
       'xhtml_basic',
       'xhtml_1.0',
       'xhtml_mp',
       'xhtml_5'],
 'u': ['xhunashi_caballero',
       'xhuliano_kamberaj',
       'xhulia_xhindole',
       'xhuliano_skuka',
       'xhulian_rrudho',
       'xhuljo_mehmeti',
       'xhulio_jaupi',
       'xhuljo_colla',
       'xhuljo_tushi'],
 'y': ['xhynejt_cutra']}
