
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ij = {'_': ['ij_paderewski',
       'ij_wickrema',
       'ij,_zanjan',
       'ij_parker',
       'ij,_iran',
       'ij_river',
       'ij_good'],
 'a': ['ijamsville,_maryland',
       'ijamsville,_indiana',
       'ijara_constituency',
       'ijahnya_christian',
       'ijaharul_hussain',
       'ijara_district',
       'ijaw_languages',
       'ijah_anderson',
       'ijaz_hussain',
       'ijazul_ahsan',
       'ijad_madisch',
       'ijahman_levi',
       'ijaw_youths',
       'ijaw_people',
       'ijah_halley',
       'ijaz_ahmed',
       'ijaz_faqih',
       'ijaz_masih',
       'ijaz_mirza',
       'ijaw_youth',
       'ijaz_butt',
       'ijaz_khan',
       'ijang_ui'],
 'e': ['ijeoma_ndukwe-egwuronu',
       'ijeoma_nwaogwugwu',
       'ijevan_dendropark',
       'ijemskii_district',
       'ijemskiy_district',
       'ijem_onwuamaegbu',
       'ijeoma_umebinyuo',
       'ijemski_district',
       'ijele_masquerade',
       'ijemsky_district',
       'ijeoma_egbunine',
       'ijeoma_uchegbu',
       'ijemskiy_raion',
       'ijemskii_raion',
       'ijebu_kingdom',
       'ijemski_raion',
       'ijemsky_raion',
       'ijebu_people',
       'ijebu_north',
       'ijeoma_john',
       'ijeoma_oluo',
       'ijero_ekiti',
       'ijebu,_owo',
       'ijeoma_obi',
       'ijebu_east',
       'ijebu_igbo',
       'ije_tebab',
       'ijebu_ode'],
 'f': ['ijf_blokker'],
 'i': ['ijimaia_plicatellus',
       'ijivitari_district',
       'ijichi_kiyoshi',
       'ijichi_kosuke',
       'ijiri_station',
       'ijiel_protti',
       'ijiri_okada',
       'ijira_river',
       'iji_castle'],
 'k': ['ijke_buisma', 'ijkm_keys', 'ijkl_keys'],
 'l': ['ijlil_al-shamaliyya', 'ijlil_al-qibliyya'],
 'm': ['ijmuiden_heliport', 'ijmuider_courant', 'ijm_corporation', 'ijm_corp'],
 'n': ['ijn_yamashiro',
       'ijn_kirishima',
       'ijn_musashi',
       'ijn_shinano',
       'ijn_ayanami',
       'ijn_nagato',
       'ijn_haruna',
       'ijn_yamato',
       'ijn_nachi',
       'ijn_hiei',
       'ijn_ise'],
 'o': ['ijoid_languages',
       'ijo_languages',
       'ijora,_lagos',
       'ijon_tichy',
       'ijo_people',
       'ijo_temple'],
 'r': ['ijrud_county'],
 's': ['ijsselmonde,_rotterdam',
       'ijsselmeer_polders',
       'ijsbrand_chardon',
       'ijsbrand_godske',
       'ijssel_river',
       'ijssel_line'],
 't': ['ijtihadi_family', 'ijteba_nadwi'],
 'u': ['ijuin,_kagoshima',
       'ijuizinho_river',
       'ijuin_hikokichi',
       'ijuin_tadaaki',
       'ijumaa_mosque',
       'ijuin_station',
       'ijuw_district',
       'ijui_airport',
       'iju_seiichi',
       'ijuin_goro',
       'ijui_river',
       'iju,_ogun'],
 'y': ['ijyaraj_singh'],
 'z': ['ijzeren_rita']}
