import libcst
from typing import Any

class Visitor(libcst.CSTVisitor): ...

class Transformer(libcst.CSTTransformer):
    ImportALIAS: Any
    RequiredLookupImport: Any
    def __init__(self, visitor) -> None: ...
    def leave_ImportAlias_asname(self, node) -> None: ...
    def leave_Module(self, original_node, updated_node): ...
    def leave_Call(self, node, updated_node): ...
