
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_dv = {'_': ['dv6000z', 'dv386', 'dv25', 'dv12', 'dv50', 'dv8', 'dv3'],
 'a': ['dvadasamanjarika-stotra',
       'dvalishvili',
       'dvakacovice',
       'dvargantis',
       'dvarapalas',
       'dvarcionys',
       'dvarchive',
       'dvadasaha',
       'dvaravati',
       'dvarapala',
       'dvaletia',
       'dvarsatt',
       'dvaraka',
       'dvandva',
       'dvaleti',
       'dvalinn',
       'dvarka',
       'dvaita',
       'dvarim',
       'dvabzu',
       'dvalin',
       'dvach',
       'dvals',
       'dvali',
       'dvas',
       'dvar',
       'dva'],
 'b': ['dvbviewer',
       'dvb-data',
       'dvb-cpcm',
       'dvb-iptv',
       'dvb-mpeg',
       'dvb-h/sh',
       'dvb-html',
       'dvb-mhp',
       'dvb-rip',
       'dvb-rcs',
       'dvb-ipi',
       'dvb-csa',
       'dvb-s2x',
       'dvb-vbi',
       'dvb-txt',
       'dvb-sub',
       'dvb-rct',
       'dvb-sh',
       'dvb-si',
       'dvb-ms',
       'dvb-ca',
       'dvb-t2',
       'dvbrip',
       'dvb-ci',
       'dvb-s2',
       'dvb-h',
       'dvbjj',
       'dvbbs',
       'dvb-m',
       'dvbst',
       'dvb-t',
       'dvb-x',
       'dvbs2',
       'dvb-s',
       'dvb-c',
       'dvbc',
       'dvbh',
       'dvbs',
       'dvb'],
 'c': ['dvcreators.net', 'dvc-pro', 'dvcpro', 'dvcs', 'dvca', 'dvc'],
 'd': ['dvdempire.com',
       'dvd+rw-tools',
       'dvd-by-mail',
       'dvd-writers',
       'dvd-writer',
       'dvdisaster',
       'dvdactive',
       'dvd-forum',
       'dvdxpress',
       'dvd-audio',
       'dvdshrink',
       'dvd-video',
       'dvdripper',
       'dvdstyler',
       'dvdxcopy',
       'dvd-roms',
       'dvd-ram',
       'dvdplus',
       'dvd-rom',
       'dvdtalk',
       'dvd-r/w',
       'dvd-jon',
       'dvd-rip',
       'dvd/vcr',
       'dvdcca',
       'dvd-rw',
       'dvd-14',
       'dvd-dl',
       'dvd-vr',
       'dvdrip',
       'dvd+vr',
       'dvd+-r',
       'dvdfab',
       'dvdscr',
       'dvd-r9',
       'dvdram',
       'dvd43',
       'dvd6c',
       'dvd-r',
       'dvdpg',
       'dvd-a',
       'dvdrw',
       'dvd-d',
       'dvd18',
       'dvdtv',
       'dvdr',
       'dvds',
       'dvdi',
       'dvda',
       'dvd'],
 'e': ['dvellecanus',
       'dvergsoya',
       'dvenadsat',
       'dvergsdal',
       'dvergatal',
       'dverberg',
       'dveselu',
       'dverger',
       'dveikus',
       'dveykus',
       'dvergar',
       'dvergr',
       'dveri',
       'dve'],
 'f': ['dvfs', 'dvfr'],
 'g': ['dvga', 'dvgs', 'dvg'],
 'h': ['dvhw', 'dvhd', 'dvhs', 'dvh'],
 'i': ['dvirkivshchyna',
       'dvinosauroidea',
       'dvi-lanthanum',
       'dvi-manganese',
       'dvirkivschyna',
       'dvinosauridae',
       'dvigatelstroy',
       'dvilanthanum',
       'dvinosauria',
       'dvi-digital',
       'dvinosaurus',
       'dviniidae',
       'dvinosaur',
       'dvice.com',
       'dvinskoy',
       'dvipdfmx',
       'dvigatel',
       'dvinitsa',
       'dvied-ep',
       'dvigrad',
       'dvipdfm',
       'dvivida',
       'dvinsk',
       'dvipng',
       'dvicio',
       'dvinia',
       'dviete',
       'dvirah',
       'dvipdf',
       'dvi-dl',
       'dvija',
       'dvi-i',
       'dvina',
       'dvips',
       'dvigu',
       'dvi-d',
       'dvipa',
       'dvi-a',
       'dvira',
       'dvisd',
       'dvin',
       'dvir',
       'dvic',
       'dvi'],
 'j': ['dvj-1000', 'dvj1000', 'dvj-x1'],
 'k': ['dvke', 'dvk'],
 'l': ['dvl1', 'dvlp', 'dvlf', 'dvl2', 'dvlc', 'dvlr', 'dvl3', 'dvla', 'dvl'],
 'm': ['dvmrp', 'dvm'],
 'n': ['dvno', 'dvnp', 'dvn'],
 'o': ['dvorniky-vcelare',
       'dvorak.org/blog',
       'dvoryanskoye',
       'dvoryanstvo',
       'dvoevlastie',
       'dvorishnevo',
       'dvokodvweni',
       'dvoynovsky',
       'dvoragyukh',
       'dvorishchi',
       'dvorovenko',
       'dvorkovich',
       'dvorishche',
       'dvoyezyory',
       'dvoretzky',
       'dvorichna',
       'dvorianky',
       'dvorskoye',
       'dvoryanin',
       'dvoranci',
       'dvorovoi',
       'dvoynovo',
       'dvoryans',
       'dvoyanka',
       'dvorjane',
       'dvoriste',
       'dvorniky',
       'dvoracek',
       'dvoryane',
       'dvorian',
       'dvorets',
       'dvoriki',
       'dvorane',
       'dvoryan',
       'dvorska',
       'dvornik',
       'dvorica',
       'dvortsy',
       'dvorsky',
       'dvorovi',
       'dvorak',
       'dvorec',
       'dvojka',
       'dvorah',
       'dvorce',
       'dvori',
       'dvora',
       'dvonn',
       'dvory',
       'dvoje',
       'dvon',
       'dvom',
       'dvor',
       'dvoa',
       'dvo'],
 'p': ['dvpb-hd', 'dvpl', 'dvp'],
 'r': ['dvrsnica', 'dvrmnhs', 'dvr-ms', 'dvrpc', 'dvrp', 'dvra', 'dvr'],
 's': ['dvsr', 'dvs1', 'dvsn', 'dvsc', 'dvs'],
 't': ['dvtk-eger', 'dvtk', 'dvt'],
 'u': ['dvulikiaspis', 'dvuluchnoye', 'dvu'],
 'v': ['dvvli', 'dvvld', 'dvvl'],
 'w': ['dvw'],
 'x': ['dvx100', 'dvx']}
