
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_db = {'_': ['db-2073',
       'db-soft',
       'db-alm',
       'db13w3',
       'db-ar1',
       'db289',
       'db-25',
       'db-15',
       'db-3t',
       'db2e3',
       'db320',
       'db-37',
       'db120',
       'db2/2',
       'db-2',
       'db-1',
       'db/2',
       'db-7',
       'db25',
       'db-3',
       'db23',
       'db15',
       'db4o',
       'db-5',
       'db-6',
       'db-4',
       'db-9',
       'db4',
       'db9',
       'db1',
       'db8',
       'db6',
       'db5',
       'db7',
       'db3'],
 'a': ['dbapparel',
       'dbass3/5',
       'dbayeh',
       'dbakan',
       'dbacks',
       'dbar1',
       'dbatc',
       'dbase',
       'dbap',
       'dbag',
       'dbal',
       'dba'],
 'b': ['dbbr', 'dbbd', 'dbbb', 'dbbp', 'dbbc', 'dbbk', 'dbbn', 'dbbo', 'dbb'],
 'c': ['dbclifford', 'dbcamp', 'dbcrid', 'dbcs', 'dbc1', 'dbcc', 'dbc'],
 'd': ['dbdesigner',
       'dbdmh',
       'dbdod',
       'dbdnv',
       'dbdos',
       'dbdpo',
       'dbdu',
       'dbde',
       'dbd'],
 'e': ['dbexpress', 'dbeaver', 'dbedit', 'dbeat', 'dbe'],
 'f': ['dbforge', 'dbfsd', 'dbf4', 'dbfo', 'dbfc', 'dbfx', 'dbfs', 'dbf'],
 'g': ['dbgallery', 'dbgp', 'dbgt', 'dbg'],
 'h': ['dbhs', 'dbh'],
 'i': ['dbix::class', 'dbi/dbd', 'dbia', 'dbit', 'dbi1', 'dbi'],
 'j': ['dbj'],
 'k': ['dbku', 'dbkl', 'dbk'],
 'l': ['dblspace', 'dbltools', 'dbl-583', 'dblp', 'dbl'],
 'm': ['dbmaestro',
       'dbmotion',
       'dbm/hz',
       'dbmss',
       'dbm0',
       'dbmw',
       'dbms',
       'dbm'],
 'n': ['dbndns',
       'dbndd2',
       'dbnpa',
       'dbngp',
       'dbna',
       'dbnr',
       'dbnl',
       'dbn1',
       'dbn'],
 'o': ['dbomp', 'dbox2', 'dbox', 'dbo'],
 'p': ['dbpoweramp', 'dbpedia', 'dbpsk', 'dbpro', 'dbpcs', 'dbpc', 'dbp'],
 'q': ['dbq'],
 'r': ['dbridge', 'dbrs9', 'dbrct', 'dbrn', 'dbr9', 'dbrs', 'dbr1', 'dbr'],
 's': ['dbscan',
       'dbsics',
       'dbsnp',
       'dbsk',
       'dbsu',
       'dbsa',
       'dbsp',
       'dbss',
       'dbso',
       'dbsg',
       'dbs'],
 't': ['dbtel', 'dbtss', 'dbta', 'dbtl', 'dbtt', 'dbtc', 'dbti', 'dbtg', 'dbt'],
 'u': ['dbu-can', 'dbus', 'dbu'],
 'v': ['dbv'],
 'w': ['dbw'],
 'x': ['dbx1', 'dbx2', 'dbx'],
 'y': ['dby'],
 'z': ['dbz:sagas', 'dbz:bl', 'dbzbl', 'dbz:s', 'dbzp', 'dbz']}
