
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rz = {'_': ['rz_piscium', 'rz_pyxidis', 'rz_normae', 'rz_gruis'],
 'a': ['rza-instrumental_experience',
       'rzasnik_wloscianski',
       'rzadka_wola-parcele',
       'rzasnik_szlachecki',
       'rza_discography',
       'rzanica,_serbia',
       'rzanovo,_struga',
       'rzad_narodowy',
       'rza_tahmasib',
       'rzadka_wola',
       'rza_hits'],
 'b': ['rzb_group'],
 'd': ['rzd_arena'],
 'e': ['rzeszow-khmelnytskyi_powerline',
       'rzeczyca_ziemianska-kolonia',
       'rzeczpospolita_zakopianska',
       'rzeszow-jasionka_airport',
       'rzepiennik_marciszewski',
       'rzepiennik_strzyzewski',
       'rzeszotary-stara_wies',
       'rzeczpospolita_polska',
       'rzeczyca_ziemianska',
       'rzeszow_voivodeship',
       'rzeczenica_commune',
       'rzecznik_patentowy',
       'rzepiennik_biskupi',
       'rzechta_druzbinska',
       'rzechowo_wielkie',
       'rzeczyca_okragla',
       'rzeszotary_gorne',
       'rzeczyca_commune',
       'rzepiennik_suchy',
       'rzecz_pospolita',
       'rzewuski_family',
       'rzeczyca_ksieza',
       'rzeczyca_wielka',
       'rzewnie_commune',
       'rzezawa_commune',
       'rzepin_pierwszy',
       'rzeczyca_mokra',
       'rzeczyca_sucha',
       'rzeszow_castle',
       'rzeszow_county',
       'rzepin_commune',
       'rzeczyca_dluga',
       'rzeczyca_mala',
       'rzeznik_drzew',
       'rzeki_wielkie',
       'rzepin_drugi',
       'rzeki_male'],
 'g': ['rzgow_pierwszy', 'rzgow_drugi'],
 'h': ['rzhevskoye_microdistrict',
       'rzhev-sychevka_offensive',
       'rzhev-vyazma_operation',
       'rzhaksinsky_district',
       'rzhevsky_district',
       'rzhanaya_polyana',
       'rzhevka_airport',
       'rzhevsky_family',
       'rzhevsky_uyezd',
       'rzhev_battles',
       'rzhd_cup'],
 'i': ['rzisce,_litija', 'rzionr_nrzfm'],
 'k': ['rzk_zagorje'],
 'u': ['rzucewo_culture', 'rzucewo_castle', 'rzuski_las'],
 'y': ['rzymsko_bg']}
