
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_kp = {'_': ['kp-sam_shingung',
       'kp_gopalkrishna',
       'kp_vivekananda',
       'kp_subdivision',
       'kp_namboodiris',
       'kp_paratroopa',
       'kp_technology',
       'kp_pieterson',
       'kp_anbalagan',
       'kp_episodes',
       'kp_candeth',
       'kp_bhaskar',
       'kp_2u-sova',
       'kp_kumaran',
       'kp01_danio',
       'kp_police',
       'kp_snacks',
       'kp_discos',
       'kp_saxena',
       'kp_khanal',
       'kp_appan',
       'kp_koopa',
       'kp_singh',
       'kp_sopot',
       'kp_media',
       'kp_index',
       'kp_duty',
       'kp_lodz',
       'kp_chen',
       'kp_nuts'],
 'a': ['kpatcha_gnassingbe',
       'kparblee_district',
       'kparia_waterfalls',
       'kpassagnon_gneto',
       'kpalaga_language',
       'kpandai_district',
       'kpanda_chiefdom',
       'kpayan_district',
       'kpasam_language',
       'kpala_language',
       'kpaka_chiefdom',
       'kpando_stadium',
       'kpalikpakpa_za',
       'kpati_language',
       'kpale_kpalime',
       'kpan_language',
       'kpalime_duga',
       'kpah_sherman',
       'kpac_lalitha',
       'kpana_lewis'],
 'd': ['kpd_1930+2752'],
 'e': ['kpendjal_prefecture',
       'kpele_prefecture',
       'kpelle_syllabary',
       'kpelle_language',
       'kpee_language',
       'kpelle_people',
       'kperou_guera'],
 'f': ['kpf_slonim'],
 'g': ['kpga_championship'],
 'h': ['kph_notoprojo'],
 'i': ['kpit_technologies', 'kpini_chugu'],
 'k': ['kpk_kumaran', 'kpk_menon'],
 'l': ['kpledjoo_festival', 'kplang_language', 'kpl_awards', 'kplx_tower'],
 'm': ['kpmg_international',
       'kpmg_consulting',
       'kpmb_architects',
       'kpmg_building',
       'kpmg_centre',
       'kpmg_trophy',
       'kpmg_center',
       'kpmg_tower',
       'kpmg_china',
       'kpm_trust',
       'kpm_music'],
 'n': ['kpn_telecompetitie',
       'kpn_eredivisie',
       'kpn_internet',
       'kpn_travels',
       'kpn_mobile',
       'kpn_retail',
       'kpn_tower',
       'kpn_award'],
 'o': ['kpodegbe_djigla',
       'kpong_airfield',
       'kpop_selection',
       'kposo_language',
       'kposo_people',
       'kpong_dam',
       'kpo_plus'],
 'p': ['kpp_best'],
 'r': ['kpr_kobierzyce', 'kpr_gopalan', 'kpr_114'],
 's': ['kps_9566-97',
       'kpss_tests',
       'kps_kielce',
       'kpss_test',
       'kps_gill',
       'kps_9566'],
 't': ['kpt_kuopio', 'kpt_tower', 'kpt_f.c.'],
 'u': ['kpuere_department'],
 'v': ['kpv_kokkola'],
 'w': ['kpwe_language'],
 'x': ['kpxm_tower']}
