
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_kc = {'_': ['kc-135e/r_stratotanker',
       'kc-135_stratotankers',
       'kc-135a_stratotanker',
       'kc-135r_stratotanker',
       'kc-135e_stratotanker',
       'kc-135t_stratotanker',
       'kc-135_stratotanker',
       'kc-97l_stratotanker',
       'kc-97g_stratotanker',
       'kc-97_stratotanker',
       'kc-130_hercules',
       'kc_sivasankaran',
       'kc_masterpiece',
       'kc_constantine',
       'kc-10_extender',
       'kc_motorgroup',
       'kc_concepcion',
       'kc_palanisamy',
       'kc_accidental',
       'kc_athletics',
       'kc_boutiette',
       'kc_streetcar',
       'kc_lightfoot',
       'kc_ohaebosim',
       'kc_mitchell',
       'kc_ramrakha',
       'kc_cariappa',
       'kc_spinelli',
       'kc-97_units',
       'kc_collins',
       'kc_bokadia',
       'kc_eusebio',
       'kc_wizards',
       'kc_johnson',
       'kc_college',
       'kc_hilites',
       'kc_ibrahim',
       'kc_montero',
       'kc_corkery',
       'kc_agrawal',
       'kc_douglas',
       'kc_stadium',
       'kc_lights',
       'kc_chiefs',
       'kc_irving',
       'kc_akshay',
       'kc_royals',
       'kc_groves',
       'kc_pillai',
       'kc_keeler',
       'kc_martel',
       'kc_rebell',
       'kc_porter',
       'kc_claffy',
       'kc_becker',
       'kc_reddy',
       'kc_jones',
       'kc_adams',
       'kc_james',
       'kc_ndefo',
       'kc_wolf',
       'kc_life',
       'kc_chan',
       'kc_pant',
       'kc-_45',
       'kc_rep',
       'kc_dey',
       'kc_zoo',
       'kc_ten',
       'kc_wu',
       'kc_87',
       'kc_85'],
 'a': ['kca_university', 'kca_bangalore', 'kca_deutag', 'kcal_9'],
 'b': ['kcbs-tv/fm_tower',
       'kcbx_terminals',
       'kcbs_pentagram',
       'kcbc_radio',
       'kcb_group'],
 'c': ['kcc_corporation',
       'kcc_chemical',
       'kcci_tower',
       'kcc_malls',
       'kcc_mall'],
 'e': ['kce_electronics',
       'kcet_studios',
       'kce_studios',
       'kcej_west',
       'kcen_tv'],
 'f': ['kcf_technologies', 'kcfcc_awards', 'kcfcc_award'],
 'g': ['kcg_holdings'],
 'h': ['kchung_radio'],
 'i': ['kci_konecranes', 'kci_airport'],
 'l': ['kclr_96fm'],
 'n': ['kcnq_channels'],
 'o': ['kcom_group'],
 'r': ['kcr_106.7', 'kcr_east', 'kcr_cro', 'kcr_fm', 'kcra_3'],
 's': ['kcskehat_limestone', 'kcs_railway', 'kcsp_fm'],
 'u': ['kcu_falcons'],
 'y': ['kcynia_commune']}
