
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_uh = {'_': ['uh-downtown_station',
       'uh-university_park',
       'uh-19_chickasaw',
       'uh-60_blackhawk',
       'uh-34_seahorse',
       'uh-1n_iroquois',
       'uh-1_iroquois',
       'uh-72a_lakota',
       'uh-72_lakota',
       'uh_libraries',
       'uh-1y_venom',
       'uh_islands',
       'uh-1a_huey',
       'uh-oh_oreo',
       'uh_cougars',
       'uh-1h_huey',
       'uh-1n_huey',
       'uh-1_huey',
       'uh_system',
       'uh_county',
       'uh_racing',
       'uh_atoll',
       'uh_manoa',
       'uh_mamma',
       'uh_river',
       'uh_hilo',
       'uh_huh',
       'uh_25',
       'uh_60',
       'uh_oh'],
 'a': ['uhangri_formation',
       'uhami_language',
       'uhamu_kanzibe',
       'uhaul_lesbian',
       'uharie_river'],
 'c': ['uhc_stockerau', 'uhc_zugerland'],
 'e': ['uhehlia_nerissidioides',
       'uhehlia_pardalis',
       'uherce_mineralne',
       'uherske_hradiste',
       'uhersko,_ukraine',
       'uhelna_pribram',
       'uhersky_ostroh',
       'uheiji_uehata',
       'uhersky_brod',
       'uhehe_fiscal',
       'uhehe_shrike'],
 'f': ['uhf_follow-on',
       'uhf_connector',
       'uhf_algebra',
       'uhf-tv_inc.',
       'uhf_anime',
       'uhf_radio',
       'uhf_ii',
       'uhf_cb'],
 'h': ['uhh_ahh'],
 'j': ['uhj_format'],
 'l': ['uhlerstown-frenchtown_bridge',
       'uhlerstown,_pennsylvania',
       'uhlorchestia_uhleri',
       'uhlirske_janovice',
       'uhligia_schilskyi',
       'uhlenhorster_hc',
       'uhlenhuth_test',
       'uhlirska_lhota',
       'uhlovitsa_cave',
       'uhland,_texas',
       'uhl,_kansas',
       'uhl_anomaly',
       'uhl_pottery',
       'uhl_albayt',
       'uhl_river',
       'uhl_belk'],
 'm': ['uhm_hyun-kyung',
       'uhm_tae-woong',
       'uhm_jung-hwa',
       'uhm_bok-dong',
       'uhm_warriors',
       'uhm_tae-goo',
       'uhm_ji-won',
       'uhm_jiwon'],
 'n': ['uhn_tiss'],
 'o': ['uhorska_ves', 'uhoh_oreo', 'uhod_road', 'uhod_area'],
 'r': ['uhrichsville,_ohio',
       'uhrovske_podhradie',
       'uhrkuenni_battery',
       'uhrenmuseum_beyer',
       'uhreticka_lhota',
       'uhrik_truckers'],
 't': ["uhthoff's_phenomenon", 'uhtred_ragnarson', 'uhtju_islands', 'uht_milk'],
 'u': ['uhunoma_osazuwa',
       'uhuru_monument',
       'uhuru_movement',
       'uhuru_kenyatta',
       'uhuru_hamiter',
       'uhuru_stadium',
       'uhuru_gardens',
       'uhudler_wine',
       "uhura's_song",
       'uhuru_design',
       'uhuru_mobile',
       'uhuru_afrika',
       'uhuru_times',
       'uhuru_torch',
       'uhura_mazda',
       'uhuru_park',
       'uhuru_peak'],
 'v': ['uhv_jaguars'],
 'w': ['uhw_west'],
 'y': ['uhy_advisors']}
