
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_yv = {'a': ['yvaine', 'yvain', 'yvan', 'yva'],
 'b': ['yvb'],
 'e': ['yverdon-les-bains',
       'yverdon-sport',
       'yvetot-bocage',
       'yves-gomezee',
       'yvernaumont',
       'yvecrique',
       'yvelines',
       'yversay',
       'yverdun',
       'yverdon',
       'yvetot',
       'yvesia',
       'yvette',
       'yvert',
       'yves',
       'yven',
       'yvel',
       'yve'],
 'g': ['yvgenie', 'yvg'],
 'h': ['yvhs'],
 'i': ['yville-sur-seine', 'yvignac-la-tour', 'yvignac', 'yviers', 'yvias'],
 'j': ['yvj'],
 'm': ['yvmdfl', 'yvm'],
 'o': ['yvoy-le-marron',
       'yvonand',
       'yvoire',
       'yvonne',
       'yvorne',
       'yvoir',
       'yvon',
       'yvo4',
       'yvo'],
 'p': ['yvp'],
 'q': ['yvq'],
 'r': ['yvrac-et-malleyrand',
       'yvre-le-polin',
       "yvre-l'eveque",
       'yvridiosuchus',
       'yvrencheux',
       'yvrandes',
       'yvretta',
       'yvrench',
       'yvrac',
       'yvras',
       'yvrr',
       'yvr'],
 't': ['yvto', 'yvt'],
 'v': ['yvv']}
