
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_xf = {'_': ['xf86config',
       'xf-106',
       'xf8u-3',
       'xf-103',
       'xf-109',
       'xf-108',
       'xf7f-1',
       'xf-104',
       'xf-92a',
       'xf-84h',
       'xf-92',
       'xf-12',
       'xf-91',
       'xf-11',
       'xf109',
       'xf108',
       'xf-90',
       'xf-87',
       'xf-89',
       'xf-73',
       'xf-85',
       'xf-88',
       'xf-7',
       'xf5u',
       'xf86',
       'xf8b',
       'xf5',
       'xf4',
       'xf2',
       'xf3',
       'xf6',
       'xf1'],
 'a': ['xfast', 'xfat', 'xfa'],
 'c': ['xfce4', 'xfcn', 'xfce'],
 'd': ['xfdisk', 'xfdtd', 'xfdl', 'xfd'],
 'e': ['xfera', 'xfest', 'xfer', 'xfem', 'xfe'],
 'f': ['xff'],
 'h': ['xfh'],
 'i': ['xfinity', 'xfixes', 'xfiles', 'xfire', 'xfile', 'xfig', 'xfi'],
 'l': ['xflow', 'xfld', 'xfl'],
 'm': ['xfmedia', 'xfml', 'xfm'],
 'n': ['xfn'],
 'o': ['xforce', 'xforms', 'xfone', 'xform', 'xfoil'],
 'p': ['xfp'],
 'r': ['xfreetype', 'xframes', 'xfree86', 'xfree', 'xfrog', 'xfr'],
 's': ['xfs'],
 't': ['xft'],
 'u': ['xfusion', 'xfund', 'xfu'],
 'v': ['xfv-12a', 'xfv-12', 'xfv-1', 'xfv'],
 'w': ['xfw'],
 'x': ['xfx'],
 'y': ['xfy']}
