# coding: utf-8

"""
    herd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.178.0-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class BusinessObjectDefinitionSubjectMatterExpert(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'business_object_definition_subject_matter_expert_key': 'BusinessObjectDefinitionSubjectMatterExpertKey'
    }

    attribute_map = {
        'id': 'id',
        'business_object_definition_subject_matter_expert_key': 'businessObjectDefinitionSubjectMatterExpertKey'
    }

    def __init__(self, id=None, business_object_definition_subject_matter_expert_key=None):  # noqa: E501
        """BusinessObjectDefinitionSubjectMatterExpert - a model defined in OpenAPI"""  # noqa: E501

        self._id = None
        self._business_object_definition_subject_matter_expert_key = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.business_object_definition_subject_matter_expert_key = business_object_definition_subject_matter_expert_key

    @property
    def id(self):
        """Gets the id of this BusinessObjectDefinitionSubjectMatterExpert.  # noqa: E501

        The internal Id that uniquely references a Business Object Definition Subject Matter Expert  # noqa: E501

        :return: The id of this BusinessObjectDefinitionSubjectMatterExpert.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this BusinessObjectDefinitionSubjectMatterExpert.

        The internal Id that uniquely references a Business Object Definition Subject Matter Expert  # noqa: E501

        :param id: The id of this BusinessObjectDefinitionSubjectMatterExpert.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def business_object_definition_subject_matter_expert_key(self):
        """Gets the business_object_definition_subject_matter_expert_key of this BusinessObjectDefinitionSubjectMatterExpert.  # noqa: E501


        :return: The business_object_definition_subject_matter_expert_key of this BusinessObjectDefinitionSubjectMatterExpert.  # noqa: E501
        :rtype: BusinessObjectDefinitionSubjectMatterExpertKey
        """
        return self._business_object_definition_subject_matter_expert_key

    @business_object_definition_subject_matter_expert_key.setter
    def business_object_definition_subject_matter_expert_key(self, business_object_definition_subject_matter_expert_key):
        """Sets the business_object_definition_subject_matter_expert_key of this BusinessObjectDefinitionSubjectMatterExpert.


        :param business_object_definition_subject_matter_expert_key: The business_object_definition_subject_matter_expert_key of this BusinessObjectDefinitionSubjectMatterExpert.  # noqa: E501
        :type: BusinessObjectDefinitionSubjectMatterExpertKey
        """
        if business_object_definition_subject_matter_expert_key is None:
            raise ValueError("Invalid value for `business_object_definition_subject_matter_expert_key`, must not be `None`")  # noqa: E501

        self._business_object_definition_subject_matter_expert_key = business_object_definition_subject_matter_expert_key

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BusinessObjectDefinitionSubjectMatterExpert):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
