# coding: utf-8

"""
    herd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.178.0-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class DataProviderKeys(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'data_provider_keys': 'list[DataProviderKey]'
    }

    attribute_map = {
        'data_provider_keys': 'dataProviderKeys'
    }

    def __init__(self, data_provider_keys=None):  # noqa: E501
        """DataProviderKeys - a model defined in OpenAPI"""  # noqa: E501

        self._data_provider_keys = None
        self.discriminator = None

        if data_provider_keys is not None:
            self.data_provider_keys = data_provider_keys

    @property
    def data_provider_keys(self):
        """Gets the data_provider_keys of this DataProviderKeys.  # noqa: E501


        :return: The data_provider_keys of this DataProviderKeys.  # noqa: E501
        :rtype: list[DataProviderKey]
        """
        return self._data_provider_keys

    @data_provider_keys.setter
    def data_provider_keys(self, data_provider_keys):
        """Sets the data_provider_keys of this DataProviderKeys.


        :param data_provider_keys: The data_provider_keys of this DataProviderKeys.  # noqa: E501
        :type: list[DataProviderKey]
        """

        self._data_provider_keys = data_provider_keys

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DataProviderKeys):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
