# coding: utf-8

"""
    herd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.178.0-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class EmrClusterInstanceFleetStatus(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'state': 'str',
        'state_change_reason': 'EmrClusterInstanceFleetStateChangeReason',
        'timeline': 'EmrClusterInstanceFleetTimeline'
    }

    attribute_map = {
        'state': 'state',
        'state_change_reason': 'stateChangeReason',
        'timeline': 'timeline'
    }

    def __init__(self, state=None, state_change_reason=None, timeline=None):  # noqa: E501
        """EmrClusterInstanceFleetStatus - a model defined in OpenAPI"""  # noqa: E501

        self._state = None
        self._state_change_reason = None
        self._timeline = None
        self.discriminator = None

        if state is not None:
            self.state = state
        if state_change_reason is not None:
            self.state_change_reason = state_change_reason
        if timeline is not None:
            self.timeline = timeline

    @property
    def state(self):
        """Gets the state of this EmrClusterInstanceFleetStatus.  # noqa: E501

        A code representing the instance fleet status                  # noqa: E501

        :return: The state of this EmrClusterInstanceFleetStatus.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this EmrClusterInstanceFleetStatus.

        A code representing the instance fleet status                  # noqa: E501

        :param state: The state of this EmrClusterInstanceFleetStatus.  # noqa: E501
        :type: str
        """

        self._state = state

    @property
    def state_change_reason(self):
        """Gets the state_change_reason of this EmrClusterInstanceFleetStatus.  # noqa: E501


        :return: The state_change_reason of this EmrClusterInstanceFleetStatus.  # noqa: E501
        :rtype: EmrClusterInstanceFleetStateChangeReason
        """
        return self._state_change_reason

    @state_change_reason.setter
    def state_change_reason(self, state_change_reason):
        """Sets the state_change_reason of this EmrClusterInstanceFleetStatus.


        :param state_change_reason: The state_change_reason of this EmrClusterInstanceFleetStatus.  # noqa: E501
        :type: EmrClusterInstanceFleetStateChangeReason
        """

        self._state_change_reason = state_change_reason

    @property
    def timeline(self):
        """Gets the timeline of this EmrClusterInstanceFleetStatus.  # noqa: E501


        :return: The timeline of this EmrClusterInstanceFleetStatus.  # noqa: E501
        :rtype: EmrClusterInstanceFleetTimeline
        """
        return self._timeline

    @timeline.setter
    def timeline(self, timeline):
        """Sets the timeline of this EmrClusterInstanceFleetStatus.


        :param timeline: The timeline of this EmrClusterInstanceFleetStatus.  # noqa: E501
        :type: EmrClusterInstanceFleetTimeline
        """

        self._timeline = timeline

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EmrClusterInstanceFleetStatus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
