# coding: utf-8

"""
    herd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.178.0-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class FileTypeKey(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'file_type_code': 'str'
    }

    attribute_map = {
        'file_type_code': 'fileTypeCode'
    }

    def __init__(self, file_type_code=None):  # noqa: E501
        """FileTypeKey - a model defined in OpenAPI"""  # noqa: E501

        self._file_type_code = None
        self.discriminator = None

        self.file_type_code = file_type_code

    @property
    def file_type_code(self):
        """Gets the file_type_code of this FileTypeKey.  # noqa: E501

        The File Type code  # noqa: E501

        :return: The file_type_code of this FileTypeKey.  # noqa: E501
        :rtype: str
        """
        return self._file_type_code

    @file_type_code.setter
    def file_type_code(self, file_type_code):
        """Sets the file_type_code of this FileTypeKey.

        The File Type code  # noqa: E501

        :param file_type_code: The file_type_code of this FileTypeKey.  # noqa: E501
        :type: str
        """
        if file_type_code is None:
            raise ValueError("Invalid value for `file_type_code`, must not be `None`")  # noqa: E501

        self._file_type_code = file_type_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FileTypeKey):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
