# coding: utf-8

"""
    herd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.178.0-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class JobDefinitionKeys(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'job_definition_keys': 'list[JobDefinitionKey]'
    }

    attribute_map = {
        'job_definition_keys': 'jobDefinitionKeys'
    }

    def __init__(self, job_definition_keys=None):  # noqa: E501
        """JobDefinitionKeys - a model defined in OpenAPI"""  # noqa: E501

        self._job_definition_keys = None
        self.discriminator = None

        if job_definition_keys is not None:
            self.job_definition_keys = job_definition_keys

    @property
    def job_definition_keys(self):
        """Gets the job_definition_keys of this JobDefinitionKeys.  # noqa: E501


        :return: The job_definition_keys of this JobDefinitionKeys.  # noqa: E501
        :rtype: list[JobDefinitionKey]
        """
        return self._job_definition_keys

    @job_definition_keys.setter
    def job_definition_keys(self, job_definition_keys):
        """Sets the job_definition_keys of this JobDefinitionKeys.


        :param job_definition_keys: The job_definition_keys of this JobDefinitionKeys.  # noqa: E501
        :type: list[JobDefinitionKey]
        """

        self._job_definition_keys = job_definition_keys

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JobDefinitionKeys):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
