# coding: utf-8

"""
    herd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.178.0-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class NamespaceSearchFilter(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'namespace_search_keys': 'list[NamespaceSearchKey]'
    }

    attribute_map = {
        'namespace_search_keys': 'namespaceSearchKeys'
    }

    def __init__(self, namespace_search_keys=None):  # noqa: E501
        """NamespaceSearchFilter - a model defined in OpenAPI"""  # noqa: E501

        self._namespace_search_keys = None
        self.discriminator = None

        if namespace_search_keys is not None:
            self.namespace_search_keys = namespace_search_keys

    @property
    def namespace_search_keys(self):
        """Gets the namespace_search_keys of this NamespaceSearchFilter.  # noqa: E501

        A wrapper for a list of namespace search keys. Only a single search key supported  # noqa: E501

        :return: The namespace_search_keys of this NamespaceSearchFilter.  # noqa: E501
        :rtype: list[NamespaceSearchKey]
        """
        return self._namespace_search_keys

    @namespace_search_keys.setter
    def namespace_search_keys(self, namespace_search_keys):
        """Sets the namespace_search_keys of this NamespaceSearchFilter.

        A wrapper for a list of namespace search keys. Only a single search key supported  # noqa: E501

        :param namespace_search_keys: The namespace_search_keys of this NamespaceSearchFilter.  # noqa: E501
        :type: list[NamespaceSearchKey]
        """

        self._namespace_search_keys = namespace_search_keys

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NamespaceSearchFilter):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
