# coding: utf-8

"""
    herd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.178.0-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class NamespaceIamRoleAuthorizationUpdateRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'iam_role_description': 'str'
    }

    attribute_map = {
        'iam_role_description': 'iamRoleDescription'
    }

    def __init__(self, iam_role_description=None):  # noqa: E501
        """NamespaceIamRoleAuthorizationUpdateRequest - a model defined in OpenAPI"""  # noqa: E501

        self._iam_role_description = None
        self.discriminator = None

        if iam_role_description is not None:
            self.iam_role_description = iam_role_description

    @property
    def iam_role_description(self):
        """Gets the iam_role_description of this NamespaceIamRoleAuthorizationUpdateRequest.  # noqa: E501

        A description of the IAM role  # noqa: E501

        :return: The iam_role_description of this NamespaceIamRoleAuthorizationUpdateRequest.  # noqa: E501
        :rtype: str
        """
        return self._iam_role_description

    @iam_role_description.setter
    def iam_role_description(self, iam_role_description):
        """Sets the iam_role_description of this NamespaceIamRoleAuthorizationUpdateRequest.

        A description of the IAM role  # noqa: E501

        :param iam_role_description: The iam_role_description of this NamespaceIamRoleAuthorizationUpdateRequest.  # noqa: E501
        :type: str
        """

        self._iam_role_description = iam_role_description

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NamespaceIamRoleAuthorizationUpdateRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
