# coding: utf-8

"""
    herd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.178.0-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class SecurityRoleFunction(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'security_role_function_key': 'SecurityRoleFunctionKey'
    }

    attribute_map = {
        'id': 'id',
        'security_role_function_key': 'securityRoleFunctionKey'
    }

    def __init__(self, id=None, security_role_function_key=None):  # noqa: E501
        """SecurityRoleFunction - a model defined in OpenAPI"""  # noqa: E501

        self._id = None
        self._security_role_function_key = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.security_role_function_key = security_role_function_key

    @property
    def id(self):
        """Gets the id of this SecurityRoleFunction.  # noqa: E501

        The internal Id that uniquely references a security role to function mapping  # noqa: E501

        :return: The id of this SecurityRoleFunction.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SecurityRoleFunction.

        The internal Id that uniquely references a security role to function mapping  # noqa: E501

        :param id: The id of this SecurityRoleFunction.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def security_role_function_key(self):
        """Gets the security_role_function_key of this SecurityRoleFunction.  # noqa: E501


        :return: The security_role_function_key of this SecurityRoleFunction.  # noqa: E501
        :rtype: SecurityRoleFunctionKey
        """
        return self._security_role_function_key

    @security_role_function_key.setter
    def security_role_function_key(self, security_role_function_key):
        """Sets the security_role_function_key of this SecurityRoleFunction.


        :param security_role_function_key: The security_role_function_key of this SecurityRoleFunction.  # noqa: E501
        :type: SecurityRoleFunctionKey
        """
        if security_role_function_key is None:
            raise ValueError("Invalid value for `security_role_function_key`, must not be `None`")  # noqa: E501

        self._security_role_function_key = security_role_function_key

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SecurityRoleFunction):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
