# coding: utf-8

"""
    herd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.178.0-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class StoragePolicyKey(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'namespace': 'str',
        'storage_policy_name': 'str'
    }

    attribute_map = {
        'namespace': 'namespace',
        'storage_policy_name': 'storagePolicyName'
    }

    def __init__(self, namespace=None, storage_policy_name=None):  # noqa: E501
        """StoragePolicyKey - a model defined in OpenAPI"""  # noqa: E501

        self._namespace = None
        self._storage_policy_name = None
        self.discriminator = None

        self.namespace = namespace
        self.storage_policy_name = storage_policy_name

    @property
    def namespace(self):
        """Gets the namespace of this StoragePolicyKey.  # noqa: E501

        The namespace of the storage policy  # noqa: E501

        :return: The namespace of this StoragePolicyKey.  # noqa: E501
        :rtype: str
        """
        return self._namespace

    @namespace.setter
    def namespace(self, namespace):
        """Sets the namespace of this StoragePolicyKey.

        The namespace of the storage policy  # noqa: E501

        :param namespace: The namespace of this StoragePolicyKey.  # noqa: E501
        :type: str
        """
        if namespace is None:
            raise ValueError("Invalid value for `namespace`, must not be `None`")  # noqa: E501

        self._namespace = namespace

    @property
    def storage_policy_name(self):
        """Gets the storage_policy_name of this StoragePolicyKey.  # noqa: E501

        The name of the storage policy  # noqa: E501

        :return: The storage_policy_name of this StoragePolicyKey.  # noqa: E501
        :rtype: str
        """
        return self._storage_policy_name

    @storage_policy_name.setter
    def storage_policy_name(self, storage_policy_name):
        """Sets the storage_policy_name of this StoragePolicyKey.

        The name of the storage policy  # noqa: E501

        :param storage_policy_name: The storage_policy_name of this StoragePolicyKey.  # noqa: E501
        :type: str
        """
        if storage_policy_name is None:
            raise ValueError("Invalid value for `storage_policy_name`, must not be `None`")  # noqa: E501

        self._storage_policy_name = storage_policy_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StoragePolicyKey):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
