#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# AUTO-GENERATED CONTENT
d_stem_vt = {'vta': {'vtas': []},
 'vtabl': {'vtable': ['vtables']},
 'vtable': ['vtables'],
 'vtam': {'vtams': []},
 'vtar': {'vtars': []},
 'vtbl': {'vtbls': []},
 'vtc': {'vtcs': []},
 'vtcker': {'vtckers': []},
 'vtcmo': {'vtcmos': []},
 'vtcomt': {'vtcomte': []},
 'vtconomi': {'vtconomie': []},
 'vtctori': {'vtctory': []},
 'vtcunqu': {'vtcunque': []},
 'vtd': {'vtds': []},
 'vtda': {'vtdas': []},
 'vtdgari': {'vtdgaris': []},
 'vtducat': {'vtducation': []},
 'vte': {'vtes': []},
 'vtenn': {'vtenne': []},
 'vterg': {'vterge': []},
 'vteri': {'vtery': []},
 'vterli': {'vterly': []},
 'vterqu': {'vterque': []},
 'vteru': {'vterus': []},
 'vtew': {'vtewed': [], 'vtews': []},
 'vtf': {'vtfs': []},
 'vtfa': {'vtfas': []},
 'vtg': {'vtgs': []},
 'vtgilia': {'vtgiliae': []},
 'vtgypt': {'vtgypte': []},
 'vth': {'vths': []},
 'vthen': {'vthens': []},
 'vther': {'vthers': []},
 'vtheri': {'vtheris': []},
 'vtherway': {'vtherwayes': []},
 'vtherwayi': {'vtherwayis': []},
 'vtherwys': {'vtherwyse': []},
 'vthi': {'vthis': [], 'vthy': []},
 'vthiri': {'vthiris': []},
 'vthoma': {'vthomas': []},
 'vthu': {'vthus': []},
 'vti': {'vties': [], 'vtis': [], 'vty': ['vtys']},
 'vtile': {'vtiles': []},
 'vtili': {'vtilis': []},
 'vtilit': {'vtilitate': [], 'vtilite': ['vtiliter']},
 'vtilita': {'vtilitas': []},
 'vtilitati': {'vtilitatis': []},
 'vtilite': ['vtiliter'],
 'vtiliti': {'vtilitie': [], 'vtility': []},
 'vtiliu': {'vtilius': []},
 'vtilu': {'vtilue': []},
 'vtime': {'vtimes': []},
 'vtin': {'vtins': []},
 'vtion': {'vtions': []},
 'vtiqu': {'vtique': []},
 'vtka': {'vtkas': []},
 'vtl': {'vtls': []},
 'vtli': {'vtly': []},
 'vtllar': {'vtllars': []},
 'vtlle': {'vtlles': []},
 'vtllega': {'vtllegas': []},
 'vtllett': {'vtllette': []},
 'vtllier': {'vtlliers': []},
 'vtlociti': {'vtlocity': []},
 'vtloo': {'vtloos': []},
 'vtm': {'vtms': []},
 'vtmi': {'vtmis': []},
 'vtn': {'vtns': []},
 'vtncenn': {'vtncennes': []},
 'vtnu': {'vtnus': []},
 'vto': {'vtos': []},
 'vtoc': {'vtocs': []},
 'vtol': {'vtols': []},
 'vtolenc': {'vtolence': []},
 'vtopi': {'vtopie': []},
 'vtord': {'vtords': []},
 'vtorichny': {'vtorichnye': []},
 'vtork': {'vtorks': []},
 'vtoro': {'vtoroe': []},
 'vtoroy': {'vtoroye': []},
 'vtorzheni': {'vtorzhenie': []},
 'vtoth': {'vtothing': []},
 'vtp': {'vtps': []},
 'vtpoqu': {'vtpoque': []},
 'vtr': {'vtrs': []},
 'vtramqu': {'vtramque': []},
 'vtran': {'vtrans': []},
 'vtraqu': {'vtraque': []},
 'vtrasaiv': {'vtrasaivism': []},
 'vtrasaiva': {'vtrasaivas': []},
 'vtrchow': {'vtrchows': []},
 'vtre': {'vtres': []},
 'vtren': {'vtrens': []},
 'vtrgini': {'vtrginie': [], 'vtrginis': []},
 'vtrginiu': {'vtrginius': []},
 'vtri': {'vtry': []},
 'vtridi': {'vtridis': []},
 'vtrinqu': {'vtrinque': []},
 'vtriou': {'vtrious': []},
 'vtriqu': {'vtrique': []},
 'vtrisqu': {'vtrisque': []},
 'vtrita': {'vtritas': []},
 'vtriusqu': {'vtriusque': []},
 'vtrivsqv': {'vtrivsqve': []},
 'vtrobiqu': {'vtrobique': []},
 'vtroqu': {'vtroque': []},
 'vtrse': {'vtrses': []},
 'vtrsu': {'vtrsus': []},
 'vtrtualli': {'vtrtually': []},
 'vtrtue': {'vtrtues': []},
 'vtru': {'vtrus': []},
 'vtrumqu': {'vtrumque': []},
 'vtsite': {'vtsited': []},
 'vtssel': {'vtssels': []},
 'vtssp': {'vtssps': []},
 'vtston': {'vtstons': []},
 'vtt': {'vtts': []},
 'vttali': {'vttalis': []},
 'vtter': {'vtters': []},
 'vtteranc': {'vtterance': []},
 'vtteraunc': {'vtteraunce': []},
 'vttere': {'vttered': [], 'vttering': []},
 'vtterli': {'vtterlie': [], 'vtterly': []},
 'vtterly': {'vtterlye': []},
 'vttermost': {'vttermoste': []},
 'vtti': {'vttis': [], 'vtty': []},
 'vttri': {'vttry': []},
 'vttruviu': {'vttruvius': []},
 'vttu': {'vttus': []},
 'vtu': {'vtus': []},
 'vtuzi': {'vtuzy': []},
 'vtve': {'vtves': []},
 'vtvm': {'vtvms': []},
 'vtwin': {'vtwins': []},
 'vty': ['vtys']}
