
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_dd = {'_': ['dd51_diesel_locomotive',
       'dd_himachal_pradesh',
       'dd_madhya_pradesh',
       'dd_uttar_pradesh',
       'dd_social_league',
       'dd_postcode_area',
       'dd_port_station',
       'dd_lok_sabha',
       'dd_free_dish',
       'dd_form_214'],
 'a': ['dda_classic_airlines'],
 'c': ['ddc_and_loc'],
 'f': ['ddf_productions_ltd.'],
 'o': ['ddor_novi_sad'],
 'p': ['ddp_4_life'],
 'r': ['ddr:_hottest_party',
       'ddr_border_system',
       'ddr_hottest_party',
       'ddr_solo_series',
       'ddr_supernova_2',
       'ddr_disney_mix',
       'ddr:_mario_mix',
       'ddr_ultramix_2',
       'ddr_universe_3',
       'ddr_with_mario',
       'ddr_mario_mix',
       'ddr_extreme_2',
       'ddr_solo_2000',
       'ddr_extra_mix',
       'ddr_ii_sdram',
       'ddr_5th_mix',
       'ddr_2_sdram',
       'ddr_3rd_mix',
       'ddr_2nd_mix',
       'ddr_7th_mix',
       'ddr_6th_mix',
       'ddr_max_2'],
 't': ['ddt_universal_championship',
       'ddt_extreme_championship',
       'ddt_ultimate_party',
       'ddt_and_malaria',
       'ddt_peter_pan',
       'ddt_sky_tower'],
 'u': ['dduallt_railway_station', 'dduallt_fr_station']}
