
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_dc = {'_': ['dc-community_access_network',
       'dc_kizhakemuri_foundation',
       'dc_republican_committee',
       'dc_rivals_hypercoaster',
       'dc_universe:_legacies',
       'dc_showcase:_catwoman',
       'dc_entertainment_inc.',
       'dc_universe_all-stars',
       'dc_statehood_movement',
       'dc_universe_infinite',
       'dc_injection_braking',
       'dc_showcase_presents',
       'dc_comics_bombshells',
       'dc_animated_universe',
       'dc101_chili_cook-off',
       'dc_universe_classics',
       'dc_extended_universe',
       'dc_comics_characters',
       'dc_olympic_committee',
       'dc_universe_presents',
       'dc_archive_editions',
       'dc_superheroes_cafe',
       'dc101_chili_cookoff',
       'dc_sniper_shootings',
       'dc_talk_discography',
       'dc_democratic_party',
       'dc_anti-war_network',
       'dc_republican_party',
       'dc_brushless_motor',
       'dc_united_holdings',
       'dc_comics_presents',
       'dc_antiwar_network',
       'dc_universe_online',
       'dc_comics_universe',
       'dc_central_kitchen',
       'dc_universe_movies',
       'dc_cosmic_entities',
       'dc_statehood_party',
       'dc_showcase:_death',
       'dc_public_schools',
       "dc's_young_animal",
       'dc_public_library',
       'dc_superior_court',
       'dc_special_series',
       'dc_touchdown_club',
       'dc_graphic_novels',
       'dc_voting_rights',
       'dc_chris_skelton',
       'dc_jazz_festival',
       'dc_versus_marvel',
       'dc_nation_shorts',
       'dc_graphic_novel',
       'dc_comics_titles',
       'dc_motemba_pembe',
       'dc_debate_league',
       'dc_comics_mmorpg',
       'dc-10_air_tanker',
       'dc_circuit_court',
       'dc_olympic_team',
       'dc_fashion_week',
       'dc_shoe_company',
       'dc_urban_debate',
       'dc_mountain_lab',
       'dc_hand_dancing',
       'dc_city_council',
       'dc3_music_group',
       'dc_new_frontier',
       'dc_cosmic_cards',
       'dc_brau_brewing',
       'dc_motema_pembe',
       'dc_mckay_stakes',
       'dc_metro_police',
       'dc_health_link',
       'dc_black_label',
       'dc_green_party',
       'dc_super_stars',
       'dc_one_million',
       'dc_vs._marvel',
       'dc_vs._heller',
       'dc_and_family',
       'dc_jo_masters',
       'dc_state_fair',
       'dc_games_2007',
       'dc_metro_area',
       'dc_hand_dance',
       'dc_web_women',
       'dc_v._heller',
       'dc_vs_marvel',
       'dc_city_hall',
       'dc_tea_party',
       'dc_home_rule',
       'dc_v_heller',
       'dc_to_light',
       'dc_fair_act',
       'dc_al_coda',
       'dc_al_fine',
       'dc_go_go',
       'dc_vs_mk'],
 'f': ['dcf_interframe_space'],
 'g': ['dcg_radio-tv_network'],
 'h': ['dcheira_el_jihadia'],
 'i': ['dci_global_partnerships',
       'dci_world_championships',
       'dci_grace_barraclough',
       'dci_cheese_company',
       'dci_roy_slater',
       'dci_matt_burke',
       'dci_gene_hunt'],
 'l': ['dcl_command_language'],
 'p': ['dcp_midstream_partners'],
 'r': ['dcrrc_track_championships'],
 's': ['dcsmat_business_school',
       'dcs_copy_protection',
       'dcs:_black_shark',
       'dcs_pro_14nx'],
 'u': ["dcu_students'_union", 'dcu_ryan_academy']}
