
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rt = {'_': ['rt-2utth_topol-m',
       'rt-2pm2_topol-m',
       'rt-23_molodets',
       'rt_documentary',
       'rt-21m_pioneer',
       'rt-21m_pioner',
       'rt_andromedae',
       'rt_middleware',
       'rt-2pm_topol',
       'rt_williams',
       'rt_crowley',
       'rt_carinae',
       'rt_ponting',
       'rt_kendall',
       'rt_america',
       'rt_aurigae',
       'rt_france',
       'rt_arabic',
       'rt_gerard',
       'rt_movies',
       'rt_normae',
       'rt_number',
       'rt_smith',
       'rt._rev.',
       'rt_nagar',
       'rt_bozak',
       'rt_rybak',
       'rt._hon.',
       'rt_rail',
       'rt_hon.',
       'rt._hon',
       'rt_revd',
       'rt_and',
       'rt_125',
       'rt_hon',
       'rt_rev',
       'rt_pcr',
       'rt_128',
       'rt_pc',
       'rt_cg',
       'rt_uk',
       'rt_27',
       'rt_de',
       'rt_66'],
 'a': ['rta_furniture', 'rta_insurer', 'rta_clade'],
 'b': ['rtbf_international',
       'rtb_international',
       'rtb_sukmaindera',
       'rtb_perdana',
       'rtb_aneka',
       'rtbf_sat'],
 'c': ['rtcm_sc-104', 'rtc_transit', 'rtc_alarm', 'rtcg_1', 'rtcg_3', 'rtcg_2'],
 'd': ['rtdna_canada', 'rtd_denver', 'rtd_info'],
 'e': ['rte_television',
       'rtecs_number',
       'rte_ireland',
       'rte_choice',
       'rte_player',
       'rte_aertel',
       'rte_radio',
       'rte_board',
       'rte_chill',
       'rte_three',
       'rte_pulse',
       'rte_sport',
       'rte_guide',
       'rte_gold',
       'rte_2fm',
       'rte_one',
       'rte_2xm'],
 'f': ['rtf_format', 'rtf_files'],
 'h': ['rthk_putonghua'],
 'i': ['rtishchevsky_district',
       'rti_international',
       'rti_producciones',
       'rti_colombia',
       'rti_surgical',
       'rti_systems',
       'rti_india',
       'rti_act'],
 'k': ['rtkl_associates', 'rtk_4', 'rtk_3', 'rtk_2', 'rtk_1'],
 'l': ['rtl_international',
       'rtl_description',
       'rtl_deutschland',
       'rtl_television',
       'rtl_televizija',
       'rtl_boulevard',
       'rtl_veronique',
       'rtl_orchestra',
       'rtl_nederland',
       'rtlinux_free',
       'rtl7_masters',
       'rtl_telekids',
       'rtl_aktuell',
       'rtl_passion',
       'rtl_kockica',
       'rtl_design',
       'rtl_lounge',
       'rtl_living',
       'rtl_nieuws',
       'rtl_travel',
       'rtl_games',
       'rtl_group',
       'rtl_radio',
       'rtl_matin',
       'rtl_102.5',
       'rtl_crime',
       'rtl_text',
       'rtl_zwei',
       'rtl_klub',
       'rtl_zwee',
       'rtl_plus',
       'rtl_ii',
       'rtl_24',
       'rtl_8',
       'rtl_2',
       'rtl_5',
       'rtl_z',
       'rtl_7',
       'rtl_4'],
 'm': ['rtm_mostar', 'rtm_worm'],
 'n': ['rtn_seals'],
 'p': ['rtp_internacional',
       'rtp_informacao',
       'rtp_desporto',
       'rtp_memoria',
       'rtp_madeira',
       'rtp_acores',
       'rtp_awards',
       'rtp_africa',
       'rtp1_hd',
       'rtp_tv',
       'rtp_n',
       'rtp_1',
       'rtp_2'],
 'r': ['rtr_moldova', 'rtr_sports', 'rtrs_plus', 'rtr_sport', 'rtr_tv'],
 's': ['rtse_thang',
       'rts_index',
       'rts_games',
       'rts_game',
       'rts_svet',
       'rts_info',
       'rts_bus',
       'rts_1',
       'rts_2',
       'rts_3'],
 't': ['rtt_news', 'rtt_rna'],
 'u': ['rtu_rauma', 'rtu_fc'],
 'v': ['rtv_kragujevac',
       'rtv-g-4_bumper',
       'rtv-a-3_nativ',
       'rtv_ljubljana',
       'rtv_slovenija',
       'rtv-a-2_hiroc',
       'rtv_jablanica',
       'rtv_rijnmond',
       'rtv_zivinice',
       'rtv_politika',
       'rtv_slovenia',
       'rtv_panorama',
       'rtv_slobomir',
       'rtv_silicone',
       'rtv_gorazde',
       'rtv_utrecht',
       'rtv_vogosca',
       'rtv_bugojno',
       'rtv_visoko',
       'rtv_maglaj',
       'rtv_niksic',
       'rtv_bostel',
       'rtv_center',
       'rtv_zenica',
       'rtv_selant',
       'rtv_cazin',
       'rtve_play',
       'rtv_vikom',
       'rtv_palma',
       'rtv_noord',
       'rtv_atlas',
       'rtv_doboj',
       'rtv_sabac',
       'rtv_pink',
       'rtv_sana',
       'rtv_luna',
       'rtv_apr',
       'rtv_six',
       'rtv_usk',
       'rtv_is',
       'rtv_tk',
       'rtv_bk',
       'rtv_bn',
       'rtv_cg',
       'rtv_6'],
 'w': ['rtwbm_episodes', 'rtw_alex'],
 'x': ['rtxc_quadros', 'rtx_toxin']}
