
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rd = {'_': ['rd_coordinates',
       'rd_fitzgerald',
       'rd_blumenfeld',
       'rd_mcnaughton',
       'rd_wingfield',
       'rd_blackmore',
       'rd_oriamendi',
       'rd_tichborne',
       'rd_reynolds',
       'rd_ariffien',
       'rd_pradhan',
       'rd_mochtar',
       'rd_dolphin',
       'rd_ribnica',
       'rd_slovan',
       'rd_burman',
       'rd_amross',
       'rd_oliver',
       'rd_congo',
       'rd_patel',
       'rd_laing',
       'rd_raval',
       'rd_loka',
       'rd_call',
       'rd_s.a.',
       'rd_reid',
       'rd_128',
       'rd:_g',
       'rd_66'],
 'e': ['rdeci_kamen'],
 'f': ['rdf_television',
       'rdf_datastore',
       'rdf_database',
       'rdfz_united',
       'rdf_schema',
       'rdf_media',
       'rdf_1985',
       'rdf_feed'],
 'g': ['rdg-33_grenade'],
 'h': ['rdh_architects'],
 'i': ['rdi_powerlite', 'rdi_reit'],
 'j': ['rdj_album'],
 'm': ['rdm_server'],
 'o': ['rdo-rje_shugs-ldan', 'rdo_building'],
 'p': ['rdp_internacional',
       'rdp_algorithm',
       'rdp_technique',
       'rdp_africa',
       'rdp_shop'],
 'r': ['rdr_philippines', 'rdrive_image'],
 's': ['rds_simmonscourt',
       'rds-2_linage',
       'rds-jvc_cup',
       'rds_encoder',
       'rds_stadium',
       'rds_arena',
       'rds_info',
       'rds_cup',
       'rds_tmc'],
 'u': ['rdu_airport'],
 'v': ['rdv_sportsplex'],
 'w': ['rdw_group'],
 'x': ['rdx_technology']}
