
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_bc = {'_': ['bc-li-0186',
       'bc-1000',
       'bc-611',
       'bc-stv',
       'bc-654',
       'bc-779',
       'bc-342',
       'bc-610',
       'bc-348',
       'bc548',
       'bc-41',
       'bc-1a',
       'bc/ad',
       'bc-14',
       'bc150',
       'bc/bs',
       'bc-99',
       'bc-1',
       'bc-3',
       'bc4',
       'bc3',
       'bc2',
       'bc1'],
 'a': ['bcachefs',
       'bcap31',
       'bcap29',
       'bcache',
       'bcar1',
       'bcas3',
       'bcafc',
       'bcas1',
       'bcar3',
       'bcatp',
       'bcafl',
       'bcas2',
       'bcaha',
       'bcal',
       'bcas',
       'bcam',
       'bcaa',
       'bcan',
       'bcat',
       'bcap',
       'bca'],
 'b': ['bcbgmaxazria',
       'bcbusiness',
       'bcbst',
       'bcbsu',
       'bcbg',
       'bcbs',
       'bcbp',
       'bcbc',
       'bcb'],
 'c': ['bccresearch.com',
       'bccdaily.org',
       'bccresearch',
       'bcc-rapid',
       'bcc-bliss',
       'bccat',
       'bcciv',
       'bccla',
       'bccip',
       'bcchs',
       'bccsl',
       'bcc:',
       'bccl',
       'bcch',
       'bcci',
       'bcca',
       'bccc',
       'bcc6',
       'bccm',
       'bcc'],
 'd': ['bcdmos', 'bcd541', 'bcdmh', 'bcdsp', 'bcds', 'bcdb', 'bcd'],
 'e': ['bcepmuvirus',
       'bcesis',
       'bce/ce',
       'bceao',
       'bces',
       'bcec',
       'bcer',
       'bcel',
       'bcet',
       'bce'],
 'f': ['bcferries', 'bcfg2', 'bcfed', 'bcfx', 'bcfm', 'bcfc', 'bcfp', 'bcf'],
 'g': ['bcgnis', 'bcgf1', 'bcg'],
 'h': ['bchennine',
       'bchernata',
       'bcharre',
       'bcheale',
       'bchydro',
       'bcheck',
       'bchrt',
       'bchb',
       'bchs',
       'bche',
       'bchd',
       'bchl',
       'bch'],
 'i': ['bci2000',
       'bcihl',
       'bcisd',
       'bciii',
       'bcing',
       'bcia',
       'bcic',
       'bcie',
       'bcis',
       'bci'],
 'j': ['bcjournal', 'bcjhl', 'bcjhs', 'bcjr', 'bcj'],
 'k': ['bckdhb', 'bckdha', 'bckdk', 'bckdh', 'bck2', 'bckv', 'bcks', 'bck'],
 'l': ['bclambgnk',
       'bcl-abr',
       'bcl2l12',
       'bcl2l13',
       'bcl2l10',
       'bcl2l11',
       'bcl2l14',
       'bcl-xl',
       'bcl2a1',
       'bcl2l2',
       'bclaf1',
       'bcl11b',
       'bcl2l8',
       'bcl11a',
       'bcl6b',
       'bcl-w',
       'bcldb',
       'bcl9l',
       'bcl7a',
       'bcl-2',
       'bcl10',
       'bcla',
       'bcl9',
       'bclc',
       'bcl3',
       'bcl6',
       'bclr',
       'bcls',
       'bclp',
       'bcl2',
       'bcl'],
 'm': ['bcmess',
       'bcmhs',
       'bcmsn',
       'bcmc',
       'bcmb',
       'bcms',
       'bcma',
       'bcmg',
       'bcmp',
       'bcm'],
 'n': ['bcn/osasco', 'bcnpmr', 'bcndp', 'bcnha', 'bcnu', 'bcnz', 'bcnf', 'bcn'],
 'o': ['bcommerce',
       'bcompsc',
       'bcomm',
       'bcode',
       'bcov',
       'bcoq',
       'bcot',
       'bcof',
       'bcol',
       'bcor',
       'bcom',
       'bco'],
 'p': ['bcpnn',
       'bcpss',
       'bcpbl',
       'bcps',
       'bcpp',
       'bcpc',
       'bcpb',
       'bcpl',
       'bcpa',
       'bcp'],
 'q': ['bcq'],
 'r': ['bcr:abl',
       'bcr/abl',
       'bcr-abl',
       'bcrypt',
       'bcrabl',
       'bcrail',
       'bcrfm',
       'bcric',
       'bcrfc',
       'bcrpm',
       'bcrp1',
       'bcrr',
       'bcru',
       'bcrp',
       'bcra',
       'bcrs',
       'bcr1',
       'bcry',
       'bcrg',
       'bcr'],
 's': ['bcs-theory',
       'bcswomen',
       'bcs-facs',
       'bcs1l',
       'bcssa',
       'bcsc',
       'bcss',
       'bcsn',
       'bcsr',
       'bcsa',
       'bcsl',
       'bcsm',
       'bcso',
       'bcs'],
 't': ['bctel', 'bctia', 'bctcs', 'bctv', 'bctc', 'bct'],
 'u': ['bcube', 'bcuc', 'bcu'],
 'v': ['bcvsmgcd', 'bcv-8', 'bcvx', 'bcv8', 'bcvo', 'bcv'],
 'w': ['bcworld', 'bcwnc', 'bcwp', 'bcw'],
 'x': ['bcx'],
 'y': ['bcycle', 'bcyp', 'bcy'],
 'z': ['bcz']}
