
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_wt = {'_': ['wt_pfefferle',
       'wt_purkiser',
       'wt_cosgrave',
       'wt_preston',
       'wt_marriot',
       'wt_astbury',
       'wt_attrill',
       'wt_woodson',
       'wt_social',
       'wt_martin',
       'wt_stead',
       'wt_tutte',
       'wt_grant',
       'wt_asia',
       'wt_kerr',
       'wt_visa',
       'wt_dunn'],
 'a': ['wta_championships',
       'wta_christchurch',
       'wta_knokke-heist',
       'wta_wellington',
       'wta_bratislava',
       'wta_montreal',
       'wta_rankings',
       'wta_auckland',
       'wta_estoril',
       'wta_memphis',
       'wta_kolkata',
       'wta_hasselt',
       'wta_austria',
       'wta_hamburg',
       'wta_atlanta',
       'wta_antwerp',
       'wta_bayonne',
       'wta_sapporo',
       'wta_masters',
       'wta_seattle',
       'wta_taranto',
       'wta_modena',
       'wta_finals',
       'wta_orange',
       'wta_mahwah',
       'wta_moscow',
       'wta_awards',
       'wta_nagoya',
       'wta_sydney',
       'wta_athens',
       'wta_warsaw',
       'wta_tokyo',
       'wta_seoul',
       'wta_bali',
       'wta_tour',
       'wta_bol'],
 'c': ['wtc_championship',
       'wtc_collapse',
       'wtc_bathtub',
       'wtc_cross',
       'wtc_wharf',
       'wtc_cough',
       'wtc_view',
       'wtc_expo',
       'wtc_9/11',
       'wtc_lung',
       'wtc_site',
       'wtc_nyc',
       'wtc_2',
       'wtc_1',
       'wtc_3'],
 'g': ['wtg_records', 'wtg_morton'],
 'h': ['wthyr_bendragon'],
 'i': ['wti_transport', 'wtii_records'],
 'l': ['wtls_radio'],
 'n': ['wtn_champ'],
 'o': ['wto_protests',
       'wto/fta_moot',
       'wto_members',
       'wtop_radio',
       'wto_riots',
       'wto_riot',
       'wto_ab'],
 'r': ['wtr-ten10_racing'],
 's': ['wts_group', 'wts_.50'],
 't': ['wtt_reduction', 'wtt_hk'],
 'v': ['wtvm/wrbl/wvrk_tower', 'wtv_gracanica', 'wtvy-tv_tower', 'wtvd_tower'],
 'x': ['wtxf-tv_personalities']}
