
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_hs = {'_': ['hs_koningin_regentes',
       'hs2_rolling_stock',
       'hs_postcode_area',
       'hs_timber_group',
       'hs_produkt_vhs',
       'hs_red_top',
       'hs_and_ts'],
 'a': ['hsanda_gol_formation',
       'hsaung_wutyee_may',
       'hsan_type_iii',
       'hsan_type_ii',
       'hsan_type_iv',
       'hsan_type_v',
       'hsan_type_4',
       'hsan_type_i',
       'hsan_type_5',
       'hsan_type_3',
       'hsan_type_2',
       'hsan_type_1'],
 'b': ['hsbc_champions_tournament',
       'hsbc_finance_corporation',
       'hsbc_continental_europe',
       'hsbc_insurance_brokers',
       "hsbc_women's_champions",
       'hsbc_guyerzeller_bank',
       'hsbc_halbis_partners',
       'hsbc_canada_building',
       'hsbc_bank_australia',
       'hsbc_bank_singapore',
       'hsbc_bank_argentina',
       'hsbc_bank_malaysia',
       'hsbc_north_america',
       'hsbc_bank_building',
       'hsbc_bank_georgia',
       'hsbc_bank_bermuda',
       'hsb_turning_torso',
       'hsbc_holdings_plc',
       'hsbc_saudi_arabia',
       'hsbc_private_bank',
       'hsb_colour_space',
       'hsbc_bank_canada',
       'hsbc_bank_polska',
       'hsbc_bank_panama',
       'hsbc_trinkaus_ag',
       'hsbc_bank_malta',
       'hsbc_brazil_cup',
       'hsbc_bank_egypt',
       'hsbc_bank_india',
       'hsb_color_space',
       'hsbc_hldgs_plc',
       'hsbc_sri_lanka',
       'hsbc_mexico_sa',
       'hsbc_bank_usa'],
 'c': ['hsc70_heat-shock_proteins',
       'hsc_distinction_courses',
       'hsc_benchijigua_express',
       'hsc_hellenic_highspeed',
       'hsc_betancuria_express',
       'hsc_condor_liberation',
       'hsc_worldchampion_jet',
       'hsc_hoverspeed_france',
       'hsc_superseacat_three',
       'hsc_superseacat_four',
       'hsc_santorini_palace',
       'hsc_atlantic_express',
       'hsc_sardegna_express',
       'hsc_fastcat_shanklin',
       'hsc_speedrunner_iii',
       'hsc_seacat_boulogne',
       'hsc_stena_discovery',
       'hsc_superseacat_two',
       'hsc_bocayna_express',
       'hsc_aeolos_kenteris',
       'hsc_autoexpress_two',
       'hsc_condor_voyager',
       'hsc_hss_discovery',
       'hsc_caldera_vista',
       'hsc_stena_voyager',
       'hsc_almudaina_dos',
       'hsc_natchan_world',
       'hsc_cecilia_payne',
       'hsc_condor_rapide',
       'hsc_dublin_swift',
       'hsc_seacat_norge',
       'hsc_fastcat_ryde',
       'hsc_lake_express',
       'hsc_gotlandia_ii',
       'hsc_2000_coburg',
       'hsc_highspeed_4',
       'hsc_t&t_spirit',
       'hsc_tarifa_jet',
       'hsc_speed_jet',
       'hsc_condor_10',
       'hsc_fjord_cat',
       'hsc_express_1',
       'hsc_express_4',
       'hsc_incat_059',
       'hsc_express_3',
       'hsc_naxos_jet',
       'hsc_incat_046',
       'hsc_incat_050',
       'hsc_express_2',
       'hsc_jaume_ii',
       'hsc_max_mols',
       'hsc_mega_jet'],
 'e': ['hse_high_school'],
 'f': ['hsf_cruise_bonaria'],
 'g': ['hsg_bad_wildungen'],
 'h': ['hsh_nordbank_arena',
       'hsh_class_t211.0',
       'hsh_nordbank_ag',
       'hsh_class_72',
       'hsh_class_31'],
 'i': ['hsinchu_international_school',
       'hsinchu_county_constituency',
       'hsinjuang_baseball_stadium',
       'hsinchu_county_government',
       'hsinchu_city_constituency',
       'hsinchu_chenghuang_temple',
       'hsinchu_metropolitan_area',
       'hsinjuang_baseball_field',
       'hsinchu_railway_station',
       'hsinchu_american_school',
       'hsinchu_city_government',
       'hsin_chong_construction',
       'hsinchu_industrial_park',
       'hsinchu_county_council',
       'hsinchu_county_stadium',
       'hsingyuan_power_plant',
       'hsingneng_power_plant',
       'hsiahsing_power_plant',
       'hsi-yue_fan-kuo_chih',
       'hsinchu_science_park',
       'hsieh-ho_power_plant',
       'hsin_usurper_dynasty',
       'hsiu-lien_annette_lu',
       'hsinchu_city_council',
       'hsing-wu_high_school',
       'hsinchu_jko_lioneers',
       'hsintao_power_plant',
       'hsing_wu_university',
       'hsinchu_fish_harbor',
       'hsinchu_hsr_station',
       'hsinhwa_news_agency',
       'hsi-yu_fan-kuo_chih',
       'hsi_lai_university',
       'hsi_hseng_township',
       'hsinta_power_plant',
       'hsi-chun_mike_hua',
       'hsieh_chia_hsian',
       'hsien_chung_wang',
       'hsi_tseng_tsiang',
       'hsi_hsia_kingdom',
       'hsin_ji_building',
       'hsi_color_space',
       'hsing_yin_shean',
       'hsiung_feng_iie',
       'hsien_hsing_che',
       'hsiung_feng_iii',
       'hsing_chung_hui',
       'hsiao_hsien_hou',
       'hsiao_chi_hsin',
       'hsiao_hung_jen',
       'hsiung_feng_ii',
       'hsin_tien_city',
       'hsin_tung_yang',
       'hsi_lai_temple',
       'hsin_hsin_ming',
       'hsiung_feng_3',
       'hsiung_feng_i',
       'hsia_ling_jun',
       'hsiao_lan_yue',
       'hsing_i_chuan',
       'hsin_wan_pao',
       'hsiao_lan_yu',
       'hsin_pei_soh',
       'hsi_wang_mum',
       'hsieh_su_wei',
       'hsi_wang_mu',
       'hsi_duan_yu',
       'hsin_kuo_wu',
       'hsi_yu_chi'],
 'k': ['hsk_gradanski_zagreb',
       'hsk_zrinjski_mostar',
       'hsk_hajduk_zemun',
       'hsk_dunav_zemun'],
 'l': ['hsl-44_swamp_foxes', 'hsl_color_space', 'hsl_and_hsv'],
 'm': ['hsm-78_blue_hawks', 'hsm_hits_remixed', 'hsmn_type_2', 'hsmn_type_1'],
 'o': ['hso_khan_pha'],
 'p': ['hsp90_cis-regulatory_element',
       'hsp47_heat-shock_proteins',
       'hsp70_heat-shock_proteins',
       'hsp90_heat-shock_proteins',
       'hspq_protein_domain'],
 'q': ['hsql_database_engine'],
 'r': ['hsr_strongbad_email'],
 's': ['hss_stena_explorer'],
 'u': ['hsuehshan_mountain_range',
       'hsuan_chuang_university',
       'hsu_chung_pi-hsia',
       'hsu_peng_campaign',
       'hsueh_shou_sheng',
       'hsu_yun_temple',
       'hsu_eaint_san',
       'hsu_hai_ching',
       'hsu_yung_chin',
       'hsu_pan_htwar',
       'hsu_yun_tsiao',
       'hsu_and_chan',
       'hsu_wen_long',
       'hsu_li_yang',
       'hsu_lai_tai',
       'hsu_li_kong',
       'hsu_ta_tung',
       'hsu_wei_lun',
       'hsu_tzu_yi',
       'hsu_fu_chi'],
 'v': ['hsv_borussia_friedenstal',
       'hsv_senator_signature',
       'hsv-x1_joint_venture',
       'hsv-1_joint_venture',
       'hsv_de_zuidvogels',
       'hsv_avalanche_suv',
       'hsv_avalanche_xuv',
       'hsv_clubsport_r8',
       'hsv_colour_space',
       'hsv_color_space',
       'hsv_dealer_team',
       'hsv_coupe_gts',
       'hsv_gts_300',
       'hsv_and_hsl'],
 'w': ['hswms_drottning_victoria',
       'hswms_john_ericsson',
       'hswms_clas_fleming',
       'hswms_claes_uggla',
       'hswms_tre_kronor',
       'hswms_gota_lejon',
       'hswms_klas_uggla',
       'hswms_oscar_ii',
       'hswms_gustaf_v'],
 'y': ['hsy-55_class_gunboat']}
