
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_hc = {'_': ['hc_nizhnekamsk_neftekhimik',
       'hc_neftekhimik_nizhnekamsk',
       'hc_pustertal-val_pusteria',
       'hc_shakhtyor_prokopyevsk',
       'hc_zntu-zab_zaporozhye',
       'hc_olimpus-85_chisinau',
       'hc_shakhtyor_soligorsk',
       'hc_steelers_kapfenberg',
       'hc_motor_zaporizhzhia',
       'hc_stadion_litomerice',
       'hc_dnepryanka_kherson',
       'hc_odorheiu_secuiesc',
       'hc_berounsti_medvedi',
       'hc_sibir_novosibirsk',
       'hc_kaustik_volgograd',
       'hc_la_chaux-de-fonds',
       'hc_moeller_pardubice',
       'hc_klein_zwitserland',
       'hc_slovan_bratislava',
       'hc_vitkovice_ridera',
       'hc_achilles_bocholt',
       'hc_steaua_bucuresti',
       'hc_karpaty_uzhgorod',
       'hc_riviera_chisinau',
       'hc_ztr_zaporizhzhia',
       'hc_lions_courmaosta',
       'hc-144_ocean_sentry',
       'hc_dynamo_pardubice',
       'hc_moller_pardubice',
       'hc_kuban_krasnodar',
       'hc_eaton_pardubice',
       'hc_sfantu_gheorghe',
       'hc_sporta_hlohovec',
       'hc_pustertal_wolfe',
       'hc_presov_penguins',
       'hc_spartak_moscow',
       'hc_ocelari_trinec',
       'hc_ramat_hasharon',
       'hc_vityaz_chekhov',
       'hc_erik_midelfort',
       'hc_viking_tallinn',
       'hc_vipers_tallinn',
       'hc_lada_togliatti',
       'hc_andersen_arena',
       'hc_dunarea_braila',
       'hc_dinamo_yerevan',
       'hc_robbins_landon',
       'hc_twk_innsbruck',
       'hc_dukla_jihlava',
       'hc_dinan_quevert',
       'hc_dynamo_moscow',
       'hc_empor_rostock',
       'hc_bolzano_bozen',
       'hc_zvezda_moscow',
       'hc_meshkov_brest',
       'hc_lada_tolyatti',
       'hc_milano_vipers',
       'hc_dinamo_moscow',
       'hc_torpedo_gorky',
       'hc_eppan_pirates',
       'hc_svht_dracones',
       'hc_atlant_moscow',
       'hc_twc_innsbruck',
       'hc_fassa_falcons',
       'hc_sparta_prague',
       'hc_moscow_dynamo',
       'hc_slavia_prague',
       'hc_devils_milano',
       'hc_levski_sofia',
       'hc_slezan_opava',
       'hc_neman_grodno',
       'hc_slavia_sofia',
       'hc_spartak_kyiv',
       'hc_milano_saima',
       'hc_karlovy_vary',
       'hc_dynamo_minsk',
       'hc_bosna_visoko',
       'hc_slavia_praha',
       'hc_sparta_praha',
       'hc_wikov_hronov',
       'hc_dinamo_minsk',
       'hc_rabat_kladno',
       'hc_dukla_prague',
       'hc_zubr_prerov',
       'hc_sm_garliava',
       'hc_kometa_brno',
       'hc_teramo_2002',
       'hc_46_bardejov',
       'hc_matthew_sim',
       'hc_vita_hasten',
       'hc_cska_moscow',
       'hc_dukla_praha',
       'hc_skoda_plzen',
       'hc_oktan_perm',
       'hc_nove_zamky',
       'hc_agidel_ufa',
       'hc_lev_poprad',
       'hc_19_humenne',
       'hc_prange_co.',
       'hc_cska_sofia',
       'hc_sokil_kyiv',
       'hc_21_presov',
       'hc_atk_praha',
       'hc_nsa_sofia',
       'hc_lev_praha',
       'hc_07_detva',
       'hc_mvd_tver',
       'hc_red_ice',
       'hc_bat_yam'],
 'b': ['hcb_ticino_rockets'],
 'i': ['hci_equity_partners'],
 'j': ['hcj_milano_vipers'],
 'l': ['hcl_color_space'],
 'm': ['hcm_baia_mare'],
 'p': ['hcpcs_level_2'],
 'r': ['hcr_manor_care'],
 's': ['hcs_clustering_algorithm', 'hcs_chapel_choir'],
 't': ['hct_co.,_ltd.']}
