#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# AUTO-GENERATED CONTENT
d_stem_zm = {'zmachinski': {'zmachinsky': []},
 'zmagazin': {'zmagazine': []},
 'zmajev': {'zmajevic': []},
 'zmaragdu': {'zmaragdus': []},
 'zmbabw': {'zmbabwe': []},
 'zme': {'zmes': []},
 'zmeini': {'zmeiny': []},
 'zmeni': {'zmeny': []},
 'zmeskal': {'zmeskall': []},
 'zmi': {'zmy': []},
 'zmian': {'zmiane': []},
 'zmiani': {'zmianie': [], 'zmiany': []},
 'zmienion': {'zmienione': []},
 'zmienn': {'zmienne': []},
 'zmienni': {'zmienny': []},
 'zmijewski': {'zmijewsky': []},
 'zmine': {'zmines': []},
 'zmini': {'zminis': []},
 'zmire': {'zmires': []},
 'zmiro': {'zmiros': []},
 'zmniejszani': {'zmniejszanie': []},
 'zmniejszeni': {'zmniejszenie': []},
 'zmo': {'zmos': []},
 'zmole': {'zmoles': []},
 'zmone': {'zmones': []},
 'zmotoryzowan': {'zmotoryzowane': []},
 'zmucki': {'zmucky': []},
 'zmuidina': {'zmuidinas': []},
 'zmuidzina': {'zmuidzinas': []},
 'zmuidzinaviciu': {'zmuidzinavicius': []}}
