
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_dp = {'_': ['dp-scouts',
       'dp-brane',
       'dp216',
       'dp-28',
       'dp-64',
       'dp-65',
       'dp28',
       'dp3t',
       'dp1',
       'dp2'],
 'a': ['dpa-714',
       'dpa-713',
       'dpakara',
       'dpa-bo',
       'dpagt1',
       'dpaint',
       'dpart',
       'dpapi',
       'dpath',
       'dpann',
       'dpaa',
       'dpad',
       'dpac',
       'dpag',
       'dpa'],
 'b': ['dpb1', 'dpbc', 'dpbs', 'dpb'],
 'c': ['dpcdsb', 'dpcch', 'dpcm', 'dpcu', 'dpcx', 'dpcp', 'dpca', 'dpc'],
 'd': ['dpdgroup', 'dpdpe', 'dpdch', 'dpda', 'dpds', 'dpdt', 'dpd'],
 'e': ['dpephos', 'dpep1', 'dpes', 'dpen', 'dpe'],
 'f': ['dpfgse-noe', 'dpf2', 'dpf1', 'dpf'],
 'g': ['dpgb', 'dpgc', 'dpg'],
 'h': ['dphm-rs',
       'dpharm',
       'dphil.',
       'dphb3k',
       'dphil',
       'dph1',
       'dphp',
       'dph5',
       'dphs',
       'dph'],
 'i': ['dpi-3290',
       'dpi-287',
       'dpi-221',
       'dpicm',
       'dpia',
       'dpir',
       'dpiw',
       'dpip',
       'dpie',
       'dpic',
       'dpi'],
 'j': ['dpj'],
 'k': ['dpkg-deb', 'dpko', 'dpkg', 'dpk'],
 'l': ['dplanet', 'dplay', 'dplyr', 'dpll', 'dpld', 'dpl'],
 'm': ['dpm1', 'dpmo', 'dpmi', 'dpma', 'dpms', 'dpm2', 'dpmc', 'dpm3', 'dpm'],
 'n': ['dpnss', 'dpni', 'dpn'],
 'o': ['dpon-chen', 'dpoll', 'dpop', 'dpoy', 'dpof', 'dpo'],
 'p': ['dpp-iv',
       'dpp10',
       'dpp08',
       'dppa3',
       'dppa2',
       'dppiv',
       'dpp7',
       'dpph',
       'dpp1',
       'dppa',
       'dppe',
       'dppc',
       'dpp6',
       'dpp4',
       'dpp9',
       'dpp3',
       'dppo',
       'dppx',
       'dpp8',
       'dpp'],
 'r': ['dpreview.com',
       'dprevanq',
       'dpreview',
       'dprevank',
       'dprabak',
       'dprobes',
       'dpress',
       'dpram',
       'dprof',
       'dprnk',
       'dprm',
       'dprk',
       'dprc',
       'dprg',
       'dpr'],
 's': ['dpsu.com',
       'dps-mmod',
       'dpser',
       'dpsir',
       'dpst',
       'dpsg',
       'dpss',
       'dpsu',
       'dpsk',
       'dps'],
 't': ['dpt-mph', 'dptt', 'dpth', 'dpt'],
 'u': ['dpubs', 'dpu'],
 'v': ['dpvweb', 'dpvat', 'dpvm', 'dpv'],
 'w': ['dpws', 'dpwn', 'dpw'],
 'x': ['dpx-mp062', 'dpx'],
 'y': ['dpy19l2', 'dpysl2', 'dpysl4', 'dpysl5', 'dpysl3', 'dpys'],
 'z': ['dpz']}
