
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_nn = {'nn.wikipedia.org': 'norwegian_wikipedia',
 'nn2s': 'nothing_nice_to_say',
 'nnachi': 'nnachi_ipia',
 'nnao2': 'sodium_nitrite',
 'nnao3': 'sodium_nitrate',
 'nnapulitano': 'neapolitan_language',
 'nnck': 'no-neck_blues_band',
 'nndb.com': 'nndb',
 'nndym': 'narnarayan_dev_yuvak_mandal',
 'nnec': 'north_nova_education_centre',
 'nnekwunwenyi': 'mami_wata',
 'nnemp': 'electromagnetic_pulse',
 'nnepra': 'downeaster',
 'nnfa': 'natural_products_association',
 'nnfcc': 'national_non-food_crops_centre',
 'nnhs': 'naperville_north_high_school',
 'nnicu': 'neonatal_intensive-care_unit',
 'nnirvi': 'niko_nirvi',
 'nnjil': 'northern_new_jersey_interscholastic_league',
 'nnkieh': 'national_nanke_international_experimental_high_school',
 'nnls': 'sternberg_centre',
 'nnmc': 'national_naval_medical_center',
 'nnmf': 'non-negative_matrix_factorization',
 'nnoc': 'california_nurses_association/national_nurses_organizing_committee',
 'nnor': 'logical_nor',
 'nnos': 'nitric_oxide_synthase',
 'nnpa': 'national_newspaper_publishers_association',
 'nnpc': 'nigerian_national_petroleum_corporation',
 'nnpi-c': 'naval_nuclear_propulsion_information',
 'nnpi-u': 'naval_nuclear_propulsion_information',
 'nnpt': 'nuclear_non-proliferation_treaty',
 'nnptc': 'naval_nuclear_power_training_command',
 'nnrp': 'network_news_transfer_protocol',
 'nnrti': 'reverse_transcriptase_inhibitor',
 'nnsa': 'national_nuclear_security_administration',
 'nnsc': 'neutral_nations_supervisory_commission',
 'nnsl': 'northern_news_services',
 'nnsma': 'nizhny_novgorod_state_medical_academy',
 'nnsy': 'norfolk_naval_shipyard',
 'nntn': 'not_necessarily_the_news',
 'nntool': 'matlab',
 'nntp': 'network_news_transfer_protocol',
 'nntps': 'network_news_transfer_protocol',
 'nnwa': 'nordic_walking',
 'nnyx': 'national_new_york_central_railroad_museum'}
        