
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_zu = {'zu_al-nun_al-misri': 'dhul-nun_al-misri',
 'zubair_ibn_al-awwam': 'hadith_of_the_ten_promised_paradise',
 'zubair_safe_house': 'al-qaeda_safe_house',
 'zubayr_al_halli': 'abu_zubayr_al_halili',
 'zubayr_ibn_al-awwam': 'zubair_ibn_al-awam',
 'zubayr_rahama_pasha': 'al-zubayr_rahma_mansur',
 'zuben_el_genubi': 'alpha_librae',
 'zuber_et_cie': 'zuber_cie',
 'zubin_potok_municipality': 'zubin_potok',
 'zubrod_performance_scale': 'performance_status',
 'zubrod_performance_score': 'performance_status',
 'zucchetti_reggio_emilia': 'pallacanestro_reggiana',
 'zuckerman_induction_functor': 'zuckerman_functor',
 'zuenir_carlos_ventura': 'zuenir_ventura',
 'zuerich_financial_services': 'zurich_financial_services',
 'zuhri_ibn_shab': 'ibn_shihab_al-zuhri',
 'zuid-afrikaansche_republiek_politie': 'south_african_republic_police',
 'zuid_afrika_republic': 'south_african_republic',
 'zuid_afrikaansche_republik': 'south_african_republic',
 'zuid_afrikaanse_republiek': 'south_african_republic',
 'zuid_hollandse_waard': 'grote_hollandse_waard',
 'zuiderkruis_class_jss': 'zuiderkruis_class_support_ship',
 'zuilen_en_zwezereng': 'zuilen',
 'zujajat_ul_masaabih': 'zujajat_al-masabih',
 'zul_kifu_salami': 'zul_kifl_salami',
 'zulema_fatima_yoma': 'zulema_yoma',
 'zuleyka_rivera_mendoza': 'zuleyka_rivera',
 'zulfiqar_ali_bhutto': 'zulfikar_ali_bhutto',
 'zulfiqqar_ali_bhuttoo': 'zulfikar_ali_bhutto',
 'zulia_toad-headed_turtle': 'zulia_toad-headed_sideneck',
 'zulifiqar_ali_bhutto': 'zulfikar_ali_bhutto',
 'zulima_v._farber': 'zulima_farber',
 'zuloaga_y_zabaleta': 'ignacio_zuloaga',
 'zulu_round_potato': 'plectranthus_rotundifolius',
 'zulu_stick_fighting': 'nguni_stick_fighting',
 'zululand_dwarf_chameleon': 'zululand_dwarf_chamaeleon',
 'zumbi_dos_palmares': 'zumbi',
 'zumo_juice_bar': 'zumo',
 'zumo_smoothie_bar': 'zumo',
 'zumwalt_class_destroyers': 'zumwalt_class_destroyer',
 'zumwalt_class_warship': 'zumwalt_class_destroyer',
 'zumwalt_class_warships': 'zumwalt_class_destroyer',
 'zune_market_place': 'zune',
 'zune_media_player': 'zune',
 'zuni_public_schools': 'zuni_public_school_district',
 'zuni_school_district': 'zuni_public_school_district',
 'zunut_dag_dibi': 'zunud',
 'zuojia_publishing_house': 'writers_publishing_house',
 'zurab_revazovich_kokoyev': 'zurab_kokoyev',
 'zurcher_kammer_orchester': 'zurich_chamber_orchestra',
 'zuri_national_park': 'binder_park_zoo',
 'zurich_chamber_orchester': 'zurich_chamber_orchestra',
 'zurich_direct_underwriters': 'zurich_financial_services',
 'zurich_north_america': 'zurich_financial_services',
 'zurich_stock_exchange': 'six_swiss_exchange'}
        