__version__ = '0.1.10'
__title__ = 'rest_typed_models'
__description__ = 'Typed model serializers for Django REST Framework.'
__url__ = 'https://github.com/denisorehovsky/django-rest-polymorphic'
__author__ = 'Krystof Beuermann'
__author_email__ = 'krystof+django@blackbox.ms'
__license__ = 'MIT License'
