
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_vx = {'_': ['vx-rexx',
       'vx9amk',
       'vx8300',
       'vx-950',
       'vx8700',
       'vx1000',
       'vx-170',
       'vx-7rb',
       'vx-20',
       'vx220',
       'vx-30',
       'vx-2r',
       'vx-6r',
       'vx-7r',
       'vx-31',
       'vx-23',
       'vx-3',
       'vx-6',
       'vx-1',
       'vx-9',
       'vx-4',
       'vx32',
       'vx3'],
 'a': ['vxa'],
 'c': ['vxc'],
 'd': ['vxd'],
 'e': ['vxe-6'],
 'f': ['vxfs'],
 'i': ['vxinsight', 'vxibus', 'vxi'],
 'l': ['vxl'],
 'm': ['vxml'],
 'n': ['vxn'],
 'r': ['vxr8', 'vxr'],
 's': ['vxs-1', 'vxsf', 'vxs'],
 't': ['vxtreme'],
 'u': ['vxut'],
 'v': ['vxvm', 'vxv'],
 'w': ['vxworks'],
 'x': ['vxx']}
