
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ub = {'_': ['ub_chartres_metropole',
       'ub_iwerks_studio',
       'ub_postcode_area',
       'ub_machine_gun',
       'ub_postal_area',
       'ub_law_school',
       'ub_la_palma'],
 'a': ['ubayd-allah_ibn_abd-allah',
       'ubaidullah_bin_abdullah',
       'ubaydallah_ibn_al-mahdi',
       'ubaidullah_ibn_abdullah',
       'ubaydullah_ibn_al-abbas',
       'ubaydallah_ibn_al-sari',
       'ubayd-allah_ibn_ziyad',
       'ubayd-allah_ibn_jahsh',
       'ubaldo_matildo_fillol',
       'ubaid-allah_ibn_ziyad',
       'ubayd_allah_al-anbari',
       'ubaydah_ibn_al-harith',
       'ubaldo_aguilar_flores',
       'ubajara_national_park',
       'ubayd_allah_al-mahdi',
       'ubaidallah_ibn_ziyad',
       'ubangi_young_workers',
       'ubaida_ibn_al-harith',
       'ubayama_shell_mound',
       'ubaldo_fillol_award',
       'ubashi_khong_tayiji',
       'ubaldo_degli_uberti',
       'ubaldo_nestor_sacco',
       'ubadah_ibn_al-samit',
       'uba_protein_domain',
       'ubaldo_ii_visconti',
       'ubasi_khong_tayiji',
       'ubaidur_rahman_zia',
       'ubaid_ullah_mayar',
       'ubaldo_i_visconti',
       'ubaldo_of_gallura',
       'ubach_over_worms',
       'ubay_ibn_khalaf',
       "ubayy_ibn_ka'b"],
 'b': ['ubbi_dubbi_language', 'ubbo_j._albertsen'],
 'c': ['ubc_thunderbirds_football',
       'ubc_okanagan_exchange',
       'ubc_thunderbird_arena',
       'ubc_debating_society',
       'ubc_botanical_garden',
       'ubc_computer_science',
       'ubc_gussing_knights',
       'ubc_robson_square',
       'ubc_okanagan_heat',
       'ubc_law_faculty',
       'ubc_media_group',
       'ubc_law_school'],
 'd': ['ubd_ibm_centre'],
 'e': ['ubeidiya_prehistoric_site',
       'uberlandia_esporte_clube',
       'uberto_rossi_lanfranchi',
       'ubeshwar_mahadev_temple',
       'ube_frontier_university',
       'ubertinello_da_carrara',
       'ubeidiya,_west_bank',
       'uber_den_tellerrand',
       'ubertino_da_carrara',
       'ubertino_de_casale',
       'uberaba_sport_club',
       'ubertino_of_casale',
       'ubertino_da_casale',
       'uberto_de_morpurgo',
       'uberto_da_carrara',
       'ubertin_of_casale',
       'uberall_zu_hause',
       'uber_die_weiber',
       'ube_kosan_open',
       'ube_ice_cream'],
 'i': ['ubiquitin-protein_ligase_complexes',
       'ubiquitin_c-terminal_hydrolase',
       'ubiquitin-protein_ligase_e3b',
       'ubiquitin_proteasome_pathway',
       'ubiquitin_proteasome_system',
       'ubiquitin_proteosome_system',
       'ubisoft_entertainment_inc',
       'ubiquitous_sensor_network',
       'ubirajara_ribeiro_martins',
       'ubiquitous_synergy_seeker',
       'ubique_barracks,_widnes',
       'ubiratan_pereira_maciel',
       'ubiquitinyl_hydrolase_1',
       'ubiratan_esporte_clube',
       'ubi_soft_entertainment',
       'ubirajara,_sao_paulo',
       'ubisoft_quebec_city',
       'ubid_protein_domain',
       'ubi_theatre_leipzig',
       'ubisoft_blue_byte',
       'ubieranie_do_snu',
       'ubiq_sf_magazine',
       'ubi_mrt_station',
       'ubi_studios_uk',
       'ubi_sunt_theme',
       'ubi_de_feo'],
 'l': ['ubl_texas_wranglers'],
 'm': ['ubm_northern_classic', 'ubm_technology_group'],
 'o': ['ubon_ratchathanee_university',
       'ubon_ratchathani_university',
       'ubon_rachathanee_university',
       'ubon_ratchatani_university',
       'ubon_rachathani_university',
       'ubon_rajathanee_university',
       'ubonrak_thonburi_hospital',
       'ubon_ratchathani_province',
       'ubon_rajathani_university',
       'ubon_ratchathani_airport',
       'ubora_residential_tower',
       'ubombo_ranches_airfield',
       'ubol_rattana_rajakanya',
       'ubora_commercial_tower',
       'ubon_candle_festival',
       'ubon_kruanapat_f.c.',
       'uboro_isong_inyang',
       'ubong_moses_ekpai',
       'ubodung_udung_uko',
       'ubon_united_f.c.',
       'ubol_ratana_dam',
       'ubon_united_fc',
       'ubon_air_base'],
 's': ['ubs_financial_services',
       'ubs_investment_bank',
       'ubs_capital_asia',
       'ubs_nuur_basin'],
 'u': ['ubuntu_professional_certification',
       'ubuhlebezwe_local_municipality',
       'ubuntu_local_municipality',
       'ubuntu_customization_kit',
       'ubuntu_restricted_extras',
       'ubuntu_ultimate_edition',
       'ubuntu_software_center',
       'ubuntu_netbook_edition',
       'ubuntu_version_history',
       'ubuntu_release_history',
       'ubuntu_connected_front',
       'ubu_repertory_theater',
       'ubuntu_buddhist_remix',
       'ubuntu_software_store',
       'ubuntu_muslim_edition',
       'ubuntu_netbook_remix',
       'ubuntu_super_edition',
       'ubuntu_colors_theme',
       'ubud_monkey_forest',
       'ubuntu_mid_edition',
       'ubuntu_global_jam',
       'ubuntu_live_usb'],
 'v': ['ubv_photometric_system', 'ubv_m_24264', 'ubv_m_5351', 'ubv_m_8173'],
 'x': ['ubx_protein_domain']}
