#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# AUTO-GENERATED CONTENT
d_stem_gp = {'gpa': {'gpa': []},
             'gpal': {'gpals': []},
             'gpart': {'gparted': []},
             'gpat': {'gpats': []},
             'gpb': {'gpbs': []},
             'gpc': {'gpcs': []},
             'gpci': {'gpcis': []},
             'gpcr': {'gpcrs': []},
             'gpd': {'gpds': []},
             'gpe': {'gpes': []},
             'gpeak': {'gpeaking': [], 'gpeaks': []},
             'gpear': {'gpeare': []},
             'gpeci': {'gpecies': []},
             'gpecif': {'gpecific': []},
             'gpf': {'gpfs': []},
             'gpfh': {'gpfhs': []},
             'gpg': {'gpgs': []},
             'gph': {'gphs': []},
             'gpi': {'gpis': [], 'gpy': []},
             'gpianchor': {'gpianchored': []},
             'gpilink': {'gpilinked': []},
             'gpirit': {'gpirits': []},
             'gpiritu': {'gpiritual': []},
             'gpl': {'gpls': []},
             'gplegisl': {'gplegislation': []},
             'gpm': {'gpms': []},
             'gpmg': {'gpmgs': []},
             'gpn': {'gpns': []},
             'gpneral': {'gpnerally': []},
             'gpniu': {'gpnius': []},
             'gpnpralli': {'gpnprally': []},
             'gpo': {'gpo': []},
             'gpod': {'gpodness': [], 'gpods': []},
             'gpondenc': {'gpondence': []},
             'gporg': {'gporge': []},
             'gpp': {'gpps': []},
             'gpr': {'gprs': []},
             'gprder': {'gprders': []},
             'gprmani': {'gprmany': []},
             'gproduct': {'gproducts': []},
             'gprom': {'gproms': []},
             'gprotein': {'gproteins': []},
             'gpsbase': {'gpsbased': []},
             'gpsderiv': {'gpsderived': []},
             'gpsg': {'gpsgs': []},
             'gpt': {'gpts': []},
             'gption': {'gptions': []},
             'gptm': {'gptms': []},
             'gpu': {'gpus': []},
             'gpupdat': {'gpupdate': []},
             'gpvern': {'gpverned': []},
             'gpvernment': {'gpvernments': []},
             'gpw': {'gpws': []},
             'gpww': {'gpwws': []}}
