#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# AUTO-GENERATED CONTENT
d_stem_bw = {'bwa': {'bwas': []},
 'bwais': {'bwaise': []},
 'bwallow': {'bwallowed': []},
 'bwamba': {'bwambae': []},
 'bwambal': {'bwambale': []},
 'bwamp': {'bwamps': []},
 'bwana': {'bwanas': []},
 'bwandi': {'bwandy': []},
 'bwanj': {'bwanje': []},
 'bward': {'bwards': []},
 'bwarm': {'bwarmed': [], 'bwarming': [], 'bwarms': []},
 'bwatiy': {'bwatiye': []},
 'bwave': {'bwaves': []},
 'bway': {'bwayed': []},
 'bwayis': {'bwayise': []},
 'bwb': {'bwbs': []},
 'bwc': {'bwcs': []},
 'bwe': {'bwes': []},
 'bwear': {'bwearing': []},
 'bweep': {'bweeps': []},
 'bweet': {'bweetness': [], 'bweets': []},
 'bweetli': {'bweetly': []},
 'bweight': {'bweighted': []},
 'bwell': {'bwelled': [], 'bwelling': ['bwellings'], 'bwells': []},
 'bwelling': ['bwellings'],
 'bwend': {'bwende': []},
 'bwengy': {'bwengye': []},
 'bwer': {'bwers': []},
 'bweranyang': {'bweranyange': []},
 'bwere': {'bwered': []},
 'bweup': {'bweupe': []},
 'bweyorer': {'bweyorere': []},
 'bwf': {'bwfs': []},
 'bwgraphi': {'bwgraphie': [], 'bwgraphy': []},
 'bwi': {'bwis': [], 'bwy': []},
 'bwiftli': {'bwiftly': []},
 'bwilil': {'bwilile': []},
 'bwim': {'bwimming': []},
 'bwing': {'bwinging': [], 'bwings': []},
 'bwk': {'bwks': []},
 'bwl': {'bwls': []},
 'bwo': {'bwos': []},
 'bwone': {'bwones': []},
 'bword': {'bwords': []},
 'bwoy': {'bwoys': []},
 'bwphi': {'bwphys': []},
 'bwr': {'bwr': []},
 'bwu': {'bwus': []}}
