#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# AUTO-GENERATED CONTENT
d_stem_bd = {'bda': {'bdas': []},
 'bdarnai': {'bdarnais': []},
 'bdat': {'bdats': []},
 'bday': {'bdays': []},
 'bdb': {'bdbs': []},
 'bdbb': {'bdbbs': []},
 'bdbhan': {'bdbhans': []},
 'bdbi': {'bdbis': []},
 'bdc': {'bdcs': []},
 'bdd': {'bdds': []},
 'bddbase': {'bddbased': []},
 'bddi': {'bddies': [], 'bddy': []},
 'bddk': {'bddks': []},
 'bde': {'bdes': []},
 'bdefici': {'bdeficient': []},
 'bdefin': {'bdefined': []},
 'bdeliti': {'bdelity': []},
 'bdellida': {'bdellidae': []},
 'bdellod': {'bdellodes': []},
 'bdellodrilu': {'bdellodrilus': []},
 'bdelloid': {'bdelloids': []},
 'bdellonyssu': {'bdellonyssus': []},
 'bdellovibrio': {'bdellovibrios': []},
 'bdemnit': {'bdemnites': []},
 'bdenot': {'bdenotes': []},
 'bdeogal': {'bdeogale': []},
 'bdepart': {'bdepartment': ['bdepartments']},
 'bdepartment': ['bdepartments'],
 'bdepend': {'bdependent': [], 'bdepends': []},
 'bderiv': {'bderived': []},
 'bdetermin': {'bdetermined': []},
 'bdf': {'bdfs': []},
 'bdg': {'bdgs': []},
 'bdgiqu': {'bdgique': []},
 'bdguin': {'bdguines': []},
 'bdh': {'bdhs': []},
 'bdhlau': {'bdhlaus': []},
 'bdhmen': {'bdhmens': []},
 'bdhmisch': {'bdhmische': []},
 'bdi': {'bdies': [], 'bdis': [], 'bdy': ['bdys']},
 'bdicat': {'bdication': []},
 'bdicion': {'bdiciones': []},
 'bdiev': {'bdieve': ['bdieved']},
 'bdieve': ['bdieved'],
 'bdiffer': {'bdifference': ['bdifferences'], 'bdifferent': []},
 'bdifference': ['bdifferences'],
 'bdinn': {'bdinne': []},
 'bdirect': {'bdirection': []},
 'bdisariu': {'bdisarius': []},
 'bdite': {'bdited': []},
 'bditor': {'bditors': []},
 'bditori': {'bditorial': []},
 'bdivis': {'bdivision': []},
 'bdkesi': {'bdkesy': []},
 'bdl': {'bdls': []},
 'bdlconi': {'bdlcony': []},
 'bdle': {'bdles': []},
 'bdlevu': {'bdlevue': []},
 'bdli': {'bdly': []},
 'bdm': {'bdms': []},
 'bdn': {'bdns': []},
 'bdnd': {'bdnds': []},
 'bdndh': {'bdndhs': []},
 'bdne': {'bdnes': []},
 'bdnffi': {'bdnffy': []},
 'bdni': {'bdnis': []},
 'bdnign': {'bdnigne': []},
 'bdo': {'bdos': []},
 'bdoe': {'bdoes': []},
 'bdok': {'bdoks': []},
 'bdomin': {'bdominal': []},
 'bdong': {'bdonging': []},
 'bdope': {'bdoped': []},
 'bdp': {'bdps': []},
 'bdqueri': {'bdquery': []},
 'bdr': {'bdrs': []},
 'bdrani': {'bdrany': []},
 'bdrbara': {'bdrbaras': []},
 'bdrbaro': {'bdrbaros': []},
 'bdrdni': {'bdrdny': []},
 'bdrdo': {'bdrdos': []},
 'bdrdossi': {'bdrdossy': []},
 'bdrenfamili': {'bdrenfamilie': []},
 'bdrenhdut': {'bdrenhduter': []},
 'bdrenreit': {'bdrenreiter': []},
 'bdrgir': {'bdrgirs': []},
 'bdri': {'bdris': [], 'bdry': []},
 'bdrm': {'bdrms': []},
 'bdrn': {'bdrns': []},
 'bdrsoni': {'bdrsony': []},
 'bdrull': {'bdrulle': []},
 'bdsendorf': {'bdsendorfer': []},
 'bdsica': {'bdsicas': []},
 'bdsico': {'bdsicos': []},
 'bdt': {'bdts': []},
 'bdtard': {'bdtarde': ['bdtardes'], 'bdtards': []},
 'bdtarde': ['bdtardes'],
 'bdtc': {'bdtcs': []},
 'bdte': {'bdtes': []},
 'bdteill': {'bdteille': []},
 'bdteli': {'bdtely': []},
 'bdthori': {'bdthory': []},
 'bdti': {'bdties': [], 'bdtis': []},
 'bdtimen': {'bdtimens': []},
 'bdtiment': {'bdtiments': []},
 'bdtisseur': {'bdtisseurs': []},
 'bdton': {'bdtons': []},
 'bdtonnet': {'bdtonnets': []},
 'bdtonnier': {'bdtonniers': []},
 'bdu': {'bdued': [], 'bdus': []},
 'bducat': {'bducation': ['bducational']},
 'bducation': ['bducational'],
 'bduerlich': {'bduerliche': []},
 'bdul': {'bduls': []},
 'bduoation': {'bduoational': []},
 'bdure': {'bduring': []},
 'bdv': {'bdvs': []},
 'bdvaro': {'bdvaros': []},
 'bdward': {'bdwardes': [], 'bdwards': []},
 'bdwi': {'bdwy': []},
 'bdy': ['bdys'],
 'bdz': {'bdzs': []},
 'bdzar': {'bdzars': []},
 'bdzdr': {'bdzdrs': []},
 'bdzier': {'bdziers': []},
 'bdziqu': {'bdzique': []}}
