
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_pz = {'_': ['pz-90', 'pz-61', 'pz865', 'pz-68', 'pz61'],
 'a': ['pzazz'],
 'c': ['pzc'],
 'e': ['pzed', 'pzev', 'pze'],
 'f': ['pzflex'],
 'g': ['pzg'],
 'h': ['pzh-2000', 'pzh2000', 'pzh'],
 'i': ['pzich'],
 'k': ['pzkw-iii', 'pzkpfw', 'pzko', 'pzkw', 'pzk'],
 'l': ['pzl-franklin',
       'pzl-bielsko',
       'pzl-swidnik',
       'pzl-mielec',
       'pzl-104',
       'pzl-105',
       'pzl-230',
       'pzl-130',
       'pzl-12',
       'pzl.26',
       'pzl.27',
       'pzl.16',
       'pzl.12',
       'pzl.43',
       'pzl.62',
       'pzl-3s',
       'pzl.19',
       'pzl-19',
       'pzl.55',
       'pzl-3',
       'pzl.4',
       'pzl.3',
       'pzl.6',
       'pzl-5',
       'pzl.5',
       'pzl'],
 'm': ['pzm21', 'pzm'],
 'o': ['pzombie', 'pzone', 'pzo'],
 'p': ['pzpn', 'pzp'],
 'q': ['pzq'],
 's': ['pzszach'],
 't': ['pzt'],
 'u': ['pzuk'],
 'y': ['pzy-clone', 'pzyche'],
 'z': ['pzzl']}
