
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_pq = {'_': ['pq-tree',
       'pq.13',
       'pq-13',
       'pq-18',
       'pq-14',
       'pq.16',
       'pq-17',
       'pq-16',
       'pq.17',
       'pq-15',
       'pq.18',
       'pq35',
       'pq16',
       'pq.5',
       'pq34',
       'pq.4',
       'pq-2',
       'pq.3',
       'pq17',
       'pq18',
       'pq-1',
       'pq-4',
       'pq.1',
       'pq.2',
       'pq-3',
       'pq13',
       'pq-5',
       'pq5',
       'pq3',
       'pq4',
       'pq2',
       'pq1'],
 'a': ['pqasso', 'pqa'],
 'b': ['pqbp1'],
 'c': ['pqcc', 'pqct', 'pqc'],
 'd': ['pqdif'],
 'f': ['pqfp', 'pqf'],
 'i': ['pqi'],
 'l': ['pqli', 'pql'],
 'm': ['pqmq'],
 'q': ['pqq'],
 'r': ['pqrst', 'pqrs'],
 's': ['pqs'],
 'u': ['pqube']}
