import libcst
from typing import Any

MAP_ReturnType: Any

class Visitor(libcst.CSTVisitor): ...

class Transformer(libcst.CSTTransformer):
    ImportALIAS: Any = ...
    def __init__(self, visitor: Any) -> None: ...
    def leave_ImportAlias_asname(self, node: Any) -> None: ...
    def leave_Call(self, original_node: Any, updated_node: Any): ...
