
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_vh = {'_': ['vh1_ill-ustrated',
       'vh1_storytellers',
       "vh1's_legends",
       'vh-71_kestrel',
       'vh-1_classic',
       'vh1_european',
       'vh1_megahits',
       'vh-1_country',
       'vh_viglielmo',
       'vh1_classics',
       'vh1_classic',
       'vh1_country',
       'vh1_polska',
       'vh1_brazil',
       'vh1_poland',
       'vh1_brasil',
       'vh1_europe',
       'vh-1_soul',
       'vh1_live!',
       'vh1_divas',
       'vh_lewis',
       'vh1_uno',
       'vh1_hd'],
 'c': ['vhc_sviesa'],
 'd': ['vhdl_93', 'vhdl_87'],
 'f': ['vhf_omnirange', 'vhf_records', 'vhf_radio', 'vhf_band'],
 'h': ['vhh_antibodies'],
 'i': ['vhi_healthcare'],
 'k': ['vhk_vsetin'],
 'l': ['vhl_championship'],
 'o': ['vhong_navarro'],
 's': ['vhs_collection',
       'vhs_j1256-1257',
       'vhs_kahloucha',
       'vhs_video',
       'vhs_head'],
 'v': ['vhv_group']}
