
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_vk = {'_': ['vk_samaranayake',
       'vk_wallstreet',
       'vk_singidunum',
       'vk_commodore',
       'vk_vojvodina',
       'vk_ramaswamy',
       'vk_prostejov',
       'vk_partizan',
       'vk_choudhry',
       'vk_zepperen',
       'vk_primorje',
       'vk_bhargava',
       'vk_beograd',
       'vk_opatija',
       'vk_sibenik',
       'vk_banjica',
       'vk_solaris',
       'vk_osijek',
       'vk_mornar',
       'vk_mobile',
       'vk_kladno',
       'vk_duggal',
       'vk_murthy',
       'vk_datta',
       'vk_dunav',
       'vk_rajah',
       'vk_gusar',
       'vk_sabac',
       'vk_becej',
       'vk_bosna',
       'vk_budva',
       'vk_gokak',
       'vk_zak',
       'vk_jug',
       'vk_30',
       'vk_n.',
       'vk_20',
       'vk_9',
       'vk_7'],
 'a': ['vka_vodka'],
 'b': ['vkb_nair'],
 'c': ['vkc_footwear'],
 'g': ['vkg_elektrivorgud', 'vkg_oil'],
 'h': ['vkhodnoy_island'],
 'l': ['vklse_gyor'],
 'p': ['vkp_bratislava'],
 'r': ['vkrv_rao'],
 't': ['vkt_line'],
 'v': ['vkv_dibrugarh', 'vkv_shergaon', 'vkv_golaghat', 'vkv_hurda']}
