
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_oz = {'_': ['oz_for_africa', 'oz_comic_con', 'oz_beg_khan'],
 'a': ['ozarka_vocational-technical_school',
       'ozanna,_podkarpackie_voivodeship',
       'ozarow,_masovian_voivodeship',
       'ozarks_electric_cooperative',
       'ozarow,_lublin_voivodeship',
       'ozarks_community_hospital',
       'ozaukee_county,_wisconsin',
       'ozarka_technical_college',
       'ozarow,_lodz_voivodeship',
       'ozaukee_interurban_trail',
       'ozark_festival_orchestra',
       'ozark_medieval_fortress',
       'ozark_adventist_academy',
       'ozark_christian_college',
       'ozark_henry_discography',
       'ozark_zigzag_salamander',
       'ozark_mountain_jubilee',
       'ozark_southern_english',
       'ozark_regional_transit',
       'ozark_regional_airport',
       'ozark_mountain_forests',
       'ozark_county,_missouri',
       'ozar,_nashik_district',
       'ozark_highlands_trail',
       'ozark_national_forest',
       'ozark_school_district',
       'ozanam_house,_ipswich',
       'ozark_beach,_missouri',
       'ozark_valley_railroad',
       'ozark_acres,_arkansas',
       'ozark_big-eared_bats',
       'ozar,_madhya_pradesh',
       'ozark_music_festival',
       'ozark_actors_theatre',
       'ozamiz_ferry_bombing',
       'ozark_big-eared_bat',
       'ozark_highlands_ava',
       'ozamiz_airport_road',
       'ozark_bible_college',
       'ozan_lumber_company',
       'ozaukee_high_school',
       'ozark_state_zephyr',
       'ozaukee_ice_center',
       'ozan_kofun_cluster',
       'ozark_civic_center',
       'ozark_city_schools',
       'ozara,_abia_state',
       'ozark_high_school',
       'ozark_folk_center',
       'ozan_evrim_ozenc',
       'ozark_air_lines',
       'ozana_of_kotor',
       'oza_dos_rios'],
 'b': ['ozbak,_east_azerbaijan', 'ozbak,_south_khorasan', 'ozbek_han_mosque'],
 'd': ['ozdemiroglu_osman_pasha', 'ozdi_kohasz_se'],
 'e': ['ozeriany,_borshchiv_hromada',
       'ozernoye,_astrakhan_oblast',
       'ozerki,_voronezh_oblast',
       'ozerki,_belgorod_oblast',
       'ozerne,_zhytomyr_oblast',
       'ozernoye,_amur_oblast',
       'ozeljan,_nova_gorica',
       'ozella_shields_head',
       'ozenise_me_muzikom',
       'ozell_miller_trask',
       'ozel_alman_lisesi',
       'oze_national_park',
       'ozer_turk_stadium',
       'ozel_ege_lisesi',
       'ozerne_air_base'],
 'g': ['ozgunes_railway_station',
       'ozgoleh_rural_district',
       'ozge_kirdar_cemberci',
       'ozgur_can_ozcan',
       'ozgur_b._akan'],
 'i': ['ozimek_suspension_bridge',
       'oziel_hlalele_motaung',
       'ozias_thurston_linley',
       'ozi_william_whitaker',
       'ozias_goodwin_house',
       'ozil_de_cadartz',
       'ozias_m._hatch'],
 'k': ['ozkonak_underground_city', 'ozk_arena_ruse'],
 'l': ['ozlem_yasemin_taskin', 'ozlem_ceren_dursun', 'ozlem_belcim_galip'],
 'm': ['ozmaktas-ozaltin_makina_otomotiv', 'ozma_of_oz'],
 'n': ['oznobishino,_vladimir_oblast', 'oznerol_pacheco_castro'],
 'o': ['ozolotepec_zapotec_language',
       'ozone_monitoring_instrument',
       'ozothamnus_x_expansifolius',
       'ozone_transport_commission',
       'ozone_depletion_potential',
       'ozone_depleting_substance',
       'ozone_layer_protection',
       'ozone_depletion_theory',
       'ozone_layer_depletion',
       'ozora_pierson_stearns',
       'ozora_de_dakishimete',
       'ozone_park_station',
       'ozone_hole_monster',
       'ozone_park,_queens',
       'ozona_high_school',
       'ozone_action_day',
       'ozone_disco_fire',
       'ozora_p._stearns',
       'ozone_park_boys',
       'ozo_golf_club'],
 'r': ['ozra_amander_hadley',
       'ozro_john_dodds',
       'ozra_a._hadley',
       'ozro_w._childs',
       'ozro_j._dodds'],
 'u': ['ozurgeti,_ozurgeti_municipality',
       'ozurgeti_history_museum',
       'ozurgeti_drama_theatre',
       'ozun_darreh,_fars',
       'ozuki_air_field',
       'ozuki_air_base'],
 'w': ['ozwald_boateng_obe'],
 'y': ['ozyorskoye,_leningrad_oblast',
       'ozyorsk,_chelyabinsk_oblast',
       'ozyorsk,_kaliningrad_oblast',
       'ozyornaya_railway_station',
       'ozyornoye,_bryansk_oblast',
       'ozyorny,_vladimir_oblast',
       'ozyorny,_smolensk_oblast',
       'ozyorny,_voronezh_oblast',
       'ozyorny,_bryansk_oblast',
       'ozyory,_moscow_oblast',
       'ozyorsky_urban_okrug',
       'ozyorny,_tver_oblast',
       'ozyora,_tver_oblast',
       'ozy_and_millie'],
 'z': ['ozzfest:_10th_anniversary',
       'ozzy_osbourne_discography',
       'ozzy_osbourne_band',
       'ozzie_van_brabant',
       'ozzie_and_harriet',
       'ozzie_virgil_jr.',
       'ozzie_virgil_sr.',
       'ozzie_cobb_lake',
       'ozzy_and_millie',
       'ozzy_&_drix']}
