
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_zn = {'_': ['zn2+-exporting_atpase',
       'zn-finger_protein',
       'zn-air_batteries',
       'zn_finger',
       'zn_stain',
       'zn_cl'],
 'a': ['znamenskii_district',
       'znamenskiy_district',
       'znamenskaya_square',
       'znamenski_district',
       'znamensky_district',
       'znamenskiy_island',
       'znamennoe_singing',
       'znamensky_theatre',
       'znamenskiy_raion',
       'znamenka,_russia',
       'znamenskii_raion',
       'znamensky_raion',
       'znamenka_street',
       'znamianka_raion',
       'znamenski_raion',
       'znamianka_druha',
       "znam's_problem",
       'znaur_gassiyev',
       'znamenny_chant',
       'znaur_district',
       'znamya_arzamas',
       'znaur_gassiev',
       'znachit,_pora',
       'znaps_vodka',
       'znayu_ya'],
 'c': ['znc_battery', 'znc_cell'],
 'd': ['znd_theory', 'znd_model'],
 'i': ['znicz_pruszkow', 'zniwiarz_group', 'znicz_jaroslaw', 'znin_county'],
 'k': ['znk_dinamo-maksimir',
       'znk_radomlje',
       'znk_pomurje',
       'znk_neretva',
       'znk_osijek',
       'znk_hajduk',
       'znk_rijeka',
       'znk_agram',
       'znk_ombla',
       'znk_split',
       'znk_donat',
       'znk_krka'],
 'o': ['zno_nanostructures',
       'znojmo_catacombs',
       'znojile,_kamnik',
       'znojile,_tolmin',
       'znojmo_district',
       'znojmo_rotunda',
       'znojmo_castle']}
