
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_hv = {'hv-22': 'v-22_osprey',
 'hv016': 'hv-016',
 'hvaa': 'happy_valley_aa',
 'hvacr': 'hvac',
 'hvair': 'hwair',
 'hvakhshathra': 'cyaxares',
 'hvakuk': 'habakkuk',
 'hvam': 'ddrmax_dance_dance_revolution_6thmix',
 'hvammr': 'kvam',
 'hvap': 'kinetic_energy_penetrator',
 'hvar': 'high_velocity_aircraft_rocket',
 'hvarf': 'hvarf/heim',
 'hvarf-heim': 'hvarf/heim',
 'hvcollege': 'hope_valley_college',
 'hvd-1': 'saddam_hussein',
 'hvdc': 'high-voltage_direct_current',
 'hvdl': 'high_speed_voice_and_data_link',
 'hvedrung': 'loki',
 'hvessinge': 'hvissinge',
 'hvfc': 'hanworth_villa_f.c.',
 'hvfcu': 'hudson_valley_federal_credit_union',
 'hvhf': 'high_velocity_human_factors',
 'hvhs': 'hutt_valley_high_school',
 'hvidra': 'croatian_disabled_homeland_war_veterans_association',
 'hvidstengruppen': 'hvidsten_group',
 'hvitaleder': 'hvide',
 'hvitaledr': 'hvide',
 'hvitblainn': 'flag_of_iceland',
 'hvitfeldtska': 'hvitfeldtska_gymnasiet',
 'hvitramannaland': 'great_ireland',
 'hvla': 'joint_manipulation',
 'hvod': 'hepatic_veno-occlusive_disease',
 'hvorostovsky': 'dmitri_hvorostovsky',
 'hvpe': 'hydride_vapour_phase_epitaxy',
 'hvr-a1': 'sony_hdr-hc1',
 'hvr1': 'hypervariable_region',
 'hvr2': 'hypervariable_region',
 'hvratski': 'keith_fullerton_whitman',
 'hvrhs': 'housatonic_valley_regional_high_school',
 'hvsc': 'the_high_voltage_sid_collection',
 'hvtr': 'hotham_valley_railway',
 'hvx-200': 'panasonic_ag-hvx200',
 'hvx200': 'panasonic_ag-hvx200',
 'hvxc': 'harmonic_vector_excitation_coding'}
        