
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_gt = {'_': ['gt-gyroplanes_kruza',
       'gt_chesterford',
       'gt_interactive',
       'gt_traditions',
       'gt5_prologue',
       'gt._yarmouth',
       'gt_yarmouth',
       'gt_bicycles',
       'gt_nanavati',
       'gt_library',
       'gt_legends',
       'gt_history',
       'gt4_mobile',
       'gt_cockpit',
       'gt_capital',
       'gt_cruiser',
       'gt_advance',
       'gt25_live!',
       'gt_academy',
       'gt_bradley',
       'gt_racers',
       'gt_foulis',
       'gt_racing',
       'gt_shires',
       'gt._brit',
       'gt_nexus',
       'gt_clark',
       'gt_force',
       'gt_smith',
       'gt_turbo',
       'gt_tower',
       'gt_racer',
       'gt_cube',
       'gt_labs',
       'gt_dave',
       'gt_rudd',
       'gt_road',
       'gt_tour',
       'gt_hawk',
       'gt_car',
       'gt_101',
       'gt_750',
       'gt_air',
       'gt_76',
       'gt_hd',
       'gt_64',
       'gt_5',
       'gt_4'],
 'a': ['gta:vc_soundtrack',
       'gtasa_soundtrack',
       'gtavc_soundtrack',
       'gta2_soundtrack',
       'gta3_soundtrack',
       'gta:san_andreas',
       'gta4_soundtrack',
       'gta:_chinatown',
       'gta:vice_city',
       'gta_grizzlies',
       "gta'_language",
       'gta_farecard',
       'gta_teleguam',
       'gta:_london',
       'gta_advance',
       'gta_london',
       'gta_clones',
       'gta_clone',
       'gta_mycar',
       'gta:_vcs',
       'gta_tlad',
       'gta_four',
       'gta:_lcs',
       'gta_vice',
       'gta_gang',
       'gta_iii',
       'gta:_sa',
       'gta_iiv',
       'gta:_vc',
       'gta_lcs',
       'gta:_ds',
       'gta_sas',
       'gta:_iv',
       'gta_vcs',
       'gta_sa',
       'gta_vc',
       'gta_ds',
       'gta_iv',
       'gta_1v',
       'gta_2',
       'gta_4',
       'gta_3'],
 'b': ['gtb_nagar'],
 'c': ['gtc_wireless'],
 'd': ['gtd-5_eax'],
 'e': ['gte_entertainment',
       'gtech_corporation',
       'gte_corporation',
       'gte_mainstreet',
       'gte_california',
       'gte_southwest',
       'gtel_zimbabwe',
       'gte_northwest',
       'gte_financial',
       'gte_classic',
       'gte_florida',
       'gte_midwest',
       'gte_north',
       'gte_south'],
 'f': ['gtf_airport'],
 'i': ['gtichavank_monastery',
       'gti_engineering',
       'gti_mortsel',
       'gti_polo',
       'gti_club'],
 'k': ['gtk_gnutella', 'gtk_radiant', 'gtk_gliwice', 'gtk_sharp'],
 'l': ['gtl_infrastructure', 'gtl_ltd'],
 'm': ['gtmo_attorneys',
       'gtmo_detainees',
       'gtm_languages',
       'gtmo_lawyers',
       'gtm_rossa',
       'gtm_libra',
       'gtm_coupe',
       'gtm_cars',
       'gtm_k3'],
 'o': ['gto_inverter', 'gtown_rugby', 'gto_records'],
 'p': ['gtp:gtp_guanylyltransferase',
       'gtpase-activating_proteins',
       'gtpase-activating_protein',
       'gtp_phosphohydrolases',
       'gtp-binding_proteins',
       'gtp-binding_protein',
       'gtp_diphosphokinase',
       'gtp_cyclohydrolase',
       'gtpase_superfamily',
       'gtpr_gdynia',
       'gtp_gs'],
 'r': ['gtr_euroseries', 'gtr_euroserie', 'gtr_evolution', 'gtr_2'],
 's': ['gts_constellation',
       'gts_infinity',
       'gts_duratek',
       'gts_finnjet',
       'gts_summit',
       'gts_250ie',
       'gts_300'],
 't': ['gtt_communications'],
 'v': ['gtv_9'],
 'w': ['gtw_72'],
 'x': ['gtx_incorporated']}
