#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# AUTO-GENERATED CONTENT
d_stem_kj = {'kja': {'kjas': []},
             'kjaa': {'kjaas': []},
             'kjabenhavn': {'kjabenhavns': []},
             'kjaer': {'kjaere': [], 'kjaers': []},
             'kjaerbi': {'kjaerby': []},
             'kjaerbol': {'kjaerbolling': []},
             'kjaerligh': {'kjaerlighed': []},
             'kjaerligheden': {'kjaerlighedens': []},
             'kjaern': {'kjaernes': []},
             'kjage': {'kjages': []},
             'kjalar': {'kjalarness': []},
             'kjalarn': {'kjalarnes': []},
             'kjalk': {'kjalke': []},
             'kjanderman': {'kjandermans': []},
             'kjanuari': {'kjanuary': []},
             'kjarka': {'kjarkas': []},
             'kjarligh': {'kjarlighed': []},
             'kjarligheden': {'kjarlighedens': []},
             'kjass': {'kjasse': []},
             'kjatriya': {'kjatriyas': []},
             'kjau': {'kjaus': []},
             'kjb': {'kjbs': []},
             'kjcerligh': {'kjcerlighed': []},
             'kjcerligheden': {'kjcerlighedens': []},
             'kjco': {'kjcos': []},
             'kjd': {'kjds': []},
             'kjeb': {'kjebs': []},
             'kjebenhavn': {'kjebenhavns': []},
             'kjeen': {'kjeene': []},
             'kjein': {'kjeine': []},
             'kjekhu': {'kjekhus': []},
             'kjekshu': {'kjekshus': []},
             'kjelaa': {'kjelaas': []},
             'kjelby': {'kjelbye': []},
             'kjeldaa': {'kjeldaas': []},
             'kjeldahl': {'kjeldahls': []},
             'kjeldahlgun': {'kjeldahlgunning': []},
             'kjeldahp': {'kjeldahps': []},
             'kjeldby': {'kjeldbye': []},
             'kjell': {'kjelle': [], 'kjelling': []},
             'kjelland': {'kjellander': []},
             'kjelsa': {'kjelsas': []},
             'kjelsasit': {'kjelsasite': []},
             'kjem': {'kjems': []},
             'kjemen': {'kjemens': []},
             'kjemik': {'kjemiker': []},
             'kjemisk': {'kjemiske': []},
             'kjemp': {'kjempe': []},
             'kjemper': {'kjemperer': []},
             'kjenaa': {'kjenaas': []},
             'kjend': {'kjende': []},
             'kjendt': {'kjendte': []},
             'kjenn': {'kjenne': ['kjennes']},
             'kjenne': ['kjennes'],
             'kjennetegn': {'kjennetegner': [], 'kjennetegnes': []},
             'kjensgjern': {'kjensgjerning': []},
             'kjent': {'kjente': []},
             'kjeorg': {'kjeorge': []},
             'kjerby': {'kjerbye': []},
             'kjerfv': {'kjerfve': []},
             'kjerligh': {'kjerlighed': []},
             'kjerligheden': {'kjerlighedens': []},
             'kjern': {'kjerne': []},
             'kjernist': {'kjernisted': []},
             'kjerstin': {'kjerstine': []},
             'kjertemind': {'kjerteminde': []},
             'kjerulf': {'kjerulfs': []},
             'kjerv': {'kjerve': []},
             'kjetron': {'kjetronic': []},
             'kji': {'kjy': ['kjys']},
             'kjibanski': {'kjibansky': []},
             'kjinefelt': {'kjinefelter': []},
             'kjinisch': {'kjinische': []},
             'kjiow': {'kjiowing': [], 'kjiows': []},
             'kjiowledg': {'kjiowledge': []},
             'kjk': {'kjks': []},
             'kjnd': {'kjnds': []},
             'kjndli': {'kjndly': []},
             'kjndnef': {'kjndnefs': []},
             'kjng': {'kjngs': []},
             'kjngdom': {'kjngdoms': []},
             'kjnowingli': {'kjnowingly': []},
             'kjnowledg': {'kjnowledge': []},
             'kjo': {'kjos': []},
             'kjobenhavn': {'kjobenhavns': []},
             'kjobenhavnsk': {'kjobenhavnske': []},
             'kjobmagergad': {'kjobmagergade': []},
             'kjoekkenmoed': {'kjoekkenmoeddings': []},
             'kjokkenmod': {'kjokkenmodding': ['kjokkenmoddings']},
             'kjokkenmodding': {'kjokkenmoddinger': []},
             'kjolbi': {'kjolby': []},
             'kjolby': {'kjolbye': []},
             'kjolhed': {'kjolhede': []},
             'kjollesd': {'kjollesdal': []},
             'kjonaa': {'kjonaas': []},
             'kjoo': {'kjoos': []},
             'kjopt': {'kjopte': []},
             'kjorel': {'kjorell': []},
             'kjort': {'kjorte': []},
             'kjos': {'kjosness': []},
             'kjot': {'kjots': []},
             'kjoul': {'kjoule': ['kjoules']},
             'kjoule': ['kjoules'],
             'kjrbi': {'kjrby': []},
             'kju': {'kjus': []},
             'kjuli': {'kjuly': []},
             'kjuot': {'kjuoted': []},
             'kjuu': {'kjuus': []},
             'kjv': {'kjvs': []},
             'kjy': ['kjys']}
