
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_zm = {'_': ['zm-241,385', 'zm-182345', 'zm447439', 'zm-87'],
 'a': ['zmajevic',
       'zmajevac',
       'zmachine',
       'zmaratha',
       'zmailer',
       'zmajevo',
       'zmarle',
       'zmaray',
       'zmajan',
       'zmanda',
       'zmanim',
       'zmacs',
       'zmapp',
       'zmap',
       'zman',
       'zmag',
       'zmax',
       'zmaj',
       'zma'],
 'b': ['zmbss', 'zmb'],
 'd': ['zmda', 'zmdi', 'zmd'],
 'e': ['zmeinogorsk',
       'zmeytsyno',
       'zmerynka',
       'zmelkoow',
       'zmeoaica',
       'zmeurata',
       'zmeyevka',
       'zmeitsa',
       'zmeskal',
       'zmeevo',
       'zmey',
       'zmei',
       'zmeu'],
 'f': ['zmf'],
 'i': ['zmijewo-podusie',
       'zmijewo-trojany',
       'zmijewo-zagroby',
       'zmijewo-szawly',
       'zmijewo-ponki',
       'zmijowek-mans',
       'zmijewo-kuce',
       'zmijewo-gaje',
       'zmiennica',
       'zmiennicy',
       'zmigrodek',
       'zmijewko',
       'zmiyovka',
       'zmiyivka',
       'zmijavci',
       'zmiarki',
       'zmitser',
       'zmiovka',
       'zmijani',
       'zmigrod',
       'zmiivka',
       'zminjak',
       'zmijkow',
       'zminec',
       'zminne',
       'zmirot',
       'zminac',
       'zmiaca',
       'zmiros',
       'zmiiv',
       'zmila',
       'zmist',
       'zmiz1',
       'zminj',
       'zmiz2',
       'zmiy',
       'zmi'],
 'k': ['zmk'],
 'm': ['zmms', 'zmm'],
 'o': ['zmodeler', 'zmojdak', 'zmodem', 'zmobie'],
 'p': ['zmpste24', 'zmp'],
 's': ['zms-05', 'zms'],
 't': ['zmt'],
 'u': ['zmuttgletscher',
       'zmudz-kolonia',
       'zmudzinski',
       'zmuttal',
       'zmuda',
       'zmudz',
       'zmutt',
       'zmub',
       'zmud',
       'zmug'],
 'w': ['zmw'],
 'y': ['zmyslanka',
       'zmyslowo',
       'zmynd11',
       'zmynd10',
       'zmynd8',
       'zmym2',
       'zmym3']}
