
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_mx = {'_': ['mx_designations',
       'mx-1_kalakian',
       'mx_revolution',
       'mx981_project',
       'mx_unleashed',
       'mx_revoltion',
       'mx-7_gagamba',
       'mx-8_barako',
       'mx_superfly',
       'mx_missiles',
       'mx_missile',
       'mx_machine',
       'mx_records',
       'mx_player',
       'mx_puppis',
       'mx_energy',
       'mx_record',
       'mx_rider',
       'mx_entry',
       'mx_linux',
       'mx1_ltd',
       'mx_air',
       'mx_igp',
       'mx_518'],
 'i': ['mxim_framework', 'mxit_lifestyle'],
 'm': ['mxm_pci'],
 'o': ['mxolisi_siyonzana',
       'mxolisi_mthethwa',
       'mxolisa_sokatsha',
       'mxolisi_lukhele',
       'mxolisi_nxasana',
       'mxolisi_kaunda',
       'mxolisi_mgojo'],
 'p': ['mxpx_discography'],
 'r': ['mxr_yorkshire']}
