
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_mk = {'_': ['mk_engineering',
       'mk.44_torpedo',
       'mk2_detonator',
       'mk-46_torpedo',
       'mk-48_torpedo',
       'mk_sportscars',
       'mk_armageddon',
       'mk_publishers',
       'mk_lightning',
       'mk46_torpedo',
       'mk48_torpedo',
       'mk_nobilette',
       'mk_wimbledon',
       'mk_electric',
       'mk_azhagiri',
       'mk3_grenade',
       'mk_airlines',
       'mk2_grenade',
       'mk_thunder',
       'mk_mubanga',
       'mk_capital',
       'mk_theatre',
       'mk_trilogy',
       'mk_pandhe',
       'mk_perker',
       'mk_stalin',
       'mk_hobson',
       'mk_joseph',
       'mk_balaji',
       'mk_gandhi',
       'mk_olsen',
       'mk_brown',
       'mk_sanoo',
       'mk_brass',
       'mk_ultra',
       'mk_lions',
       'mk5_polo',
       'mk1_mini',
       'mk_menon',
       'mk_group',
       'mk_media',
       'mk_raina',
       'mk_xviii',
       'mk_metro',
       'mk3_golf',
       'mk_dons',
       'mk-v_ar',
       'mk_f.c.',
       'mk_indy',
       'mk_xvii',
       'mk_wren',
       'mk_guth',
       'mk_801',
       'mk_886',
       'mk._17',
       'mk._ii',
       'mk_one',
       'mk_103',
       'mk_pop',
       'mk._19',
       'mk._16',
       'mk._11',
       'mk_xix',
       'mk_wii',
       'mk_101',
       'mk._28',
       'mk_108',
       'mk_18',
       'mk_20',
       'mk_11',
       'mk_43',
       'mk_48',
       'mk_82',
       'mk_ds',
       'mk._2',
       'mk_83',
       'mk_22',
       'mk_32',
       'mk_19',
       'mk_16',
       'mk_41',
       'mk_50',
       'mk_84',
       'mk_47',
       'mk_17',
       'mk_46',
       'mk_44',
       'mk_77',
       'mk_5',
       'mk_1',
       'mk_v',
       'mk_i',
       'mk_2',
       'mk_a'],
 'a': ['mkalama_district',
       'mkamzee_mwatela',
       'mkabayi_kajama',
       'mkapa_bridge',
       'mkama_ndume'],
 'b': ['mkb_raduga', 'mkb_fakel', 'mkb_bank'],
 'c': ['mkc_networks'],
 'e': ['mke_kirikkalespor',
       'mke_ankaragucu',
       'mke_jng-90',
       'mke_tamgec',
       'mke_mpt',
       'mkek_7',
       'mkek_6',
       'mkek_4',
       'mkek_2',
       'mkek_5',
       'mkek_1'],
 'g': ['mkg_group'],
 'h': ['mkhitar_mnatsakanyan',
       'mkhitar_hayrapetyan',
       'mkhanyiseli_siwahla',
       'mkhitar_sebastatsi',
       'mkhitar_djrbashian',
       'mkhitar_sparapet',
       'mkhuphali_masuku',
       'mkhuleko_hlengwa',
       'mkhitar_manukyan',
       'mkhululi_bhebhe',
       'mkhululi_nyathi',
       'mkhululi_calana',
       'mkhitar_heratsi',
       'mkhokheli_dube',
       'mkhuseli_jack',
       'mkhitar_gosh'],
 'i': ['mkinga_district'],
 'k': ['mkkhitar_manukyan'],
 'm': ['mkm_aboobakar', 'mkm_stadium', 'mkmf_awards', 'mkm_steel'],
 'o': ['mkomazi,_tanzania', 'mkokheli_dube', 'mko_abiola'],
 'r': ['mkrtich_beshiktashlian',
       'mkrtich_hovhannisyan',
       'mkrtich_portukalian',
       'mkrtich_gardashian',
       'mkrtich_arzumanyan',
       'mkrtich_avetisian',
       'mkrtich_mazmanian',
       'mkrtich_khrimian',
       'mkrtich_achemian',
       'mkrtich_naghash',
       'mkrtich_armen',
       'mkristo_bruce'],
 's': ['mks_trzebinia-siersza',
       'mks_instruments',
       'mks_przasnysz',
       'mks_kluczbork',
       'mks_x/server',
       'mks_toolkit',
       'mks_kalisz',
       'mks_lublin',
       'mks_supply',
       'mks_system',
       'mks_bedzin',
       'mks_units',
       'mks_unit',
       'mks_inc.',
       'mks_inc',
       'mks_vir'],
 't': ['mkt-araz_imishli',
       'mkt-araz_imisli',
       'mktbt_mine',
       'mkt_trail',
       'mkt_araz',
       'mkt_cap'],
 'u': ['mkuranga_district',
       'mkulumuzi_river',
       'mkunde_chachage',
       'mkushi_district',
       'mkushi_north',
       'mkushi_south',
       'mkuzu_river'],
 'v': ['mkv_bappu'],
 'w': ['mkwakwani_stadium']}
