
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rf = {'_': ['rf_resistance_architecture',
       'rf_distribution_amplifier',
       'rf-80a_shooting_star',
       'rf_joyce_observatory',
       'rf_coaxial_connector',
       'rf_monitor_software',
       'rf_power_amplifier',
       'rf-100_super_sabre',
       'rf_remote_control',
       'rf-4g_phantom_ii',
       'rf-4c_phantom_ii',
       'rf_micro_devices',
       'rf_switch_matrix',
       'rf_power_margin',
       'rf_radio_nippon',
       'rf_front_end'],
 'a': ['rfa_bedenham_explosion',
       'rfamide_peptide_family',
       'rfa_lady_cory-wright',
       'rfa_surf_pioneer',
       'rfa_fort_rosalie',
       'rfa_ocean_salvor',
       'rfa_tide_austral',
       'rfa_wave_knight',
       'rfa_sir_galahad',
       'rfa_surf_patrol',
       'rfa_gray_ranger',
       'rfa_wave_chief',
       'rfa_wave_ruler',
       'rfa_wave_laird'],
 'b': ['rfb/grumman_american_fanliner'],
 'c': ['rfc_bad_reichenhall', 'rfc_liegeois_rugby', 'rfc_arsenal_tivat'],
 'e': ['rfe_phonetic_alphabet'],
 'i': ['rfid_information_center',
       'rfid_tracking_module',
       'rfid_race_timing',
       'rfid_on_metal'],
 'k': ['rfk_memorial_stadium', 'rfk_must_die', 'rfk_novi_sad'],
 'l': ['rfl_reserve_championship',
       'rfl_community_shield',
       'rfl_match_officials',
       "rfl_president's_cup",
       'rfl_yorkshire_cup',
       'rfl_league_1',
       'rfl_1895_cup'],
 'q': ['rfq_beam_cooler'],
 's': ['rfs_vladimir_monomakh',
       'rfs_yuriy_dolgorukiy',
       'rfs_alexander_nevsky',
       'rfs_marshal_ustinov',
       'rfs_yury_dolgorukiy',
       'rfs_yury_dolgoruky',
       'rfs_pyotr_velikiy',
       'rfs_kursk_k-141'],
 't': ['rft_riverfront_times'],
 'u': ['rfu_championship_cup',
       'rfu_intermediate_cup',
       'rfu_championship_xv',
       'rfu_senior_vase',
       'rfu_junior_vase']}
