
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rn = {'_': ['rn_school_tal-handaq',
       'rn_shetty_stadium',
       'rn_giulio_cesare',
       'rn_staff_college',
       'rn_pudur,_erode',
       'rn_irwin_stakes',
       'rn_angell_lane'],
 'a': ['rna-induced_transcriptional_silencing',
       'rna-induced_silencing_complex',
       'rna-dependent_rna_polymerases',
       'rna-directed_dna_methylation',
       'rna-binding_protein_database',
       'rna-dependent_rna_polymerase',
       'rna-dependent_dna_polymerase',
       'rna_immunoprecipitation_chip',
       'rna-directed_rna_polymerase',
       'rna-directed_dna_polymerase',
       'rna_interference_machinery',
       'rna_copy-number_variation',
       'rna_modification_database',
       'rna_cap-binding_proteins',
       'rna_structure_prediction',
       'rna-binding_protein_ews',
       'rna-binding_protein_fus',
       'rnai_global_initiative',
       'rnase_protection_assay',
       'rna_adenylating_enzyme',
       'rna_helicase_database',
       'rnase_h-dependent_pcr',
       'rna_recognition_motif',
       'rna_integrity_number',
       'rna_world_hypothesis',
       'rna_virus_infections',
       'rnas_hickling_broad',
       'rnad_broughton_moor',
       'rna,_18s_ribosomal',
       'rnas_middle_wallop',
       'rna_polymerase_iii',
       'rnad_ditton_priors',
       'rnas_hornsea_mere',
       'rna_polymerase_iv',
       'rna_polymerase_ii',
       'rnas_prawle_point',
       'rnas_worthy_down',
       'rna_polymerase_i',
       'rna_splice_sites',
       'rna_polymerase_v',
       'rna_copy_number',
       'rnase_ph_domain',
       'rnase_r_domain',
       'rna_helicase_a',
       'rnas_st_angelo',
       'rnase_d_domain',
       'rna_tie_club',
       'rna_pol_iii',
       'rna_pol_ii',
       'rna_pol_i'],
 'b': ['rnb_global_university', 'rnb_fridays_live'],
 'e': ['rne-ii_rna_motif'],
 'f': ['rnf_motogp_racing'],
 'i': ['rnib_college,_loughborough', 'rnib_connect_radio', 'rnib_new_college'],
 'l': ['rnlb_queen_victoria', 'rnlb_mary_stanford'],
 'm': ['rnmd_milford_haven'],
 'o': ['rnov_shabab_oman'],
 'z': ['rnzaf_station_waipapakauri',
       'rnzaf_station_weraroa',
       'rnzaf_museum_aircraft',
       'rnzaf_base_woodbourne',
       'rnzaf_security_forces',
       'rnzaf_base_whenuapai',
       'rnzaf_base_auckland',
       'rnzaf_base_ohakea',
       'rnzaf_dip_flat']}
