
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rs = {'_': ['rs:x_european_championships',
       'rs_canum_venaticorum',
       'rs_ginnastica_torino',
       'rs_basingstoke_f.c.',
       'rs_coronae_borealis',
       'rs_basingstoke_fc',
       'rs_music_records',
       'rs_album_guide',
       'rs_of_serbia'],
 'a': ['rsa_secret-key_challenge',
       'rsa_factoring_challenge',
       'rsa_trustmark_building',
       'rsa_judicial_building',
       'rsa_battlehouse_tower',
       'rsa_insurance_group',
       'rsaf_black_knights',
       'rsa_data_security',
       'rsa_blocker_tags',
       'rsa_blocker_tag'],
 'c': ['rsc_sessions_perdues'],
 'd': ['rsd_sloboda_tuzla', 'rsd_santa_isabel', 'rsd_alcala_b'],
 'f': ['rsf_social_finance'],
 'h': ['rsh_remote_shell'],
 'i': ['rsi_rete_uno', 'rsi_rete_due', 'rsi_rete_tre', 'rsi_la_2', 'rsi_la_1'],
 'm': ['rsm_robson_rhodes', 'rsmy_rna_family', 'rsmc_new_delhi'],
 'o': ['rso_records_discography'],
 'p': ['rspb_buckenham_marshes',
       'rspb_pulborough_brooks',
       'rspb_blacktoft_sands',
       'rspb_brading_marshes',
       'rspb_titchwell_marsh',
       'rspb_middleton_lakes',
       'rspb_sandwell_valley',
       'rspb_middleton_lake',
       'rspb_coombes_valley',
       'rspb_berney_marshes',
       'rspca_animal_rescue',
       'rspb_bempton_cliffs',
       'rspb_lakenheath_fen',
       'rspb_frampton_marsh',
       'rspb_strumpshaw_fen',
       'rspca_reform_group',
       'rspb_stour_estuary',
       'rspb_radipole_lake',
       'rspb_fairburn_ings',
       'rspb_leighton_moss',
       'rspb_ouse_washes',
       'rspb_south_stack',
       'rspb_the_lodge',
       'rspb_rye_meads',
       'rspb_old_moor'],
 's': ['rss-dev_working_group',
       'rss_feeds_directory',
       'rss_advisory_board',
       'rssc_united_f.c.',
       'rss_feed_reader',
       'rss_web_feed'],
 'u': ['rsud_lrt_station'],
 'v': ['rsv_media_center'],
 'x': ['rsx_reality_synthesizer', 'rsx_energy_inc.', 'rsx_energy_inc']}
