
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_mv = {'mv-22': 'v-22_osprey',
 'mv-22b': 'v-22_osprey',
 'mv-5': 'm-v',
 'mv/8000': 'data_general_eclipse_mv/8000',
 'mvac': 'anti-communist_volunteer_militia',
 'mvae': 'beti-pahuin',
 'mvar': 'ac_power',
 'mvba': 'mindanao_visayas_basketball_association',
 'mvc-cd500': 'sony_mavica',
 'mvc2': 'marvel_vs._capcom_2:_new_age_of_heroes',
 'mvcds': 'maumee_valley_country_day_school',
 'mvci': 'marriott_vacation_club_international',
 'mvcl': 'vinculin',
 'mvcv': 'malva_vein_clearing_virus',
 'mvda': 'ontario_motor_vehicle_industry_council',
 'mvder': 'mvedr',
 'mvele': 'beti-pahuin',
 'mvemjsun': 'planetary_mnemonic',
 'mvemjsunp': 'planetary_mnemonic',
 'mvemjsupn': 'planetary_mnemonic',
 'mvgr': 'mvgr_college_of_engineering',
 'mvgrce': 'mvgr_college_of_engineering',
 'mviaa': 'big_eight_conference',
 'mvip': 'multi-vendor_integration_protocol',
 'mviri': 'meteosat_visible_and_infrared_imager',
 'mvit': 'sir_m._visvesvaraya_institute_of_technology',
 'mvita': 'mombasa',
 'mvjce': 'visvesvaraya_technological_university',
 'mvjhl': 'maritime_junior_a_hockey_league',
 'mvla': 'mountain_view-los_altos_union_high_school_district',
 'mvll': 'mario_vargas_llosa',
 'mvlpo': 'landing_page_optimization',
 'mvme': 'motorola_single_board_computers',
 'mvme68k': 'motorola_single_board_computers',
 'mvnc': 'mount_vernon_nazarene_university',
 'mvne': 'mobile_virtual_network_enabler',
 'mvno': 'mobile_virtual_network_operator',
 'mvnu': 'mount_vernon_nazarene_university',
 'mvog-nyenge': 'beti-pahuin',
 'mvoung': 'mvoung_department',
 'mvpa': 'music_video_production_association',
 'mvpd': 'multichannel_video_programming_distributor',
 'mvpn': 'mobile_virtual_private_network',
 'mvq-6': 'stq',
 'mvq6': 'stq',
 'mvrc': 'moonee_valley_racing_club',
 'mvsc': 'master_of_veterinary_science',
 'mvsc2': 'marvel_vs._capcom_2:_new_age_of_heroes',
 'mvsevm': 'museum',
 'mvsn': 'blackshirts',
 'mvsr': 'maturi_venkata_subba_rao_engineering_college',
 'mvsrec': 'maturi_venkata_subba_rao_engineering_college',
 'mvta': 'minnesota_valley_transit_authority',
 'mvtr': 'moisture_vapor_transmission_rate',
 'mvtu': 'bauman_moscow_state_technical_university',
 'mvue': 'minimum-variance_unbiased_estimator',
 'mvumbi': 'albert_lutuli',
 'mvvm': 'model_view_viewmodel'}
        