
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_tp = {'_': ['tp-3:_reloaded',
       'tp_properties',
       'tp.3_reloaded',
       'tp_sudhindra',
       'tp_rajeevan',
       'tp_kailasam',
       'tp_mazembe',
       'tp_ligands',
       'tp_molunge',
       'tp_formula',
       'tp_mckenna',
       'tp_mystere',
       'tp_library',
       'tp53_gene',
       'tp_figgis',
       'tp_vision',
       'tp_ligand',
       'tp_cable',
       'tp_icap',
       'tp_gill',
       'tp_52'],
 'a': ['tpa_deficiency', 'tpao_batman'],
 'b': ['tpb_episodes', 'tpb_trial', 'tpb_afk', 'tpb_tv'],
 'c': ['tpc_prestancia',
       'tpc_scottsdale',
       'tpc_stonebrae',
       'tpc_southwind',
       'tpc_sugarloaf',
       'tpc_louisiana',
       'tpc_sawgrass',
       'tpc_michigan',
       'tpc_potomac',
       'tpc_boston',
       'tpc_avenel',
       'tpc_group'],
 'g': ['tpg_internet',
       'tpg_telecom',
       'tpg_capital',
       'tpg_n.v.',
       'tpg_post',
       'tpg_inc.',
       'tpg_tour',
       'tpg_nv'],
 'h': ['tph_partners', 'tph_club'],
 'i': ['tpi_specialties', 'tpi_polene', 'tpi_theory'],
 'k': ['tpk_algorithm'],
 'l': ['tpl_tables'],
 'm': ['tpm_muckraker', 'tpm_domain', 'tpm_media', 'tpm_cafe', 'tpm_chip'],
 'o': ['tpok_jazz'],
 'p': ['tpp_riboswitch', 'tppts_ligand', 'tpp_kostolac'],
 'q': ['tpq-36_radar', 'tpq-37_radar', 'tpq_36', 'tpq_37'],
 'r': ['tpr_storytelling'],
 's': ['tps-59_radar',
       'tps_pakistan',
       'tps-75_radar',
       'tps_reports',
       'tps_naiset',
       'tps_report',
       'tps_cable',
       'tps_group',
       'tps_turku',
       'tps_foot',
       'tps_star',
       'tps_77',
       'tps_59',
       'tps_43',
       'tps_75'],
 'v': ['tpv_technology', 'tpv_tampere'],
 'x': ['tpx_communications'],
 'z': ['tpz_fuchs']}
