
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_tb = {'_': ['tb/fc_suduroy/royn',
       'tb10cs3h1_snorna',
       'tb11cs4h2_snorna',
       'tb11cs4h1_snorna',
       'tb11cs5h2_snorna',
       'tb10cs3h2_snorna',
       'tb10cs4h2_snorna',
       'tb10cs4h4_snorna',
       'tb11cs4h3_snorna',
       'tb10cs1h3_snorna',
       'tb10cs4h3_snorna',
       'tb10cs4h1_snorna',
       'tb10cs1h2_snorna',
       'tb11cs5h3_snorna',
       'tb11cs3h2_snorna',
       'tb11cs2h1_snorna',
       'tb11cs5h1_snorna',
       'tb10cs1h1_snorna',
       'tb10cs2h1_snorna',
       'tb10cs2h2_snorna',
       'tb10cs5h3_snorna',
       'tb11cs3h1_snorna',
       'tb10cs5h1_snorna',
       'tb10cs5h2_snorna',
       'tb8cs3h1_snorna',
       'tb9cs3h1_snorna',
       'tb9cs4h3_snorna',
       'tb8cs4h1_snorna',
       'tb9cs2h1_snorna',
       'tb9cs6h1_snorna',
       'tb9cs1h2_snorna',
       'tb9cs3h2_snorna',
       'tb6cs1h2_snorna',
       'tb9cs2h2_snorna',
       'tb6cs1h4_snorna',
       'tb9cs1h3_snorna',
       'tb6cs2h1_snorna',
       'tb_wanne-eickel',
       'tb9cs4h2_snorna',
       'tb9cs1h1_snorna',
       'tb8cs2h1_snorna',
       'tb8cs4h2_snorna',
       'tb3cs2h2_snorna',
       'tb6cs1h1_snorna',
       'tb9cs4h1_snorna',
       'tb6cs1h3_snorna',
       'tb3cs2h1_snorna',
       'tb9cs6h2_snorna',
       'tb2d_skypirate',
       'tb_ilangaratne',
       'tb_buccaneers',
       'tb3f_guardian',
       'tb_treatment',
       'tb,_maryland',
       'tb_diagnosis',
       'tb_lightning',
       'tb_alliance',
       'tb_walker',
       'tb_joshua',
       'tb_d-rays',
       'tb_sheets',
       'tb_irving',
       'tb_potter',
       'tb_alert',
       'tb_jayah',
       'tb_rays',
       'tb_ulm',
       'tb_191'],
 'a': ['tbaytel_mobility', 'tbaeng_meanchey', 'tba_studios'],
 'b': ['tbbt_characters', 'tbbt_episodes', 'tbb_pank'],
 'c': ['tbc_corporation', 'tbc_domain', 'tbc_radio', 'tbc_bank'],
 'd': ['tbd_devastator', 'tbd_records'],
 'e': ['tbeli_abuserisdze', 'tbeng_meanchey', 'tbe_buffer'],
 'f': ['tbf_avenger'],
 'g': ['tbg_dragons', 'tbg_labor', 'tbg_ag'],
 'i': ['tbilisi_caucasians',
       'tbilissky_district',
       'tbilisi_sakrebulo',
       'tbi_complications',
       'tbilisi_institute',
       'tbilisi_assembly',
       'tbilisis_forumi',
       'tbilisi_airport',
       'tbilisi_circus',
       'tbi_solicitors',
       'tbilisi_subway',
       'tbilisi_avenue',
       'tbilisi_mayor',
       'tbilisi_metro',
       'tbilisi_sea',
       'tbilisi_zoo',
       'tbi_bank',
       'tbi_plc'],
 'l': ['tblghu,_nagorno-karabakh'],
 'm': ['tbm_avenger', 'tbm_700', 'tbmm_tv', 'tbm_850'],
 'n': ['tbn_inspire', 'tbn_enlace', 'tbn_salsa'],
 'o': ['tboli_language',
       'tbone_burnett',
       'tboung_khmom',
       'tboung_khmum',
       'tboli_people',
       'tbong_khmom',
       'tbong_khmum',
       'tbong_kmom',
       'tbong_kmum'],
 'p': ['tbp-associated_factors', 'tbp-associated_factor'],
 's': ['tbs_education', 'tbs_monkeys', 'tbs_sports', 'tbs_radio', 'tbs_gb'],
 'u': ['tbuong_kmoum'],
 'v': ['tbvfl_neustadt-wildenheid', 'tbv_wildenheid', 'tbv_lemgo'],
 'w': ['tbwa_worldwide', 'tbw_ramsay', 'tbw_list'],
 'x': ['tbx18_transduction'],
 'y': ['tby_seawolf']}
