import libcst
from typing import Any

class Visitor(libcst.CSTVisitor): ...

class Transformer(libcst.CSTTransformer):
    ImportALIAS: Any = ...
    def __init__(self, visitor: Any) -> None: ...
    def leave_ImportFrom(self, original_node: Any, updated_node: Any): ...
    def leave_ImportAlias_asname(self, node: Any) -> None: ...
    def leave_ClassDef(self, original_node: Any, updated_node: Any): ...

def create_simple_statement_line(statement: Any, class_name: str) -> Any: ...
