
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_yr = {'_': ['yr_australydd',
       'yr_ymofynnydd',
       'yr_atgyfodi',
       'yr_arloeswr',
       'yr_amserau',
       'yr_anhrefn',
       'yr_wladfa',
       'yr_wyddor',
       'yr_wyddfa',
       'yr_arwydd',
       'yr_studio',
       'yr_ystog',
       'yr_estyn',
       'yr_rune',
       'yr_elen',
       'yr_eifl',
       'yr_aran',
       'yr_god'],
 'a': ['yrausquin_airport', 'yrauskin_airport', 'yramea_cytheris'],
 'b': ['yrb_magazine'],
 'c': ['yrc_logistics', 'yrc_worldwide'],
 'e': ['yreka,_california',
       'yreina_cervantez',
       'yreka_railroad',
       'yretha_silete',
       'yreka_phlox',
       'yren_rotela'],
 'f': ['yrf_distribution', 'yrf_television'],
 'g': ['yrgyz_district', 'yrg_care'],
 'i': ['yrick_gallantes', 'yrius_carboni'],
 'j': ['yrjo_korholin-koski',
       'yrjo_saastamoinen',
       'yrjo_jaaskelainen',
       'yrjo_kilpelainen',
       'yrjoe_elfvengren',
       'yrjo_vesterinen',
       'yrjo_elfvengren',
       'yrjo_lindegren',
       'yrjo_kukkapuro',
       'yrjo_sinkkonen',
       'yrjo_miettinen',
       'yrjo_blomstedt',
       'yrjo_salpakari',
       'yrjo_pulkkinen',
       'yrjo_kallinen',
       'yrjo_helander',
       'yrjo_hietanen',
       'yrjo_jahnsson',
       'yrjo_raisanen',
       'yrjo_vaananen',
       'yrjo_rantanen',
       'yrjo_tuominen',
       'yrjo_kilpinen',
       'yrjo_saarinen',
       'yrjo_nikkanen',
       'yrjo_kivenoja',
       'yrjo_parnanen',
       'yrjo_keinonen',
       'yrjo_hakoila',
       'yrjo_sotiola',
       'yrjo_uimonen',
       'yrjo_karilas',
       'yrjoe_wallin',
       'yrjo_welling',
       'yrjo_lehtila',
       'yrjo_sotamaa',
       'yrjo_kylmala',
       'yrjo_pesonen',
       'yrjo_makelin',
       'yrjo_lampila',
       'yrjo_vaisala',
       'yrjo_ekqvist',
       'yrjo_reenpaa',
       'yrjo_hautala',
       'yrjo_halonen',
       'yrjo_jussila',
       'yrjo_saarela',
       'yrjo_valkama',
       'yrjo_wallin',
       'yrjo_vuolio',
       'yrjo_hakala',
       'yrjo_nurmio',
       'yrjo_ollila',
       'yrjo_makela',
       'yrjo_vartia',
       'yrjo_sirola',
       'yrjo_ruutu',
       'yrjo_linko',
       'yrjo_soini',
       'yrjo_leiwo',
       'yrjo_kolho',
       'yrjo_kesti',
       'yrjo_kiuru',
       'yrjo_murto',
       'yrjo_kokko',
       'yrjo_leino',
       'yrjo_norta',
       'yrjo_neuvo',
       'yrjo_vesa'],
 'k': ['yrkv_mechelen'],
 'o': ['yrondu_musavu-king'],
 's': ['yrsa_sigurdardottir', 'yrsa_daley-ward', 'yrsa_stenius'],
 'v': ['yrvind_island']}
