
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_td = {'_': ['td-learning',
       'td-gammon',
       'td-scdma',
       'td-cdma',
       'td2000',
       'td-dft',
       'td2192',
       'td/smp',
       'td-1a',
       'td-3',
       'td06',
       'td8e',
       'td15',
       'td-1',
       'td-2',
       'td1'],
 'a': ['tdagarim', 'tdaction', 'tdac', 'tdap', 'tda'],
 'b': ['tdbzcholine', 'tdbfg', 'tdb'],
 'c': ['tdcanadatrust.com',
       'tdcaa',
       'tdch',
       'tdcs',
       'tdcp',
       'tdci',
       'tdcj',
       'tdc'],
 'd': ['tdd/tty', 'tddft', 'tddb', 'tdd'],
 'e': ['tdep', 'tdea', 'tdes', 'tdel', 'tde'],
 'f': ['tdfcu', 'tdfa', 'tdf'],
 'g': ['tdgf1', 'tdg'],
 'h': ['tdhca', 'tdhs', 'tdh'],
 'i': ['tdindustries', 'tdisland', 'tdiq', 'tdim', 'tdif', 'tdi'],
 'k': ['tdk-micronas', 'tdkp-sb', 'tdksa', 'tdkp', 'tdkr', 'tdk'],
 'l': ['tdlas', 'tdls', 'tdlo', 'tdl'],
 'm': ['tdm-gcc', 'tdmoip', 'tdme', 'tdma', 'tdms', 'tdmi', 'tdm'],
 'n': ['tdnim', 'tdna', 'tdnn', 'tdn'],
 'o': ['tdondarup', 'tdor', 'tdoa', 'tdot', 'tdo'],
 'p': ['tdp-4-oxo-6-deoxy-alpha-d-glucose-3,4-oxoisomerase',
       'tdp-43',
       'tdppme',
       'tdpod',
       'tdp43',
       'tdpf',
       'tdp1',
       'tdp'],
 'r': ['tdrsmusic',
       'tdrs-12',
       'tdr2000',
       'tdrs-10',
       'tdrs-13',
       'tdrs-11',
       'tdrs-b',
       'tdrs-1',
       'tdrs-4',
       'tdrs-5',
       'tdrama',
       'tdrs-7',
       'tdrs-6',
       'tdrs-9',
       'tdrs-3',
       'tdrs-8',
       'tdrd7',
       'tdrkh',
       'tdrd3',
       'tdrss',
       'tdri',
       'tdrs',
       'tdra',
       'tdr'],
 's': ['tdscdma', 'tdsotm', 'tdsoft', 'tdshs', 'tdsb', 'tdss', 'tds'],
 't': ['tdtess', 'tdtnc', 'tdts', 'tdtv', 'tdt'],
 'u': ['tdu'],
 'v': ['tdvision', 'tdv-2200', 'tdv'],
 'w': ['tdwaterhouse', 'tdwdtg', 'tdwtf', 'tdwhs', 'tdwg', 'tdwr', 'tdw'],
 'x': ['tdx'],
 'y': ['tdy']}
