
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_pz = {'_': ['pz_cussons_ghana',
       'pz_cussons_plc',
       'pz._sfl._ivc.',
       'pz_mg_51/71',
       'pz._sfl._1a',
       'pz_kpfw_iii',
       'pz_kpfw_iv'],
 'h': ['pzh_2000_howitzer'],
 'i': ['pzinz_403_lux-sport'],
 'k': ['pzkpfw_ix/pzkpfw_x', 'pzkpfw_ii_flamm'],
 'l': ['pzl-okecie_pzl-110_koliber',
       'pzl-swidnik_m-18_dromader',
       'pzl-mielec_m-18_dromader',
       'pzl_bielsko_szd-21',
       'pzl_bielsko_szd-26',
       'pzl.53_jastrzab_ii',
       'pzl_bielsko_szd-48',
       'pzl_bielsko_szd-6x',
       'pzl_m-15_belphegor',
       'pzl_bielsko_szd-41',
       'pzl_bielsko_szd-45',
       'pzl_bielsko_szd-56',
       'pzl_bielsko_szd-55',
       'pzl_bielsko_szd-52',
       'pzl_bielsko_szd-50',
       'pzl_bielsko_szd-30',
       'pzl_m-18_dromader',
       'pzl_m-26_iskierka',
       'pzl_sw-4_puszczyk',
       'pzl_bielsko_szd-6',
       'pzl_m-28_skytruck',
       'pzl_bielsko_szd-9',
       'pzl_pzl-104_wilga',
       'pzl_mielec_ts-11',
       'pzl_szd-30_pirat',
       'pzl_m26_iskierka',
       'pzl_rzeszow_so-3',
       'pzl_m28_skytruck',
       'pzl_ts-11_iskra',
       'pzl_m-28b_bryza',
       'pzl_mielec_m-15',
       'pzl_m-3_pliszka',
       'pzl_ts-16_grot',
       'pzl_m-4_tarpan',
       'pzl_sm-4_latka',
       'pzl_w-3a_sokol',
       'pzl_m28b_bryza',
       'pzl_i-22_iryda',
       'pzl_p.38_wilk',
       'pzl_m-20_mewa',
       'pzl_44_wicher',
       'pzl_ts-8_bies',
       'pzl_w-3_huzar',
       'pzl_104_wilga',
       'pzl_w-3_sokol',
       'pzl_ws_foka'],
 'u': ['pzu_polfa_pabianice', 'pzu_azs_olsztyn']}
