
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_yt = {'_': ['yt-1300', 'yt-2000', 'yt-2400', 'yt//st'],
 'a': ['ytalo', 'ytay', 'yta'],
 'b': ['ytbi', 'ytb'],
 'c': ['ytcracker', 'ytc'],
 'd': ['ytd'],
 'e': ['yte'],
 'f': ['ytfc', 'ytf'],
 'g': ['ytgm'],
 'h': ['ythanwells',
       'ythanbank',
       'ythogtha',
       'ythsie',
       'ythdf1',
       'ythdf3',
       'ythdc2',
       'ythdc1',
       'ythdf2',
       'ythan',
       'ytht',
       'yth'],
 'i': ['yti_career_institute'],
 'j': ['ytj'],
 'l': ['ytlm', 'ytl'],
 'm': ['ytmnd.com', 'ytmnsfw', 'ytmnds', 'ytmnd', 'ytm'],
 'n': ['ytnmd', 'ytn'],
 'o': ['ytong', 'yto'],
 'p': ['ytp'],
 'q': ['ytq'],
 'r': ['ytri-ranga',
       'ytraberget',
       'ytrebygda',
       'ytr-2320',
       'ytringen',
       'ytr-232',
       'ytrac',
       'ytres',
       'ytre',
       'ytr'],
 's': ['ytsejam', 'ytse', 'ytso', 'ytss', 'yts'],
 't': ['yttro-columbite',
       'ytterdalsgubben',
       'yttrocolumbite',
       'ytterdalsegga',
       'ytterdalssata',
       'yttrogummite',
       'yttro-cerite',
       'yttrocerite',
       'yttertjurbo',
       'ytter-vikna',
       'yttermalung',
       'ytterhogdal',
       'yttrialite',
       'yttertavle',
       'yttrium-90',
       'ytterdalen',
       'ytterbite',
       'ytterbium',
       'ytterhorn',
       'ytteroya',
       'yttralox',
       'yttersjo',
       'ytterbyn',
       'ytterbic',
       'ytteran',
       'yttrium',
       'ytterby',
       'ytteren',
       'ytteroy',
       'yttila',
       'ytttv',
       'ytt'],
 'u': ['ytu'],
 'v': ['ytv'],
 'w': ['ytwok'],
 'y': ['ytyk-kyuyol', 'ytyk-kuyol'],
 'z': ['ytz']}
