
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_yp = {'_': ['yp-403', 'yp-80', 'yp-24', 'yp-p2'],
 'a': ['ypacarai',
       'ypakoe',
       'ypato',
       'ypane',
       'ypard',
       'ypadu',
       'ypaja',
       'ypati',
       'ypas',
       'ypad',
       'ypa'],
 'b': ['ypbpr'],
 'c': ['ypc/pjc', 'ypcc', 'ypc'],
 'd': ['ypdn', 'ypd'],
 'e': ['ypecolsga',
       'ypenburg',
       'yperiet',
       'yperite',
       'ypers',
       'ypehu',
       'ypel3',
       'ypes',
       'ypec',
       'ypet',
       'ype'],
 'f': ['ypfb', 'ypfl', 'ypf'],
 'g': ['ypg'],
 'h': ['yphthimoides', 'yph'],
 'i': ['ypiranga_futebol_clube'],
 'j': ['ypj'],
 'l': ['yplan', 'yplm', 'ypll', 'ypl'],
 'm': ['ypm'],
 'n': ['ypn'],
 'o': ['ypotagmatarchis',
       'yponomeutoidea',
       'yport-sur-mer',
       'yponomeutidae',
       'yponomeutinae',
       'ypolochagos',
       'ypolokhagos',
       'yponomeuta',
       'ypotryll',
       'ypops!',
       'yport',
       'ypo'],
 'p': ['yppotryl', 'yppah', 'ypph', 'ypp'],
 'q': ['ypq'],
 'r': ['ypreville-biville',
       'ypresiosirex',
       'ypresiomyrma',
       'ypresian',
       'ypr-765',
       'yprium',
       'yproxy',
       'yprpb',
       'ypres',
       'ypr'],
 's': ['ypsilothuriidae',
       'ypsilonigaster',
       'ypsolophidae',
       'ypsotingini',
       'ypsilomena',
       'ypsilantis',
       'ypsilandra',
       'ypsilopus',
       'ypsigrock',
       'ypsolopha',
       'ypsilon',
       'ypsonas',
       'ypsora',
       'yps'],
 't': ['ypthimomorpha', 'ypthima', 'ypt-10', 'ypt-9'],
 'u': ['ypupiara', 'ypuw', 'ypu'],
 'w': ['ypw'],
 'y': ['ypypuera', 'ypy'],
 'z': ['ypz']}
