
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-21T07:50:03-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "07df6df7f906ecffe85ba523438562d7b063de2b",
 "version": "0.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
