
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_nb = {'_': ['nb.bbvci', 'nb-fi', 'nb2o5', 'nb-36', 'nb1', 'nb2'],
 'a': ['nba.com',
       'nbadl',
       'nbacc',
       'nba2k',
       'nbatv',
       'nbarc',
       'nback',
       'nbar',
       'nbac',
       'nbaa',
       'nbas',
       'nbaf',
       'nbat',
       'nba'],
 'b': ['nbbo', 'nbbi', 'nbbl', 'nbbj', 'nbbc', 'nbb'],
 'c': ['nbc-universal',
       'nbcuniversal',
       'nbcnews.com',
       'nbc-weapons',
       'nbc-weapon',
       'nbc.com',
       'nbc4hd',
       'nbc-tv',
       'nbc30',
       'nbc11',
       'nbc25',
       'nbcaa',
       'nbc10',
       'nbcam',
       'nbcsl',
       'nbchs',
       'nbc12',
       'nbcsn',
       'nbcl',
       'nbci',
       'nbcs',
       'nbc6',
       'nbcd',
       'nbca',
       'nbcu',
       'nbcc',
       'nbc5',
       'nbc4',
       'nbc'],
 'd': ['nbd-tma', 'nbdhmt', 'nbdl', 'nbde', 'nbd'],
 'e': ['nbeal2',
       'nbeika',
       'nbeal1',
       'nbench',
       'nbepc',
       'nbe-1',
       'nbec',
       'nbe1',
       'nbe'],
 'f': ['nbfl', 'nbfc', 'nbfz', 'nbfa', 'nbf'],
 'g': ['nbgi', 'nbg'],
 'h': ['nbhof', 'nbhm', 'nbhs', 'nbhd', 'nbh'],
 'i': ['nbioth', 'nbiaa', 'nbial', 'nbic', 'nbii', 'nbia', 'nbil', 'nbi'],
 'j': ['nbjhl'],
 'k': ['nbk'],
 'l': ['nblxnba', 'nblc', 'nbl1', 'nbl'],
 'm': ['nbmbaa', 'nbmr-1', 'nbmr-3', 'nbmb', 'nbmc', 'nbmg', 'nbma', 'nbm'],
 'n': ['nbname', 'nbn-3', 'nbn-4', 'nbn3', 'nbnw', 'nbni', 'nbn'],
 'o': ['nbome-mescaline', 'nbo-105', 'nbomb', 'nbo'],
 'p': ['nbpower',
       'nbpf10',
       'nbpf15',
       'nbpf19',
       'nbpf1',
       'nbpf3',
       'nbpme',
       'nbps',
       'nbpa',
       'nbpf',
       'nbpp',
       'nbpo',
       'nbp'],
 'q': ['nbqx', 'nbq'],
 'r': ['nbr3', 'nbri', 'nbrp', 'nbrm', 'nbr1', 'nbrc', 'nbr2', 'nbr'],
 's': ['nbscett',
       'nbstc',
       'nbs-1',
       'nbsae',
       'nbsd',
       'nbsp',
       'nbsr',
       'nbs1',
       'nbsc',
       'nbsx',
       'nbsi',
       'nbs'],
 't': ['nbtel',
       'nbths',
       'nbtsc',
       'nbtfc',
       'nbti',
       'nbty',
       'nbtc',
       'nbth',
       'nbtv',
       'nbt'],
 'u': ['nbu-prisen', 'nbuli', 'nbump', 'nbuf', 'nbu'],
 'v': ['nbva', 'nbv'],
 'w': ['nbwa', 'nbw'],
 'x': ['nbx'],
 'y': ['nbyo', 'nby']}
