
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_lw = {'_': ['lw5/7',
       'lw6/8',
       'lw10',
       'lw11',
       'lw12',
       'lw3',
       'lw2',
       'lw9',
       'lw1',
       'lw4'],
 'a': ['lwangghale',
       'lwakhakha',
       'lwamondo',
       'lwangwa',
       'lwamata',
       'lwandle',
       'lwanda',
       'lwala',
       'lwarx',
       'lwa'],
 'b': ['lwbt', 'lwb'],
 'c': ['lwcf', 'lwc'],
 'd': ['lwd'],
 'e': ['lwegyaung',
       'lwensinga',
       'lwemiyaga',
       'lweibdeh',
       'lweeza',
       'lwengo',
       'lweje',
       'lwei',
       'lwe'],
 'f': ['lwfc', 'lwf'],
 'g': ['lwgj'],
 'h': ['lwhs', 'lwh'],
 'i': ['lwizyana',
       'lwiindi',
       'lwin-u',
       'lwiii',
       'lwip',
       'lwir',
       'lwiw',
       'lwic',
       'lwi'],
 'j': ['lwjgl'],
 'k': ['lwkt', 'lwk'],
 'l': ['lwl'],
 'm': ['lwma', 'lwm'],
 'n': ['lwn.net', 'lwn'],
 'o': ['lwowiany', 'lwowiec', 'lwowek', 'lwow', 'lwop', 'lwob', 'lwo'],
 'p': ['lwpimp', 'lwp.pm', 'lwp'],
 'r': ['lwrifles', 'lwrak', 'lwrc', 'lwr'],
 's': ['lws-2', 'lwsd', 'lws'],
 't': ['lwt'],
 'v': ['lwv'],
 'w': ['lww']}
