
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_lv = {'_': ['lv-1201', 'lv-426', 'lv-rom', 'lv-sem', 'lv426', 'lv2'],
 'a': ['lvalue', 'lvam', 'lvac', 'lvad', 'lva'],
 'b': ['lvb'],
 'c': ['lvcmos', 'lvccld', 'lvcva', 'lvchs', 'lvcc', 'lvc'],
 'd': ['lvdc', 'lvdt', 'lvds', 'lvd'],
 'e': ['lvesd', 'lvedd', 'lvef', 'lvee', 'lvea', 'lvep'],
 'f': ['lvfcs', 'lvf'],
 'g': ['lvgz', 'lvg'],
 'h': ['lvhiff', 'lvhs', 'lvh'],
 'i': ['lvivelectrotrans',
       'lvivmozart',
       'lviewpro',
       'lvivska',
       'lvivske',
       'lview',
       'lvia',
       'lviv',
       'lvi'],
 'j': ['lvj'],
 'k': ['lvk'],
 'l': ['lvls', 'lvlt', 'lvl'],
 'm': ['lvmpd', 'lvmi', 'lvms', 'lvmh', 'lvm'],
 'n': ['lvndscape', 'lvn'],
 'o': ['lvovskaya',
       'lvovskoye',
       'lvovsky',
       'lvoa-c',
       'lvovka',
       'lvovo',
       'lvov',
       'lvo'],
 'p': ['lvpecl', 'lvpd', 'lvps', 'lvpa', 'lvp'],
 'q': ['lvq'],
 'r': ['lvrj.com', 'lvrj', 'lvrr', 'lvrs', 'lvrt', 'lvr'],
 's': ['lvs-86', 'lvs-97', 'lvsem', 'lvsf', 'lvsd', 'lvsv', 'lvs'],
 't': ['lvtp7a1',
       'lvtp-5',
       'lvtp-7',
       'lvt-5',
       'lvtp5',
       'lvt-7',
       'lvts',
       'lvt4',
       'lvtp',
       'lvtn',
       'lvt'],
 'u': ['lvucentvm', 'lvucenvm', 'lvusd'],
 'v': ['lvvpu', 'lvvwd', 'lvv'],
 'x': ['lvx'],
 'z': ['lvzbel', 'lvz']}
