
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_xm = {'_': ['xm26-lss',
       'xm-117e2',
       'xm-177e2',
       'xm177e2',
       'xm10014',
       'xm1128',
       'xm-177',
       'xm1156',
       'xm-214',
       'xm1202',
       'xm70e2',
       'xm41e1',
       'xm-109',
       'xm-207',
       'xm1219',
       'xm22e1',
       'xm45e1',
       'xm40e5',
       'xm1203',
       'xm207',
       'xm982',
       'xm303',
       'xm104',
       'xm109',
       'xm395',
       'xm156',
       'xm-29',
       'xm2go',
       'xm301',
       'xm-25',
       'xm-26',
       'xm148',
       'xm110',
       'xm214',
       'xm806',
       'xm307',
       'xm174',
       'xm177',
       'xm320',
       'xm500',
       'xm107',
       'xm312',
       'xm27',
       'xm84',
       'xm44',
       'xm-8',
       'xm41',
       'xm29',
       'xm26',
       'xm65',
       'xm25',
       'xm22',
       'xm8'],
 'a': ['xmark93',
       'xmascon',
       'xmarks',
       'xmark',
       'xmass',
       'xmame',
       'xman',
       'xmap',
       'xmal',
       'xmas',
       'xma'],
 'b': ['xmb'],
 'c': ['xmcd', 'xmc'],
 'd': ['xmdp', 'xmdr', 'xmdf', 'xmd'],
 'e': ['xmessage', 'xmetal', 'xmen'],
 'f': ['xmf'],
 'g': ['xmg'],
 'h': ['xmh'],
 'i': ['xmission.com',
       'xmission',
       'xmithie',
       'xmingw',
       'xmind',
       'xming',
       'xmii',
       'xmi'],
 'k': ['xmk'],
 'l': ['xmlhttprequest',
       'xml-retrieval',
       'xml/edifact',
       'xmlbeansxx',
       'xmlstarlet',
       'xmllambda',
       'xmlambda',
       'xml-http',
       'xmlvend',
       'xmlhttp',
       'xml-dom',
       'xmlmind',
       'xml-rpc',
       'xmlnuke',
       'xml-ir',
       'xmlgui',
       'xmlrpc',
       'xmldom',
       'xml:tm',
       'xmlspy',
       'xmlns',
       'xmltv',
       'xmlms',
       'xmldb',
       'xmlrs',
       'xml/a',
       'xmlp',
       'xmlm',
       'xmla',
       'xml'],
 'm': ['xmm-newton', 'xmmer', 'xmms2', 'xmms', 'xmm'],
 'n': ['xmn'],
 'o': ['xmodem-1k',
       'xmortis',
       'xmobots',
       'xmor-fm',
       'xmodem',
       'xmouse',
       'xmoand',
       'xmonad',
       'xmods',
       'xmove',
       'xmoto',
       'xmos',
       'xmo'],
 'p': ['xmplay', 'xmpp:', 'xmpr', 'xmpp', 'xmp'],
 'r': ['xmradio', 'xmrv', 'xmrc', 'xmr'],
 's': ['xmsr', 'xmss', 'xmsn', 'xms'],
 't': ['xmtc', 'xmtr', 'xmtv', 'xmt'],
 'u': ['xmultiplies', 'xmulzencab', 'xmucane', 'xmule', 'xmu'],
 'x': ['xmx']}
