
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-19T19:04:06-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "900973e92559f87d996ba0880749b6eb0519c7ac",
 "version": "v1.1.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
