
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_rr = {'rr.com': 'road_runner_high_speed_online',
 'rr300': 'rolls-royce_rr300',
 'rr4-rr64': 'sabayon_linux',
 'rr64': 'ridge_racer_64',
 'rrac': 'red_river_athletic_conference',
 'rram': 'resistive_random-access_memory',
 'rranchpar': 'ranchpar',
 'rrat': 'rotating_radio_transient',
 'rrca': 'road_runners_club_of_america',
 'rrcat': 'raja_ramanna_centre_for_advanced_technology',
 'rrci': 'redmont_railway',
 'rrcnca': 'red_rock_canyon_national_conservation_area',
 'rrcp': 'realtek_remote_control_protocol',
 'rrde': 'rotating_ring-disk_electrode',
 'rrdgraph': 'rrdtool',
 'rrds': 'relative_record_data_set',
 'rretrospective': 'dreamsongs:_a_rretrospective',
 'rrfm': 'really_really_free_market',
 'rrgi': 'reality_racing_incorporated',
 'rrhof': 'rock_and_roll_hall_of_fame',
 'rrim': 'reaction_injection_molding',
 'rriot': 'mos_technology_rriot',
 'rrisd': 'round_rock_independent_school_district',
 'rrkm': 'rrkm_theory',
 'rrlf': 'russian_rugby_league_federation',
 'rrmc': 'raven_rock_mountain_complex',
 'rrna': 'ribosomal_rna',
 'rrns': 'roosevelt_roads_naval_station',
 'rrok': 'revised_romanization_of_korean',
 'rrom': 'gypsy',
 'rroma': 'romani_people',
 'rromanes': 'romani_language',
 'rromania': 'romania',
 'rrotn': 'red_river_of_the_north',
 'rrr2': 'rayman_raving_rabbids_2',
 'rrr3': 'rayman_raving_rabbids_tv_party',
 'rrrr': 'rock_and_rail_llc',
 'rrsb': 'rhein-ruhr_s-bahn',
 'rrsp': 'registered_retirement_savings_plan',
 'rrssc': 'report_and_recommendations_of_the_scots_spelling_committee',
 'rrstar': 'the_rockford_register_star',
 'rrta': 'red_rose_transit_authority',
 'rrtm': 'rolls-royce_turbomeca_limited',
 'rrtmg': 'rapid_radiative_transfer_model',
 'rrvw': 'red_river_valley_and_western_railroad',
 'rrw1': 'reliable_replacement_warhead',
 'rrw2': 'reliable_replacement_warhead'}
        