
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_rk = {'rk-62': 'rk_62',
 'rk-95': 'rk_95_tp',
 'rk-pratishakhya': 'shiksha',
 'rk.crane': 'robert_k._crane',
 'rk02': 'rk05',
 'rk03': 'rk05',
 'rk04': 'rk05',
 'rk05-e': 'rk05',
 'rk05-f': 'rk05',
 'rk08': 'rk05',
 'rk11': 'rk05',
 'rk62': 'rk_62',
 'rk8e': 'rk05',
 'rkas': 'royal_kennebecasis_adventurers_society',
 'rkastiteli': 'rkatsiteli',
 'rkba': 'right_to_keep_and_bear_arms',
 'rkcrane': 'robert_k._crane',
 'rkellie': 'r._kelly',
 'rkelly': 'r._kelly',
 'rkhs': 'reproducing_kernel_hilbert_space',
 'rkjb': 'muan_international_airport',
 'rkjy': 'yeosu_airport',
 'rkka': 'red_army',
 'rkkf': 'soviet_navy',
 'rkky': 'rkky_interaction',
 'rkm62': 'rk_62',
 'rknw': 'wonju_airport',
 'rko-general': 'rko_pictures',
 'rkpc': 'jeju_international_airport',
 'rkpk': 'gimhae_international_airport',
 'rkpn': 'roman_catholic_party_of_the_netherlands',
 'rkpu': 'ulsan_airport',
 'rks8e': 'rk05',
 'rksi': 'incheon_international_airport',
 'rksp': 'roman-catholic_state_party',
 'rkss': 'gimpo_international_airport',
 'rkth': 'pohang_airport',
 'rktn': 'daegu_airport',
 'rktu': 'cheongju_airport'}
        