
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_hc = {'_': ['hc_neuilly-sur-marne',
       'hc_victoria-berestie',
       'hc_fribourg-gotteron',
       "hc_'s-hertogenbosch",
       'hc_sierre-anniviers',
       'hc_morzine-avoriaz',
       'hc_kazzinc-torpedo',
       'hc_astrakhanochka',
       'hc_frydek-mistek',
       'hc_bozen-bolzano',
       'hc_neumarkt-egna',
       'hc_keski-uusimaa',
       'hc-130n_hercules',
       'hc-130p_hercules',
       'hc-130_hercules',
       'hc_ambri-piotta',
       'hc_oranje-rood',
       'hc_berkut-kyiv',
       'hc_midtjylland',
       'hc_bagtyyarlyk',
       'hc_neftekhimik',
       'hc_bloemendaal',
       'hc_csikszereda',
       'hc_valpellice',
       'hc_budivelnyk',
       'hc_westermann',
       'hc_svilengrad',
       'hc_galychanka',
       'hc_lamacraft',
       'hc_gherdeina',
       'hc_baldridge',
       'hc_donbass-2',
       'hc_satakunta',
       'hc_severstal',
       'hc_pardubice',
       'hc_topolcany',
       'hc_prievidza',
       'hc_rotterdam',
       'hc85_series',
       'hc_grierson',
       'hc_litvinov',
       'hc_dobrudja',
       'hc_zalgiris',
       'hc_lausanne',
       'hc_vrchlabi',
       'hc_erlangen',
       'hc_andersen',
       'hc_temirtau',
       'hc_vladimir',
       'hc_martigny',
       'hc_belgorod',
       'hc_strache',
       'hc_lipetsk',
       'hc_kharkiv',
       'hc_metulla',
       'hc_tallinn',
       'hc_salamat',
       'hc_gardena',
       'hc_airways',
       'hc_olomouc',
       'hc_izhstal',
       'hc_jihlava',
       'hc_bolzano',
       'hc_mcneile',
       'hc_everest',
       'hc_thurgau',
       'hc_tornado',
       'hc_artmann',
       'hc_lipovci',
       'hc_chrudim',
       'hc_rybinsk',
       'hc_donbass',
       'hc_vilnius',
       'hc_bryansk',
       'hc_villars',
       'hc_almaty',
       'hc_bailey',
       'hc_korosa',
       'hc_varese',
       'hc_coombs',
       'hc_mechel',
       'hc_merano',
       'hc_tambov',
       'hc_rostov',
       'hc_astana',
       'hc_patten',
       'hc_chelny',
       'hc_asiago',
       'hc_kosice',
       'hc_berkut',
       'hc_lugano',
       'hc_raikes',
       'hc_hansen',
       'hc_sierre',
       'hc_vityaz',
       'hc_kladno',
       'hc_ryazan',
       'hc_potter',
       'hc_monza',
       'hc_drita',
       'hc_dalen',
       'hc_sarov',
       'hc_liceo',
       'hc_zalau',
       'hc_tabor',
       'hc_evans',
       'hc_speir',
       'hc_lutsk',
       'hc_zubri',
       'hc_ajoie',
       'hc_kuban',
       'hc_kehra',
       'hc_gomel',
       'hc_yugra',
       'hc_gilje',
       'hc_davos',
       'hc_odesa',
       'hc_verma',
       'hc_sochi',
       'hc_barys',
       'hc_braga',
       'hc_buzau',
       'hc_brno',
       'hc_lada',
       'hc_levy',
       'hc_omsk',
       'hc_most',
       'hc_cska',
       'hc_mvd',
       'hc_tps',
       'hc_loc',
       'hc_900',
       'hc_rys'],
 'a': ['hca_healthcare', 'hca_harrison', 'hca_inc.'],
 'b': ['hcb_karvina'],
 'c': ['hcc_training', 'hcc_40'],
 'e': ['hce_childers'],
 'f': ['hcf_insurance', 'hcf_domain', 'hcf_catch', 'hcfc_21'],
 'g': ['hcg_87'],
 'i': ['hci_bibliography'],
 'l': ['hcl_technologies',
       'hcl_connections',
       'hcl_infosystems',
       'hcl_corporation',
       'hcl_enterprise',
       'hcl_sametime',
       'hcl_commerce',
       'hcl_domino',
       'hcl_acid',
       'hcl_axon'],
 'm': ['hcmc_airport', 'hcm_metro', 'hcm_city'],
 'n': ['hcng_dispenser', 'hcn_channels', 'hcn_channel'],
 'o': ['hco_bonsor'],
 'p': ['hcp_z1'],
 'r': ['hcr_corporation', 'hcr_manorcare'],
 's': ['hcs_rawat'],
 't': ['hct116_cells', 'hct_group'],
 'v': ['hcv_genotypes', 'hcv_ires'],
 'y': ['hcy_522']}
