
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_hn = {'_': ['hn_andromedae',
       'hn_turtletaub',
       'hn_hardcastle',
       'hn_brailsford',
       'hn_pegasi',
       'hn_group'],
 'a': ['hnaberd,_aragatsotn',
       'hnahthial_district',
       'hnat_domenichelli',
       'hnat_honcharenko',
       'hnat_khotkevych',
       'hnaberd,_ararat',
       'hna_technology',
       'hnat_stefaniv',
       'hna_building',
       'hnanisho_ii',
       'hnanisho_i',
       'hna_group',
       'hnat_yura',
       'hna_hnu'],
 'c': ['hncoca_experiment', 'hnca_experiment'],
 'e': ['hnevin_castle'],
 'g': ['hngettwin_nikaya'],
 'i': ['hnialum_lalruatfeli',
       'hnifur_abrahams',
       'hni_corporation',
       'hnila_lypa',
       'hnin_mya',
       'hnic_2'],
 'j': ['hnj_mb'],
 'k': ['hnk_branitelj',
       'hnk_suhopolje',
       'hnk_tomislav',
       'hnk_capljina',
       'hnk_drinovci',
       'hnk_brotnjo',
       'hnk_segesta',
       'hnk_cibalia',
       'hnk_sibenik',
       'hnk_dinara',
       'hnk_zagreb',
       'hnk_gorica',
       'hnk_hajduk',
       'hnk_borovo',
       'hnk_rijeka',
       'hnk_trogir',
       'hnk_orasje',
       'hnk_zadar',
       'hnk_grude'],
 'l': ['hnlms_noord-brabant',
       'hnlms_heiligerlee',
       'hnlms_gelderland',
       'hnlms_schorpioen',
       'hnlms_groningen',
       'hnlms_rotterdam',
       'hnlms_kortenaer',
       'hnlms_amsterdam',
       'hnlms_friesland',
       'hnlms_evertsen',
       'hnlms_cerberus',
       'hnlms_zeeleeuw',
       'hnlms_banckert',
       'hnlms_utrecht',
       'hnlms_sumatra',
       'hnlms_matador',
       'hnlms_bonaire',
       'hnlms_holland',
       'hnlms_dolfijn',
       'hnlms_zeeland',
       'hnlms_zeehond',
       'hnlms_medusa',
       'hnlms_buffel',
       'hnlms_guinea',
       'hnlms_flores',
       'hnlms_walrus',
       'hnlms_soemba',
       'hnlms_borneo',
       'hnlms_draak',
       'hnlms_stier',
       'hnlms_tromp',
       'hnlms_java',
       'hnlms_o-20',
       'hnlms_o-8',
       'hnlms_m-1'],
 'm': ['hnmr_spectroscopy', 'hnms_tromp', 'hnms_java'],
 'n': ['hnn_extension'],
 'o': ['hnoms_tordenskjold',
       'hnoms_honningsvag',
       'hnoms_skorpionen',
       'hnoms_trondheim',
       'hnoms_thrudvang',
       'hnoms_valkyrien',
       'hnoms_valkyrjen',
       'hnoms_stavanger',
       'hnoms_nordkapp',
       'hnoms_sleipner',
       'hnoms_trudvang',
       'hnoms_eidsvold',
       'hnoms_utstein',
       'hnoms_svenner',
       'hnoms_thorodd',
       'hnoms_bergen',
       'hnoms_uthaug',
       'hnoms_ellida',
       'hnoms_glomma',
       'hnoms_kobben',
       'hnoms_gyller',
       'hnoms_storm',
       'hnomy_norge',
       'hnoms_stegg',
       'hnoms_kvikk',
       'hnoms_norge',
       'hnoms_vigra',
       'hnoms_hessa',
       'hnoms_brage',
       'hnoms_aeger',
       'hnoms_troll',
       'hnoms_tjeld',
       'hnoms_brann',
       'hnoms_ornen',
       'hnoms_vidar',
       'hnoms_froya',
       'hnoms_hitra',
       'hnoms_snogg',
       'hnoms_uller',
       'hnoms_kjell',
       'hnoms_start',
       'hnoms_trygg',
       'hnoms_rauma',
       'hnoms_stord',
       'hnoms_draug',
       'hnoms_nasty',
       'hnoms_rapp',
       'hnoms_maud',
       'hnoms_garm',
       'hnoms_rask',
       'hnoms_thor',
       'hnoms_vale',
       'hnoms_oslo',
       'hnoms_otra',
       'hnoms_odin',
       'hnoms_snar',
       'hnoms_sael',
       'hnoms_myg',
       'hnoms_sel',
       'hnoms_gor',
       'hnoms_ula',
       'hnoms_b-5',
       'hnoms_tyr',
       'hnoms_lyn'],
 's': ['hns_convention', 'hnsk_moslavina', 'hns_hoverfly'],
 't': ['hntb_architects', 'hnt_chicken', 'hntb_corp.'],
 'u': ['hnuti_brontosaurus', 'hnuti_duha'],
 'v': ['hnv_temperley'],
 'y': ['hnylyi_tikych', 'hnyla_lypa'],
 'z': ['hnz_group']}
