
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_aw = {'_': ['aw_canum_venaticorum',
       'aw-li_on-nam_ot-tjin',
       'aw_rostamani_group',
       'aw_cheng_chye',
       'aw_aaakare_aa',
       'aw_tjoei_lan',
       'aw_boon_haw',
       'aw_boon_par',
       'aw_tee_hong',
       'aw_pi_kyeh',
       'aw_chu_kee',
       'aw_chu_kin'],
 'a': ['awareness_international_academy',
       'awa_international_championship',
       'award_software_international',
       'awa_lightweight_championship',
       'awa_heavyweight_championship',
       'awantipora_railway_station',
       'awa_wrestling_championship',
       'awa-shirahama_bus_terminal',
       'awareness_through_movement',
       "awa_america's_championship",
       'awa_championship_wrestling',
       'awakenings_techno_parties',
       'awapuni,_palmerston_north',
       'awash_international_bank',
       'awadhesh_prasad_kushwaha',
       'awash_multimammate_mouse',
       'awashima_island,_niigata',
       'awaz_television_network',
       'awashima_island,_kagawa',
       'awaza_convention_center',
       'awakening_of_aggression',
       'awasani_railway_station',
       'awarua_tracking_station',
       'awad_moukhtar_halloudah',
       'awadeshwar_prasad_sinha',
       'awa_district,_tokushima',
       'awapuni_railway_station',
       'awashima_kaijo_ropeway',
       'awa_all-star_wrestling',
       'awami_action_committee',
       'awadh_bihari_choudhary',
       'awards_and_decorations',
       'awan_kecil_interchange',
       'awanish_kumar_awasthi',
       'awaba_railway_station',
       'away:_shuffle_dungeon',
       'awadhesh_narain_singh',
       'awas_aviation_capital',
       'awadhesh_pratap_singh',
       'awassa_kenema_stadium',
       'awake-evoke_the_urge-',
       'awa_heavyweight_title',
       'awaking_the_centuries',
       'awakening_bharat_mata',
       'awards_for_excellence',
       'aware_global_hospital',
       'award_software_europe',
       'awatea_street_stadium',
       'award_software_japan',
       'awang_husaini_sahari',
       'awami_national_party',
       'awakening_the_zodiac',
       'awad_hamed_al-bander',
       'awakening_from_abyss',
       'awara_paagal_deewana',
       'away_shuffle_dungeon',
       'awad_hamed_al-bandar',
       'awad_hamad_al-bandar',
       'award_of_excellence',
       'awaken_the_guardian',
       'awaare_caraale_cali',
       'awaken_the_dreamers',
       'awash_national_park',
       'awanish_kumar_singh',
       'awakening_the_world',
       'awash_rail_disaster',
       'awaiting_your_reply',
       'awadh_saleh_sherman',
       'awami_muslim_league',
       'awa_district,_chiba',
       'awa_marie_coll-seck',
       'awasthi_bala_prasad',
       'awami_workers_party',
       'awad_bing_language',
       'awaken_in_oblivion',
       'awatef_ben_hassine',
       'away_goes_prudence',
       'awadhesh_kumar_rai',
       'awang_faroek_ishak',
       'award_modular_bios',
       'awana_ibn_al-hakam',
       'awatef_abdel_kerim',
       'awan_setho_raharjo',
       'awa_dance_festival',
       'awake_and_dreaming',
       'awatef_abdel_karim',
       'awad_ahmed_ashareh',
       'award_software_inc',
       'awakening_of_faith',
       'awareness_of_dying',
       'awadia_and_fadnia',
       'awaken_the_empire',
       'award_for_heroism',
       'awakino_ski_field',
       'awa_superclash_ii',
       'awakening_in_iraq',
       'awadh_queer_pride',
       'awad_salah_nasser',
       'awards_for_dexter',
       'awatea_st_stadium',
       'awards_and_prizes',
       'awake_and_breathe',
       'awa_tanuki_gassen',
       'awang_anak_raweng',
       'awang_adek_hussin',
       'awad_saleh_ahmed',
       'awail_al_maqalat',
       'awaken_the_world',
       'awakino_ski_area',
       'awa_sand_pillars',
       'awais_qasim_khan',
       'awa_super_sunday',
       'awa_superclash_1',
       'awake_in_america',
       'awa_pit_language',
       'awaken_the_tides',
       'awaking_the_gods',
       'awais_qadir_shah',
       'awapuni_gold_cup',
       'awash_sebat_kilo',
       'awa_odori_kaikan',
       'awantura_o_basie',
       'awassa_city_f.c.',
       'away_goals_rule',
       'awata_no_mahito',
       'awad_abdel_nabi',
       'award_for_valor',
       'awar_khan_aibak',
       'awake_and_sing!',
       'away_from_rome!',
       'away_with_words',
       'awake_our_souls',
       'awake_and_alive',
       'awantura_o_kase',
       'awaaz_india_tv',
       'award_of_merit',
       'awad_saud_awad',
       'awad_al_bandar',
       'awa_oki_kaisen',
       "awa_ly_n'diaye",
       'away_from_here',
       'away_from_home',
       'awassa_city_fc',
       'away_all_boats',
       'awa_sene_sarr',
       'awad_al_sayad',
       'award_tour_ii',
       'away_from_her',
       'awa_whigs_awa',
       'awake_my_soul',
       'awa_fall_diop',
       'awad_haj_ali',
       'away_is_mine',
       'away_from_me',
       'away_we_go'],
 'b': ['awb_oil-for-wheat_scandal', 'awbury_historic_district'],
 'e': ['awendaw,_south_carolina',
       'awenda_provincial_park',
       'awesome_magical_tales',
       'awesome_new_republic',
       'awesome_again_stakes',
       'aweil_center_county',
       'aweil_south_county',
       'aweil_north_county',
       'aweil,_south_sudan',
       'aweil_east_county',
       'aweil_west_county',
       'aweil_east_state',
       'aweb_web_browser',
       'awesome_as_fuck',
       'aweil_stars_fc',
       'awe_+_wonder'],
 'f': ['awf_heavyweight_championship',
       'awf_tag-team_championship',
       'awf_hardcore_championship',
       'awful,_beautiful_life',
       'awful_mess_mystery'],
 'g': ['awg-9_and_apg-71'],
 'h': ['awh_polytechnic_college',
       'awhad_al-din_al-razi',
       'awhitu_regional_park',
       'awhadi_of_maragheh',
       'awhitu_wind_farm'],
 'i': ['awila_wachana_punta',
       'awi-pori_rural_llg',
       "awit_para_sa'yo",
       'awit_sa_bohol',
       'awit_ng_saya'],
 'k': ['awk_programming_language',
       'awk_programming_langauge',
       'awkward_family_photos',
       'awkward_&_depressed',
       'awkward_black_girl'],
 'l': ['awlad_hossain_chakladar', 'awliya_allah_amuli', 'awlad_sidi_shaykh'],
 'm': ['awm/maa_falconer_lecturer', 'awm_service_award'],
 'n': ['awn-adin_ibn_hubayra',
       'awntyrs_off_arthure',
       'awn_alsharif_qasim',
       'awni_abd_al-hadi',
       'awni_abdul_hadi',
       "awn_ibn_ja'far"],
 'o': ['awooto_eeday_mosque'],
 's': ['aws_heavyweight_championship',
       'awsworth_railway_station',
       'aws_heavyweight_champion',
       'aws_elastic_beanstalk',
       'aws_ibn_qallam'],
 't': ['awty_international_school', 'awt_native_interface'],
 'u': ['awutu_senya_district', 'awuah_panin_iii', 'awut_deng_acuil'],
 'w': ['awwal_zubairu_gambo', 'awwam_ibn_khuwaylid'],
 'z': ['awz_p70_zwickau']}
