
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_gb = {'_': ['gb_pro-series_loughborough',
       'gb_pro-series_shrewsbury',
       'gb_pro-series_glasgow',
       'gb_theatre_company',
       'gb_hodge_center',
       'gb_cycling_team',
       'gb_di_quadro',
       'gb_de_rossi',
       'gb_virus_c',
       'gb_class_3',
       'gb_class_2',
       'gb_class_1'],
 'a': ['gba_championship_basketball:two-on-two',
       'gbanti_kamaranka_chiefdom',
       'gbagada_general_hospital',
       'gbane_kandor_chiefdom',
       'gba_wireless_adapter',
       'gbagbo_junior_magbi',
       'gba_flash_cartridge',
       'gbahi_gwladys_sakoa',
       'gba_movie_player',
       'gba_sound_format',
       'gba_network_boot',
       'gba_flash_carts',
       'gba_majay_bma'],
 'c': ['gbc_international_bank', 'gbc_asset_management'],
 'e': ['gbendembu_ngowahun_chiefdom',
       'gbehzohngar_milton_findley',
       'gbemisola_ruqayyah_saraki',
       'gbemileke_"oscar"_oyinsan',
       'gbedikpe_emmanuel_amouzou',
       'gbemi_olateru_olagbegi',
       'gbenga_bareehu_ashafa',
       'gbenga_samuel_okunowo',
       'gbele_resource_centre'],
 'h': ['gbh_with_intent'],
 'i': ['gbinle_dixing_chiefdom'],
 'n': ['gbn_high_school'],
 'o': ['gbolahan_olusegun_yishawu',
       'gboribiogha_john_jonah',
       'gbomo_gbomo_express',
       'gborogboro_and_meme'],
 's': ['gbs-department_of_management'],
 'u': ['gbu-37_gps-aided_munition',
       'gbu-44/b_viper_strike',
       'gbu-27_paveway_iii',
       'gbu_indoor_stadium',
       'gbu-24_paveway_iii',
       'gbu-12_paveway_ii',
       'gbu-16_paveway_ii',
       'gbu-10_paveway_ii']}
