
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_lm = {'_': ['lm_brekhovskikh',
       'lm_montgomery',
       'lm_kaganovich',
       'lm_magazine',
       'lm_thompson',
       'lm_ericsson',
       'lm_distance',
       'lm/dc_tour',
       'lm_sensors',
       'lm_gensman',
       'lm_thapar',
       'lm_curve',
       'lm_truck',
       'lm_wells',
       'lm_radio',
       'lm_hash',
       'lm_ward',
       'lm_boyd',
       'lm_shaw',
       'lm_2500',
       'lm_gte',
       'lm_24'],
 'a': ['lma_manager', 'lmax_group'],
 'b': ['lmb_hotel'],
 'c': ['lmcu_ballpark', 'lmc_n49'],
 'e': ['lme_aluminium', 'lme_nickel', 'lme_copper', 'lme,_inc.', 'lme_zinc'],
 'f': ['lmfao_discography'],
 'g': ['lmg-pist_41/44', 'lmg_08/15', 'lmg,_llc', 'lmg_25', 'lmg_08'],
 'h': ['lmhosts_file'],
 'j': ['lmj_viaud'],
 'k': ['lmk_resources'],
 'l': ['lmlk_seals', 'lmlk_seal', 'lml_nv'],
 'n': ['lmno_entertainment', 'lmn_architects'],
 'r': ['lmr_liepaja', 'lmr_rutten', 'lmr_lion'],
 's': ['lms_beyer-garratts',
       'lms_perseverance',
       'lms_turbomotive',
       'lms_pacifics',
       'lms_railcars',
       'lms_garratt',
       'lms,_moscow',
       'lms_filter',
       'lms_center',
       'lms_10000',
       'lms_8f'],
 't': ['lmt_connection', 'lmt_virsliga'],
 'u': ['lmu_klinikum', 'lmu_munich'],
 'x': ['lmx_sirex']}
