
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_hl = {'_': ['hl2:_lost_coast',
       'hl2_lost_coast',
       'hl2:_episode_1',
       'hl_v._matheson',
       'hl2_episode_2',
       'hl_nage_gowda',
       'hl_tau_76',
       'hl_dt_st'],
 'a': ['hla_a1-b8-dr3-dq2_haplotype',
       'hlabisa_local_municipality',
       'hlawga_railway_station',
       'hla_informatics_group',
       'hlawga_national_park',
       'hlantlalala_v_dyanti',
       'hla_a1-b8_haplotype',
       'hlatshwayo_v_hein',
       'hlaing_myo_aung',
       'hla_myint_than',
       'hla_maung_shwe',
       'hla_thein_swe',
       'hla_myint_swe',
       'hlaing_bo_bo',
       'hla_moe_aung',
       'hla_yee_yee',
       'hla_yin_win'],
 'b': ['hlboke_nad_vahom'],
 'e': ['hleda_se_tata'],
 'i': ['hlinaia,_grigoriopol,_transnistria',
       'hlinaia,_slobozia,_transnistria',
       'hliadky,_ternopil_oblast',
       'hlinka_gretzky_cup',
       'hlinik_nad_hronom'],
 'k': ['hlkx_hawk_eye'],
 'l': ['hll_lifecare_limited'],
 'o': ['hloubetin_tram_depot', 'hlothhere_of_kent'],
 's': ['hls_color_space'],
 'u': ['hluhluwe-umfolozi_game_reserve',
       'hluleka_nature_reserve',
       'hluhluwe_game_reserve',
       'hluboka_nad_vltavou'],
 'y': ['hlynsko-rozbyshevske_oil_field',
       'hlybochok,_borshchiv_hromada',
       'hlynsk,_romny_raion',
       'hlyboka_coal_mine']}
