
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_hk = {'_': ['hk_television_entertainment',
       'hk_government_romanisation',
       'hk_kryzhynka_kompanion',
       'hk_olimpija_ljubljana',
       'hk_liepajas_metalurgs',
       'hk_slavia_partizanske',
       'hk_dukla_michalovce',
       'hk_spartak_subotica',
       'hk_olimp/venta_2002',
       'hk_lokomotiv_moscow',
       'hk_acroni_jesenice',
       'hk_golfer_magazine',
       'hk_vityaz_kharkiv',
       'hk_kryzhynka_kyiv',
       'hk_slovan_gelnica',
       'hk_generals_kiev',
       'hk_dynamax_nitra',
       'hk_2016_trebisov',
       'hk_kranjska_gora',
       'hk_dukla_trencin',
       'hk_triglav_kranj',
       'hk_golden_forum',
       'hk_english_pop',
       'hk_prizma_riga',
       'hk_ardo_nitra',
       'hk_36_skalica',
       'hk_orange_20',
       'hk_atek_kyiv',
       'hk_riga_2000',
       'hk_91_senica',
       'hk_mvd_tver',
       'hk_novi_sad',
       'hk_ns_stars',
       'hk_id_card'],
 'a': ['hkakaborazi_national_park'],
 'b': ['hkbp_nommensen_university'],
 'f': ["hkfa_chairman's_cup", 'hkfc_soccer_sevens', 'hkfa_league_cup'],
 'k': ['hkk_zrinjski_mostar', 'hkk_capljina_lasta'],
 'l': ['hkl_class_m200', 'hkl_class_m300', 'hkl_class_m100'],
 'm': ['hkm_rimavska_sobota'],
 'r': ['hkr_international_limited',
       'hkr_international_ltd.',
       'hkr_international_ltd',
       'hkri_taikoo_hui'],
 's': ['hksar_reunification_cup',
       'hks_ruch_zdzieszowice',
       'hks_bobry_bytom',
       'hks_pu_college'],
 't': ['hktdc_food_expo'],
 'u': ["hkust_students'_union",
       'hkust_business_school',
       'hkuga_primary_school']}
