
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_jr = {'_': ['jr-basic', 'jr-tokai', 'jr-west', 'jr-voy', 'jr.'],
 'a': ['jrahovit',
       'jrambar',
       'jraberd',
       'jrarrat',
       'jrabiee',
       'jraifia',
       'jradzor',
       'jrakuys',
       'jrashen',
       'jrarbi',
       'jrarat',
       'jraber',
       'jrakus',
       'jrahs',
       'jraif',
       'jrapi',
       'jras',
       'jra'],
 'b': ['jrbcafc', 'jrb37', 'jrbm', 'jrbp', 'jrb'],
 'c': ['jrc386', 'jrcls', 'jrcl', 'jrc'],
 'd': ['jrdn', 'jrd'],
 'e': ['jreijes', 'jreap', 'jreif', 'jref'],
 'f': ['jrf-5', 'jrfu', 'jrfm', 'jrf'],
 'g': ['jrgs', 'jrg'],
 'h': ['jrhs', 'jrh'],
 'i': ['jri-poland', 'jripples', 'jric', 'jrib', 'jri'],
 'j': ['jrjr'],
 'k': ['jrk'],
 'l': ['jrl'],
 'm': ['jrman', 'jrmp', 'jrm'],
 'n': ['jrn'],
 'o': ['jrocker', 'jrockit', 'jrocket', 'jroll', 'jroc', 'jro'],
 'p': ['jrp-ringier', 'jrp'],
 'r': ['jrrtolkien', 'jrrt', 'jrr'],
 's': ['jrsm', 'jrss', 'jrs'],
 't': ['jrti', 'jrtv', 'jrtc', 'jrt'],
 'u': ['jruby', 'jrulm', 'jrul', 'jruh', 'jrun', 'jru'],
 'v': ['jrvezh', 'jrvesh', 'jrvej', 'jrv'],
 'x': ['jrx2'],
 'z': ['jrz']}
