from enum import Enum


class PrivateEndpoints(str, Enum):
    ENDPOINT_SERVICE_STATUS_CREATING = "ENDPOINT_SERVICE_STATUS_CREATING"
    ENDPOINT_SERVICE_STATUS_AVAILABLE = "ENDPOINT_SERVICE_STATUS_AVAILABLE"
    ENDPOINT_SERVICE_STATUS_CREATE_FAILED = "ENDPOINT_SERVICE_STATUS_CREATE_FAILED"
    ENDPOINT_SERVICE_STATUS_DELETING = "ENDPOINT_SERVICE_STATUS_DELETING"
    ENDPOINT_SERVICE_STATUS_DELETE_FAILED = "ENDPOINT_SERVICE_STATUS_DELETE_FAILED"

    def __str__(self) -> str:
        return str(self.value)
