
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rm = {'_': ['rm_broadcasting',
       'rm_discography',
       'rm_ballantyne',
       'rm_turnchapel',
       'rm_tollefson',
       'rm_converter',
       'rm_education',
       "rm_sotheby's",
       'rm-81_agena',
       'rm_stallman',
       'rm_chivenor',
       'rm_minibook',
       'rm_auctions',
       'rm_johnson',
       'rm_hubbert',
       'rm_keesing',
       'rm-86_exos',
       'rm_pollock',
       'rm_vaughan',
       'rm_condor',
       'rm_nimbus',
       'rm_koster',
       'rm_instow',
       'rm_tamar',
       'rm_lence',
       'rm_rilke',
       'rm_poole',
       'rm_1431',
       'rm_2338',
       'rm_1832',
       'rm_2222',
       'rm_2244',
       'rm_1837',
       'rm_1869',
       'rm_1826',
       'rm_2243',
       'rm_380z',
       'rm_hare',
       'rm_2322',
       'rm_1221',
       'rm_fox',
       'rm_620',
       'rm_plc',
       'rm_243',
       'rm_odp',
       'rm_505',
       'rm_70',
       'rm_12'],
 'a': ['rmaf_butterworth',
       'rmanj_monastery',
       'rma_sandhurst',
       'rmaf_simpang',
       'rmaf_kuantan'],
 'b': ['rmb_holdings', 'rmb_chivenor', 'rmb_city'],
 'c': ['rmcc_invitational', 'rmc_decouverte', 'rmc_story', 'rmc_group'],
 'd': ['rmd_kwikform'],
 'f': ['rmf_fm'],
 'g': ['rmgroup_message', 'rmg_networks', 'rmg_connect'],
 'i': ['rmit_publishing',
       'rmit_university',
       'rmi_corporation',
       'rmi_expeditions',
       'rmit_redbacks',
       'rmit_gallery',
       'rmit_music',
       'rmit_link'],
 'j': ['rmjm_london'],
 'k': ['rmk_9'],
 'l': ['rml_group', 'rml_380z'],
 'n': ['rmn_newsletter', 'rmn_network', 'rmn_iloilo', 'rmn_naga'],
 'r': ['rmr_hall'],
 's': ['rms_ben-my-chree',
       'rms_strathnaver',
       'rms_granularity',
       'rms_montlaurier',
       'rms_mauritania',
       'rms_lancastria',
       'rms_strathaird',
       'rms-106_hizack',
       'rms_strathmore',
       'rms_berengaria',
       'rms_mauretania',
       'rms_carinthia',
       'rms_victorian',
       'rms_franconia',
       'rms_aquitania',
       'rms_britannic',
       'rms_laurentic',
       'rms_montnairn',
       'rms_britannia',
       'rms_lusitania',
       'rms_rangitiki',
       'rms_rangitata',
       'rms_magdalena',
       'rms_carpathia',
       'rms_campania',
       'rms_sylvania',
       'rms_atlantic',
       'rms_canberra',
       'rms_justicia',
       'rms_teutonic',
       'rms_britanic',
       'rms_carthage',
       'rms_carmania',
       'rms_tuscania',
       'rms_monteith',
       'rms_moldavia',
       'rms_slavonia',
       'rms_titantic',
       'rms_leinster',
       'rms_scythia',
       'rms_titanic',
       'rms_etruria',
       'rms_mooltan',
       'rms_oceanic',
       'rms_saxonia',
       'rms_orizaba',
       'rms_ausonia',
       'rms_locotec',
       'rms_andania',
       'rms_fenella',
       'rms_laconia',
       'rms_orontes',
       'rms_mataroa',
       'rms_columba',
       'rms_olympic',
       'rms_antonia',
       'rms_aurania',
       'rms_ivernia',
       'rms_tayleur',
       'rms_lucania',
       'rms_niagara',
       'rms_alaunia',
       'rms_gaelic',
       'rms_tahiti',
       'rms_orduna',
       'rms_segwun',
       'rms_atrato',
       'rms_persia',
       'rms_orbita',
       'rms_scotia',
       'rms_heaven',
       'rms_quetta',
       'rms_aureol',
       'rms_maloja',
       'rms_cedric',
       'rms_amazon',
       'rms_arabia',
       'rms_umbria',
       'rms_douro',
       'rms_power',
       'rms_saxon',
       'rms_corfu',
       'rms_rhone',
       'rms_value',
       'rms_trent',
       'rms_cairo',
       'rms_orion',
       'rms_speed',
       'rms_ophir',
       'rms_ebro',
       'rms_celt',
       'rms_qm2',
       'rms_qe2'],
 't': ['rmt_sambandham', 'rmt_bateleur'],
 'w': ['rmw_dixon'],
 'z': ['rmz_corp']}
