
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rw = {'_': ['rw3_technologies',
       'rw_payne-gallwey',
       'rw/rr_challenge',
       'rw_fassbinder',
       'rw_mcquarters',
       'rw_andromedae',
       'rw_bradford',
       'rw_southern',
       'rw_goodwin',
       'rw_aurigae',
       'rw_cameron',
       'rw_kember',
       'rw_wehrle',
       'rw_church',
       'rw_carden',
       'rw_miller',
       'rw_cephei',
       'rw_cygni',
       'rw_ahlen',
       'rw_essen',
       'rw_95.1',
       'rw_eaks',
       'rw_paul',
       'rw_and'],
 'a': ['rwanda/transnational_issues',
       'rwanda-tanzania_relations',
       'rwanda-turkey_relations',
       'rwanda-spain_relations',
       'rwandan_government',
       'rwamagana_district',
       'rwakayihura_famine',
       'rwandan_literature',
       'rwandan_revolution',
       'rwandan_president',
       'rwampara_district',
       'rwandese_republic',
       'rwandan_massacre',
       'rwandair_express',
       'rwandan_language',
       'rwandan_passport',
       'rwandan_genocide',
       'rwandan_monarchy',
       'rwandan_kingdom',
       'rwanda_massacre',
       'rwandan_cuisine',
       'rwandi_language',
       'rwanda_tribunal',
       'rwanda_language',
       'rwanda_genocide',
       'rwanda_inquiry',
       'rwanda_kingdom',
       'rwandan_music',
       'rwandan_dance',
       'rwandan_franc',
       'rwandan_frank',
       'rwandese_carp',
       'rwanda_rwacu',
       'rwanda_franc',
       'rwanda_nziza',
       'rwandan_cup',
       'rwanda_war',
       'rwa_people',
       'rwan_seco'],
 'b': ['rwby_chibi', 'rwb_adria', 'rwb_lewis', 'rwb_330'],
 'd': ['rwd-14_czapla',
       'rwd_molenbeek',
       'rwd.14_czapla',
       'rwd_magazine',
       'rwd_mag',
       'rwd_14',
       'rwd_23',
       'rwd_21',
       'rwd_16',
       'rwd_18',
       'rwd_10',
       'rwd_22',
       'rwd_17',
       'rwd_11',
       'rwd_15',
       'rwd_13',
       'rwd_19',
       'rwd_5',
       'rwd_2',
       'rwd_1',
       'rwd_4',
       'rwd_7',
       'rwd_9',
       'rwd_6',
       'rwd_8',
       'rwd_3'],
 'e': ['rwekunye-apac-aduku-lira-kitgum-musingo_road',
       'rwenzururu_movement',
       'rwenzori_mountains',
       'rwegasira_oscar',
       'rwenzori_turaco',
       'rwenzori_apalis',
       'rweideh,_idlib',
       'rwenzori_batis',
       'rwe_transgas',
       'rwe_tower',
       'rwe_dea',
       'rwe_ag'],
 'i': ['rwitobroto_mukherjee', 'rwindi_airport', 'rwi_racing', 'rwi_essen'],
 'j': ['rwjbarnabas_health', 'rwj_foundation', 'rwj_airpark'],
 'o': ['rwo_alzey'],
 's': ['rws_motorsport',
       'rws_bruxelles',
       'rwsfm_103.3',
       'rws_group',
       'rws_bank'],
 't': ['rwth_aachen', 'rwth_asr']}
