
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_mw = {'_': ['mw6825000',
       'mw-peak',
       'mw1122',
       'mw4mw',
       'mw-50',
       'mw50',
       'mw08',
       'mw4m',
       'mw-1',
       'mw4w',
       'mw4',
       'mw2',
       'mw7',
       'mw3'],
 'a': ['mwananyamala',
       'mwanamutapa',
       'mwadingusha',
       'mwakinyungu',
       'mwahahahaha',
       'mwambathana',
       'mwanathumba',
       'mwaluvanga',
       'mwanachini',
       'mwakirunge',
       'mwakeitari',
       'mwangareme',
       'mwarakaya',
       'mwathaini',
       'mwahahaha',
       'mwakibete',
       'mwaketutu',
       'mwamkuchi',
       'mwashinga',
       'mwansanga',
       'mwangangi',
       'mwasumbia',
       'mwansekwa',
       'mwanawasa',
       'mwandishi',
       'mwanhuzi',
       'mwandoni',
       'mwambiri',
       'mwanyora',
       'mwangeza',
       'mwangoni',
       'mwangini',
       'mwanzele',
       'mwambani',
       'mwandimu',
       'mwarungu',
       'mwangata',
       'mwankoko',
       'mwakwala',
       'mwakunde',
       'mwandeti',
       'mwaiseni',
       'mwangulu',
       'mwatisi',
       'mwasiti',
       'mwalili',
       'mwaembe',
       'mwazare',
       'mwanuku',
       'mwabani',
       'mwatate',
       'mwalimu',
       'mwabila',
       'mwayaya',
       'mwanga',
       'mwanda',
       'mwanza',
       'mwandi',
       'mwalau',
       'mwambi',
       'mwansa',
       'mwangi',
       'mwalim',
       'mwambe',
       'mwadui',
       'mwanzo',
       'mwaga',
       'mwana',
       'mwaya',
       'mwaro',
       'mwata',
       'mwani',
       'mwari',
       'mwazi',
       'mwada',
       'mwale',
       'mwami',
       'mwave',
       'mwape',
       'mwaru',
       'mwaa',
       'mwac',
       'mwam',
       'mwak',
       'mwav',
       'mwah',
       'mwa'],
 'b': ['mwb'],
 'c': ['mwcs-38',
       'mwcs-18',
       'mwcs-28',
       'mwcs-48',
       'mwcs-1',
       'mwcsd',
       'mwcog',
       'mwcd',
       'mwcr',
       'mwcw',
       'mwcc',
       'mwcf',
       'mwcb',
       'mwc'],
 'd': ['mwdwl-eithin', 'mwda', 'mwd'],
 'e': ['mweru-wa-ntipa',
       'mwenezi-chivi',
       'mwenemutapa',
       'mwene-ditu',
       'mwenekongo',
       'mwebantu',
       'mweelrea',
       'mwenezi',
       'mweileh',
       'mwe-te',
       'mwenda',
       'mwembe',
       'mweiga',
       'mwenge',
       'mwewe',
       'mwema',
       'mweru',
       'mweza',
       'mweso',
       'mwera',
       'mwele',
       'mweka',
       'mweya',
       'mweri',
       'mwesa',
       'mweb',
       'mwe'],
 'f': ['mwfl', 'mwf'],
 'g': ['mwgw', 'mwg'],
 'h': ['mwhs-3', 'mwhswm', 'mwhs-2', 'mwhs-1', 'mwhl', 'mwhs', 'mwh'],
 'i': ['mwinilunga',
       'mwirichia',
       'mwitikila',
       'mwiyogo',
       'mwimuto',
       'mwindo',
       'mwinda',
       'mwingi',
       'mwiini',
       'mwicps',
       'mwini',
       'mwit',
       'mwir',
       'mwi'],
 'k': ['mwk'],
 'l': ['mwl'],
 'm': ['mwm'],
 'n': ['mwnt', 'mwnf', 'mwng', 'mwn'],
 'o': ['mwogahendi', 'mwotlap', 'mwom', 'mwo'],
 'p': ['mwpc', 'mwph', 'mwp'],
 'r': ['mwrank', 'mwrrs', 'mwrri', 'mwrta', 'mwra', 'mwrc', 'mwr'],
 's': ['mwss-172',
       'mwss-472',
       'mwss-274',
       'mwss-473',
       'mwss-271',
       'mwss-371',
       'mwss-273',
       'mwss-272',
       'mwss-372',
       'mwss-374',
       'mwss-171',
       'mwss-471',
       'mwss-373',
       'mwsg-37',
       'mwsg-17',
       'mwsg-27',
       'mwsg-47',
       'mwst',
       'mwsa',
       'mwsd',
       'mws'],
 't': ['mwtc', 'mwta', 'mwth', 'mwt'],
 'u': ['mwuetsi', 'mwua', 'mwu'],
 'v': ['mwv'],
 'w': ['mwwst', 'mwws', 'mww'],
 'x': ['mwx'],
 'y': ['mwygq', 'mwy']}
