
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_xb = {'_': ['xb-33',
       'xb-48',
       'xb-21',
       'xb-28',
       'xb-35',
       'xb-59',
       'xb-44',
       'xb-60',
       'xb-30',
       'xb-19',
       'xb-40',
       'xb-45',
       'xb-22',
       'xb130',
       'xb-27',
       'xb360',
       'xb-17',
       'xb-15',
       'xb-39',
       'xb-38',
       'xb-31',
       'xb-46',
       'xb-42',
       'xb-52',
       'xb-49',
       'xb-16',
       'xb-68',
       'xb-53',
       'xb-51',
       'xb-70',
       'xb-41',
       'xb-8',
       'xb-1',
       'xb17',
       'xb1'],
 'a': ['xbase-clients',
       'xbaquiyalo',
       'xbalanque',
       'xbase++',
       'xbasic',
       'xband',
       'xbase',
       'xbap',
       'xbai',
       'xba'],
 'b': ['xbbrowser'],
 'c': ['xbc'],
 'e': ['xbel', 'xbee', 'xber', 'xbe'],
 'h': ['xbhs'],
 'i': ['xbiff', 'xbill', 'xbiz', 'xbin'],
 'j': ['xbj'],
 'l': ['xblades',
       'xblock',
       'xblive',
       'xblite',
       'xbloc',
       'xblm',
       'xbla',
       'xbl2',
       'xbl'],
 'm': ['xbmc4xbox', 'xbml', 'xbmp', 'xbmc', 'xbm'],
 'o': ['xboxmediaplayer',
       'xboxmediacenter',
       'xbox-live',
       'xbox-360',
       'xboxlive',
       'xbox360',
       'xboard',
       'xboxen',
       'xbox2',
       'xbow',
       'xbox'],
 'p': ['xbp1', 'xbp'],
 'r': ['xbright', 'xbrite', 'xbrls', 'xbrl', 'xbra', 'xbr'],
 's': ['xbss'],
 't': ['xbtf'],
 'u': ['xbuntu', 'xburst'],
 'w': ['xbwd'],
 'x': ['xbxrx', 'xbx']}
