
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_vf = {'_': ['vf-211_fighting_checkmates',
       'vf_of_hohenlohe-langenburg',
       'vf-103_jolly_rogers',
       'vf-22_sturmvogel_ii',
       'vf-17_jolly_rogers',
       'vf-84_jolly_rogers',
       'vf-61_jolly_rogers',
       'vf-41_black_aces',
       'vf_display_tube',
       'vf_ivano_dibona'],
 'a': ['vfa-211_fighting_checkmates',
       'vfa-87_golden_warriors',
       'vfa-103_jolly_rogers',
       'vfa-41_black_aces'],
 'b': ['vfb_germania_halberstadt',
       'vfb_marathon_remscheid',
       'vfb_stuttgart_amateure',
       'vfb-einheit_zu_pankow',
       'vfb_fortuna_chemnitz',
       'vfb_fichte_bielefeld',
       'vfb_1900_offenbach',
       'vfb_oldenburg_ii',
       'vfb_stuttgart_ii',
       'vfb_leipzig_ii'],
 'c': ['vfc-12_fighting_omars'],
 'k': ['vfk_sudwest_leipzig'],
 'l': ['vfl/afl_pre-season_competition',
       'vfl/afl_goalkicking_records',
       'vfl-stadion_am_elsterweg',
       'vfl_klafeld-geisweid_08',
       'vfl_players_association',
       'vfl_kirchheim_knights',
       'vfl/afl_games_records',
       'vfl_germania_1894',
       'vfl_bad_berleburg',
       'vfl_wolfsburg_ii',
       'vfl_night_series',
       'vfl_07_neustadt',
       'vfl_grand_final',
       'vfl_nord_berlin',
       'vfl_bochum_1848',
       'vfl_halle_1896',
       'vfl_06_benrath',
       'vfl_93_hamburg',
       'vfl_bochum_ii',
       'vfl_07_bremen',
       'vfl_halle_96',
       'vfl_05_heide',
       'vfl_96_halle',
       'vfl_koln_99'],
 'r': ['vfr_schlesien_breslau',
       'vfr_07_schweinfurt',
       'vfr_wormatia_worms',
       'vfr_terminal_chart',
       'vfr_aalen_ii'],
 's': ['vfs_acl_xattr'],
 'v': ['vfv_06_hildesheim'],
 'w': ['vfw_senior_championship',
       'vfw-fokker_h3_sprinter',
       'vfw-fokker_vak_191',
       'vfw_fokker_614',
       'vfw_vak_191b'],
 'x': ['vfx_creative_director']}
