
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_fy = {'fy-1c': 'fengyun',
 'fy-3a': 'fengyun',
 'fyad': 'nigger',
 'fyao': 'florida_young_artists_orchestra',
 'fyb3roptik': 'this_spartan_life',
 'fyborg': 'cyborg',
 'fybromyalgia': 'fibromyalgia',
 'fyco': 'firebird_youth_chinese_orchestra',
 'fyeg': 'federation_of_young_european_greens',
 'fyeo': 'for_your_eyes_only',
 'fyer': 'fyer_language',
 'fygar': 'dig_dug',
 'fygle': 'leknes',
 'fyhs': 'fasman_yeshiva_high_school',
 'fyiv': 'fyifv',
 'fyke': 'fishing_net',
 'fylakion': 'fylakio',
 'fylates': 'thesprotians',
 'fylgia': 'fylgja',
 'fylgjesdalen': 'flesland',
 'fylgjur': 'fylgja',
 'fylgukona': 'fylgja',
 'fylgya': 'fylgja',
 'fylingsdale': 'raf_fylingdales',
 'fylke': 'counties_of_norway',
 'fylker': 'counties_of_norway',
 'fylkesbaatane': 'fjord1_fylkesbaatane',
 'fylkesmann': 'county_governor',
 'fylla': 'fulla',
 'fyllebro': 'battle_of_halmstad',
 'fyne': 'loch_fyne',
 'fyning': 'rogate',
 'fynnoderee': 'fenodyree',
 'fyodora': 'fyodor',
 'fyodorova': 'fyodorov',
 'fyodorovskaya': 'theotokos_of_st._theodore',
 'fyodorovski': 'fyodorovsky',
 'fyodorovskii': 'fyodorovsky',
 'fyodorovskiy': 'fyodorovsky',
 'fyrd': 'leidang',
 'fyrisa': 'fyris',
 'fyrisan': 'fyris',
 'fyrisbadet': 'fyrishov',
 'fyrish': 'fyrish_monument',
 'fyrisvold': 'fyrisvellir',
 'fyrkantsserien': 'fyrkantserien',
 'fyrm': 'republic_of_macedonia',
 'fyrmacedondia': 'republic_of_macedonia',
 'fyrnsidu': 'germanic_neopaganism',
 'fyrom': 'republic_of_macedonia',
 'fysics': 'physics',
 'fysiostigmine': 'physostigmine',
 'fyson': 'philip_furley_fyson',
 'fysop': 'boston_university',
 'fyve': 'fyve_domain',
 'fywh': 'windhoek_hosea_kutako_international_airport'}
        