
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_fs = {'_': ['fs_ashley-cooper',
       'fs_technology',
       'fs_micronesia',
       'fs_trenitalia',
       'fs_martorell',
       'fs_southwest',
       'fs_cartagena',
       'fs_napajedla',
       'fs_mostoles',
       'fs_hamilton',
       'fs_marjata',
       'fs_houston',
       'fs_croatia',
       'fs_aln772',
       'fs_garcia',
       'fs_zamora',
       'fs_cargo',
       'fs_daily',
       'fs_south',
       'fs_flint',
       'fs_rubis',
       'fs_malan',
       'fs_seoul',
       'fs_curie',
       'fs_e.626',
       'fs_oise',
       'fs_eger',
       'fs_e626',
       'fs_e636',
       'fs_ohio',
       'fs_bell',
       'fs_set',
       'fs_688',
       'fs_10',
       'fs_me',
       'fs_x'],
 'a': ['fsa_corporation', 'fsa_voronezh', 'fsa_freedom', 'fsa_card'],
 'b': ['fsbo_madison', 'fsb_academy', 'fsb_ripcord', 'fsbi_medal', 'fsb_coral'],
 'c': ['fsc_15307+3253',
       'fsc_lohfelden',
       'fscte_manston',
       'fsc_northrop',
       'fsc_millport',
       'fsc_rybinsk',
       'fsc_lublin',
       'fsc_star',
       'fsc_zuk'],
 'f': ['fsf/unesco_directory',
       'fsf_directory',
       'fsf_europe',
       'fsf_trophy',
       'fsf_india'],
 'h': ['fshm-torpedo_moscow',
       'fshajt_bridge',
       'fsh_receptor',
       'fshm_moscow',
       'fshv_cup',
       'fsh_604',
       'fsh_605'],
 'i': ['fsi_international', 'fsi_scale'],
 'k': ['fsk_klungkung', 'fsk_markers', 'fsk_rybinsk', 'fsk_marker'],
 'l': ['fsl_lyons'],
 'm': ['fsm-based_programming', 'fsm_beskid', 'fsma_2000'],
 'n': ['fsn_pittsburgh',
       'fsn_northwest',
       'fsn_wisconsin',
       'fsn_southwest',
       'fsn_analysis',
       'fsn_houston',
       'fsn_detroit',
       'fsn_arizona',
       'fsn_chicago',
       'fsn_midwest',
       'fsn_indiana',
       'fsn_florida',
       'fsn_north',
       'fsn_south',
       'fsn_ohio',
       'fsn_west'],
 'o': ['fso_nabarima',
       'fso_warszawa',
       'fso_polonez',
       'fso_syrena',
       'fso_safer'],
 'p': ['fspace_publications', 'fsp_protocol', 'fsp_festival', 'fsp_group'],
 'q': ['fsq_7'],
 'r': ['fsru_independence', 'fsr_tarpan', 'fsr_1758'],
 's': ['fss_code'],
 't': ['fstc_awka'],
 'u': ['fsue_atomflot',
       'fsu_cowgirls',
       'fsu_circus',
       'fsu_hymns',
       'fsu_hyms',
       'fsu_ysp',
       'fsu_rez',
       'fsu_07'],
 'v': ['fsv_ludwigshafen-oggersheim',
       'fsv_krumhermersdorf',
       'fsv_erlangen-bruck',
       'fsv_ludwigshafen',
       'fsv_bergshausen',
       'fsv_jagersburg',
       'fsv_oggersheim',
       'fsv_hollenbach',
       'fsv_bentwisch',
       'fsv_frankfurt',
       'fsv_braunfels',
       'fsv_steinbach',
       'fsv_fernwald',
       'fsv_bayreuth',
       'fsv_salmrohr',
       'fsv_zwickau',
       'fsv_velten']}
