
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_fd = {'_': ['fd-composites_arrowcopter',
       'fd_trinitron/wega',
       'fd-25_defender',
       'fd_mediagroep',
       'fd.o_xserver',
       'fd-1_phantom',
       'fd_trinitron',
       'fd_hrvatska',
       'fd_croatia',
       'fd_benteen',
       'fd_mount',
       'fd_200mm'],
 'a': ['fda_commissioner',
       'fda_preemption',
       'fda_consumer',
       'fda_consum',
       'fda_music'],
 'b': ['fdb_mobler'],
 'd': ['fddi_ring'],
 'e': ['fderik_airport'],
 'g': ['fdgb_pokal', 'fdgb_cup'],
 'h': ['fdh_bank'],
 'i': ['fdic_international',
       'fdic_insurance',
       'fdi_magazine',
       'fdi_stock',
       'fdiv_bug'],
 'm': ['fdm_group'],
 'n': ['fdny_commissioner', 'fdny_necrology', 'fdny_racing'],
 'p': ['fdp.the_liberals'],
 'r': ['fdr_skatepark',
       'fdr_memorial',
       'fdr_library',
       'fdr_drive',
       'fdr_park',
       'fdr_plot'],
 's': ['fdsrcs_england'],
 'u': ['fdu_materials', 'fdu_press']}
