
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_tg = {'_': ['tg-10_peregrine',
       'tg-rash2_mouse',
       'tg_collective',
       'tg-pvr_mouse',
       'tg_hamilton',
       'tg_guingona',
       'tg_sheppard',
       'tg_grammar',
       'tg_millner',
       'tg_bowles',
       'tg_lurgan',
       'tg_jones',
       'tg21_plc',
       'tg_halli',
       'tg_sambo',
       'tg_omori',
       'tg_38.1',
       'tg_11.2',
       'tg_58.3',
       'tg_rage',
       'tg_58.2',
       'tg_38.3',
       'tg_58.4',
       'tg_58.1',
       'tg_38.2',
       'tg_38.4',
       'tg_261',
       'tg_now',
       'tg_114',
       'tg_lee',
       'tg_la7'],
 'a': ['tgag_broad'],
 'f': ['tgf-beta_receptors',
       'tgfb_receptors',
       'tgf-beta_1',
       'tgf_alpha',
       'tgf_beta',
       'tgf_b'],
 'g': ['tggc_outlet', 'tgg_group'],
 'i': ['tgi_fridays'],
 'k': ['tgk_pg'],
 'l': ['tgl_series', 'tgl_co.'],
 'n': ['tgn_atlantic', 'tgn_1412'],
 'o': ['tgo_gbadamosi', 'tgoj_x20'],
 'r': ['tgr_motorsport', 'tgr_foundation', 'tgrt_haber'],
 's': ['tgscom_inc.'],
 'v': ['tgv_haute-picardie',
       'tgv_signalling',
       'tgv_atlantique',
       'tgv_sud-est',
       'tgv_cinemas',
       'tgv_trains',
       'tgv_duplex',
       'tgv_lyria',
       'tgv_inoui',
       'tgv_east',
       'tgv_tmst',
       'tgv_pbka',
       'tgv_est',
       'tgv_pos',
       'tgv_pse',
       'tgv_001'],
 'w': ['tgwu_amalgamations']}
