
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_vb = {'vb-104': 'vpb-104',
 'vb-1b': 'vfa-11',
 'vb-2b': 'vfa-14',
 'vb-3': 'vfa-14',
 'vb-41': 'vfa-14',
 'vb-4m': 'vmfa-232',
 'vb-6m': 'vmtb-132',
 'vb.net': 'visual_basic_.net',
 'vb10': 'vb_10',
 'vba-m': 'visualboyadvance',
 'vba32': 'vba32_antivirus',
 'vbac': 'vaginal_birth_after_caesarean',
 'vbam': 'victory_by_any_means',
 'vbasic': 'visual_basic',
 'vbbs': 'virtual_advanced',
 'vbcps': 'virginia_beach_city_public_schools',
 'vbe/ai': 'vesa_bios_extensions',
 'vbf-17': 'vfa-106',
 'vbf-19': 'vf-114',
 'vbf-20': 'vf-74',
 'vbfa': 'van_buren_first_assembly_of_god',
 'vbied': 'car_bomb',
 'vbios': 'video_bios',
 'vblank': 'vertical_blanking_interval',
 'vblog': 'video_blogging',
 'vblogs': 'video_blogging',
 'vboda': 'virginia_band_and_orchestra_directors_association',
 'vbox': 'virtualbox',
 'vboxmanage': 'virtualbox',
 'vbp1': 'von_hippel-lindau_binding_protein_1',
 'vbras-spungs': 'drepung_monastery',
 'vbrc': 'viral_bioinformatics_resource_center',
 'vbs-1': 'vbs1',
 'vbs.loveletter': 'iloveyou',
 'vbs.loveletter.csi': 'iloveyou',
 'vbs/iloveyou': 'iloveyou',
 'vbs/lovelet': 'iloveyou',
 'vbs/lovelet-a': 'iloveyou',
 'vbs/loveletter': 'iloveyou',
 'vbs/loveletter.a': 'iloveyou',
 'vbsw': 'vigorous_burmese_student_warriors',
 'vbuletin': 'vbulletin',
 'vbulliten': 'vbulletin',
 'vbusiness': 'v-business'}
        