
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_gb = {'_': ['gb2312-80',
       'gb-18030',
       'gb-eire',
       'gb18030',
       'gb-pvr',
       'gb2nlo',
       'gb2312',
       'gb/bhe',
       'gb-tv',
       'gb84',
       'gb-1',
       'gb-4',
       'gb40',
       'gb3'],
 'a': ['gbangbegouine-yati',
       'gbangbegouine',
       'gbaja-biamila',
       'gbameledougo',
       'gbatongouin',
       'gbangbossou',
       'gbangbatoke',
       'gbarpolu-2',
       'gbagbongom',
       'gbaspecial',
       'gbarpolu-1',
       'gbado-lite',
       'gbangbadou',
       'gbarpolu-3',
       'gbakpodji',
       'gbanyamli',
       'gbadamosi',
       'gbalamuya',
       'gbangbale',
       'gbargolay',
       'gbablasso',
       'gbalekaha',
       'gbadolite',
       'gbarpolu',
       'gbakedou',
       'gbapleu',
       'gbadjie',
       'gbandja',
       'gbanlin',
       'gbabshe',
       'gbagbam',
       'gbalahi',
       'gbarnga',
       'gbabire',
       'gbazoa',
       'gbaffo',
       'gbanye',
       'gbagyi',
       'gbanga',
       'gbasp',
       'gbamp',
       'gbawe',
       'gbaya',
       'gbach',
       'gbara',
       'gbadu',
       'gbala',
       'gbako',
       'gba2',
       'gbao',
       'gbar',
       'gbas',
       'gba3',
       'gba1',
       'gbap',
       'gba'],
 'b': ['gbbs', 'gbbf', 'gbbi', 'gbb'],
 'c': ['gbcast', 'gbcs', 'gbcw', 'gbci', 'gbc'],
 'd': ['gbde', 'gbd'],
 'e': ['gberedou-baranama',
       'gberedou/hamana',
       'gbetihindjou',
       'gbegourou',
       'gbendembu',
       'gbekekro',
       'gbeleban',
       'gbessoba',
       'gbehoue',
       'gbetogo',
       'gbelany',
       'gbedin',
       'gbenga',
       'gbelce',
       'gbejna',
       'gbegbe',
       'gbeans',
       'gbeogo',
       'gbelo',
       'gberu',
       'gbeke',
       'gbely',
       'gbeko',
       'gbeho',
       'gbefi',
       'gbedu',
       'gbed',
       'gbe'],
 'f': ['gbfxt', 'gbf1', 'gbfc', 'gbfl', 'gbf'],
 'g': ['gbgt1', 'gbg'],
 'h': ['gbhgis', 'gbhb', 'gbhs', 'gbh'],
 'i': ['gbits/sec',
       'gbingue',
       'gbinti',
       'gbiska',
       'gbitma',
       'gbisd',
       'gbiti',
       'gbit',
       'gbic',
       'gbif',
       'gbi'],
 'j': ['gbj'],
 'k': ['gbk'],
 'l': ['gbledi-agbogame',
       'gbld-345',
       'gblx.net',
       'gbliglo',
       'gblon',
       'gbla',
       'gblx',
       'gblt',
       'gbl'],
 'm': ['gbms', 'gbmd', 'gbmc', 'gbm'],
 'n': ['gbn'],
 'o': ['gbofesso-sama',
       'gbolouville',
       'gbokopeteme',
       'gbon-houye',
       'gbozounme',
       'gbongaha',
       'gbolahan',
       'gbogolo',
       'gbonyin',
       'gboguhe',
       'gbongan',
       'gbokle',
       'gboard',
       'gbowtr',
       'gbonne',
       'gbook',
       'gboyo',
       'gbowr',
       'gboko',
       'gbob',
       'gbon',
       'gboh',
       'gbo'],
 'p': ['gbp510', 'gbpec', 'gbps', 'gbp1', 'gbp5', 'gbp2', 'gbp'],
 'q': ['gbq'],
 'r': ['gbr-12909',
       'gbr-13069',
       'gbr-12935',
       'gbr-13098',
       'gbr-13119',
       'gbr-12783',
       'gbrimani',
       'gbrowser',
       'gbridge',
       'gbrimah',
       'gbrmpa',
       'gbra',
       'gbrf',
       'gbr'],
 's': ['gbsd', 'gbs'],
 't': ['gbtw', 'gbta', 'gbtc', 'gbt'],
 'u': ['gbulahagu',
       'gbu-44/b',
       'gbu-43/b',
       'gbu-1/b',
       'gbulung',
       'gbu-32',
       'gbu-24',
       'gbu-54',
       'gbudwe',
       'gbu-15',
       'gbu-28',
       'gbu-43',
       'gbu-37',
       'gbu-27',
       'gbu-12',
       'gbu-31',
       'gbu-16',
       'gbu-39',
       'gbu-36',
       'gbugli',
       'gbu-38',
       'gbu-10',
       'gbu-44',
       'gbu-29',
       'gbuy',
       'gbur',
       'gbu'],
 'v': ['gbv-c', 'gbv'],
 'w': ['gbwc', 'gbw'],
 'x': ['gbxml', 'gbx2', 'gbx'],
 'y': ['gbytes/sec', 'gbytes', 'gbyso', 'gbyte', 'gbyd', 'gby'],
 'z': ['gbz']}
