
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_gm = {'_': ['gm2700/3000',
       'gm-gruppen',
       'gm-allison',
       'gm-avtovaz',
       'gm-holden',
       'gm16v265',
       'gm-csf-r',
       'gm-5975',
       'gm-611',
       'gm-352',
       'gm-emd',
       'gm-csf',
       'gm-hm',
       'gm10b',
       'gm100',
       'gm-94',
       'gm.tv',
       'gm10',
       'gm2a',
       'gm6c',
       'gm-1',
       'gm2',
       'gm1',
       'gm3'],
 'a': ['gmail.google.com/',
       'gmail.google.com',
       'gmail/features',
       'gmail/history',
       'gmailgoogle',
       'gmanews.tv',
       'gmaildrive',
       'gmailswap',
       'gmane.org',
       'gmail.com',
       'gmajnica',
       'gmarket',
       'gmailfs',
       'gma950',
       'gmassa',
       'gmabit',
       'gmajna',
       'gmachl',
       'gma-7',
       'gmail',
       'gmane',
       'gmats',
       'gmask',
       'gmacs',
       'gmat',
       'gmac',
       'gmai',
       'gmaj',
       'gmax',
       'gmaa',
       'gmad',
       'gmaw',
       'gman',
       'gma'],
 'b': ['gmbc', 'gmba', 'gmb'],
 'c': ['gmc-yukon', 'gmc-4', 'gmcsf', 'gmcl1', 'gmca', 'gmc'],
 'd': ['gmdh-3', 'gmdnm', 'gmdat', 'gmdss', 'gmdh', 'gmdd', 'gmds', 'gmd'],
 'e': ['gmelinoides',
       'gmelanone',
       'gmelinite',
       'gmeinder',
       'gmelinol',
       'gmelinka',
       'gmeiner',
       'gmelina',
       'gmelin',
       'gmeb1',
       'gmeb2',
       'gmer',
       'gmes',
       'gme'],
 'f': ['gmfc', 'gmfo', 'gmfn', 'gmfa', 'gmf'],
 'g': ['gmgpl', 'gmg'],
 'h': ['gmhc', 'gmhm', 'gmhl', 'gmhs', 'gmhp', 'gmh'],
 'i': ['gminsidenews',
       'gminas',
       'gming',
       'gminy',
       'gmiri',
       'gmina',
       'gmiss',
       'gmita',
       'gmici',
       'gmii',
       'gmit',
       'gmi'],
 'j': ['gmjahl', 'gmjhl', 'gmj'],
 'k': ['gmk'],
 'l': ['gmlcmd', 'gml-1', 'gmlrs', 'gml10', 'gmlc', 'gmls', 'gml'],
 'm': ['gmmrp',
       'gmmtv',
       'gmmx',
       'gmmn',
       'gmml',
       'gmmy',
       'gmmi',
       'gmms',
       'gmmr',
       'gmm'],
 'n': ['gmnn', 'gmn'],
 'o': ['gmo-free', 'gmobile', 'gmogala', 'gmosaic', 'gmod', 'gmo'],
 'p': ['gmplayer',
       'gmp-140',
       'gmp140',
       'gmpcs',
       'gmpte',
       'gmppb',
       'gmpta',
       'gmpls',
       'gmpi',
       'gmpc',
       'gmps',
       'gmp'],
 'r': ['gmroii', 'gmres', 'gmroi', 'gmrc', 'gmrp', 'gmrs', 'gmrt', 'gmr'],
 's': ['gmsarn', 'gms-4', 'gmsc', 'gmst', 'gmsh', 'gms'],
 't': ['gmtv.co.uk',
       'gmt-5:00',
       'gmt-0:25',
       'gmt-9:30',
       'gmt-2:30',
       'gmt-3:30',
       'gmtjahl',
       'gmt355',
       'gmt360',
       'gmt400',
       'gmt-10',
       'gmt800',
       'gmt-12',
       'gmt900',
       'gmtjhl',
       'gmt-11',
       'gmtv2',
       'gmt-5',
       'gmtv3',
       'gmt-4',
       'gmt-6',
       'gmt-7',
       'gmt-8',
       'gmt-3',
       'gmt-2',
       'gmtv1',
       'gmt-9',
       'gmt-1',
       'gmti',
       'gmta',
       'gmtv',
       'gmt'],
 'u': ['gmurowo', 'gmunden', 'gmund', 'gmur', 'gmul', 'gmu'],
 'v': ['gmv'],
 'w': ['gmwatch.org', 'gmwatch', 'gmwda', 'gmw'],
 'x': ['gmx.net', 'gmx'],
 'y': ['gmyrdek', 'gmy'],
 'z': ['gmz']}
