
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_bs = {'bs_albert_odyssey': 'albert_odyssey',
 'bs_detective_club': 'bs_tantei_club:_yuki_ni_kieta_kako',
 'bs_en_3': 'en_3',
 'bs_en_60309-2': 'iec_60309',
 'bs_energy_braunschweig': 'new_yorker_phantoms_braunschweig',
 'bs_fire_emblem': 'bs_fire_emblem:_akaneia_senki',
 'bs_kanaderu_convert': 'ongaku_tsukuru:_kanadeeru',
 'bs_sutte_hakkun': 'sutte_hakkun',
 'bs_tantei_club': 'bs_tantei_club:_yuki_ni_kieta_kako',
 'bs_wizardry_v': 'wizardry_v:_heart_of_the_maelstrom',
 'bsa_1926_thompson': 'thompson_submachine_gun',
 'bsa_a65_spitfire': 'bsa_spitfire',
 'bsa_membership_controversy': 'boy_scouts_of_america_membership_controversies',
 'bsa_rocket_3': 'bsa_rocket_3/triumph_trident',
 'bsa_scout_car': 'daimler_dingo',
 'bsa_shooting_star': 'bsa_a7',
 'bsa_star_twin': 'bsa_a7',
 'bsa_tower_1': 'the_bsa_twin_towers_at_st._francis_square',
 'bsa_twin_tower': 'the_bsa_twin_towers_at_st._francis_square',
 'bsa_twin_towers': 'the_bsa_twin_towers_at_st._francis_square',
 'bsa_victor_special': 'bsa_b44_shooting_star',
 'bsd_documentation_license': 'freebsd_documentation_license',
 'bsd_is_dying': 'slashdot',
 'bsd_socket_api': 'berkeley_sockets',
 'bsd_sockets_api': 'berkeley_sockets',
 'bsdi_vs_usl': 'usl_v._bsdi',
 'bsec_business_council': 'organization_of_the_black_sea_economic_cooperation',
 'bsg_chemie_leipzig': 'fc_sachsen_leipzig',
 'bsg_motor_eberswalde': 'fv_motor_eberswalde',
 'bsg_motor_karl-marx-stadt': 'chemnitzer_fc',
 'bsg_motor_zwickau': 'fsv_zwickau',
 'bsg_rotation_dresden': 'dresdner_sc',
 'bsg_sachsenring_zwickau': 'fsv_zwickau',
 'bsg_turbine_halle': 'hallescher_fc',
 'bsg_waggonbau_dessau': 'sv_dessau_05',
 'bsg_westende_hamborn': 'westende_hamborn',
 'bsg_wismut_aue': 'fc_erzgebirge_aue',
 'bsi_love_you': 'b.s._i_love_you',
 'bsi_product_services': 'bsi_group',
 'bspn_deportes_radio': 'espn_deportes_radio',
 'bspn_on_abc': 'espn_on_abc',
 'bspn_the_magazine': 'espn_the_magazine',
 'bss_group_plc': 'bss_group',
 'bsv_1892_berlin': 'berliner_sv',
 'bsv_92_berlin': 'berliner_sv',
 'bsv_98_bayreuth': 'fsv_bayreuth',
 'bsv_stahl_brandeburg': 'stahl_brandenburg',
 'bsv_stahl_brandenburg': 'stahl_brandenburg'}
        