
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_jm = {'jm_3100': 'plerixafor',
 'jm_aitken': 'james_macrae_aitken',
 'jm_appel': 'jacob_m._appel',
 'jm_barrie': 'j._m._barrie',
 'jm_coetzee': 'j._m._coetzee',
 'jm_cohen': 'j._m._cohen',
 'jm_dematteis': 'j._m._dematteis',
 'jm_dent': 'j._m._dent',
 'jm_flagg': 'james_montgomery_flagg',
 'jm_gates': 'j._m._gates',
 'jm_gordon': 'j._m._gordon',
 'jm_gully': 'james_manby_gully',
 'jm_hogg': 'james_mcgarel-hogg',
 'jm_howard': 'john_morgan_howard',
 'jm_humphrey': 'j._m._humphrey',
 'jm_johnson': 'j._m._johnson',
 'jm_kemp': 'justin_kemp',
 'jm_kerrigan': 'j._m._kerrigan',
 'jm_keynes': 'john_maynard_keynes',
 'jm_langtry': 'j._m._langtry',
 'jm_ledgard': 'j._m._ledgard',
 'jm_lexus': 'jm_family_enterprises',
 'jm_lofficier': 'jean-marc_lofficier',
 'jm_marauder': 'b-26_marauder',
 'jm_ravi': 'jayam_ravi',
 'jm_robertson': 'john_m._robertson',
 'jm_snyder': 'j.m._snyder',
 'jm_synge': 'john_millington_synge',
 'jm_wallace-hadrill': 'j._m._wallace-hadrill',
 'jm_wave': 'jmwave',
 'jm_weston': 'j._m._weston',
 'jm_whorton': 'j._m._whorton',
 'jmak_equation': 'avrami_equation',
 'jmb_competition': 'jmb_racing',
 'jmc_airlines': 'jmc_air',
 'jmc_landwind': 'jiangling_motors_landwind',
 'jmd_coey': 'michael_coey',
 'jme_editor': 'jme_molecule_editor',
 'jme_mctaggart': 'j._m._e._mctaggart',
 'jmj_fletcher': 'j._m._j._fletcher',
 'jmj_records': 'jam_master_jay_records',
 'jml_direct': 'jml_direct_tv',
 'jmr_parrondo': 'j._m._r._parrondo',
 'jms_careless': 'j._m._s._careless',
 'jmu_dukes': 'james_madison_dukes',
 'jmw_turner': 'j._m._w._turner'}
        