#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# AUTO-GENERATED CONTENT
d_stem_lj = {'lja': {'ljas': []},
             'ljabl': {'ljable': []},
             'ljame': {'ljames': []},
             'ljanguag': {'ljanguage': []},
             'ljanuari': {'ljanuary': []},
             'ljaw': {'ljaws': []},
             'ljawyer': {'ljawyers': []},
             'ljberdad': {'ljberdade': []},
             'ljberti': {'ljberty': []},
             'ljbrari': {'ljbrary': []},
             'ljcida': {'ljcidas': []},
             'ljcurgu': {'ljcurgus': []},
             'lje': {'ljeing': [], 'ljes': []},
             'ljecam': {'ljecame': []},
             'ljecaus': {'ljecause': []},
             'ljecom': {'ljecome': []},
             'ljefor': {'ljefore': []},
             'ljeliev': {'ljelieve': []},
             'ljeliu': {'ljelius': []},
             'ljeschi': {'ljeschie': []},
             'ljespit': {'ljespite': []},
             'ljetopi': {'ljetopis': []},
             'lji': {'ljis': [], 'ljy': []},
             'ljin': {'ljins': []},
             'ljj': {'ljjs': []},
             'ljkeli': {'ljkely': []},
             'ljl': {'ljls': []},
             'ljlb': {'ljlbs': []},
             'ljm': {'ljms': []},
             'ljmit': {'ljmits': []},
             'ljne': {'ljnes': []},
             'ljnite': {'ljnited': []},
             'ljnivers': {'ljniversity': []},
             'ljo': {'ljos': []},
             'ljodi': {'ljody': []},
             'ljoen': {'ljoenes': []},
             'ljolj': {'ljolje': []},
             'ljon': {'ljons': []},
             'ljone': {'ljones': []},
             'ljong': {'ljongs': []},
             'ljook': {'ljooking': [], 'ljooks': []},
             'ljorent': {'ljorente': []},
             'ljot': {'ljots': []},
             'ljp': {'ljps': []},
             'ljterari': {'ljterary': []},
             'lju': {'ljus': []},
             'ljuba': {'ljubas': []},
             'ljubarski': {'ljubarsky': []},
             'ljuben': {'ljubenic': []},
             'ljubes': {'ljubesic': []},
             'ljubibrat': {'ljubibratic': []},
             'ljubic': {'ljubice': [], 'ljubicic': []},
             'ljubijank': {'ljubijankic': []},
             'ljubinj': {'ljubinje': []},
             'ljubinkov': {'ljubinkovic': []},
             'ljubinski': {'ljubinsky': []},
             'ljubisavljev': {'ljubisavljevic': []},
             'ljubivoj': {'ljubivoje': []},
             'ljubljan': {'ljubljane': []},
             'ljubojev': {'ljubojevic': []},
             'ljubov': {'ljubovic': []},
             'ljudj': {'ljudje': []},
             'ljudsk': {'ljudske': []},
             'ljuli': {'ljuly': []},
             'ljungar': {'ljungars': []},
             'ljungberg': {'ljungbergs': []},
             'ljungbi': {'ljungby': []},
             'ljungbyh': {'ljungbyhed': []},
             'ljunghal': {'ljunghall': []},
             'ljungskil': {'ljungskile': []},
             'ljungstrom': {'ljungstroms': []},
             'ljure': {'ljuring': []},
             'ljuri': {'ljury': []},
             'ljusar': {'ljusare': []},
             'ljuset': {'ljusets': []},
             'ljusn': {'ljusne': []},
             'ljusned': {'ljusnedal': []},
             'ljust': {'ljusted': []},
             'ljutom': {'ljutomer': []},
             'ljve': {'ljves': []},
             'ljvi': {'ljvy': []}}
