
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ns = {'_': ['ns-toetungsanstalt_grafeneck',
       'ns-totungsanstalt_grafeneck',
       'ns/ep_telecommunications',
       'ns_kamporganisasjon',
       'ns_railinfratrust',
       'ns_international',
       'ns_ramachandran',
       'ns_manedshefte',
       'ns2-3_protease',
       'ns5b_inhibitor',
       'ns_motorcycle',
       'ns_pascagoula',
       'ns_ramaswami',
       'ns_solutions',
       'ns_brukkaros',
       'ns_krishanan',
       'ns_sevmorput',
       'ns_structure',
       'ns_diagrams',
       'ns_krishnan',
       'ns_stations',
       'ns_madhavan',
       'ns_argentia',
       'ns_elephant',
       'ns_savannah',
       'ns_hispeed',
       'ns_everett',
       'ns_mayport',
       'ns_concord',
       'ns_norfolk',
       'ns_diagram',
       'ns_rajaram',
       'ns_railway',
       'ns_groton',
       'ns_4551-1',
       'ns_joseph',
       'ns_daures',
       'ns_puppis',
       'ns0_cell',
       'ns_power',
       'ns_dd-ar',
       'ns_basic',
       'ns_rehab',
       'ns_1900',
       'ns_virm',
       'ns_line',
       'ns_ural',
       'ns_4300',
       'ns_5600',
       'ns_3300',
       'ns_spca',
       'ns_3500',
       'ns_3400',
       'ns_5000',
       'ns_3850',
       'ns_7100',
       'ns_mura',
       'ns_3700',
       'ns_5300',
       'ns_4000',
       'ns_6000',
       'ns_6100',
       'ns_3600',
       'ns_7700',
       'ns_8500',
       'ns_3900',
       'ns_7600',
       'ns_93',
       'ns_fa'],
 'a': ['nsaid_nephropathy',
       'nsa_cryptography',
       'nsambya_hospital',
       'nsaka_university',
       'nsa_wiretapping',
       'nsa_controversy',
       'nsanje_district',
       'nsanje_airport',
       'nsama_district',
       'nsap_address',
       'nsang_dilong',
       'nsana_simon',
       'nsala_soup',
       'nsa_linux',
       'nsah_mala',
       'nsa_key'],
 'b': ['nsb_gardermobanen',
       'nsbhs_bookroom',
       'nsb_biltrafikk',
       'nsb_eiendom',
       'nsb_agenda',
       'nsb_napoli',
       'nsb_wlab-2',
       'nsb_gods',
       'nsb_el11',
       'nsb_bm64',
       'nsb_bm65',
       'nsb_el15',
       'nsb_el14',
       'nsb_bm86',
       'nsb_bm92',
       'nsb_bm66',
       'nsb_el13',
       'nsb_bm70',
       'nsb_bm68',
       'nsb_bm62',
       'nsb_el18',
       'nsb_bm93',
       'nsb_el16',
       'nsb_bm88',
       'nsb_bm83',
       'nsb_bm73',
       'nsb_bm67',
       'nsb_bm69',
       'nsb_bm89',
       'nsb_bm72',
       'nsb_bm91',
       'nsb_el17',
       'nsb_bm87',
       'nsb_di6',
       'nsb_el3',
       'nsb_el8',
       'nsb_di5',
       'nsb_el9',
       'nsb_di8',
       'nsb_di2',
       'nsb_di3',
       'nsb_b5'],
 'c': ['nscad_university',
       'nscb_airport',
       'nsc_nijkerk',
       'nsc_601316',
       'nsc_united',
       'nsc_177382',
       'nsc_deputy',
       'nsc_162/2',
       'nsc_bose',
       'nsc_tv',
       'nsc_68'],
 'd': ['nsd_powerball'],
 'e': ['nsenga_language',
       'nsea_protector',
       'nsei_language',
       'nse_ekpenyong',
       'nsenga_people',
       'nse_ikpe-etim',
       'nsep_office',
       'nse_indices',
       'nse_emerge',
       'nsel_case',
       'nse_ufot'],
 'f': ['nsf_international', 'nsf_thurmont', 'nsf_grfp', 'nsf_fee'],
 'g': ['nsg_mouse'],
 'h': ['nshan_beshiktashlian',
       'nshan_topouzian',
       'nshan_erzrumyan',
       'nshan_munchyan'],
 'i': ['nsimba_webster',
       'nsiika,_uganda',
       'nsite_software',
       'nsikak_eduok',
       'nsima_ekere',
       'nsiah_asare',
       'nsima_peter',
       'nsi_runavik',
       'nsis_media',
       'nsi_kwilu'],
 'k': ['nsk_olimpiyskyi', 'nsk_ltd.'],
 'l': ['nsl_services', 'nsl_group', 'nsl_buses', 'nsl_cup'],
 'm': ['nsmb_wii'],
 'o': ['nsongo_language',
       'nsom_microscopy',
       'nsoko_airfield',
       'nsong_village',
       'nso_language',
       'nso_people',
       'nso_spirit',
       'nso_group',
       'nsong_hq'],
 'p': ['nspd_51'],
 'r': ['nsrdc_bqm-108', 'nsrgnts_rmxs', 'nsr_125'],
 's': ['nss_annapolis',
       'nssl_doppler',
       'nss_number',
       'nsss_inc.',
       'nssm_200',
       'nssdc_id',
       'nsss_inc',
       'nss_6',
       'nss_7'],
 't': ['nstg_warnsdorf',
       'nstigate_games',
       'nst_minimum',
       'nstg_aussig',
       'nstg_asch'],
 'u': ['nsungwe_formation',
       'nsu_motorenwerke',
       'nsu_challenge',
       'nsumbu_mazuwa',
       'nsukka_group',
       'nsu_sulmobil',
       'nsu_quickly',
       'nsu_station',
       'nsu_spider',
       'nsu_alumni',
       'nsu_prinz',
       'nsu_ro80',
       'nsu_tts',
       'nsu_k70',
       'nsu_ok',
       'nsu_ag'],
 'v': ['nsvs_14256825',
       'nsv_chitthan',
       'nsv_23218',
       'nsv_20797',
       'nsv_14515',
       'nsv_14715',
       'nsv_1436'],
 'w': ['nswrfl_premiership',
       'nswrl_premiership',
       'nsw_parliament',
       'nsw_government',
       'nswc_dahlgren',
       'nsw_ambulance',
       'nsw_trainlink',
       'nsw_lotteries',
       'nsw_planning',
       'nsw_gridiron',
       'nsw_patriots',
       'nsw_waratahs',
       'nsw/act_rams',
       'nsw_maritime',
       'nsw_marines',
       'nsw-act_u18',
       'nsw_wallaby',
       'nsw_number',
       'nsw_police',
       'nsw_swifts',
       'nsw_greens',
       'nsw_rugby',
       'nsw_corps',
       'nsw_kiama',
       'nsw_pride',
       'nsw_burra',
       'nsw_prime',
       'nsw_blues',
       'nsw_tafe',
       'nsw_open',
       'nsw_hsc',
       'nsw_cup',
       'nsw_rfs',
       'nsw_ses',
       'nsw_src'],
 'y': ['nsync_discography'],
 'z': ['nszz_solidarity', 'nszan_munczian']}
