
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_nf = {'_': ['nf-kappa-b-activating_protein',
       'nf_magazine',
       'nf_simpson',
       'nf_browser',
       'nf_sonata',
       'nf_board',
       'nf_2'],
 'a': ['nfa_minimization', 'nfat_uavs'],
 'c': ['nfc_championship',
       'nfc_central',
       'nfc_norris',
       'nfc_south',
       'nfc_north',
       'nfc_east',
       'nfc_west'],
 'i': ['nfi_group', 'nfilm_hd'],
 'l': ['nfl_championships',
       'nfl_thanksgiving',
       'nfl_cheerleaders',
       'nfl_championship',
       'nfl_quarterbacks',
       'nfl_cheerleading',
       'nfl_quarterback',
       'nfl_cheerleader',
       'nfl_properties',
       'nfl_superbowls',
       'nfl_scoreboard',
       'nfl_experience',
       'nfl_challenge',
       'nfl_countdown',
       'nfl_slimetime',
       'nfl_mini-camp',
       'nfl_nicknames',
       'nfl_nationals',
       'nfl_preseason',
       'nfl_rivalries',
       'nfl_primetime',
       'nfl_playoffs',
       'nfl_insiders',
       'nfl_classics',
       'nfl_showdown',
       'nfl_captains',
       'nfl_superpro',
       'nfl_stadiums',
       'nfl_rejects',
       'nfl_matchup',
       'nfl_redzone',
       'nfl_rosters',
       'nfl_lockout',
       'nfl_seasons',
       'nfl_combine',
       'nfl_gameday',
       'nfl_country',
       'nfl_records',
       'nfl_network',
       'nfl_2night',
       'nfl_xtreme',
       'nfl_europe',
       'nfl_honors',
       'nfl_replay',
       'nflpa_game',
       'nfl_canada',
       'nfl_series',
       'nfl_street',
       'nfl_staffs',
       'nfl_alumni',
       'nfl_owners',
       'nfl_europa',
       'nfl_london',
       'nfl_films',
       'nfl_rules',
       'nfl_today',
       'nfl_blitz',
       'nfl_fever',
       'nfl_draft',
       'nfl_tour',
       'nfl_ties',
       'nfl_film',
       'nfl_dpoy',
       'nfl_live',
       'nfl_lore',
       'nfl_mvp',
       'nfl_cup',
       "nfl_'97",
       'nfl_2k1',
       'nfl_hof',
       'nfl_2k2',
       'nfl_2k3',
       "nfl_'95",
       'nfl_2k5',
       'nfl_am',
       'nfl_ta',
       'nfl_2k',
       'nfl_u.',
       'nfl_uk',
       'nfl_u'],
 'o': ['nforce_700', 'nforce_500', 'nforce_600', 'nforce_4', 'nforce_3'],
 'p': ['nfp-labour_coalition',
       'nfpa_1123',
       'nfpa_1001',
       'nfpa_1600',
       'nfpa_1006',
       'nfpa_1901',
       'nfpa_1670',
       'nfpa_704',
       'nfpa_805',
       'nfpa_921',
       'nfpa_70b',
       'nfpa_70e',
       'nfpa_70',
       'nfpa_72'],
 's': ['nfs:most_wanted',
       'nfs_underground',
       'nfs:_undercover',
       'nfs_undercover',
       'nfs:_prostreet',
       'nfs_prostreet',
       'nfs:_carbon',
       'nfs_carbon',
       'nfs:_shift',
       'nfs_nitro',
       'nfs_world',
       'nfs_shift',
       'nfs_plot',
       'nfs_hp2',
       'nfs:_u2',
       'nfs:_ps',
       'nfs:_mw',
       'nfs_11',
       'nfs_ii',
       'nfs_uc',
       'nfs_mw',
       'nfs_wo',
       'nfsu_2',
       'nfs_xi',
       'nfs_6',
       'nfs_4',
       'nfs_3',
       'nfs_5',
       'nfs_7',
       'nfs_2'],
 't': ['nfta_fleet'],
 'u': ['nfu_mutual'],
 'w': ['nfw_e.ii', 'nfw_e.i']}
