
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_cw = {'_': ['cw-structure',
       'cw-complex',
       'cw4kids',
       'cw-pair',
       'cw-wham',
       'cw-33',
       'cw-21',
       'cw-tv',
       'cw-25',
       'cw11',
       'cw39',
       'cw57',
       'cw50',
       'cw44',
       'cw46',
       'cw27',
       'cw2',
       'cw4',
       'cw3',
       'cw1'],
 'a': ['cwangayana',
       'cwatset',
       'cwacom',
       'cwarme',
       'cwalk',
       'cwags',
       'cwat',
       'cwas',
       'cwal',
       'cwac',
       'cwa'],
 'b': ['cwbl', 'cwb'],
 'c': ['cwchey', 'cwcap', 'cwc15', 'cwcb', 'cwc'],
 'd': ['cwdhs', 'cwdb', 'cwdm', 'cwd'],
 'e': ['cwenthryth',
       'cwenland',
       'cwenburh',
       'cwens',
       'cweet',
       'cwezi',
       'cweb',
       'cwen',
       'cwe'],
 'f': ['cwff', 'cwfa', 'cwf'],
 'g': ['cwgc', 'cwg'],
 'h': ['cwhuang', 'cwh'],
 'i': ['cwikly-krajewo',
       'cwikly-rupie',
       'cwikielnia',
       'cwietalka',
       'cwiklinek',
       'cwierdzin',
       'cwiklice',
       'cwiercie',
       'cwichelm',
       'cwiersk',
       'cwiklin',
       'cwikla',
       'cwikow',
       'cwi-2',
       'cwins',
       'cwis',
       'cwik',
       'cwin',
       'cwid',
       'cwi'],
 'k': ['cwkyt', 'cwkr', 'cwks', 'cwk'],
 'l': ['cwlth', 'cwlp', 'cwlb', 'cwl'],
 'm': ['cwm-felin-fach',
       'cwm-yr-eglwys',
       'cwmrhydyceirw',
       'cwmcarnhywel',
       'cwmcoednerth',
       'cwmfelinfach',
       'cwmllynfell',
       'cwmsychbant',
       'cwmpengraig',
       'cwmynyscoy',
       'cwmdauddwr',
       'cwmtillery',
       'cwmystwyth',
       'cwmhiraeth',
       'cwmpennar',
       'cwm-y-glo',
       'cwmsymlog',
       'cwmbrwyno',
       'cwmgwrach',
       'cwmcarvan',
       'cwmamman',
       'cwmffrwd',
       'cwmgwili',
       'cwmfelin',
       'cwmerfyn',
       'cwmgiedd',
       'cwmbwrla',
       'cwm-hwnt',
       'cwmtwrch',
       'cwmwysg',
       'cwmgors',
       'cwmifor',
       'cwmaman',
       'cwmduad',
       'cwmdare',
       'cwmbach',
       'cwmtawe',
       'cwmderi',
       'cwmafan',
       'cwmafon',
       'cwmcidi',
       'cwmcarn',
       'cwmparc',
       'cwmcych',
       'cwmbran',
       'cwmavon',
       'cwmars',
       'cwmdar',
       'cwmann',
       'cwmyoy',
       'cwmwd',
       'cwmdu',
       'cwmry',
       'cwmp',
       'cwm'],
 'n': ['cwnrhydyceirw', 'cwna', 'cwne', 'cwnu', 'cwn'],
 'o': ['cwoenthryth', 'cwot', 'cwop', 'cwoa', 'cwo'],
 'p': ['cwpt', 'cwp1', 'cwp'],
 'r': ['cwrt-y-gollen',
       'cwrtnewydd',
       'cwrtmawr',
       'cwrsync',
       'cwry',
       'cwrn',
       'cwru',
       'cwrw',
       'cwr'],
 's': ['cwsdpmi', 'cwsf', 'cwsp', 'cwsu', 'cws'],
 't': ['cwtch', 'cwts', 'cwt.', 'cwt'],
 'u': ['cwuaa', 'cwu45', 'cwu'],
 'v': ['cwv'],
 'w': ['cww'],
 'x': ['cwx'],
 'y': ['cwyllog', 'cwyfan', 'cwy']}
