
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_cm = {'_': ['cm-32_armoured_vehicle',
       'cm32_armoured_vehicle',
       'cm.173_super_magister',
       'cm-21_armored_vehicle',
       'cm_labs_simulations',
       'cm_padmanabhan_nair',
       'cm-11_brave_tiger',
       'cm_russell_museum',
       'cm_postcode_area',
       'cm_ashok_sekhar',
       'cm_postal_area',
       'cm_shafi_sami',
       'cm_draconis_c',
       'cm_phase_ii'],
 'a': ['cma_cgm_bougainville',
       'cmas**_scuba_diver',
       'cma_music_festival',
       'cma_cgm_normandie',
       'cma_cgm_kerguelen',
       'cmas*_scuba_diver',
       'cma_cgm_butterfly',
       'cma_cgm_laperouse',
       'cma_cgm_magellan',
       'cma_cgm_thalassa',
       'cma_cgm_medea',
       'cma_cgm_tower',
       'cma_cgm_vela'],
 'b': ['cmbt_metro_station', 'cmb_cold_spot'],
 'c': ['cmc_connect_burson-marsteller',
       'cmc_magnetics_corporation',
       'cmc_music_awards'],
 'd': ['cmd_fd_series'],
 'e': ['cme_group_inc.'],
 'h': ['cmh_masjid_jhelum'],
 'i': ['cmielow_porcelain_works',
       'cmic_project_management',
       'cmic_music_awards'],
 'j': ['cmj_new_music'],
 'l': ['cmll-reina_international_championship',
       'cmll_universal_championship',
       'cmll_leyendas_mexicanas',
       'cmll_super_viernes',
       'cmll_juicio_final',
       'cmll_sin_salida'],
 'm': ['cmmism_project_planning', 'cmmg_mk47_mutant'],
 'o': ['cmos_image_sensor'],
 'p': ["cmp-n,n'-diacetyllegionaminic_acid_synthase",
       'cmp-sialic_acid_transporter',
       'cmp_game_group'],
 'r': ['cmr_central,_visakhapatnam'],
 's': ['cmsu_multipurpose_building',
       'cms_energy_corporation',
       'cms_yorkshire_league',
       'cms_college_kottayam',
       'cms_cameron_mckenna',
       'cmsd_whitney_young',
       'cms_grammar_school',
       'cms_file_system',
       'cms_made_simple'],
 't': ["cmt's_next_superstar",
       'cmt_invitation_only',
       'cmt_cross_country',
       'cmt_music_awards',
       'cmt_pure_country',
       'cmt_comedy_stage',
       'cmt_music_award',
       'cmt_music_fest',
       'cmt_hot_twenty',
       'cmt_front_row'],
 'u': ['cmu_pronouncing_dictionary',
       'cmu_public_television',
       'cmu_2nd_hospital',
       'cmu_common_lisp'],
 'v': ['cmv_infectious_mononucleosis', 'cmv_antenatal_infection'],
 'y': ['cmyk_color_separations',
       'cmyk_colour_model',
       'cmyk_color_model',
       'cmyk_color_space',
       'cmy_color_model']}
