
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_tb = {'_': ['tb2l_2015-16_season',
       'tb_ackerson_company',
       'tb_devil_rays',
       'tb_skin_test',
       'tb_in_china'],
 'a': ['tbaeng_meanchey_district', 'tbaeng_mean_chey'],
 'c': ['tbc_radio_network', 'tbc_brass_band'],
 'e': ['tbeng_mean_chey'],
 'f': ['tbf5_protein_domain'],
 'i': ['tbilisi_aerospace_manufacturing',
       'tbilisi_aircraft_manufacturing',
       'tbilisi_international_airport',
       'tbilisi_state_conservatoire',
       'tbilisi_state_conservatory',
       'tbilisi_hijacking_incident',
       'tbilisi_spiritual_seminary',
       'tbilisi_botanical_gardens',
       'tbilisi_assembly_building',
       'tbilisi_botanical_garden',
       'tbilisi_state_university',
       'tbilisi_sameba_cathedral',
       'tbilisi_sioni_cathedral',
       'tbilisi_medical_academy',
       'tbilisi_railway_station',
       'tbilisi_regional_league',
       'tbilisi_marriott_hotel',
       'tbilisi_sports_palace',
       'tbilisi_jazz_festival',
       'tbilisi_city_assembly',
       'tbilisi_national_park',
       'tbilisi_appeal_court',
       'tbilisi_city_council',
       'tbilisi_fashion_week',
       'tbilisi_film_studio',
       'tbilisi_art_gallery',
       'tbilisi_city_hall',
       'tbilisi_open_air'],
 'n': ['tbn_enlace_usa', 'tbn_tampa_bay'],
 'o': ['tboung_khmom_district',
       'tboung_khmum_district',
       'tboung_khmum_province',
       'tbong_khmom_district',
       'tbong_khmum_district',
       'tbong_kmom_district',
       'tbong_khmum_fc'],
 's': ['tbs_universiteti_rc', 'tbs_bus_terminus', 'tbs_mlb_sunday'],
 't': ['tbt_hospital_gboko'],
 'u': ['tbuong_kmoum_district'],
 'y': ['tby_sea_wolf']}
