
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_tl = {'_': ["tl'etinqox-t'in_government_office",
       "tl'esqox_first_nation",
       'tl_ultralight_condor'],
 'a': ['tlahuelilpan_pipeline_explosion',
       'tlaltecatzin_of_cuauhchinanco',
       'tlaxco_municipality,_tlaxcala',
       'tlacolulita_zapotec_language',
       'tlalnepantla_railway_station',
       'tlaxco_municipality,_puebla',
       'tla-o-qui-aht_first_nations',
       'tlatlasikwala_first_nation',
       'tla-o-qui-aht_first_nation',
       'tlacoquemecatl_arts_garden',
       'tlahtoani_of_tenochtitlan',
       'tlatoani_of_tenochtitlan',
       'tla_players_championship',
       'tlatelolco_metro_station',
       'tlatelolco,_mexico_city',
       'tlaltenco_metro_station',
       'tlaxcala_city_cathedral',
       'tla_entertainment_group',
       'tlacolula_de_matamoros',
       'tlatoani_of_tlatelolco',
       'tlahualilo_de_zaragoza',
       'tlacuilas_y_retrateras',
       "tlaloc's_leopard_frog",
       'tlahuac_metro_station',
       'tlalixtac_de_cabrera',
       'tlajomulco_de_zuniga',
       'tlatoani_of_texcoco',
       'tlacotepec_de_mejia',
       'tlalnepantla_de_baz',
       'tlatoque_of_texcoco',
       'tlaconete_con_barba',
       'tlapa_de_comonfort',
       'tlazala_de_fabela',
       'tlacote_el_bajo',
       'tlacote_el_alto'],
 'c': ['tlc_casino_enterprises', 'tlc_2016_tour'],
 'e': ['tlevak_strait-suemez_island', 'tlemcen_national_park'],
 'i': ['tlicho_all-season_road',
       'tlicho_yatii_language',
       'tlikakila_wild_river',
       'tli_cho_government'],
 'o': ['tlokwe_local_municipality',
       'tlomackie_street,_warsaw',
       'tloz:_twilight_princess',
       'tloz:_phantom_hourglass',
       'tlowitsis_first_nation',
       'tloz_phantom_hourglass'],
 's': ['tls_termination_proxy'],
 'u': ['tluszcz_railway_station', 'tluszcz,_makow_county'],
 'y': ['tlyustenkhablskoye_urban_settlement']}
