
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ds = {'_': ['ds/cft_correspondence',
       'ds_accessories',
       'ds_automobiles',
       'ds_satyaranjan',
       'ds_andromedae',
       'ds_senanayake',
       'ds9_episodes',
       'ds_attygalle',
       'ds9_relaunch',
       'ds_atkinson',
       'ds_division',
       'ds_homebrew',
       'ds_tucanae',
       'ds_browser',
       'ds_series',
       'ds_fanboy',
       'ds_warner',
       'ds_crucis',
       'ds_corvus',
       'ds_mirsky',
       'ds_games',
       'ds_ideas',
       'ds_minsk',
       'ds_orkla',
       'ds_linux',
       'ds_style',
       'ds_donau',
       'ds_logon',
       'ds_field',
       'ds_smith',
       'ds_light',
       'ds_2089',
       'ds_phat',
       'ds_lite',
       'ds_5ls',
       'ds_air',
       'ds_4s',
       'ds_1',
       'ds_6',
       'ds_9',
       'ds_3',
       'ds_4',
       'ds_5'],
 'a': ['dsa_antananarivo', 'dsa_bulldogs', 'dsa_myanmar'],
 'b': ['dsb_congress',
       'dsbn_academy',
       'dsb_oresund',
       'dsbv_punch',
       'dsb_groep',
       'dsb_bank',
       'dsb_my',
       'dsb_mx'],
 'c': ['dsc_wanne-eickel',
       'dschinghis_khan',
       'dschiu_dschitsu',
       'dschang_airport',
       'dschingis_khan',
       'dsch_motif',
       'dscs_iii',
       'dsc_t-1',
       'dscs_3'],
 'd': ['dsdna-rt_virus', 'dsdna_viruses', 'dsdp_368', 'dsdp_367', 'dsd_ac-3'],
 'e': ['dser_20'],
 'f': ['dsfa_records', 'dsf_europe'],
 'g': ['dsg_international', 'dsg_gearbox', 'dsge_model'],
 'h': ['dshamilja_kaiser', 'dshon_forbes', 'dshk_1938'],
 'i': ['dsinezumi_shrew',
       'dsign_music',
       'dsi_points',
       'dsi_colors',
       'dsi_point',
       'dsi_games'],
 'k': ['dsk_duster', 'dsk_group', 'dsk_bank', 'dsk_hyp'],
 'l': ['dsl_modem/router',
       'dsl_splitter',
       'dsl_gateway',
       'dsl_marlins',
       'dslr_camera',
       'dsl_pirates',
       'dsl_dodgers',
       'dsl_filter',
       'dsl_giants',
       'dsl_router',
       'dsl_astros',
       'dsl_angels',
       'dsl_braves',
       'dsl_linux',
       'dsl_modem',
       'dsl_rings',
       'dsl_sport',
       'dsl_mets'],
 'm': ['dsm-iv_codes', 'dsm-iv_tr', 'dsm_iv-tr', 'dsm_iv', 'dsm_cc', 'dsm_4'],
 'n': ['dsn_corporation', 'dsn_music'],
 'o': ['dso_ratio'],
 'p': ['dsp_entertainment',
       'dsp_satellites',
       'dsp_satellite',
       'dsp/bios_link',
       'dsp_coupling',
       'dspnano_rtos',
       'dspg_telecom',
       'dspace_gmbh',
       'dsp_media',
       'dsp_group',
       'dsp_chip',
       'dsp_dev'],
 'q': ['dsq_software'],
 'r': ['dsr-precision_dsr-50',
       'dsr-precision_dsr-1',
       'dsr_proteus-eretes',
       'dsrv-2_avalon',
       'dsrv-1_mystic',
       'dsrna_virus',
       'dsra_rna',
       'dsr_1'],
 's': ['dssam_model', 'dss_haarlem', 'dss_f.c.', 'dss_80'],
 't': ['dst_international',
       'dst_systems',
       'dst_global',
       'dst_group',
       'dst_index',
       'dst_time'],
 'v': ['dsv_concordia',
       'dsv-3_turtle',
       'dsv_shinkai',
       'dsv-2_alvin',
       'dsv_alpine',
       'dsv-5_nemo',
       'dsv_leoben',
       'dsv_turtle',
       'dsv_wagons',
       'dsv_alvin',
       'dsv_posen',
       'dsv_wagon',
       'dsv_saaz'],
 'w': ['dsw_entertainment', 'dsw_algorithm', 'dsw_roster']}
