
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ds = {'_': ['ds-xtreme',
       'ds-p1-yu',
       'ds80c390',
       'ds:style',
       'ds4ever',
       'ds-101',
       'ds4/na',
       'ds2000',
       'ds-825',
       'ds-air',
       'ds4seq',
       'ds-102',
       'ds-13',
       'ds-22',
       'ds-39',
       'ds-16',
       'ds420',
       'ds-ss',
       'ds825',
       'ds-9',
       'ds13',
       'ds0a',
       'ds-1',
       'ds-3',
       'ds0',
       'ds2',
       'ds3',
       'ds1',
       'ds7',
       'ds6',
       'ds5',
       'ds9',
       'ds4'],
 'a': ['dsacdad',
       'dsausa',
       'dsatur',
       'dsamun',
       'dsap',
       'dsac',
       'dsai',
       'dsat',
       'dsa'],
 'b': ['dsbfirst',
       'dsb-am',
       'dsb-sc',
       'dsbsc',
       'dsbe',
       'dsbn',
       'dsbl',
       'dsbc',
       'dsba',
       'dsbx',
       'dsb'],
 'c': ['dscdbuilder',
       'dsc-qx100',
       'dsc-t100',
       'dschagga',
       'dsc-s600',
       'dschubba',
       'dsc-qx10',
       'dsc-p120',
       'dsc-w200',
       'dsc-t300',
       'dsc-w100',
       'dsc-f717',
       'dsc-f828',
       'dschang',
       'dsc-t25',
       'dsc-p92',
       'dsc-p52',
       'dsc-f88',
       'dsc-p73',
       'dsc-w50',
       'dsc-s90',
       'dsc-p72',
       'dsc-f55',
       'dsc-w35',
       'dsc-w30',
       'dsc-w55',
       'dsc-u30',
       'dsc-u60',
       'dsc-t10',
       'dsc-p12',
       'dscanal',
       'dsc-p32',
       'dsc-w5',
       'dsc-t1',
       'dsc-t5',
       'dsc-v3',
       'dscovr',
       'dsc-w7',
       'dsc-r1',
       'dsc-p8',
       'dsc-m1',
       'dsc-w1',
       'dsc-t3',
       'dsc-t7',
       'dsc-v1',
       'dscr1',
       'dscam',
       'dsc1',
       'dsch',
       'dscb',
       'dscr',
       'dscp',
       'dscs',
       'dsci',
       'dsc2',
       'dsca',
       'dsc3',
       'dscc',
       'dscn',
       'dsc'],
 'd': ['dsdna', 'dsds', 'dsdv', 'dsda', 'dsdl', 'dsdp', 'dsdm', 'dsd'],
 'e': ['dse-alpha',
       'dselect',
       'dsekh',
       'dsear',
       'dsegh',
       'dseep',
       'dsea',
       'dsei',
       'dse'],
 'f': ['dsfargeg', 'dsfslrp', 'dsfrs', 'dsfl', 'dsfa', 'dsfn', 'dsfc', 'dsf'],
 'g': ['dsge', 'dsgi', 'dsg3', 'dsg1', 'dsg2', 'dsg'],
 'h': ['dshield',
       'dshkes',
       'dsharp',
       'dshell',
       'dshke',
       'dshkm',
       'dshow',
       'dshb',
       'dshs',
       'dshk',
       'dsht',
       'dsh'],
 'i': ['dsiware', 'dsip', 'dsir', 'dsif', 'dsi'],
 'j': ['dsj'],
 'k': ['dsknectd', 'dsky', 'dsk'],
 'l': ['dslreports',
       'dslinux',
       'dslayer',
       'dslala',
       'dslink',
       'dslite',
       'dslam',
       'dslr',
       'dsl2',
       'dsl'],
 'm': ['dsma-notice',
       'dsm-iii-r',
       'dsm-iv-tr',
       'dsmvwllng',
       'dsmvwlng',
       'dsm-iii',
       'dsmlv2',
       'dsm-ii',
       'dsm-cc',
       'dsm-iv',
       'dsm-i',
       'dsmem',
       'dsmcc',
       'dsm-5',
       'dsmiv',
       'dsmlt',
       'dsma1',
       'dsml2',
       'dsmb',
       'dsm4',
       'dsmz',
       'dsmc',
       'dsml',
       'dsm'],
 'n': ['dsniff', 'dsn-2', 'dsn1', 'dsny', 'dsng', 'dsn'],
 'o': ['dsongarian',
       'dsorashen',
       'dsongaria',
       'dsongars',
       'dsongar',
       'dsound',
       'dsotr',
       'dsotm',
       'dsopk',
       'dsoc',
       'dsoa',
       'dsos',
       'dso'],
 'p': ['dsp-2230',
       'dsplayer',
       'dspic33f',
       'dspic30',
       'dspace',
       'dsp-23',
       'dsp-4',
       'dspca',
       'dspg2',
       'dsp-1',
       'dsph',
       'dspd',
       'dspe',
       'dspc',
       'dspa',
       'dspg',
       'dsps',
       'dspt',
       'dsp1',
       'dspf',
       'dsp'],
 'q': ['dsquared2', 'dsquared', 'dsquare2', 'dsquare', 'dsqi', 'dsq'],
 'r': ['dsrflow',
       'dsred',
       'dsr-1',
       'dsrr',
       'dsrp',
       'dsrm',
       'dsrl',
       'dsrs',
       'dsrc',
       'dsr'],
 's': ['dssa/spx',
       'dssccd',
       'dss-49',
       'dssat',
       'dss80',
       'dssim',
       'dsssl',
       'dssam',
       'dssp',
       'dssi',
       'dssu',
       'dss2',
       'dsss',
       'dssc',
       'dsst',
       'dssq',
       'dss1',
       'dssa',
       'dss'],
 't': ['dstore',
       'dstld',
       'dsts',
       'dsta',
       'dsto',
       'dstn',
       'dstc',
       'dstt',
       'dstl',
       'dstv',
       'dst'],
 'u': ['dsungaripteroidea',
       'dsungaripteridae',
       'dsungaripterus',
       'dsuunmod',
       'dsungars',
       'dsu/csu',
       'dsungar',
       'dsus',
       'dsub',
       'dsup',
       'dsu'],
 'v': ['dsv-0', 'dsv-3', 'dsvii', 'dsv-4', 'dsv-2', 'dsv-1', 'dsvd', 'dsv'],
 'w': ['dsw'],
 'x': ['dsx'],
 'y': ['dsylexia', 'dsy'],
 'z': ['dsz']}
