
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_jy = {'_': ['jy_cell_line'],
 'e': ['jyestharya_of_sambhupura'],
 'l': ['jyllands-posten_mohammad_controversy',
       'jyllands-posten_muhammad_controversy',
       'jyllands-posten_muhammad_caricatures',
       'jyllands-posten_cartoon_controversy',
       'jyllandsposten_cartoon_controversy',
       'jyllands-posten_muhammad_cartoons',
       'jyllands-posten_muhammad_cartoon',
       'jylgyndy_forest_reserve'],
 'o': ['jyotiraditya_mahadevrai_scindia',
       'jyotiraditya_madhavrao_scindia',
       'jyotirindra_bodhipriya_larma',
       'jyothika_sadanah_saravanan',
       'jyotiranjan_srichandan_ray',
       'jyothy_kendriya_vidyalaya',
       'jyotinder_singh_randhawa',
       'jyoti_bhusan_chatterjea',
       'jyotirmay_singh_mahato',
       'jyoti_prasad_agarwalla',
       'jyoti_bhushan_banerji',
       'jyoti_jyoti_mahajyoti',
       'jyoti_prasad_agarwala',
       'jyothi_surekha_vennam',
       'jyoti_prasad_rajkhowa',
       'jyoti_prakash_nirala',
       'jyoti_prakash_tamang',
       'jyotindra_nath_dixit',
       'jyotsna_keshav_bhole',
       'jyoti_nivas_college',
       'jyotiba_phule_nagar',
       'jyoti_prakash_dutta',
       'jyotiba_rao_scindia',
       'jyoti_class_tanker',
       'jyoti_bhusan_chaki',
       'jyothi_high_school',
       'jyoti_kirit_parikh',
       'jyoti_sunita_kullu',
       'jyoti_kumar_sinha',
       'jyoti_ann_burrett',
       'jyoti_prasad_das',
       'jyoti_bane_jwala',
       'jyoti_kapur_das',
       'jyoti_rao_phule'],
 'p': ['jyp_entertainment_discography', 'jyp_ht_jyvaskyla'],
 'r': ['jyrki_jarvilehto_lehto', 'jyrki_j.j._kasvi'],
 's': ['jyske_bank_boxen'],
 't': ['jython_programming_language', 'jytte_reichstein_nilsson'],
 'u': ['jyuuken_sentai_gekiranger',
       'jyuken_sentai_gekiranger',
       'jyushin_thunder_lyger',
       'jyuki_ningen_jumbor',
       'jyu_jik_chuyhn',
       'jyu_oh_sei'],
 'v': ['jyvaskyla_university_library',
       'jyvaskylan_seudun_palloseura',
       'jyvaskyla_library_stabbing',
       'jyvaskyla_central_station',
       'jyvaskyla_rail_accident',
       'jyvaskyla_arts_festival',
       'jyvaskyla_city_theatre']}
