
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_q_ = {'_': ['q._fabius_rullianus',
       'q._titurius_sabinus',
       'q._servilius_caepio',
       'q._lollius_urbicus',
       'q3_academy_langley',
       'q._fufius_calenus',
       'q3_academy_tipton',
       'q0957_plus_561a/b',
       'q._todd_dickinson',
       'q!_film_festival',
       'q._j._stephenson',
       'q._curtius_rufus',
       'q9_input_method',
       'q._david_bowers',
       'q0957_plus_561a',
       'q._allan_brocka',
       'q0957_plus_561b',
       'q0957_plus_561',
       'q6_trivia_game',
       'q._rev._biol.',
       'q._a._gilmore',
       'q-1_eridani_b',
       'q0957_561_a/b',
       'q0957_561_ab',
       'q7_wind_farm',
       'q1_eridani_b',
       'q._d._leavis',
       'q._t._honey',
       'q0957_561_b',
       'q0957_561_a',
       'q_100.7_fm',
       'q._t._hush',
       'q._v._lowe',
       'q._e._d.',
       'q_&_q'],
 'a': ['q&a_comedy_website',
       'q3a_panel_house',
       'q_allan_brocka',
       'q_awards_2008'],
 'b': ['q-ball:_billiards_master', 'q-bec_my_love'],
 'c': ['q-cytochrome_c_oxidoreductase',
       'q_christian_fellowship',
       'q-class_melbourne_tram',
       'q_class_destroyer'],
 'd': ['q_division_records', 'q_division_studios', 'q_d_leavis', 'q_da_fool'],
 'e': ['q_e_d'],
 'l': ['q_link_wireless'],
 'm': ['q_multimedia_console'],
 'p': ['q_public_license', 'q_pootle_5'],
 'r': ['q_radio_belfast', 'q_radio_network'],
 's': ["q's_jook_joint"],
 't': ['q-tip_production_discography',
       'q-type_calcium_channel',
       'q_television_network',
       'q_t_hush'],
 'v': ["q'viva!_the_chosen"],
 'w': ['q_with_stroke', 'q_without_u', 'q_with_hook']}
