import libcst

class Visitor(libcst.CSTVisitor): ...

class Transformer(libcst.CSTTransformer):
    def __init__(self, visitor) -> None: ...
    def leave_Attribute(self, original_node: Attribute, updated_node: Attribute) -> BaseExpression: ...
