
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-21T10:46:34+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2240870a936977f6b9e7e16a168c7545ec9afb2b",
 "version": "2.0.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
