
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_wn = {'_': ['wn_colquitt',
       'wn_herbert',
       'wn_cobbold',
       'wn_hodgson',
       'wn_star',
       'wn_9007'],
 'a': ['wnas_radio'],
 'b': ['wnba_championship',
       'wnba_attendance',
       'wnba_champions',
       'wnba_playoffs',
       'wnba_tuesdays',
       'wnba_rosters',
       'wnbl_records',
       'wnba_records',
       'wnba_tuesday',
       'wnba_finals',
       'wnbl_finals',
       'wnba_draft',
       'wnbc_radio',
       'wnb_tower',
       'wnb_tavur',
       'wnba_mvp',
       'wnbt_tv',
       'wnbc_4'],
 'c': ['wncaa_tournament',
       'wnc_championship',
       'wnc_object',
       'wncn_tower',
       'wncr_fm',
       'wnc_4'],
 'd': ['wnd_books'],
 'e': ['wnep_anchors', 'wnet_idents', 'wnew_1130', 'wnec_law'],
 'f': ['wnf_342'],
 'n': ['wnnj_fm'],
 'p': ['wnp_barbellion'],
 't': ['wnt4_deficiency',
       'wnt_proteins',
       'wnt_pathway',
       'wnt_signals',
       'wnt_beckett',
       'wnt_protein'],
 'u': ['wnur_sports'],
 'w': ['wnwo_tower'],
 'y': ['wnyc_studios', 'wnyc_radio']}
