
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_wg = {'_': ['wg_ellison-macartney',
       'wg_collingwood',
       'wg_rutherford',
       'wg_richardson',
       'wg_griffiths',
       'wg_hoskins',
       'wg_godfrey',
       'wg_bagnall',
       'wg_curtis',
       'wg_walden',
       'wg_sebald',
       'wg_granet',
       'wg_ernst',
       'wg_craig',
       'wg_grace',
       'wg_film',
       'wg_fay'],
 'a': ['wga_strike', 'wga_awards', 'wga_award', 'wga_study'],
 'b': ['wgbh_idents', 'wgbh_boston'],
 'c': ['wgc-bridgestone_invitational',
       'wgc-nec_invitational',
       'wgc-ca_championship',
       'wgc-hsbc_champions',
       'wgc_invitational',
       'wgc_championship',
       'wgc_f.c.'],
 'h': ['wghp_fox8'],
 'l': ['wgl_holdings', 'wglq_fm'],
 'm': ['wgmu_radio', 'wgme_13'],
 'n': ['wgn_superstation',
       'wgns_recordings',
       'wgns_records',
       'wgns_am-1450',
       'wgn_america',
       'wgn_sports'],
 'p': ['wgpl,_lexington', 'wgp_k-1'],
 'q': ['wgqr_fm'],
 'r': ['wgr_sprague'],
 's': ['wgs_72', 'wgs_64', 'wgs_60', 'wgs_84'],
 'u': ['wgu_indiana'],
 'y': ['wgy_television'],
 'z': ['wgz_bank']}
