
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_hf = {'_': ['hf118_turbofan',
       'hf_productions',
       'hf_foundation',
       'hf_rosenbusch',
       'hf_maceration',
       'hf_verwoerd',
       'hf-24_marut',
       'hf_ahmanson',
       'hf_stephens',
       'hf_ponsonby',
       'hf_samuels',
       'hf_lenfest',
       'hf_thynne',
       'hf_fisher',
       'hf_baker',
       'hf_radio',
       'hf_ellis',
       'hf_laser',
       'hf_acid'],
 'b': ['hfb_hansajet'],
 'c': ['hfc_network',
       'hfc_haarlem',
       'hfc_chemie',
       'hfc_smith',
       'hfc_bank',
       'hfc_edo',
       'hfc_32',
       'hfc_23'],
 'k': ['hfk_prievidza', 'hfk_prerov', 'hfk_trebic'],
 'm': ['hfm_prescott'],
 'q': ['hfq_protein'],
 'r': ['hfr_strain', 'hfr_cell'],
 's': ['hfs_incorporated', 'hfs_plus'],
 'v': ['hfv_browser'],
 'x': ['hfx_broadcasting']}
