
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_bf = {'_': ['bf-109_fighter',
       'bf2c_goshawk',
       'bf_hastings',
       'bf_goodrich',
       'bf_skinner',
       'bf_orionis',
       'bf_antliae',
       'bf_shelton',
       'bf_heroes',
       'bf_falcon',
       'bf_theory',
       'bf_model',
       'bf_2142',
       'bf_1942',
       'bf_reed',
       'bf:bc_2',
       'bf_108',
       'bf:_bc',
       'bf_109',
       'bf_110',
       'bf:_v',
       'bf_2'],
 'b': ['bfbs_lisburn'],
 'c': ['bfc_norden-west',
       'bfc_daugavpils',
       'bfc_nordstern',
       'bfc_frankfurt',
       'bfc_preussen',
       'bfc_sudring',
       'bfc_goshawk',
       'bfc_dynamo',
       'bfc_siofok'],
 'f': ['bff_girls'],
 'g': ['bfg_technologies', 'bfgs_method', 'bfg_9000', 'bfg_4'],
 'i': ['bfi_screenonline',
       'bfi_southbank',
       'bfi_flipside',
       'bfi_gallery',
       'bfi_canada',
       'bfi_imax',
       'bfi_100'],
 'l': ['bflix_movies', 'bfl_group'],
 'm': ['bfm_business',
       'bfme2_rotwk',
       'bfm_regions',
       'bfm_89.9',
       'bfme_ii',
       'bfm_tv',
       'bfme_2'],
 'o': ['bford_9'],
 'r': ['bfr_algorithm'],
 's': ['bfs_algorithm', 'bfs_nummer', 'bfs_group'],
 'w': ['bfw_flamingo',
       'bfw_m.17',
       'bfw_m.23',
       'bfw_m.21',
       'bfw_m.22',
       'bfw_m.18',
       'bfw_m.35',
       'bfw_m.29',
       'bfw_m.31',
       'bfw_cl.i',
       'bfw_m.19',
       'bfw_m.36',
       'bfw_m.26',
       'bfw_m.20',
       'bfw_m.24',
       'bfw_m.27',
       'bfw_n.i',
       'bfw_m23',
       'bfw_22']}
