
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_ua = {'ua_175': 'united_airlines_flight_175',
 'ua_232': 'united_airlines_flight_232',
 'ua_93': 'united_airlines_flight_93',
 'ua_briain': 'brian_boru',
 'ua_cinemas': 'regal_entertainment_group',
 'ua_fairbanks': 'university_of_alaska_fairbanks',
 'ua_fanthorp': 'u._a._fanthorpe',
 'ua_fanthorpe': 'u._a._fanthorpe',
 'ua_pou': 'ua_pu',
 'ua_records': 'united_artists_records',
 'ua_sedan': 'cs_sedan_ardennes',
 'ua_sedan-torcy': 'cs_sedan_ardennes',
 'ua_smirnov': 'u._a._smirnov',
 'ua_string': 'user_agent',
 'ua_strings': 'user_agent',
 'ua_zit': 'wadjet',
 'uaap_71': 'uaap_season_71',
 'uaap_72': 'uaap_season_72',
 'uab/walker_college': 'bevill_state_community_college',
 'uab_meto': 'atoni',
 'uac_nigeria': 'united_africa_company_of_nigeria',
 'uac_platform': 'united_american_committee',
 'uacca_kazombiaze': 'uakazuwaka_kazombiaze',
 'uae_airforce': 'united_arab_emirates_air_force',
 'uae_army': 'united_arab_emirates_army',
 'uae_culture': 'culture_of_the_united_arab_emirates',
 'uae_currency': 'united_arab_emirates_dirham',
 'uae_dirham': 'united_arab_emirates_dirham',
 'uae_government': 'politics_of_the_united_arab_emirates',
 'uae_league': 'uae_football_league',
 'uae_money': 'united_arab_emirates_dirham',
 'uae_music': 'music_of_the_united_arab_emirates',
 'uae_passport': 'emirati_passport',
 'uag_tecos': 'estudiantes_tecos',
 'uah_hockey': 'alabama-huntsville_chargers_ice_hockey',
 'ual_232': 'united_airlines_flight_232',
 'ual_93': 'united_airlines_flight_93',
 'ual_corp.': 'ual_corporation',
 'ualr_trojans': 'arkansas-little_rock_trojans',
 'uame_church': 'union_american_methodist_episcopal_church',
 'uapou_maculata': 'uapou',
 'uarctic_atlas': 'university_of_the_arctic_atlas',
 'uart_overrun': 'universal_asynchronous_receiver/transmitter',
 'uas_states': 'u.s._state',
 'uasin_gishu': 'uasin_gishu_district',
 'uate_akuila': 'akuila_uate',
 'uav_corporation': 'uav_corp.',
 'uav_cypher': 'sikorsky_cypher',
 'uav_endurance': 'unmanned_aerial_vehicle',
 'uav_entertainment': 'uav_corp.',
 'uaw-daimlerchrysler_400': 'shelby_427',
 'uaw-dodge_400': 'shelby_427',
 'uaw-ford_500': 'amp_energy_500',
 'uay_chivo': 'huay_chivo',
 'uaz_69': 'gaz-69'}
        