
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_iz = {'iz_al-din_al-qassam': 'izz_ad-din_al-qassam_brigades',
 'izaac_walton_league': 'izaak_walton_league',
 'izaak_jakubowicz_synagogue': 'izaak_synagogue',
 'izaak_m._kolthoff': 'izaak_kolthoff',
 'izaak_maurits_kolthoff': 'izaak_kolthoff',
 'izaak_walton_killiam': 'izaak_walton_killam',
 'izabela_jaruga_nowacka': 'izabela_jaruga-nowacka',
 'izanagi_and_izanami': 'izanagi',
 'izasa_choisai_ienao': 'iizasa_ienao',
 'izbica_kujawska_commune': 'gmina_izbica_kujawska',
 'izbica_transit_camp': 'izbica_concentration_camp',
 'izhar_ul_haq': 'muhammad_izhar_ul_haq',
 'izhevsk_machine-building_factory': 'izhevsk_mechanical_works',
 'izhevsky_zavod_izhevsk': 'fc_izhevsk',
 'izhorskiye_zavody_oao': 'izhorskiye_zavody',
 'izidore_k._musallam': 'izidore_musallam',
 'iziko_sa_museum': 'iziko_south_african_museum',
 'izmail_class_battlecruiser': 'borodino_class_battlecruiser',
 'izmailovo_urban_forest': 'izmaylovsky_park',
 'izmir_air_station': 'izmir_air_base',
 'izmir_hava_yollari': 'izair',
 'izod_impact_test': 'izod_impact_strength_test',
 'izola_ware_curry': 'izola_curry',
 'izora_rhodes_armstead': 'izora_armstead',
 'izrael_ben_eliezer': 'baal_shem_tov',
 'izrail_moiseevich_gelfand': 'israel_gelfand',
 'izu_hakone_railway': 'izuhakone_railway',
 'izu_no_odoriko': 'the_dancing_girl_of_izu',
 'izudin_dadi_dervic': 'izudin_dervic',
 'izumi_and_meroko': 'full_moon_o_sagashite',
 'izumi_shikibu_nikki': 'izumi_shikibu',
 'izumo_taishakyo_mission': 'izumo_taishakyo_mission_of_hawaii',
 'izuna_unemployed_ninja': 'izuna:_legend_of_the_unemployed_ninja',
 'izuogu_z_600': 'izuogu_z-600',
 'izvesti_tsik_islands': 'izvestiy_tsik_islands',
 'izz_ad-din_al-qassam': 'izz_ad-din_al-qassam_brigades',
 'izz_ad-din_el-kasam': 'izz_ad-din_al-qassam_brigades',
 'izz_ad-din_el-kassam': 'izz_ad-din_al-qassam_brigades',
 'izz_al-din_al-qassam': 'izz_ad-din_al-qassam',
 'izz_al-din_al-qassem': 'izz_ad-din_al-qassam_brigades',
 'izz_al-din_kaykaus': 'kaykaus_ii',
 'izz_al-din_osama': 'izz_al-din_usama',
 'izz_al-din_salim': 'ezzedine_salim',
 'izz_el-din_al-qassam': 'izz_ad-din_al-qassam_brigades',
 'izzadin_al_qassam': 'izz_ad-din_al-qassam_brigades',
 'izzat_ibrahim_al-douri': 'izzat_ibrahim_ad-douri',
 'izzat_ibrahim_al-duri': 'izzat_ibrahim_ad-douri',
 'izzat_ibrahim_duri': 'izzat_ibrahim_ad-douri',
 'izzat_muhammad_darwaza': 'izzat_darwaza',
 'izze_beverage_company': 'izze',
 'izzeddin_keykavus_i': 'kaykaus_i',
 'izzeddin_keykavus_ii': 'kaykaus_ii',
 'izzedine_al_qassam': 'izz_ad-din_al-qassam_brigades'}
        