
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_dk = {'_': ['dk_audikesavulu',
       'dk_chakrabarti',
       'dk_publishing',
       'dk_pattammal',
       'dk_lacertae',
       'dk_kennedys',
       'dk_broster',
       'dk_metcalf',
       'dk_ulrich',
       'dk_bongos',
       'dk_naiker',
       'dk_taknet',
       'dk_tyagi',
       'dk_adult',
       'dk1_rigs',
       'dk_holm',
       'dk_ceti',
       'dk_jamz',
       'dk_rap',
       'dk_jet',
       'dk_lac',
       'dk_64'],
 'a': ['dka_smolensk'],
 'b': ['dkb_group', 'dkb_ghana'],
 'e': ['dke_pong'],
 'i': ['dki_jakarta', 'dki_jaya'],
 'm': ['dkm_schleswig-holstein',
       'dkm_scharnhorst',
       'dkm_deutschland',
       'dkm_gneisenau',
       'dkm_kormoran',
       'dkm_bismarck',
       'dkm_luetzow',
       'dkm_tirpitz',
       'dkm_lutzow'],
 'r': ['dkr_engineering'],
 't': ['dkt_international'],
 'v': ['dkv_joventut'],
 'w': ['dkw_schnellaster',
       'dkw_junior',
       'dkw_munga',
       'dkw_monza',
       'dkw_f103',
       'dkw_f102',
       'dkw_f11',
       'dkw_750',
       'dkw_f89',
       'dkw_f12',
       'dkw_3=6',
       'dkw_f10',
       'dkw_f4',
       'dkw_f5',
       'dkw_f7',
       'dkw_f8',
       'dkw_f9',
       'dkw_f1',
       'dkw_f2']}
