
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_td = {'_': ['td_crittenden',
       'td_securities',
       'td_ameritrade',
       'td_waterhouse',
       'td_overdrive',
       'td_banknorth',
       'td2n_gorgon',
       'td_kendrick',
       'td_ballpark',
       'td3n_gorgon',
       'td_learning',
       'td_mischke',
       'td_madison',
       'td_bingham',
       'td_station',
       'td_synnex',
       'td_barnes',
       'td1_24679',
       'td_centre',
       'td_weldon',
       'td_little',
       'td1_31081',
       'td1_25656',
       'td_allman',
       'td_canada',
       'td_status',
       'td_lambda',
       'td_garden',
       'td_arena',
       'td_tower',
       'td_place',
       'td_daily',
       'td_judah',
       'td_cruze',
       'td_jakes',
       'td1_816',
       'td_visa',
       'td_bank',
       'td_cars'],
 'a': ['tda_armements'],
 'b': ['tdbanknorth_center', 'tdbanknorth_garden'],
 'c': ['tdc_games', 'tdc_group', 'tdc_a/s'],
 'e': ['tdecu_stadium'],
 'f': ['tdf_group', 'tdf_ghar', 'tdf_2', 'tdf_1'],
 'g': ['tdg_limited'],
 'i': ['tdi_characters', 'tdi_episodes', 'tdi_vector', 'tdi_kriss'],
 'k': ['tdk_kabushiki-kaisha',
       'tdk_electronics',
       'tdk_corporation',
       'tdk_macassette',
       'tdk_shinwakai',
       'tdk_akita',
       'tdk_corp',
       'tdk_s.c.',
       'tdk_sc'],
 'l': ['tdl_group', 'tdlr_5', 'tdlr_4'],
 'm': ['tdm-to-packet_conversion', 'tdma_is-136', 'tdm_switch', 'tdm_bus'],
 'o': ['tdo_connector'],
 'p': ['tdp_lamp', 'tdp_43'],
 'r': ['tdrs_records', 'tdr_targets', 'tdr_capital', 'tdrs_music'],
 's': ['tdshop.it_livorno',
       'tds_metrocom',
       'tds_telecom',
       'tds_racing',
       'tds_2004'],
 'u': ['tdu-12/b_skydart'],
 'v': ['tdv_2200'],
 'w': ['tdw_nomads'],
 'x': ['tdx_power', 'tdx_group']}
