
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_tf = {'_': ['tf1-television_francaise',
       'tf2000-class_destroyer',
       'tf_thistleton-dyer',
       'tf_bourdillon',
       'tf5_motorway',
       'tf_middleton',
       'tf1_motorway',
       'tf_algorithm',
       'tf-19_wasp',
       'tf_carrier',
       'tf_kelsall',
       'tf_bayonet',
       'tf-1_cell',
       'tf_bayard',
       'tf1_group',
       'tf_models',
       'tf1_tower',
       'tf_powys',
       'tf_sport',
       'tf_simon',
       'tf_green',
       'tf_south',
       'tf_150',
       'tf_16',
       'tf_58',
       'tf_38',
       'tf_17',
       'tf_11',
       'tf_2'],
 'd': ['tfd_music'],
 'f': ['tff_cup'],
 'h': ['tfh_publications'],
 'i': ['tfi_international', 'tfilat_haderech', 'tfilat_haderekh', 'tfi_friday'],
 'l': ['tfl_rail'],
 'n': ['tfn_group'],
 'o': ['tforce_freight', 'tfou_tv'],
 'p': ['tfp_deficiency'],
 's': ['tfs_mississauga'],
 't': ['tft_display', 'tft_screen', 'tft_racing', 'tft_gamut', 'tft_lcd'],
 'u': ['tful_282'],
 'x': ['tfx_program'],
 'y': ['tfyr_macedonia']}
