
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_dz = {'_': ['dz_bank_building', 'dz_comedy_show', 'dz_bank_ag'],
 'a': ['dzaoudzi-pamandzi_international_airport',
       'dzanga-sangha_special_reserve',
       'dzanga-ndoki_national_park',
       'dzao_min_language',
       'dza_ili_bu'],
 'b': ['dzban,_masovian_voivodeship',
       'dzbenin,_gmina_troszyn',
       'dzbenin,_gmina_rzekun'],
 'e': ['dzerzhinsky_prospekt,_novosibirsk',
       'dzerzhinsky_district,_novosibirsk',
       'dzerzhinskoye,_krasnoyarsk_krai',
       'dzerzhinsky_district,_russia',
       'dzerzhinsky_military_academy',
       'dzerzhinskiy_city_district',
       'dzerzhinskii_city_district',
       'dzerzhinsky,_moscow_oblast',
       'dzerjinskiy_city_district',
       'dzerzhinski_city_district',
       'dzerjinskii_city_district',
       'dzerzhinsky_city_district',
       'dzerjinsky_city_district',
       'dzerzhinets_nizhny_tagil',
       'dzerjinski_city_district',
       'dzeliwe_of_swaziland',
       'dzeliwe_of_eswatini',
       'dzeko_&_torres'],
 'h': ['dzhoisubani_achaemenid_seal',
       'dzhokhar_musayevich_dudayev',
       'dzhokhar_dudayev_battalion',
       'dzheyrakh_rural_settlement',
       'dzhabar_rasulovich_rasulov',
       'dzherginsky_nature_reserve',
       'dzhendo_stoyanov_dzhendov',
       'dzhankoi_railway_station',
       'dzhugdzur_nature_reserve',
       'dzhuma_mosque,_tashkent',
       'dzhafer_osman_topchi',
       'dzhuma_durdy_karayev'],
 'i': ['dziarnowo,_kuyavian-pomeranian_voivodeship',
       'dzierzaznik,_warmian-masurian_voivodeship',
       'dziekanowice,_swietokrzyskie_voivodeship',
       'dzikowo,_kuyavian-pomeranian_voivodeship',
       'dzialyn,_kuyavian-pomeranian_voivodeship',
       'dzieslawice,_swietokrzyskie_voivodeship',
       'dziegiele,_warmian-masurian_voivodeship',
       'dziki,_kuyavian-pomeranian_voivodeship',
       'dzierzgow,_swietokrzyskie_voivodeship',
       'dzialki,_warmian-masurian_voivodeship',
       'dzialy,_warmian-masurian_voivodeship',
       'dzikowiec,_podkarpackie_voivodeship',
       'dzierzaznik,_pomeranian_voivodeship',
       'dzieciolowo,_podlaskie_voivodeship',
       'dziewiatka,_pomeranian_voivodeship',
       'dziadkowice,_podlaskie_voivodeship',
       'dzierzgowek,_masovian_voivodeship',
       'dzielec,_podkarpackie_voivodeship',
       'dziegiel,_pomeranian_voivodeship',
       'dzierzazna,_masovian_voivodeship',
       'dzierzanow,_masovian_voivodeship',
       'dziegiele,_podlaskie_voivodeship',
       'dziedzice,_masovian_voivodeship',
       'dzierzawa,_silesian_voivodeship',
       'dziarnowo,_masovian_voivodeship',
       'dzierzkowice,_opole_voivodeship',
       'dzierzyslaw,_opole_voivodeship',
       'dzielnik,_masovian_voivodeship',
       'dzikow,_pomeranian_voivodeship',
       'dziekanowice,_myslenice_county',
       'dzieraznia,_lublin_voivodeship',
       'dzialyn,_masovian_voivodeship',
       'dzialki,_masovian_voivodeship',
       'dziadkowice,_lodz_voivodeship',
       'dziunin,_masovian_voivodeship',
       'dzierzgowek,_lodz_voivodeship',
       'dzielna,_silesian_voivodeship',
       'dzilam_gonzalez_municipality',
       'dzierzazna,_poddebice_county',
       'dzielnica,_opole_voivodeship',
       'dzielnica,_gmina_zelechlinek',
       'dzierzazna,_lodz_voivodeship',
       'dzielnica,_gmina_czerniewice',
       'dziedzice,_krapkowice_county',
       'dziurow,_starachowice_county',
       'dzierzgow,_lodz_voivodeship',
       'dzialyn,_lublin_voivodeship',
       'dziecinow,_kozienice_county',
       'dziekanowice,_krakow_county',
       'dzierzazno,_kartuzy_county',
       'dzierzazna,_sieradz_county',
       'dziedzice,_namyslow_county',
       'dziurow,_sandomierz_county',
       'dzierzazno_railway_station',
       'dzieraznia,_pinczow_county',
       'dziecioly,_wolomin_county',
       'dzielna,_lodz_voivodeship',
       'dzierzanowo,_plock_county',
       'dzikowo,_mysliborz_county',
       'dzialdowo_railway_station',
       'dzierzanowo,_makow_county',
       'dzikowo,_koszalin_county',
       'dzieci_z_leningradzkiego',
       'dziecinow,_otwock_county',
       'dzierzazno,_tczew_county',
       'dzialy,_ciechanow_county',
       'dziecioly,_losice_county',
       'dzigar_kongtrul_rinpoche',
       'dzisnity,_ostroda_county',
       'dzisnity,_elblag_county',
       'dzialy,_gostynin_county',
       'dzikowo,_gorzow_county',
       'dzialy,_sieradz_county',
       'dziennik_gazeta_prawna',
       'dzialy,_wielun_county',
       'dzikowo,_walcz_county',
       'dzial,_gorlice_county',
       'dzialy,_kutno_county',
       'dzien_dobry_wakacje',
       'dziewczyny_z_dubaju',
       'dziga_vertov_group',
       'dziobas_rar_player',
       'dzikow_gas_field',
       'dzihan_&_kamien',
       'dzien_dobry_tvn',
       'dzien_na_zywo'],
 'm': ['dzmm_630_khz'],
 'o': ['dzongkha_development_commission',
       'dzoraghbyur_training_centre',
       'dzongsar_khyentse_rinpoche',
       'dzogchen_ponlop_rinpoche',
       'dzongkha_keyboard_layout',
       'dzoeng_maan_juk'],
 'r': ['dzrh_news_television', 'dzrh_network_news', 'dzrr_103.1_mhz'],
 'u': ["dzurinda's_second_cabinet",
       'dzungarian_dwarf_hamster',
       'dzulkifli_abdul_razak',
       'dzukija_national_park',
       'dzudo_klub_partizan'],
 'v': ['dzveli_gavazi_church'],
 'w': ['dzwierzno,_kuyavian-pomeranian_voivodeship',
       'dzwonek,_masovian_voivodeship',
       'dzwierzno,_czluchow_county',
       'dzwonowo,_stargard_county',
       'dzwierzno,_zuromin_county',
       'dzwierzno,_plock_county',
       'dzwonowo,_walcz_county'],
 'x': ['dzxq_1350_am']}
