
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_lh = {'_': ['lh_medical_college'],
 'a': ['lha-klu_tshe-dbang_rdo-rje',
       'lhanbryde_railway_station',
       'lhasa_airport_expressway',
       'lhagyari_namgyal_dolkar',
       'lhakpa_tenzing_sherpa',
       'lhasa_gonggar_airport',
       'lhasa_railway_station',
       'lhamoy_zingkha_gewog',
       'lhalung_pelgyi_dorje',
       'lha_charitable_trust',
       'lhasa_carpet_factory',
       'lhasa_gongga_airport',
       'lhalu_tsewang_dorje',
       'lhasa_great_mosque',
       'lhasa_evening_post',
       'lhasa_zhol_pillar',
       'lhalu_cewang_doje',
       'lhao_vo_language',
       'lhasa_de_sela',
       'lha_of_tibet',
       'lha_120-n_55',
       'lha_120-s_79'],
 'b': ['lhb_prototype_carriages'],
 'c': ['lhc_les_lions'],
 'e': ["lheidli_t'enneh_band", 'lhen_coan_station'],
 'k': ['lhk_jestrabi_prostejov'],
 'o': ['lhotsky/blackhouse_tasmanian_language',
       'lhodrak_seykhar_dratshang',
       'lhota_pod_horickami',
       'lhotse_shar_glacier',
       'lhotka_u_litultovic',
       'lhota_pod_libcany',
       'lhoty_u_potstejna',
       'lhota_u_olesnice',
       'lhotka_nad_labem',
       'lhota_u_pribrame',
       'lhota_pod_radcem',
       'lhotka_u_radnic',
       'lhota_u_vsetina',
       'lho_mang_thang',
       'lhota_u_lysic',
       'lho_men_jong'],
 's': ['lhs_1140_b', 'lhs_3844_b'],
 'x': ['lhx_attack_chopper']}
