
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_lj = {'_': ['lj_hooker_league', 'lj_de_montcalm', 'lj_van_zyl'],
 'a': ['ljabru_tram_stop'],
 'd': ['ljd_law_college'],
 'e': ['ljesnica,_bijelo_polje'],
 'i': ['ljiljana_habjanovic_durovic'],
 'n': ['ljn_video_art'],
 'u': ['ljubljana-matica_mountaineering_club',
       'ljusnarsberg_obundna_kommunparti',
       'ljubljana_student_organisation',
       'ljubljana-matica_climbing_club',
       'ljubljana_passenger_transport',
       'ljubica_zorka_karadjordjevic',
       'ljubov_nikolaevna_vassiljeva',
       'ljubac,_sibenik-knin_county',
       'ljubica_mrdakovic_todorovic',
       'ljubicevo_equestrian_games',
       'ljubljana_castle_funicular',
       'ljubljana_central_pharmacy',
       'ljubljana_botanical_garden',
       'ljubljana_railway_station',
       'ljubica_ivosevic_dimitrov',
       'ljubljana_summer_festival',
       'ljubljana_lacanian_school',
       'ljubljanica_river_barrier',
       'ljubljana_graphic_school',
       'ljutomer_railway_station',
       'ljubljanica_sluice_gates',
       'ljubibratic_noble_family',
       'ljubljana_central_market',
       'ljubljana_stock_exchange',
       'ljungstrom_air_preheater',
       'ljubljana_medical_center',
       'ljubljana_marshes_wheel',
       'ljudmila_dolar_mantuani',
       'ljubomir_ivanovic_gedza',
       'ljubljanica_sluice_gate',
       'ljungstorp_och_jagersbo',
       'ljuvlig_ar_sommarnatten',
       'ljubljana_power_station',
       'ljusdal_court_district',
       'ljubljana_city_theatre',
       'ljubomir_pavicevic_fis',
       'ljubav,_navika,_panika',
       'ljudmila_plesnicar_gec',
       'ljubljana_opera_house',
       'ljubljana_sports_park',
       'ljubljana_tram_system',
       'ljubinka_bobic_award',
       'ljunghusen_golf_club',
       'ljubenic_mass_graves',
       'ljubisa_d.r._kocinac',
       'ljutovid_of_zahumlje',
       'ljubac,_zadar_county',
       'ljubljana_ring_road',
       'ljubljana_town_hall',
       'ljubljana_city_hall',
       'ljud_&_bildskolan',
       'ljubno_ob_savinji',
       'ljubo_cesic_rojs',
       'ljutic_space_gun',
       'ljubav_je_svuda',
       'ljudi_i_bogovi',
       'ljubez_v_lazih',
       'ljubav_i_bol'],
 'v': ['ljvm_coliseum_complex', 'ljvm_coliseum_annex']}
