
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_lt = {'_': ['lt.col.saurabh_singh_shekhawat',
       'lt._col._haroon-ul-islam',
       'lt.gen._prakash_gokarn',
       'lt.col._wisnu_airfield',
       'lt-gen_umar_al-bashir',
       'lt._kenneth_armstrong',
       'lt._thomas_selfridge',
       'lt._reginald_barclay',
       'lt-cmdr_suresh_nanda',
       'lt._reginald_barkley',
       'lt._general_lumsden',
       'lt._commander_tuvok',
       'lt-gen_keith_coster',
       'lt._cedric_daniels',
       'lt._raymond_foster',
       'lt._gen._chaudhari',
       'lt_col_loganathan',
       'lt._gen._caldwell',
       'lt_fashih_bokhari',
       'lt._howard_hunter',
       'lt-gen_thein_sein',
       'lt._philip_dalton',
       'lt._david_steeves',
       'lt._felina_feral',
       'lt._max_eckhardt',
       'lt._leary_series',
       'lt&sr_2100_class',
       'lt._audie_murphy',
       'lt_smith_stadium',
       'lt._ehren_watada',
       'lt._andy_baldwin',
       'lt._reg_barkley',
       'lt._col._tejero',
       'lt._reg_barclay',
       'lt._max_eckhart',
       'lt&sr_79_class',
       'lt._col._leroy',
       'lt&sr_51_class',
       'lt&sr_49_class',
       'lt&sr_37_class',
       'lt&sr_69_class',
       'lt._gen._maude',
       'lt._lou_roher',
       'lt._col._cole',
       'lt&sr_1_class',
       'lt._dan_band',
       'lt_dale_bair',
       'lt_col_cole',
       'lt_vz._34'],
 'c': ['ltc_financial_partners', 'ltc_bob_bowden'],
 'd': ['ltdl_multimedia_collection'],
 'e': ['lte_international_airways',
       'lte_advanced_standard',
       'lte_advanced_wireless',
       'lte_advanced_network',
       'lte_frequency_bands',
       'lte_live_2008'],
 'g': ['ltg_william_caldwell', 'ltgen_james_mattis', 'ltgen_cardozo_luna'],
 'i': ['lti_system_theory', 'lti_giessen_46ers'],
 's': ['lts_gardbaer_studios'],
 't': ['lttle_red_schoolbook',
       'lttihad_ve_terraki',
       'ltte_black_tiger',
       'ltte_sri_lanka'],
 'u': ['ltu_international_airlines', 'ltu_international_airways'],
 'v': ['ltv_super_cup'],
 'y': ['ltyentye_apurte_community']}
