
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_mp = {'_': ['mp_creek,_queensland',
       'mp_expenses_scandal',
       'mp_birla_foundation',
       'mp_veerendra_kumar',
       'mp-apvl_83-f4_mine',
       'mp_investment_bank',
       'mp_sankunni_nair',
       'mp4_holin_family',
       'mp3_file_sharing',
       'mp_expenses_row',
       'mp_birla_group',
       'mp_anil_kumar',
       'mp_muar_f.c.',
       'mp_united_fc',
       'mp_443_grach',
       'mp_1-5_zone',
       'mp_&_silva',
       'mp_89_cc',
       'mp_89_ca',
       'mp_-_43'],
 'a': ['mpanga-kipengere_game_reserve',
       'mpaa_rating_system',
       'mpaa_movie_ratings',
       'mpaa_film_rating',
       'mpaa_series_1',
       'mpatu_a_ponta'],
 'b': ['mpbl_finals_mvp'],
 'c': ['mpc_catalogue_numbers', 'mpc_catalogue_number', 'mpc_computers_bowl'],
 'd': ['mpd_in_fiction'],
 'e': ['mpeg_multiprotocol_encapsulation',
       'mpelembe_secondary_school',
       'mpeg_licensing_authority',
       'mpeg-4_structured_audio',
       'mpenjati_nature_reserve',
       'mpeg-2_transport_stream',
       'mpeg_elementary_stream',
       'mpeg_common_encryption',
       'mpeg_transport_stream',
       'mpeg_media_transport',
       'mpeg_industry_forum',
       'mpeg_program_stream',
       'mpesela_ntlot_soeu',
       'mpeg_audio_decoder',
       'mpeg-4_timed_text',
       'mpeg-4_avc_/h.264',
       'mpeg-1_layer_iii',
       'mpeg-1_layer_ii',
       'mpeg-4_layer_14',
       'mpeg-h_3d_audio',
       'mpeg-4_layer_10',
       'mpeg-2_layer_ii',
       'mpeg_user_data',
       'mpeg-4_part_17',
       'mpeg-4_part_14',
       'mpeg_layer_iii',
       'mpeg-4_layer_2',
       'mpeg-4_layer_3',
       'mpeg-1_layer_3',
       'mpeg-4_part_20',
       'mpeg-4_part_10',
       'mpeg-4_part_11',
       'mpeg-1_layer_2',
       'mpeg-4_part_12',
       'mpeg-4_part_1',
       'mpeg-4_part_2',
       'mpeg-2_part_7',
       'mpeg-2_part_3',
       'mpeg-4_part_3',
       'mpeg_layer_2',
       'mpeg_4_avc'],
 'f': ['mpf_industry_group'],
 'h': ['mphj_technology_investments',
       'mph_entertainment,_inc.',
       'mphanda_nkuwa_dam',
       'mpho_osei_tutu'],
 'i': ['mpisekhaya_ngangomhlaba_sigcawu',
       'mpigi_general_hospital',
       'mpika_railway_station',
       'mpire_music_group',
       'mpi_media_group'],
 'l': ['mpls_local_restoration',
       'mpls_local_protection',
       'mpls_fast_reroute',
       'mplayer_1.0_rc2',
       'mplayer_os_x'],
 'o': ['mpofana_local_municipality',
       'mpohor/wassa_east_district',
       'mpower_tobacco_control',
       'mpofu_nature_reserve',
       'mpopoma_high_school',
       'mponeng_gold_mine'],
 'p': ['mppj_selangor_f.c.', 'mpp-b_wierzba_mine', 'mppj_selangor_fc'],
 'r': ['mpr_dpr_building'],
 's': ['mps_expenses_controversy',
       'mps_records_discography',
       'mps_group_championships',
       'mps_capital_services',
       'mps_expenses_scandal',
       'mps_expenses_row',
       'mps_group_inc.',
       'mps_of_wales',
       'mps_in_wales',
       'mps_cape_cod'],
 'u': ['mpumalanga_provincial_legislature',
       'mpumalanga_high_court',
       'mpumalanga_black_aces',
       'mpu_tantular_museum'],
 'w': ['mpwapwa_worm_lizard']}
