
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_hn = {'hn-ams': 'hanoi_-_amsterdam_high_school',
 'hn51': 'influenza_a_virus_subtype_h5n1',
 'hnao': 'sodium_hydroxide',
 'hnas': 'sodium_hydrosulfide',
 'hnatiuk': 'roger_hnatiuk',
 'hnau': 'the_space_trilogy',
 'hnbr': 'nitrile_rubber',
 'hnca': 'hnca_experiment',
 'hnchag': 'social_democrat_hunchakian_party',
 'hnchakian': 'social_democrat_hunchakian_party',
 'hncoca': 'hncoca_experiment',
 'hndajet': 'honda_ha-420_hondajet',
 'hnefatafl': 'tafl_games',
 'hnetafl': 'tafl_games',
 'hnf1': 'hnf1a',
 'hnf4': 'hepatocyte_nuclear_factor_4',
 'hnf4a': 'hepatocyte_nuclear_factor_4_alpha',
 'hnf4a7': 'hepatocyte_nuclear_factor_4_alpha',
 'hnf4a8': 'hepatocyte_nuclear_factor_4_alpha',
 'hnf4a9': 'hepatocyte_nuclear_factor_4_alpha',
 'hnf4g': 'hepatocyte_nuclear_factor_4_gamma',
 'hnhm': 'hungarian_natural_history_museum',
 'hnic': 'hockey_night_in_canada',
 'hnickar': 'nickar',
 'hnin': 'nicole_scherzinger',
 'hnitbjoerg': 'hnitbjorg',
 'hniw': 'hexanitrohexaazaisowurtzitane',
 'hnizdovsky': 'jacques_hnizdovsky',
 'hnizdowsky': 'jacques_hnizdovsky',
 'hnks': 'nonketotic_hyperosmolar_coma',
 'hnmh': 'harvard_museum_of_natural_history',
 'hnmr': 'proton_nmr',
 'hnn-extension': 'hnn_extension',
 'hnnkn': 'higurashi_no_naku_koro_ni',
 'hno2': 'nitrous_acid',
 'hno3': 'nitric_acid',
 'hno5s': 'nitrosylsulfuric_acid',
 'hnoh': 'hebrew_national_orphan_home',
 'hnoms': 'knm',
 'hnossa': 'hnoss',
 'hnpcc': 'hereditary_nonpolyposis_colorectal_cancer',
 'hnpcc5': 'msh6',
 'hnpcc6': 'tgf_beta_receptor_2',
 'hnpp': 'peripheral_myelin_protein_22',
 'hnr3': 'grin2b',
 'hnrc': 'harry_needle_railroad_company',
 'hnrna': 'precursor_mrna',
 'hnrnp': 'heterogeneous_ribonucleoprotein_particle',
 'hnrpa1': 'heterogeneous_nuclear_ribonucleoprotein_a1',
 'hnrpc': 'hnrnpc',
 'hns-info.net': 'hacktivist_news_service',
 'hnsalwp': 'hungarian_national_socialist_party',
 'hnsp': 'hungarian_national_socialist_party',
 'hntv': 'hanoi_radio_television',
 'hnue': 'hanoi_national_university_of_education',
 'hnwi': 'high_net_worth_individual'}
        