
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_pm = {'_': ['pm-international',
       'pm/scl-complex',
       'pm-elect',
       'pm:ttyd',
       'pm-98s',
       'pm2fgd',
       'pm20d1',
       'pm-scl',
       'pm5544',
       'pm5644',
       'pm-2.5',
       'pm-84p',
       'pm/ssc',
       'pm2fgr',
       'pm-147',
       'pm/scl',
       'pm-ssc',
       'pm2.5',
       'pm12s',
       'pm-63',
       'pm-10',
       'pm-73',
       'pm-98',
       'pm-84',
       'pm-70',
       'pm12',
       'pm5k',
       'pm-3',
       'pm10',
       'pm3',
       'pm2'],
 'a': ['pmang.com',
       'pmachine',
       'pmaesa',
       'pma400',
       'pmandr',
       'pmall',
       'pmagl',
       'pma-1',
       'pmate',
       'pma-2',
       'pma-3',
       'pmail',
       'pmaa',
       'pmac',
       'pmag',
       'pmap',
       'pmas',
       'pmat',
       'pma'],
 'b': ['pmbga', 'pmbus', 'pmbok', 'pmbr', 'pmb'],
 'c': ['pmc-sierra',
       'pmc-80',
       'pmc-90',
       'pmc80',
       'pmcs',
       'pmch',
       'pmcp',
       'pmcl',
       'pmcc',
       'pmcd',
       'pmc'],
 'd': ['pmdtechnologies',
       'pmd-7ts',
       'pmdeta',
       'pmdien',
       'pmd660',
       'pmd-6m',
       'pmdtt',
       'pmdta',
       'pmdb',
       'pmdd',
       'pmds',
       'pmdg',
       'pmdc',
       'pmda',
       'pmdt',
       'pmdf',
       'pmd'],
 'e': ['pmedsci', 'pmetb', 'pmee', 'pme3', 'pmea', 'pmel', 'pme'],
 'f': ['pmfbp1', 'pmftc', 'pmf1', 'pmf'],
 'g': ['pmgsy', 'pmg'],
 'h': ['pmhub', 'pmhs', 'pmh'],
 'i': ['pmi-sp',
       'pmirkb',
       'pmi-80',
       'pmirr',
       'pmic',
       'pmio',
       'pmid',
       'pmip',
       'pmi'],
 'j': ['pmji'],
 'k': ['pmk-dgn', 'pmkri', 'pmk'],
 'l': ['pmlexis', 'pmla', 'pmln', 'pmli', 'pmlf', 'pmlq', 'pmle', 'pml'],
 'm': ['pmmf', 'pmmp', 'pmma', 'pmm2', 'pmmu', 'pmm1', 'pmml', 'pmm'],
 'n': ['pmn-2', 'pmn-e', 'pmnh', 'pmn'],
 'o': ['pmode/w',
       'pmotuk',
       'pmode',
       'pmof',
       'pmoc',
       'pmog',
       'pmos',
       'pmoy',
       'pmox',
       'pmo'],
 'p': ['pmpml',
       'pmp22',
       'pmpcb',
       'pmprb',
       'pmpca',
       'pmpv1',
       'pmpo',
       'pmpg',
       'pmp2',
       'pmps',
       'pmp'],
 'q': ['pmq'],
 'r': ['pmr446', 'pmrs', 'pmrt', 'pmrc', 'pmrf', 'pmr'],
 's': ['pmseic',
       'pmssr',
       'pmsia',
       'pmset',
       'pmsa',
       'pms1',
       'pmsg',
       'pmsp',
       'pmss',
       'pmsi',
       'pmsl',
       'pmsf',
       'pmse',
       'pms2',
       'pms'],
 't': ['pmtoday', 'pmtair', 'pmttyd', 'pmtud', 'pmts', 'pmtu', 'pmtv', 'pmt'],
 'u': ['pmut', 'pmun', 'pmu'],
 'v': ['pmview', 'pmve', 'pmvi', 'pmv'],
 'w': ['pmwiki', 'pmw'],
 'x': ['pmx'],
 'z': ['pmz-a-750', 'pmzox', 'pmz']}
