
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_dc = {'dc101_chili_cookoff': 'dc101_chili_cook-off',
 'dc_al_coda': 'd.c._al_coda',
 'dc_al_fine': 'da_capo',
 'dc_and_family': 'dc_and_the_family',
 'dc_antiwar_network': 'dc_anti-war_network',
 'dc_brushless_motor': 'brushless_dc_electric_motor',
 'dc_chris_skelton': 'chris_skelton',
 'dc_circuit_court': 'united_states_court_of_appeals_for_the_district_of_columbia_circuit',
 'dc_city_council': 'council_of_the_district_of_columbia',
 'dc_city_hall': 'john_a._wilson_building',
 'dc_comics_mmorpg': 'dc_universe_online',
 'dc_comics_universe': 'dc_universe',
 'dc_debate_league': 'urban_debate_league',
 'dc_democratic_party': 'district_of_columbia_democratic_state_committee',
 'dc_entertainment_inc.': 'dc_comics',
 'dc_fair_act': 'district_of_columbia_voting_rights',
 'dc_games_2007': 'disney_channel_games',
 'dc_go_go': 'go-go',
 'dc_graphic_novels': 'dc_graphic_novel',
 'dc_green_party': 'd.c._statehood_green_party',
 'dc_hand_dance': 'hand_dancing',
 'dc_hand_dancing': 'hand_dancing',
 'dc_home_rule': 'district_of_columbia_home_rule',
 'dc_jo_masters': 'the_bill',
 'dc_mckay_stakes': 'd.c._mckay_stakes',
 'dc_metro_area': 'washington_metropolitan_area',
 'dc_metro_police': 'metropolitan_police_department_of_the_district_of_columbia',
 'dc_motema_pembe': 'daring_club_motema_pembe',
 'dc_motemba_pembe': 'daring_club_motema_pembe',
 'dc_new_frontier': 'dc:_the_new_frontier',
 'dc_olympic_committee': 'district_of_columbia_olympic_committee',
 'dc_olympic_team': 'district_of_columbia_olympic_committee',
 'dc_public_library': 'district_of_columbia_public_library',
 'dc_public_schools': 'district_of_columbia_public_schools',
 'dc_republican_committee': 'district_of_columbia_republican_committee',
 'dc_republican_party': 'district_of_columbia_republican_committee',
 'dc_shoe_company': 'dc_shoes',
 'dc_showcase_presents': 'showcase_presents',
 'dc_sniper_shootings': 'beltway_sniper_attacks',
 'dc_statehood_movement': 'd.c._statehood_movement',
 'dc_statehood_party': 'd.c._statehood_green_party',
 'dc_superior_court': 'superior_court_of_the_district_of_columbia',
 'dc_tea_party': 'tea_party_protests',
 'dc_united_holdings': 'd.c._united_holdings',
 'dc_universe_movies': 'dc_universe_original_animated_movies',
 'dc_urban_debate': 'urban_debate_league',
 'dc_v._heller': 'district_of_columbia_v._heller',
 'dc_v_heller': 'district_of_columbia_v._heller',
 'dc_versus_marvel': 'dc_vs._marvel',
 'dc_voting_rights': 'district_of_columbia_voting_rights',
 'dc_vs._heller': 'district_of_columbia_v._heller',
 'dc_vs_marvel': 'dc_vs._marvel',
 'dc_vs_mk': 'mortal_kombat_vs._dc_universe',
 'dci_gene_hunt': 'gene_hunt',
 'dci_matt_burke': 'taggart',
 'dci_world_championships': 'drum_corps_international_world_class_champions',
 'dcl_command_language': 'digital_command_language',
 'dcs:_black_shark': 'digital_combat_simulator',
 'dcs_pro_14nx': 'kodak_dcs_pro_14n'}
        