
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_rj = {'rj._mitchell': 'r._j._mitchell',
 'rj_100': 'dzrj-fm',
 'rj_100.3': 'dzrj-fm',
 'rj_1200': 'cjrj',
 'rj_adams': 'r._j._adams',
 'rj_berg': 'r._j._berg',
 'rj_berry': 'r._j._berry',
 'rj_billinton': 'r._j._billinton',
 'rj_brande': 'r._j._brande',
 'rj_brandes': 'richard_john_brandes',
 'rj_campbell': 'reginald_john_campbell',
 'rj_cobbs': 'r._j._cobbs',
 'rj_connector': 'registered_jack',
 'rj_corman': 'r.j._corman_railroad_group',
 'rj_cutler': 'r._j._cutler',
 'rj_dent': 'r._j._dent',
 'rj_herrera': 'r._j._herrera',
 'rj_hollingdale': 'reginald_john_hollingdale',
 'rj_hopper': 'r._j._hopper',
 'rj_mccone': 'ryan_mccone',
 'rj_mendenhall': 'r._j._mendenhall',
 'rj_mical': 'robert_j._mical',
 'rj_mitchell': 'r._j._mitchell',
 'rj_morrison': 'richard_james_morrison',
 'rj_motorsports': 'carter_simo_racing',
 'rj_nuevas': 'r.j._nuevas',
 'rj_reynolds': 'r._j._reynolds',
 'rj_rummel': 'r._j._rummel',
 'rj_seddon': 'richard_seddon',
 'rj_soward': 'r._jay_soward',
 'rj_sternberg': 'robert_sternberg',
 'rj_stove': 'r._j._stove',
 'rj_swindle': 'r._j._swindle',
 'rj_thomas': 'r._j._thomas',
 'rj_umberger': 'r._j._umberger',
 'rj_washington': 'r._j._washington',
 'rj_williams': 'r._j._williams',
 'rj_yeatman': 'r._j._yeatman',
 'rjb_knight': 'r._j._b._knight',
 'rjb_mining': 'uk_coal',
 'rje_mkhan-po': 'je_khenpo',
 'rjebtsun_dampa': 'jebtsundamba_khutuktu',
 'rjp_williams': 'robert_joseph_paton_williams',
 'rjtv_29': 'dzrj-tv',
 'rjv_gas': 'rjv_gas_field_services',
 'rjv_oil': 'rjv_gas_field_services',
 'rjyan_kidwell': 'cex'}
        