
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_rp = {'rp_blackmur': 'r._p._blackmur',
 'rp_brereton': 'r._p._brereton',
 'rp_english': 'received_pronunciation',
 'rp_goenka': 'r._p._goenka',
 'rp_hplc': 'high_performance_liquid_chromatography',
 'rp_keigwin': 'r._p._keigwin',
 'rp_king': 'dick_king',
 'rp_patnaik': 'r._p._patnaik',
 'rp_process': 'rp-process',
 'rp_romina': 'communist_romania',
 'rp_saraf': 'r._p._saraf',
 'rp_singh': 'r._p._singh',
 'rp_weston': 'r._p._weston',
 'rpa_program': 'rpa_assessment',
 'rpc_2': 'regional_playback_control',
 'rpc_ii': 'regional_playback_control',
 'rpf_academy': 'railway_protection_force_academy',
 'rpg-29_vampir': 'rpg-29',
 'rpg_29': 'rpg-29',
 'rpg_7': 'rpg-7',
 'rpg_game': 'role-playing_game',
 'rpg_games': 'role-playing_game',
 'rpg_gun': 'rocket-propelled_grenade',
 'rpg_history': 'history_of_role-playing_games',
 'rpg_ii': 'ibm_rpg_ii',
 'rpg_iii': 'ibm_rpg_iii',
 'rpg_iv': 'ibm_rpg',
 'rpg_launcher': 'rocket-propelled_grenade',
 'rpg_school': 'rpg_maker',
 'rpg_system': 'role-playing_game_system',
 'rpg_theory': 'role-playing_game_theory',
 'rpg_tkool': 'rpg_maker',
 'rpg_tsukuru': 'rpg_maker',
 'rpg_tsukuuru': 'rpg_maker',
 'rpg_vault': 'vault_network',
 'rpgmaker_2000': 'rpg_maker_2000',
 'rpgmaker_2003': 'rpg_maker_2003',
 'rpi_observatory': 'hirsch_observatory',
 'rpk_74': 'rpk',
 'rpm_2day': 'rpm_2night',
 'rpm_limiter': 'rev_limiter',
 'rpm_live': 'rpm:_live',
 'rpm_package': 'rpm_package_manager',
 'rpn_9': 'dzkb-tv',
 'rpn_calculator': 'reverse_polish_notation',
 'rpn_manila': 'dzkb-tv',
 'rpo_code': 'regular_production_option',
 'rpo_codes': 'regular_production_option',
 'rpp_nepal': 'rastriya_prajatantra_party_nepal'}
        