
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_rb = {'rb-1_conestoga': 'rb_conestoga',
 'rb-47_stratojet': 'b-47_stratojet',
 'rb-57_canberra': 'b-57_canberra',
 'rb-69_neptune': 'p-2_neptune',
 'rb-71_skyflash': 'british_aerospace_skyflash',
 'rb_57': 'mbt_law',
 'rb_bennett': 'r._b._bennett',
 'rb_braithwaite': 'r._b._braithwaite',
 'rb_cola': 'red_bull_cola',
 'rb_cunninghame-graham': 'robert_bontine_cunninghame_graham',
 'rb_etherington-smith': 'raymond_etherington-smith',
 'rb_greaves': 'r._b._greaves',
 'rb_kitaj': 'r._b._kitaj',
 'rb_mcdowell': 'r._b._mcdowell',
 'rb_pearson': 'r._b._pearson',
 'rb_protein': 'retinoblastoma_protein',
 'rb_richardson': 'richie_richardson',
 'rb_rutherford': 'r._b._rutherford',
 'rb_salzburg': 'fc_red_bull_salzburg',
 'rb_script': 'rbscript',
 'rb_searcy': 'r._b._searcy',
 'rb_series': 'rock_band',
 'rb_swift': 'r.b._swift',
 'rb_tree': 'red-black_tree',
 'rbb_fernsehen': 'rundfunk_berlin-brandenburg',
 'rbc_centura': 'rbc_bank',
 'rbc_count': 'complete_blood_count',
 'rbc_cup': 'royal_bank_cup',
 'rbc_group': 'rbc_information_systems',
 'rbc_index': 'red_blood_cell_indices',
 'rbc_indices': 'red_blood_cell_indices',
 'rbc_stadion': 'rosada_stadion',
 'rbd_augsburg': 'reichsbahndirektion_augsburg',
 'rbd_regensburg': 'reichsbahndirektion_regensburg',
 'rbi_baseball': 'r.b.i._baseball',
 'rbia_river': 'oum_er-rbia_river',
 'rbj_corporation': 'klm_telephone',
 'rbk_edge': 'nhl_uniform',
 'rbk_tv': 'rbc_tv',
 'rbs_15': 'rbs-15',
 'rbs_aviation': 'royal_bank_of_scotland',
 'rbs_group': 'royal_bank_of_scotland_group',
 'rbs_international': 'royal_bank_of_scotland_international',
 'rbs_plc': 'royal_bank_of_scotland',
 'rbx_files': 'the_rbx_files',
 'rbx_filez': 'the_rbx_files',
 'rby_scott': 'robert_balgarnie_young_scott'}
        