
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_mg = {'mg1_electric_motor': 'hybrid_synergy_drive',
 'mg2_electric_motor': 'hybrid_synergy_drive',
 'mg42_machine_gun': 'mg_42',
 'mg4_machine_gun': 'mg-4_machine_gun',
 'mg_151/15_cannon': 'mg_151_cannon',
 'mg_151/20_cannon': 'mg_151_cannon',
 'mg_metro_6r4': 'rover_metro',
 'mg_per_l': 'gram_per_litre',
 'mg_x-power_sv': 'mg_xpower_sv',
 'mg_xpower_wr': 'mg_x-power_wr',
 'mga_entertainment_inc.': 'mga_entertainment',
 'mga_munting_tinig': 'small_voices',
 'mga_type_2': 'barth_syndrome',
 'mga_type_ii': 'barth_syndrome',
 'mgahinga_national_park': 'mgahinga_gorilla_national_park',
 'mgarr_united_fc': 'mgarr_united_f.c.',
 'mge_ups_systems': 'schneider_electric',
 'mgic_investment_corporation': 'mortgage_guaranty_insurance_corporation',
 'mgm-ua_home_video': 'mgm_home_entertainment',
 'mgm/ua_communications_co.': 'metro-goldwyn-mayer',
 'mgm/ua_distribution_co.': 'metro-goldwyn-mayer',
 'mgm/ua_entertainment_co.': 'metro-goldwyn-mayer',
 'mgm/ua_entertainment_company': 'metro-goldwyn-mayer',
 'mgm/ua_home_entertainment': 'mgm_home_entertainment',
 'mgm/ua_home_video': 'mgm_home_entertainment',
 'mgm_camera_65': 'ultra_panavision_70',
 'mgm_cartoon_department': 'metro-goldwyn-mayer_cartoon_studio',
 'mgm_distribution_co.': 'metro-goldwyn-mayer',
 'mgm_grand_ac': 'mgm_grand_atlantic_city',
 'mgm_grand_air': 'champion_air',
 'mgm_grand_arena': 'mgm_grand_garden_arena',
 'mgm_grand_darwin': 'skycity_darwin',
 'mgm_grand_garden': 'mgm_grand_garden_arena',
 'mgm_grand_hotel': 'mgm_grand',
 'mgm_grand_inc': 'mgm_grand_inc.',
 'mgm_grand_reno': 'grand_sierra_resort',
 'mgm_mirage_resorts': 'mgm_mirage',
 'mgm_mirage_x': 'mgm_mirage',
 'mgm_parade_show': 'mgm_parade',
 'mgm_recording_studios': 'cherokee_studios',
 'mgm_studios_inc.': 'metro-goldwyn-mayer',
 'mgp-84_submachine_gun': 'mgp-15_submachine_gun',
 'mgr._athol_murray': 'athol_murray',
 'mgr._mathew_mankuzhikary': 'mathew_mankuzhikary',
 'mgr_de_bonald': 'louis_jacques_maurice_de_bonald',
 'mgr_medical_university': 'the_tamil_nadu_dr._m.g.r._medical_university',
 'mgs:_peace_walker': 'metal_gear_solid:_peace_walker',
 'mgs:_portable_ops': 'metal_gear_solid:_portable_ops',
 'mgs_peace_walker': 'metal_gear_solid:_peace_walker',
 'mgs_portable_ops': 'metal_gear_solid:_portable_ops'}
        