#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# AUTO-GENERATED CONTENT
d_stem_jv = {'jva': {'jvas': []},
             'jvaldens': {'jvaldenses': []},
             'jvale': {'jvales': []},
             'jvalgam': {'jvalgame': []},
             'jvalli': {'jvallis': []},
             'jvalpol': {'jvalpole': []},
             'jvalu': {'jvalue': ['jvalues']},
             'jvalue': ['jvalues'],
             'jvame': {'jvames': []},
             'jvamo': {'jvamos': []},
             'jvamono': {'jvamonos': []},
             'jvanc': {'jvance': []},
             'jvanho': {'jvanhoe': []},
             'jvapl': {'jvaples': []},
             'jvar': {'jvars': []},
             'jvariou': {'jvarious': []},
             'jvation': {'jvational': [], 'jvations': []},
             'jvational': {'jvationale': []},
             'jvatur': {'jvatural': [], 'jvature': []},
             'jvavi': {'jvavy': []},
             'jvay': {'jvays': []},
             'jvb': {'jvbs': []},
             'jvbte': {'jvbtes': []},
             'jvc': {'jvcs': []},
             'jvdice': {'jvdices': []},
             'jvdmono': {'jvdmonos': []},
             'jve': {'jves': []},
             'jveal': {'jveale': []},
             'jvecess': {'jvecessity': []},
             'jveekli': {'jveekly': []},
             'jvel': {'jvels': []},
             'jvell': {'jvells': []},
             'jvelop': {'jveloped': [], 'jvelopment': []},
             'jvement': {'jvements': []},
             'jvenceremo': {'jvenceremos': []},
             'jvene': {'jvening': []},
             'jvent': {'jvents': []},
             'jver': {'jvers': []},
             'jverag': {'jverage': []},
             'jvere': {'jvered': []},
             'jveri': {'jvery': []},
             'jverk': {'jverke': []},
             'jvernment': {'jvernments': []},
             'jveryth': {'jverything': []},
             'jveue': {'jveues': []},
             'jvew': {'jvews': []},
             'jvhi': {'jvhy': []},
             'jvhig': {'jvhigs': []},
             'jvi': {'jvis': [], 'jvy': []},
             'jviani': {'jviany': []},
             'jviari': {'jviary': []},
             'jvicen': {'jvicene': []},
             'jvide': {'jvided': []},
             'jvidenc': {'jvidence': []},
             'jview': {'jviews': []},
             'jvile': {'jviles': []},
             'jvilk': {'jvilkes': []},
             'jvilkin': {'jvilkins': []},
             'jvilliam': {'jvilliams': []},
             'jvilloughbi': {'jvilloughby': []},
             'jving': {'jvings': []},
             'jviou': {'jvious': []},
             'jviousli': {'jviously': []},
             'jvir': {'jvirs': []},
             'jvivet': {'jviveting': []},
             'jvlaggi': {'jvlaggie': []},
             'jvlake': {'jvlaking': []},
             'jvlani': {'jvlany': []},
             'jvlari': {'jvlary': []},
             'jvlayb': {'jvlaybe': []},
             'jvli': {'jvly': []},
             'jvliu': {'jvlius': []},
             'jvliv': {'jvlivs': []},
             'jvlose': {'jvloses': []},
             'jvlove': {'jvloving': []},
             'jvlr': {'jvlrs': []},
             'jvm': {'jvms': []},
             'jvo': {'jvos': []},
             'jvofe': {'jvofes': []},
             'jvomant': {'jvomantic': []},
             'jvord': {'jvords': []},
             'jvori': {'jvory': []},
             'jvork': {'jvorks': []},
             'jvorker': {'jvorkers': []},
             'jvorri': {'jvorris': []},
             'jvote': {'jvotes': []},
             'jvoth': {'jvothing': []},
             'jvou': {'jvous': []},
             'jvouvel': {'jvouvelle': ['jvouvelles']},
             'jvouvelle': ['jvouvelles'],
             'jvovemb': {'jvovember': []},
             'jvp': {'jvps': []},
             'jvper': {'jvpers': []},
             'jvri': {'jvry': []},
             'jvrite': {'jvritings': []}}
