
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_nw = {'nw_airlines': 'northwest_airlines',
 'nw_airlink': 'delta_connection',
 'nw_england': 'north_west_england',
 'nw_jasper': 'n._w._jasper',
 'nw_knights': 'wisconsin_mustangs',
 'nw_ordiance': 'northwest_ordinance',
 'nw_ordinance': 'northwest_ordinance',
 'nw_plaza': 'northwest_plaza',
 'nw_territories': 'northwest_territories',
 'nwa-uk_hammerlock': 'nwa_uk_hammerlock',
 'nwa:_eccw': 'nwa:_extreme_canadian_championship_wrestling',
 'nwa:_tna': 'total_nonstop_action_wrestling',
 'nwa:_wcw': 'world_championship_wrestling',
 'nwa:uk_hammerlock': 'nwa_uk_hammerlock',
 'nwa_airlink': 'delta_connection',
 'nwa_championship': 'nwa_world_heavyweight_championship',
 'nwa_florida': 'championship_wrestling_from_florida',
 'nwa_inc.': 'northwest_airlines',
 'nwa_legacy': 'n.w.a._legacy',
 'nwa_mid-south': 'national_wrestling_alliance',
 'nwa_midwest': 'national_wrestling_alliance',
 'nwa_naturals': 'northwest_arkansas_naturals',
 'nwa_ohio': 'world_wide_wrestling_alliance',
 'nwa_quebec': 'nwa_quebec_pro_wrestling',
 'nwa_starrcade': 'starrcade',
 'nwa_title': 'nwa_world_heavyweight_championship',
 'nwa_tna': 'total_nonstop_action_wrestling',
 'nwa_wrestling': 'national_wrestling_alliance',
 'nwa_zero-one': 'pro_wrestling_zero1',
 'nwarhtogyi_township': 'natogyi_township',
 'nwc_express': 'york_factory_express',
 'nwi_times': 'the_times_of_northwest_indiana',
 'nwn2_expansion': 'neverwinter_nights_2:_mask_of_the_betrayer',
 'nwn2_mask': 'neverwinter_nights_2:_mask_of_the_betrayer',
 'nwn_2': 'neverwinter_nights_2',
 'nwo_championship': 'wcw_world_heavyweight_championship',
 'nwo_referee': 'nick_hamilton',
 'nws_yorktown': 'naval_weapons_station_yorktown',
 'nwt_air': 'first_air',
 'nwt_news/north': 'news/north',
 'nww_list': 'nurse_with_wound_list',
 'nwy_prydain': 'centrica'}
        