
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_nz = {'_': ['nz_independent_coalition',
       'nz_conceptual_framework',
       'nz_cycling_conference',
       'nz_olympic_committee',
       'nz_transport_agency',
       'nz_computer_society',
       'nz_performance_car',
       'nz_national_party',
       'nz_flag.com_trust',
       'nz_climate_party',
       'nz_pass_verifier',
       'nz_workers_party',
       'nz_defence_force',
       'nz_fire_service',
       'nz_labour_party',
       'nz_book_council',
       'nz_covid_tracer',
       'nz_drift_series',
       'nz_classic_car',
       'nz_coast_guard',
       'nz_book_month',
       'nz_meat_union',
       'nz_on_screen',
       'nz_road_code',
       'nz_rail_150',
       'nz_on_air'],
 'a': ['nzai_ct-4_airtrainer', 'nzara,_south_sudan', 'nzambi_a_mpungu'],
 'e': ['nzelo_herve_lembi',
       'nzema_kotoko_f.c.',
       'nze_ukwu_nnadum',
       'nze_na_ozo'],
 'i': ['nzinga_of_matamba', 'nzia_gold_medal'],
 'o': ['nzoia_sugar_f.c.', 'nzo_ekhah_nghaky', 'nzo_ekhah_ngaky'],
 'r': ['nzrfu_centenary_matches',
       'nzr_50-foot_carriage',
       'nzr_56-foot_carriage',
       'nzr_sumbersari_f.c.',
       'nzr_dsa_class',
       'nzr_wab_class',
       'nzr_dsb_class',
       'nzr_dsc_class',
       'nzr_adc_class',
       'nzr_adk_class',
       'nzr_adb_class',
       'nzr_adl_class',
       'nzr_dbr_class',
       'nzr_mem_class',
       'nzr_dl_class',
       'nzr_class_ef',
       'nzr_ba_class',
       'nzr_ja_class',
       'nzr_oa_class',
       'nzr_ua_class',
       'nzr_ab_class',
       'nzr_ub_class',
       'nzr_wa_class',
       'nzr_na_class',
       'nzr_ww_class',
       'nzr_dk_class',
       'nzr_ec_class',
       'nzr_ud_class',
       'nzr_fm_class',
       'nzr_aa_class',
       'nzr_df_class',
       'nzr_wg_class',
       'nzr_la_class',
       'nzr_wd_class',
       'nzr_rm_class',
       'nzr_ed_class',
       'nzr_oc_class',
       'nzr_dx_class',
       'nzr_we_class',
       'nzr_kb_class',
       'nzr_ob_class',
       'nzr_db_class',
       'nzr_fa_class',
       'nzr_uc_class',
       'nzr_wh_class',
       'nzr_bc_class',
       'nzr_nc_class',
       'nzr_wj_class',
       'nzr_wb_class',
       'nzr_ds_class',
       'nzr_ka_class',
       'nzr_ef_class',
       'nzr_wf_class',
       'nzr_bb_class',
       'nzr_c_class',
       'nzr_p_class',
       'nzr_d_class',
       'nzr_g_class',
       'nzr_x_class',
       'nzr_l_class',
       'nzr_u_class',
       'nzr_o_class',
       'nzr_b_class',
       'nzr_s_class',
       'nzr_h_class',
       'nzr_e_class',
       'nzr_r_class',
       'nzr_w_class',
       'nzr_t_class',
       'nzr_k_class',
       'nzr_a_class',
       'nzr_f_class',
       'nzr_j_class',
       'nzr_n_class',
       'nzr_y_class',
       'nzr_v_class',
       'nzr_m_class'],
 'u': ['nzubechi_grace_nwokocha'],
 'w': ['nzwpw_heavyweight_championship']}
