
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_vs = {'_': ['vs_of_california',
       'vs._ballon_fight',
       'vs_sport_tallinn',
       'vs-n_fuzed_mines',
       'vs_of_chicago',
       'vs_of_florida',
       'vs_rugby_f.c.',
       'vs._racing_2',
       'vs._the_snow',
       'vs_raw_2009'],
 'b': ['vsb_poetry_prize'],
 'c': ['vsc_high_school'],
 'e': ['vsevolod_mikhailovich_abramovich',
       'vsevolod_vyacheslavovich_ivanov',
       'vsevolod_illarionovich_pudovkin',
       'vsevolod_yemilyevich_meyerhold',
       'vsevolod_ilarionovich_pudovkin',
       'vsevolod_sergyeevich_solovyoff',
       'vsevolod_nikolayevich_merkulov',
       'vsevolod_borisovich_levenstein',
       'vsevolod_emilievich_meyerhold',
       'vsevolod_mikhaylovich_garshin',
       'vsevolod_ivanovich_romanovsky',
       'vsevolod_mikhailovich_garshin',
       'vsevolod_ivanovich_roborovsky',
       'vsevolod_emilevich_meyerhold',
       'vsevolod_mikhailovich_bobrov',
       'vsevolod_borisovich_bessonov',
       'vsevolod_sergeevich_solovyov',
       'vsevolod_leonidovich_roshko',
       'vseobecna_obcanska_strana',
       'vsevolod_i_svyatoslavich',
       'vseobecna_uverova_banka',
       'vserv_digital_services',
       'vsevolod_i_yaroslavich',
       'vsevolod_iii_yuryevich',
       'vsevolod_ii_olgovich',
       'vseslav_the_sorcerer',
       'vseslav_of_polatsk',
       'vseslav_of_polotsk',
       'vsevolod_of_pskov',
       'vsevolod_big_nest',
       'vsevolod_of_kiev',
       'vseslav_of_kiev',
       'vse_pro_lasku'],
 'f': ['vsft_g_322'],
 'g': ['vsg_altglienicke_berlin'],
 'i': ['vsi_international_school',
       'vsichni_dobri_rodaci',
       'vsichni_proti_vsem',
       'vsi_berlin_gmbh'],
 'k': ['vsk_osterholz-scharmbeck_ii',
       'vsk_osterholz_scharmbeck',
       'vsk_osterholz_ii'],
 'm': ['vsmpo_avisma_corporation'],
 'n': ['vsnl_international_canada',
       'vsnl_northern_europe',
       'vsnl_western_europe'],
 'p': ['vsp_vision_care'],
 'r': ['vsr_sr-1_snoshoo', 'vsr_v8_trophy'],
 's': ['vss_enterprise_crash',
       'vssc_central_school',
       'vss_unity_vf-01',
       'vss_high_school',
       'vss_unity_vp-03'],
 't': ['vstar_entertainment_group', 'vstol_support_ship', 'vst_&_co.'],
 'z': ['vsz_slovak_open']}
