# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import banyanclient
from banyanclient.paths.v1_mdm_update_device import post  # noqa: E501
from banyanclient import configuration, schemas, api_client

from .. import ApiTestMixin


class TestV1MdmUpdateDevice(ApiTestMixin, unittest.TestCase):
    """
    V1MdmUpdateDevice unit test stubs
        Ban & Unban Devices  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = post.ApiForpost(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 200






if __name__ == '__main__':
    unittest.main()
