
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-19T08:54:26+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "aa00dddd4a214a943f70e31db9a64e422cdfa9e7",
 "version": "1.1.20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
