
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_gk = {'_': ['gk_wien-southeast',
       'gk_butterfield',
       'gk_chesterton',
       'gk_investment',
       'gk_venkatesh',
       'gk_partners',
       'gk_durnrohr',
       'gk_software',
       'gk_moopanar',
       'gk_gilbert',
       'gk_convoys',
       'gk_persei',
       'gk_films',
       'gk_radio',
       'gk_bowes',
       'gk_tauri',
       'gk_vasan',
       'gk_reid',
       'gk_mani'],
 'b': ['gkb_opticals', 'gkb_t-34'],
 'd': ['gkd_evolution', 'gkd_legend'],
 'i': ['gkikas_magiorkinis'],
 'k': ['gkk_etzenricht', 'gkk_sibenka'],
 'm': ['gkm_grudziadz', 'gkm_variety'],
 'n': ['gkn_driveline',
       'gkn_defense',
       'gkn_sankey',
       'gkn_pallet',
       'gkn_simba',
       'gkn_plc'],
 'o': ['gko_construction'],
 'r': ['gkr_karate'],
 's': ['gks_jastrzebie', 'gks_belchatow', 'gks_katowice', 'gks_tychy'],
 'u': ['gkuthaarn_language']}
