
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_gp = {'_': ['gp_triberg-schwarzwald',
       'gp_plumenec-morbihan',
       'gp2_championship',
       'gp_investimentos',
       'gp_ouest-france',
       'gp_investments',
       'gp_fundholding',
       'gp_liberazione',
       'gp_andromedae',
       'gp_federation',
       'gp_wallonnie',
       'gp_batteries',
       'gp_challenge',
       'gp_capodarco',
       'gp_primavera',
       'gp_registrar',
       'gp_karlsruhe',
       'gp_manavgat',
       'gp_fourmies',
       'gp_beghelli',
       'gp_wallonie',
       'gp_maximoff',
       'gp_s.a.t.s.',
       'gp_transit',
       'gp_antalya',
       'gp_zeliony',
       'gp_pascuas',
       'gp_legends',
       'gp_chiasso',
       'gp3_series',
       'gp_masters',
       'gp_herning',
       'gp_horsens',
       'gp_formies',
       'gp_koirala',
       'gp2_series',
       'gp_wolber',
       'gp_laguna',
       'gp_aarhus',
       'gp_lugano',
       'gp_racing',
       'gp_plouay',
       'gp_llodio',
       'gp_series',
       'gp_viborg',
       'gp_denain',
       'gp_cholet',
       'gp_planum',
       'gp_pillai',
       'gp_rider',
       'gp2_asia',
       'gp_sippy',
       'gp_wells',
       'gp_basic',
       'gp_belek',
       'gp5_chip',
       'gp_kranj',
       'gp2x_wiz',
       'gp3_2000',
       'gp_nerli',
       'gp_capt',
       'gp_cima',
       'gp_hall',
       'gp_500',
       'gp_wu'],
 'a': ['gpa76_battery',
       'gpac_project',
       'gparted_live',
       'gpa_group',
       'gpa_f.c.'],
 'b': ['gpb_knowledge'],
 'c': ['gpcr_ultra-left',
       'gpcr_oligomer',
       'gpc_biotech',
       'gpc_sport',
       'gpc_youth',
       'gpc_mini'],
 'd': ['gpd_win', 'gpd_xd'],
 'g': ['gpgcfg_chishtian', 'gpgc_chishtian', 'gpg_mail'],
 'h': ['gph_ispat'],
 'i': ['gpiib/iiia_inhibitors', 'gpi_anchor', 'gpi_ltd'],
 'l': ['gpl_violation', 'gplv2_license', 'gpl_license'],
 'm': ['gpm_11.763966-11.871916', 'gpm_investments'],
 'o': ['gpo_telephones', 'gpot_center', 'gpo_access', 'gpo_tower', 'gpo_uk'],
 'r': ['gpr_endopeptidase',
       'gprc5_receptor',
       'gprs_modem',
       'gpr_index',
       'gpr_120'],
 's': ['gps_modernization',
       'gps_modernisation',
       'gps_reflectometry',
       'gps_applications',
       'gpsolo_magazine',
       'gps_coordinates',
       'gps_hospitality',
       'gps_coordiantes',
       'gps_meteorology',
       'gps_macpherson',
       'gps_navigation',
       'gps_dropsonde',
       'gps_navigator',
       'gps_sonobuoy',
       'gps_reciever',
       'gps_tracking',
       'gps_receiver',
       'gps_schools',
       'gps_raghava',
       'gps_drawing',
       'gps_signals',
       'gps_school',
       'gps_iir-21',
       'gps_signal',
       'gps_omens',
       'gps_phone',
       'gps_rugby',
       'gps_watch',
       'gps_iir-1',
       'gps_buoy',
       'gps_puck',
       'gps_waas',
       'gps_map',
       'gps_iii',
       'gps_l1c',
       'gps_l2c',
       'gps_l5',
       'gps_3'],
 't': ['gpt_group', 'gpt_disk'],
 'u': ['gpu_virtualization', 'gpu_switching', 'gpu_cluster']}
