
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_tx = {'_': ['tx-sector',
       'tx26-427',
       'tx-8000',
       'tx-led',
       'tx8000',
       'tx-100',
       'tx81z',
       'tx2-6',
       'tx-2',
       'tx3g',
       'tx-1',
       'tx-0',
       'tx4e',
       'tx5',
       'tx4',
       'tx2',
       'tx1',
       'tx3'],
 'a': ['txapelgorri',
       'txamantxoia',
       'txalaparta',
       'txakolina',
       'txarango',
       'txalaina',
       'txakoli',
       'txacoli',
       'txamsem',
       'txarng',
       'txa2',
       'txaa',
       'txa'],
 'b': ['txb2'],
 'c': ['txcn', 'txc'],
 'd': ['txdads', 'txdps', 'txdot'],
 'e': ['txeroki', 'txe'],
 'f': ['txf2', 'txfm', 'txf'],
 'g': ['txga'],
 'i': ['txillardegi',
       'txin-txon',
       'txistorra',
       'txintxon',
       'txintxom',
       'txirrita',
       'txindoki',
       'txistu',
       'txiki',
       'txii',
       'txi'],
 'k': ['txkf', 'txk'],
 'l': ['txlnb', 'txled', 'txl'],
 'n': ['txndc12',
       'txndc9',
       'txnrd1',
       'txndc2',
       'txnl4b',
       'txndc5',
       'txnl4a',
       'txnip',
       'txnl1',
       'txn2',
       'txn'],
 'o': ['txoriherri', 'txorierri', 'txoko'],
 'p': ['txprtconsarg', 'txprtconarg', 'txptconarg', 'txpf'],
 'r': ['txrd', 'txr'],
 's': ['txseries', 'txsh', 'txsu'],
 't': ['txtspeak',
       'txt2tags',
       'txt.fyi',
       'txt-tv',
       'txtspk',
       'txt402',
       'txtmob',
       'txtag',
       'txt-1',
       'txts',
       'txtc',
       'txtr',
       'txt'],
 'u': ['txuringa', 'txusta', 'txutxi', 'txu'],
 'v': ['txv'],
 'x': ['txx']}
