
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_np = {'np-complete_language': 'np-complete',
 'np-complete_problem': 'np-complete',
 'np-hard_problem': 'np-hard',
 'np-hard_problems': 'np-hard',
 'np_airway': 'nasopharyngeal_airway',
 'np_buu-hoi': 'buu_hoi',
 'np_complete': 'np-complete',
 'np_completeness': 'np-complete',
 'np_dodge': 'np_dodge_company',
 'np_durga': 'n._p._durga',
 'np_hard': 'np-hard',
 'np_ignatieff': 'nicholas_pavlovich_ignatiev',
 'np_nayar': 'n._p._nayar',
 'np_pradeep': 'naduparampil_pappachen_pradeep',
 'np_problem': 'np-complete',
 'np_test': 'neuropsychological_test',
 'np_testing': 'neuropsychological_test',
 'np_tests': 'neuropsychological_test',
 'npa_code': 'north_american_numbering_plan',
 'npb_mvp': 'nippon_professional_baseball_most_valuable_player_award',
 'npc_160': 'fujicolor_pro',
 'npd_funworld': 'npd_group',
 'npd_intelect': 'npd_group',
 'npd_quebec': 'new_democratic_party_of_quebec',
 'npd_reactor': 'nuclear_power_demonstration',
 'nph_400': 'fujicolor_pro',
 'npkc_coup': 'national_peace_keeping_council',
 'npl_160': 'fujicolor_pro',
 'npo_energia': 's.p._korolev_rocket_and_space_corporation_energia',
 'npo_energiya': 's.p._korolev_rocket_and_space_corporation_energia',
 'npo_lavochkin': 'lavochkin',
 'npo_mashinostroenia': 'npo_mashinostroyeniya',
 'npo_mashinostroeyenia': 'npo_mashinostroyeniya',
 'npo_mashinostroyenia': 'npo_mashinostroyeniya',
 'npo_mashinostroyeniye': 'npo_mashinostroyeniya',
 'npo_molnia': 'npo_molniya',
 'npo_pm': 'jsc_information_satellite_systems',
 'npo_polyot': 'production_corporation_polyot',
 'npower_renewables': 'rwe',
 'npr_chicago': 'chicago_public_radio',
 'npr_news': 'national_public_radio',
 'nprotect_ggp': 'nprotect_gameguard_personal_2007',
 'nprotect_ggp2007': 'nprotect_gameguard_personal_2007',
 'nps_160': 'fujicolor_pro',
 'nps_rawlinson': 'nps_rawlinson_roadway',
 'npv_compact': 'national_popular_vote_interstate_compact',
 'npy_r': 'neuropeptide_y_receptor',
 'npy_receptor': 'neuropeptide_y_receptor',
 'npz_800': 'fujicolor_pro'}
        