
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_kk = {'_': ['kk_sonik-puntamika',
       'kk_neelakantan',
       'kk_profikolor',
       'kk_rabotnicki',
       'kk_blokotehna',
       'kk_andromedae',
       'kk_crikvenica',
       'kk_hercegovac',
       'kk_motorsport',
       'kk_zeleznicar',
       'kk_superfund',
       'kk_dubrovnik',
       'kk_wloclawek',
       'kk_podgorica',
       'kk_grosuplje',
       'kk_panevezys',
       'kk_vojvodina',
       'kk_buducnost',
       'kk_meridiana',
       'kk_zrinjevac',
       'kk_doughnuts',
       'kk_jagodina',
       'kk_kumanovo',
       'kk_crnokosa',
       'kk_gostivar',
       'kk_sutjeska',
       'kk_krizevci',
       'kk_vinkovci',
       'kk_olimpija',
       'kk_pelister',
       'kk_portoroz',
       'kk_lastovka',
       'kk_hrastnik',
       'kk_strumica',
       'kk_zlatibor',
       'kk_radnicki',
       'kk_steincke',
       'kk_bratunac',
       'kk_borovica',
       'kk_partizan',
       'kk_zdravlje',
       'kk_mladost',
       'kk_maribor',
       'kk_parklji',
       'kk_ergonom',
       'kk_baltika',
       'kk_loznica',
       'kk_sloboda',
       'kk_sibenik',
       'kk_sentral',
       'kk_kvarner',
       'kk_belisce',
       'kk_zarkovo',
       'kk_elektra',
       'kk_sentjur',
       'kk_barrett',
       'kk_goswami',
       'kk_swiecie',
       'kk_vogosca',
       'kk_slavija',
       'kk_brotnjo',
       'kk_olimpas',
       'kk_radovis',
       'kk_downing',
       'kk_dubrava',
       'kk_dynamic',
       'kk_rogaska',
       'kk_kastela',
       'kk_masinac',
       'kk_gorica',
       'kk_kakanj',
       'kk_viimsi',
       'kk_centar',
       'kk_shkupi',
       'kk_thesis',
       'kk_ulcinj',
       'kk_jazine',
       'kk_zagreb',
       'kk_trogir',
       'kk_palace',
       'kk_vardar',
       'kk_igokea',
       'kk_slodes',
       'kk_mathew',
       'kk_sencur',
       'kk_dalvin',
       'kk_angeli',
       'kk_rajeev',
       'kk_vizura',
       'kk_cibona',
       'kk_leotar',
       'kk_pirot',
       'kk_rtanj',
       'kk_juggy',
       'kk_atlas',
       'kk_birla',
       'kk_kozuv',
       'kk_solin',
       'kk_zadar',
       'kk_torus',
       'kk_alkar',
       'kk_opara',
       'kk_vrsac',
       'kk_bosco',
       'kk_zabok',
       'kk_celje',
       'kk_split',
       'kk_joker',
       'kk_zemun',
       'kk_dodds',
       'kk_kalev',
       'kk_korab',
       'kk_sloga',
       'kk_nagar',
       'kk_livno',
       'kk_celik',
       'kk_tamis',
       'kk_koper',
       'kk_krka',
       'kk_agha',
       'kk_ibar',
       'kk_klik',
       'kk_best',
       'kk_seet',
       'kk_beko',
       'kk_null',
       'kk_fosu',
       'kk_star',
       'kk_hito',
       'kk_beck',
       'kk_fmp',
       'kk_mg3',
       'kk_bor',
       'kk_heo',
       'kk._30',
       'kk_tft',
       'kk_62'],
 'a': ['kkachisan_station', 'kkachiul_station', 'kkachi_durumagi'],
 'd': ['kkd_karthik'],
 'e': ['kke_architects', 'kke_exterior', 'kke_1918-55', 'kkei-ca_38'],
 'h': ['kkh_060'],
 'k': ['kkk_auxiliaries',
       'kkk_radnicki',
       'kkk_costume',
       'kkk_bosna',
       'kkk_act'],
 'n': ['kknd2:_krossfire', 'kknd_series'],
 'o': ['kkoktugakshi_nori',
       'kkondae_intern',
       'kkot_jijimi',
       'kkot_bukumi',
       'kkot_darim',
       'kkot_seom',
       'kkoch_ip',
       'kkog_16'],
 'r': ['kkr_approximation', 'kkr_03', 'kkr_25'],
 's': ['kkstb_429.1',
       'kkstb_429.9',
       'kkstb_429',
       'kkstb_269',
       'kkstb_112',
       'kkstb_265',
       'kkstb_270',
       'kkstb_229',
       'kkstb_99',
       'kkstb_30',
       'kkstb_97',
       'kkstb_73',
       'kkstb_6',
       'kks_3'],
 't': ['kktc_telsim'],
 'v': ['kkv_guitar'],
 'w': ['kkwing_stadium']}
