
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_sd = {'_': ['sd-kuriren',
       'sd.kfz.251',
       'sd-women',
       'sd-l902a',
       'sd/sdio',
       'sd22eco',
       'sd70mac',
       'sd.kfz.',
       'sd-card',
       'sd80mac',
       'sd90mac',
       'sd70ace',
       'sd40-2w',
       'sd70m-2',
       'sd45-2',
       'sd-160',
       'sd-wan',
       'sd40-2',
       'sd70i',
       'sd-03',
       'sd70m',
       'sd-10',
       'sd50f',
       'sd50s',
       'sd60m',
       'sd-70',
       'sd-40',
       'sd10',
       'sd70',
       'sd14',
       'sd26',
       'sd24',
       'sd18',
       'sd-3',
       'sd40',
       'sd-6',
       'sd50',
       'sd11',
       'sd43',
       'sd4',
       'sd3',
       'sd1',
       'sd6',
       'sd2'],
 'a': ['sdadic',
       'sdacom',
       'sdapo',
       'sdapi',
       'sdad1',
       'sdats',
       'sdarm',
       'sdars',
       'sdabc',
       'sdaie',
       'sdaw',
       'sdau',
       'sdae',
       'sdai',
       'sdax',
       'sdam',
       'sdap',
       'sdar',
       'sda'],
 'b': ['sdb-005',
       'sdb-006',
       'sdbz',
       'sdbm',
       'sdba',
       'sdbp',
       'sdbe',
       'sdbc',
       'sdb'],
 'c': ['sdccag8',
       'sdcard',
       'sdccd',
       'sdch',
       'sdck',
       'sdci',
       'sdc1',
       'sdco',
       'sdcv',
       'sdcc',
       'sdcl',
       'sdcg',
       'sdc'],
 'd': ['sdd-age', 'sddot', 'sdds', 'sddx', 'sddc', 'sdd'],
 'e': ['sde-boker',
       'sdelka',
       'sderot',
       'sdeir',
       'sdee',
       'sder',
       'sdep',
       'sdef',
       'sdes',
       'sdet',
       'sde'],
 'f': ['sdfcs',
       'sdf-2',
       'sdfla',
       'sdf-4',
       'sdf-1',
       'sdf-3',
       'sdf2',
       'sdfd',
       'sdf1',
       'sdfu',
       'sdfc',
       'sdf3',
       'sdf4',
       'sdf'],
 'g': ['sdgonline', 'sdge'],
 'h': ['sdhaf1',
       'sdhaf2',
       'sdhsaa',
       'sdhp',
       'sdhs',
       'sdhb',
       'sdha',
       'sdhd',
       'sdh'],
 'i': ['sdi-12',
       'sdind',
       'sdiri',
       'sdibt',
       'sdiru',
       'sdiff',
       'sdill',
       'sdis',
       'sdif',
       'sdiy',
       'sdio',
       'sdic',
       'sdib',
       'sdig',
       'sdia',
       'sdi'],
 'j': ['sdjff', 'sdja', 'sdj'],
 'k': ['sdkfz.251', 'sdkfz251', 'sdkpil', 'sdkfz', 'sdk2', 'sdk1', 'sdk'],
 'l': ['sdlbasic',
       'sdl.net',
       'sdla',
       'sdlc',
       'sdlt',
       'sdlv',
       'sdlg',
       'sdlp',
       'sdlr',
       'sdl'],
 'm': ['sdmcet',
       'sdml',
       'sdmr',
       'sdms',
       'sdmx',
       'sdmf',
       'sdma',
       'sdmi',
       'sdmb',
       'sdm2',
       'sdm'],
 'n': ['sdn48', 'sdn.', 'sdny', 'sdnr', 'sdna', 'sdn'],
 'o': ['sdoit', 'sdom', 'sdot', 'sdo'],
 'p': ['sdptv', 'sdpd', 'sdps', 'sdpr', 'sdpf', 'sdpb', 'sdpl', 'sdp'],
 'q': ['sdq-4', 'sdq4', 'sdq'],
 'r': ['sdram', 'sdre', 'sdrp', 'sdrc', 'sdrt', 'sdra', 'sdr'],
 's': ['sdssj0946+1006',
       'sds-page',
       'sdspage',
       'sds-gel',
       'sdscpa',
       'sds-1',
       'sdsmt',
       'sdsrt',
       'sds-4',
       'sdsf',
       'sdso',
       'sdsi',
       'sdsl',
       'sdsd',
       'sdsa',
       'sdss',
       'sdsr',
       'sdsc',
       'sdsm',
       'sds'],
 't': ['sdtv', 'sdts', 'sdtm', 'sdti', 'sdt'],
 'u': ['sdushor', 'sdups', 'sdusa', 'sdusd', 'sduis', 'sduk', 'sdub', 'sdu'],
 'v': ['sdvr2008', 'sdvr2007', 'sdvosb', 'sdvo', 'sdv'],
 'w': ['sdwap', 'sdwa', 'sdw'],
 'x': ['sdxcentral', 'sdx-102', 'sdx-105', 'sdxf'],
 'y': ['sdyshor', 'sdyc', 'sdy'],
 'z': ['sdz']}
