
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_jj = {'_': ['jj-coupling',
       'jj/wbgsp',
       'jj-3054',
       'jj3054',
       'jj-7',
       'jj-5',
       'jj-2',
       'jj+e',
       'jj-4',
       'jj72',
       'jj2',
       'jj1'],
 'a': ['jjajangmyeon',
       'jjambbong',
       'jjapaguri',
       'jjamppong',
       'jjam-fm',
       'jjaro',
       'jjap',
       'jjad',
       'jjam',
       'jja'],
 'b': ['jjb'],
 'c': ['jjcet', 'jjcc', 'jjc'],
 'd': ['jjdp'],
 'f': ['jjfes', 'jjf'],
 'g': ['jjg'],
 'h': ['jjh'],
 'i': ['jjimjilbang', 'jjinppang', 'jjigae', 'jjige', 'jjif', 'jjim'],
 'j': ['jjj'],
 'k': ['jjk'],
 'l': ['jjl'],
 'm': ['jjms'],
 'n': ['jjn'],
 'o': ['jjol-myeon',
       'jjol-myun',
       'jjolmyeon',
       'jjol-myon',
       'jjolmyun',
       'jjolmyon',
       'jjokbali',
       'jjokbari',
       'jjonak'],
 'p': ['jjp'],
 'r': ['jjrousseau', 'jjrtc', 'jjr2', 'jjr'],
 's': ['jjs-phhc', 'jjs-ch', 'jjss', 'jjs'],
 't': ['jjthomson'],
 'u': ['jjunction', 'jju'],
 'w': ['jjwbgsp'],
 'y': ['jjy']}
