
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_gv = {'a': ['gvav-rapiditas',
       'gvardeyskoye',
       'gvardejskoje',
       'gvardeiskii',
       'gvardeyskii',
       'gvadeyskoye',
       'gvardeyskiy',
       'gvardeiskiy',
       'gvardeyski',
       'gvardeiski',
       'gvardeysky',
       'gvardeisky',
       'gvardeisk',
       'gvangjsih',
       'gvangzsi6',
       'gvardeysk',
       'gvaladze',
       'gvantsa',
       'gvazava',
       "gvar'am",
       'gvazda',
       'gvarv',
       'gvax',
       'gvav',
       'gvat',
       'gva'],
 'b': ['gvb'],
 'c': ['gvcs', 'gvc'],
 'd': ['gvdes', 'gvd'],
 'e': ['gvenetadze', 'gvedysh', 'gveret', 'gved', 'gve'],
 'f': ['gvfc', 'gvfs', 'gvfl', 'gvfx', 'gvf'],
 'g': ['gvg'],
 'h': ['gvhd', 'gvhs', 'gvh'],
 'i': ['gvinum',
       'gvisor',
       'gvidas',
       'gvido',
       'gviet',
       'gvif',
       'gvil',
       'gvir',
       'gvi'],
 'k': ['gvk'],
 'l': ['gvl'],
 'm': ['gvmg', 'gvm'],
 'n': ['gvnml', 'gvn'],
 'o': ['gvozdenovic',
       'gvozdanovic',
       'gvozdyovka',
       'gvozdansko',
       'gvozdarus',
       'gvozdovka',
       'gvozdetz',
       'gvozdets',
       'gvozdevo',
       'gvodzitz',
       'gvozdac',
       'gvozdic',
       'gvozdev',
       'gvozno',
       'gvozd',
       'gvo'],
 'p': ['gvpk', 'gvpl', 'gvpa', 'gvpn', 'gvp'],
 'q': ['gvq'],
 'r': ['gvrobot', 'gvro', 'gvrp', 'gvrd', 'gvr'],
 's': ['gvs-100',
       'gvsmmc',
       'gvshp',
       'gvskg',
       'gvsig',
       'gvsd',
       'gvsr',
       'gvsu',
       'gvsb',
       'gvs'],
 't': ['gvtaps', 'gvt'],
 'u': ['gvulot', 'gvura', 'gvu'],
 'v': ['gvvv'],
 'w': ['gvwr']}
