
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_bg = {'_': ['bg_discography',
       'bg&cm_railroad',
       'bg_gottingen',
       'bg_karlsruhe',
       'bg_geminorum',
       'bg_express',
       'bg_stadium',
       'bg_capital',
       'bg_burkett',
       'bg_sharma',
       'bg_uberti',
       'bg_escher',
       'bg_crucis',
       'bg_james',
       'bg_group',
       'bg_news',
       'bg_indi',
       'bg_rock',
       'bg_bank',
       'bg_9002',
       'bg_voz',
       'bg_plc',
       'bg_uys'],
 'a': ['bgafd_awards'],
 'c': ['bgc_partners', 'bgc_2040', 'bgc_bus'],
 'f': ['bgfibank_group', 'bgfi_groupe'],
 'g': ['bgg_resolution'],
 'h': ['bgh_capital'],
 'i': ['bgi_group'],
 'l': ['bglg-cis-reg_rna', 'bgl_swamy', 'bgl_ligue', 'bgl_group'],
 'm': ['bgm-109g_gryphon',
       'bgm-109_tomahawk',
       'bgm-34_firebee',
       'bgm-75_aicbm',
       'bgmea_bhaban',
       'bgm-71_tow',
       'bgm_71'],
 'n': ['bgn/pcgn_transliteration', 'bgn/pcgn_romanization', 'bgn/pcgn_system'],
 'o': ['bgo_records', 'bgo_gemini'],
 'p': ['bgp_injection', 'bgp_hijacking', 'bgp_001'],
 'r': ['bgr_group'],
 's': ['bgsu_firelands'],
 'w': ['bgw_systems']}
