
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_bc = {'_': ['bc_politekhnika-halychyna',
       'bc_augsburg-oberhausen',
       'bc_mgzavrebi-armia',
       'bc-la/at-6a_texan',
       'bc_namur-capitale',
       'bc_lietkabelis-2',
       'bc_ecosocialists',
       'bc_conservatives',
       'bc_chernomorets',
       'bc_tsmoki-minsk',
       'bc_gargzdai-sc',
       'bc_valga-valka',
       'bc_delikatesas',
       'bc_fuenlabrada',
       'bc_novosibirsk',
       'bc_dnipro-azot',
       'bc_politekhnik',
       'bc_radviliskis',
       'bc_lietkabelis',
       'bc_legislature',
       'bc_kalev/cramo',
       'bc_winterthur',
       'bc_assessment',
       'bc_budivelnyk',
       'bc_zaporizhya',
       'bc_zalgiris-2',
       'bc_kibirkstis',
       'bc_stephenson',
       'bc_government',
       'bc200_lncrna',
       'bc_savanoris',
       'bc_ahrweiler',
       'bc_bookworld',
       'bc_athletics',
       'bc_camplight',
       'bc108_family',
       'bc_mazeikiai',
       'bc_chernihiv',
       'bc_johnstone',
       'bc_eindhoven',
       'bc_prievidza',
       'bc_panevezys',
       'bc_interior',
       'bc_fourteen',
       'bc_neptunas',
       'bc_strumica',
       'bc_kretinga',
       'bc_ternopil',
       'bc_zalgiris',
       'bc_magazine',
       'bc_liberals',
       'bc150_years',
       'bc_khanduri',
       'bc_boncourt',
       'bc_catholic',
       'bc_techasas',
       'bc_siauliai',
       'bc_juventus',
       'bc_partizan',
       'bc1_complex',
       'bc_partners',
       'bc_oostende',
       'bc_borisfen',
       'bc_ezerunas',
       'bc_research',
       'bc_augsburg',
       'bc_prometey',
       'bc_liberal',
       'bc_goverla',
       'bc_aichach',
       'bc_dzukija',
       'bc_glasses',
       'bc_sukhumi',
       'bc_donetsk',
       'bc_andorra',
       'bc_cabinet',
       'bc_nevezis',
       'bc_symbols',
       'bc_taurage',
       'bc_kursiai',
       'bc_kochmit',
       'bc_statyba',
       'bc_kormend',
       'bc_palanga',
       'bc_shekhar',
       'bc_telsiai',
       'bc_binning',
       'bc_transit',
       'bc_ferries',
       'bc_orchies',
       'bc_studies',
       'bc_cubbage',
       'bc_prienai',
       'bc_sakalai',
       'bc_terreur',
       'bc_housing',
       'bc_rustavi',
       'bc_avtodor',
       'bc_astana',
       'bc_campus',
       'bc_shumen',
       'bc_cooray',
       'bc_silute',
       'bc_report',
       'bc_khimik',
       'bc_cancer',
       'bc_kosher',
       'bc_vienna',
       'bc_sliven',
       'bc_forbes',
       'bc_titans',
       'bc_vision',
       'bc_icemen',
       'bc_racers',
       'bc_angels',
       'bc_odessa',
       'bc_enisey',
       'bc_dnipro',
       'bc_trakai',
       'bc_powder',
       'bc_yambol',
       'bc_samara',
       'bc_vaught',
       'bc_hockey',
       'bc_khimki',
       'bc_titebi',
       'bc_almaty',
       'bc_hartha',
       'bc_alytus',
       'bc_lavera',
       'bc_jonava',
       'bc_eagles',
       'bc_beroe',
       'bc_kolin',
       'bc_unics',
       'bc_bears',
       'bc_lulea',
       'bc_clark',
       'bc_place',
       'bc_parma',
       'bc_lions',
       'bc_euras',
       'bc_rugby',
       'bc_vytis',
       'bc_kalev',
       'bc_hydro',
       'bc_wheel',
       'bc_alita',
       'bc_lusis',
       'bc_cygni',
       'bc_parks',
       'bc_rytas',
       'bc_ferry',
       'bc_party',
       'bc_joshi',
       'bc_mures',
       'bc_nokia',
       'bc_games',
       'bc_raids',
       'bc_story',
       'bc_rasai',
       'bc_kiev',
       'bc_high',
       'bc_bill',
       'bc_card',
       'bc_brno',
       'bc_kyiv',
       'bc_lara',
       'bc_rich',
       'bc_rail',
       'bc_road',
       'bc_jean',
       'bc_open',
       'bc_stv',
       'bc_law',
       'bc_day',
       'bc_gas',
       'bc_ctv',
       'bc_tel',
       'bc_ndp',
       'bc_150',
       'bc_bud',
       'bc_lee',
       'bc_99',
       'bc_ad'],
 'a': ['bca_marketplace',
       'bcatp_museum',
       'bca_research',
       'bca_tower',
       'bca_assay'],
 'b': ['bcb_106.6fm', 'bcbc_blends', 'bcbs_239'],
 'c': ['bcc_observatory',
       'bcc_research',
       'bcci_awards',
       'bcc_company',
       'bcc_report',
       'bcc_weekly',
       'bcci_bank',
       'bcc_inc.'],
 'd': ['bcdr_4-6-4t',
       'bcd_galaxy',
       'bcd_number',
       'bcd_group',
       'bcd_code',
       'bcdr_28',
       'bcdr_2'],
 'e': ['bcet_gurdaspur', 'bce_emergis', 'bce_place', 'bce_inc.', 'bce_inc'],
 'f': ['bcf_wolfratshausen', 'bcf_extinguisher', 'bcfw_recursion', 'bcf_arena'],
 'g': ['bcg_diagram', 'bcg_vaccine', 'bcg_matrix'],
 'h': ['bcharre_district', 'bch_algebra', 'bch_lions', 'bch_code'],
 'i': ['bci_citirider', 'bcic_college', 'bci_algebra', 'bcia_inc.', 'bci_bus'],
 'j': ['bcjr_algorithm'],
 'k': ['bck_algebra'],
 'l': ['bcl-2-interacting_killer',
       'bcl-6_corepressor',
       'bcl_undergraduate',
       'bcl-2_protein',
       'bcl_molecular',
       'bcl-2_family',
       'bcl2-like_11',
       'bcl_limited',
       'bcl_springs',
       'bcl2-like_1',
       'bcl-2_gene',
       'bcl_102',
       'bcl_2'],
 'm': ['bcm_gravelines-dunkerque',
       'bcm_classification',
       'bcm_gravelines',
       'bcmp_network',
       'bcm_theory',
       'bcms_uav'],
 'n': ['bcn_competicion', 'bcn_nanotube', 'bcn_week', 'bcn_mes'],
 'o': ['bco-lnga_mchod-pa', 'bcore_disc'],
 'p': ['bcpl_language', 'bcp-1_cells', 'bcp_api', 'bcp_47', 'bcp_38'],
 'r': ['bcr_chisinau', 'bcr_gene'],
 's': ['bcs_championship',
       'bcs_examination',
       'bcs_conferences',
       'bcs_statistics',
       'bcs_conference',
       'bcsl_american',
       'bcs_countdown',
       'bcsl_national',
       'bcs_standings',
       'bcsl_olympic',
       'bcs_theory',
       'bcs_league',
       'bcs_clash',
       'bcs_women',
       'bcs_facs',
       'bcs_bowl',
       'bcs_ncg'],
 't': ['bct_modernization',
       'bct_commander',
       'bct_network',
       'bct_travel',
       'bctv_news',
       'bct_plus'],
 'v': ['bcv_building'],
 'w': ['bcwest_air']}
