#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# AUTO-GENERATED CONTENT
d_stem_mh = {'mha': {'mhas': []},
             'mhabit': {'mhabitant': ['mhabitants'], 'mhabited': [], 'mhabiting': []},
             'mhabitant': ['mhabitants'],
             'mhadaje': {'mhadajee': []},
             'mhaill': {'mhaille': []},
             'mhain': {'mhaine': []},
             'mhair': {'mhaire': [], 'mhairs': []},
             'mhairea': {'mhaireas': []},
             'mhaith': {'mhaithe': []},
             'mhaithea': {'mhaitheas': []},
             'mhalat': {'mhalation': []},
             'mham': {'mhammed': []},
             'mhame': {'mhamed': []},
             'mhand': {'mhande': []},
             'mhang': {'mhanges': []},
             'mhangwan': {'mhangwane': []},
             'mhaphysiqu': {'mhaphysique': []},
             'mhappi': {'mhappy': []},
             'mhar': {'mhars': []},
             'mharatta': {'mharattas': []},
             'mhask': {'mhaske': []},
             'mhatr': {'mhatre': []},
             'mhau': {'mhaus': []},
             'mhb': {'mhbs': []},
             'mhc': {'mhcs': []},
             'mhcassoci': {'mhcassociated': []},
             'mhcbind': {'mhcbinding': []},
             'mhcdepend': {'mhcdependent': []},
             'mhcencod': {'mhcencoded': []},
             'mhchao': {'mhchaos': []},
             'mhclink': {'mhclinked': []},
             'mhcpeptid': {'mhcpeptide': []},
             'mhcrestrict': {'mhcrestricted': []},
             'mhcunrestrict': {'mhcunrestricted': []},
             'mhd': {'mhds': []},
             'mhe': {'mhes': []},
             'mhea': {'mheas': []},
             'mhen': {'mhens': []},
             'mhenri': {'mhenry': []},
             'mhent': {'mhented': []},
             'mhepe': {'mhepes': []},
             'mher': {'mhers': []},
             'mherent': {'mherently': []},
             'mherit': {'mheritance': [], 'mherited': []},
             'mhetra': {'mhetras': []},
             'mhf': {'mhfs': []},
             'mhh': {'mhhs': []},
             'mhhode': {'mhhodes': []},
             'mhi': {'mhis': [], 'mhy': []},
             'mhiag': {'mhiage': []},
             'mhibit': {'mhibited': [], 'mhibition': []},
             'mhibitor': {'mhibitors': []},
             'mhibitori': {'mhibitory': []},
             'mhic': {'mhics': []},
             'mhida': {'mhidas': []},
             'mhisand': {'mhisande': []},
             'mhistori': {'mhistory': []},
             'mhitari': {'mhitary': []},
             'mhjtari': {'mhjtary': []},
             'mhl': {'mhls': []},
             'mhlangan': {'mhlangane': []},
             'mhlathuz': {'mhlathuze': []},
             'mhlatuz': {'mhlatuze': []},
             'mhli': {'mhly': []},
             'mhloph': {'mhlophe': []},
             'mhm': {'mhms': []},
             'mhnoir': {'mhnoire': ['mhnoires']},
             'mhnoirc': {'mhnoircs': []},
             'mhnoire': ['mhnoires'],
             'mho': {'mho': []},
             'mhoir': {'mhoire': []},
             'mhomogen': {'mhomogeneous': []},
             'mhondoro': {'mhondoros': []},
             'mhot': {'mhots': []},
             'mhote': {'mhotes': []},
             'mhous': {'mhouse': []},
             'mhp': {'mhps': []},
             'mhr': {'mhrs': []},
             'mhrt': {'mhrts': []},
             'mhsuscept': {'mhsusceptible': []},
             'mht': {'mhts': []},
             'mhu': {'mhus': []},
             'mhuigh': {'mhuighe': []},
             'mhuir': {'mhuire': []},
             'mhuiri': {'mhuiris': []},
             'mhuirn': {'mhuirne': []},
             'mhuman': {'mhumanity': []},
             'mhv': {'mhvs': []},
             'mhw': {'mhws': []}}
