
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_hc = {'hc-130_hercules': 'lockheed_hc-130',
 'hc-130n_hercules': 'lockheed_hc-130',
 'hc-130p_hercules': 'lockheed_hc-130',
 'hc_900': 'kc_85',
 'hc_airways': 'star1_airlines',
 'hc_artmann': 'h._c._artmann',
 'hc_bailey': 'h._c._bailey',
 'hc_baldridge': 'h._c._baldridge',
 'hc_barys': 'barys_astana',
 'hc_bolzano': 'bolzano-bozen_foxes',
 'hc_brno': 'kometa_brno',
 'hc_coombs': 'h._c._coombs',
 'hc_cska': 'hc_cska_moscow',
 'hc_evans': 'h._c._evans',
 'hc_grierson': 'herbert_john_clifford_grierson',
 'hc_hansen': 'h._c._hansen',
 'hc_jihlava': 'hc_dukla_jihlava',
 'hc_lada': 'hc_lada_togliatti',
 'hc_lamacraft': 'h._c._lamacraft',
 'hc_lausanne': 'lausanne_hockey_club',
 'hc_loc': 'matt_knowles',
 'hc_mcneile': 'h._c._mcneile',
 'hc_neuilly-sur-marne': 'bisons_de_neuilly-sur-marne',
 'hc_omsk': 'avangard_omsk',
 'hc_patten': 'h._c._patten',
 'hc_potter': 'h._c._potter',
 'hc_raikes': 'henry_cecil_raikes',
 'hc_sierre': 'hc_sierre-anniviers',
 'hc_speir': 'h._c._speir',
 'hc_strache': 'heinz-christian_strache',
 'hc_verma': 'harish_chandra_verma',
 'hc_westermann': 'h._c._westermann',
 'hca_harrison': 'h._c._a._harrison',
 'hca_inc.': 'hospital_corporation_of_america',
 'hcc_40': 'chloromethane',
 'hce_childers': 'hugh_childers',
 'hcf_domain': 'gcd_domain',
 'hcfc_21': 'dichlorofluoromethane',
 'hcl_acid': 'hydrochloric_acid',
 'hcl_corporation': 'hcl_enterprise',
 'hcl_infosystems': 'hcl_enterprise',
 'hcl_technologies': 'hcl_enterprise',
 'hcm_city': 'ho_chi_minh_city',
 'hcm_metro': 'ho_chi_minh_city_metro',
 'hcmc_airport': 'tan_son_nhat_international_airport',
 'hcn_channels': 'hcn_channel',
 'hco_bonsor': 'cosmo_bonsor',
 'hcs_rawat': 'harish_chandra_singh_rawat',
 'hcv_ires': 'hepatitis_c_virus_internal_ribosome_entry_site',
 'hcy_522': 'helios_airways_flight_522'}
        