#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# AUTO-GENERATED CONTENT
d_stem_rv = {'rva': {'rvas': []},
             'rvabl': {'rvable': []},
             'rvad': {'rvads': []},
             'rval': {'rvals': []},
             'rvalu': {'rvalue': ['rvalues']},
             'rvaluat': {'rvaluation': []},
             'rvalue': ['rvalues'],
             'rvan': {'rvans': []},
             'rvanc': {'rvance': []},
             'rvant': {'rvants': []},
             'rvari': {'rvary': []},
             'rvasiv': {'rvasive': []},
             'rvation': {'rvational': [], 'rvations': []},
             'rvativ': {'rvative': ['rvatives']},
             'rvative': ['rvatives'],
             'rvatori': {'rvatory': []},
             'rvatur': {'rvature': []},
             'rvben': {'rvbens': []},
             'rvbu': {'rvbus': []},
             'rvc': {'rvcs': []},
             'rvcri': {'rvcry': []},
             'rvd': {'rvds': []},
             'rvdt': {'rvdts': []},
             'rve': {'rf': []},
             'rveal': {'rvealed': []},
             'rveillanc': {'rveillance': []},
             'rvel': {'rvels': []},
             'rvellou': {'rvellous': []},
             'rvelop': {'rvelopment': []},
             'rvelou': {'rvelous': []},
             'rvene': {'rvening': []},
             'rvent': {'rvents': []},
             'rvention': {'rventions': []},
             'rvenu': {'rvenue': []},
             'rver': {'rvers': []},
             'rverag': {'rverage': []},
             'rveri': {'rvery': []},
             'rverrg': {'rverrge': []},
             'rvers': {'rverse': []},
             'rveryon': {'rveryone': []},
             'rveryth': {'rverything': []},
             'rvest': {'rvested': [], 'rvesting': []},
             'rvey': {'rveyed': [], 'rveys': []},
             'rvfescen': {'rvfescens': []},
             'rvfu': {'rvfus': []},
             'rvfv': {'rvfvs': []},
             'rvi': {'rvis': [], 'rvy': []},
             'rvicc': {'rviccs': []},
             'rvice': {'rvices': [], 'rvicing': []},
             'rvidenc': {'rvidence': []},
             'rvidig': {'rvidiger': []},
             'rview': {'rviewed': [], 'rviews': []},
             'rvill': {'rville': []},
             'rvin': {'rvins': []},
             'rving': {'rvings': []},
             'rviou': {'rvious': []},
             'rviro': {'rviros': []},
             'rvise': {'rvised': []},
             'rvisor': {'rvisors': []},
             'rvisori': {'rvisory': []},
             'rvive': {'rvived': [], 'rviving': []},
             'rvivor': {'rvivors': []},
             'rvland': {'rvlands': []},
             'rvlc': {'rvlcs': []},
             'rvle': {'rvles': []},
             'rvm': {'rvms': []},
             'rvn': {'rvns': []},
             'rvo': {'rvos': []},
             'rvoir': {'rvoirs': []},
             'rvolut': {'rvolution': []},
             'rvolutionari': {'rvolutionary': []},
             'rvord': {'rvords': []},
             'rvori': {'rvory': []},
             'rvork': {'rvorks': []},
             'rvot': {'rvots': []},
             'rvou': {'rvous': []},
             'rvp': {'rvps': []},
             'rvpavvi': {'rvpavvis': []},
             'rvpavvo': {'rvpavvos': []},
             'rvpawo': {'rvpawos': []},
             'rvpe': {'rvpes': []},
             'rvpo': {'rvpos': []},
             'rvr': {'rvrs': []},
             'rvrri': {'rvrry': []},
             'rvt': {'rvts': []},
             'rvth': {'rvths': []},
             'rvu': {'rvus': []},
             'rvvacat': {'rvvacations': []}}
