#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# AUTO-GENERATED CONTENT
d_stem_rw = {'rwa': {'rwas': []},
             'rwagasor': {'rwagasore': []},
             'rwai': {'rwais': []},
             'rwanda': {'rwanda': []},
             'rwandai': {'rwandais': []},
             'rwandais': {'rwandaise': ['rwandaises']},
             'rwandaise': ['rwandaises'],
             'rwandan': {'rwandan': []},
             'rwandes': {'rwandese': []},
             'rwanyarar': {'rwanyarare': []},
             'rward': {'rwarded': [], 'rwards': []},
             'rwave': {'rwaves': []},
             'rway': {'rways': []},
             'rwc': {'rwcs': []},
             'rwe': {'rwes': []},
             'rwebishengy': {'rwebishengye': []},
             'rweiv': {'rweived': []},
             'rwelv': {'rwelve': []},
             'rwenri': {'rwenry': []},
             'rwenti': {'rwenties': [], 'rwenty': []},
             'rwentiethcenturi': {'rwentiethcentury': []},
             'rwentyf': {'rwentyfive': []},
             'rwenzori': {'rwenzoris': []},
             'rwer': {'rwers': []},
             'rwerer': {'rwerere': []},
             'rwerv': {'rwerved': []},
             'rwg': {'rwgs': []},
             'rwhelm': {'rwhelming': []},
             'rwhi': {'rwhy': []},
             'rwhoi': {'rwhois': []},
             'rwi': {'rwis': [], 'rwy': ['rwys']},
             'rwig': {'rwigs': []},
             'rwin': {'rwins': []},
             'rwist': {'rwisted': []},
             'rwk': {'rwks': []},
             'rwli': {'rwly': []},
             'rwm': {'rwms': []},
             'rwma': {'rwmas': []},
             'rwn': {'rwns': []},
             'rwo': {'rwos': []},
             'rwolut': {'rwolution': []},
             'rwomir': {'rwomire': []},
             'rword': {'rwords': []},
             'rwork': {'rworks': []},
             'rworth': {'rworths': []},
             'rwp': {'rwps': []},
             'rwqcb': {'rwqcbs': []},
             'rwr': {'rwrs': []},
             'rwt': {'rwts': []},
             'rwult': {'rwults': []},
             'rwy': ['rwys']}
