
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_fn = {'_': ['fn_browning_m1910',
       'fn_f2000_tactical',
       'fn_grand_browning',
       'fn_baby_browning',
       'fn_mininimi_para',
       'fn_model_1910/22',
       'fn_canis_majoris',
       'fn_police_rifle',
       'fn_model_30-11',
       'fn_minimi_para',
       'fn_model_10/22',
       'fn_five_seven',
       'fn_model_1910',
       'fn_fnp_series',
       'fn_model_1949',
       'fn_model_1900',
       'fn_model_1903',
       'fn_model_1922',
       'fn_high_power',
       'fn_m249_saw',
       'fn_a1a_spr',
       'fn_p90_pdw',
       'fn_a4_spr',
       'fn_a3_spr',
       'fn_a2_spr',
       'fn_a1_spr',
       'fn_a5_spr',
       'fn_303_p',
       'fn_hp_da',
       'fn_a3_g'],
 'b': ['fnb_varsity_cup', 'fnb_v_rosenblum', 'fnb_v_lynn'],
 'c': ['fnc_entertainment_discography'],
 'g': ['fng_logistics_company'],
 'l': ['fnl_cup_2012'],
 'm': ['fnm_socimi_coaches', 'fnm_class_e.750'],
 'n': ['fnn_date_line'],
 's': ['fnss_sharpshooter_turret',
       'fnss_defence_systems',
       'fns_music_festival',
       'fns_aura_ii'],
 't': ['fntsy_sports_network'],
 'x': ['fnx_mining_company']}
