
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_qi = {'qi_bai_shi': 'qi_baishi',
 'qi_huan_gong': 'duke_huan_of_qi',
 'qi_qi_haer': 'qiqihar',
 'qi_qiao_ban': 'tangram',
 'qi_qiao_jie': 'qixi_festival',
 'qi_tai_he': 'qitaihe',
 'qi_wu_di': 'emperor_wu_of_southern_qi',
 'qi_xiao_fu': 'painted_faces',
 'qi_yu_wu': 'qi_yuwu',
 'qi_zhong_stadium': 'qizhong_forest_sports_city_arena',
 'qian_xun_xue': 'xue_family_murder_and_abandonment',
 'qiannan_autonomous_prefecture': 'qiannan_buyei_and_miao_autonomous_prefecture',
 'qiao_ge_ru': 'melungtse',
 'qiao_qian_jin': 'cute_princess',
 'qibla_cola_company': 'qibla_cola',
 'qide_international_airport': 'kai_tak_airport',
 'qie_mo_county': 'qiemo_county',
 'qila_rai_pithora': 'history_of_delhi',
 'qilich_arslan_i': 'kilij_arslan_i',
 'qin_huang_dao': 'qinhuangdao',
 'qin_ke_qing': 'qin_keqing',
 'qin_min_dang': 'people_first_party',
 'qin_mu_gong': 'duke_mu_of_qin',
 'qin_shi_gu': 'stone_drums_of_qin',
 'qin_shi_haungdi': 'qin_shi_huang',
 'qin_shi_huang-di': 'qin_shi_huang',
 'qin_shi_huangdi': 'qin_shi_huang',
 'qin_stone_drums': 'stone_drums_of_qin',
 'qin_wu_yang': 'qin_wuyang',
 'qin_xiao_gong': 'duke_xiao_of_qin',
 'qing-yuan_legitimacy_debate': 'qing_and_yuan_dynasties_debate',
 'qing_chinese_empire': 'qing_dynasty',
 'qing_han_feast': 'manchu_han_imperial_feast',
 'qing_imperial_house': 'aisin_gioro',
 'qing_ming_festival': 'qingming_festival',
 'qing_ming_jie': 'qingming_festival',
 'qing_yan_fang': 'marble_boat',
 'qingchengshan--dujiangyan_national_park': 'mount_qingcheng',
 'qingdao_international_airport': 'qingdao_liuting_international_airport',
 'qingdao_international_marina': 'qingdao_international_sailing_centre',
 'qingdao_liuting_airport': 'qingdao_liuting_international_airport',
 'qingdao_yizhong_center': 'yizhong_sports_center',
 'qingdao_yizhong_hainiu': 'qingdao_jonoon_f.c.',
 'qinghaihu_national_park': 'qinghai_lake',
 'qingjin_international_airport': 'chongjin_airport',
 'qingjin_yulang_airport': 'chongjin_airport',
 'qingming_shanghe_tu': 'along_the_river_during_the_qingming_festival',
 'qingzhou_international_airport': 'cheongju_airport',
 'qinling_mountain_range': 'qinling_mountains',
 'qiong_wen_min': 'hainanese',
 'qiqihar_medical_university': 'qiqihar_university',
 'qirim_muhtar_cumhuriyeti': 'crimea',
 'qiryat_eliezer_stadium': 'kiryat_eliezer_stadium',
 'qiryat_shemona_airport': 'kiryat_shmona_airport',
 'qishla_of_mecca': 'the_qishla_of_mecca',
 'qiyaam_al_layl': 'tahajjud',
 'qiyam_al_layl': 'tahajjud',
 'qiyunshan_national_park': 'mount_qiyun'}
        