
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_jc = {'jc69': 'substitution_model',
 'jcag': 'justice_commandos_against_armenian_genocide',
 'jcaho': 'joint_commission',
 'jcamp': 'joint_committee_on_atomic_and_molecular_physical_data',
 'jcan': 'joint_capability_for_airborne_networking',
 'jcaps': 'java_caps',
 'jcbb': 'joint_compatibility_branch_and_bound',
 'jcbdieselmax': 'jcb_dieselmax',
 'jcboe': 'jersey_city_public_schools',
 'jcca': 'john_curtin_college_of_the_arts',
 'jccc': 'johnson_county_community_college',
 'jcchs': 'jackson_county_comprehensive_high_school',
 'jccic': 'united_states_congress_joint_committee_on_inaugural_ceremonies',
 'jcdm': 'jean_charles_de_menezes',
 'jcet': 'joint_combined_exchange_training',
 'jcfargo': 'j._c._fargo',
 'jchs': 'jewish_community_high_school_of_the_bay',
 'jcics': 'journal_of_chemical_information_and_modeling',
 'jcids': 'joint_capabilities_integration_development_system',
 'jcim': 'journal_of_chemical_information_and_modeling',
 'jclu': 'japan_civil_liberties_union',
 'jcmateri': 'terry_tremaine',
 'jcmc': 'jersey_city_medical_center',
 'jcmf': 'union_of_czech_mathematicians_and_physicists',
 'jcmidge': 'jc_midge',
 'jcmotf': 'joint_civil-military_operations_task_force',
 'jcms': 'jcm',
 'jcmt': 'james_clerk_maxwell_telescope',
 'jcmu': 'japan_center_for_michigan_universities',
 'jcnerr': 'jacques_cousteau_national_estuarine_research_reserve',
 'jcoe': 'jordanhill_college',
 'jcom': 'j2_global_communications',
 'jcop': 'java_card_openplatform',
 'jcoty': 'car_of_the_year_japan',
 'jcpc': 'judicial_committee_of_the_privy_council',
 'jcpds': 'international_centre_for_diffraction_data',
 'jcpenney': 'j._c._penney',
 'jcpenneys': 'j._c._penney',
 'jcpenny': 'j._c._penney',
 'jcpennys': 'j._c._penney',
 'jcpes': 'joint_center_for_political_and_economic_studies',
 'jcps': 'jefferson_county_public_schools',
 'jcrew': 'j.crew',
 'jcsat-6': 'jcsat-4a',
 'jcss': 'jesus_christ_superstar',
 'jcsu': 'johnson_c._smith_university',
 'jctlm': 'joint_committee_for_traceability_in_laboratory_medicine',
 'jcwhitney': 'jc_whitney'}
        