
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_kv = {'_': ['kv_channel-interacting_proteins',
       'kv1.2_potassium_channel',
       'kv1.5_potassium_channel',
       'kv1.3_potassium_channel',
       'kv1.4_potassium_channel',
       'kv1.1_potassium_channel',
       'kv1.6_potassium_channel',
       'kv_racing_technology',
       "kv_men's_basketball",
       'kv-1_heavy_tank',
       'kv_krishna_iyer',
       'kv_adler_rauxel',
       'kv_iit_chennai',
       'kv_krishna_rao',
       'kv-1_and_kv-2',
       'kv_heavy_tank',
       'kv-1e_m_1941',
       'kv-1_m_1942'],
 'a': ['kvaenangen_concentration_camp',
       'kvalifikacija_za_millstreet',
       'kvacany,_presov_district',
       'kvaegtorvet_railway_halt',
       'kvartetten_som_sprangdes',
       'kvaerner_masa_yards',
       'kvaerner_govan_ltd',
       'kvartal_95_studio',
       'kvat_food_city'],
 'c': ['kvc_health_systems'],
 'e': ['kvernes_stave_church'],
 'h': ['kvh_co._ltd.'],
 'i': ['kvikkalkul_programming_language',
       'kvindelige_kunstneres_samfund',
       'kvitkove,_ternopil_oblast',
       'kvinesdal_rock_festival',
       'kviteseid_old_church',
       'kvitt_eller_dubbelt',
       'kvikne_copper_works',
       'kvinden_&_samfundet',
       'kvinna_utan_ansikte',
       'kvinnorna_pa_taket',
       'kvinnan_bakom_allt',
       'kvinna_till_kvinna',
       'kvinnliga_ik_sport',
       'kvik_hockey_arena',
       'kvinnor_och_barn',
       'kvinnen_og_tiden',
       'kvinner_og_klaer',
       'kvik_halden_f.k.',
       'kvik_halden_fk',
       'kvinna_&_man'],
 'l': ['kvly/kthi_tv_mast', 'kvly_tv_antenna', 'kvly_tv_tower', 'kvly_tv_mast'],
 'p': ['kvp_ramachandra_rao'],
 's': ['kvsk_united_overpelt-lommel'],
 'u': ['kvue_tv_tower'],
 'v': ['kvv_crossing_elewijt', 'kvv_quick_boys']}
