
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_xm = {'_': ['xm1203_non-line-of-sight_cannon',
       'xm_satellite_radio/footprints',
       'xm1111_mid-range_munition',
       'xm107/m107_barrett_rifle',
       'xm736_8-inch_projectile',
       'xm8_armament_subsystem',
       'xm174_grenade_launcher',
       'xm148_grenade_launcher',
       'xm-x_crossbone_gundam',
       'xm_gravity_indonesia',
       'xm110_sniper_rifle',
       'xm_satellite_radio',
       'xm25_sniper_rifle',
       'xm_sports_nation',
       'xm-7_spider_mine',
       'xm_sirius_merger',
       'xm_extreme_talk',
       'xm913_chain_gun',
       'xm_liquid_metal',
       'xm_public_radio',
       'xm_radio_canada',
       'xm_hd_surround',
       'xm_comedy_150',
       'xm_music_lab'],
 'a': ['xmas_lemmings_1991',
       'xmas_lemmings_1992',
       'xmas_tree_cluster',
       'xmas_party_album',
       'xmas_tree_attack',
       'xmas_ear_bender',
       'xmas_port_scan'],
 'e': ['xmen_origins_wolverine'],
 'l': ['xml-binary_optimized_packaging',
       'xml_transformation_languages',
       'xml_denial-of-service_attack',
       'xml_transformation_language',
       'xml_certified_professional',
       'xml_professional_publisher',
       'xml_certification_program',
       'xml_metadata_interchange',
       'xml_master_professional',
       'xml_paper_specification',
       'xml_template_processor',
       'xml_forms_architecture',
       'xml_enabled_networking',
       'xml_digital_signature',
       'xml_enabled_directory',
       'xml_management_system',
       'xml_information_set',
       'xml_template_system',
       'xml_template_engine',
       'xml_native_database',
       'xml_query_language',
       'xml_schema_editors',
       'xml_encoding_rules',
       'xml_web_services',
       'xml_for_analysis',
       'xml_data_binding',
       'xml_data_package',
       'xml_object_model',
       'xml_master_basic',
       'xml_data_reduced',
       'xml_topic_maps',
       'xml_and_mime',
       'xml_tag_set'],
 'm': ['xmm_cluster_survey'],
 'p': ['xmpp_standards_foundation'],
 's': ['xms_capital_partners', 'xms_mail_server'],
 'u': ['xmucane_and_xpiacoc', 'xmucane_and_xpiayoc']}
