
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rb = {'_': ['rb26dett',
       'rb-tree',
       'rb-3007',
       'rb25det',
       'rb-120',
       'rb-66a',
       'rb-66b',
       'rb-ild',
       'rb1cc1',
       'rb-101',
       'rb-66c',
       'rb-98',
       'rb-74',
       'rb-66',
       'rb-64',
       'rb545',
       'rb-36',
       'rb199',
       'rb401',
       'rb2te',
       'rb-50',
       'rb-69',
       'rb-57',
       'rb-75',
       'rb-99',
       'rb-45',
       'rb211',
       'rb293',
       'rb-47',
       'rb-26',
       'rb2o',
       'rb93',
       'rb-1',
       'rb-m',
       'rb5x',
       'rb4',
       'rb3',
       'rb2',
       'rb1'],
 'a': ['rbase', 'rbaf', 'rbar', 'rbai', 'rbac', 'rba'],
 'b': ['rbbs-pc',
       'rbbp7',
       'rbbp6',
       'rbbp8',
       'rbbfc',
       'rbbp5',
       'rbbp9',
       'rbbp4',
       'rbbs',
       'rbbr',
       'rbbb',
       'rbb'],
 'c': ['rbcg30', 'rbcsnz', 'rbclo4', 'rbck1', 'rbcs', 'rbcl', 'rbc'],
 'd': ['rbds', 'rbdf', 'rbd'],
 'e': ['rbe2', 'rbe'],
 'f': ['rbfox1', 'rbf'],
 'g': ['rbg-azimuth', 'rbgh', 'rbge', 'rbgs'],
 'h': ['rbhus', 'rbhu', 'rbhc', 'rbhs', 'rbh'],
 'i': ['rbiex', 'rbis', 'rbih', 'rbia', 'rbic', 'rbi'],
 'k': ['rbk-250', 'rbk-500', 'rbkc', 'rbk'],
 'l': ['rbl2', 'rbl1', 'rbl'],
 'm': ['rbmk-1000',
       'rbmedia',
       'rbm28',
       'rbm12',
       'rbm22',
       'rbm17',
       'rbm47',
       'rbm19',
       'rbm10',
       'rbmks',
       'rbm26',
       'rbm15',
       'rbm8a',
       'rbm33',
       'rbm34',
       'rbm11',
       'rbms1',
       'rbms3',
       'rbm23',
       'rbm25',
       'rbm39',
       'rbm14',
       'rbms',
       'rbmk',
       'rbm4',
       'rbmu',
       'rbm5',
       'rbmx',
       'rbm6',
       'rbm3',
       'rbmn',
       'rbm7',
       'rbmw',
       'rbm9',
       'rbm'],
 'n': ['rbno3', 'rbny', 'rbnz', 'rbnh', 'rbn'],
 'o': ['rbocs', 'rboc', 'rboh', 'rbob', 'rbos', 'rbox', 'rbo'],
 'p': ['rbp10',
       'rbpms',
       'rbp2',
       'rbpf',
       'rbp7',
       'rbp4',
       'rbp3',
       'rbpj',
       'rbp1',
       'rbp'],
 'q': ['rbq'],
 'r': ['rbrvs', 'rbr'],
 's': ['rbscript',
       'rbs-70',
       'rbs-15',
       'rbs15',
       'rbsoa',
       'rbsa',
       'rbst',
       'rbsp',
       'rbsd',
       'rbsl',
       'rbss',
       'rbs'],
 't': ['rbtree', 'rbtn2', 'rbtt', 'rbti', 'rbt'],
 'u': ['rbu-6000', 'rbu-1000', 'rbu-1200', 'rbu'],
 'v': ['rbv'],
 'w': ['rbw'],
 'x': ['rbx6jm', 'rbx1', 'rbx'],
 'y': ['rbyc', 'rby'],
 'z': ['rbznh', 'rbz']}
