
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_q_ = {'_': ['q2343-bx418',
       'q0906+6930',
       'q97.2fm',
       'q104.3',
       'q100.5',
       'q94-fm',
       'q15x25',
       'q9550',
       'q4000',
       'q-107',
       'q97.2',
       'q-200',
       'q97.9',
       'q33ny',
       'q.931',
       'q94fm',
       'q-400',
       'q400x',
       'q.7xx',
       'q9300',
       'q-102',
       'q-40',
       'q.30',
       'q-45',
       'q-35',
       'q-94',
       'q103',
       'q.10',
       'q500',
       'q102',
       'q.94',
       'q931',
       'q-22',
       'q.95',
       'q-30',
       'q104',
       'q113',
       'q300',
       'q200',
       'q111',
       'q-38',
       'q400',
       'q106',
       'q112',
       'q107',
       'q114',
       'q-16',
       'q100',
       'q-92',
       'q110',
       'q-95',
       'q-10',
       'q.92',
       'q101',
       'q150',
       'q.22',
       'q92',
       'q.4',
       'q-9',
       'q10',
       'q.2',
       'q95',
       'q96',
       'q41',
       'q31',
       'q70',
       'q45',
       'q61',
       'q12',
       'q55',
       'q60',
       'q40',
       'q-7',
       'q42',
       'q-6',
       'q-3',
       'q.5',
       'q53',
       'q.3',
       'q49',
       'q32',
       'q22',
       'q16',
       'q13',
       'q17',
       'q87',
       'q30',
       'q.6',
       'q68',
       'q47',
       'q11',
       'q72',
       'q-4',
       'q50',
       'q65',
       'q69',
       'q.9',
       'q-2',
       'q.7',
       'q38',
       'q94',
       'q.1',
       'q98',
       'q25',
       'q35',
       'q-1',
       'q-5',
       'q99'],
 'a': ['q-analogues',
       'q-analysis',
       "q'anjob'al",
       "q'asaqucha",
       'q-analogue',
       'q-analogs',
       "q'atawini",
       "q'aysiri",
       'q-analog',
       "q'asiri",
       "q'axilu",
       'q.a.p.',
       "q'ari",
       'q&a',
       'q3a',
       'q+a'],
 'b': ['q-binomial',
       'q@bizd@r@',
       'q-basic',
       'q-boat',
       'q.b.a.',
       'q-ball',
       'q-band',
       'q*bert',
       'q-bio',
       'q-bus',
       'q-bah',
       'q-boy',
       'q-be',
       'q2b'],
 'c': ['q-construction',
       'q-clearance',
       'q-calculus',
       'q-commerce',
       'q-chastic',
       'q-course',
       'q-celtic',
       'q-cells',
       'q-chem',
       'q-cert',
       'q-code',
       'q@cr@s',
       'q-cif'],
 'd': ['q-differentiation',
       'q@dim@likqislaq',
       'q-deformation',
       'q-difference',
       'q-derivative',
       'q-division',
       'q@dimk@nd',
       'q-dance',
       'q.d.iii',
       'q@dirli',
       'q@dili',
       'q2dm1',
       'q-dos',
       'q-day',
       'q-d-s'],
 'e': ['q-exponential', "q'eqchi'", 'q.e.f.', 'q.e.d.', "q'ero", 'q.e.d'],
 'f': ['q-function',
       'q-factor',
       'q-force',
       'q@f@rli',
       'q-fever',
       'q-flex',
       'q-free',
       'q-fish',
       'q-feel'],
 'g': ['q-guidance', 'q-games', 'q-gram', 'q.g.a.', 'q-go'],
 'h': ['q@hr@manb@yli', 'q@hr@manli'],
 'i': ["q'illuqucha",
       "q'illumayu",
       "q'isanani",
       'q-in-law',
       "q'ilani",
       "q'iwiri",
       'q-in-q',
       "q'illu",
       'q.i.',
       'q.i',
       'q-i'],
 'k': ['q-ko-chan', 'q2ktvq', 'q2k'],
 'l': ['q-learning',
       'q-loader',
       'q-league',
       'q-linear',
       'q@l@duz',
       'q@l@gah',
       'q@l@bin',
       'q-link',
       'q-less',
       'q-lan'],
 'm': ['q-machine',
       'q-measure',
       'q-matrix',
       'q@m@rvan',
       'q-metal',
       'q-mack',
       'q-max',
       'q-man'],
 'n': ['q-number', 'q@nid@r@', 'q-notes', 'q-noise', 'q-net'],
 'o': ['q.o.d.', 'q4os'],
 'p': ['q-productions',
       'q-principle',
       'q-project',
       'q-plate',
       'q.p.r.',
       'q-park',
       'q-pits',
       'q-pace',
       'q-pid',
       'q-pit',
       'q-pop',
       'q-pcr'],
 'q': ['q.q.q.'],
 'r': ['q3radiant',
       'q@ribl@r',
       'q-report',
       'q@riblik',
       'q-rating',
       'q@rv@nd',
       'q@ribli',
       'q@rs@l@',
       'q-roxin',
       'q-rich',
       'q@rch@',
       'q@r@r',
       'q@r@h',
       'q-ray'],
 's': ['q-smartphone',
       'q-statistic',
       'q-switching',
       'q-switched',
       'q-squared',
       'q-systems',
       'q-signal',
       'q-switch',
       'q-series',
       'q-sensei',
       'q-symbio',
       'q-school',
       'q-server',
       'q-slope',
       'q-siren',
       'q-ships',
       'q-sound',
       'q-star',
       'q-ship',
       'q@sil',
       'q@s@d',
       'q.sig'],
 't': ['q-telecom',
       'q-turn',
       'q.t.v.',
       'q-tips',
       'q-tee',
       'q-tel',
       'q-tip',
       'q-tex',
       'q-tv'],
 'u': ['q.u.i.e.t.',
       "q'ullq'uni",
       'q.u.e.e.n.',
       "q'uq'umatz",
       "q'urawiri",
       "q'umarkaj",
       'q-unique',
       'q.u.b.e.',
       "q'ursha"],
 'v': ['q-vectors', 'q-value', 'q@voy'],
 'w': ['q-workshop', 'q-warrior', 'q-waves', 'q-wave', 'q2wf'],
 'y': ['q-york'],
 'z': ['q@zvinoba', 'q@zli', 'q-zar']}
