# coding: utf-8

"""
    herd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.178.0-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import herdsdk
from herdsdk.api.attribute_value_list_api import AttributeValueListApi  # noqa: E501
from herdsdk.rest import ApiException


class TestAttributeValueListApi(unittest.TestCase):
    """AttributeValueListApi unit test stubs"""

    def setUp(self):
        self.api = herdsdk.api.attribute_value_list_api.AttributeValueListApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_attribute_value_list_create_attribute_value_list(self):
        """Test case for attribute_value_list_create_attribute_value_list

        createAttributeValueList  # noqa: E501
        """
        pass

    def test_attribute_value_list_delete_attribute_value_list(self):
        """Test case for attribute_value_list_delete_attribute_value_list

        deleteAttributeValueList  # noqa: E501
        """
        pass

    def test_attribute_value_list_get_attribute_value_list(self):
        """Test case for attribute_value_list_get_attribute_value_list

        getAttributeValueList  # noqa: E501
        """
        pass

    def test_attribute_value_list_get_attribute_value_lists(self):
        """Test case for attribute_value_list_get_attribute_value_lists

        getAttributeValueLists  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
