# coding: utf-8

"""
    herd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.178.0-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import herdsdk
from herdsdk.models.tag_type_create_request import TagTypeCreateRequest  # noqa: E501
from herdsdk.rest import ApiException


class TestTagTypeCreateRequest(unittest.TestCase):
    """TagTypeCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTagTypeCreateRequest(self):
        """Test TagTypeCreateRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = herdsdk.models.tag_type_create_request.TagTypeCreateRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
