# coding: utf-8

"""
    herd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.178.0-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import herdsdk
from herdsdk.api.business_object_data_storage_file_api import BusinessObjectDataStorageFileApi  # noqa: E501
from herdsdk.rest import ApiException


class TestBusinessObjectDataStorageFileApi(unittest.TestCase):
    """BusinessObjectDataStorageFileApi unit test stubs"""

    def setUp(self):
        self.api = herdsdk.api.business_object_data_storage_file_api.BusinessObjectDataStorageFileApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_business_object_data_storage_file_create_business_object_data_storage_files(self):
        """Test case for business_object_data_storage_file_create_business_object_data_storage_files

        createBusinessObjectDataStorageFiles  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
