# coding: utf-8

"""
    herd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.178.0-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import herdsdk
from herdsdk.api.system_job_api import SystemJobApi  # noqa: E501
from herdsdk.rest import ApiException


class TestSystemJobApi(unittest.TestCase):
    """SystemJobApi unit test stubs"""

    def setUp(self):
        self.api = herdsdk.api.system_job_api.SystemJobApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_system_job_run_system_job(self):
        """Test case for system_job_run_system_job

        runSystemJob  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
