# coding: utf-8

"""
    herd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.178.0-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import herdsdk
from herdsdk.models.aws_credential import AwsCredential  # noqa: E501
from herdsdk.rest import ApiException


class TestAwsCredential(unittest.TestCase):
    """AwsCredential unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAwsCredential(self):
        """Test AwsCredential"""
        # FIXME: construct object with mandatory attributes with example values
        # model = herdsdk.models.aws_credential.AwsCredential()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
