# coding: utf-8

"""
    herd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.178.0-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import herdsdk
from herdsdk.models.system_job_run_request import SystemJobRunRequest  # noqa: E501
from herdsdk.rest import ApiException


class TestSystemJobRunRequest(unittest.TestCase):
    """SystemJobRunRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSystemJobRunRequest(self):
        """Test SystemJobRunRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = herdsdk.models.system_job_run_request.SystemJobRunRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
