# coding: utf-8

"""
    herd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.178.0-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import herdsdk
from herdsdk.api.relational_table_registration_api import RelationalTableRegistrationApi  # noqa: E501
from herdsdk.rest import ApiException


class TestRelationalTableRegistrationApi(unittest.TestCase):
    """RelationalTableRegistrationApi unit test stubs"""

    def setUp(self):
        self.api = herdsdk.api.relational_table_registration_api.RelationalTableRegistrationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_relational_table_registration_create_relational_table_registration(self):
        """Test case for relational_table_registration_create_relational_table_registration

        createRelationalTableRegistration  # noqa: E501
        """
        pass

    def test_relational_table_registration_delete_relational_table_registration(self):
        """Test case for relational_table_registration_delete_relational_table_registration

        deleteRelationalTableRegistration  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
