# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['pyramid_precis_creative_template']

package_data = \
{'': ['*'],
 'pyramid_precis_creative_template': ['static/css/*',
                                      'static/favicon_io/*',
                                      'static/icomoon/*',
                                      'static/icomoon/fonts/*',
                                      'static/vendor/bootstrap/css/bootstrap-grid.css',
                                      'static/vendor/bootstrap/css/bootstrap-grid.css',
                                      'static/vendor/bootstrap/css/bootstrap-grid.css',
                                      'static/vendor/bootstrap/css/bootstrap-grid.css',
                                      'static/vendor/bootstrap/css/bootstrap-grid.css',
                                      'static/vendor/bootstrap/css/bootstrap-grid.css',
                                      'static/vendor/bootstrap/css/bootstrap-grid.min.css',
                                      'static/vendor/bootstrap/css/bootstrap-grid.min.css',
                                      'static/vendor/bootstrap/css/bootstrap-grid.min.css',
                                      'static/vendor/bootstrap/css/bootstrap-grid.min.css',
                                      'static/vendor/bootstrap/css/bootstrap-grid.min.css',
                                      'static/vendor/bootstrap/css/bootstrap-grid.min.css',
                                      'static/vendor/bootstrap/css/bootstrap-reboot.css',
                                      'static/vendor/bootstrap/css/bootstrap-reboot.css',
                                      'static/vendor/bootstrap/css/bootstrap-reboot.css',
                                      'static/vendor/bootstrap/css/bootstrap-reboot.css',
                                      'static/vendor/bootstrap/css/bootstrap-reboot.css',
                                      'static/vendor/bootstrap/css/bootstrap-reboot.css',
                                      'static/vendor/bootstrap/css/bootstrap-reboot.min.css',
                                      'static/vendor/bootstrap/css/bootstrap-reboot.min.css',
                                      'static/vendor/bootstrap/css/bootstrap-reboot.min.css',
                                      'static/vendor/bootstrap/css/bootstrap-reboot.min.css',
                                      'static/vendor/bootstrap/css/bootstrap-reboot.min.css',
                                      'static/vendor/bootstrap/css/bootstrap-reboot.min.css',
                                      'static/vendor/bootstrap/css/bootstrap.css',
                                      'static/vendor/bootstrap/css/bootstrap.css',
                                      'static/vendor/bootstrap/css/bootstrap.css',
                                      'static/vendor/bootstrap/css/bootstrap.css',
                                      'static/vendor/bootstrap/css/bootstrap.css',
                                      'static/vendor/bootstrap/css/bootstrap.css',
                                      'static/vendor/bootstrap/css/bootstrap.min.css',
                                      'static/vendor/bootstrap/css/bootstrap.min.css',
                                      'static/vendor/bootstrap/css/bootstrap.min.css',
                                      'static/vendor/bootstrap/css/bootstrap.min.css',
                                      'static/vendor/bootstrap/css/bootstrap.min.css',
                                      'static/vendor/bootstrap/css/bootstrap.min.css',
                                      'static/vendor/bootstrap/js/bootstrap.bundle.js',
                                      'static/vendor/bootstrap/js/bootstrap.bundle.js',
                                      'static/vendor/bootstrap/js/bootstrap.bundle.js',
                                      'static/vendor/bootstrap/js/bootstrap.bundle.js',
                                      'static/vendor/bootstrap/js/bootstrap.bundle.min.js',
                                      'static/vendor/bootstrap/js/bootstrap.bundle.min.js',
                                      'static/vendor/bootstrap/js/bootstrap.bundle.min.js',
                                      'static/vendor/bootstrap/js/bootstrap.bundle.min.js',
                                      'static/vendor/bootstrap/js/bootstrap.js',
                                      'static/vendor/bootstrap/js/bootstrap.js',
                                      'static/vendor/bootstrap/js/bootstrap.js',
                                      'static/vendor/bootstrap/js/bootstrap.js',
                                      'static/vendor/bootstrap/js/bootstrap.min.js',
                                      'static/vendor/bootstrap/js/bootstrap.min.js',
                                      'static/vendor/bootstrap/js/bootstrap.min.js',
                                      'static/vendor/bootstrap/js/bootstrap.min.js',
                                      'static/vendor/devicon/*',
                                      'static/vendor/devicon/fonts/*',
                                      'static/vendor/devicon/icons/amazonwebservices/*',
                                      'static/vendor/devicon/icons/android/*',
                                      'static/vendor/devicon/icons/angularjs/*',
                                      'static/vendor/devicon/icons/apache/*',
                                      'static/vendor/devicon/icons/appcelerator/*',
                                      'static/vendor/devicon/icons/apple/*',
                                      'static/vendor/devicon/icons/asm/*',
                                      'static/vendor/devicon/icons/atom/*',
                                      'static/vendor/devicon/icons/babel/*',
                                      'static/vendor/devicon/icons/backbonejs/*',
                                      'static/vendor/devicon/icons/behance/*',
                                      'static/vendor/devicon/icons/bitbucket/*',
                                      'static/vendor/devicon/icons/bootstrap/*',
                                      'static/vendor/devicon/icons/bower/*',
                                      'static/vendor/devicon/icons/c/*',
                                      'static/vendor/devicon/icons/c3js/*',
                                      'static/vendor/devicon/icons/cakephp/*',
                                      'static/vendor/devicon/icons/ceylon/*',
                                      'static/vendor/devicon/icons/chrome/*',
                                      'static/vendor/devicon/icons/codeigniter/*',
                                      'static/vendor/devicon/icons/coffeescript/*',
                                      'static/vendor/devicon/icons/confluence/*',
                                      'static/vendor/devicon/icons/couchdb/*',
                                      'static/vendor/devicon/icons/cplusplus/*',
                                      'static/vendor/devicon/icons/csharp/*',
                                      'static/vendor/devicon/icons/css3/*',
                                      'static/vendor/devicon/icons/cucumber/*',
                                      'static/vendor/devicon/icons/d3js/*',
                                      'static/vendor/devicon/icons/debian/*',
                                      'static/vendor/devicon/icons/devicon/*',
                                      'static/vendor/devicon/icons/django/*',
                                      'static/vendor/devicon/icons/docker/*',
                                      'static/vendor/devicon/icons/doctrine/*',
                                      'static/vendor/devicon/icons/dot-net/*',
                                      'static/vendor/devicon/icons/drupal/*',
                                      'static/vendor/devicon/icons/electron/*',
                                      'static/vendor/devicon/icons/elm/*',
                                      'static/vendor/devicon/icons/embeddedc/*',
                                      'static/vendor/devicon/icons/ember/*',
                                      'static/vendor/devicon/icons/erlang/*',
                                      'static/vendor/devicon/icons/express/*',
                                      'static/vendor/devicon/icons/facebook/*',
                                      'static/vendor/devicon/icons/firefox/*',
                                      'static/vendor/devicon/icons/foundation/*',
                                      'static/vendor/devicon/icons/gatling/*',
                                      'static/vendor/devicon/icons/gimp/*',
                                      'static/vendor/devicon/icons/git/*',
                                      'static/vendor/devicon/icons/github/*',
                                      'static/vendor/devicon/icons/gitlab/*',
                                      'static/vendor/devicon/icons/go/*',
                                      'static/vendor/devicon/icons/google/*',
                                      'static/vendor/devicon/icons/gradle/*',
                                      'static/vendor/devicon/icons/grunt/*',
                                      'static/vendor/devicon/icons/gulp/*',
                                      'static/vendor/devicon/icons/handlebars/*',
                                      'static/vendor/devicon/icons/heroku/*',
                                      'static/vendor/devicon/icons/html5/*',
                                      'static/vendor/devicon/icons/ie10/*',
                                      'static/vendor/devicon/icons/illustrator/*',
                                      'static/vendor/devicon/icons/inkscape/*',
                                      'static/vendor/devicon/icons/intellij/*',
                                      'static/vendor/devicon/icons/ionic/*',
                                      'static/vendor/devicon/icons/jasmine/*',
                                      'static/vendor/devicon/icons/java/*',
                                      'static/vendor/devicon/icons/javascript/*',
                                      'static/vendor/devicon/icons/jeet/*',
                                      'static/vendor/devicon/icons/jetbrains/*',
                                      'static/vendor/devicon/icons/jquery/*',
                                      'static/vendor/devicon/icons/krakenjs/*',
                                      'static/vendor/devicon/icons/labview/*',
                                      'static/vendor/devicon/icons/laravel/*',
                                      'static/vendor/devicon/icons/less/*',
                                      'static/vendor/devicon/icons/linkedin/*',
                                      'static/vendor/devicon/icons/linux/*',
                                      'static/vendor/devicon/icons/meteor/*',
                                      'static/vendor/devicon/icons/mocha/*',
                                      'static/vendor/devicon/icons/mongodb/*',
                                      'static/vendor/devicon/icons/moodle/*',
                                      'static/vendor/devicon/icons/mysql/*',
                                      'static/vendor/devicon/icons/nginx/*',
                                      'static/vendor/devicon/icons/nodejs/*',
                                      'static/vendor/devicon/icons/nodewebkit/*',
                                      'static/vendor/devicon/icons/npm/*',
                                      'static/vendor/devicon/icons/oracle/*',
                                      'static/vendor/devicon/icons/photoshop/*',
                                      'static/vendor/devicon/icons/php/*',
                                      'static/vendor/devicon/icons/phpstorm/*',
                                      'static/vendor/devicon/icons/postgresql/*',
                                      'static/vendor/devicon/icons/protractor/*',
                                      'static/vendor/devicon/icons/pycharm/*',
                                      'static/vendor/devicon/icons/python/*',
                                      'static/vendor/devicon/icons/rails/*',
                                      'static/vendor/devicon/icons/react/*',
                                      'static/vendor/devicon/icons/redhat/*',
                                      'static/vendor/devicon/icons/redis/*',
                                      'static/vendor/devicon/icons/ruby/*',
                                      'static/vendor/devicon/icons/rubymine/*',
                                      'static/vendor/devicon/icons/safari/*',
                                      'static/vendor/devicon/icons/sass/*',
                                      'static/vendor/devicon/icons/sequelize/*',
                                      'static/vendor/devicon/icons/sketch/*',
                                      'static/vendor/devicon/icons/slack/*',
                                      'static/vendor/devicon/icons/sourcetree/*',
                                      'static/vendor/devicon/icons/ssh/*',
                                      'static/vendor/devicon/icons/stylus/*',
                                      'static/vendor/devicon/icons/swift/*',
                                      'static/vendor/devicon/icons/symfony/*',
                                      'static/vendor/devicon/icons/tomcat/*',
                                      'static/vendor/devicon/icons/travis/*',
                                      'static/vendor/devicon/icons/trello/*',
                                      'static/vendor/devicon/icons/twitter/*',
                                      'static/vendor/devicon/icons/typescript/*',
                                      'static/vendor/devicon/icons/ubuntu/*',
                                      'static/vendor/devicon/icons/vagrant/*',
                                      'static/vendor/devicon/icons/vim/*',
                                      'static/vendor/devicon/icons/visualstudio/*',
                                      'static/vendor/devicon/icons/vuejs/*',
                                      'static/vendor/devicon/icons/webpack/*',
                                      'static/vendor/devicon/icons/webstorm/*',
                                      'static/vendor/devicon/icons/windows8/*',
                                      'static/vendor/devicon/icons/wordpress/*',
                                      'static/vendor/devicon/icons/yarn/*',
                                      'static/vendor/devicon/icons/yii/*',
                                      'static/vendor/devicon/icons/zend/*',
                                      'static/vendor/font-awesome/css/font-awesome.css',
                                      'static/vendor/font-awesome/css/font-awesome.css',
                                      'static/vendor/font-awesome/css/font-awesome.min.css',
                                      'static/vendor/font-awesome/css/font-awesome.min.css',
                                      'static/vendor/font-awesome/fonts/*',
                                      'static/vendor/font-awesome/less/*',
                                      'static/vendor/font-awesome/scss/*',
                                      'static/vendor/icomoon/*',
                                      'static/vendor/icomoon/fonts/*',
                                      'static/vendor/jquery-easing/*',
                                      'static/vendor/jquery/jquery.js',
                                      'static/vendor/jquery/jquery.js',
                                      'static/vendor/jquery/jquery.js',
                                      'static/vendor/jquery/jquery.js',
                                      'static/vendor/jquery/jquery.min.js',
                                      'static/vendor/jquery/jquery.min.js',
                                      'static/vendor/jquery/jquery.min.js',
                                      'static/vendor/jquery/jquery.min.js',
                                      'static/vendor/jquery/jquery.slim.js',
                                      'static/vendor/jquery/jquery.slim.js',
                                      'static/vendor/jquery/jquery.slim.js',
                                      'static/vendor/jquery/jquery.slim.js',
                                      'static/vendor/jquery/jquery.slim.min.js',
                                      'static/vendor/jquery/jquery.slim.min.js',
                                      'static/vendor/jquery/jquery.slim.min.js',
                                      'static/vendor/jquery/jquery.slim.min.js',
                                      'static/vendor/magnific-popup/*',
                                      'static/vendor/scrollreveal/*',
                                      'static/vendor/simple-line-icons/css/*',
                                      'static/vendor/simple-line-icons/fonts/*',
                                      'static/vendor/simple-line-icons/less/*',
                                      'static/vendor/simple-line-icons/scss/*',
                                      'templates/*']}

entry_points = \
{'console_scripts': ['pyramid_precis_creative_template = '
                     'pyramid_precis_creative_template.cli:main']}

setup_kwargs = {
    'name': 'pyramid-precis-creative-template',
    'version': '0.2.0',
    'description': 'Default template for pyramid_resume',
    'long_description': '# Pyramid Precis Creative Template\n\n## Getting started\n\nTBD\n\n## Test and Deploy\n\nTBD\n\n***\n\n## Usage\nTBD\n\n## Contributing\n\nCreate an issue and a PR!\n\n## License\n\nMIT\n',
    'author': 'Marc LaBelle',
    'author_email': 'mjlabe@gmail.com',
    'maintainer': 'None',
    'maintainer_email': 'None',
    'url': 'None',
    'packages': packages,
    'package_data': package_data,
    'entry_points': entry_points,
    'python_requires': '>=3.9,<4.0',
}


setup(**setup_kwargs)
