
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_cs = {'_': ['cs_universitatea_cluj-napoca',
       'cs_universitatea_alexandria',
       'cs_gloria_bistrita-nasaud',
       'cs_tiligul-tiras_tiraspol',
       'cs_femina-sport_chisinau',
       'cs_universitatea_craiova',
       'cs_crisul_chisineu-cris',
       'cs_petrolistul_boldesti',
       'cs_universitatea_resita',
       'cs_mont-royal_outremont',
       'cs_metalurgistul_cugir',
       'cs_stiinta_miroslava',
       'cs_minerul_mehedinti',
       'cs_progym_gheorgheni',
       'cs_plebiscito_padova',
       'cs_concordia_chiajna',
       'cs_phoenix_constanta',
       'cs_luceafarul_oradea',
       'cs_muncitorul_resita',
       'cs_unirea_tarlungeni',
       'cs_tricolorul_breaza',
       'cs_sporting_rosiori',
       'cs_portul_constanta',
       'cs_politehnica_iasi',
       'cs_vedita_colonesti',
       'cs_louhans_cuiseaux',
       'cs_dinamo_bucuresti',
       'cs_cuiseaux_louhans',
       'cs_sporting_liesti',
       'cs_sporting_vaslui',
       'cs_rapid_bucuresti',
       'cs_viitorul_daesti',
       'cs_conpet_ploiesti',
       'cs_soimii_pancota',
       'cs_minerul_lupeni',
       'cs/mpq-90_bee_eye',
       'cs_sportul_snagov',
       'cs_sedan_ardennes',
       'cs_motorul_oradea',
       'cs_aerostar_bacau',
       'cs_viitorul_ianca',
       'cs_national_sebis',
       'cs_salamis_glory',
       'cs_dacia_mioveni',
       'cs_turnu_severin',
       'cs_bihorul_beius',
       'cs_soimii_lipova',
       'cs_stiinta_bacau',
       'cs_coltea_brasov',
       'cs_minerul_motru',
       'cs_gloria_resita',
       'cs_la_forestoise',
       'cs_arcada_galati',
       'cs_first_boston',
       'cs_alterna_bank',
       'cs_triumf_barca',
       'cs_chimia_brazi',
       'cs_unirea_jucu',
       'cs_ocean_layer',
       'cs_alliance_01',
       'cs_targu_mures',
       'cs_cfr_simeria',
       'cs_lewis_house',
       'cs_gloria_arad',
       'cs_rugby_1863',
       'cs_la_sagesse',
       'cs_bayou_city',
       'cs_42/3_mine',
       'cs_36_merlin',
       'cs_joachim_f',
       'cs_don_bosco',
       'cs_fola_esch',
       'cs_42/2_mine',
       'cs_la_mancha',
       'cs_acu_arad',
       'cs_sao_joao',
       'cs_ben_hur'],
 'a': ['csa_orthocarolina_sportsplex',
       'csa_provincial_competitions',
       'csa_axiopolis_cernavoda',
       'csaba_ferenc_asztalos',
       'csa_steaua_bucuresti',
       'csaba_sandor_tabajdi',
       'csa_czech_airlines',
       'csaba_nagy_lakatos',
       'csa_t20_challenge',
       'csar_rack_4-6-4rt',
       'csain_snia_milano',
       'csar_nicholas_ii',
       'csaba_p._kovesdy',
       'csa_ps-38_tourer',
       'csa_flight_540',
       'csa_flight_511',
       'csa_aurul_brad',
       'csa_flight_523',
       'csa_flight_001',
       'csak_ii_hahot',
       'csak_i_hahot'],
 'b': ['csbc_corporation,_taiwan', 'csb_lady_blazers'],
 'c': ['csc_aircraft_company',
       'csc_enterprise_corp.',
       'csc_enterprise_corp',
       'csc_maiden_saginaw',
       'cscl_indian_ocean',
       'csc_1599_selimbar',
       'cscl_arctic_ocean',
       "csc_team_o'grady",
       'csce_minsk_group',
       'csc_nika_stadium',
       'csc_champa_f.c.',
       'csc_media_group',
       'cscl_long_beach',
       'csc_de_cayenne'],
 'd': ['csd_class_t478.3',
       'csd_class_387.0',
       'csd_class_477.0',
       'csd_colo_colo'],
 'e': ['csepel_automobile_factory',
       'csesznegi_von_milvanyi',
       'csejtei_joachim_ferenc',
       'cseszneky_de_milvany',
       'cse_insurance_group',
       'csejtei_joachim_f'],
 'f': ['csf/serum_glucose_ratio',
       'csf/serum_albumin_ratio',
       'csf_spartanii_selemet',
       'csf_sparta_chisinau',
       'csf_cfr_timisoara',
       'csf_total_protein',
       'csf_tap_test'],
 'g': ['csg_holding_limited'],
 'h': ['csharp_lex_generators'],
 'i': ['csi:crime_scene_investigation',
       'csi:crime_scene_investigaion',
       'csi_centennial_observatory',
       'csi:_investigacao_criminal',
       'csi:_fatal_conspiracy',
       'csilla_von_boeselager',
       'csi_immanuel_church',
       'csi:_the_experience',
       'csi:_kagaku_sosakan',
       'csi_miami_episodes',
       'csi:_deadly_intent',
       'csi:_hard_evidence',
       'csi:_dark_motives',
       'csi_dark_motives',
       'csi_episode_list',
       'csi_ny_episodes',
       'csi:_crime_city',
       'csi:_las_vegas',
       'csi_100_index',
       'csi-13_6439_1',
       'csi_las_vegas',
       'csi-01_3925_1',
       'csi:_new_york',
       'csi-13_6439_2',
       'csi_300_index',
       'csi_new_york',
       'csir_sara_ii',
       'csir_mk_i',
       'csir_mk_1'],
 'k': ['csk_vvs-kristall_smolensk',
       'cska_pamir_dushanbe',
       'cska_sports_complex',
       'cska_sport_palace',
       'csk_uhersky_brod',
       'cska_ice_palace',
       'csk_zsu_stadium',
       'csk_vmf_moscow',
       'csk_vvs_samara',
       'csk_vss_samara',
       'csk_zsu_kyiv'],
 'l': ['csl_golden_boot', 'csl_group_inc.', 'csl_group_ltd'],
 'm': ['csm_drobeta-turnu_severin',
       'csm_sighetu_marmatiei',
       'csm_bucovina_radauti',
       'csm_olimpia_salonta',
       'csm_flacara_moreni',
       'csm_jiul_petrosani',
       'csm_avantul_reghin',
       'csm_dunarea_galati',
       'csm_miercurea_ciuc',
       'csmd_diables_noirs',
       'csm_dacia_orastie',
       'csm_corona_brasov',
       'csm_campia_turzii',
       'csm_ramnicu_sarat',
       'csm_phil_johndrow',
       'csm_digi_oradea',
       'csm_targu_mures',
       'csm_satu_mare',
       'csm_baia_mare',
       'csm_u_oradea'],
 'n': ['csn_international_translators', 'csn_new_england', 'csn_bay_area'],
 'o': ['csongrad-csanad_county_assembly',
       'csongrad_megyei_cegregiszter',
       "csorba's_mouse-eared_bat",
       'csoa_forte_prenestino',
       'cso_tricolorul_breaza',
       'csongor_istvan_nagy',
       'cso_konser_salonu',
       'csongor_es_tunde',
       'cso_concert_hall'],
 'p': ['cspc_pharmaceutical_group', 'csp_um_timisoara', 'csp_music_group'],
 'r': ['csr_refinery,_yarraville',
       'csr_corporation_limited',
       'csra_football_classic',
       'csrb/rsmb_rna_family',
       'csr_qishuyan_sda2',
       'csr_ziyang_sda1',
       'csrc_rna_family'],
 's': ['css_general_beauregard',
       'css_image_replacement',
       'css_stonewall_jackson',
       'css_html_validator',
       'css_general_lovell',
       'css_palmetto_state',
       'css_colonel_lovell',
       'css_north_carolina',
       'css_working_group',
       'css_patrick_henry',
       'css_black_warrior',
       'css_indian_chief',
       'cssa_nations_cup',
       'css_general_polk',
       'css_style_sheets',
       'css_colonel_lamb',
       'css_cotton_plant',
       'css_grid_layout',
       'css_george_page',
       'css_virginia_ii',
       'css_new_orleans',
       'css_lady_davis',
       'css_zen_garden',
       'css_grand_duke',
       'css_box_model',
       'css_sea_bird',
       'css_rob_roy'],
 't': ['cst-panvel_fast_corridor',
       'cst_railway_station',
       'cstc_hmcs_acadia',
       'cstc_hmcs_avalon',
       'cstc_hmcs_quebec',
       'cstc_hmcs_quinte',
       'cstc_hmcs_quadra',
       'cstc_cold_lake'],
 'u': ['csu_pueblo_thunderwolves',
       'csu_convocation_center',
       'csu_asesoft_ploiesti',
       'csu_neptun_constanta',
       'csu_danubius_galati',
       'csu_vointa_sibiu',
       'csu_alba_iulia'],
 'v': ['csv_olympia_1897'],
 'w': ['cswf_hardcore_championship'],
 'x': ['csx_indianapolis_subdivision',
       'csx_metropolitan_subdivision',
       'csx_philadelphia_subdivision',
       'csx_transportation_building',
       'csx_washington_subdivision',
       'csx_harrisburg_subdivision',
       'csx_cumberland_subdivision',
       'csx_kingsport_subdivision',
       'csx_keystone_subdivision',
       'csx_transportation_corp.',
       'csx_mountain_subdivision',
       'csx_illinois_subdivision',
       'csx_indiana_subdivision',
       'csx_capital_subdivision',
       'csx_niagara_subdivision',
       'csx_decatur_subdivision',
       'csx_capitol_subdivision',
       'csx_trenton_subdivision',
       'csx_hanover_subdivision',
       'csx_memphis_subdivision',
       'csx_milepost_prefixes',
       'csx_northern_region',
       'csx_southern_region',
       'csx_kp_subdivision',
       'csx_cv_subdivision',
       'csx_a-line_bridge',
       'csx_porter_branch',
       'csx_8888_incident'],
 'y': ['csyd_tristan_suarez']}
