
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_cp = {'_': ['cp_windsor_subdivision',
       'cp/m_operating_system',
       'cp_cuencas_mineras',
       'cp_urban_services',
       'cp_ramaswami_iyer',
       'cp_gijon_solimar',
       'cp_san_cristobal',
       'cp_parla_escuela',
       'cp_goya_almeria',
       'cp_music_group',
       'cp_la_felguera',
       'cp_class_1400',
       'cp_class_2550',
       'cp_class_1930',
       'cp_class_1150',
       'cp_class_1900',
       'cp_class_1500',
       'cp_class_3150',
       'cp_class_1200',
       'cp_system_iii',
       'cp_class_2600',
       'cp_class_5600',
       'cp_class_1960',
       'cp_class_1800',
       'cp_class_9020',
       'cp_class_1550',
       'cp_ships_ltd.',
       'cp_class_4700',
       'cp_nel_museum',
       'cp_class_1320',
       'cp_class_2240',
       'cp_class_1300',
       'cp_granada_74',
       'cp_class_2500',
       'cp_system_ii',
       'cp_ejido_b',
       'cp_la_roda'],
 'a': ['cpa_board_examinations',
       'cpa_technology_advisor',
       'cpa_practice_advisor',
       'cpa_board_exam',
       'cpa_order_17',
       'cpa_order_2'],
 'b': ['cpbl-kbo_club_championship'],
 'c': ['cpc_organization_department',
       'cpcs_transcom_limited',
       'cpc_national_congress',
       'cpc_general_secretary',
       'cpc_central_committee',
       'cpc_corporation_f.c.',
       'cpc_party_secretary',
       'cpc_binary_barcode',
       'cpc_cine_awards',
       'cpc_party_chief',
       'cpc_4_state',
       'cpc_19_6834'],
 'd': ['cpdrc_dancing_inmates',
       'cpd_-49_10052a',
       'cpd_-49_10052b',
       'cpd_-49_10052',
       'cpd_-58_7788b',
       'cpd_-62_332b',
       'cpd_-32_1008',
       'cpd_-23_1588',
       'cpd_-33_3933',
       'cpd_-53_1168',
       'cpd_-32_6269',
       'cpd_-30_3121',
       'cpd_-39_8327',
       'cpd_-58_7788',
       'cpd_-22_5388',
       'cpd_-61_5655',
       'cpd_-44_3126',
       'cpd_-77_1474',
       'cpd_-60_1817',
       'cpd_-34_8799',
       'cpd_-33_3159',
       'cpd_-58_5875',
       'cpd_-62_332',
       'cpd_-32_302',
       'cpd_-42_513',
       'cpd_-60_508',
       'cpd_-78_893',
       'cpd_-62_487',
       'cpd_-55_663',
       'cpd_-35_752',
       'cpd_-71_309',
       'cpd_-51_524',
       'cpd_-64_215',
       'cpd_-58_670',
       'cpd_-78_741'],
 'e': ['cpe_binding_protein'],
 'g': ['cpg_island_hypermethylation'],
 'h': ['cph1_holin_family'],
 'i': ['cpi_property_group'],
 'l': ['cpl_programming_language',
       'cplc_community_schools',
       'cpl-u_sports_draft',
       'cpl._willy_apiata',
       'cpl_joshua_belile'],
 'm': ['cpm_operating_system', 'cpm_s30v_steel'],
 'o': ['cpo_boss_hogg'],
 'p': ['cpp_investment_board'],
 'r': ['cpr_vaughan_intermodal',
       'cpr_montrose_yard',
       'cpr_parkdale_yard',
       'cpr_aberdeen_yard',
       'cpr_lambton_yard',
       'cpr_buffalo_yard',
       'cpr_toronto_yard',
       'cpr_kinnear_yard',
       'cpr_angus_shops',
       'cpr_alyth_yard',
       'cpr_pier_d'],
 's': ['cpsu_central_committee', 'cpsu_party_congress'],
 't': ['cpt._kenneth_elloway',
       'cpt._jack_sparrow',
       'cpt_ii_deficiency',
       'cpt_i_deficiency',
       'cpt._fear_not'],
 'u': ['cpu_electrical_consumption',
       'cpu_power_dissipation',
       'cpu_power_consumption',
       'cpu_research_center',
       'cpu_handbell_choir',
       'cpu_water_cooling',
       'cpu_memory_cache',
       'cpu_core_voltage',
       'cpu_sleep_state',
       'cpu_clock_rate']}
