from setuptools import setup

setup(
    # Needed to silence warnings (and to be a worthwhile package)
    name="ResumeReader",
    url="https://github.com/gigumbrajaguru/ResumeReader",
    author="Gigum Rajaguru",
    author_email="gigumbrajaguru@gmail.com",
    packages=[],
    # Needed for dependencies
    install_requires=[
        "asttokens",
        "backcall",
        "blis",
        "catalogue",
        "certifi",
        "cffi",
        "charset-normalizer",
        "click",
        "colorama",
        "commonregex",
        "confection",
        "cryptography",
        "cymem",
        "decorator",
        "executing",
        "idna",
        "ipython",
        "jedi",
        "jellyfish",
        "Jinja2",
        "joblib",
        "langcodes",
        "MarkupSafe",
        "matplotlib-inline",
        "murmurhash",
        "nltk",
        "numpy",
        "packaging",
        "pandas",
        "parso",
        "pathy",
        "pdf2image",
        "pdfminer.six",
        "phonenumbers",
        "pickleshare",
        "Pillow",
        "preshed",
        "prompt-toolkit",
        "pure-eval",
        "pycparser",
        "pydantic",
        "Pygments",
        "pyparsing",
        "pypostalwin",
        "pytesseract",
        "python-dateutil",
        "pytz",
        "regex",
        "requests",
        "six",
        "skillNer",
        "smart-open",
        "spacy",
        "spacy-legacy",
        "spacy-loggers",
        "srsly",
        "stack-data",
        "thinc",
        "tqdm",
        "traitlets",
        "typer",
        "typing_extensions",
        "urllib3",
        "wasabi",
        "wcwidth",
    ],
    # *strongly* suggested for sharing
    version="0.1",
    # The license can be anything you like
    license="MIT",
    description="",
    # We will also need a readme eventually (there will be a warning)
    long_description="",
)

if __name__ == "__main__":
    setup()
