#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# AUTO-GENERATED CONTENT
d_stem_hj = {'hja': {'hjas': []},
 'hjadn': {'hjadnings': []},
 'hjaelp': {'hjaelpe': []},
 'hjalag': {'hjalager': []},
 'hjalma': {'hjalmas': []},
 'hjalmar': {'hjalmare': [], 'hjalmars': []},
 'hjalpt': {'hjalpte': []},
 'hjalt': {'hjalte': []},
 'hjaltad': {'hjaltadal': []},
 'hjand': {'hjandes': []},
 'hjanuari': {'hjanuary': []},
 'hjard': {'hjarde': []},
 'hjarn': {'hjarne': []},
 'hjarp': {'hjarpe': []},
 'hjarr': {'hjarre': []},
 'hjartat': {'hjartats': []},
 'hjave': {'hjaving': []},
 'hjco': {'hjcos': []},
 'hject': {'hjects': []},
 'hjed': {'hjedding': [], 'hjeds': []},
 'hjejl': {'hjejle': []},
 'hjeld': {'hjelde': []},
 'hjell': {'hjelle': []},
 'hjellbrekk': {'hjellbrekke': []},
 'hjellm': {'hjellming': []},
 'hjelm': {'hjelme': [], 'hjelms': []},
 'hjelma': {'hjelmas': []},
 'hjelmroo': {'hjelmroos': []},
 'hjelmslev': {'hjelmslevs': []},
 'hjelp': {'hjelpe': []},
 'hjelpemidl': {'hjelpemidler': []},
 'hjelt': {'hjelte': []},
 'hjeltn': {'hjeltnes': []},
 'hjembo': {'hjemboe': []},
 'hjemlig': {'hjemlige': []},
 'hjemm': {'hjemme': []},
 'hjemmen': {'hjemmenes': []},
 'hjemmestyr': {'hjemmestyre': []},
 'hjemmet': {'hjemmets': []},
 'hjemorrhag': {'hjemorrhage': []},
 'hjemov': {'hjemover': []},
 'hjemst': {'hjemsted': []},
 'hjer': {'hjerring': []},
 'hjern': {'hjerne': []},
 'hjernen': {'hjernens': []},
 'hjerp': {'hjerpe': []},
 'hjerpp': {'hjerppe': []},
 'hjert': {'hjerte': [], 'hjerting': []},
 'hjertaa': {'hjertaas': []},
 'hjertag': {'hjertager': []},
 'hjertet': {'hjertets': []},
 'hjggin': {'hjggins': []},
 'hjghli': {'hjghly': []},
 'hji': {'hjis': [], 'hjy': []},
 'hjig': {'hjigs': []},
 'hjiow': {'hjiows': []},
 'hjistori': {'hjistory': []},
 'hjj': {'hjjs': []},
 'hjleucin': {'hjleucine': []},
 'hjli': {'hjly': []},
 'hjll': {'hjlls': []},
 'hjmn': {'hjmns': []},
 'hjnd': {'hjnds': []},
 'hjnite': {'hjnited': []},
 'hjo': {'hjos': []},
 'hjor': {'hjorring': []},
 'hjordi': {'hjordis': []},
 'hjorn': {'hjorne': []},
 'hjornag': {'hjornager': []},
 'hjort': {'hjorting': [], 'hjorts': []},
 'hjorten': {'hjortens': []},
 'hjortespr': {'hjortespring': []},
 'hjorth': {'hjorths': []},
 'hjortna': {'hjortnaes': []},
 'hjortspr': {'hjortspring': []},
 'hjowev': {'hjowever': []},
 'hjpothesi': {'hjpothesis': []},
 'hjre': {'hjres': []},
 'hjstoir': {'hjstoire': []},
 'hjstori': {'hjstory': []},
 'hjt': {'hjts': []},
 'hjthymidin': {'hjthymidine': []},
 'hjuks': {'hjukse': []},
 'hjuli': {'hjuly': []},
 'hjur': {'hjurs': []}}
