
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_fv = {'_': ['fv_preussen_eberswalde',
       'fv_laubegast_dresden',
       'fv1620_humber_hornet',
       'fv_motor_eberswalde',
       'fv_community_shield',
       'fv_monte_galineiro',
       'fv_4101_charioteer',
       'fv_1911_neuendorf',
       'fv_north_american',
       'fv_cornelia_marie',
       'fv_northern_belle',
       'fv_august_wriedt',
       'fv_hassia_bingen',
       'fv_empire_fisher',
       'fv_alaska_ranger',
       'fv_pere_charles',
       'fv433_abbot_spg',
       'fv_kreuznach_07',
       'fv_1897_linden',
       'fv_09_weinheim',
       'fv_103_spartan',
       'fv_08_rottweil',
       'fv_silver_king',
       'fv_bad_vilbel',
       'fv_430_series',
       'fv_big_valley',
       'fv_dresden_06',
       'fv_gera_sued',
       'fv_engers_07',
       'fv_ulm_1894',
       'fv_gera_sud',
       'fv_432_afv',
       'fv_ulm_94'],
 'a': ['fva-1_schwatze_duvel'],
 'g': ['fvgg._kastel_06', 'fvgg_kastel_06'],
 'm': ['fvm_o1_tummelisa', 'fvm_j_23'],
 'p': ['fvpr_el_olivo']}
