
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_iy = {'_': ['iy626'],
 'a': ['iyappanthangal',
       'iyang-argapura',
       'iyarpagaiar',
       'iyah-gbede',
       'iyashikei',
       'iyannough',
       'iyarpahai',
       'iyanadon',
       "iyal'oja",
       'iyatiku',
       'iyanifa',
       'iya2008',
       'iyalawo',
       'iyarkai',
       'iyakkam',
       'iya2009',
       'iyanya',
       'iyamho',
       'iyambo',
       'iyaric',
       'iyari',
       'iyapa',
       'iyasu',
       'iyara',
       'iyasa',
       'iyad',
       'iyaz',
       'iyai',
       'iyar',
       'iya'],
 'c': ['iyc'],
 'd': ['iydkydg', 'iydmma', 'iydp', 'iydu', 'iyd'],
 'e': ['iye-abarim',
       'iyede-ame',
       'iyengars',
       'iyevlevo',
       'iyengra',
       'iyeyasu',
       'iyengar',
       'iye626',
       'iyego',
       'iyela',
       'iyeye',
       'iyeza',
       'iyers',
       'iyer',
       'iye'],
 'h': ['iyhf', 'iyhw', 'iyh'],
 'i': ['iyibkhentre', 'iyi-uwa', 'iyidere', 'iyiyi'],
 'k': ['iykwim', 'iyk'],
 'm': ['iym'],
 'n': ['iynefer', 'iynu', 'iynx'],
 'o': ['iyotetsu',
       'iyouella',
       'iyo-ben',
       'iyouit',
       'iyokan',
       'iyoite',
       'iyonix',
       'iyogi',
       'iyore',
       'iyov',
       'iyo'],
 'p': ['iyp'],
 'r': ['iyrcae', 'iyru', 'iyrs', 'iyri', 'iyr'],
 's': ['iysine', 'iysa', 'iysh'],
 't': ['iytjenu', 'iyt'],
 'u': ['iyulelog', 'iyulsky', 'iyumbu', 'iyunga', 'iyula'],
 'y': ['iyyapanthangal', 'iyyar', 'iyyer', 'iyyun', 'iyy']}
