
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_vp = {'_': ['vp-hl-1',
       'vp-hl-5',
       'vp-hl-3',
       'vp-am-5',
       'vp-am-1',
       'vp-info',
       'vp-142',
       'vp-153',
       'vp-106',
       'vp-133',
       'vp-sem',
       'vp-148',
       'vp-104',
       'vp-123',
       'vp-168',
       'vp-152',
       'vp-102',
       'vp-131',
       'vp/css',
       'vp-21',
       'vp-43',
       'vp-27',
       'vp-34',
       'vp-30',
       'vp-92',
       'vp-47',
       'vp-50',
       'vp-67',
       'vp-56',
       'vp-66',
       'vp-45',
       'vp-10',
       'vp-60',
       'vp-25',
       'vp-41',
       'vp-28',
       'vp-26',
       'vp-61',
       'vp-40',
       'vp-11',
       'vp-94',
       'vp-20',
       'vp-65',
       'vp-69',
       'vp-49',
       'vp/ms',
       'vp-93',
       'vp-31',
       'vp-64',
       'vp-46',
       'vp-17',
       'vp-62',
       'vp-42',
       'vp-22',
       'vp-91',
       'vp-44',
       'vp-29',
       'vp-24',
       'vp-90',
       'vp-16',
       'vp-48',
       'vp-23',
       'vp-18',
       'vp-51',
       'vp-32',
       'vp-33',
       'vp-68',
       'vp-2',
       'vp-6',
       'vp-8',
       'vp-5',
       'vp-7',
       'vp-1',
       'vp-9',
       'vp22',
       'vp40',
       'vp16',
       'vp11',
       'vp-3',
       'vp6f',
       'vp8',
       'vp3',
       'vp9',
       'vp6',
       'vp1'],
 'a': ['vpat', 'vpap', 'vpac', 'vpa'],
 'b': ['vpb-207',
       'vpb-151',
       'vpb-104',
       'vpb-216',
       'vpb-134',
       'vpb-127',
       'vpb-202',
       'vpb-114',
       'vpb-212',
       'vpb-110',
       'vpb-132',
       'vpb-139',
       'vpb-197',
       'vpb-203',
       'vpb-100',
       'vpb-113',
       'vpb-214',
       'vpb-126',
       'vpb-105',
       'vpb-118',
       'vpb-213',
       'vpb-147',
       'vpb-121',
       'vpb-199',
       'vpb-125',
       'vpb-209',
       'vpb-215',
       'vpb-200',
       'vpb-137',
       'vpb-117',
       'vpb-103',
       'vpb-198',
       'vpb-210',
       'vpb-112',
       'vpb-211',
       'vpb-150',
       'vpb-129',
       'vpb-141',
       'vpb-109',
       'vpb-145',
       'vpb-149',
       'vpb-206',
       'vpb-94',
       'vpb-11',
       'vpb-23',
       'vpb-17',
       'vpb-13',
       'vpb-29',
       'vpb-44',
       'vpb-15',
       'vpb-98',
       'vpb-43',
       'vpb-18',
       'vpb-33',
       'vpb-16',
       'vpb-24',
       'vpbint',
       'vpb-84',
       'vpb-54',
       'vpb-20',
       'vpb-61',
       'vpb-99',
       'vpb-92',
       'vpb-45',
       'vpb-34',
       'vpb-52',
       'vpb-91',
       'vpb-63',
       'vpb-1',
       'vpb-4',
       'vpb'],
 'c': ['vpchat', 'vpci', 'vpc'],
 'd': ['vpdn', 'vpd'],
 'e': ['vperyod', 'vpec-t', 'vpered', 'vpe'],
 'f': ['vpf'],
 'g': ['vpg'],
 'h': ['vphs', 'vph'],
 'i': ['vpisu', 'vpitv', 'vpim', 'vpid', 'vpi'],
 'k': ['vpk'],
 'l': ['vpl-fm', 'vpl.', 'vpls', 'vpl'],
 'm': ['vpm-fm', 'vpmi', 'vpms', 'vpm'],
 'n': ['vpnfilter', 'vpnbook', 'vpn-1', 'vpns', 'vpn'],
 'o': ['vpointer', 'vpopmail', 'vpotus', 'vport', 'vpost', 'vpod', 'vpo'],
 'p': ['vppa', 'vpp'],
 'r': ['vprintf', 'vpreb1', 'vpreb3', 'vprbp', 'vpro', 'vpr'],
 's': ['vpskeys',
       'vps13b',
       'vps13a',
       'vps26b',
       'vps13d',
       'vps/vm',
       'vps33a',
       'vps33b',
       'vps37a',
       'vps26a',
       'vps35l',
       'vps45',
       'vps29',
       'vps35',
       'vps24',
       'vps28',
       'vps72',
       'vps25',
       'vps18',
       'vps36',
       'vpshr',
       'vps4a',
       'vps34',
       'vps23',
       'vps53',
       'vps-2',
       'vps39',
       'vps52',
       'vps11',
       'vps4b',
       'vps2',
       'vpsa',
       'vps'],
 't': ['vpt'],
 'u': ['vpup', 'vpu'],
 'v': ['vpv-fm', 'vpvp'],
 'w': ['vpw-fm', 'vpws', 'vpwa'],
 'x': ['vpx'],
 'y': ['vpython']}
