
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_fd = {'fd.0': 'freedesktop.org',
 'fd.o': 'freedesktop.org',
 'fdacs': 'florida_department_of_agriculture_and_consumer_services',
 'fdau': 'flight-data_acquisition_unit',
 'fdbr': 'florida_department_of_business_and_professional_regulation',
 'fdcc': 'federal_desktop_core_configuration',
 'fdcpa': 'fair_debt_collection_practices_act',
 'fddi': 'fiber_distributed_data_interface',
 'fdfa': 'federal_department_of_foreign_affairs',
 'fdfd': 'finite-difference_frequency-domain',
 'fdg-pet': 'positron_emission_tomography',
 'fdgb': 'free_german_trade_union_federation',
 'fdgbpokal': 'fdgb-pokal',
 'fdgr': 'democratic_forum_of_germans_in_romania',
 'fdha': 'federal_department_of_home_affairs',
 'fdhd': 'superdrive',
 'fdhilb': 'category_of_finite_dimensional_hilbert_spaces',
 'fdhm': 'full_width_at_half_maximum',
 'fdic': 'federal_deposit_insurance_corporation',
 'fdicia': 'federal_deposit_insurance_corporation_improvement_act_of_1991',
 'fdisc': 'fdisk',
 'fdiv': 'pentium_fdiv_bug',
 'fdla': 'democratic_front_for_the_liberation_of_angola',
 'fdle': 'florida_department_of_law_enforcement',
 'fdlr': 'democratic_forces_for_the_liberation_of_rwanda',
 'fdma': 'frequency-division_multiple_access',
 'fdmavica': 'sony_mavica',
 'fdmc': 'francis_douglas_memorial_college',
 'fdmi': 'flat_display_mounting_interface',
 'fdnm': 'fairbanks_daily_news-miner',
 'fdny': 'new_york_city_fire_department',
 'fdopen': 'c_file_input/output',
 'fdos': 'freedos',
 'fdot': 'florida_department_of_transportation',
 'fdqfp13': 'frankenstein_drag_queens_from_planet_13',
 'fdre': 'ethiopia',
 'fdsc': 'foundation_degree',
 'fdsh': 'fort_dodge_senior_high_school',
 'fdsr': 'descriptional_complexity_of_formal_systems',
 'fdtd': 'finite-difference_time-domain_method'}
        