
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_fh = {'fh-1': 'fh_phantom',
 'fh-1100': 'fairchild_hiller_fh-1100',
 'fh-227': 'fairchild_hiller_fh-227',
 'fh-77': 'haubits_fh77/a',
 'fh-deggendorf': 'university_of_applied_sciences_deggendorf',
 'fh506': 'tacrolimus',
 'fhad': 'fahd',
 'fhaw': 'raf_ascension_island',
 'fhchs': 'forest_hill_community_high_school',
 'fhcrc': 'fred_hutchinson_cancer_research_center',
 'fhefssa': 'federal_housing_enterprises_financial_safety_and_soundness_act_of_1992',
 'fheq': 'national_qualifications_framework',
 'fher': 'fernando_olvera',
 'fhfa': 'federal_housing_finance_agency',
 'fhhs': 'forest_hills_high_school',
 'fhia': 'honduras_foundation_for_agricultural_research',
 'fhia-01': 'goldfinger_banana',
 'fhimah': 'lamin_khalifah_fhimah',
 'fhl1': 'factor_h',
 'fhlb': 'federal_home_loan_banks',
 'fhlbb': 'federal_home_loan_banks',
 'fhlmc': 'freddie_mac',
 'fhmonline.com': 'fhm',
 'fhmqv': 'mqv',
 'fho3s': 'fluorosulfuric_acid',
 'fhordism': 'fordism',
 'fhpa': 'family_home_protection_act_1976',
 'fhqwgads': 'homestar_runner',
 'fhqwghads': 'homestar_runner',
 'fhqwhgads': 'homestar_runner',
 'fhsaa': 'florida_high_school_athletic_association',
 'fhsd': 'forest_hills_local_school_district',
 'fhsr': 'florida_high_speed_rail',
 'fhsra': 'florida_high_speed_rail',
 'fhssa': 'foundation_for_hospices_in_sub-saharan_africa',
 'fhsst': 'free_high_school_science_texts',
 'fhtagn': 'cthulhu',
 'fhv-1': 'feline_viral_rhinotracheitis',
 'fhwa': 'federal_highway_administration',
 'fhwqwgads': 'strong_bad',
 'fhwrg': 'oddworld'}
        