
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_jy = {'jy_park': 'park_jin-young',
 'jy_ranch': 'laurance_s._rockefeller_preserve',
 'jydsk_boldspil-union': 'jutland_football_association',
 'jyllands-posten_controversy': 'jyllands-posten_muhammad_cartoons_controversy',
 'jyllands-posten_mohammed': 'jyllands-posten_muhammad_cartoons_controversy',
 'jyllands_posten': 'jyllands-posten',
 'jynnan_tonnyx': 'gin_and_tonic',
 'jynx/version_2': 'jynx',
 'jynx_ruficollis': 'rufous-necked_wryneck',
 'jynx_torquilla': 'eurasian_wryneck',
 'jyo_kido': 'joe_kido',
 'jyoji_shibue': 'jouji_shibue',
 'jyongri_discography': 'jyongri',
 'jyono-uchi_katsuya': 'katsuya_jonouchi',
 'jyonouchi_katsuya': 'katsuya_jonouchi',
 'jyonouchi_tomoya': 'katsuya_jonouchi',
 'jyoonouchi_katsuya': 'katsuya_jonouchi',
 'jyosei_shonan': 'the_prince_of_tennis',
 'jyothi_venkatachalam': 'jyothi_vencatachellum',
 'jyothika_sadanah': 'jyothika_saravanan',
 'jyothir_linga': 'jyotirlinga',
 'jyoti_chitraban': 'jyoti_chitraban_film_and_television_institute',
 'jyoti_class': 'jyoti_class_tanker',
 'jyoti_mishra': 'white_town',
 'jyotiba_phule': 'jyotirao_phule',
 'jyotindranath_mukhopadhyay': 'bagha_jatin',
 'jyotiprasad_agarwala': 'jyoti_prasad_agarwala',
 'jyotiprasad_agarwalla': 'jyoti_prasad_agarwala',
 'jyotir_linga': 'jyotirlinga',
 'jyotir_lingam': 'jyotirlinga',
 'jyotiraditya_scindia': 'jyotiraditya_madhavrao_scindia',
 'jyotsana_patel': 'jyotsna_patel',
 'jyou_kido': 'joe_kido',
 'jyouji_shibue': 'jouji_shibue',
 'jyounouchi_katsuya': 'katsuya_jonouchi',
 'jyounouti_katuya': 'katsuya_jonouchi',
 'jyrki_jaervilehto': 'jj_lehto',
 'jyrki_jarvilehto': 'jj_lehto',
 'jyrki_linnankivi': 'jyrki_69',
 'jyrki_manninen': 'muddy_manninen',
 'jysk_supermarked': 'dansk_supermarked_gruppen',
 'jyske_lov': 'codex_holmiensis',
 'jyu_chyuhn': 'jyu_jik_chuyhn',
 'jyudai_yuki': 'jaden_yuki',
 'jyudai_yuuki': 'jaden_yuki',
 'jyun_woping': 'yuen_woo-ping',
 'jyunichi_masuda': 'junichi_masuda',
 'jyunichiro_koizumi': 'junichiro_koizumi',
 'jyuri_katou': 'jeri_katou',
 'jyushin_enbu': 'hero_tales',
 'jyushin_lyger': 'jushin_liger',
 'jyut_ping': 'jyutping',
 'jyuudai_yuki': 'jaden_yuki',
 'jyuudai_yuuki': 'jaden_yuki'}
        