# coding: utf-8

"""
    eHelply SDK - 1.1.118

    eHelply SDK for SuperStack Services  # noqa: E501

    The version of the OpenAPI document: 1.1.118
    Contact: support@ehelply.com
    Generated by: https://openapi-generator.tech
"""

import unittest

import ehelply_python_experimental_sdk
from ehelply_python_experimental_sdk.api.tag_api import TagApi  # noqa: E501


class TestTagApi(unittest.TestCase):
    """TagApi unit test stubs"""

    def setUp(self):
        self.api = TagApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_tag(self):
        """Test case for delete_tag

        Deletetag  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
