# coding: utf-8

"""
    eHelply SDK - 1.1.118

    eHelply SDK for SuperStack Services  # noqa: E501

    The version of the OpenAPI document: 1.1.118
    Contact: support@ehelply.com
    Generated by: https://openapi-generator.tech
"""

import unittest

import ehelply_python_experimental_sdk
from ehelply_python_experimental_sdk.model.alarm_assign import AlarmAssign


class TestAlarmAssign(unittest.TestCase):
    """AlarmAssign unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def test_AlarmAssign(self):
        """Test AlarmAssign"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AlarmAssign()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
