# coding: utf-8

"""
    eHelply SDK - 1.1.118

    eHelply SDK for SuperStack Services  # noqa: E501

    The version of the OpenAPI document: 1.1.118
    Contact: support@ehelply.com
    Generated by: https://openapi-generator.tech
"""

import unittest

import ehelply_python_experimental_sdk
from ehelply_python_experimental_sdk.model.project_db import ProjectDB


class TestProjectDB(unittest.TestCase):
    """ProjectDB unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def test_ProjectDB(self):
        """Test ProjectDB"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProjectDB()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
