# coding: utf-8

"""
    eHelply SDK - 1.1.118

    eHelply SDK for SuperStack Services  # noqa: E501

    The version of the OpenAPI document: 1.1.118
    Contact: support@ehelply.com
    Generated by: https://openapi-generator.tech
"""

import unittest

import ehelply_python_experimental_sdk
from ehelply_python_experimental_sdk.api.content_api import ContentApi  # noqa: E501


class TestContentApi(unittest.TestCase):
    """ContentApi unit test stubs"""

    def setUp(self):
        self.api = ContentApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_file(self):
        """Test case for create_file

        Createfile  # noqa: E501
        """
        pass

    def test_delete_file(self):
        """Test case for delete_file

        Deletefile  # noqa: E501
        """
        pass

    def test_get_file(self):
        """Test case for get_file

        Getfile  # noqa: E501
        """
        pass

    def test_update_file(self):
        """Test case for update_file

        Updatefile  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
