# coding: utf-8

"""
    herd

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.178.0-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from herdsdk.api_client import ApiClient


class StoragePolicyApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def storage_policy_create_storage_policy(self, storage_policy_create_request, **kwargs):  # noqa: E501
        """createStoragePolicy  # noqa: E501

        Creates a new storage policy. <p>Requires WRITE permission on storage policy namespace and storage policy filter namespace</p>  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.storage_policy_create_storage_policy(storage_policy_create_request, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param StoragePolicyCreateRequest storage_policy_create_request: the information needed to create the storage policy (required)
        :return: StoragePolicy
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.storage_policy_create_storage_policy_with_http_info(storage_policy_create_request, **kwargs)  # noqa: E501
        else:
            (data) = self.storage_policy_create_storage_policy_with_http_info(storage_policy_create_request, **kwargs)  # noqa: E501
            return data

    def storage_policy_create_storage_policy_with_http_info(self, storage_policy_create_request, **kwargs):  # noqa: E501
        """createStoragePolicy  # noqa: E501

        Creates a new storage policy. <p>Requires WRITE permission on storage policy namespace and storage policy filter namespace</p>  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.storage_policy_create_storage_policy_with_http_info(storage_policy_create_request, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param StoragePolicyCreateRequest storage_policy_create_request: the information needed to create the storage policy (required)
        :return: StoragePolicy
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['storage_policy_create_request']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method storage_policy_create_storage_policy" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'storage_policy_create_request' is set
        if ('storage_policy_create_request' not in local_var_params or
                local_var_params['storage_policy_create_request'] is None):
            raise ValueError("Missing the required parameter `storage_policy_create_request` when calling `storage_policy_create_storage_policy`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'storage_policy_create_request' in local_var_params:
            body_params = local_var_params['storage_policy_create_request']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'application/xml'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'application/xml'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basicAuth', 'oauthAuth']  # noqa: E501

        return self.api_client.call_api(
            '/storagePolicies', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='StoragePolicy',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def storage_policy_delete_storage_policy(self, namespace, storage_policy_name, **kwargs):  # noqa: E501
        """deleteStoragePolicy  # noqa: E501

        Deletes an existing storage policy by key. <p>Requires WRITE permission on namespace</p>  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.storage_policy_delete_storage_policy(namespace, storage_policy_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str namespace: the namespace (required)
        :param str storage_policy_name: the storage policy name (required)
        :return: StoragePolicy
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.storage_policy_delete_storage_policy_with_http_info(namespace, storage_policy_name, **kwargs)  # noqa: E501
        else:
            (data) = self.storage_policy_delete_storage_policy_with_http_info(namespace, storage_policy_name, **kwargs)  # noqa: E501
            return data

    def storage_policy_delete_storage_policy_with_http_info(self, namespace, storage_policy_name, **kwargs):  # noqa: E501
        """deleteStoragePolicy  # noqa: E501

        Deletes an existing storage policy by key. <p>Requires WRITE permission on namespace</p>  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.storage_policy_delete_storage_policy_with_http_info(namespace, storage_policy_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str namespace: the namespace (required)
        :param str storage_policy_name: the storage policy name (required)
        :return: StoragePolicy
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['namespace', 'storage_policy_name']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method storage_policy_delete_storage_policy" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'namespace' is set
        if ('namespace' not in local_var_params or
                local_var_params['namespace'] is None):
            raise ValueError("Missing the required parameter `namespace` when calling `storage_policy_delete_storage_policy`")  # noqa: E501
        # verify the required parameter 'storage_policy_name' is set
        if ('storage_policy_name' not in local_var_params or
                local_var_params['storage_policy_name'] is None):
            raise ValueError("Missing the required parameter `storage_policy_name` when calling `storage_policy_delete_storage_policy`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'namespace' in local_var_params:
            path_params['namespace'] = local_var_params['namespace']  # noqa: E501
        if 'storage_policy_name' in local_var_params:
            path_params['storagePolicyName'] = local_var_params['storage_policy_name']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'application/xml'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basicAuth', 'oauthAuth']  # noqa: E501

        return self.api_client.call_api(
            '/storagePolicies/namespaces/{namespace}/storagePolicyNames/{storagePolicyName}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='StoragePolicy',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def storage_policy_get_storage_policy(self, namespace, storage_policy_name, **kwargs):  # noqa: E501
        """getStoragePolicy  # noqa: E501

        Gets an existing storage policy by key. <p>Requires READ permission on namespace</p>  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.storage_policy_get_storage_policy(namespace, storage_policy_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str namespace: the namespace (required)
        :param str storage_policy_name: the storage policy name (required)
        :return: StoragePolicy
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.storage_policy_get_storage_policy_with_http_info(namespace, storage_policy_name, **kwargs)  # noqa: E501
        else:
            (data) = self.storage_policy_get_storage_policy_with_http_info(namespace, storage_policy_name, **kwargs)  # noqa: E501
            return data

    def storage_policy_get_storage_policy_with_http_info(self, namespace, storage_policy_name, **kwargs):  # noqa: E501
        """getStoragePolicy  # noqa: E501

        Gets an existing storage policy by key. <p>Requires READ permission on namespace</p>  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.storage_policy_get_storage_policy_with_http_info(namespace, storage_policy_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str namespace: the namespace (required)
        :param str storage_policy_name: the storage policy name (required)
        :return: StoragePolicy
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['namespace', 'storage_policy_name']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method storage_policy_get_storage_policy" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'namespace' is set
        if ('namespace' not in local_var_params or
                local_var_params['namespace'] is None):
            raise ValueError("Missing the required parameter `namespace` when calling `storage_policy_get_storage_policy`")  # noqa: E501
        # verify the required parameter 'storage_policy_name' is set
        if ('storage_policy_name' not in local_var_params or
                local_var_params['storage_policy_name'] is None):
            raise ValueError("Missing the required parameter `storage_policy_name` when calling `storage_policy_get_storage_policy`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'namespace' in local_var_params:
            path_params['namespace'] = local_var_params['namespace']  # noqa: E501
        if 'storage_policy_name' in local_var_params:
            path_params['storagePolicyName'] = local_var_params['storage_policy_name']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'application/xml'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basicAuth', 'oauthAuth']  # noqa: E501

        return self.api_client.call_api(
            '/storagePolicies/namespaces/{namespace}/storagePolicyNames/{storagePolicyName}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='StoragePolicy',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def storage_policy_get_storage_policy_keys(self, namespace, **kwargs):  # noqa: E501
        """getStoragePolicyKeys  # noqa: E501

        Gets a list of keys for all storage policies defined in the system for the specified namespace. <p>Requires READ permission on namespace</p>  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.storage_policy_get_storage_policy_keys(namespace, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str namespace: the namespace (required)
        :return: StoragePolicyKeys
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.storage_policy_get_storage_policy_keys_with_http_info(namespace, **kwargs)  # noqa: E501
        else:
            (data) = self.storage_policy_get_storage_policy_keys_with_http_info(namespace, **kwargs)  # noqa: E501
            return data

    def storage_policy_get_storage_policy_keys_with_http_info(self, namespace, **kwargs):  # noqa: E501
        """getStoragePolicyKeys  # noqa: E501

        Gets a list of keys for all storage policies defined in the system for the specified namespace. <p>Requires READ permission on namespace</p>  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.storage_policy_get_storage_policy_keys_with_http_info(namespace, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str namespace: the namespace (required)
        :return: StoragePolicyKeys
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['namespace']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method storage_policy_get_storage_policy_keys" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'namespace' is set
        if ('namespace' not in local_var_params or
                local_var_params['namespace'] is None):
            raise ValueError("Missing the required parameter `namespace` when calling `storage_policy_get_storage_policy_keys`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'namespace' in local_var_params:
            path_params['namespace'] = local_var_params['namespace']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'application/xml'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basicAuth', 'oauthAuth']  # noqa: E501

        return self.api_client.call_api(
            '/storagePolicies/namespaces/{namespace}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='StoragePolicyKeys',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def storage_policy_update_storage_policy(self, namespace, storage_policy_name, storage_policy_update_request, **kwargs):  # noqa: E501
        """updateStoragePolicy  # noqa: E501

        Updates an existing storage policy by key. <p>Requires WRITE permission on storage policy namespace and storage policy filter namespace</p>  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.storage_policy_update_storage_policy(namespace, storage_policy_name, storage_policy_update_request, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str namespace: the namespace (required)
        :param str storage_policy_name: the storage policy name (required)
        :param StoragePolicyUpdateRequest storage_policy_update_request: the information needed to update the storage policy (required)
        :return: StoragePolicy
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.storage_policy_update_storage_policy_with_http_info(namespace, storage_policy_name, storage_policy_update_request, **kwargs)  # noqa: E501
        else:
            (data) = self.storage_policy_update_storage_policy_with_http_info(namespace, storage_policy_name, storage_policy_update_request, **kwargs)  # noqa: E501
            return data

    def storage_policy_update_storage_policy_with_http_info(self, namespace, storage_policy_name, storage_policy_update_request, **kwargs):  # noqa: E501
        """updateStoragePolicy  # noqa: E501

        Updates an existing storage policy by key. <p>Requires WRITE permission on storage policy namespace and storage policy filter namespace</p>  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.storage_policy_update_storage_policy_with_http_info(namespace, storage_policy_name, storage_policy_update_request, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str namespace: the namespace (required)
        :param str storage_policy_name: the storage policy name (required)
        :param StoragePolicyUpdateRequest storage_policy_update_request: the information needed to update the storage policy (required)
        :return: StoragePolicy
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['namespace', 'storage_policy_name', 'storage_policy_update_request']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method storage_policy_update_storage_policy" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'namespace' is set
        if ('namespace' not in local_var_params or
                local_var_params['namespace'] is None):
            raise ValueError("Missing the required parameter `namespace` when calling `storage_policy_update_storage_policy`")  # noqa: E501
        # verify the required parameter 'storage_policy_name' is set
        if ('storage_policy_name' not in local_var_params or
                local_var_params['storage_policy_name'] is None):
            raise ValueError("Missing the required parameter `storage_policy_name` when calling `storage_policy_update_storage_policy`")  # noqa: E501
        # verify the required parameter 'storage_policy_update_request' is set
        if ('storage_policy_update_request' not in local_var_params or
                local_var_params['storage_policy_update_request'] is None):
            raise ValueError("Missing the required parameter `storage_policy_update_request` when calling `storage_policy_update_storage_policy`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'namespace' in local_var_params:
            path_params['namespace'] = local_var_params['namespace']  # noqa: E501
        if 'storage_policy_name' in local_var_params:
            path_params['storagePolicyName'] = local_var_params['storage_policy_name']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'storage_policy_update_request' in local_var_params:
            body_params = local_var_params['storage_policy_update_request']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'application/xml'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'application/xml'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basicAuth', 'oauthAuth']  # noqa: E501

        return self.api_client.call_api(
            '/storagePolicies/namespaces/{namespace}/storagePolicyNames/{storagePolicyName}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='StoragePolicy',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)
