
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_mb = {'_': ['mb_roland_distillery', 'mb-2_tow_tractor', 'mb_new_eyes'],
 'a': ['mbabane_government_hospital',
       'mbasic_programming_language',
       'mbabane_highlanders_f.c.',
       'mbale_islamic_university',
       'mbarizunga_game_reserve',
       'mbandzeni_of_swaziland',
       'mbabane_swallows_f.c.',
       'mbara_kwengo_language',
       'mbambe_forest_reserve',
       'mbala_mbuta_biscotte',
       'mbanza_congo_airport',
       'mba_vitus_onyekachi',
       'mbaba_belo_selambar',
       'mbala_henri_balenga',
       'mbarara_high_school',
       'mbamba_bay_language',
       'mbande_ana_nzingha',
       "mbadi_john_ng'ongo",
       'mbanja_worm_lizard',
       'mbaba_mwana_waresa',
       'mba_gyrojet_pistol',
       'mbaye_jacques_diop',
       'mbarara_united_fc',
       'mbaye_dieye_faye',
       'mbarara_city_fc',
       'mbaye_gana_kebe'],
 'b': ['mbb/kawasaki_bk_117',
       'mbb_223_flamingo',
       'mbb_boe_105',
       'mbb_bo_115',
       'mbb_bo_108',
       'mbb_bo_209',
       'mbb_bo_105'],
 'c': ['mbcgame_starcraft_league',
       'mbc_entertainment_awards',
       'mbcevery1_idol_show',
       'mbc_gayo_daejejeon',
       'mbc_dynamo_moscow',
       'mbc_drama_awards',
       'mbc_blue_dragons',
       'mbc_standard_fm',
       'mbc_every_1'],
 'd': ['mbda_european_missile',
       'mbda_deutschland_gmbh',
       'mbda_storm_shadow',
       'mbda_pgm_2000',
       'mbda_pgm_500'],
 'e': ['mbeere_north_constituency',
       'mbeere_south_constituency',
       "mbereshi_girls'_school",
       'mbeya_rural_district',
       'mbella_sonne_dipoko',
       'mbere_rift_valley',
       'mbele_blaise_lelo',
       'mbeya_city_f.c.',
       'mbedi_a_mbongo'],
 'f': ['mbf-m1_m1_astray'],
 'h': ['mbhashe_local_municipality', 'mbh_sigma_relation'],
 'i': ['mbiganyi_charles_tibone',
       'mbilwi_secondary_school',
       'mbissine_therese_diop',
       'mbiuki_japhet_kareke',
       'mbira_nyunga_nyungas',
       'mbira_nyunga_nyunga',
       'mbi_sports_complex',
       'mbizo_johnny_dyani'],
 'k': ['mbk_entertainment_discography', 'mbk_fight_night', 'mbk_spu_nitra'],
 'l': ['mbl_media_school'],
 'm': ['mbm_engineering_college'],
 'n': ['mbna_racepoints_400',
       'mbna_platinum_400',
       'mbna_america_bank',
       'mbna_america_500',
       'mbna_canada_bank',
       'mbna_america_400',
       'mbna_gold_400'],
 'o': ['mbombela_local_municipality',
       'mbombini_molteno_sihele',
       'mbocayaty_del_yhaguy',
       'mbombela_united_f.c.',
       'mbour_petite-cote_fc',
       'mbocayty_del_yhaguy',
       'mbour_sign_language',
       'mbom_mbom_julien',
       'mbo,_akwa_ibom'],
 's': ['mbs_international_airport'],
 't': ['mbta_newburyport/rockport_line',
       'mbta_framingham/worcester_line',
       'mbta_attleboro/stoughton_line',
       'mbta_haverhill/reading_line',
       'mbta_commuter_railroad',
       'mbta_kickback_schemes',
       'mbta_crosstown_buses',
       'mbta_transit_police',
       'mbta_fitchburg_line',
       'mbta_commuter_boat',
       'mbta_commuter_rail',
       'mbta_suburban_rail',
       'mbta_vs._anderson',
       'mbta_lowell_line',
       'mbta_v._anderson',
       'mbta_key_route',
       'mbti_step_ii'],
 'u': ['mbuya_military_hospital',
       'mburucuya_national_park',
       'mbuma_mission_hospital',
       'mbuluzi_game_reserve',
       'mbuji_mayi_airport'],
 'w': ['mbwn_railway_station'],
 'y': ['mbya-guarani_cinema_collective',
       'mbya_guarani_language',
       'mbya_guarani_people']}
