
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_cv = {'_': ['cv_torrelavega',
       'cv_subdivision',
       'cv_padmarajan',
       'cv_ciutadella',
       'cv_alcobendas',
       'cv4_technique',
       'cv_kunhiraman',
       'cv-22_osprey',
       'cv_sreeraman',
       'cv-7_buffalo',
       'cv_barcelona',
       'cv-2_caribou',
       'cv_profiling',
       'cv_stanford',
       'cv_tenerife',
       'cv_wedgwood',
       'cv_murillo',
       'cv_almeria',
       'cv_hartman',
       'cv_logrono',
       'cv_network',
       'cv_sridhar',
       'cv_stephen',
       'cv_joints',
       'cv_teruel',
       'cv_aguere',
       'cv_portol',
       'cv_durell',
       'cv4_virus',
       'cv_villas',
       'cv_xativa',
       'cv_raman',
       'cv_joint',
       'cv_money',
       'cv_tudor',
       'cv_boys',
       'cv_haro',
       'cv_boot',
       'cv_90',
       'cv_33',
       'cv_47'],
 'c': ['cvc_gameline', 'cvc_code'],
 'd': ['cvd_diamond'],
 'e': ['cvetkovic-macek_agreement',
       'cvetkovic,_jastrebarsko',
       'cvetan_churlinov',
       'cvetan_grozdanov',
       'cvetak_zanovetak',
       'cvetanka_petrova',
       'cveta_majtanovic',
       'cvetkova_pijaca',
       'cvetan_cvetanov',
       'cvetana_dekleva',
       'cvetomir_panov',
       'cven,_ljutomer',
       'cvetkovic_brdo',
       'cvetko_rajovic',
       'cvetan_genkov',
       'cveto_pretnar',
       'cvetka_lipus',
       'cveto_pavcic',
       'cvetnic_brdo',
       'cvetka_ahlin',
       'cvetka_bevc',
       'cve_number',
       'cvetni_trg'],
 'i': ['cvijetin_blagojevic',
       'cvijetin_mijatovic',
       'cvitovic,_croatia',
       'cvijan_milosevic',
       'cvitan_spuzevic',
       'cvijanovic_brdo',
       'cvijeta_zuzoric',
       'cvi_starbucks',
       'cvijan_saric',
       'cvitan_galic',
       'cvitko_bilic'],
 'j': ['cvjetkovic_ca-61', 'cvjetkovic_ca-65', 'cvjetko_popovic'],
 'l': ['cvlt_nation'],
 'm': ['cvm_television'],
 'n': ['cvnh_domain', 'cvn_dsph', 'cvn_80', 'cvn_79', 'cvn_i'],
 'p': ['cvp_analysis', 'cvp_line'],
 'r': ['cvr_partners', 'cvrd_inco'],
 's': ['cvs/caremark_corporation',
       'cvs_corporation',
       'cvsd_modulation',
       'cvs_pharmacy',
       'cvs_caremark',
       'cvs_ferrari',
       'cvs_health',
       'cvs_corp.',
       'cvso_30'],
 't': ['cvt2_veltro', 'cvt4_strale', 'cvt1_zigolo', 'cvt_m-300', 'cvt_m-200'],
 'u': ['cvut_fel'],
 'v': ['cvv-4_pellicano', 'cvv-6_canguro', 'cvv2_number', 'cvv_number'],
 'w': ['cvwr_20',
       'cvw_11',
       'cvw_14',
       'cvw_17',
       'cvw_20',
       'cvw_8',
       'cvw_3',
       'cvw_7',
       'cvw_9',
       'cvw_1',
       'cvw_5']}
