
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_pd = {'_': ['pd-4501_scenicruiser',
       'pd_ljubljana-matica',
       'pd_castellarano',
       'pd_subdivision',
       'pd_controller',
       'pd_ouspensky',
       'pd_aerospace',
       'pd_williams',
       'pd_gaitonde',
       'pd_software',
       'pd_eastman',
       'pd_144418',
       'pd_engine',
       'pd_james',
       'pd_ports',
       'pd_drive',
       'pd_cacek',
       'pd_racer',
       'pd_kode',
       'pd_note',
       'pd_draw',
       'pd_5500',
       'pd_360',
       'pd_500',
       'pd_pro',
       'pd_ii'],
 'a': ['pda_dimensions', 'pda_phone', 'pda_case'],
 'b': ['pdbbind_database'],
 'c': ['pdci-rda_house', 'pdca_cycle', 'pdc_darts', 'pdc_2008'],
 'd': ['pdd_25', 'pdd_51'],
 'e': ['pde-constrained_optimization',
       'pde5_inhibitors',
       'pde3_inhibitor',
       'pde5_inhibitor',
       'pde_inhibitor',
       'pde_surfaces',
       'pde_surface',
       "pdei_la'o"],
 'f': ['pdf-xchange_viewer',
       'pdf_association',
       'pdftron_systems',
       'pdf24_creator',
       'pdf_solutions',
       'pdf_software',
       'pdf_creator',
       'pdf_expert',
       'pdf_studio',
       'pdf_reader',
       'pdf/a_mode',
       'pdf_format',
       'pdf_signer',
       'pdf_file'],
 'g': ['pdgf_receptor', 'pdgfb_gene', 'pdg_s.a.'],
 'h': ['pdh_complex'],
 'i': ['pdi_printer'],
 'l': ['pdl_biopharma'],
 'm': ['pdm_university',
       'pdm-1m_mine',
       'pdm-2m_mine',
       'pdm-1_mine',
       'pdm_racing',
       'pdms_stamp',
       'pdm-6_mine',
       'pdm-2_mine',
       'pdm_cycle'],
 'o': ['pdoc_headquarters', 'pdo_planetarium'],
 'p': ['pdp-11_architecture',
       'pdp_london',
       'pdp_cares',
       'pdp_12',
       'pdp_11',
       'pdp_15',
       'pdp_14',
       'pdp_16',
       'pdp_10',
       'pdp_2',
       'pdp_3',
       'pdp_8',
       'pdp_9',
       'pdp_6',
       'pdp_7',
       'pdp_5',
       'pdp_1',
       'pdp_4'],
 'q': ['pdq_chocolate', 'pdq_bach'],
 'r': ['pdrm_fc', 'pdrm_fa'],
 's': ['pds_school', 'pds_110', 'pds_70'],
 't': ['pdt_partners', 'pdt_standard', 'pdt_acharya'],
 'u': ['pdufa_date'],
 'v': ['pdval_affair'],
 'x': ['pdx_airport', 'pdx_fc'],
 'z': ['pdz_protein', 'pdz_domain']}
