
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_fy = {'_': ['fy-1c', 'fy-3a', 'fy5'],
 'a': ['fyataru', 'fyans', 'fyan', 'fyah', 'fyao', 'fyad', 'fya'],
 'b': ['fybromyalgia', 'fyb3roptik', 'fyborg', 'fyb'],
 'c': ['fychan', 'fyco', 'fyc'],
 'e': ['fyers', 'fyer', 'fyeo', 'fyeg', 'fye'],
 'f': ['fyfield', 'fyffes', 'fyffe', 'fyfe'],
 'g': ['fygle', 'fygar'],
 'h': ['fyhs'],
 'i': ['fyifv', 'fyiv', 'fyi'],
 'j': ['fyj'],
 'k': ['fyksesund', 'fyke', 'fyk'],
 'l': ['fyllingenbergen',
       'fyllingsdalen',
       'fylkesbaatane',
       'fylingthorpe',
       'fylkisvollur',
       'fylgjesdalen',
       'fylingsdale',
       'fylingdales',
       'fylkesmann',
       'fylkingen',
       'fylgukona',
       'fylakion',
       'fyllinge',
       'fyllebro',
       'fyldener',
       'fyllida',
       'fylates',
       'fylgjur',
       'fylakio',
       'fyllean',
       'fylfot',
       'fyllia',
       'fylket',
       'fylgja',
       'fylkir',
       'fylgia',
       'fylker',
       'fylgya',
       'fylde',
       'fyllo',
       'fyles',
       'fylla',
       'fylke',
       'fylax',
       'fyli'],
 'm': ['fym'],
 'n': ['fynnoderee',
       'fynbos',
       'fyning',
       'fynes',
       'fynch',
       'fynbo',
       'fynn',
       'fyne',
       'fyn'],
 'o': ['fyodorovskaya',
       'fyodorovskii',
       'fyodorovskiy',
       'fyodorovski',
       'fyodorovsky',
       'fyodorovka',
       'fyodorova',
       'fyodorov',
       'fyodora',
       'fyodor'],
 'p': ['fyp'],
 'r': ['fyrkantsserien',
       'fyrkantserien',
       'fyrmacedondia',
       'fyrtiotalism',
       'fyrisvellir',
       'fyrisbadet',
       'fyrisvold',
       'fyresvatn',
       'fyrudden',
       'fyrishov',
       'fyresdal',
       'fyrnsidu',
       'fyrsjoen',
       'fyrisan',
       'fyrisa',
       'fyrish',
       'fyrkat',
       'fyrom',
       'fyris',
       'fyrde',
       'fyrd',
       'fyra',
       'fyre',
       'fyrm',
       'fyrk',
       'fyr'],
 's': ['fysiostigmine', 'fysics', 'fyson', 'fyska', 'fysop', 'fysh', 'fys'],
 't': ['fyteies', 'fytche', 'fyti', 'fyta', 'fyt'],
 'u': ['fyulaba', 'fyutch', 'fyuse', 'fyu'],
 'v': ['fyvie', 'fyve'],
 'w': ['fywh'],
 'x': ['fyxation'],
 'z': ['fyzabad']}
