
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ue = {'_': ['ue_castelldefels',
       'ue_chenillette',
       'ue..._paisano!',
       "ue_l'estartit",
       'ue_santboiana',
       'ue_extremenya',
       'ue_engordany',
       'ue_rapitenca',
       'ue_vilajuiga',
       'ue_warriors',
       'ue_cornella',
       'ue_figueres',
       'ue_patrick',
       'ue_chorale',
       'ue_alcudia',
       'ue_kedadji',
       'ue_tarrega',
       'ue_amazons',
       'ue_arenal',
       'ue-li_pen',
       'ue_domain',
       'ue_lleida',
       'ue_sants',
       'ue_pages',
       'ue_valls',
       'ue_rubi',
       'ue_boom',
       'ue_roll',
       'ue_olot',
       'ue_avia',
       'ue_news',
       'ue_vic',
       'ue_3.0',
       'ue_900'],
 'a': ['uea_broad'],
 'b': ['uebelmannia_pectinifera',
       'ueberreuter_publishing',
       'uebelmannia_buiningii',
       'uebelmannia_gummifera',
       'ueberreuter_verlag',
       'uebayashi_station',
       'uebeschi_lake',
       'ueberstorf_fr',
       'uebeschi_see',
       'uebert_angel',
       'uebeschi_be',
       'ueba_esou'],
 'c': ['ueckermunde_station',
       'ueckermunde_heath',
       'uecht_observatory',
       'uec-perm_engines',
       'uecker_monument',
       'uechi_kanbun',
       'uec_preston',
       'uec_saturn'],
 'd': ['uedineniya_island',
       'uedahara_station',
       'ueda_campaign',
       'ueda_yasuyuki',
       'ueda_soko-ryu',
       'uedai_station',
       'ueda_tatsuya',
       'ueda_station',
       'uedo_station',
       'ueda_arisawa',
       'ueda_glacier',
       'ueda_akinari',
       'ueda,_nagano',
       'ueda_kiyoshi',
       'ueda_makoto',
       'ueda_castle',
       'ueda_fumito',
       'ueda_domain',
       'ueda_akira',
       'ueda_kana',
       'ueda_soko',
       'ueda_bin'],
 'f': ['uefa_u-21championship',
       'uefa_intertoto-cup',
       'uefa_competitions',
       'uefa_coefficients',
       'uefa_coefficient',
       'uefa_five-star',
       'uefa_challenge',
       'uefa_congress',
       'uefa_rankings',
       'uefa_supercup',
       'uefa_ranking',
       'uefa_striker',
       'uefa_anthem',
       'uefa_awards',
       'uefa_league',
       'uefi_fourm',
       'uefi_forum',
       'uefa_2010',
       'uefa_2008',
       'uefa_2012',
       'uefa_euro',
       'uefa_cup',
       'uefa_68',
       'uefa_cl'],
 'g': ['uegitglanis_zammaranoi', 'uego_sensor'],
 'h': ['uehling,_nebraska',
       'uehling_potential',
       'uehara,_shibuya',
       'uehara_futoshi',
       'uehara_kimiko',
       'uehara_takako',
       'uehara_yusaku',
       'uehara_azumi'],
 'i': ['uei_college'],
 'j': ['uejima_onitsura'],
 'k': ['uekusa_university',
       'uekusa_kazuhide',
       'uekusa_college',
       'ueki,_kumamoto',
       'ueki_station',
       'ueki_hitoshi',
       'ueki_noboru',
       'ueki_emori',
       'ueken_ag'],
 'l': ['uelzen-langwedel_railway',
       'ueli_scheidegger',
       'ueli_gegenschatz',
       'ueli_leuenberger',
       'ueli_tualaulelei',
       'ueli_kestenholz',
       'uelia_sepidapex',
       'uelzen_station',
       'ueli_bodenmann',
       'ueli_bachmann',
       'ueli_schnider',
       'uele_province',
       'ueli_schenkel',
       'uele_district',
       'uell_andersen',
       'ueli_schibler',
       'ueli_steiger',
       'ueli_hofmann',
       'ueli_maurer',
       'ueleni_fono',
       'uel_eubanks',
       'ueli_sutter',
       'uele_river',
       'ueli_wiget',
       'ueli_steck',
       'ueli_mulli',
       'ueli_matti',
       'ueli_staub',
       'uel_graham',
       'ueli_isler',
       'ueli_aebi',
       'uel_key'],
 'm': ['uemoa_tournament',
       'uemura_masakatsu',
       'uemura_masahisa',
       'uematsu_station',
       'uemachi_plateau',
       'uemura_tatsuya',
       'uemura_station',
       'uematsu_nobuo',
       'uemura_soichi',
       'uemura_iemasa',
       'uemura_tatuya',
       'uematu_nobuo',
       'uemura_naomi',
       'uemura_shoen',
       'uemon_ikeda',
       'uem_edgenta',
       'uem_group'],
 'n': ['ueno-okachimachi_station',
       'ueno-hirokoji_station',
       'uenohara_observatory',
       'uenoshiba_station',
       'uenohara_station',
       'ueno-tokyo_line',
       'uenoshi_station',
       'ueno_tsuruhime',
       'ueng_ming-yih',
       'uenae_station',
       'uenohara_site',
       'ueno,_okinawa',
       'ueno_daibutsu',
       'ueno_tosho-gu',
       'ueno_toshiya',
       'ueno_station',
       'ueno,_gunma',
       'ueno_yukiko',
       'ueno_hikoma',
       'uendi_vecaj',
       'ueno_route',
       'ueno_park',
       'ueno_juri',
       'ueno,_mie',
       'ueno_dam',
       'ueno_zoo'],
 'p': ['uep_systems'],
 'r': ['uerikon-bauma_railway',
       'uerikondjera_kasaona',
       'uerdinger_railbus',
       'uerdingen_railbus',
       'uerschhauser_see',
       'uerdingen_hoard',
       'uerdingen_line',
       'uerkheim_ag',
       'uere_river',
       'uerdi_mara'],
 's': ['ueshiba_kisshomaru',
       'uesslingen-buch_tg',
       'uesugi_tsunakatsu',
       'ueshiba_moriteru',
       'uesugi_kagekatsu',
       'uesugi_mochinori',
       'uesugi_shigenori',
       'uesugi_norimasa',
       'uesugi_sadazane',
       'ueshiba_morihei',
       'uesugi_kagetora',
       'uesugi_narinori',
       'uesugi_masatora',
       'uesugi_kagenobu',
       'uesugi_terutora',
       'uesugi_harunori',
       'uesugi_norizane',
       'uesslingen_buch',
       'uesugi_kenshin',
       'ueshima_coffee',
       'uesugi_tomooki',
       'uesugi_akisada',
       'uesugi_youzan',
       'uesugi_family',
       'uesugi_kensin',
       'uesugi_zenshu',
       'uesugi_yozan',
       'uesugi_clan',
       'uesu_gewog',
       'ues_fgc'],
 't': ['uetliberg_tv-tower',
       'uetersen_airfield',
       'ueta_solomona',
       'uetendorf_be',
       'uetz_pelikan',
       'ueta_station',
       'uetsu_line',
       'ueto_aya'],
 'u': ['ueue_zacatzin'],
 'z': ['uezu_house', 'uezwil_ag']}
