
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_uo = {'_': ['uo_gateway', 'uo_aztec'],
 'a': ['uoa_group'],
 'b': ['uob-kay_hian', 'uob_plaza'],
 'c': ['uoc_le'],
 'f': ['uofm_football', 'uofd_jesuit', 'uoft_rowing', 'uofl_health'],
 'i': ['uoif_matteuspojkarna', 'uoit_ridgebacks'],
 'l': ['uolevi_manninen', 'uolevi_kahelin', 'uolevi_raade', 'uol_host'],
 'm': ['uomo_universalis',
       'uomo_universale',
       'uomini_ombra',
       'uom_football',
       'uomini_soli',
       'uoma_beauty'],
 'n': ['uonuma-kyuryo_station',
       'uonuma-nakajo_station',
       'uonuma-tanaka_station',
       'uonquen_airport',
       'uono_river',
       'uong_bi'],
 'p': ['uop_llc'],
 'r': ['uorullubut_kus'],
 's': ['uostadvaris_lighthouse',
       'uosat-12_satellite',
       'uoshima,_ehime',
       'uosat-oscar_11',
       'uosat-oscar_9',
       'uosat_oscar-9'],
 't': ['uottawa_station', 'uotsuri_jima', 'uota_ale'],
 'v': ['uovo_sbattuto'],
 'z': ['uozaki_station',
       'uozumi_station',
       'uozumi_atsuko',
       'uozu_station',
       'uozu,_toyama']}
