
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_uy = {'_': ['uy_volantis', 'uy_scuti'],
 'a': ['uyandik,_kovancilar',
       'uyanga,_ovorkhangai',
       'uyaiedu_ikpe-etim',
       'uyanwatte_stadium',
       'uyarndha_manithan',
       'uyarsky_district',
       'uyanik,_saraykoy',
       'uyagawa_station',
       'uyanga_language',
       'uyama_hisakane',
       'uyarndha_ullam',
       'uyarthiru_420',
       'uyama_hiroto',
       'uya_language',
       'uyajola_9/9',
       'uyanga_bold',
       'uya_oron',
       'uya_oro'],
 'c': ['uychi_district'],
 'e': ['uyedineniya_island',
       'uyea,_northmavine',
       'uyenanao_lake',
       'uyeno_hikoma',
       'uyea,_unst',
       'uyen_linh'],
 'g': ['uyghur-mongolian_script',
       'uyghur_independence',
       'uyghur_nationalism',
       'uyghuric_languages',
       'uyghur_literature',
       'uyghur_separatism',
       'uyghur_languages',
       'uyghur_khaganate',
       'uyghur_alphabets',
       'uyghur_americans',
       'uyghur_phonology',
       'uyghur_kaganate',
       'uyghur_timeline',
       'uyghur_language',
       'uyghur_alphabet',
       'uyghur_dialects',
       'uyghur_tribunal',
       'uyghur_genocide',
       'uyghur_cuisine',
       'uygur_language',
       'uyghur_grammar',
       'uyghur_peoples',
       'uygur_district',
       'uyghur_people',
       'uyghur_turkic',
       'uyghur_empire',
       'uyghur_script',
       'uygur,_amasya',
       'uyghur_music',
       'uyghur_turks',
       'uyghur_muqam',
       'uyghur_riots',
       'uygur,_kulp'],
 'i': ['uyirile_kalanthathu',
       'uyirullavarai_usha',
       'uyirukku_uyiraga',
       'uyirodu_uyiraga',
       'uyire_unakkaga',
       'uyira_maanama',
       'uyire_uyire'],
 'k': ['uyk_8'],
 'l': ['uylupinar,_golhisar'],
 'o': ["uyongu_yata'uyungana",
       'uyo-gakuen_college',
       'uyoku_dantai',
       'uyo_meyo'],
 's': ['uysky_district', 'uys_krige'],
 't': ['uytash_airport'],
 'u': ['uyuk-tarlak_inscription',
       'uyucek,_kizilcahamam',
       'uyuklutatar,_edirne',
       'uyuni_municipality',
       'uyucek,_kastamonu',
       'uyuk,_golpazari',
       'uyurca,_kalecik',
       'uyunid_dynasty',
       'uyun_al-hammam',
       'uyun_al-akhbar',
       'uyunid_emirate',
       'uyuni_airport',
       'uyui_district',
       'uyun_al-wadi',
       'uyun_sahira',
       "uyu_k'uchu",
       'uyu_river',
       'uyu_uyu'],
 'v': ['uyvar_eyalet'],
 'y': ['uyyakondan_thirumalai', 'uyyala_jampala']}
