
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_z_ = {'_': ['z._clava-herculis',
       'z-95_headhunter',
       'z100_university',
       'z._flavescens',
       'z._terrestris',
       'z-80_softcard',
       'z189_shipyard',
       'z._americanus',
       'z800_3dvisor',
       'z173_factory',
       'z._inornatus',
       'z111_factory',
       'z._cornutus',
       'z13_torpedo',
       'z._robustus',
       'z._maculata',
       'z._budapest',
       'z._gracilis',
       'z1_kawasaki',
       'z._insignis',
       'z._japonica',
       'z30_snorna',
       'z8_encore!',
       'z12_snorna',
       'z2_carinae',
       'z._spinosa',
       'z._elegans',
       'z213:_exit',
       'z1_carinae',
       'z18_snorna',
       'z._candida',
       'z*_theorem',
       'z._grandis',
       'z._frankel',
       'z._montana',
       'z._bauman',
       'z1_cancri',
       'z._exigua',
       'z6_snorna',
       'z._indica',
       'z._marcas',
       'z_535-14',
       'z-4_plan',
       'z._phys.',
       'z._libin',
       'z_535-17',
       'z1_boats',
       'z0_probe',
       'z_535-16',
       'z._janko',
       'z._mason',
       'z._laeta',
       'z._ornea',
       'z_550-6',
       'z_23000',
       'z._obed',
       'z._mays',
       'z_20500',
       'z_410-5',
       'z_550-9',
       'z:_zed',
       'z_9001',
       'z_850',
       'z80_a',
       'z1_tv',
       'z_88',
       'z_14'],
 'a': ['z-axis_limited',
       'z_andromedae',
       'z_americanus',
       'z.a._nizami',
       'z.a._suleri',
       'z-axis_ltd.',
       'z_aquarii',
       'z_arietis',
       'z_apodis',
       'z_arae',
       'z_axis',
       'z_and'],
 'b': ['z_batteries',
       'z_budapest',
       'z_battery',
       'z_brewer',
       'z_buffer',
       'z_boson',
       'z_berg',
       'z_bots',
       'z_bend'],
 'c': ['z-code_interpreter',
       'z_communications',
       'z_camelopardalis',
       'z-channel_radio',
       'z_chamaeleontis',
       'z_cassiopeiae',
       'z.c.b.j._hall',
       'z_corporation',
       'z_capricorni',
       'z_chromosome',
       'z_cornutus',
       'z_centauri',
       'z_culling',
       'z_channel',
       'z_carinae',
       'z_curve',
       'z_corp.',
       'z_code',
       'z_cars',
       'z_cas',
       'z_car',
       'z_cam'],
 'd': ['z-disk-associated_protein',
       'z.d._mangoaela',
       'z_division',
       'z_drugs',
       'z_drive',
       'z_drug',
       'z_drag',
       'z_dna'],
 'e': ['z_energy', 'z_event'],
 'f': ['z_filmtidsskrift',
       'z-finger_protein',
       'z_filesystem',
       'z_function',
       'z_fighters',
       'z-form_dna',
       'z_fighter',
       'z-fly_uav',
       'z_factor',
       'z_finger',
       'z_force',
       'z_flag',
       'z+f_uk'],
 'g': ['z.g._clevenger',
       'z_gallerie',
       'z_gundam',
       'z_gorres',
       'z_grill',
       'z_gauge',
       'z_group'],
 'h': ['z@hm@tabad,_bilasuvar', 'z@hm@tabad,_jalilabad', 'z_holdings'],
 'i': ['z_inornatus', 'z_island', 'z_index'],
 'k': ['z.k._matthews', 'z.k._mathews', 'z_knights'],
 'l': ['z_launcher', 'z_living', 'z_lala', 'z_line'],
 'm': ['z-morh_tunnel',
       'z-man_records',
       'z-m_weapons',
       'z-man_games',
       'z_mazinger',
       'z_magazine',
       'z.m._dagar',
       'z_machine',
       'z_movies',
       'z_matrix',
       'z_movie',
       'z_media',
       'z_music',
       'z_man'],
 'n': ['z_notation', 'z_number', 'z_nation', 'z_net'],
 'o': ['z-ordering_utility', 'z-order_curve', 'z_order'],
 'p': ['z-plan_castle',
       'z_particles',
       'z_particle',
       'z_pinch',
       'z_pack',
       'z_plan'],
 'r': ['z-ro_discography',
       'z-ro_tolerance',
       'z@rqava,_agsu',
       'z-rock_hawaii',
       'z@rqava,_quba',
       'z-rated_tires',
       'z@rdab,_agsu',
       'z_roads',
       'z_rink',
       'z_road',
       'z_rock',
       'z_ram'],
 's': ['z-scan_measurements',
       'z-scan_measurement',
       'z-source_inverter',
       'z-scan_technique',
       'z-series_trains',
       'z_statistic',
       'z_security',
       'z_society',
       'z_spinosa',
       'z_scores',
       'z_series',
       'z_storm',
       'z_score',
       'z_shell',
       'z_space',
       'z_scale',
       'z_sweet',
       'z_scan'],
 't': ['z-trip_discography',
       'z.tao_discography',
       'z.t._serdiuk',
       'z_terrestris',
       'z_transform',
       'z_train',
       'z_table',
       'z_twins',
       'z_test',
       'z_top'],
 'u': ['z_unit'],
 'v': ['z.vex_effects', 'z_variant', 'z_value', 'z_video', 'z_vex'],
 'w': ['z-wave_alliance'],
 'y': ['z@ylik,_dashkasan',
       'z@ylik,_kalbajar',
       'z@y@m,_zaqatala',
       'z@y@m_cirdaxan',
       'z@y@m,_shamkir',
       'z@y@m,_qakh',
       'z.y._fu'],
 'z': ['z.z._hill', 'z.z._top']}
