
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_iq = {'_': ['iq_calmodulin-binding_region',
       'iq_calmodulin-binding_motif',
       'iq_student_accommodation',
       'iq_test_controversy',
       'iq_reference_chart',
       'iq_business_group',
       'iq_of_nations',
       'iq_by_country',
       'iq_and_race',
       'iq_of_bush'],
 'a': ['iqaluit_public_transit', 'iqaluit_city_council', 'iqa_world_cup'],
 'b': ['iqbalpur_railway_station',
       'iqbal_memorial_institute',
       'iqbal_hossain_chowdhury',
       'iqbal_academy_pakistan',
       'iqbal_town,_faisalabad',
       'iqbal_sobhan_chowdhury',
       'iqbal_bahar_chowdhury',
       'iqbal_hussain_qureshi',
       'iqbal_hussain_durrani',
       'iqbaljit_singh_grewal',
       'iqbal_dawood_pakwala',
       'iqbal_hossain_sabuj',
       'iqbal_baloch_colony',
       'iqbal_singh_jhundan',
       'iqbal_karim_bhuiyan',
       'iqbal_ahmed_saradgi',
       'iqbal_singh_lalpura',
       'iqbal_zafar_jhagra',
       'iqbal_mohammad_ali',
       'iqbal_town,_lahore',
       'iqbal_ahmed_ansari',
       'iqbal_singh_chahal',
       'iqbal_khan_jadoon',
       'iqbal_hossain_apu',
       'iqbal_ahmad_khan',
       'iqbal_asif_jewel',
       'iqbal_z._ahmed',
       'iqbal_f._qadir'],
 'f': ['iqfoil_european_championships', 'iqfoil_world_championships'],
 'r': ['iqra_national_university',
       'iqroop_singh_ghuman',
       'iqraar_by_chance',
       'iqrar_ahmad_khan',
       'iqrar_ul_hassan'],
 'u': ['iquitos_international_airport',
       'iquitos_metropolitan_area',
       'ique_ecological_station',
       'iquiri_national_forest',
       'iquique_naval_combat',
       'ique_ds_lite']}
