
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_ey = {'eyalet_of_rumelia': 'rumelia',
 'eyaw_nayr/russell_corporation': 'russell_corporation',
 'eydie_d._whittington': 'eydie_whittington',
 'eye-ringed_tody_tyrant': 'eye-ringed_tody-tyrant',
 'eye_black_grease': 'eye_black',
 'eye_blink_conditioning': 'eyeblink_conditioning',
 'eye_brow_tattoo': 'permanent_makeup',
 'eye_hate_god': 'eyehategod',
 'eye_hate_u': 'i_hate_u',
 'eye_industries_records': 'eye_industries',
 'eye_movement_desensitization': 'eye_movement_desensitization_and_reprocessing',
 'eye_of_africa': 'richat_structure',
 'eye_of_argon': 'the_eye_of_argon',
 'eye_of_balor': 'balor',
 'eye_of_fatima': 'hamsa',
 'eye_of_god': 'helix_nebula',
 'eye_of_judgement': 'the_eye_of_judgment',
 'eye_of_judgment': 'the_eye_of_judgment',
 'eye_of_london': 'london_eye',
 'eye_of_palpatine': 'children_of_the_jedi',
 'eye_of_quebec': 'manicouagan_reservoir',
 'eye_of_ra': 'eye_of_horus',
 'eye_of_revelation': 'five_tibetan_rites',
 'eye_on_people': 'investigation_discovery',
 'eye_on_sports': 'cbs_sports_spectacular',
 'eye_roll_test': 'hypnotic_susceptibility',
 'eye_see_you': 'd-tox',
 'eye_shield_21': 'eyeshield_21',
 'eye_toy_groove': 'eyetoy:_groove',
 'eyebrowed_jungle_flycatcher': 'eyebrowed_jungle-flycatcher',
 'eyecandy_acceleration_architecture': 'exa',
 'eyelash_bush_viper': 'atheris_ceratophora',
 'eyelash_leaved_sage': 'salvia_blepharophylla',
 'eyelash_mountain_viper': 'bothriechis_schlegelii',
 'eyelash_pit_viper': 'bothriechis_schlegelii',
 'eyelash_pixie_cup': 'scutellinia_scutellata',
 'eyemouth_united_fc': 'eyemouth_united_f.c.',
 'eyes_cold_lemonade': 'happy_tree_friends',
 'eyes_for_eyes': 'eye_for_an_eye',
 'eyes_of_mystery': 'the_eyes_of_mystery',
 'eyes_of_nye': 'the_eyes_of_nye',
 'eyes_of_texas': 'the_eyes_of_texas',
 'eyes_on_fire': 'blue_foundation',
 'eyetoy:_chat_light': 'eyetoy:_chat',
 'eyewitness_travel_guides': 'eyewitness_books',
 'eyghon_the_sleepwalker': 'the_dark_age',
 'eyke_von_repchowe': 'eike_von_repgow',
 'eyke_von_repgow': 'eike_von_repgow',
 'eyke_von_repkow': 'eike_von_repgow',
 'eylesbarrow_tin_mine': 'eylesbarrow_mine',
 'eymard_g._corbin': 'eymard_corbin',
 'eymard_georges_corbin': 'eymard_corbin',
 'eynesbury_rovers_fc': 'eynesbury_rovers_f.c.',
 'eyre_botanic_district': 'esperance_plains',
 'eyre_botanical_district': 'esperance_plains',
 'eyre_m._shaw': 'eyre_massey_shaw',
 'eyre_peninsular_railway': 'eyre_peninsula_railway',
 'eyring_research_institutie': 'eyring_research_institute',
 'eyring_science_center': 'carl_f._eyring_science_center',
 'eystein_i_magnusson': 'eystein_i_of_norway'}
        