
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_uz = {'_': ['uz_marsala_tita', 'uz_class_675', 'uz_jsme_doma'],
 'a': ['uzamat_akinbile_yussuf',
       'uzalud_behari_mirisu',
       'uzair_gul_peshawari',
       'uzair_zaheer_khan',
       'uzana_of_toungoo',
       'uzana_of_bassein',
       'uzal_girard_ent',
       'uzana_of_pagan'],
 'b': ['uzbekistan_football_association',
       'uzbekistan_banking_association',
       'uzbekistani_chess_championship',
       'uzbekistan_football_federation',
       'uzbekistani_political_system',
       'uzbekistan_tennis_federation',
       'uzbekistan_rugby_federation',
       'uzbekistan_communist_party',
       'uzbek_football_federation',
       'uzbek_soviet_encyclopedia',
       'uzbek_diplomatic_missions',
       'uzbekistan_national_guard',
       'uzbekistan_second_league',
       'uzbekistan_futsal_league',
       'uzbekistan_pro-b_league',
       'uzbekistan_super_league',
       'uzbek_political_system',
       'uzbek_state_university',
       'uzbekistan_pro_league',
       'uzbekistan_league_cup',
       'uzbek_communist_party',
       'uzbekistan_super_cup',
       'uzbek_ground_forces',
       'uzbin_valley_ambush',
       'uzbeks_in_pakistan',
       'uzbek_river_force',
       'uzbeks_in_russia',
       'uzbeks_in_turkey',
       'uzbek_el_clasico',
       'uzbek_black_goat'],
 'e': ['uzen_oil_field', 'uzee_brown_jr.'],
 'h': ['uzhhorod-kosice_broad-gauge_track',
       'uzhhorod_international_airport',
       'uzhhorod_national_university',
       'uzhhorod_orthodox_cathedral',
       'uzhavar_uzhaippalar_katchi',
       'uzhivka,_novoazovsk_raion',
       'uzhhorod_railway_station',
       'uzhgorod_railway_station',
       'uzhaippali_makkal_katchi',
       'uzhgorod_rail_terminal',
       'uzhaithu_vaazha_vendum',
       'uzhhorod_rail_terminal'],
 'i': ['uzi_submachine_gun',
       'uzice_city_stadium',
       'uzicka_crna_gora',
       'uzi_does_it',
       'uzi_and_ari'],
 'm': ['uzma_zahid_bukhari',
       'uzma_riaz_jadoon',
       'uzma_aslam_khan',
       'uzmi_ili_ostavi',
       'uzma_z._rizvi'],
 'n': ['uznach_railway_station'],
 't': ['uztarroz_-_uztarrotze'],
 'u': ['uzumasa_tenjingawa_station',
       'uzun-akmat_forest_reserve',
       'uzunkopru_railway_station',
       'uzuegbunam_v._preczewski',
       'uzun_darreh-ye_sofla',
       'uzun_tappeh-ye_sofla',
       'uzun_tappeh-ye_olya',
       'uzun_darreh-ye_olya',
       'uzungwa_red_colobus',
       'uzunkum_nature_park',
       'uzulmez_coal_mine',
       'uzungwe_vlei_rat'],
 'w': ['uzwil_railway_station'],
 'z': ['uzziah_of_judah']}
