
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_zr = {'a': ['zrarieh_raid'],
 'e': ['zrenjanin_municipality',
       'zrecze_chalupczanskie',
       'zrenjanin_airport',
       'zrenjanin_theatre',
       'zrecze_duze',
       'zrecze_male',
       'zrebar_lake'],
 'i': ['zrinski_topolovac',
       'zrinski_battalion',
       'zrinjski_mostar',
       'zrinka_cvitesic',
       'zrinski_bridge',
       'zrinski_family',
       'zrinko_ogresta',
       'zrinka_ljutic',
       'zrinski_park',
       'zrinska_gora',
       'zrin_castle'],
 'k': ['zrk_arandelovac',
       'zrk_danilovgrad',
       'zrk_ajdovscina',
       'zrkadlo_rokov',
       'zrk_kumanovo',
       'zrk_pelister',
       'zrk_metalurg',
       'zrk_velenje',
       'zrk_zajecar',
       'zrk_vardar',
       'zrk_ilidza',
       'zrk_naisa',
       'zrk_celje',
       'zrk_zamet',
       'zrk_borac'],
 'n': ['zrnovci_municipality', 'zrnovci_opstina'],
 'o': ['zrock_103.3', 'zrock_103'],
 'u': ['zrubavel_gilad'],
 'z': ['zrzeszenie_kaszubsko-pomorskie', 'zrze_monastery']}
