
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rl = {'_': ['rl-83_blindicide',
       'rl_premiership',
       'rl_conference',
       'rl_gyroscope',
       'rl_stevenson',
       'rl_kirkland',
       'rl_burnside',
       'rl_football',
       'rl_circuits',
       'rl_syndrome',
       'rl:_ements',
       'rl_network',
       'rl_circuit',
       'rl_jalappa',
       'rl_brooks',
       'rl_bhatia',
       'rl_grime',
       'rl_stein',
       'rl_stine',
       'rl_polk',
       'rl_ryan',
       'rl_gyro',
       'rl_24'],
 'c': ['rlc_conference',
       'rlc_circuits',
       'rlc_circuit',
       'rlc_network',
       'rlc_museum',
       'rlc_filter'],
 'd': ['rlds_church'],
 'e': ['rle_compression'],
 'f': ['rlf_brands'],
 'g': ['rlg_communications'],
 'i': ['rlim_shaikorth', 'rlif_awards', 'rli_corp.'],
 'j': ['rlj_companies', 'rlje_films'],
 'k': ['rlk_virchow'],
 'l': ['rll_interface'],
 's': ['rls_algorithm', 'rls_filter'],
 't': ['rlt_college'],
 'u': ['rlu-1_breezy'],
 'x': ['rlx_technologies']}
