
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rj = {'_': ['rj_vigneshkanth',
       'rj_shaughnessy',
       'rj_motorsports',
       'rj_hollingdale',
       'rj_mendenhall',
       'rj_washington',
       'rj_liebenberg',
       'rj._mitchell',
       'rj_billinton',
       'rj_sternberg',
       'rj_connector',
       'rj_sigurdson',
       'rj_thompson',
       'rj_benjamin',
       'rj_reynolds',
       'rj_campbell',
       'rj_williams',
       'rj_morrison',
       'rj_mitchell',
       'rj_malishka',
       'rj_umberger',
       'rj_nembhard',
       'rj_rosales',
       'rj_praveen',
       'rj_jimenez',
       'rj_herrera',
       'rj_pradeep',
       'rj_padilla',
       'rj_swindle',
       'rj_ophelia',
       'rj_yeatman',
       'rj_brandes',
       'rj_barrett',
       'rj_hadley',
       'rj_gannon',
       'rj_soward',
       'rj_harris',
       'rj_seddon',
       'rj_mccone',
       'rj_brande',
       'rj_dheena',
       'rj_rummel',
       'rj_balaji',
       'rj_corman',
       'rj_cutler',
       'rj_hemant',
       'rj_thomas',
       'rj_nuevas',
       'rj_texted',
       'rj_hopper',
       'rj_brewer',
       'rj_rohith',
       'rj_mical',
       'rj_100.3',
       'rj_adams',
       'rj_berry',
       'rj_cobbs',
       'rj_jazul',
       'rj_duets',
       'rj_cyler',
       'rj_nieto',
       'rj_mitte',
       'rj_stove',
       'rj_renu',
       'rj_dent',
       'rj_1200',
       'rj_berg',
       'rj_king',
       'rj_may',
       'rj_100'],
 'a': ['rjana_luzica'],
 'b': ['rjb_mining', 'rjb_knight', 'rjb_20-22'],
 'e': ['rjebtsun_dampa', 'rjecica_gornja', 'rjecica_donja', 'rje_mkhan-po'],
 'g': ['rjg_inc.'],
 'p': ['rjp_williams'],
 'r': ['rjr_championship', 'rjr_nabisco'],
 't': ['rjtv_29'],
 'u': ['rjukan_arbeiderblad', 'rjukan_station', 'rjukan_falls', 'rjukan_line'],
 'v': ['rjv_oil', 'rjv_gas'],
 'y': ['rjyan_kidwell']}
