
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-21T22:35:03+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "9fd676fc217a8259b02dec2a95f786cd2ee5ec80",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
