# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_type.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data_type.proto',
  package='oi.papi',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x64\x61ta_type.proto\x12\x07oi.papi\"k\n\x08\x44\x61taType\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0e\n\x06schema\x18\x03 \x01(\t\x12\x17\n\x0f\x64\x61ta_source_ids\x18\x04 \x03(\t\x12\x13\n\x0bsensor_type\x18\x05 \x01(\t\"_\n\x15\x44\x61taTypeCreateRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0e\n\x06schema\x18\x03 \x01(\t\x12\x13\n\x0bsensor_type\x18\x04 \x01(\t\"S\n\x16\x44\x61taTypeCreateResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\r\x12$\n\tdata_type\x18\x02 \x01(\x0b\x32\x11.oi.papi.DataType\"!\n\x12\x44\x61taTypeGetRequest\x12\x0b\n\x03ids\x18\x01 \x03(\t\"Q\n\x13\x44\x61taTypeGetResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\r\x12%\n\ndata_types\x18\x02 \x03(\x0b\x32\x11.oi.papi.DataType\"*\n\x13\x44\x61taTypeListRequest\x12\x13\n\x0bsearch_text\x18\x01 \x01(\t\"R\n\x14\x44\x61taTypeListResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\r\x12%\n\ndata_types\x18\x02 \x03(\x0b\x32\x11.oi.papi.DataType2\xdf\x01\n\x0b\x44\x61taTypeAPI\x12I\n\x06\x63reate\x12\x1e.oi.papi.DataTypeCreateRequest\x1a\x1f.oi.papi.DataTypeCreateResponse\x12@\n\x03get\x12\x1b.oi.papi.DataTypeGetRequest\x1a\x1c.oi.papi.DataTypeGetResponse\x12\x43\n\x04list\x12\x1c.oi.papi.DataTypeListRequest\x1a\x1d.oi.papi.DataTypeListResponseb\x06proto3'
)




_DATATYPE = _descriptor.Descriptor(
  name='DataType',
  full_name='oi.papi.DataType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='oi.papi.DataType.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='oi.papi.DataType.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='schema', full_name='oi.papi.DataType.schema', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_source_ids', full_name='oi.papi.DataType.data_source_ids', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sensor_type', full_name='oi.papi.DataType.sensor_type', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=135,
)


_DATATYPECREATEREQUEST = _descriptor.Descriptor(
  name='DataTypeCreateRequest',
  full_name='oi.papi.DataTypeCreateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='oi.papi.DataTypeCreateRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='oi.papi.DataTypeCreateRequest.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='schema', full_name='oi.papi.DataTypeCreateRequest.schema', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sensor_type', full_name='oi.papi.DataTypeCreateRequest.sensor_type', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=232,
)


_DATATYPECREATERESPONSE = _descriptor.Descriptor(
  name='DataTypeCreateResponse',
  full_name='oi.papi.DataTypeCreateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status_code', full_name='oi.papi.DataTypeCreateResponse.status_code', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_type', full_name='oi.papi.DataTypeCreateResponse.data_type', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=317,
)


_DATATYPEGETREQUEST = _descriptor.Descriptor(
  name='DataTypeGetRequest',
  full_name='oi.papi.DataTypeGetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ids', full_name='oi.papi.DataTypeGetRequest.ids', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=319,
  serialized_end=352,
)


_DATATYPEGETRESPONSE = _descriptor.Descriptor(
  name='DataTypeGetResponse',
  full_name='oi.papi.DataTypeGetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status_code', full_name='oi.papi.DataTypeGetResponse.status_code', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_types', full_name='oi.papi.DataTypeGetResponse.data_types', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=354,
  serialized_end=435,
)


_DATATYPELISTREQUEST = _descriptor.Descriptor(
  name='DataTypeListRequest',
  full_name='oi.papi.DataTypeListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='search_text', full_name='oi.papi.DataTypeListRequest.search_text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=437,
  serialized_end=479,
)


_DATATYPELISTRESPONSE = _descriptor.Descriptor(
  name='DataTypeListResponse',
  full_name='oi.papi.DataTypeListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status_code', full_name='oi.papi.DataTypeListResponse.status_code', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_types', full_name='oi.papi.DataTypeListResponse.data_types', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=481,
  serialized_end=563,
)

_DATATYPECREATERESPONSE.fields_by_name['data_type'].message_type = _DATATYPE
_DATATYPEGETRESPONSE.fields_by_name['data_types'].message_type = _DATATYPE
_DATATYPELISTRESPONSE.fields_by_name['data_types'].message_type = _DATATYPE
DESCRIPTOR.message_types_by_name['DataType'] = _DATATYPE
DESCRIPTOR.message_types_by_name['DataTypeCreateRequest'] = _DATATYPECREATEREQUEST
DESCRIPTOR.message_types_by_name['DataTypeCreateResponse'] = _DATATYPECREATERESPONSE
DESCRIPTOR.message_types_by_name['DataTypeGetRequest'] = _DATATYPEGETREQUEST
DESCRIPTOR.message_types_by_name['DataTypeGetResponse'] = _DATATYPEGETRESPONSE
DESCRIPTOR.message_types_by_name['DataTypeListRequest'] = _DATATYPELISTREQUEST
DESCRIPTOR.message_types_by_name['DataTypeListResponse'] = _DATATYPELISTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataType = _reflection.GeneratedProtocolMessageType('DataType', (_message.Message,), {
  'DESCRIPTOR' : _DATATYPE,
  '__module__' : 'data_type_pb2'
  # @@protoc_insertion_point(class_scope:oi.papi.DataType)
  })
_sym_db.RegisterMessage(DataType)

DataTypeCreateRequest = _reflection.GeneratedProtocolMessageType('DataTypeCreateRequest', (_message.Message,), {
  'DESCRIPTOR' : _DATATYPECREATEREQUEST,
  '__module__' : 'data_type_pb2'
  # @@protoc_insertion_point(class_scope:oi.papi.DataTypeCreateRequest)
  })
_sym_db.RegisterMessage(DataTypeCreateRequest)

DataTypeCreateResponse = _reflection.GeneratedProtocolMessageType('DataTypeCreateResponse', (_message.Message,), {
  'DESCRIPTOR' : _DATATYPECREATERESPONSE,
  '__module__' : 'data_type_pb2'
  # @@protoc_insertion_point(class_scope:oi.papi.DataTypeCreateResponse)
  })
_sym_db.RegisterMessage(DataTypeCreateResponse)

DataTypeGetRequest = _reflection.GeneratedProtocolMessageType('DataTypeGetRequest', (_message.Message,), {
  'DESCRIPTOR' : _DATATYPEGETREQUEST,
  '__module__' : 'data_type_pb2'
  # @@protoc_insertion_point(class_scope:oi.papi.DataTypeGetRequest)
  })
_sym_db.RegisterMessage(DataTypeGetRequest)

DataTypeGetResponse = _reflection.GeneratedProtocolMessageType('DataTypeGetResponse', (_message.Message,), {
  'DESCRIPTOR' : _DATATYPEGETRESPONSE,
  '__module__' : 'data_type_pb2'
  # @@protoc_insertion_point(class_scope:oi.papi.DataTypeGetResponse)
  })
_sym_db.RegisterMessage(DataTypeGetResponse)

DataTypeListRequest = _reflection.GeneratedProtocolMessageType('DataTypeListRequest', (_message.Message,), {
  'DESCRIPTOR' : _DATATYPELISTREQUEST,
  '__module__' : 'data_type_pb2'
  # @@protoc_insertion_point(class_scope:oi.papi.DataTypeListRequest)
  })
_sym_db.RegisterMessage(DataTypeListRequest)

DataTypeListResponse = _reflection.GeneratedProtocolMessageType('DataTypeListResponse', (_message.Message,), {
  'DESCRIPTOR' : _DATATYPELISTRESPONSE,
  '__module__' : 'data_type_pb2'
  # @@protoc_insertion_point(class_scope:oi.papi.DataTypeListResponse)
  })
_sym_db.RegisterMessage(DataTypeListResponse)



_DATATYPEAPI = _descriptor.ServiceDescriptor(
  name='DataTypeAPI',
  full_name='oi.papi.DataTypeAPI',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=566,
  serialized_end=789,
  methods=[
  _descriptor.MethodDescriptor(
    name='create',
    full_name='oi.papi.DataTypeAPI.create',
    index=0,
    containing_service=None,
    input_type=_DATATYPECREATEREQUEST,
    output_type=_DATATYPECREATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get',
    full_name='oi.papi.DataTypeAPI.get',
    index=1,
    containing_service=None,
    input_type=_DATATYPEGETREQUEST,
    output_type=_DATATYPEGETRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='list',
    full_name='oi.papi.DataTypeAPI.list',
    index=2,
    containing_service=None,
    input_type=_DATATYPELISTREQUEST,
    output_type=_DATATYPELISTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATATYPEAPI)

DESCRIPTOR.services_by_name['DataTypeAPI'] = _DATATYPEAPI

# @@protoc_insertion_point(module_scope)
