# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: token.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from terrascope_api.models import common_models_pb2 as common__models__pb2

from terrascope_api.models.common_models_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='token.proto',
  package='oi.papi',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0btoken.proto\x12\x07oi.papi\x1a\x13\x63ommon_models.proto\"C\n\x12TokenCreateRequest\x12\x18\n\x10\x64uration_minutes\x18\x01 \x01(\x05\x12\x13\n\x0b\x66or_user_id\x18\x02 \x01(\t\"=\n\x13TokenCreateResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\r\x12\x11\n\tjwt_token\x18\x02 \x01(\t2O\n\x08TokenApi\x12\x43\n\x06\x63reate\x12\x1b.oi.papi.TokenCreateRequest\x1a\x1c.oi.papi.TokenCreateResponseP\x00\x62\x06proto3'
  ,
  dependencies=[common__models__pb2.DESCRIPTOR,],
  public_dependencies=[common__models__pb2.DESCRIPTOR,])




_TOKENCREATEREQUEST = _descriptor.Descriptor(
  name='TokenCreateRequest',
  full_name='oi.papi.TokenCreateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='duration_minutes', full_name='oi.papi.TokenCreateRequest.duration_minutes', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='for_user_id', full_name='oi.papi.TokenCreateRequest.for_user_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=112,
)


_TOKENCREATERESPONSE = _descriptor.Descriptor(
  name='TokenCreateResponse',
  full_name='oi.papi.TokenCreateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status_code', full_name='oi.papi.TokenCreateResponse.status_code', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='jwt_token', full_name='oi.papi.TokenCreateResponse.jwt_token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=175,
)

DESCRIPTOR.message_types_by_name['TokenCreateRequest'] = _TOKENCREATEREQUEST
DESCRIPTOR.message_types_by_name['TokenCreateResponse'] = _TOKENCREATERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TokenCreateRequest = _reflection.GeneratedProtocolMessageType('TokenCreateRequest', (_message.Message,), {
  'DESCRIPTOR' : _TOKENCREATEREQUEST,
  '__module__' : 'token_pb2'
  # @@protoc_insertion_point(class_scope:oi.papi.TokenCreateRequest)
  })
_sym_db.RegisterMessage(TokenCreateRequest)

TokenCreateResponse = _reflection.GeneratedProtocolMessageType('TokenCreateResponse', (_message.Message,), {
  'DESCRIPTOR' : _TOKENCREATERESPONSE,
  '__module__' : 'token_pb2'
  # @@protoc_insertion_point(class_scope:oi.papi.TokenCreateResponse)
  })
_sym_db.RegisterMessage(TokenCreateResponse)



_TOKENAPI = _descriptor.ServiceDescriptor(
  name='TokenApi',
  full_name='oi.papi.TokenApi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=177,
  serialized_end=256,
  methods=[
  _descriptor.MethodDescriptor(
    name='create',
    full_name='oi.papi.TokenApi.create',
    index=0,
    containing_service=None,
    input_type=_TOKENCREATEREQUEST,
    output_type=_TOKENCREATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TOKENAPI)

DESCRIPTOR.services_by_name['TokenApi'] = _TOKENAPI

# @@protoc_insertion_point(module_scope)
