
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_wb = {'_': ['wb_electronics_warmate',
       'wb_television_network',
       'wb_games_montreal',
       'wb_sinaai_girls',
       'wb_games_boston'],
 'a': ['wba_featherweight_champion',
       'wba_cruiserweight_champion',
       'wba_minimumweight_champion',
       'wba_welterweight_champion',
       'wba_bantamweight_champion',
       'wba_middleweight_champion',
       'wba_lightweight_champion',
       'wba_heavyweight_champion',
       'wba_flyweight_champion',
       'wbab_homegrown_album',
       'wbay_tv_tower'],
 'c': ['wbc_minimumweight_champion',
       'wbc_featherweight_champion',
       'wbc_cruiserweight_champion',
       'wbc_welterweight_champion',
       'wbc_bantamweight_champion',
       'wbc_heavyweight_champion',
       'wbc_lightweight_champion',
       'wbc_flyweight_champion',
       'wbc_neftokhimik_burgas',
       'wbc_dynamo_novosibirsk',
       'wbc_lokomotiv_sofia',
       'wbc_spartak_noginsk',
       'wbc_maritsa_plovdiv',
       'wbc_akademik_sofia',
       'wbc_spartak_moscow',
       'wbc_minyor_pernik',
       'wbc_slavia_sofia',
       'wbc_montana_2003',
       'wbc_dynamo_kyiv',
       'wbc_cska_moscow',
       'wbc_the_palace',
       'wbc_dunav_ruse'],
 'e': ['wbem_services_specification'],
 'f': ['wbf_open_ranking', 'wbf_youth_award'],
 'n': ['wbns_tv_tower'],
 'o': ['wbo_minimumweight_champion',
       'wbo_cruiserweight_champion',
       'wbo_featherweight_champion',
       'wbo_bantamweight_champion',
       'wbo_welterweight_champion',
       'wbo_lightweight_champion',
       'wbo_flyweight_champion'],
 'r': ['wbr_sessions_ep'],
 's': ['wbsc_world_rankings'],
 'v': ['wbvp_and_wmba'],
 'z': ['wbzy_northern_might']}
