
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-18T13:00:14-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "1392d9386ec1cd517ce32eec90ebbe253fb0938c",
 "version": "0.8.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
