
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_wc = {'wc_bradley_co.': 'w._c._bradley_co.',
 'wc_eaket_ss': 'w._c._eaket_secondary_school',
 'wc_handy_award': 'blues_music_award',
 'wc_peterson_auditorium': 'w._c._peterson_auditorium',
 'wc_postal_area': 'london_postal_district',
 'wc_programming_language': 'c_stamp',
 'wca_flight_956': 'west_coast_airlines_flight_956',
 'wcal_91.9_fm': 'wcal',
 'wcau_local_programs': 'wcau',
 'wcau_news_team': 'wcau',
 'wcbs-hdtv_news_team': 'wcbs-tv',
 'wcbs-tv_news_team': 'wcbs-tv',
 'wccw_heavyweight_championship': 'wcwa_world_heavyweight_championship',
 'wccw_television_championship': 'wcwa_television_championship',
 'wces_tv_tower': 'wces-tv',
 'wci_communities_inc.': 'wci_communities',
 'wci_home_video': 'warner_home_video',
 'wcpt_850_am': 'wcpt',
 'wcsc_television_tower': 'wcsc-tv',
 'wct_scottsdale_open': 'tennis_channel_open',
 'wcw/new_japan_show': 'wcw/new_japan_supershow',
 'wcw/nwo_souled_out': 'souled_out',
 'wcw_battle_bowl': 'battlebowl',
 'wcw_beach_blast': 'beach_blast',
 'wcw_canadian_championship': 'wwe_united_states_championship',
 'wcw_cruiserweight_championship': 'wwe_cruiserweight_championship',
 'wcw_cruiserweight_title': 'wwe_cruiserweight_championship',
 'wcw_fall_brawl': 'fall_brawl',
 'wcw_halloween_havoc': 'halloween_havoc',
 'wcw_hardcore_champion': 'wcw_hardcore_championship',
 'wcw_hardcore_title': 'wcw_hardcore_championship',
 'wcw_international_championship': 'wcw_international_world_heavyweight_championship',
 'wcw_millenium_final': 'millennium_final',
 'wcw_millennium_final': 'world_championship_wrestling',
 'wcw_road_wild': 'road_wild',
 'wcw_saturday_morning': 'wcw_saturday_night',
 'wcw_souled_out': 'souled_out',
 'wcw_spring_stampede': 'spring_stampede',
 'wcw_superbrawl_revenge': 'superbrawl',
 'wcw_television_championship': 'wcw_world_television_championship',
 'wcw_television_title': 'wcw_world_television_championship',
 'wcw_tv_championship': 'wcw_world_television_championship',
 'wcw_tv_title': 'wcw_world_television_championship',
 'wcw_us_title': 'wwe_united_states_championship',
 'wcw_world_championship': 'wcw_world_heavyweight_championship',
 'wcw_world_title': 'wcw_world_heavyweight_championship',
 'wcw_world_tour': 'wcw_vs._nwo:_world_tour',
 'wcw_world_wide': 'wcw_worldwide',
 'wcwa_heavyweight_championship': 'wcwa_world_heavyweight_championship'}
        