
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_hv = {'hv-22_osprey': 'v-22_osprey',
 'hv_71': 'hv71',
 'hv_college': 'hope_valley_college',
 'hv_esmond': 'henry_v._esmond',
 'hv_evatt': 'h._v._evatt',
 'hv_kershaw': 'h._v._kershaw',
 'hv_porter': 'h._v._porter',
 'hv_seshadri': 'h._v._seshadri',
 'hvac_system': 'hvac',
 'hvalsey_church': 'hvalsey',
 'hvalstad_if': 'holmen_if',
 'hvar_culture': 'hvar',
 'hvar_diocese': 'roman_catholic_diocese_of_hvar',
 'hvar_island': 'hvar',
 'hvar_kshaeta': 'hvare-khshaeta',
 'hvare_khshaeta': 'hvare-khshaeta',
 'hvarska_buna': 'hvar_rebellion',
 'hvb_bank': 'hypovereinsbank',
 'hvb_banka': 'unicredit_banka',
 'hvb_group': 'hypovereinsbank',
 'hvdc_bass-strait': 'basslink',
 'hvdc_hokkaido-honschu': 'hvdc_hokkaido-honshu',
 'hvdc_italia-corsica-sardinia': 'hvdc_italy-corsica-sardinia',
 'hvdc_lithuania-sweden': 'nordbalt',
 'hvdc_mechanicville-schenectaday': 'hvdc_mechanicville-schenectady',
 'hvdc_norway-germany': 'nord.link',
 'hvdc_vancouver-island': 'hvdc_vancouver_island',
 'hvdc_wolgograd-donbass': 'hvdc_volgograd-donbass',
 'hvedholm_slot': 'hvedholm_castle',
 'hvf_winstone': 'h._v._f._winstone',
 'hvidovre_kommune': 'hvidovre_municipality',
 'hvitfeldtska_gymnasia': 'hvitfeldtska_gymnasiet',
 'hvk_gusar': 'hvk_gusar_split',
 'hvr_iyengar': 'h._v._r._iyengar',
 'hvt_1': 'osama_bin_laden',
 'hvt_2': 'ayman_al-zawahiri',
 'hvx_200': 'panasonic_ag-hvx200',
 'hvz_reaction': 'hell-volhard-zelinsky_halogenation'}
        