#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# AUTO-GENERATED CONTENT
d_stem_jr = {'jra': {'jra': []},
 'jrabl': {'jrable': []},
 'jractic': {'jractical': ['jractically'], 'jractice': ['jractices']},
 'jractical': ['jractically'],
 'jractice': ['jractices'],
 'jractur': {'jracture': []},
 'jrad': {'jrads': []},
 'jrade': {'jrades': []},
 'jradiobutton': {'jradiobuttons': []},
 'jradit': {'jradition': ['jraditional']},
 'jradition': ['jraditional'],
 'jradual': {'jradually': []},
 'jragili': {'jragilis': []},
 'jragment': {'jragments': []},
 'jragran': {'jragrans': []},
 'jrah': {'jrahs': []},
 'jrai': {'jrais': []},
 'jrain': {'jraining': [], 'jrains': []},
 'jrais': {'jraise': ['jraised']},
 'jraise': ['jraised'],
 'jrait': {'jraits': []},
 'jral': {'jrals': []},
 'jralli': {'jrally': []},
 'jralu': {'jralue': []},
 'jram': {'jrams': []},
 'jrame': {'jrames': []},
 'jran': {'jrans': []},
 'jranc': {'jrance': [], 'jrancs': []},
 'jrancai': {'jrancais': []},
 'jrancais': {'jrancaise': ['jrancaises']},
 'jrancaise': ['jrancaises'],
 'jrances': {'jrancese': []},
 'jranch': {'jranches': []},
 'jranci': {'jrancis': []},
 'jrancoi': {'jrancois': []},
 'jrand': {'jrande': []},
 'jranfai': {'jranfais': []},
 'jranfais': {'jranfaise': ['jranfaises']},
 'jranfaise': ['jranfaises'],
 'jrang': {'jrange': []},
 'jrangai': {'jrangais': []},
 'jrangais': {'jrangaise': ['jrangaises']},
 'jrangaise': ['jrangaises'],
 'jranqai': {'jranqais': []},
 'jranqais': {'jranqaise': []},
 'jrant': {'jranted': [], 'jrants': []},
 'jraph': {'jraphs': []},
 'jraphi': {'jraphy': []},
 'jrapidli': {'jrapidly': []},
 'jrapp': {'jrappe': []},
 'jrard': {'jrards': []},
 'jrari': {'jraries': [], 'jrary': []},
 'jrate': {'jrated': [], 'jrateful': [], 'jrates': [], 'jrating': []},
 'jraternit': {'jraternite': []},
 'jration': {'jrations': []},
 'jratitud': {'jratitude': []},
 'jrativ': {'jrative': []},
 'jratr': {'jratres': []},
 'jratri': {'jratris': []},
 'jratribu': {'jratribus': []},
 'jratur': {'jrature': []},
 'jrau': {'jraus': []},
 'jrave': {'jraves': []},
 'jravel': {'jravels': []},
 'jraviti': {'jravity': []},
 'jraw': {'jrawing': [], 'jraws': []},
 'jrb': {'jrbs': []},
 'jrc': {'jrcs': []},
 'jrca': {'jrcas': []},
 'jrce': {'jrces': []},
 'jrd': {'jrds': []},
 'jrder': {'jrders': []},
 'jrdere': {'jrdered': []},
 'jrdinari': {'jrdinary': []},
 'jrdli': {'jrdly': []},
 'jre': {'jres': []},
 'jrea': {'jreas': []},
 'jreach': {'jreached': []},
 'jreadi': {'jready': []},
 'jreadili': {'jreadily': []},
 'jrealiti': {'jreality': []},
 'jrealli': {'jreally': []},
 'jream': {'jreams': []},
 'jrear': {'jrears': []},
 'jreason': {'jreasons': []},
 'jreat': {'jreated': []},
 'jreati': {'jreaty': []},
 'jreatli': {'jreatly': []},
 'jreceiv': {'jreceived': []},
 'jrecherch': {'jrecherches': []},
 'jrecis': {'jrecisely': []},
 'jree': {'jrees': []},
 'jreec': {'jreece': []},
 'jreek': {'jreeks': []},
 'jreeli': {'jreely': []},
 'jreement': {'jreements': []},
 'jreen': {'jreene': []},
 'jrefer': {'jreference': [], 'jreferred': []},
 'jregori': {'jregory': []},
 'jreissati': {'jreissaty': []},
 'jreland': {'jrelande': []},
 'jrelat': {'jrelations': []},
 'jreli': {'jrely': []},
 'jreligi': {'jreligious': []},
 'jremain': {'jremained': []},
 'jrenaeu': {'jrenaeus': []},
 'jrenau': {'jrenaus': []},
 'jrenc': {'jrence': ['jrences']},
 'jrence': ['jrences'],
 'jrend': {'jrends': []},
 'jrendu': {'jrendus': []},
 'jrener': {'jreneral': ['jrenerally']},
 'jreneral': ['jrenerally'],
 'jreniu': {'jrenius': []},
 'jrenseu': {'jrenseus': []},
 'jrenvil': {'jrenville': []},
 'jreopl': {'jreople': []},
 'jreorg': {'jreorge': []},
 'jrepar': {'jrepared': []},
 'jreprodm': {'jreprodmed': []},
 'jrequenc': {'jrequency': []},
 'jrequent': {'jrequently': []},
 'jrer': {'jrers': []},
 'jrere': {'jreres': []},
 'jreri': {'jrery': []},
 'jresenc': {'jresence': []},
 'jresent': {'jresentation': [], 'jresented': []},
 'jreshli': {'jreshly': []},
 'jresid': {'jresident': []},
 'jresolv': {'jresolved': []},
 'jress': {'jressed': []},
 'jressiv': {'jressive': []},
 'jressur': {'jressure': []},
 'jrest': {'jrests': []},
 'jresult': {'jresults': []},
 'jreturn': {'jreturned': []},
 'jreviou': {'jrevious': []},
 'jrevious': {'jreviously': []},
 'jrf': {'jrfs': []},
 'jrface': {'jrfaces': []},
 'jrg': {'jrgs': []},
 'jrgan': {'jrgans': []},
 'jrganiz': {'jrganization': ['jrganizations']},
 'jrganization': ['jrganizations'],
 'jrhi': {'jrhis': []},
 'jri': {'jried': [], 'jries': [], 'jris': [], 'jry': ['jrying']},
 'jribe': {'jribes': []},
 'jribun': {'jribune': []},
 'jrice': {'jrices': []},
 'jricultur': {'jricultural': [], 'jriculture': []},
 'jridg': {'jridge': []},
 'jriec': {'jriece': []},
 'jrienc': {'jrience': []},
 'jriend': {'jriends': []},
 'jriendli': {'jriendly': []},
 'jriest': {'jriests': []},
 'jright': {'jrights': []},
 'jrigin': {'jriginal': ['jriginally']},
 'jriginal': ['jriginally'],
 'jrijol': {'jrijoles': []},
 'jrimari': {'jrimary': []},
 'jrimarili': {'jrimarily': []},
 'jrinari': {'jrinary': []},
 'jrinc': {'jrince': ['jrinces']},
 'jrince': ['jrinces'],
 'jrincip': {'jrincipal': []},
 'jrincipl': {'jrinciple': ['jrinciples']},
 'jrinciple': ['jrinciples'],
 'jring': {'jringing': [], 'jrings': []},
 'jrint': {'jrinted': []},
 'jriou': {'jrious': []},
 'jrirl': {'jrirls': []},
 'jrisdict': {'jrisdiction': []},
 'jrise': {'jrising': []},
 'jrison': {'jrisoners': []},
 'jrite': {'jrites': []},
 'jriti': {'jrities': [], 'jrity': []},
 'jrivat': {'jrivate': []},
 'jrive': {'jrives': [], 'jriving': []},
 'jrk': {'jrks': []},
 'jrker': {'jrkers': []},
 'jrli': {'jrlis': [], 'jrly': []},
 'jrlori': {'jrlory': []},
 'jrm': {'jrms': []},
 'jrmanc': {'jrmance': []},
 'jrme': {'jrmes': []},
 'jrmi': {'jrmy': []},
 'jrn': {'jrns': []},
 'jrnation': {'jrnational': []},
 'jrnl': {'jrnls': []},
 'jrnorri': {'jrnorris': []},
 'jrnuari': {'jrnuary': []},
 'jro': {'jroing': [], 'jros': []},
 'jrobabl': {'jrobable': [], 'jrobably': []},
 'jroblem': {'jroblems': []},
 'jroce': {'jroceed': []},
 'jrocedur': {'jrocedure': ['jrocedures']},
 'jrocedure': ['jrocedures'],
 'jroceed': {'jroceeded': [], 'jroceedings': []},
 'jrocess': {'jrocesses': []},
 'jrod': {'jrods': []},
 'jroduc': {'jroduce': ['jroduced'], 'jroducing': []},
 'jroduce': ['jroduced'],
 'jroduct': {'jroduction': [], 'jroducts': []},
 'jroe': {'jroes': []},
 'jrofession': {'jrofessional': []},
 'jrofit': {'jrofits': []},
 'jrogram': {'jrograms': []},
 'jrogramm': {'jrogramme': []},
 'jroject': {'jrojects': []},
 'jroman': {'jromans': []},
 'jromis': {'jromise': ['jromised']},
 'jromise': ['jromised'],
 'jromptli': {'jromptly': []},
 'jron': {'jrons': []},
 'jrone': {'jroning': []},
 'jroni': {'jrony': []},
 'jront': {'jronte': []},
 'jrood': {'jroods': []},
 'jroop': {'jroops': []},
 'jrootpan': {'jrootpane': []},
 'jrop': {'jrops': []},
 'jroperli': {'jroperly': []},
 'jroperti': {'jroperties': [], 'jroperty': []},
 'jroport': {'jroportion': []},
 'jropos': {'jroposals': [], 'jroposed': []},
 'jropriat': {'jropriate': []},
 'jroquoi': {'jroquois': []},
 'jrosper': {'jrosperity': []},
 'jrotect': {'jrotected': [], 'jrotection': []},
 'jrotiu': {'jrotius': []},
 'jrou': {'jrous': []},
 'jround': {'jrounds': []},
 'jroup': {'jroups': []},
 'jrove': {'jroved': []},
 'jrovern': {'jrovernment': []},
 'jrovid': {'jrovide': ['jrovided', 'jrovides'], 'jroviding': []},
 'jrovide': ['jrovided', 'jrovides'],
 'jrovinc': {'jrovince': ['jrovinces']},
 'jrovince': ['jrovinces'],
 'jrovis': {'jrovision': ['jrovisions']},
 'jrovision': ['jrovisions'],
 'jrow': {'jrowing': [], 'jrows': []},
 'jrp': {'jrps': []},
 'jrpo': {'jrpos': []},
 'jrporat': {'jrporation': []},
 'jrpose': {'jrposes': []},
 'jrr': {'jrrs': []},
 'jrranc': {'jrrance': []},
 'jrrant': {'jrranted': []},
 'jrreatli': {'jrreatly': []},
 'jrrentli': {'jrrently': []},
 'jrressur': {'jrressure': []},
 'jrri': {'jrry': []},
 'jrroup': {'jrroups': []},
 'jrse': {'jr': []},
 'jrselv': {'jrselves': []},
 'jrsiti': {'jrsity': []},
 'jrsocm': {'jrsocmed': []},
 'jrsu': {'jrsus': []},
 'jrt': {'jrts': []},
 'jrtanc': {'jrtance': []},
 'jrti': {'jrty': []},
 'jrtion': {'jrtions': []},
 'jru': {'jrus': []},
 'jrubi': {'jruby': []},
 'jructu': {'jructus': []},
 'jrug': {'jrugs': []},
 'jruge': {'jruges': []},
 'jruid': {'jruide': []},
 'jruilti': {'jruilty': []},
 'jruit': {'jruits': []},
 'jrule': {'jrules': []},
 'jruli': {'jruly': []},
 'jrun': {'jruns': []},
 'jrussel': {'jrussell': []},
 'jrutescen': {'jrutescens': []},
 'jruticosu': {'jruticosus': []},
 'jrve': {'jrves': []},
 'jrvice': {'jrvices': []},
 'jrw': {'jrws': []},
 'jry': ['jrying']}
