
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_nv = {'_': ['nv_krishnaiah',
       'nv_neurons',
       'nv_network',
       'nv-41_mine',
       'nv_puppis',
       'nv_energy',
       'nv_arena',
       'nv_elmar',
       'nv_514',
       'nv_38a',
       'nv_25a',
       'nv_42',
       'nv_80',
       'nv_15',
       'nv_40',
       'nv_3b',
       'nv_51',
       'nv_46',
       'nv_70',
       'nv_60',
       'nv_91',
       'nv_50',
       'nv_85',
       'nv_25',
       'nv_93',
       'nv_6'],
 'c': ['nvc_mg2'],
 'd': ['nvdia_ion'],
 'f': ['nvf_company'],
 'g': ['nvg_t550'],
 'i': ['nvidia_corporation',
       'nvidia_gameworks',
       'nvidia_purevideo',
       'nvidia_geforce2',
       'nvidia_optimus',
       'nvidia_9800gx2',
       'nvidia_goforce',
       'nvidia_9800gtx',
       'nvidia_geforce',
       'nvidia_jetson',
       'nvidia_g-sync',
       'nvidia_quadro',
       'nvidia_tesla',
       'nvidia_nvenc',
       'nvidia_drive',
       'nvidia_tegra',
       'nvidia_share',
       'nvidia_corp.',
       'nvidia_titan',
       'nvidia_nvdec',
       'nvidia_demos',
       'nvidia_physx',
       'nvidia_grid',
       'nvidia_7800',
       'nvidia_780i',
       'nvidia_9800',
       'nvidia_9600',
       'nvidia_gpus',
       'nvidia_br02',
       'nvidia_nv40',
       'nvi_f.k.35',
       'nvidia_gtc',
       'nvidia_n40',
       'nvi_f.k.31',
       'nvidia_ion',
       'nvi_f.k.33',
       'nvi_f.k.29',
       'nvidia_sli',
       'nvidia_rtx',
       'nvi_f.k.32',
       'nvidia_gpu',
       'nvidia_dgx',
       'nvi_f.k.34'],
 'k': ['nvk_sakha'],
 'm': ['nvm_gonzales', 'nvm_gonzalez', 'nvm_express'],
 'r': ['nvram_wakeup', 'nvr,_inc.'],
 's': ['nvss_2146+82']}
