#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# AUTO-GENERATED CONTENT
d_stem_fb = {'fba': {'fbas': []},
 'fbagment': {'fbagments': []},
 'fbahci': {'fbahcis': []},
 'fbakci': {'fbakcis': []},
 'fban': {'fbans': []},
 'fbanc': {'fbance': ['fbances']},
 'fbance': ['fbances'],
 'fbanci': {'fbancis': []},
 'fbanciscu': {'fbanciscus': []},
 'fbanck': {'fbancke': []},
 'fbancoi': {'fbancois': []},
 'fbano': {'fbanoe': []},
 'fbanoi': {'fbanois': []},
 'fbar': {'fbars': []},
 'fbase': {'fbased': []},
 'fbaud': {'fbauds': []},
 'fbb': {'fbbs': []},
 'fbc': {'fbcs': []},
 'fbcieti': {'fbciety': []},
 'fbcu': {'fbcus': []},
 'fbcuss': {'fbcussed': []},
 'fbd': {'fbds': []},
 'fbderalismu': {'fbderalismus': []},
 'fbdor': {'fbdors': []},
 'fbdorschoic': {'fbdorschoice': []},
 'fbe': {'fbeing': [], 'fbes': []},
 'fbecaus': {'fbecause': []},
 'fbedeb': {'fbedebic': []},
 'fbeder': {'fbederic': []},
 'fbefor': {'fbefore': []},
 'fbem': {'fbems': []},
 'fbenez': {'fbenezer': []},
 'fbequenc': {'fbequency': []},
 'fber': {'fbers': []},
 'fbetri': {'fbetry': []},
 'fbf': {'fbfs': []},
 'fbg': {'fbgs': []},
 'fbgc': {'fbgcs': []},
 'fbi': {'fbi': [], 'fby': ['fbys']},
 'fbiedland': {'fbiedlander': []},
 'fbiend': {'fbiends': []},
 'fbiendli': {'fbiendly': []},
 'fbint': {'fbinted': [], 'fbints': []},
 'fbinteb': {'fbintebs': []},
 'fbisea': {'fbiseas': []},
 'fbisn': {'fbisnes': []},
 'fbj': {'fbjs': []},
 'fbk': {'fbks': []},
 'fbl': {'fbls': []},
 'fbld': {'fblds': []},
 'fblde': {'fbldes': []},
 'fbldier': {'fbldiers': []},
 'fblici': {'fblicy': []},
 'fblitic': {'fblitical': [], 'fblitics': []},
 'fblklorist': {'fblklorists': []},
 'fbllett': {'fbllette': []},
 'fblli': {'fblly': []},
 'fbllicit': {'fbllicitous': []},
 'fbllow': {'fbllowed': [], 'fbllowing': [], 'fbllows': []},
 'fbm': {'fbms': []},
 'fbmeth': {'fbmething': []},
 'fbmetim': {'fbmetimes': []},
 'fbn': {'fbns': []},
 'fbo': {'fbos': []},
 'fbod': {'fbods': []},
 'fbodgrain': {'fbodgrains': []},
 'fbodi': {'fbody': []},
 'fboud': {'fboude': []},
 'fbowd': {'fbowde': []},
 'fboy': {'fboys': []},
 'fbp': {'fbps': []},
 'fbpase': {'fbpases': []},
 'fbpulat': {'fbpulation': []},
 'fbr': {'fbrs': []},
 'fbrandr': {'fbrandring': []},
 'fbrbe': {'fbrbes': []},
 'fbrce': {'fbrces': []},
 'fbrdabl': {'fbrdable': []},
 'fbre': {'fbres': []},
 'fbrement': {'fbrementioned': []},
 'fbrenc': {'fbrence': []},
 'fbrene': {'fbrening': []},
 'fbreningen': {'fbreningens': []},
 'fbrget': {'fbrgetfulness': []},
 'fbri': {'fbris': []},
 'fbrm': {'fbrms': []},
 'fbrmalist': {'fbrmalistic': []},
 'fbrmanc': {'fbrmance': []},
 'fbrmerli': {'fbrmerly': []},
 'fbrmiti': {'fbrmity': []},
 'fbrri': {'fbrry': []},
 'fbrsyth': {'fbrsythe': []},
 'fbrt': {'fbrts': []},
 'fbrtabl': {'fbrtable': []},
 'fbrteckn': {'fbrteckning': []},
 'fbrtescu': {'fbrtescue': []},
 'fbrthrightli': {'fbrthrightly': []},
 'fbrti': {'fbrty': []},
 'fbsitiv': {'fbsitive': []},
 'fbssilifer': {'fbssiliferous': []},
 'fbt': {'fbts': []},
 'fbu': {'fbus': []},
 'fbuf': {'fbufs': []},
 'fbuit': {'fbuits': []},
 'fbund': {'fbunded': []},
 'fbundat': {'fbundation': ['fbundational']},
 'fbundation': {'fbundationalism': []},
 'fburc': {'fburce': []},
 'fburpenc': {'fburpence': []},
 'fburseason': {'fburseasons': []},
 'fbw': {'fbws': []},
 'fbwer': {'fbwers': []},
 'fby': ['fbys']}
