
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_mh = {'_': ['mh-60g',
       'mh-53e',
       'mh-60r',
       'mh-53j',
       'mh-60j',
       'mh-47',
       'mh-53',
       'mh-90',
       'mh-1a',
       'mh-60',
       'mh-68',
       'mh90',
       'mh-6',
       'mh4'],
 'a': ['mhainamtsi',
       'mharashtra',
       'mhaimbhat',
       'mhasawad',
       'mhalmoye',
       'mhadalem',
       'mhasurne',
       'mhaireth',
       'mhallami',
       'mhaismal',
       'mhaskoba',
       'mhaydseh',
       'mhachkay',
       'mhangura',
       'mharraq',
       'mhadjeb',
       'mhaisur',
       'mhaikam',
       'mhalasa',
       'mhardeh',
       'mhaswad',
       'mhaskar',
       'mhasane',
       'mhakave',
       'mhasoba',
       'mhapan',
       'mhande',
       'mhacks',
       'mhalsa',
       'mhango',
       'mhasla',
       'mhasad',
       'mhairi',
       'mhash',
       'mhada',
       'mhall',
       'mhac',
       'mhal',
       'mhai',
       'mha'],
 'b': ['mhbc', 'mhb'],
 'c': ['mhcima', 'mhc-ii', 'mhchs', 'mhc2', 'mhcc', 'mhc'],
 'd': ['mhdbdb', 'mhdys', 'mhd'],
 'e': ['mhendhan',
       'mheger-4',
       'mheibes',
       'mhetase',
       'mhealth',
       'mheg-5',
       'mheer',
       'mhemt',
       'mhere',
       'mheda',
       'mheg5',
       'mhezi',
       'mheac',
       'mher',
       'mheg',
       'mhec',
       'mhe'],
 'f': ['mhfm', 'mhfu', 'mhf2'],
 'g': ['mhgs', 'mhg'],
 'h': ['mhhs', 'mhh'],
 'i': ['mhing', 'mhic', 'mhi'],
 'k': ['mhk'],
 'l': ['mhlambanyatsi',
       'mhlangatane',
       'mhlosheni',
       'mhlangana',
       'mhlangeni',
       'mhlumeni',
       'mhlongo',
       'mhlume',
       'mhluzi',
       'mhl'],
 'm': ['mhms', 'mhmm', 'mhmr', 'mhm'],
 'n': ['mhn-uabcs', 'mhnp', 'mhn'],
 'o': ['mhowgaon', 'mhorkya', 'mhow', 'mho'],
 'p': ['mhpcc', 'mhpra', 'mhpa', 'mhps', 'mhp'],
 'q': ['mhq'],
 'r': ['mhrir', 'mhrr', 'mhrt', 'mhra', 'mhr'],
 's': ['mhsnet', 'mhsdg', 'mhsaa', 'mhsi', 'mhsc', 'mhsa', 'mhsf', 'mhs'],
 't': ['mhtrtc', 'mhtml', 'mht'],
 'u': ['mhuire', 'mhudi', 'mhul', 'mhu'],
 'v': ['mhv'],
 'w': ['mhw-rtg', 'mhws'],
 'x': ['mhx'],
 'y': ['mhysa'],
 'z': ['mhz']}
