import libcst
from viktor._codemod.helpers import collect_class_attributes as collect_class_attributes, match_controller_class as match_controller_class

class Visitor(libcst.CSTVisitor): ...

class Transformer(libcst.CSTTransformer):
    def __init__(self, visitor) -> None: ...
    def leave_ClassDef(self, original_node, updated_node): ...
