#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# AUTO-GENERATED CONTENT
d_stem_bk = {'bka': {'bkas': []},
             'bkaili': {'bkaily': []},
             'bkamwel': {'bkamwell': []},
             'bkatti': {'bkattie': [], 'bkatty': []},
             'bkccle': {'bkccles': []},
             'bkcclk': {'bkcclks': []},
             'bkci': {'bkcy': []},
             'bkd': {'bkds': []},
             'bkde': {'bkdes': []},
             'bke': {'bkes': []},
             'bkeli': {'bkely': []},
             'bkerk': {'bkerke': []},
             'bkesu': {'bkesus': []},
             'bketch': {'bketches': []},
             'bkewis': {'bkewise': []},
             'bki': {'bkies': [], 'bky': []},
             'bkidg': {'bkidge': ['bkidges']},
             'bkidge': ['bkidges'],
             'bkigg': {'bkiggs': []},
             'bkil': {'bkilful': ['bkilfully']},
             'bkilful': ['bkilfully'],
             'bkill': {'bkilled': [], 'bkillful': []},
             'bkin': {'bkins': []},
             'bkirbi': {'bkirby': []},
             'bkirt': {'bkirts': []},
             'bkk': {'bkks': []},
             'bko': {'bkos': []},
             'bkodi': {'bkodie': []},
             'bkologisch': {'bkologische': ['bkologischer']},
             'bkologische': ['bkologischer'],
             'bkonomi': {'bkonomie': []},
             'bkonomisch': {'bkonomische': ['bkonomischer']},
             'bkonomische': ['bkonomischer'],
             'bkont': {'bkonte': []},
             'bkonz': {'bkonze': []},
             'bkook': {'bkooke': [], 'bkooks': []},
             'bkothek': {'bkotheks': []},
             'bkother': {'bkothers': []},
             'bkown': {'bkowne': []},
             'bkrri': {'bkrry': []},
             'bkrtci': {'bkrtcy': []},
             'bksh': {'bkshs': []},
             'bkssing': {'bkssings': []},
             'bkst': {'bksts': []},
             'bkt': {'bkts': []},
             'bktci': {'bktcy': []},
             'bkull': {'bkulls': []},
             'bkumenisch': {'bkumenischer': []}}
