# coding: utf-8

"""
    ARLAS Subscriptions Manager API

    Manage ARLAS subscriptions on ARLAS collections' events.  # noqa: E501

    OpenAPI spec version: 23.0.1
    Contact: contact@gisaia.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import arlas_subscriptions_manager_api_python
from arlas_subscriptions_manager_api_python.api.admin_api import AdminApi  # noqa: E501
from arlas_subscriptions_manager_api_python.rest import ApiException


class TestAdminApi(unittest.TestCase):
    """AdminApi unit test stubs"""

    def setUp(self):
        self.api = arlas_subscriptions_manager_api_python.api.admin_api.AdminApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete(self):
        """Test case for delete

        Delete a subscription  # noqa: E501
        """
        pass

    def test_get(self):
        """Test case for get

        Find subscription by ID  # noqa: E501
        """
        pass

    def test_get_all(self):
        """Test case for get_all

        List all available subscriptions  # noqa: E501
        """
        pass

    def test_post(self):
        """Test case for post

        Register a new subscription  # noqa: E501
        """
        pass

    def test_put(self):
        """Test case for put

        Update an existing subscription  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
