
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_lg = {'lg-fiat': 'lg_tractors',
 'lg.philips': 'lg_display',
 'lg15': 'lonelygirl15',
 'lg15.com': 'lonelygirl15',
 'lg3d': 'project_looking_glass',
 'lg55': 'triodos_airport',
 'lg73': 'cklg-fm',
 'lga-1207': 'socket_f',
 'lga-775': 'lga_775',
 'lga1207': 'socket_f',
 'lga1366': 'lga_1366',
 'lga755': 'lga_775',
 'lga771': 'socket_j',
 'lga775': 'lga_775',
 'lgat': 'large_group_awareness_training',
 'lgav': 'athens_international_airport',
 'lgba': 'lesbian_and_gay_band_association',
 'lgbt-friendly': 'gay_friendly',
 'lgbt...': 'lgbt',
 'lgbta': 'lgbt',
 'lgbti': 'lgbt',
 'lgbtiq': 'lgbt',
 'lgbtq': 'lgbt',
 'lgbtqi': 'lgbt',
 'lgbtqq': 'lgbt',
 'lgbtqqi': 'lgbt',
 'lgbtt': 'lgbt',
 'lgbttq': 'lgbt',
 'lgbttqq': 'lgbt',
 'lgbu': 'lgbt',
 'lgcr': 'langer-giedion_syndrome',
 'lgdt': 'grand_dictionnaire_terminologique',
 'lgelectronics': 'lg_electronics',
 'lgen': 'lieutenant_general',
 'lgfc': 'leverstock_green_f.c.',
 'lghs': 'los_gatos_high_school',
 'lgib': 'lower_gastrointestinal_bleeding',
 'lgiu': 'local_government_information_unit',
 'lgkl': 'kalamata_international_airport',
 'lgky': 'kalymnos_island_national_airport',
 'lgm-118': 'lgm-118_peacekeeper',
 'lgm-118a': 'lgm-118_peacekeeper',
 'lgm-30g': 'lgm-30_minuteman',
 'lgm118': 'lgm-118_peacekeeper',
 'lgmb': 'lady_godiva_memorial_bnad',
 'lgmd': 'limb-girdle_muscular_dystrophy',
 'lgmt': 'mytilene_international_airport',
 'lgoc': 'london_general_omnibus_company',
 'lgop': 'leather_goddesses_of_phobos',
 'lgpl': 'gnu_lesser_general_public_license',
 'lgr1': 'fsh-receptor',
 'lgr2': 'luteinizing_hormone/choriogonadotropin_receptor',
 'lgr3': 'thyrotropin_receptor',
 'lgs3': 'pisces_dwarf',
 'lgsil': 'bethesda_system',
 'lgsm': 'samos_international_airport',
 'lgtb': 'lgbt',
 'lgv-se': 'lgv_sud-est'}
        