
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_bp = {'_': ['bp-amoco', 'bp-897', 'bp-20', 'bp-ii', 'bp20', 'bp21', 'bp2', 'bp3'],
 'a': ['bpamoco',
       'bpaafc',
       'bpaww',
       'bpatg',
       'bpam',
       'bpap',
       'bpad',
       'bpay',
       'bpal',
       'bpas',
       'bpan',
       'bpai',
       'bpa'],
 'b': ['bpbm', 'bpb'],
 'c': ['bpcs-steganography', 'bpc-157', 'bpcpr', 'bpcs', 'bpcp', 'bpcl', 'bpc'],
 'd': ['bpdfamily.com', 'bpdm', 'bpds', 'bpda', 'bpd'],
 'e': ['bpel4people',
       'bpel4ws',
       'bpesin',
       'bpeace',
       'bpex',
       'bpel',
       'bpea',
       'bpeo',
       'bpe'],
 'f': ['bpfna', 'bpfl', 'bpfc', 'bpf'],
 'g': ['bpghs', 'bpg'],
 'h': ['bpharma', 'bpharm', 'bphil', 'bphs', 'bphc', 'bph'],
 'i': ['bpifrance',
       'bpifb4',
       'bpifb1',
       'bpifa3',
       'bpitch',
       'bpihs',
       'bpit',
       'bpi'],
 'k': ['bpk'],
 'l': ['bplats', 'bplrt', 'bplan', 'bplr', 'bpl'],
 'm': ['bpm-97',
       'bpmr1b',
       'bpm:tv',
       'bpm-1',
       'bpmtv',
       'bpmd',
       'bpms',
       'bpmn',
       'bpml',
       'bpmc',
       'bpm'],
 'n': ['bpnichol', 'bpna', 'bpn'],
 'o': ['bpoplive', 'bpost', 'bpot', 'bpoe', 'bpon', 'bpoa', 'bpo'],
 'p': ['bppve', 'bppda', 'bppa', 'bppn', 'bppv', 'bppi', 'bpp'],
 'r': ['bprc', 'bprd', 'bpra', 'bprr', 'bpr'],
 's': ['bpst-instanton',
       'bpsk31',
       'bpsss',
       'bps-2',
       'bpsn',
       'bpsa',
       'bpsu',
       'bpst',
       'bpsd',
       'bps'],
 't': ['bptf', 'bptt', 'bpti', 'bptv', 'bpt'],
 'u': ['bpupki', 'bpuji', 'bpu'],
 'v': ['bpv-1', 'bpv-6', 'bpv-3', 'bpv-4', 'bpv-5', 'bpv-2', 'bpv'],
 'w': ['bpwfc', 'bpw'],
 'x': ['bpx'],
 'y': ['bpy2', 'bpy']}
