
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ii = {'_': ['ii-vi_semiconductor_compound',
       'ii_interceptor_command',
       'ii._gimnazija,_maribor',
       'ii_hammerstein_oscar',
       'ii_divisao_nacional',
       'ii_gymnasium_osijek',
       'ii_gymnasium_split',
       'ii_chundrigar_road',
       'ii_vatican_council',
       'ii_battle_squadron',
       'ii_district,_turku',
       'ii_gallorum_dacica',
       'ii_ss_panzerkorps',
       'ii_antigen_system',
       'ii_bomber_command',
       'ii_canadian_corps',
       'ii_tone_committee',
       'ii_raetorum_c.r.',
       'ii_cavalry_corps',
       'ii_alpinorum_eq',
       'ii_anzac_corps',
       'ii_liga_zapad',
       'ii_liga_rugby',
       'ii_d_extreme',
       'ii_world_war',
       'ii_mix_delta',
       'ii_zwicky_28',
       'ii_&_iii',
       'ii_zw_96'],
 'd': ['iidva_nature_reserve', 'iida_kofun_group'],
 'e': ['iie_iron_meteorite'],
 'f': ['iifa_best_cinematography',
       'iifa_best_choreography',
       'iifa_best_screenplay',
       'iifa_glamorous_actor',
       'iifa_best_editing',
       'iifa_best_action',
       'iifa_best_makeup',
       'iifa_star_debut'],
 'h': ['iihf_european_championships',
       'iihf_european_championship',
       'iihf_junior_championships',
       'iihf_world_championships',
       'iihf_world_championship',
       'iihf_continental_cup',
       'iihf_all-time_teams',
       'iihf_world_ranking',
       'iihf_european_cup',
       'iihf_super_cup'],
 'i': ['iii_reconnaissance_command',
       'iii_interceptor_command',
       'iii_gymnasium_osijek',
       'iii_amphibious_corps',
       'iii_battle_squadron',
       'iii_smoking_barrels',
       'iii_district,_turku',
       'iii_fighter_command',
       'iii_bomber_command',
       'iii_delmatarum_eq',
       'iii_steps_forward',
       'iii._keruleti_tve',
       'iii_cavalry_corps',
       'iii_alpinorum_eq',
       'iii_strikes_law',
       'iiird_tyme_out',
       'iii_-_tri-logy',
       'iii_the_ep',
       'iii_zw_2'],
 'j': ['iijima_bishop_pullback'],
 'n': ['iinozaka_kofun_cluster', 'iinan_district,_mie'],
 'p': ['iipumbu_ya_tshilongo'],
 's': ['iisalmi_railway_station',
       'iishi_district,_shimane',
       'iisco_steel_plant',
       'iiso_flash_shoe',
       'iiss_ship_files',
       'iisa_pa_lamang'],
 't': ['iitb-monash_research_academy',
       'iitran_programming_language',
       'iittala_railway_station',
       'iit_physics_department',
       'iit_research_institute',
       'iit_bombay_racing'],
 'z': ['iizuka_daiichi_gymnasium',
       'iizasa_choisai_ienao',
       'iizaka_onsen_station']}
