
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_fc = {'_': ['fc-receptor',
       'fc-domain',
       'fc-group',
       'fc-11b3',
       'fc-22b1',
       'fc-p2p',
       'fc-fla',
       'fc-pga',
       'fc-125',
       'fc-143',
       'fc-75',
       'fc-sb',
       'fc-sw',
       'fc-al',
       'fc-gs',
       'fc-72',
       'fc-77',
       'fc-ph',
       'fc-mi',
       'fc77',
       'fc.o',
       'fc-1',
       'fc2',
       'fc4',
       'fc3',
       'fc6'],
 'a': ['fcak-liberia',
       'fca/mr',
       'fcaps',
       'fcaca',
       'fcaf',
       'fcat',
       'fcaw',
       'fcar',
       'fcab',
       'fcas',
       'fcac',
       'fcal',
       'fca'],
 'b': ['fcbarcelona', 'fcbb', 'fcbk', 'fcb2', 'fcbs', 'fcbd', 'fcba', 'fcb'],
 'c': ['fccdc', 'fcchs', 'fccf', 'fccj', 'fccp', 'fccc', 'fcch', 'fcca', 'fcc'],
 'd': ['fcds', 'fcda', 'fcd'],
 'e': ['fcer1a',
       'fcerii',
       'fcer1g',
       'fceux',
       'fcer2',
       'fceeg',
       'fcer1',
       'fceu',
       'fcem',
       'fce'],
 'f': ['fcfc', 'fcfa', 'fcf1', 'fcf'],
 'g': ['fcgr3b',
       'fcgr3a',
       'fcgr1a',
       'fcgr2a',
       'fcgr2b',
       'fcgbp',
       'fcgb',
       'fcgi',
       'fcgs',
       'fcg'],
 'h': ['fchv-3',
       'fchsd2',
       'fchsd1',
       'fcho1',
       'fcho2',
       'fchan',
       'fcht',
       'fchs',
       'fch'],
 'i': ['fciemas',
       'fciarb',
       'fcitx',
       'fciac',
       'fcic',
       'fcim',
       'fcib',
       'fcii',
       'fcip',
       'fci'],
 'j': ['fcj'],
 'k': ['fckeditor', 'fckh8', 'fck'],
 'l': ['fcl-web', 'fclose', 'fclo2', 'fclv', 'fclt', 'fcl'],
 'm': ['fcmov', 'fcmc', 'fcmm', 'fcmi', 'fcms', 'fcmr', 'fcmb', 'fcmd', 'fcm'],
 'n': ['fcnar', 'fcn2', 'fcnm', 'fcnl', 'fcn3', 'fcn1', 'fcn'],
 'o': ['fcommunications',
       'fco.gov.uk',
       'fco-im',
       'fcollt',
       'fcode',
       'fcoim',
       'fcom',
       'fcoe',
       'fcot',
       'fcoj',
       'fco'],
 'p': ['fcps.k12.va.us',
       'fcpremix',
       'fcps.edu',
       'fcporto',
       'fcpga6',
       'fcpga',
       'fcpnm',
       'fcpa',
       'fcps',
       'fcp'],
 'r': ['fcrdns',
       'fcron',
       'fcrl1',
       'fcrl2',
       'fcrps',
       'fcrla',
       'fcrl4',
       'fcrl3',
       'fcrl5',
       'fcrao',
       'fcrce',
       'fcrit',
       'fcrn',
       'fcrd',
       'fcrl',
       'fcrc',
       'fcra',
       'fcr'],
 's': ['fcs-32',
       'fcs-1',
       'fcs-2',
       'fcs-3',
       'fcsm',
       'fcs2',
       'fcsb',
       'fcsd',
       'fcsp',
       'fcss',
       'fcsu',
       'fcsc',
       'fcsl',
       'fcs'],
 't': ['fctc', 'fct'],
 'u': ['fcurve', 'fcuom', 'fcum', 'fcu'],
 'v': ['fcvpi', 'fcvt', 'fcv'],
 'x': ['fcx'],
 'z': ['fcz']}
