
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_fn = {'_': ['fn-rifle',
       'fn-2000',
       'fn3krp',
       'fn-p90',
       'fn-cal',
       'fn2000',
       'fn-fal',
       'fn303',
       'fn-49',
       'fn10',
       'fn49',
       'fn-6',
       'fn1'],
 'a': ['fnatasy',
       'fna2o3p',
       'fnab-43',
       'fnatic',
       'fnassl',
       'fnaeg',
       'fnac',
       'fnal',
       'fnar',
       'fnab',
       'fna'],
 'b': ['fnbp1l', 'fnbdt', 'fnbox', 'fnbp1', 'fnbp4', 'fnbo', 'fnbm', 'fnb'],
 'c': ['fncv', 'fnci', 'fncm', 'fnc'],
 'd': ['fndc3a', 'fndc5', 'fnd'],
 'e': ['fneitiq', 'fneidik', 'fnet', 'fne'],
 'f': ['fnfal', 'fnfis', 'fnfl', 'fnf'],
 'g': ['fngs', 'fnge', 'fng'],
 'h': ['fnhs', 'fnh'],
 'i': ['fnideq', 'fnidek', 'fnip1', 'fnidk', 'fnir', 'fnis', 'fni'],
 'j': ['fnjoskadalur', 'fnj'],
 'k': ['fnk'],
 'l': ['fnlu', 'fnla', 'fnlc', 'fnl'],
 'm': ['fnmtv', 'fnmoc', 'fnme', 'fnma', 'fnm'],
 'n': ['fnnch', 'fnn'],
 'o': ['fnord', 'fnoc', 'fno'],
 'p': ['fnp90', 'fnpr', 'fnpt', 'fnps', 'fnpp', 'fnp'],
 'q': ['fnq-10', 'fnq10', 'fnq'],
 'r': ['fnrs-2',
       'fnrs-1',
       'fnrs-3',
       'fnrs2',
       'fnrs3',
       'fnrs1',
       'fnrj',
       'fnra',
       'fnrs',
       'fnr'],
 's': ['fnsp', 'fnsd', 'fnst', 'fns'],
 't': ['fnta', 'fntb', 'fntr', 'fnti', 'fnt'],
 'u': ['fnuc', 'fnuf', 'fnu'],
 'v': ['fnv'],
 'w': ['fnw'],
 'x': ['fnxa', 'fnx'],
 'y': ['fny'],
 'z': ['fnz']}
