
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rn = {'_': ['rn01-ss',
       'rn-9893',
       'rn5s1@',
       'rn-94',
       'rn-21',
       'rn624',
       'rn56',
       'rn1'],
 'a': ['rna-polymerase',
       'rnaseh2a',
       'rnaseh2b',
       'rnaseh2c',
       'rna-out',
       'rna28s1',
       'rnaset2',
       'rna-seq',
       'rnaseh1',
       'rnase3',
       'rnase1',
       'rnaase',
       'rnapol',
       'rnase4',
       'rnase5',
       'rnaiii',
       'rnase2',
       'rnase6',
       'rna22',
       'rnase',
       'rnal',
       'rnaa',
       'rnag',
       'rnai',
       'rnas',
       'rnaf',
       'rnap',
       'rnav',
       'rnad',
       'rna'],
 'b': ['rnbass', 'rnbdj', 'rnbr', 'rnb'],
 'c': ['rnchamps', 'rnco', 'rncp', 'rncm', 'rncb', 'rnc8', 'rnc'],
 'd': ['rnd07',
       'rndr.',
       'rndis',
       'rndp',
       'rnd3',
       'rnd2',
       'rndc',
       'rndf',
       'rndm',
       'rnd1',
       'rndu',
       'rnd'],
 'e': ['rnescape', 'rnews', 'rnec', 'rnep', 'rne'],
 'f': ['rnf144a',
       'rnf113a',
       'rnf122',
       'rnf128',
       'rnf139',
       'rnf111',
       'rnf213',
       'rnf220',
       'rnf125',
       'rnf114',
       'rnf5p1',
       'rnf123',
       'rnf216',
       'rnf146',
       'rnf135',
       'rnf183',
       'rnf19a',
       'rnf55',
       'rnf31',
       'rnf14',
       'rnf32',
       'rnf43',
       'rnf71',
       'rnf26',
       'rnf24',
       'rnf20',
       'rnf11',
       'rnf10',
       'rnf25',
       'rnf13',
       'rnf41',
       'rnf34',
       'rnf40',
       'rnf38',
       'rnf12',
       'rnf39',
       'rnf8',
       'rnfl',
       'rnf2',
       'rnf7',
       'rnf4',
       'rnf5',
       'rnf'],
 'g': ['rngtt', 'rngc', 'rng'],
 'h': ['rnh1', 'rnh'],
 'i': ['rnid', 'rnie', 'rnib', 'rnin', 'rnii', 'rni'],
 'j': ['rnj'],
 'k': ['rnk'],
 'l': ['rnlaf', 'rnli', 'rnld'],
 'm': ['rnmtl1', 'rnmws', 'rnm'],
 'n': ['rnn'],
 'o': ['rnoaf', 'rno'],
 'p': ['rnps1', 'rnpep', 'rnpv', 'rnps', 'rnp'],
 'r': ['rnrhof', 'rnrmc', 'rnr2', 'rnr5', 'rnr4', 'rnr1', 'rnr3', 'rnr'],
 's': ['rnsit', 'rnsts', 'rnsap', 'rnsa', 'rnsp', 'rnst', 'rnsh', 'rns'],
 't': ['rnthps', 'rntda', 'rntcp', 'rnt1p', 'rntp', 'rnt1', 'rntd', 'rnt'],
 'u': ['rnu4atac', 'rnu2-2', 'rnu12', 'rnu2', 'rnu'],
 'v': ['rnvsr', 'rnvr', 'rnv'],
 'w': ['rnwmp', 'rnwk', 'rnw'],
 'x': ['rnxs'],
 'y': ['rnying-ma-pa', 'rny'],
 'z': ['rnzspca',
       'rnznvr',
       'rnzeme',
       'rnzys',
       'rnzpc',
       'rnzir',
       'rnzih',
       'rnzfb',
       'rnzaf',
       'rnzi',
       'rnzn',
       'rnz']}
