
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ej = {'_': ['ej-200',
       'ej15b',
       'ej257',
       'ej22t',
       'ej200',
       'ej11',
       'ej16',
       'ej22',
       'ej15',
       'ej13',
       'ej20',
       'ej14',
       'ej12',
       'ej30'],
 'a': ['ejaculations',
       'ejaculating',
       'ejaculation',
       'ejaculated',
       'ejaculates',
       'ejambment',
       'ejaculate',
       'ejabberd',
       'ejamaan',
       'ejagham',
       'ejari',
       'ejaji',
       'ejaz',
       'ejan',
       'ejay',
       'eja'],
 'b': ['ejbca', 'ejbeh', 'ejby', 'ejb'],
 'c': ['ejcf', 'ejc'],
 'd': ['ejdabrine', 'ejdus'],
 'e': ['ejerkulation',
       'ejectorseat',
       'ejectisomes',
       'ejectosomes',
       'ejemekwuru',
       'ejectosome',
       'ejectives',
       'ejectment',
       'ejection',
       'ejecting',
       'ejective',
       'ejercito',
       'ejector',
       'ejected',
       'ejerie',
       'ejecta',
       'eject',
       'ejeme',
       'ejeda',
       'ejer',
       'ejea',
       'ejep',
       'eje'],
 'f': ['ejf'],
 'h': ['ejhl', 'ejhg', 'ejh'],
 'i': ['ejiri-juku',
       'ejidatorio',
       'ejinaspis',
       'ejinhoro',
       'ejipura',
       'ejiofor',
       'ejigbo',
       'ejiogu',
       'ejima',
       'ejisu',
       'ejipt',
       'ejigu',
       'ejido',
       'ejiao',
       'ejiri',
       'ejin',
       'eji'],
 'j': ['ejjp', 'ejji'],
 'k': ['ejk'],
 'l': ['ejlstrup', 'ejlinge', 'ejler', 'ejl'],
 'm': ['ejmt'],
 'n': ['ejnstejno', 'ejnyc', 'ejner', 'ejnar', 'ejn'],
 'o': ['ejogo', 'ejot', 'ejo'],
 'p': ['ejpovice', 'ejp'],
 's': ['ejszeryszki', 'ejstrup', 'ejs'],
 't': ['ejtc', 'ejt'],
 'u': ['ejustine', 'ejutla', 'ejulve', 'ejura', 'ejupi', 'ejule', 'eju'],
 'v': ['ejv'],
 'w': ['ejw']}
