
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_kp = {'_': ['kp:_nimzovich_defense',
       'kp:_the_autobiography',
       'kp_starogard_gdanski',
       'kp_chemik_police',
       'kp_unia_raciborz',
       'kp_kesava_menon',
       'kp_legia_warsaw',
       'kp_sharma_oli',
       'kp_vz._38'],
 'a': ['kpando_municipal_district',
       'kpalime_traditional_area',
       'kpanga_kabonde_chiefdom',
       'kpanga_krim_chiefdom',
       'kpama_baramoto_kata'],
 'b': ['kpbs_public_media'],
 'c': ['kpc_media_group'],
 'e': ['kpelle_national_forest', 'kpehi_didier_brossou', 'kpeve_new_town'],
 'f': ['kpfk_90.7_fm'],
 'g': ['kpga_tour_championship'],
 'i': ['kpi-driven_code_analysis',
       'kpit_mslta_challenger',
       'kpini_kyiu_festival',
       'kpix_dance_party',
       'kpist_mod_45'],
 'm': ['kpmg_corporate_finance',
       'kpmg_consulting_inc',
       'kpmg_peat_marwick',
       'kpmg_v_securefin',
       'kpmg_united_fc'],
 'o': ['kpop_selection_album', 'kpo_the_leopard'],
 'r': ['kpr_wolsztyniak_wolsztyn', 'kpr_ruch_chorzow'],
 's': ['kps_capital_partners',
       'kps_chemik_police',
       'kps_video_express',
       'kpsk_stal_mielec'],
 't': ['kpt_officers_society'],
 'v': ['kpvt_machine_gun', 'kpv_machine_gun', 'kpvr_and_khzr']}
