
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_km = {'_': ['km_communications_inc.',
       'km_ostrow_wielkopolski',
       'km_music_conservatory',
       'km_mammen_mappillai',
       'km_kader_mohideen',
       'km_radha_krishnan',
       'km_obaidur_rahman',
       'km_media_group',
       'km_nurul_huda',
       'km_plus_media'],
 'a': ['kmart_holdings_corporation',
       'kmart_holding_corporation',
       'kmart_australia_limited',
       'kmart_australia_ltd.',
       'kmart/dura_lube_400',
       'kmart_super_center',
       'kmart_new_zealand'],
 'b': ['kmb_football_team',
       'kmb_jazz_records',
       'kmb_route_917',
       'kmb_route_91m',
       'kmb_route_1a',
       'kmb_route_51',
       'kmb_route_70',
       'kmb_route_1'],
 'c': ['kmc_international_center',
       'kmc_hospital,_mangalore',
       'kmc_football_stadium',
       'kmc_chain_industrial'],
 'f': ['kmf_bajo_pivljanin', 'kmfdm_vs._skold', 'kmfm_west_kent'],
 'g': ['kmgw_96.7_fm'],
 'i': ['kmi_30_index'],
 'l': ['kmle_country_108'],
 'n': ['kmn_oplast_kobarid'],
 'o': ['kmos_tv_tower', 'kmov_tv_tower', 'kmox_am_1120', 'kmox_1120_am'],
 'r': ['kmr_racing_team'],
 's': ['kms_graf_zeppelin', 'kmsp_tv_tower'],
 't': ['kmt-cpc_united_fronts', 'kmt_party_flag', 'kmt_5_m'],
 'v': ['kmvu-tv_fox_26'],
 'w': ['kmw+nexter_defense_systems']}
