
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_eh = {'_': ['eh200_electric_locomotive',
       'eh_industries_eh101',
       'eh_harriman_award',
       'eh_postcode_area',
       'eh-60_quick_fix',
       'eh_postal_area',
       'eh,_kasi_bata',
       'eh,_la_bas',
       'eh_fi_amal'],
 'a': ['ehattesaht_first_nation',
       'ehab_moustafa_mansour',
       'ehab_al_shihabi',
       'ehab_el_masry'],
 'c': ['ehc_st._moritz', 'ehc_team_wien'],
 'd': ['ehd_protein_family'],
 'e': ['eheliyagoda_divisional_secretariat',
       'ehetuwewa_divisional_secretariat',
       'eheliyagoda_electoral_district',
       'eheliyagoda_polling_division',
       'ehen_vor_gericht'],
 'f': ['ehf_coefficient_rank',
       'ehf_champions_league',
       'ehf_challenge_trophy',
       'ehf_european_league',
       "ehf_nations'_cup",
       'ehf_european_cup',
       'ehf_euro_2020'],
 'i': ['ehingen,_middle_franconia',
       'ehime_at-large_district',
       'ehime_asahi_television',
       'ehime_mandarin_pirates',
       "ehime_women's_college",
       'ehigie_edobor_uzamere',
       'ehime_orange_vikings',
       'ehie_ogerenye_edison',
       'ehime_maru_incident',
       'ehime_fc_ladies',
       'ehingen_am_ries',
       'ehime_f._c.',
       'ehime_f_c'],
 'j': ['ehjeh_ascher_ehjeh'],
 'l': ['ehlanzeni_district_municipality',
       'ehlers_danlos_syndrome',
       'ehlers_round_barn',
       'ehle_house_site'],
 'o': ['ehon_hyaku_monogatari',
       'ehove_career_center',
       'eho_hamara_jeevna',
       'eho_mia_angalia'],
 'p': ['ehp_spectral_sequence'],
 'r': ["ehrenpreis's_fundamental_principle",
       'ehrc-ohchr_tigray_investigation',
       'ehrlichiosis_ewingii_infection',
       'ehrlichia_wisconsin_hm543746',
       "ehrhart's_volume_conjecture",
       'ehrgeiz_original_soundtrack',
       'ehrlich_park,_bloemfontein',
       'ehrenfried_von_tschirnhaus',
       'ehrmann_commonwealth_dairy',
       'ehrlich_ascites_carcinoma',
       'ehrenfest_diffusion_model',
       'ehrenpokal_der_luftwaffe',
       'ehrhardt,_south_carolina',
       'ehrick_kensett_rossiter',
       'ehrenburg,_lower_saxony',
       'ehrgott_bernhard_bendl',
       'ehrenfried_von_willich',
       'ehrenblatt_des_heeres',
       'ehrenfest_urn_model',
       'ehre_vater_artist',
       'ehrman_syme_nadal',
       'ehret_high_school',
       'ehrich_&_graetz',
       'ehron_von_allen',
       'ehr_top_40'],
 's': ['ehsanabad,_north_khorasan',
       'ehsan_khan_nakhichevansky',
       'ehsan_ghazizadeh_hashemi',
       'ehsanollah_khan_dustdar',
       'ehsaan_mosque,_mannheim',
       'ehsanul_islam_sadequee',
       'ehsan_mohajer_shojaei',
       'ehsan_ghaem_maghami',
       'ehsaas:_the_feeling',
       'ehsan_riaz_fatyana',
       'ehsan_elahi_zaheer',
       'ehsan_khajeh_amiri',
       'ehsan_k._matoori',
       'ehsan_ullah_khan',
       'ehsaas_is_tarah',
       'ehsan_ali_khan',
       'ehsan_h._feroz',
       'ehsan_ul_haq'],
 't': ['ehtesham_ali_khan', 'ehtsham_ul_haq'],
 'u': ['ehud_r._toledano', 'ehud_ben_tuvim', 'ehud_de_shalit', 'ehud_ben_gera'],
 'y': ['ehyeh_asher_ehyeh']}
