
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_lb = {'lb-30': 'b-24_liberator',
 'lb-426': 'lv-426',
 'lb-5': 'keystone_lb-5',
 'lb-6': 'keystone_lb-6',
 'lb07': 'if_limhamn_bunkeflo',
 'lb23': 'lebron_james',
 'lba-compete': 'linear_bounded_automaton',
 'lba1': 'little_big_adventure',
 'lba2': 'little_big_adventure_2',
 'lba48': 'logical_block_addressing',
 'lbac': 'lattice-based_access_control',
 'lbam': 'light_brown_apple_moth',
 'lbaop': 'aquarium_of_the_pacific',
 'lbar': 'tropical_cyclone_forecast_model',
 'lbas': 'free_trade_union_confederation_of_latvia',
 'lbbb': 'left_bundle_branch_block',
 'lbbg': 'burgas_airport',
 'lbc.co.uk': 'lbc',
 'lbci': 'lebanese_broadcasting_corporation',
 'lbd-1': 'lbd-1_gargoyle',
 'lbda': 'long_beach_dub_allstars',
 'lbdas': 'long_beach_dub_allstars',
 'lbdi': 'liberian_bank_for_development_and_investment',
 'lberusaiyunobara': 'the_rose_of_versailles',
 'lbf-ft': 'foot-pound_force',
 'lbf/in2': 'pounds_per_square_inch',
 'lbgo': 'gorna_oryahovitsa_airport',
 'lbgt': 'lgbt',
 'lbgtq': 'lgbt',
 'lbh-589': 'panobinostat',
 'lbhf': 'london_borough_of_hammersmith_and_fulham',
 'lbia': 'leeds_bradford_international_airport',
 'lbid': 'ibid.',
 'lbist': 'logic_built-in_self-test',
 'lblr': 'leighton_buzzard_light_railway',
 'lbma': 'london_bullion_market',
 'lbmb': 'lehman_brothers_merchant_banking',
 'lbmhs': 'bernice_macnaughton_high_school',
 'lbms': 'lake_bluff_middle_school',
 'lbngr': 'leighton_buzzard_light_railway',
 'lbnl': 'lawrence_berkeley_national_laboratory',
 'lbpd': 'long_beach_police_department',
 'lbpg': 'graf_ignatievo_air_base',
 'lbpia': 'toronto_pearson_international_airport',
 'lbppr': 'puerto_rico_baseball_league',
 'lbrp': 'lesser_ritual_of_the_pentagram',
 'lbrs': 'ruse_airport',
 'lbrut': 'london_borough_of_richmond_upon_thames',
 'lbsce': 'lal_bahadur_shastry_college_of_engineering_kasargod',
 'lbsf': 'sofia_airport',
 'lbsitw': 'l_b_s_institute_of_technology_for_women',
 'lbsnaa': 'lal_bahadur_shastri_national_academy_of_administration',
 'lbtbp': 'long_beach_township_beach_patrol',
 'lbts': 'liberty_university',
 'lbtya': 'liberty_global',
 'lbusd': 'long_beach_unified_school_district',
 'lbv-1806': 'lbv_1806-20',
 'lbwn': 'varna_airport',
 'lbxlls': 'logos_bible_software',
 'lbxproxy': 'low_bandwidth_x'}
        