
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_ld = {'ld-50': 'median_lethal_dose',
 'ld-celp': 'g.728',
 'ld-converter': 'basic_oxygen_steelmaking',
 'ld-linux.so': 'dynamic_linker',
 'ld-mpt': 'democratic_league/movement_for_the_labour_party',
 'ld.so': 'dynamic_linker',
 'ld/mpt': 'democratic_league/movement_for_the_labour_party',
 'ld11': 'unit_load_device',
 'ld50': 'median_lethal_dose',
 'lda-number': 'l-number',
 'ldap': 'lightweight_directory_access_protocol',
 'ldbba': 'licentiate_diploma_in_brass_band_adjudication',
 'ldcs': 'least_developed_countries',
 'lddba': 'licentiate_diploma_in_brass_band_adjudication',
 'lddc': 'london_docklands_development_corporation',
 'lddm': 'windows_display_driver_model',
 'lddp': 'democratic_labour_party_of_lithuania',
 'ldds': 'local_development_documents',
 'lddu': 'dubrovnik_airport',
 'lddv': 'least_distance_of_distinct_vision',
 'ldef': 'long_duration_exposure_facility',
 'ldeo': 'lamont-doherty_earth_observatory',
 'ldfc': 'loughborough_dynamo_f.c.',
 'ldfs': 'local_development_frameworks',
 'ldhi': 'clathrate_hydrate',
 'ldif': 'ldap_data_interchange_format',
 'ldii': 'indonesia_institute_of_islamic_dawah',
 'ldin': 'approach_lighting_system',
 'ldl-c': 'low-density_lipoprotein',
 'ldl-cholesterol': 'low-density_lipoprotein',
 'ldlo': 'lowest_published_lethal_dose',
 'ldlr': 'ldl_receptor',
 'ldoce': 'longman_dictionary_of_contemporary_english',
 'ldoh': 'last_days_of_humanity',
 'ldom': 'logical_domains',
 'ldot': 'louisiana_department_of_transportation_and_development',
 'ldotd': 'louisiana_department_of_transportation_and_development',
 'ldpc': 'low-density_parity-check_code',
 'ldpd': 'liberal_democratic_party_of_germany',
 'ldpe': 'low-density_polyethylene',
 'ldpl': 'pula_airport',
 'ldpr': 'liberal_democratic_party_of_russia',
 'ldprf': 'liberal_democratic_party_of_russia',
 'ldpsu': 'liberal_democratic_party_of_russia',
 'ldri': 'rijeka_airport',
 'ldrr': 'louisiana_and_delta_railroad',
 'lds.org': 'the_church_of_jesus_christ_of_latter-day_saints',
 'ldsb': 'limestone_district_school_board',
 'ldsf': 'lithuanian_cycling_federation',
 'ldsp': 'split_airport',
 'ldssa': 'lds_student_association',
 'ldtd': 'ladainian_tomlinson',
 'ldtp': 'linux_desktop_testing_project',
 'ldtv': 'low-definition_television',
 'lduq': 'liga_deportiva_universitaria_de_quito',
 'ldvt': 'linear_variable_differential_transformer',
 'ldws': 'lane_departure_warning_system',
 'ldys': 'liberal_youth',
 'ldza': 'zagreb_airport',
 'ldzd': 'zadar_airport'}
        