# Copied from
# https://github.com/cerebrotech/domino-mlflow/blob/master/domino_mlflow/services/constants.py
# TODO: Move to common location
TAG_MLFLOW_PREFIX = "mlflow.domino"

TAG_MLFLOW_DOMINO_USER = f"{TAG_MLFLOW_PREFIX}.user"
TAG_MLFLOW_DOMINO_PROJECT = f"{TAG_MLFLOW_PREFIX}.project"
TAG_MLFLOW_DOMINO_PROJECT_ID = f"{TAG_MLFLOW_PREFIX}.project_id"
TAG_MLFLOW_DOMINO_PROJECT_NAME = f"{TAG_MLFLOW_PREFIX}.project_name"
TAG_MLFLOW_DOMINO_RUN_ID = f"{TAG_MLFLOW_PREFIX}.run_id"
TAG_MLFLOW_DOMINO_HARDWARE_TIER = f"{TAG_MLFLOW_PREFIX}.hardware_tier"
TAG_MLFLOW_DOMINO_ENVIRONMENT_ID = f"{TAG_MLFLOW_PREFIX}.environment_id"
TAG_MLFLOW_DOMINO_ENVIRONMENT_REVISION_ID = (
    f"{TAG_MLFLOW_PREFIX}.environment_revision_id"
)
#For JWT Token
TAG_IS_SERVICE_ACCOUNT = "IS_SERVICE_ACCOUNT"
TAG_DOMINO_PROJECT_ID = "DOMINO_PROJECT_ID"
TAG_DOMINO_PROJECT_NAME = "domino_project_name"
TAG_DOMINO_PROJECT_OWNER = "DOMINO_PROJECT_OWNER"
TAG_DOMINO_HARDWARE_TIER_ID = "DOMINO_HARDWARE_TIER_ID"  # TODO: Remove

