
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-17T15:29:20+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b61ea2f8d7d553b07eeff38bacb5d04df6dca4ba",
 "version": "2795"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
