
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_rp = {'_': ['rp_photonics_encyclopedia',
       'rp_101-class_tugboat',
       'rp_113-class_tugboat',
       'rp_118-class_tugboat',
       'rp_125-class_tugboat',
       'rp-selecta_ice_cream',
       'rp_funding_center',
       'rp_mall,_kollam'],
 'd': ['rpd_machine_gun'],
 'f': ['rpfg_rna_motif'],
 'g': ['rpg_programming_language',
       'rpg-7_portable_grenade',
       'rpg_job/class_list',
       'rpg_weapons_system',
       'rpg_battle_systems',
       'rpg_life_sciences',
       'rpg_maker_series',
       'rpg_jinsei_game',
       'rpg_real_estate',
       'rpg_game_makers',
       'rpg_maker_2003',
       'rpg_maker_1995',
       'rpg_maker_2000',
       'rpg_tsukuru_vx',
       'rpg_maker_95',
       'rpg_maker_vx',
       'rpg_maker_xp',
       'rpg_maker_3',
       'rpg_maker_2'],
 'i': ['rpi-wpi_football_rivalry',
       'rpi_field_house',
       'rpi_tech_park',
       'rpi_all_items'],
 'k': ['rpk-6_vodopad/rpk-7_veter', 'rpk_machine_gun'],
 'l': ['rpl_character_set'],
 'm': ['rpm-based_linux_distribution',
       'rpm_nautical_foundation',
       'rpm_international_inc.',
       'rpm_international_inc',
       'rpm_package_manager',
       'rpm_college,_patna'],
 'n': ['rpn_arangkada_balita', 'rpn_kampong_mentiri', 'rpn_kampong_rimba'],
 'o': ["rpos_mrna_5'utr"],
 'p': ['rpp_film_factory'],
 'r': ['rpr_problem_diagnosis'],
 's': ['rps_world_championships',
       'rps_music_awards',
       'rpsf_leader_rna',
       'rps_group_plc'],
 'w': ['rpw_heavyweight_championship',
       "rpw_women's_championship",
       'rpw/njpw_uprising_2015']}
