
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_bd = {'_': ['bd+17deg3248',
       'bd+40deg4210',
       'bd+60deg2522',
       'bd-08deg2823',
       'bd-15deg6290',
       'bd-10deg3166',
       'bd+20deg307',
       'bd-1047',
       'bd-java',
       'bd1018',
       'bd1067',
       'bd1031',
       'bd1063',
       'bd1008',
       'bd-rom',
       'bd1052',
       'bd-700',
       'bd1060',
       'bd-01',
       'bd-18',
       'bd-20',
       'bd-27',
       'bd-46',
       'bd-23',
       'bd-15',
       'bd-42',
       'bd-49',
       'bd-39',
       'bd-59',
       'bd-35',
       'bd-34',
       'bd092',
       'bd-38',
       'bd-21',
       'bd-22',
       'bd-06',
       'bd-56',
       'bd-29',
       'bd-02',
       'bd-30',
       'bd-41',
       'bd-55',
       'bd-5j',
       'bd-53',
       'bd-44',
       'bd-54',
       'bd-08',
       'bd-43',
       'bd-37',
       'bd-60',
       'bd-05',
       'bd100',
       'bd-19',
       'bd-57',
       'bd-47',
       'bd-50',
       'bd-33',
       'bd-03',
       'bd-64',
       'bd-32',
       'bd-51',
       'bd-48',
       'bd-04',
       'bd-re',
       'bd-63',
       'bd-13',
       'bd-61',
       'bd-10',
       'bd-36',
       'bd-62',
       'bd-26',
       'bd-12',
       'bd-07',
       'bd-52',
       'bd-rw',
       'bd-16',
       'bd-45',
       'bd-24',
       'bd-40',
       'bd-31',
       'bd-25',
       'bd-14',
       'bd-09',
       'bd-28',
       'bd-58',
       'bd-1',
       'bd-4',
       'bd-9',
       'bd-j',
       'bd50',
       'bd-5',
       'bd-r',
       'bd20',
       'bd80',
       'bd9',
       'bd+',
       'bd5'],
 'a': ['bdallophytum',
       'bdallophyton',
       'bdadoun',
       'bda1b',
       'bda-9',
       'bdale',
       'bdawk',
       'bdam',
       'bda3',
       'bda2',
       'bda4',
       'bda5',
       'bdaf',
       'bdav',
       'bda1',
       'bda7',
       'bdae',
       'bdag',
       'bdas',
       'bda6',
       'bday',
       'bda'],
 'b': ['bdbc', 'bdb'],
 'c': ['bdca-2', 'bdca-4', 'bdca-3', 'bdcol', 'bdc'],
 'd': ['bddc', 'bdd'],
 'e': ['bdellovibrionaceae',
       'bdellovibrionales',
       'bdellomicrovirus',
       'bdellovibrionota',
       'bdellocephala',
       'bdellozonium',
       'bdellouridae',
       'bdellonyssus',
       'bdellovibrio',
       'bdelyropsis',
       'bdellatomy',
       'bdelloidea',
       'bdelygmia',
       'bdellodus',
       'bdellidae',
       'bdelyrus',
       'bdeneves',
       'bdec.com',
       'bdelloid',
       'bdeogale',
       'bdellium',
       'bde-209',
       'bdebba',
       'bdella',
       'bde-99',
       'bdent',
       'bdesh',
       'bdes',
       'bdem',
       'bde'],
 'f': ['bdf-3299', 'bdf-521', 'bdfl', 'bdf'],
 'g': ['bdg'],
 'h': ['bdhs', 'bdh1', 'bdh'],
 'i': ['bdintsi', 'bdii', 'bdiu', 'bdin', 'bdi'],
 'j': ['bdj'],
 'k': ['bdkrb1', 'bdkrb2', 'bdk'],
 'l': ['bdla', 'bdl'],
 'm': ['bdmlqrt', 'bdmlr', 'bdmi', 'bdma', 'bdmx', 'bdm'],
 'n': ['bdnews24.com', 'bdnf', 'bdn'],
 'o': ['bdo-epci', 'bdood', 'bdort', 'bdo'],
 'p': ['bdp-12', 'bdp1', 'bdpc', 'bdpa', 'bdp'],
 'q': ['bdq'],
 'r': ['bdr-101a', 'bdrip', 'bdre', 'bdrv', 'bdrs', 'bdrf', 'bdr'],
 's': ['bdsec', 'bds-1', 'bdsni', 'bdsc', 'bdsm', 'bdst', 'bds'],
 't': ['bdtnrm', 'bdth2', 'bdtl', 'bdtc', 'bdt'],
 'u': ['bdubs', 'bduf', 'bdu'],
 'v': ['bdv'],
 'w': ['bdwm', 'bdw'],
 'x': ['bdx'],
 'y': ['bdy'],
 'z': ['bdzh', 'bdz']}
