
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_fb = {'_': ['fb-dimm', 'fb-111a', 'fb-10', 'fb-22', 'fb-1', 'fb2k', 'fb2'],
 'a': ['fbasic', 'fbaa', 'fbar', 'fbas', 'fba'],
 'b': ['fbbank', 'fbb'],
 'c': ['fbcb2', 'fbci', 'fbcs', 'fbc'],
 'd': ['fbdimm', 'fbdev', 'fbd'],
 'e': ['fbe'],
 'f': ['fbft', 'fbf'],
 'g': ['fbgs', 'fbga', 'fbgc', 'fbg'],
 'h': ['fbhw', 'fbhs', 'fbh'],
 'i': ['fbi.gov', 'fbisd', 'fbins', 'fbise', 'fbia', 'fbis', 'fbih', 'fbi'],
 'k': ['fbke', 'fbk'],
 'l': ['fbla-pbl',
       'fblim1',
       'fbln2',
       'fbln1',
       'fbln5',
       'fbln4',
       'fbla',
       'fbld',
       'fbl'],
 'm': ['fbmw', 'fbm'],
 'n': ['fbn1', 'fbn3', 'fbn2', 'fbn'],
 'o': ['fborfw', 'fbofw', 'fbomb', 'fbook', 'fbop', 'fbox', 'fbo'],
 'p': ['fbp1', 'fbp'],
 'r': ['fbreader', 'fbr-600', 'fbrs', 'fbr'],
 's': ['fbsoa', 'fbse', 'fbsd', 'fbsm', 'fbsk', 'fbs'],
 't': ['fbtmof', 'fbtl', 'fbt'],
 'u': ['fbus', 'fbu'],
 'w': ['fbw'],
 'x': ['fbxo38',
       'fbxo11',
       'fbxo28',
       'fbxw11',
       'fbxo24',
       'fbxo32',
       'fbxw10',
       'fbxo31',
       'fbxl2',
       'fbxl4',
       'fbxl5',
       'fbxo2',
       'fbxw8',
       'fbxl3',
       'fbxo7',
       'fbxw7',
       'fbxo6',
       'fbxl7',
       'fbxo9',
       'fbxw2',
       'fbxo4',
       'fbxw4',
       'fbxo5',
       'fbxw5',
       'fbx'],
 'y': ['fby']}
