
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ff = {'_': ['ff-1080',
       'ff10-2',
       'ff.net',
       'ff7:ac',
       'ff7ac',
       'ff-x3',
       'ff7cc',
       'ff2j',
       'ff10',
       'ff12',
       'ff.c',
       'ff-7',
       'ff13',
       'ff11',
       'ff14',
       'ff7',
       'ff2',
       'ff5',
       'ff9',
       'ff6',
       'ff8',
       'ff4',
       'ff3'],
 'a': ['ffaldybrenin',
       'ffairfach',
       'ffarmers',
       'ffarcs',
       'ffar1',
       'ffar2',
       'ffado',
       'ffa13',
       'ffar3',
       'ffar',
       'ffaf',
       'ffac',
       'ffa'],
 'b': ['ffbd', 'ffb'],
 'c': ['ffccds', 'ffcccb', 'ffcc', 'ffc'],
 'd': ['ffdshow-tryouts',
       'ffd-ricardo',
       'ffdshow',
       'ffd1dc',
       'ffda',
       'ffdi',
       'ffdp',
       'ffdo',
       'ffd'],
 'e': ['ffestiniog',
       'ffernfael',
       'ffermio',
       'fferam',
       'ffeil',
       'fferm',
       'ffelp',
       'ffee',
       'ffem',
       'ffe'],
 'f': ['ffffound!',
       'fffipp',
       'fff:ct',
       'fff:cc',
       'ffff',
       'fffe',
       'fffp',
       'fff'],
 'g': ['ffg'],
 'h': ['ffhnas', 'ffhs', 'ffh'],
 'i': ['ffishing',
       'ffii.cz',
       'ffinian',
       'ffiiids',
       'ffiri',
       'ffizz',
       'ffiii',
       'ffion',
       'ffiec',
       'ffing',
       'ffix',
       'ffiv',
       'ffii',
       'ffi'],
 'j': ['ffj'],
 'k': ['ffkm', 'ffka', 'ffkr', 'ffk'],
 'l': ['fflegend',
       'fflecsi',
       'fflaps',
       'fflach',
       'fflick',
       'fflag',
       'fflam',
       'fflm',
       'ffl'],
 'm': ['ffmpeg2theora', 'ffmpeg', 'ffmpg', 'ffme', 'ffmq', 'ffm'],
 'n': ['ffn'],
 'o': ['ffotogallery',
       'fforest-fach',
       'fforestfach',
       'ffos-y-fran',
       'ffos-y-ffin',
       'ffostrasol',
       'ffoshelyg',
       'ffolkes',
       'ffoslas',
       'fforest',
       'fforde',
       'ffox',
       'ffow',
       'ffo'],
 'p': ['ffpe-epo',
       'ffplay',
       'ffphm',
       'ffpir',
       'ffp2',
       'ffp3',
       'ffps',
       'ffpp',
       'ffp'],
 'q': ['ffq'],
 'r': ['ffrreedom',
       'ffrotss',
       'ffrench',
       'ffrith',
       'ffriog',
       'ffryes',
       'ffrdc',
       'ffrr',
       'ffrf',
       'ffr'],
 's': ['ffserver', 'ffstn', 'ffsa', 'ffs2', 'ffss', 'ffs'],
 't': ['fftactics',
       'fftpack',
       'fftrou',
       'ffta2',
       'fftuz',
       'ffta',
       'fftg',
       'fftf',
       'fftw',
       'fftl',
       'ffts',
       'fft'],
 'u': ['ffun', 'ffus', 'ffu'],
 'v': ['ffvii:doc',
       'ffvii:ac',
       'ffvii:cc',
       'ffvii:bc',
       'ffvxiii',
       'ffviii',
       'ffv13',
       'ffvii',
       'ffv1',
       'ffva',
       'ffvi',
       'ffv'],
 'w': ['ffwb', 'ffwd', 'ffw'],
 'x': ['ffxii:rw',
       'ffxiii',
       'ffx-2',
       'ffxiv',
       'ffxii',
       'ffxi',
       'ffx3',
       'ffx2',
       'ffx'],
 'y': ['ffynnon-ddrain', 'ffynnongroew', 'ffynnon-oer'],
 'z': ['ffz']}
