
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_fk = {'_': ['fk-league',
       'fk-space',
       'fk-506',
       'fk1012',
       'fk.51',
       'fk.58',
       'fk962',
       'fk-51',
       'fk-58',
       'fk506',
       'fk51',
       'fk58',
       'fk3',
       'fk5',
       'fk4',
       'fk6'],
 'a': ['fkab', 'fka'],
 'b': ['fkbp12.6',
       'fkbp1b',
       'fkbp10',
       'fkbp52',
       'fkbp12',
       'fkbp1a',
       'fkbp14',
       'fkbp5',
       'fkbp2',
       'fkbp8',
       'fkbp3',
       'fkbp9',
       'fkbp7',
       'fkbpl',
       'fkbp6',
       'fkbp4',
       'fkbp',
       'fkb'],
 'c': ['fkcc', 'fkc'],
 'e': ['fkeys', 'fkey'],
 'f': ['fkfpp', 'fkf'],
 'g': ['fkg'],
 'h': ['fkhr'],
 'i': ['fkirina', 'fki'],
 'j': ['fkj'],
 'k': ['fkku', 'fkk'],
 'l': ['fkl'],
 'm': ['fkm'],
 'n': ['fkn'],
 'p': ['fkp'],
 'r': ['fkrp'],
 's': ['fks'],
 't': ['fktu', 'fktn', 'fkt'],
 'w': ['fkw'],
 'y': ['fky']}
