
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_fp = {'_': ['fp-b-cppit',
       'fp-cit',
       'fp-45',
       'fp84',
       'fp45',
       'fp-c',
       'fp6',
       'fp9',
       'fp7',
       'fp8',
       'fp4',
       'fp5',
       'fp2',
       'fp1'],
 'a': ['fpahk', 'fpass', 'fpaa', 'fpa'],
 'b': ['fpba', 'fpb'],
 'c': ['fpcit',
       'fpcgi',
       'fpcac',
       'fpcon',
       'fpct',
       'fpcc',
       'fpcs',
       'fpce',
       'fpc'],
 'd': ['fpd-link', 'fpda', 'fpdt', 'fpds', 'fpdp', 'fpdl', 'fpd'],
 'e': ['fpe'],
 'f': ['fpf'],
 'g': ['fpg-82',
       'fpgui',
       'fpgas',
       'fpg-9',
       'fpgac',
       'fpgrm',
       'fpgt',
       'fpga',
       'fpgb',
       'fpgs',
       'fpg'],
 'h': ['fphs', 'fph'],
 'i': ['fpinnovations', 'fpip', 'fpif', 'fpi'],
 'j': ['fpj'],
 'k': ['fpk-pascal', 'fpk'],
 'l': ['fplp', 'fplc', 'fpld', 'fpla', 'fplt', 'fpl'],
 'm': ['fpmarkets', 'fpml', 'fpmt', 'fpm'],
 'n': ['fpn'],
 'o': ['fpoba', 'fpoe', 'fpo'],
 'p': ['fppm', 'fpp'],
 'q': ['fpqc-topology', 'fpq-6', 'fpq6'],
 'r': ['fprint',
       'fprot',
       'fprl2',
       'fpras',
       'fprl1',
       'fpri',
       'fpr1',
       'fpry',
       'fpr'],
 's': ['fpsrussia',
       'fps-124',
       'fps-120',
       'fps-115',
       'fps-126',
       'fps-117',
       'fps-129',
       'fps-123',
       'fps-108',
       'fps-95',
       'fps126',
       'fps129',
       'fps-41',
       'fps117',
       'fpshot',
       'fps120',
       'fps123',
       'fps-16',
       'fps108',
       'fps115',
       'fps-35',
       'fps124',
       'fps95',
       'fpspi',
       'fps16',
       'fps17',
       'fpsp',
       'fpsb',
       'fpsc',
       'fpse',
       'fpsa',
       'fps'],
 't': ['fptech', 'fptas', 'fptp', 'fptv', 'fpt'],
 'u': ['fputchar', 'fpu'],
 'v': ['fpv'],
 'w': ['fpw'],
 'x': ['fpx'],
 'y': ['fpy'],
 'z': ['fpz']}
