#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# AUTO-GENERATED CONTENT
d_stem_lg = {'lga': {'lgas': []},
             'lgalactos': {'lgalactose': []},
             'lgb': {'lgb': []},
             'lgbo': {'lgbos': []},
             'lgbp': {'lgbps': []},
             'lgbt': {'lgbts': []},
             'lgc': {'lgcs': []},
             'lgd': {'lgds': []},
             'lge': {'lges': []},
             'lgenc': {'lgence': []},
             'lgener': {'lgeneral': ['lgenerally']},
             'lgeneral': ['lgenerally'],
             'lgeorg': {'lgeorge': []},
             'lger': {'lgers': []},
             'lgf': {'lgfs': []},
             'lgg': {'lggs': []},
             'lgger': {'lggers': []},
             'lggest': {'lggested': []},
             'lggi': {'lggy': []},
             'lggo': {'lggos': []},
             'lght': {'lghts': []},
             'lgi': {'lgis': [], 'lgy': []},
             'lgic': {'lgics': []},
             'lgien': {'lgiene': []},
             'lgier': {'lgiers': []},
             'lgine': {'lgines': []},
             'lgineer': {'lgineering': []},
             'lgiou': {'lgious': []},
             'lgjo': {'lgjos': []},
             'lgl': {'lgls': []},
             'lglesia': {'lglesias': []},
             'lgli': {'lgly': []},
             'lgloo': {'lgloos': []},
             'lglucos': {'lglucose': []},
             'lglucosamin': {'lglucosamine': []},
             'lglutam': {'lglutamate': [], 'lglutamic': []},
             'lglutamin': {'lglutamine': []},
             'lglycin': {'lglycine': []},
             'lgm': {'lgms': []},
             'lgmd': {'lgmds': []},
             'lgn': {'lgns': []},
             'lgnaci': {'lgnacy': []},
             'lgnatiu': {'lgnatius': []},
             'lgne': {'lgnes': []},
             'lgneou': {'lgneous': []},
             'lgni': {'lgny': []},
             'lgnimbrit': {'lgnimbrite': []},
             'lgnitabl': {'lgnitability': []},
             'lgnite': {'lgnited': [], 'lgniting': []},
             'lgnobl': {'lgnoble': []},
             'lgnoranc': {'lgnorance': []},
             'lgnorantli': {'lgnorantly': []},
             'lgnore': {'lgnored': [], 'lgnores': [], 'lgnoring': []},
             'lgo': {'lgos': []},
             'lgorithm': {'lgorithms': []},
             'lgorot': {'lgorots': []},
             'lgp': {'lgps': []},
             'lgpo': {'lgpos': []},
             'lgr': {'lgrs': []},
             'lgricultur': {'lgricultural': []},
             'lgrim': {'lgrims': []},
             'lgth': {'lgths': []},
             'lgu': {'lgus': []},
             'lguana': {'lguanas': []},
             'lguanida': {'lguanidae': []},
             'lgulon': {'lgulonic': []},
             'lguluron': {'lguluronic': []},
             'lgure': {'lgures': []},
             'lgv': {'lgv': []}}
