#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# AUTO-GENERATED CONTENT
d_stem_lp = {'lpa': {'lpas': []},
             'lpan': {'lpans': []},
             'lpani': {'lpanies': [], 'lpany': []},
             'lpapplicationnam': {'lpapplicationname': []},
             'lpar': {'lpars': []},
             'lpare': {'lpared': []},
             'lpari': {'lparis': []},
             'lparticularli': {'lparticularly': []},
             'lpb': {'lpbs': []},
             'lpc': {'lpcs': []},
             'lpcate': {'lpcated': []},
             'lpclassnam': {'lpclassname': []},
             'lpcreateparam': {'lpcreateparams': []},
             'lpcritic': {'lpcritical': []},
             'lpd': {'lpds': []},
             'lpdirectori': {'lpdirectory': []},
             'lpdu': {'lpdus': []},
             'lpe': {'lpes': []},
             'lpeak': {'lpeaking': [], 'lpeaks': []},
             'lpeci': {'lpecies': []},
             'lpentan': {'lpentane': []},
             'lpenten': {'lpentene': []},
             'lpeopl': {'lpeople': []},
             'lper': {'lpers': []},
             'lperhap': {'lperhaps': []},
             'lperson': {'lpersonal': []},
             'lpf': {'lpfs': []},
             'lpfilenam': {'lpfilename': []},
             'lpform': {'lpforms': []},
             'lpg': {'lpgs': []},
             'lpga': {'lpgas': []},
             'lph': {'lphs': []},
             'lphabet': {'lphabetical': []},
             'lphandl': {'lphandle': ['lphandles']},
             'lphandle': ['lphandles'],
             'lpheni': {'lpheny': []},
             'lphenid': {'lphenidate': []},
             'lphenylalanin': {'lphenylalanine': []},
             'lphesian': {'lphesians': []},
             'lphesu': {'lphesus': []},
             'lphi': {'lphys': []},
             'lphian': {'lphians': []},
             'lphicrat': {'lphicrates': []},
             'lphigeni': {'lphigenie': []},
             'lphigini': {'lphiginie': []},
             'lphons': {'lphonse': []},
             'lphosphat': {'lphosphate': []},
             'lphosphin': {'lphosphine': []},
             'lphysic': {'lphysical': []},
             'lpi': {'lpis': [], 'lpy': ['lpys']},
             'lpirit': {'lpirits': []},
             'lpiritu': {'lpiritual': []},
             'lpistl': {'lpistle': []},
             'lpit': {'lpits': []},
             'lpkeynam': {'lpkeyname': []},
             'lpl': {'lpls': []},
             'lple': {'lples': []},
             'lplete': {'lpleted': [], 'lpletely': []},
             'lpli': {'lply': []},
             'lploy': {'lployed': []},
             'lploye': {'lployee': ['lployees']},
             'lployee': ['lployees'],
             'lpm': {'lpms': []},
             'lpmud': {'lpmuds': []},
             'lpn': {'lpn': []},
             'lpo': {'lpos': []},
             'lpoke': {'lpoked': [], 'lpoking': []},
             'lpoli': {'lpoly': []},
             'lpolit': {'lpolitical': []},
             'lponent': {'lponents': []},
             'lpoper': {'lpoperation': []},
             'lpoption': {'lpoptions': []},
             'lporari': {'lporary': []},
             'lport': {'lports': []},
             'lportanc': {'lportance': []},
             'lpose': {'lposed': []},
             'lposit': {'lposition': []},
             'lpossibl': {'lpossible': []},
             'lpoverlap': {'lpoverlapped': []},
             'lpp': {'lpps': []},
             'lpparamet': {'lpparameter': ['lpparameters']},
             'lpparameter': ['lpparameters'],
             'lppli': {'lpplied': [], 'lpplies': [], 'lpply': []},
             'lppoint': {'lppoints': []},
             'lppose': {'lpposed': []},
             'lpr': {'lprs': []},
             'lprd': {'lprds': []},
             'lprednisolon': {'lprednisolone': []},
             'lpreserv': {'lpreserved': []},
             'lpreturnedstr': {'lpreturnedstring': []},
             'lprobabl': {'lprobably': []},
             'lproceed': {'lproceedings': []},
             'lprolin': {'lproline': []},
             'lpropan': {'lpropane': []},
             'lpropanesulfon': {'lpropanesulfonate': []},
             'lprove': {'lproved': []},
             'lprovid': {'lprovided': []},
             'lpsactiv': {'lpsactivated': []},
             'lpsbind': {'lpsbinding': []},
             'lpsecur': {'lpsecurity': []},
             'lpsecurityattribut': {'lpsecurityattributes': []},
             'lpsilater': {'lpsilateral': []},
             'lpsinduc': {'lpsinduced': []},
             'lpsiu': {'lpsius': []},
             'lpsm': {'lpsms': []},
             'lpso': {'lpsos': []},
             'lpsp': {'lpsps': []},
             'lpss': {'lp': []},
             'lpsstimul': {'lpsstimulated': []},
             'lpstreat': {'lpstreated': []},
             'lpsu': {'lpsus': []},
             'lpszclassnam': {'lpszclassname': []},
             'lpt': {'lpts': []},
             'lptemplatenam': {'lptemplatename': []},
             'lpten': {'lptens': []},
             'lpthreadattribut': {'lpthreadattributes': []},
             'lption': {'lptions': []},
             'lptv': {'lptvs': []},
             'lpu': {'lpus': []},
             'lpublish': {'lpublished': []},
             'lpui': {'lpuis': []},
             'lpuser': {'lpusers': []},
             'lpv': {'lpvs': []},
             'lpvaluenam': {'lpvaluename': []},
             'lpwindownam': {'lpwindowname': []},
             'lpy': ['lpys'],
             'lpyalti': {'lpyalty': []},
             'lpyridin': {'lpyridine': []},
             'lpyrophosph': {'lpyrophosphate': []},
             'lpyrrolin': {'lpyrroline': []}}
