
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_kg = {'_': ['kg_baalakrishnan',
       'kg_balakrishnan',
       'kg-175_taclane',
       'kg_ambegaonkar',
       'kg_cunningham',
       'kg/1940_lmg',
       'kg_canaleta',
       'kg_convoys',
       'kg_hammar',
       'kg_whales',
       'kg_george',
       'kg_murphy',
       'kg_united',
       'kg_basin',
       'kg_tribe',
       'kg_mudge',
       'kg_200',
       'kg_55',
       'kg_77',
       'kg_51',
       'kg_76',
       'kg_54',
       'kg_53',
       'kg_2',
       'kg_6',
       'kg_4',
       'kg_3'],
 'a': ['kgalebane_mohlakoana',
       'kgalagadi_district',
       'kgalagadi_language',
       'kgalema_motlhanthe',
       'kgalema_motlanthe',
       'kgatleng_district',
       'kgakgamotso_pharo',
       'kgaogelo_sekgota',
       'kgalema_molanthe',
       'kgaudisa_molefe',
       'kgari,_botswana',
       'kgagodi_crater',
       'kgale_hill'],
 'b': ['kgb_memorials',
       'kgb_defectors',
       'kgb_archiver',
       'kgb_russia',
       'kgb_museum',
       'kgb_ussr',
       'kgb_kgb'],
 'e': ['kgebetli_moele'],
 'f': ['kgf_academy', 'kgf_school'],
 'i': ['kgi_bank'],
 'm': ['kgmc_lucknow'],
 'o': ['kgosiemang_khumoyarano',
       'kgomotso_itlhabanyeng',
       'kgomotso_christopher',
       'kgomotso_balotthanyi',
       'kgosietsile_mampori',
       'kgothatso_montjane',
       'kgosi_galeshewe',
       'kgopedi_lilokoe',
       'kgosi_sekonyela',
       'kgomotso_moahi',
       'kgosi_gaborone',
       'kgosi_letlape',
       'kgotso_moleko',
       'kgosi_ntlhe',
       'kgo_kolomna'],
 's': ['kgs._lyngby'],
 't': ['kgtv_tower'],
 'v': ['kgv_college', 'kgv_school', 'kgv_park', 'kgv_oval'],
 'w': ['kgw-1_loon']}
