
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_km = {'km18a1_mine': 'm18a1_claymore_antipersonnel_mine',
 'km_0': 'kilometre_zero',
 'km_31': 'kilometer_31',
 'km_adimoolam': 'k._m._adimoolam',
 'km_arif': 'khalid_mahmud_arif',
 'km_beenamol': 'k._m._beenamol',
 'km_bismarck': 'german_battleship_bismarck',
 'km_chaitanya': 'k._m._chaitanya',
 'km_cherian': 'k._m._cherian',
 'km_communications': 'km_communications_inc.',
 'km_food': 'kam_man_food',
 'km_gneisenau': 'german_battleship_gneisenau',
 'km_mani': 'k._m._mani',
 'km_maulavi': 'k._m._maulavi',
 'km_munshi': 'k._m._munshi',
 'km_peyton': 'k._m._peyton',
 'km_roy': 'k._m._roy',
 'km_scharnhorst': 'german_battleship_scharnhorst',
 'km_seth': 'krishna_mohan_seth',
 'km_tirpitz': 'german_battleship_tirpitz',
 'kmal_haasan': 'kamal_haasan',
 'kmart_200': 'target_house_200',
 'kmart_chef': 'kmart',
 'kmart_corp': 'kmart',
 'kmart_corporation': 'kmart',
 'kmart_foods': 'kmart',
 'kmart_ggo': 'wyndham_championship',
 'kmart_holding': 'kmart',
 'kmart_holdings': 'kmart',
 'kmb_group': 'kowloon_motor_bus',
 'kmc_building': 'karachi_municipal_corporation_building',
 'kmc_stadium': 'cdgk_stadium',
 'kmer_rouge': 'khmer_rouge',
 'kmfdm_records': 'kmfdm',
 'kmfm_shepway': 'kmfm_shepway_and_white_cliffs_country',
 'kmg_group': 'kpmg',
 'kml_validator': 'keyhole_markup_language',
 'kmountain_dew': 'mountain_dew',
 'kmox_1120': 'kmox',
 'kmox_am': 'kmox',
 'kmox_radio': 'kmox',
 'kmp_braunschweig': 'braunschweig_classix_festival',
 'kmp_expressway': 'kundli-manesar-palwal_expressway',
 'kms_bismarck': 'german_battleship_bismarck',
 'kms_condition': 'kms_state',
 'kms_gneisenau': 'german_battleship_gneisenau',
 'kms_scharnhorst': 'german_battleship_scharnhorst',
 'kms_tirpitz': 'german_battleship_tirpitz',
 'kmsk_deinze': 'k.m.s.k._deinze',
 'kmsp-tv_tower': 'kmsp-tv',
 'kmt_army': 'national_revolutionary_army',
 'kmt_flag': 'blue_sky_with_a_white_sun',
 'kmv_avia': 'kavminvodyavia',
 'kmw_dingo': 'atf_dingo',
 'kmyc-am_1410': 'kmyc',
 'kmyc_1410': 'kmyc'}
        