
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_nn = {'_': ['nn.wikipedia.org', 'nn2s', 'nn9'],
 'a': ['nnapulitano',
       'nnarambia',
       'nnaemeka',
       'nnamani',
       'nnachi',
       'nnamdi',
       'nnao2',
       'nnao3',
       'nnadi',
       'nnaji',
       'nnama',
       'nnabo',
       'nna'],
 'b': ['nnb'],
 'c': ['nnc-711', 'nnck', 'nncl', 'nnc'],
 'd': ['nndb.com', 'nndym', 'nndb'],
 'e': ['nnekwunwenyi',
       'nnewichi',
       'nnenna',
       'nnepra',
       'nneka',
       'nnest',
       'nnebe',
       'nnewi',
       'nnemp',
       'nnec',
       'nne1'],
 'f': ['nnfcc', 'nnfa', 'nnf'],
 'g': ['nngi', 'nng'],
 'h': ['nnhs', 'nnh'],
 'i': ['nni-351', 'nnirvi', 'nnicu', 'nnit', 'nni'],
 'j': ['nnjil'],
 'k': ['nnkieh', 'nnk'],
 'l': ['nnls', 'nnl'],
 'm': ['nnmt', 'nnmf', 'nnmc', 'nnm'],
 'n': ['nnn'],
 'o': ['nnooo', 'nnos', 'nnor', 'nnoc', 'nno'],
 'p': ['nnpi-c',
       'nnpi-u',
       'nnpdf',
       'nnptc',
       'nnpt',
       'nnpc',
       'nnpa',
       'nnpi',
       'nnp'],
 'r': ['nnrti', 'nnrp', 'nnr'],
 's': ['nnsma', 'nnsy', 'nnsa', 'nnsc', 'nnsl', 'nnss', 'nns'],
 't': ['nntool', 'nntps', 'nntn', 'nntp', 'nnt'],
 'u': ['nnundu', 'nnu'],
 'v': ['nnv'],
 'w': ['nnwa', 'nnw'],
 'y': ['nnyx'],
 'z': ['nnz']}
