
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ej = {'_': ['ej_montagu-stuart-wortley',
       'ej_ruggles-brise',
       'ej_saunderson',
       'ej_henderson',
       'ej_connellan',
       'ej_underwood',
       'ej_williams',
       'ej_korvette',
       'ej_harrison',
       'ej,_sudbino',
       'ej_scovell',
       'ej_stewart',
       'ej_whitley',
       'ej_poynter',
       'ej_whitten',
       'ej_johnson',
       'ej_biggers',
       'ej_bellocq',
       'ej_montini',
       'ej_dimera',
       'ej_pipkin',
       'ej_junior',
       'ej_hughes',
       'ej_manuel',
       'ej_conway',
       'ej_lonnen',
       'ej_dionne',
       'ej_thribb',
       'ej_cassel',
       'ej_lennox',
       'ej_laure',
       'ej_mccoy',
       'ej_wells',
       'ej_brill',
       'ej_bowen',
       'ej_feihl',
       'ej_brady',
       'ej_corey',
       'ej_jones',
       'ej_holub',
       'ej_pratt',
       'ej_josey',
       'ej_viso',
       'ej_burt',
       'ej_reed',
       'ej_hill',
       'ej_gold',
       'ej_onu',
       'ej_200',
       'ej_su'],
 'a': ['ejaculatory_incompetence',
       'ejaculatory_dysfunction',
       'ejaculation_disorders',
       'ejaculatio_praecox',
       'ejaculatory_prayer',
       'ejagga_pakkpekatt',
       'ejaculatory_ducts',
       'ejaculatory_fluid',
       'ejagayehu_dibaba',
       'ejaculatory_duct',
       'ejaz_lakdawala',
       'ejaz_chaudhary',
       'ejajul_islam',
       'ejaz_durrani',
       'ejan_mackaay',
       'ejan,_ghana',
       'ejay_falcon',
       'ejaz_yousaf',
       'ejaz,_idlib',
       'ejaz_qaiser',
       'ejaz_khan',
       'ejaz_ali',
       'ejay_day'],
 'b': ['ejby_municipality',
       'ejby_municipal',
       'ejb_container',
       'ejb_engine',
       'ejbar_kola',
       'ejb_allen',
       'ejb_womb',
       'ejb_ql'],
 'e': ['ejective-contour_click',
       'ejercicio_cotidiano',
       'ejercito_trigarante',
       'ejective_consonants',
       'ejective_fricative',
       'ejective_consonant',
       'ejercito_argentino',
       'ejection_fraction',
       'ejection_systems',
       'eje_neovolcanico',
       'ejegayehu_dibaba',
       'ejector_venturi',
       'ejection_system',
       'ejercito_family',
       'ejercito_grande',
       'ejection_charge',
       'ejegod_windmill',
       'ejecta_blanket',
       'ejection_seats',
       'ejective_click',
       'ejei_khongghor',
       'ejection_seat',
       'ejective_stop',
       'ejer_bavnehoj',
       'ejector_seats',
       'ejector_pump',
       'eje_comunero',
       'ejector_rack',
       'ejector_seat',
       'eje_cafetero',
       'eje_central',
       'ejersa_goro',
       'eje_thelin',
       'ejembi_eko',
       'ejei_khan',
       'eje_oberg',
       'ejen_ali',
       'eje_elgh',
       'ejen_016',
       'eje_vial'],
 'g': ['ejgil_clemmensen', 'ejgayehu_taye', 'ejg_pitman'],
 'h': ['ejhl_south', 'ejh_corner'],
 'i': ['ejisu-juaben_district',
       'ejima-ikushima_affair',
       'ejinhoro_formation',
       'ejin-hami_railway',
       'ejido,_venezuela',
       'ejikeme_ikwunze',
       'ejido_erendira',
       'ejike_uzoenyi',
       'ejigbo,_lagos',
       'ejike_ugboaja',
       'ejiri_station',
       'ejima_station',
       'ejike_asiegbu',
       'ejido_valdez',
       'ejiro_kuale',
       'eji_komatsu',
       'ejiro_evero',
       'ejin_banner',
       'ejin_river',
       'ejin_horo'],
 'l': ['ejler_jakobsson',
       'ejlif_krogager',
       'ejlert_bjerke',
       'ejler_allert',
       'ejler_bille',
       'ejler_holm'],
 'n': ['ejnar_utzon-frank',
       'ejnar_hertzsprung',
       'ejner_federspiel',
       'ejnar_federspiel',
       'ejnar_mikkelsen',
       'ejner_johansson',
       'ejnar_tonsager',
       'ejnor_johanson',
       'ejnar_andersen',
       'ejner_augsburg',
       'ejnar_jacobsen',
       'ejnar_knudsen',
       'ejnar_levison',
       'ejnar_sylvest',
       'ejnar_fischer',
       'ejnar_nielsen',
       'ejnar_olsson',
       'ejner_hansen',
       'ejnar_jensen',
       'ejnar_dyggve',
       'ejnar_hansen',
       'ejner_jensen',
       'ejnar_emborg',
       'ejner_larsen'],
 'o': ['ejovi_nuwere'],
 's': ['ejszakai_orszagut'],
 'u': ['ejutla,_jalisco',
       'ejusdem_generis',
       'ejutla_district',
       'ejura_shooting',
       'ejuan_price',
       'ejup_ganic'],
 'v': ['ejvind_pedersen', 'ejvind_hansen', 'ejvind_blach'],
 'y': ['ejya_yadav']}
