
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_nt = {'_': ['nt_legislative_assembly',
       'nt_directory_service',
       'nt_cluster_server',
       'nt_gundam_cover',
       'nt_file_system',
       'nt_lan_manager',
       'nt_rama_rao'],
 'a': ['ntabankulu_local_municipality',
       'ntambanana_local_municipality',
       'ntangki_national_park',
       'ntaria_ladies_choir',
       'ntate_daniel_kgwadi',
       'ntare_iii_rushatsi',
       'ntare_iv_rugamba',
       'nta_film_network',
       'ntare_v_ndizeye'],
 'c': ['ntc_dunajska_luzna'],
 'e': ['ntebogang_secondary_school'],
 'f': ['ntf_football_awards',
       'ntfombi_of_eswatini',
       'ntfs_junction_point',
       'ntfs_reparse_point',
       'ntfs_symbolic_link',
       'ntfs_file_system'],
 'h': ['nth_country_experiment',
       'nth_derivative_test',
       'nth_root_algorithm',
       'nth_term_test',
       'nth_room_case'],
 'k': ['ntk-62_machine_gun'],
 'l': ['ntlo_ya_dikgosi'],
 'n': ['ntnu_university_museum'],
 'o': ['ntombikayise_priscilla_khubeka',
       'ntokou-pikounda_national_park',
       'ntombi_lentheng_mekgwe',
       'ntombi_of_swaziland'],
 'p': ['ntp_binding_site'],
 'r': ['ntr_national_award', 'ntr:_netsuzou_trap', 'ntr_bus_station'],
 's': ['ntshingwayo_kamahole_khoza',
       'ntsikeni_wildlife_reserve',
       'nts_sessions_1-4',
       'ntsc_color_bars',
       'ntsu_mean_green',
       'ntsc_time_code'],
 't': ['ntt_communications_corporation',
       'ntt_intercommunication_center',
       'ntt_mobile_communications',
       'ntt_communications_corp',
       'ntt_data_corporation',
       'ntt_publishing_co.',
       'ntt_resonant_inc.',
       'ntt_europe_online',
       'ntt_publishing_co',
       'ntt_docomo_inc',
       'ntt_docomo_usa'],
 'u': ['ntuc_fairprice_co-operative',
       'ntungamo-mirama_hills_road',
       'ntu_hospital_station',
       'ntuc_downtown_east',
       'ntu_rgb-d_dataset',
       'ntu_music_express',
       'ntuli_v_donald',
       'ntu_la_pass'],
 'v': ['ntv_plus_sports', 'ntv_plus_sport'],
 'w': ['ntw-20_antimaterial_rifle', 'ntwenhle_high_school']}
