
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_cw = {'_': ['cw_thamotharampillai',
       'cw_brudenell-bruce',
       'cw_illumination',
       'cw_illuminator',
       'cw_pittsburgh',
       'cw-27_caravan',
       'cw_sacramento',
       'cw_cincinnati',
       'cw_beresford',
       'cw_armstrong',
       'cw_stoneking',
       'cw_complexes',
       'cw_woodworth',
       'cw_cleveland',
       'cw_jeffreys',
       'cw-21_demon',
       'cw_anderson',
       'cw_network',
       'cw_phoenix',
       'cw_skimmer',
       'cw_seattle',
       'cw_complex',
       'cw_grafton',
       'cw_orlando',
       'cw_detroit',
       'cw_jeffrey',
       'cw_atlanta',
       'cw_daytime',
       'cw_number',
       'cw_mccall',
       'cw_alcock',
       'cw_bishop',
       'cw-1_visa',
       'cw_leonis',
       'cw_denver',
       'cw_jensen',
       'cw_melson',
       'cw_stubbs',
       'cw_philly',
       'cw_bangs',
       'cw_nicol',
       'cw_ceram',
       'cw_mars',
       'cw_plus',
       'cw_belt',
       'cw_dohm',
       'cw_pair',
       'cw_post',
       'cw_now',
       'cw_50',
       'cw_13',
       'cw_57',
       'cw_11',
       'cw_14',
       'cw_56',
       'cw_33',
       'cw_44',
       'cw_5',
       'cw_2',
       'cw_9',
       'cw_6'],
 'a': ['cwaliny_duze', 'cwaliny_male', 'cwanzit_hut'],
 'c': ['cwc_turner', 'cwc_alumni', 'cwc_group', 'cwc_2007', 'cwc_mode'],
 'e': ['cwengile_jadezweni', 'cwen_language'],
 'f': ['cwf_mid-atlantic'],
 'i': ['cwi/wipa_awards'],
 'k': ['cwks_resovia'],
 'l': ['cwl_wz.x', 'cwl_wz-x'],
 'm': ['cwmbach,_carmarthenshire',
       'cwm,_denbighshire',
       'cwmorthin_tramway',
       'cwmavon,_torfaen',
       'cwmystwyth_mines',
       'cwmorthin_quarry',
       'cwmbran_central',
       'cwmbran_stadium',
       'cwm,_llanrothal',
       'cwmllynfell_rfc',
       'cwmfelin_mynach',
       'cwmdonkin_park',
       'cwmbran_centre',
       'cwmdu,_swansea',
       'cwmyoy_church',
       'cwmgwrach_rfc',
       'cwmythig_hill',
       'cwm_penmachno',
       'cwmbran_town',
       'cwmtwrch_rfc',
       'cwmdu,_powys',
       'cwmhir_abbey',
       'cwmbran_rfc',
       'cwm_silicon',
       'cwm_rhondda',
       'cwmgors_rfc',
       'cwm_nantcol',
       'cwm_clydach',
       'cwm_cadnant',
       'cwmavon_rfc',
       'cwm_ystwyth',
       'cwm_cyffog',
       'cwm_cadlan',
       'cwm_hengae',
       'cwm_gwaun',
       'cwm_twrch',
       'cwm_idwal',
       'cwm_caseg',
       'cwm_talwg',
       'cwm_ogwr',
       'cwm_dyli',
       'cwm_head',
       'cwm_dewi',
       'cwm_glo',
       'cwm_cau',
       'cwm_fx'],
 'n': ['cwn_annwn'],
 'o': ['cwow_gallery'],
 'p': ['cwp_renewables'],
 'r': ['cwrtmawr_manuscripts', 'cwrt_herbert'],
 's': ['cws_t-1', 'cws_uk'],
 'w': ['cww_kannangara']}
