
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_ym = {'ym-2149': 'general_instrument_ay-3-8910',
 'ym-490f': 'yongmei_ym-490f',
 'ym-ywha': 'jewish_community_center',
 'ym2149': 'general_instrument_ay-3-8910',
 'ym2151': 'yamaha_ym2151',
 'ym2413': 'yamaha_ym2413',
 'ym2612': 'yamaha_ym2612',
 'ym3812': 'yamaha_ym3812',
 'ymaa': 'yerba_mate_association_of_the_americas',
 'ymai': 'umai',
 'ymatch': 'y-str',
 'ymax': 'wimax',
 'ymay': 'albury_airport',
 'ymci': 'york_mills_collegiate_institute',
 'ymdf': 'changing_rooms',
 'ymdg': 'mudgee_airport',
 'ymen': 'essendon_airport',
 'ymer': 'ymir',
 'ymf262': 'yamaha_ymf262',
 'ymf7xx': 'yamaha_ymf7xx',
 'ymfc': 'yorkshire_main_f.c.',
 'ymha': 'jewish_community_center',
 'ymic': 'young_medics_international_conference',
 'ymitos': 'ymittos',
 'ymmb': 'moorabbin_airport',
 'ymml': 'melbourne_airport',
 'ymndt': 'ytmnd',
 'ymodem-1k': 'ymodem',
 'ymodem-g': 'ymodem',
 'ymoh.s': 'hitoshi_sakimoto',
 'ymoja': 'yemaja',
 'ympc': 'young_moro_professionals_council',
 'ympe': 'imp',
 'ympn': 'young_moro_professionals_network',
 'ymq-18a': 'boeing_a160_hummingbird',
 'ymrf': 'yngwie_malmsteen',
 'ymrs': 'young_mania_rating_scale',
 'yms-1-class': 'yms-1_class_minesweeper',
 'ymsb': 'yonder_mountain_string_band',
 'ymss': 'youthmovies',
 'ymsticpc': 'house_of_cards',
 'ymtuk': 'youth_music_theatre:_uk',
 'ymuiden': 'ijmuiden',
 'ymuk': 'the_young_muslims_uk'}
        