
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_ej = {'ej-200': 'eurojet_ej200',
 'ej11': 'jordan_ej11',
 'ej12': 'jordan_ej12',
 'ej13': 'jordan_ej13',
 'ej14': 'jordan_ej14',
 'ej15': 'jordan_ej15',
 'ej15b': 'jordan_ej15',
 'ej16': 'cd59',
 'ej20': 'subaru_ej_engine',
 'ej200': 'eurojet_ej200',
 'ej22': 'subaru_ej_engine',
 'ej22t': 'subaru_ej_engine',
 'ej257': 'subaru_ej_engine',
 'ej30': 'cd59',
 'ejaculate': 'ejaculation',
 'ejaculated': 'ejaculation',
 'ejaculates': 'ejaculation',
 'ejaculating': 'ejaculation',
 'ejaculations': 'ejaculation',
 'ejagham': 'ekoi',
 'ejamaan': 'yejaman',
 'ejambment': 'enjambment',
 'ejcf': 'european_festival_of_youth_choirs',
 'ejea': 'ejea_de_los_caballeros',
 'eject': 'ejection',
 'ejected': 'ejection',
 'ejecting': 'ejection',
 'ejectisomes': 'cryptomonad',
 'ejective': 'ejective_consonant',
 'ejectives': 'ejective_consonant',
 'ejector': 'injector',
 'ejectorseat': 'ejection_seat',
 'ejectosomes': 'ejectosome',
 'ejerkulation': 'ejaculation',
 'ejhg': 'european_journal_of_human_genetics',
 'ejhl': 'eastern_junior_hockey_league',
 'ejidatorio': 'ejido',
 'ejin': 'ejin_river',
 'ejipt': 'egypt',
 'ejisu': 'ejisu-juaben_municipal_district',
 'ejji': 'panzer_dragoon',
 'ejjp': 'european_jews_for_a_just_peace',
 'ejmt': 'eisenhower_tunnel',
 'ejnstejno': 'albert_einstein',
 'ejtc': 'eliza_taylor-cotter',
 'ejustine': 'justine_ezarik'}
        