#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# AUTO-GENERATED CONTENT
d_stem_ds = {'dsa': {'dsas': []},
 'dsacryptoserviceprovid': {'dsacryptoserviceprovider': []},
 'dsana': {'dsanas': []},
 'dsap': {'dsaps': []},
 'dsaparam': {'dsaparams': []},
 'dsat': {'dsats': []},
 'dsava': {'dsavas': []},
 'dsb': {'dsbs': []},
 'dsbat': {'dsbats': []},
 'dsberein': {'dsbereiner': []},
 'dsborn': {'dsborne': []},
 'dsbri': {'dsbris': []},
 'dsbt': {'dsbts': []},
 'dsbut': {'dsbuts': []},
 'dsbutant': {'dsbutante': []},
 'dsc': {'dscs': []},
 'dscape': {'dscapes': []},
 'dscb': {'dscbs': []},
 'dscend': {'dscended': []},
 'dscendant': {'dscendants': []},
 'dschagganeg': {'dschagganeger': []},
 'dscharg': {'dscharge': ['dscharged']},
 'dscharge': ['dscharged'],
 'dschingi': {'dschingis': []},
 'dschofein': {'dschofeine': []},
 'dschungel': {'dschungels': []},
 'dschunkowski': {'dschunkowsky': []},
 'dscide': {'dscided': []},
 'dscipl': {'dsciples': []},
 'dsciplin': {'dscipline': []},
 'dscision': {'dscisions': []},
 'dsclare': {'dsclared': []},
 'dscore': {'dscores': []},
 'dscouvert': {'dscouverte': ['dscouvertes']},
 'dscouverte': ['dscouvertes'],
 'dscover': {'dscovered': []},
 'dscoveri': {'dscovery': []},
 'dscp': {'dscps': []},
 'dscq': {'dscqs': []},
 'dscr': {'dscrs': []},
 'dscribe': {'dscribed': [], 'dscribes': [], 'dscribing': []},
 'dscrimin': {'dscrimination': []},
 'dscuss': {'dscussed': []},
 'dscussion': {'dscussions': []},
 'dscustom': {'dscustomers': []},
 'dsd': {'dsds': []},
 'dsdalu': {'dsdalus': []},
 'dsdna': {'dsdnas': []},
 'dse': {'ds': []},
 'dseas': {'dsease': ['dseases']},
 'dsease': ['dseases'],
 'dsecrib': {'dsecribed': []},
 'dsecript': {'dsecription': []},
 'dsect': {'dsects': []},
 'dsectori': {'dsectory': []},
 'dsed': {'dseds': []},
 'dsedalo': {'dsedalos': []},
 'dsedalu': {'dsedalus': []},
 'dsege': {'dseges': []},
 'dseme': {'dsemed': []},
 'dsemon': {'dsemone': ['dsemones'],
            'dsemonic': [],
            'dsemonism': [],
            'dsemons': []},
 'dsemone': ['dsemones'],
 'dsemoni': {'dsemonis': []},
 'dsemoniac': {'dsemoniacal': [], 'dsemoniacs': []},
 'dsemonian': {'dsemonians': []},
 'dsemonibu': {'dsemonibus': []},
 'dsemonolog': {'dsemonology': []},
 'dsemonologi': {'dsemonologie': []},
 'dsemploye': {'dsemployees': []},
 'dsep': {'dseps': []},
 'dsepar': {'dseparation': []},
 'dsepli': {'dseply': []},
 'dseri': {'dseries': []},
 'dserin': {'dserine': []},
 'dsesiu': {'dsesius': []},
 'dset': {'dsettings': []},
 'dseva': {'dsevas': []},
 'dsf': {'dsfs': []},
 'dsfenc': {'dsfence': []},
 'dsfens': {'dsfense': []},
 'dsfine': {'dsfined': []},
 'dsfinit': {'dsfinition': []},
 'dsg': {'dsgs': []},
 'dsgree': {'dsgrees': []},
 'dsh': {'dshs': []},
 'dshape': {'dshaped': []},
 'dshe': {'dshes': []},
 'dship': {'dships': []},
 'dshk': {'dshks': []},
 'dshrama': {'dshramas': []},
 'dsi': {'dsis': [], 'dsy': ['dsys']},
 'dsiciplin': {'dsicipline': []},
 'dsicov': {'dsicovered': []},
 'dsicuss': {'dsicussed': [], 'dsicussion': []},
 'dsign': {'dsigned': [], 'dsigning': [], 'dsigns': []},
 'dsignat': {'dsignated': []},
 'dsignific': {'dsignificant': []},
 'dsignificantli': {'dsignificantly': []},
 'dsili': {'dsily': []},
 'dsim': {'dsims': []},
 'dsirabl': {'dsirable': []},
 'dsire': {'dsired': []},
 'dsitanc': {'dsitance': []},
 'dsiti': {'dsity': []},
 'dsitiv': {'dsitive': []},
 'dsitribut': {'dsitribution': []},
 'dsitrict': {'dsitricts': []},
 'dsiy': {'dsiys': []},
 'dsjini': {'dsjiny': []},
 'dsk': {'dsks': []},
 'dski': {'dsky': []},
 'dsl': {'dsl': []},
 'dslam': {'dslams': []},
 'dslr': {'dslrs': []},
 'dsm': {'dsms': []},
 'dsmand': {'dsmands': []},
 'dsmb': {'dsmbs': []},
 'dsmerg': {'dsmerge': []},
 'dsmocrati': {'dsmocratie': []},
 'dsmocratiqu': {'dsmocratique': []},
 'dsn': {'dsns': []},
 'dsngerou': {'dsngerous': []},
 'dsni': {'dsnied': [], 'dsny': []},
 'dsnsiti': {'dsnsity': []},
 'dso': {'dsos': []},
 'dsolv': {'dsolve': []},
 'dsorder': {'dsorders': []},
 'dsourc': {'dsource': []},
 'dsp': {'dsps': []},
 'dspace': {'dspacing': ['dspacings']},
 'dspacing': ['dspacings'],
 'dspartement': {'dspartements': []},
 'dspbase': {'dspbased': []},
 'dspech': {'dspeche': []},
 'dspend': {'dspends': []},
 'dsph': {'dsphs': []},
 'dsplay': {'dsplayed': []},
 'dspli': {'dsply': []},
 'dspn': {'dspns': []},
 'dsposit': {'dsposits': []},
 'dsproduct': {'dsproducts': []},
 'dsputi': {'dsputy': []},
 'dsqueri': {'dsquery': []},
 'dsr': {'dsrs': []},
 'dsrama': {'dsramas': []},
 'dsrava': {'dsravas': []},
 'dsri': {'dsris': []},
 'dsrive': {'dsrived': []},
 'dsrna': {'dsrnas': []},
 'dsrnabind': {'dsrnabinding': []},
 'dsrnadepend': {'dsrnadependent': []},
 'dsrv': {'dsrvs': []},
 'dssc': {'dsscs': []},
 'dsschylu': {'dsschylus': []},
 'dsscribe': {'dsscribed': []},
 'dssibil': {'dssibility': []},
 'dssibl': {'dssible': []},
 'dssign': {'dssigned': []},
 'dssire': {'dssired': []},
 'dsstroy': {'dsstroyed': []},
 'dssue': {'dssues': []},
 'dst': {'dsts': []},
 'dstail': {'dstailed': [], 'dstails': []},
 'dstanc': {'dstance': []},
 'dstate': {'dstates': []},
 'dstd': {'dstds': []},
 'dste': {'dstes': []},
 'dstect': {'dstected': []},
 'dstenc': {'dstence': []},
 'dstent': {'dstente': []},
 'dstermin': {'dstermination': [],
              'dstermine': ['dstermined'],
              'dstermining': []},
 'dstermine': ['dstermined'],
 'dsterreich': {'dsterreichs': []},
 'dsterreichisch': {'dsterreichische': ['dsterreichisches',
                                        'dsterreichischer']},
 'dsterreichische': ['dsterreichisches', 'dsterreichischer'],
 'dsthetisch': {'dsthetische': ['dsthetischer']},
 'dsthetische': ['dsthetischer'],
 'dsti': {'dsty': []},
 'dstinguish': {'dstinguished': []},
 'dstlich': {'dstliche': []},
 'dstori': {'dstory': []},
 'dstra': {'dstras': []},
 'dstribut': {'dstributed': [], 'dstribution': []},
 'dstrict': {'dstricts': []},
 'dstroy': {'dstroyed': []},
 'dstructur': {'dstructure': ['dstructures']},
 'dstructure': ['dstructures'],
 'dstuff': {'dstuffs': []},
 'dsu': {'dsus': []},
 'dsungar': {'dsungars': []},
 'dsungaripteru': {'dsungaripterus': []},
 'dsv': {'dsvs': []},
 'dsvelop': {'dsveloped': [], 'dsvelopment': []},
 'dsvelopp': {'dsveloppement': []},
 'dsvi': {'dsvies': [], 'dsvis': []},
 'dsvote': {'dsvoted': []},
 'dsw': {'dsws': []},
 'dsy': ['dsys'],
 'dsycholog': {'dsychological': [], 'dsychology': []},
 'dsyfunct': {'dsyfunction': ['dsyfunctions', 'dsyfunctional']},
 'dsyfunction': ['dsyfunctions', 'dsyfunctional']}
