#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# AUTO-GENERATED CONTENT
d_stem_uj = {'uja': {'ujae': [], 'ujas': []},
             'ujafeder': {'ujafederation': []},
             'ujal': {'ujale': [], 'ujall': []},
             'ujam': {'ujames': []},
             'ujanirtu': {'ujanirtus': []},
             'ujarra': {'ujarras': []},
             'ujat': {'ujater': []},
             'ujawnieni': {'ujawnienie': []},
             'ujazdowski': {'ujazdowskie': []},
             'uje': {'ujed': [], 'ujeful': [], 'ujes': [], 'ujing': []},
             'ujeci': {'ujecie': []},
             'ujedinjen': {'ujedinjene': []},
             'ujedinjenj': {'ujedinjenje': []},
             'ujemn': {'ujemne': []},
             'ujemni': {'ujemnie': [], 'ujemny': []},
             'ujer': {'ujere': []},
             'ujet': {'ujete': []},
             'ujev': {'ujevic': []},
             'ujevn': {'ujevne': []},
             'ujfalussi': {'ujfalussy': []},
             'ujfalvi': {'ujfalvy': []},
             'ujh': {'ujhely': []},
             'ujhazi': {'ujhazy': []},
             'ujhi': {'ujhy': []},
             'ujhit': {'ujhite': []},
             'uji': {'ujie': [], 'ujy': []},
             'ujid': {'ujider': []},
             'ujii': {'ujiie': []},
             'ujiit': {'ujiited': []},
             'ujiiy': {'ujiiye': []},
             'ujijian': {'ujijians': []},
             'ujik': {'ujike': []},
             'ujil': {'ujill': []},
             'ujir': {'ujire': []},
             'ujizan': {'ujizane': []},
             'ujjay': {'ujjayant': []},
             'ujl': {'ujle': []},
             'ujlaki': {'ujlaky': []},
             'ujlipotvaro': {'ujlipotvaros': []},
             'ujnfortun': {'ujnfortunately': []},
             'ujnlik': {'ujnlike': []},
             'ujnol': {'ujnoles': []},
             'ujo': {'ujos': []},
             'ujoint': {'ujoints': []},
             'ujord': {'ujords': []},
             'ujr': {'ujre': []},
             'ujratermel': {'ujratermeles': []},
             'ujs': {'ujsed': []},
             'ujsci': {'ujscie': []},
             'ujszaszi': {'ujszaszy': []},
             'ujszeg': {'ujszeged': []},
             'ujt': {'ujts': []},
             'uju': {'ujue': [], 'ujus': []},
             'ujual': {'ujually': []},
             'ujuli': {'ujuly': []},
             'ujvari': {'ujvary': []},
             'ujvaro': {'ujvaros': []},
             'ujyss': {'ujysses': []}}
