
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_zm = {'_': ['zm_christchurch',
       'zm_wellington',
       'zm_whangarei',
       'zm_auckland',
       'zm_waikato',
       'zm_weapons'],
 'a': ['zmaj_defilipis',
       'zmajski_bridge',
       'zmago_sagadin',
       'zman_tel-aviv',
       'zmaj_aircraft',
       'zmajski_most',
       'zman_switch',
       'zman_games',
       'zmaj_r-1'],
 'd': ['zmd_america'],
 'e': ['zmeinogorsky_district',
       'zmena-bate_minsk',
       'zmei_gorynych',
       'zmey_gorynych',
       'zmei_gorinich',
       'zmei_gorynich',
       'zmena_minsk',
       'zmeevo_pass',
       'zmena_zdola'],
 'i': ['zmijowek_wloscianski',
       'zmitser_zhylunovich',
       'zmicier_zhylunovich',
       'zmijanje_embroidery',
       'zmitser_dashkevich',
       'zmicier_sidarovic',
       'zmijewo_koscielne',
       'zmievskaya_balka',
       'zmitrok_biadula',
       'zmiy_gorynych',
       'zminec,_finiq',
       'zmija_facula',
       'zmiiv_raion',
       'zmija_group',
       'zmiev_uyezd',
       'zmicier_i'],
 'o': ['zmozna_wola'],
 'p': ['zmp_inc.'],
 'u': ['zmuidzinavicius_museum',
       'zmutt_glacier',
       'zmutt_valley',
       'zmulner_see'],
 'w': ['zmw_attack'],
 'y': ['zmyslona_parzynowska', 'zmyslona_ligocka', 'zmyslona_slupska'],
 'z': ['zmz_24']}
