
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ii = {'_': ['ii-v-i', 'ii25,1', 'ii-mef', 'ii-vi'],
 'a': ['iiate', 'iiasa', 'iias', 'iiaf', 'iiac', 'iiap', 'iiab', 'iia'],
 'b': ['iib-iiia', 'iiba', 'iib'],
 'c': ["iich'aa", 'iicons', 'iichan', 'iict', 'iicd', 'iici', 'iica', 'iic'],
 'd': ['iidesjarvi',
       'iidabashi',
       'iidabasi',
       'iidagale',
       'iidxred',
       'iidcya',
       'iides',
       'iide',
       'iidb',
       'iidx',
       'iida',
       'iid'],
 'e': ['iiebm', 'iiest', 'iied', 'iies', 'iie'],
 'f': ['iifso', 'iifm', 'iift', 'iifa', 'iif'],
 'g': ['iigaste', 'iig'],
 'h': ['iihipaa',
       'iihito.',
       'iihongo',
       'iihito',
       'iihsa',
       'iihl',
       'iihs',
       'iihf',
       'iih'],
 'i': ['iiidrops',
       'iii-mef',
       'iiit-b',
       'iii/iv',
       'iiiee',
       'iiimf',
       'iiis',
       'iiit',
       'iiie',
       'iiii',
       'iii'],
 'j': ['iijarvi', 'iijima', 'iijoki', 'iiji', 'iij'],
 'l': ['iilaste', 'iilwy', 'iileh', 'iilm', 'iilp', 'iila', 'iil'],
 'm': ['iimura', 'iimk', 'iims', 'iimb', 'iimc', 'iimn', 'iima', 'iimi'],
 'n': ['iinetphone',
       'iinijarvi',
       'iintersex',
       'iinoya-gu',
       'iindman',
       'iinuma',
       'iinet',
       'iino',
       'iine',
       'iina',
       'iin'],
 'o': ['iiolonioro', 'iiop', 'iiod', 'iio'],
 'p': ['iiphone', 'iipa', 'iip3', 'iipm', 'iipb', 'iipf', 'iip'],
 'r': ['iiraira',
       'iirira',
       'iirsa',
       'iiris',
       'iirhb',
       'iiroc',
       'iire',
       'iirs',
       'iira',
       'iirc',
       'iiro',
       'iir'],
 's': ['iiser-tvm',
       'iisvesi',
       'iisalmi',
       'iislam',
       'iiswbm',
       'iisaku',
       'iishp',
       'iisef',
       'iisdc',
       'iiser',
       'iisna',
       'iisc',
       'iisj',
       'iiss',
       'iism',
       'iisp',
       'iisg',
       'iisu',
       'iisr',
       'iisd',
       'iisi',
       'iis'],
 't': ['iit-hyderabad',
       'iit-jee',
       'iittala',
       'iitbbsr',
       'iitian',
       'iitjee',
       'iitran',
       'iitbbs',
       'iitoyo',
       'iitkgp',
       'iitii',
       'iitti',
       'iit-b',
       'iitbn',
       'iitm',
       'iitr',
       'iitb',
       'iitt',
       'iitk',
       'iitd',
       'iitg',
       'iita',
       'iitf',
       'iitp',
       'iits'],
 'u': ['iiuni', 'iium', 'iiug', 'iiuc', 'iiu'],
 'v': ['iivananlinna', 'iivantiira', 'iivari', 'iiv'],
 'w': ['iiwusynth', 'iiwf', 'iiww', 'iiw'],
 'x': ['iix'],
 'z': ['iizuna', 'iizumi', 'iizaka']}
