
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_ij = {'_': ['ij3', 'ij2', 'ij4'],
 'a': ['ijaz-ur-rehman',
       'ijaz-ul-haq',
       'ijamsville',
       'ijara-isin',
       'ijatkotcs',
       'ijatrotla',
       'ijatkotks',
       'ijanikin',
       'ijacking',
       'ijagiri',
       'ijahman',
       'ijaazat',
       'ijangui',
       'ijaiye',
       'ijatod',
       'ijames',
       'ijarah',
       'ijazah',
       'ijatlc',
       'ijagbe',
       'ijaza',
       'ijamt',
       'ijaaf',
       'ijare',
       'ijaci',
       'ijams',
       'ijang',
       'ijaka',
       'ijaas',
       'ijani',
       'ijara',
       'ijaw',
       'ijas',
       'ijal',
       'ijaf',
       'ija'],
 'b': ['ijburg', 'ijb'],
 'c': ['ijcmpilsh', 'ijcbdd', 'ijcai', 'ijcbs', 'ijcar', 'ijcc', 'ijc'],
 'd': ['ijdileni', 'ijdanak', 'ijdan', 'ijdb'],
 'e': ['ijermaouas',
       'ijebu-jesa',
       'ije-abarim',
       'ijebu-ode',
       'ijemskii',
       'ijemskiy',
       'ijemsky',
       'ijemski',
       'ijegun',
       'ijevan',
       'ijebus',
       'ijevsk',
       'ijesha',
       'ijegu',
       'ijeri',
       'ijebu',
       'ijede',
       'ijet',
       'ijen',
       'ije'],
 'f': ['ijfipm', 'ijf'],
 'g': ['ijgeul', 'ijg'],
 'h': ['ijhorst', 'ijhss', 'ijhs', 'ijhl'],
 'i': ['ijimaia', 'ijinasi', 'ijichi', 'ijiraq', 'ijime', 'iji'],
 'j': ['ijjuriktuq', 'ijjodu', 'ijji'],
 'k': ['ijkdijk', 'ijkl', 'ijk'],
 'l': ['ijlst', 'ijl'],
 'm': ['ijmuiden', 'ijmeer', 'ijmms', 'ijms', 'ijm'],
 'n': ['ijnisinya', 'ijnetwork', 'ijnas', 'ijn'],
 'o': ['ijoukak', 'ijolite', 'ijombe', 'ijoca', 'ijoko', 'ijok', 'ijoe', 'ijo'],
 'p': ['ijpor', 'ijpl', 'ijp'],
 'r': ['ijrahwa', 'ijrud'],
 's': ['ijsselmeervogels',
       'ijsselmuiden',
       'ijsselhallen',
       'ijsselmonde',
       'ijsselderby',
       'ijsbrechtum',
       'ijsselstein',
       'ijsselmeer',
       'ijseelmeer',
       'ijsselham',
       'ijsseloog',
       'ijselmeer',
       'ijsbrand',
       'ijscolf',
       'ijsland',
       'ijssel',
       'ijstd',
       'ijsem',
       'ijsi',
       'ijsa',
       'ijsb',
       'ijso',
       'ijs'],
 't': ['ijtihadists',
       'ijtihadism',
       'ijtihadi',
       'ijtunnel',
       'ijtihaad',
       'ijtehad',
       'ijtihad',
       'ijtema',
       'ijthad',
       'ijtram',
       'ijti',
       'ijt'],
 'u': ['ijustwanttobecool',
       'ijuander',
       'ijustine',
       'ijuhya',
       'ijumu',
       'ijuh',
       'ijun',
       'ijui',
       'ijuw',
       'iju'],
 'v': ['ijvm', 'ijv'],
 'w': ['ijwin'],
 'z': ['ijzerbedevaart',
       'ijzerkoekje',
       'ijzendoorn',
       'ijzendijke',
       'ijzevoorde',
       'ijzerwake',
       'ijzerlo',
       'ijzim',
       'ijzer']}
