
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_lm = {'_': ['lm-sensors',
       'lm13600',
       'lm3labs',
       'lm-2500',
       'lm13700',
       'lm22a-4',
       'lm3875',
       'lm-68m',
       'lm2500',
       'lm3914',
       'lm-700',
       'lm337',
       'lm-49',
       'lm-33',
       'lm317',
       'lm386',
       'lm-57',
       'lm358',
       'lm002',
       'lm741',
       'lm747',
       'lm-68',
       'lm.c',
       'lm-5',
       'lm-1',
       'lm19',
       'lm/w',
       'lm3'],
 'a': ['lmab-group',
       'lmatts',
       'lmatx5',
       'lmatx3',
       'lman2l',
       'lman1',
       'lman2',
       'lmac',
       'lmao',
       'lmag',
       'lmap',
       'lma'],
 'b': ['lmbatavank',
       'lmbrd1',
       'lmbr1l',
       'lmbr1',
       'lmbbs',
       'lmbc',
       'lmbo',
       'lmb'],
 'c': ['lmc195-1', 'lmctfy', 'lmcss', 'lmcc', 'lmca', 'lmcs', 'lmco', 'lmc'],
 'd': ['lmdc', 'lmde', 'lmdh', 'lmds', 'lmdp', 'lmd'],
 'e': ['lmechrek', 'lmems', 'lmes', 'lme'],
 'f': ['lmfbao', 'lmfao', 'lmfbr', 'lmft', 'lmfm', 'lmfr', 'lmf'],
 'g': ['lmgtfy', 'lmgtp', 'lmga', 'lmg'],
 'h': ['lmhosts.sam', 'lmhosts', 'lmhc', 'lmhs', 'lmhr', 'lmh'],
 'i': ['lmisd', 'lmia', 'lmi'],
 'k': ['lmkr', 'lmk'],
 'l': ['lmlyp', 'lmlk', 'lmln', 'lml'],
 'm': ['lmmfao', 'lmmse', 'lmmag', 'lmms', 'lmmm', 'lmmr', 'lmml', 'lmm'],
 'n': ['lmnop', 'lmnb2', 'lmnt', 'lmno', 'lmna', 'lmn'],
 'o': ['lmotp', 'lmod3', 'lmo4', 'lmo2', 'lmo7', 'lmos', 'lmo3', 'lmo1', 'lmo'],
 'p': ['lmp900',
       'lmp675',
       'lmp-1',
       'lmp-2',
       'lmptp',
       'lmpd',
       'lmp1',
       'lmp2',
       'lmpo',
       'lmp'],
 'r': ['lmrda', 'lmrs', 'lmr'],
 's': ['lms-9/19',
       'lms-usa',
       'lms-901',
       'lms100',
       'lmsncc',
       'lmsusa',
       'lmsio',
       'lmssc',
       'lmsi',
       'lmsr',
       'lmsw',
       'lmsc',
       'lmsd',
       'lms'],
 't': ['lmtsom', 'lmtk3', 'lmtk2', 'lmtv', 'lmta', 'lmtp', 'lmtd', 'lmt'],
 'u': ['lmule', 'lmu'],
 'v': ['lmvh', 'lmv'],
 'w': ['lmwh', 'lmw'],
 'x': ['lmx1b', 'lmx1a']}
