
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_mn = {'_': ['mn/road',
       'mn-244',
       'mn-210',
       'mn2400',
       'mn-280',
       'mn-sod',
       'mn-111',
       'mn/dot',
       'mn-28',
       'mn-60',
       'mn-26',
       'mn-27',
       'mn-55',
       'mn-25',
       'mn103',
       'mn-18',
       'mn2o7',
       'mn-32',
       'mn-99',
       'mn-76',
       'mn-40',
       'mn55',
       'mn-1',
       'mn12',
       'mn8',
       'mn1',
       'mn+'],
 'a': ['mnatsakanyan',
       'mnarolitia',
       'mnasitheus',
       'mnasagoras',
       'mnasinous',
       'mnasalcas',
       'mnasippus',
       'mnasicles',
       'mnase-seq',
       'mnasilus',
       'mnazinia',
       'mnarani',
       'mnadani',
       'mnaseas',
       'mnajdra',
       'mnasheh',
       'mnactec',
       'mnashe',
       'mnasra',
       'mnason',
       'mnandi',
       'mnais',
       'mnat1',
       'mnase',
       'mnata',
       'mnac',
       'mnaa',
       'mnan',
       'mna'],
 'b': ['mnbvcxz', 'mnbl', 'mnba', 'mnb'],
 'c': ['mnc-kalonji',
       'mncppc',
       'mncpa',
       'mnctv',
       'mnc-i',
       'mncs',
       'mncr',
       'mncf',
       'mncw',
       'mnc'],
 'd': ['mndsgn', 'mndot', 'mndaa', 'mndo', 'mndf', 'mndr', 'mnda', 'mnd'],
 'e': ['mnesarchaeoidea',
       'mnesarchaeidae',
       'mnemeiosaurus',
       'mnesarchella',
       'mnematidium',
       'mnesilochus',
       'mnesipenthe',
       'mnesarchaea',
       'mnesithetis',
       'mnesictena',
       'mnesimache',
       'mnemnosyne',
       'mnesistega',
       'mnesarchus',
       'mnemiopsis',
       'mnesitheus',
       'mnestiidae',
       'mnesampela',
       'mnemozina',
       'mnesithea',
       'mnesarete',
       'mnesiloba',
       'mnesileus',
       'mnesteria',
       'mnemonist',
       'mnemosyne',
       'mnematium',
       'mnesikles',
       'mnestheus',
       'mnemovore',
       'mnesicles',
       'mneumonic',
       'mnenomic',
       'mnesigea',
       'mnemonic',
       'mnemesis',
       'mnemoses',
       'mnestia',
       'mnester',
       'mnemata',
       'mnesia',
       'mnewer',
       'mnemic',
       'mnevis',
       'mnetes',
       'mnemba',
       'mnenia',
       'mnemea',
       'mnemon',
       'mneme',
       'mnek',
       'mnet',
       'mne'],
 'f': ['mnf-iraq', 'mnfpac', 'mnf-w', 'mnf-i', 'mnfi', 'mnf'],
 'g': ['mng-vlc', 'mnguni', 'mngie', 'mng'],
 'h': ['mnha', 'mnhm', 'mnhs', 'mnh'],
 'i': ['mniszow-kolonia',
       'mnich-poludnie',
       'mnin-przymusow',
       'mnin-blagodac',
       'mnich-osrodek',
       'mnin-szwedy',
       'mniarogekko',
       'mnin-mokre',
       'mnichovice',
       'mnichowice',
       'mniochloa',
       'mniopamea',
       'mniotilta',
       'mniotype',
       'mniaecia',
       'mniaceae',
       'mnisztwo',
       'mniszkow',
       'mniocera',
       'mniowice',
       'mnigolo',
       'mnichus',
       'mniszki',
       'mniszew',
       'mniszow',
       'mniodes',
       'mniszek',
       'mnichov',
       'mnierea',
       'mnichy',
       'mnizus',
       'mniusa',
       'mnikow',
       'mninga',
       'mniire',
       'mnikss',
       'mnisek',
       'mniewo',
       'mnium',
       'mnicc',
       'mnich',
       'mniow',
       'mniaa',
       'mnic',
       'mnij',
       'mnie',
       'mnip',
       'mnin',
       'mni'],
 'j': ['mnj'],
 'k': ['mnk'],
 'l': ['mnlwnd', 'mnl-2', 'mnl48', 'mnlf', 'mnla', 'mnl'],
 'm': ['mnml', 'mnmg', 'mnm'],
 'n': ['mnng', 'mnnr', 'mnna', 'mnn'],
 'o': ['mnogovershinny',
       'mnogoozyorny',
       'mnogosearch',
       'mnogotochie',
       'mnouchkine',
       'mnopedia',
       'mnong',
       'mno4-',
       'mno4',
       'mno2',
       'mnos',
       'mno'],
 'p': ['mnpg', 'mnpo', 'mnp5', 'mnpl', 'mnpp', 'mnp'],
 'q': ['mnquma_local_municipality'],
 'r': ['mnrcs',
       'mnrfu',
       'mnrkr',
       'mnras',
       'mnro',
       'mnru',
       'mnrr',
       'mnrg',
       'mnra',
       'mnr'],
 's': ['mnsd-nassara',
       'mnstc-i',
       'mnsure',
       'mnswa',
       'mnsod',
       'mnshs',
       'mnscu',
       'mnsi',
       'mnsg',
       'mnse',
       'mnst',
       'mnsd',
       'mns'],
 't': ['mntx', 'mntv', 'mntc', 'mnt'],
 'u': ['mnuphorus', 'mnuchin', 'mnu'],
 'w': ['mnwg', 'mnw'],
 'x': ['mnx1', 'mnx'],
 'y': ['mnyamawamtuka', 'mnyenzeni', 'mnyameni', 'mnynms'],
 'z': ['mnzm', 'mnz']}
