
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_mg = {'_': ['mg-maglificio',
       'mg-technogym',
       'mg-atpase',
       'mg-rover',
       'mg2sio4',
       'mg42/58',
       'mg3o8p2',
       'mg08/15',
       'mg42/59',
       'mg-rast',
       'mg08/18',
       'mg-111',
       'mg2:ss',
       'mg-050',
       'mg-167',
       'mg1a1',
       'mg710',
       'mg2si',
       'mg1a3',
       'mg-34',
       'mg42v',
       'mg-26',
       'mg253',
       'mg-13',
       'mg151',
       'mg-42',
       'mg251',
       'mg132',
       'mg3n2',
       'mg/dl',
       'mg131',
       'mg1a2',
       'mg-15',
       'mg-1',
       'mg42',
       'mg26',
       'mg30',
       'mg08',
       'mg45',
       'mg/l',
       'mg12',
       'mg17',
       'mg81',
       'mg15',
       'mg14',
       'mg34',
       'mg13',
       'mg64',
       'mg51',
       'mg-3',
       'mg07',
       'mg1',
       'mg3',
       'mg5',
       'mg4',
       'mg2',
       'mg6'],
 'a': ['mgaloblishvili',
       'mgambonyi',
       'mgahinga',
       'mgamboni',
       'mgarjes',
       'mgazini',
       'mgange',
       'mgat4b',
       'mgadim',
       'mganga',
       'mgandu',
       'mgat5b',
       'mgarjs',
       'mgarr',
       'mgat3',
       'mgat2',
       'mgat5',
       'mgart',
       'mgat1',
       'mgama',
       'mgac',
       'mga2',
       'mgam',
       'mga'],
 'b': ['mgboko', 'mgbidi', 'mgb-gt', 'mgbgt', 'mgbr2', 'mgb2', 'mgb'],
 'c': ['mgc116892',
       'mgc126724',
       'mgc125976',
       'mgc50722',
       'mgc86987',
       'mgcd0103',
       'mgcis-23',
       'mgc3207',
       'mgcl2',
       'mgco3',
       'mgcu2',
       'mgcn1',
       'mgcp',
       'mgcl',
       'mgc1',
       'mgcn',
       'mgci',
       'mgcc',
       'mgcf',
       'mgc'],
 'd': ['mgd'],
 'e': ['mgeladze', 'mgen', 'mged', 'mgex', 'mge'],
 'f': ['mgfp', 'mgf2', 'mgf'],
 'g': ['mggt', 'mgga', 'mgg'],
 'h': ['mghayreh', 'mghart', 'mghs', 'mgh'],
 'i': ['mgimwa',
       'mgimo',
       'mgims',
       'mgic',
       'mgio',
       'mgi2',
       'mgit',
       'mgip',
       'mgi'],
 'k': ['mgk-264'],
 'l': ['mglinsky',
       'mglur1a',
       'mgl-mk1',
       'mgl-140',
       'mglur5',
       'mglur6',
       'mglur7',
       'mglur1',
       'mglur4',
       'mglurs',
       'mglur3',
       'mglur2',
       'mglur8',
       'mglu4',
       'mglu2',
       'mglur',
       'mglu3',
       'mglin',
       'mglu6',
       'mglu8',
       'mglu7',
       'mgla',
       'mgln',
       'mgll',
       'mgl'],
 'm': ['mgm-52c',
       'mgm-140',
       'mgm-134',
       'mgm/ua',
       'mgm-13',
       'mgm-52',
       'mgm-21',
       'mgm-18',
       'mgm-51',
       'mgm-31',
       'mgm-29',
       'mgm140',
       'mgm-5',
       'mgm-1',
       'mgme1',
       'mgm52',
       'mgma',
       'mgmt',
       'mgm'],
 'n': ['mgn'],
 'o': ['mgovernment',
       'mgombom',
       'mgoszcz',
       'mgocsm',
       'mgongo',
       'mgori',
       'mgo4s',
       'mgowo',
       'mgoh2',
       'mgodi',
       'mgo2',
       'mgos',
       'mgo'],
 'p': ['mgp-84', 'mgpus', 'mgpl', 'mgpu', 'mgp'],
 'r': ['mgres', 'mgr.', 'mgrs'],
 's': ['mgs3:subsistence',
       'mgs4:gotp',
       'mgs2:sol',
       'mgs-0039',
       'mgs/lrs',
       'mgscomm',
       'mgs:tts',
       'mgs3:se',
       'mgs:pw',
       'mgs:po',
       'mgstts',
       'mgspo',
       'mgst2',
       'mgs:4',
       'mgso4',
       'mgs:r',
       'mgsog',
       'mgspw',
       'mgst1',
       'mgst3',
       'mgs:3',
       'mgs:2',
       'mgso3',
       'mgsm',
       'mgsa',
       'mgs3',
       'mgs2',
       'mgsr',
       'mgs5',
       'mgsh',
       'mgs1',
       'mgs4',
       'mgs'],
 't': ['mgtow', 'mgtv', 'mgts', 'mgtt', 'mgtk', 'mgta', 'mgt'],
 'u': ['mgungira', 'mguya', 'mgus', 'mgub', 'mgu'],
 'v': ['mgv-176', 'mgvcl', 'mgv'],
 'w': ['mgwr', 'mgw'],
 'x': ['mgx'],
 'y': ['mgysgt', 'mgy'],
 'z': ['mgz']}
