
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_trie_hc = {'_': ['hc-067047',
       'hc-030031',
       'hc-sdma',
       'hc2h3o2',
       'hc-130p',
       'hc-12a1',
       'hc-130n',
       'hc-144',
       'hc60ng',
       'hc-one',
       'hc-12a',
       'hc-130',
       'hc-256',
       'hc-120',
       'hc-pcf',
       'hc-1b',
       'hc-20',
       'hc-97',
       'hc12',
       'hc-9',
       'hc11',
       'hc-3',
       'hc-4',
       'hc-1',
       'hc08',
       'hc1'],
 'a': ['hcalendar',
       'hcatv',
       'hcafc',
       'hcasc',
       'hcais',
       'hcard',
       'hcac',
       'hcaw',
       'hcap',
       'hca'],
 'b': ['hcbc', 'hcb'],
 'c': ['hccua', 'hccc', 'hcci', 'hcch', 'hccb', 'hccs', 'hcca', 'hcc'],
 'd': ['hcd40l', 'hcdcp', 'hcde', 'hcdr', 'hcd'],
 'e': ['hcentive', 'hcesar', 'hcers', 'hceo', 'hce'],
 'f': ['hcfc-22', 'hcfany', 'hcfcs', 'hcfc1', 'hcfa', 'hcfc', 'hcf'],
 'g': ['hcgardena', 'hcg4p11', 'hcgh', 'hcg'],
 'h': ['hchdonline.com', 'hchr', 'hchc', 'hchd', 'hchs', 'hch'],
 'i': ['hci-rg', 'hcibs', 'hcio4', 'hciaa', 'hcil', 'hcii', 'hcis', 'hci'],
 'j': ['hcjc', 'hcjb', 'hcj'],
 'k': ['hck'],
 'l': ['hclo2',
       'hclo3',
       'hcl-v',
       'hclo4',
       'hcl-j',
       'hcls1',
       'hclo',
       'hcls',
       'hclu',
       'hclm',
       'hcl'],
 'm': ['hcmussh',
       'hcmuns',
       'hcm-6a',
       'hcmos',
       'hcmut',
       'hcms',
       'hcma',
       'hcmv',
       'hcmi',
       'hcm'],
 'n': ['hcn-0.009-0.044',
       'hcnbr',
       'hcng',
       'hcn2',
       'hcn1',
       'hcnm',
       'hcn4',
       'hcnl',
       'hcn3',
       'hcn'],
 'o': ['hcondels',
       'hcooch3',
       'hcooh',
       'hco2h',
       'hcoma',
       'hco-3',
       'hco3-',
       'hco3',
       'hcop',
       'hcoj',
       'hcoh',
       'hco'],
 'p': ['hcpcs', 'hcpa', 'hcps', 'hcp5', 'hcpc', 'hcpt', 'hcpl', 'hcp'],
 'q': ['hcqia'],
 'r': ['hcrp', 'hcrt', 'hcrr', 'hcrs', 'hcri', 'hcrh', 'hcry', 'hcrd', 'hcr'],
 's': ['hcssim',
       'hcs12',
       'hcse',
       'hcso',
       'hcss',
       'hcsa',
       'hcsc',
       'hcsd',
       'hcst',
       'hcsp',
       'hcsb',
       'hcs'],
 't': ['hctra', 'hctv', 'hctm', 'hctz', 'hctu', 'hctc', 'hct'],
 'u': ['hcuav', 'hcu'],
 'v': ['hcvf', 'hcv'],
 'w': ['hcwafc', 'hcw'],
 'y': ['hcy522', 'hcyr', 'hcy'],
 'z': ['hcz']}
