
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_tg = {'tg-10_peregrine': 'blanik_tg-10',
 'tg21_plc': 'tg21',
 'tg_11.2': 'task_force_11',
 'tg_114': 'thai_airways_international_flight_114',
 'tg_261': 'thai_airways_international_flight_261',
 'tg_38.1': 'fast_carrier_task_force',
 'tg_38.2': 'fast_carrier_task_force',
 'tg_38.3': 'fast_carrier_task_force',
 'tg_38.4': 'fast_carrier_task_force',
 'tg_58.1': 'fast_carrier_task_force',
 'tg_58.2': 'fast_carrier_task_force',
 'tg_58.3': 'fast_carrier_task_force',
 'tg_58.4': 'fast_carrier_task_force',
 'tg_bowles': 'thomas_gibson_bowles',
 'tg_grammar': 'transformational_grammar',
 'tg_halli': 'thippagondanahalli_reservoir',
 'tg_hamilton': 'thomas_glendenning_hamilton',
 'tg_jones': 't._g._jones',
 'tg_lee': 't._g._lee_dairy',
 'tg_millner': 't_g_millner_field',
 'tg_rage': 'transgender_day_of_remembrance',
 'tg_sheppard': 't._g._sheppard',
 'tgag_broad': 'tagboard',
 'tgf-beta_1': 'tgf_beta_1',
 'tgf-beta_receptors': 'tgf_beta_receptors',
 'tgf_b': 'tgf_beta',
 'tgfb_receptors': 'tgf_beta_receptors',
 'tgl_series': 'man_se',
 'tgn_1412': 'tgn1412',
 'tgscom_inc.': 'tgscom',
 'tgv_atlantique': 'lgv_atlantique',
 'tgv_cinemas': 'tanjong_golden_village',
 'tgv_duplex': 'sncf_tgv_duplex',
 'tgv_east': 'lgv_est',
 'tgv_est': 'lgv_est',
 'tgv_haute-picardie': 'gare_tgv_haute-picardie',
 'tgv_pbka': 'sncf_tgv_thalys_pbka',
 'tgv_pos': 'sncf_tgv_pos',
 'tgv_pse': 'sncf_tgv_sud-est',
 'tgv_signalling': 'transmission_voie-machine',
 'tgv_sud-est': 'sncf_tgv_sud-est',
 'tgv_tmst': 'british_rail_class_373',
 'tgv_trains': 'tgv'}
        