
#!/usr/bin/env python
# -*- coding: UTF-8 -*-


d_rev_td = {'td1_24679': 'nu_aquilae',
 'td1_25656': 'xi_aquilae',
 'td1_31081': 'ngc_246',
 'td1_816': 'hd_8673',
 'td3n_gorgon': 'td2n_gorgon',
 'td_allman': 't._d._allman',
 'td_bank': 'toronto-dominion_bank',
 'td_barnes': 'timothy_barnes',
 'td_bingham': 'tyler_bingham',
 'td_canada': 'td_canada_trust',
 'td_cars': 'td2000',
 'td_centre': 'toronto-dominion_centre',
 'td_crittenden': 't._d._crittenden',
 'td_jakes': 't._d._jakes',
 'td_judah': 't._d._judah',
 'td_kendrick': 't._d._kendrick',
 'td_lambda': 'temporal_difference_learning',
 'td_learning': 'temporal_difference_learning',
 'td_little': 't._d._little',
 'td_madison': 'tommy_dreamer',
 'td_mischke': 't._d._mischke',
 'td_securities': 'toronto-dominion_bank',
 'td_status': 'tn_status',
 'td_visa': 'tn_status',
 'td_weldon': 'thomas_dewar_weldon',
 'tdbanknorth_center': 'td_banknorth_sports_center',
 'tdbanknorth_garden': 'td_garden',
 'tdc_group': 'tdc_a/s',
 'tdi_kriss': 'tdi_vector',
 'tdk_akita': 'tdk_s.c.',
 'tdk_corp': 'tdk',
 'tdk_corporation': 'tdk',
 'tdk_kabushiki-kaisha': 'tdk',
 'tdk_sc': 'tdk_s.c.',
 'tdl_group': 'tim_hortons',
 'tdm_switch': 'telephone_exchange',
 'tdma_is-136': 'digital_amps',
 'tdp_43': 'tardbp',
 'tdrs_records': 'tdrs_music',
 'tds_2004': 'benjamin_lemaire',
 'tds_metrocom': 'telephone_and_data_systems',
 'tdshop.it_livorno': 'basket_livorno',
 'tdw_nomads': 'nomads_r.f.c.',
 'tdx_power': 'tanadgusix_corporation'}
        